from v8_manual import story, lesson

C = "corpo-umano"

ENTRIES = [
    story(
        C,
        "Perché il cuore batte a sinistra (ma non del tutto)?",
        "Why does the heart beat on the left (but not entirely)?",
        ["cuore", "sinistra"], ["heart", "left"],
        "Metti la mano sul petto e lo senti a sinistra. Eppure il cuore sta quasi al centro. Il trucco è nella sua forma e nel modo in cui batte.",
        "Put a hand on your chest and you feel it on the left. Yet the heart sits almost in the middle. The trick lies in its shape and in how it beats.",
        "Il cuore sta al centro del torace, leggermente ruotato: la punta, che batte più forte, sporge a sinistra ed è quella che sentiamo.",
        "The heart sits in the centre of the chest, slightly rotated: its tip, which beats hardest, points left and that is what we feel.",
        [
            ("Un centro un po' spostato",
             "Se guardi una radiografia del torace, il cuore non è a sinistra: sta dietro lo sterno, quasi in mezzo, appoggiato sul diaframma. Solo una parte, circa due terzi, si estende verso il lato sinistro. Il cuore è grande più o meno come un pugno chiuso e pesa tra i 250 e i 350 grammi. È racchiuso in un sacchetto protettivo, il pericardio, e circondato dai polmoni. La sensazione che stia tutto a sinistra nasce da un dettaglio della sua forma.",
             "A slightly off-centre middle",
             "Look at a chest X-ray and the heart is not on the left: it sits behind the breastbone, almost in the middle, resting on the diaphragm. Only part of it, about two thirds, extends toward the left side. The heart is roughly the size of a clenched fist and weighs between 250 and 350 grams. It is wrapped in a protective sac, the pericardium, and surrounded by the lungs. The feeling that it lives entirely on the left comes from a detail of its shape."),
            ("La punta che spinge",
             "Il cuore ha la forma di un cono rovesciato. La base larga guarda in alto e a destra, la punta, chiamata apice, guarda in basso e a sinistra. A ogni battito il ventricolo sinistro si contrae con forza e l'apice si sposta un poco in avanti, urtando la parete del torace tra la quinta e la sesta costola. È questo colpetto ripetuto che percepiamo con la mano: non il cuore intero, ma la sua estremità più muscolosa e vivace.",
             "The tip that pushes",
             "The heart is shaped like an upside-down cone. The wide base faces up and to the right, while the tip, called the apex, faces down and to the left. With every beat the left ventricle squeezes hard and the apex moves slightly forward, tapping the chest wall between the fifth and sixth ribs. That repeated little knock is what we feel with our hand: not the whole heart, but its most muscular and lively end."),
            ("Il lato dei lavori pesanti",
             "Il cuore è diviso in due metà. La destra riceve il sangue povero di ossigeno e lo spinge ai polmoni, un viaggio breve che richiede poca pressione. La sinistra riceve il sangue ossigenato e deve mandarlo a tutto il corpo, dalla testa ai piedi. Per farlo la parete del ventricolo sinistro è tre volte più spessa di quella destra. Un muscolo più grosso batte con più energia, e la sua forza si sente di più: ecco perché la sinistra sembra dominare.",
             "The heavy-duty side",
             "The heart is divided into two halves. The right receives oxygen-poor blood and pushes it to the lungs, a short trip that needs little pressure. The left receives oxygen-rich blood and must send it around the whole body, from head to toes. To do so, the wall of the left ventricle is three times thicker than the right one. A bigger muscle beats with more energy, and its force is easier to feel: that is why the left seems to dominate."),
            ("Perché non è al centro esatto",
             "Durante lo sviluppo dell'embrione il cuore nasce come un tubicino dritto, in posizione centrale. Verso la quarta settimana il tubo cresce più in fretta di quanto lo spazio permetta e si piega, ruotando verso sinistra. Questa rotazione dipende da geni che stabiliscono la asimmetria destra-sinistra di tutto il corpo, la stessa che mette il fegato a destra e la milza a sinistra. Il risultato è un organo centrale ma inclinato, con la punta che guarda a sinistra.",
             "Why it is not dead centre",
             "During embryonic development the heart begins as a straight little tube, right in the middle. Around the fourth week the tube grows faster than the space allows and folds over, rotating toward the left. This rotation depends on genes that set up the right-left asymmetry of the whole body, the same ones that place the liver on the right and the spleen on the left. The result is a central organ that leans, with its tip pointing left."),
            ("Quando è dall'altra parte",
             "Circa una persona su diecimila nasce con il cuore ruotato verso destra: si chiama dextrocardia. Spesso è accompagnata dal situs inversus, in cui tutti gli organi sono specchiati, e in quel caso la persona vive benissimo senza saperlo, finché una radiografia non lo rivela. Alcuni medici raccontano di aver auscultato a lungo un cuore silenzioso prima di spostare lo stetoscopio a destra. È la prova che la posizione è una convenzione dello sviluppo, non una necessità.",
             "When it sits on the other side",
             "About one person in ten thousand is born with the heart rotated to the right: this is called dextrocardia. It often comes with situs inversus, where every organ is mirrored, and in that case the person lives perfectly well without knowing it, until an X-ray reveals it. Some doctors tell of listening to a strangely silent chest for a long time before moving the stethoscope to the right. It proves that the position is a habit of development, not a necessity."),
            ("Ascoltarlo nel posto giusto",
             "Il medico non appoggia lo stetoscopio a caso. Ogni valvola del cuore si sente meglio in un punto preciso: la valvola aortica in alto a destra dello sterno, la polmonare in alto a sinistra, la mitrale proprio sull'apice, in basso a sinistra. Anche l'elettrocardiogramma segue questa geografia e disegna l'asse elettrico del cuore, che normalmente punta in basso a sinistra. La prossima volta che senti il battito sotto la mano, saprai che stai toccando solo la punta di una storia più grande.",
             "Listening in the right place",
             "A doctor does not place the stethoscope at random. Each heart valve is heard best at a precise spot: the aortic valve high on the right of the breastbone, the pulmonary valve high on the left, the mitral valve right over the apex, low on the left. The electrocardiogram follows the same geography and traces the heart's electrical axis, which normally points down and to the left. Next time you feel the beat under your hand, you will know you are touching only the tip of a bigger story."),
        ],
        ["heart", "pulse", "fitness", "body", "compass", "medkit"],
    ),
    story(
        C,
        "Perché ci vengono le lacrime quando ridiamo?",
        "Why do we cry when we laugh?",
        ["lacrime", "ridere"], ["tears", "laugh"],
        "Una risata fortissima e gli occhi si riempiono. Non è tristezza: è il corpo che perde per un attimo il controllo dei suoi rubinetti.",
        "One huge laugh and your eyes fill up. It is not sadness: it is the body briefly losing control of its taps.",
        "Ridere forte contrae i muscoli del viso, spreme le ghiandole lacrimali e attiva insieme sistema nervoso simpatico e parasimpatico: le lacrime sono il traboccamento.",
        "Hard laughter squeezes the facial muscles and tear glands while firing both branches of the nervous system: the tears are the overflow.",
        [
            ("Tre tipi di lacrime",
             "Non tutte le lacrime sono uguali. Le lacrime basali bagnano l'occhio in continuazione, circa un millilitro al giorno, e lo tengono pulito. Le lacrime riflesse arrivano quando qualcosa irrita l'occhio: fumo, cipolla, vento. Le lacrime emotive nascono da uno stato d'animo intenso e contengono più ormoni dello stress e proteine. Le lacrime da risata sono un caso curioso: hanno qualcosa del riflesso meccanico e qualcosa dell'emozione forte, e per questo confondono anche i ricercatori.",
             "Three kinds of tears",
             "Not all tears are the same. Basal tears wet the eye constantly, about a millilitre a day, and keep it clean. Reflex tears arrive when something irritates the eye: smoke, onion, wind. Emotional tears come from an intense state of mind and contain more stress hormones and proteins. Laughter tears are a curious case: they have something of the mechanical reflex and something of strong emotion, which is why they puzzle researchers too."),
            ("Muscoli che spremono",
             "Quando ridiamo di gusto, il viso si contrae tutto: zigomi, palpebre, guance. Il muscolo orbicolare, che circonda l'occhio, si stringe con forza e schiaccia la ghiandola lacrimale, nascosta sotto l'angolo esterno del sopracciglio. È come premere una spugna bagnata: il liquido che c'è dentro esce. Allo stesso tempo le palpebre socchiuse riducono lo spazio disponibile e i piccoli canali di scarico, vicini al naso, vengono compressi. Il risultato è che le lacrime non hanno dove andare e traboccano.",
             "Muscles that squeeze",
             "When we laugh wholeheartedly, the whole face contracts: cheekbones, eyelids, cheeks. The orbicular muscle around the eye tightens hard and presses on the lacrimal gland, tucked under the outer corner of the eyebrow. It is like squeezing a wet sponge: the liquid inside comes out. At the same time the half-closed lids reduce the available room and the small drainage canals, near the nose, get compressed. The tears have nowhere to go and spill over."),
            ("Due sistemi che si accavallano",
             "Il sistema nervoso autonomo ha due rami. Il simpatico prepara all'azione: accelera il cuore, apre i bronchi, ci fa sudare. Il parasimpatico calma e favorisce le secrezioni, comprese le lacrime. Una risata intensa è un'esperienza strana perché li accende tutti e due insieme: il corpo è eccitato come in un allarme ma sta vivendo qualcosa di piacevole. In questo sovraccarico i segnali si mescolano e la ghiandola lacrimale riceve l'ordine di produrre, anche se non c'è nulla da lavare via.",
             "Two systems that overlap",
             "The autonomic nervous system has two branches. The sympathetic one prepares for action: it speeds the heart, opens the airways, makes us sweat. The parasympathetic one calms us and encourages secretions, including tears. Intense laughter is odd because it switches both on at once: the body is aroused as if in alarm while experiencing something pleasant. In that overload the signals mix, and the tear gland gets the order to produce, even though there is nothing to wash away."),
            ("La stessa porta per due emozioni",
             "Nel cervello, riso e pianto passano da aree vicine. L'ipotalamo regola le risposte emotive e comanda le ghiandole; strutture profonde come il tronco encefalico gestiscono i movimenti automatici di respiro e viso. Quando un'emozione supera una certa intensità, il sistema sembra usare una risposta unica: convulsioni del diaframma, suoni, lacrime. È il motivo per cui una risata sfrenata e un pianto disperato si somigliano da fuori, e perché a volte non sappiamo dire quale dei due stiamo facendo.",
             "The same door for two emotions",
             "In the brain, laughter and crying pass through neighbouring areas. The hypothalamus regulates emotional responses and commands the glands; deep structures like the brainstem handle the automatic movements of breathing and face. When an emotion passes a certain intensity, the system seems to fall back on one shared response: spasms of the diaphragm, sounds, tears. That is why wild laughter and desperate crying look alike from the outside, and why sometimes we cannot tell which one we are doing."),
            ("Una valvola di sicurezza",
             "Alcuni psicologi vedono nelle lacrime da risata un meccanismo di riequilibrio. Un'emozione fortissima, anche positiva, è uno stress per l'organismo: cuore veloce, pressione alta, muscoli tesi. Piangere attiva il rilassamento e riporta il corpo a uno stato di calma, spesso lasciandoci una sensazione di leggerezza. È lo stesso principio della gioia che fa piangere a un matrimonio o all'arrivo di una bella notizia: il cervello usa le lacrime per abbassare il volume quando la musica è troppo alta.",
             "A safety valve",
             "Some psychologists see laughter tears as a rebalancing mechanism. A very strong emotion, even a positive one, is a stress for the body: fast heart, high pressure, tense muscles. Crying switches on relaxation and brings the body back toward calm, often leaving us feeling lighter. It is the same principle as the joy that makes people cry at weddings or on hearing wonderful news: the brain uses tears to turn the volume down when the music is too loud."),
            ("Perché ad alcuni succede sempre",
             "Non tutti piangono ridendo. Conta la forma del viso e la posizione della ghiandola, la quantità di lacrime basali, l'età e la sensibilità del sistema nervoso. Chi ha gli occhi facilmente lucidi al vento o alla luce spesso li ha anche nelle risate. Con gli anni i canali di scarico si restringono e traboccare diventa più facile. E c'è un effetto sociale: ridere fino alle lacrime succede quasi sempre in compagnia, quando ci sentiamo al sicuro abbastanza da lasciarci andare del tutto.",
             "Why it always happens to some people",
             "Not everyone cries when laughing. Face shape and gland position matter, as do the amount of basal tears, age and the sensitivity of the nervous system. People whose eyes water easily in wind or bright light often water when laughing too. With age the drainage canals narrow and overflowing gets easier. There is a social effect as well: laughing to tears almost always happens in company, when we feel safe enough to let go completely."),
        ],
        ["water", "body", "flash", "heart", "shield", "people"],
    ),
    story(
        C,
        "Perché i denti da latte cadono?",
        "Why do baby teeth fall out?",
        ["denti", "latte"], ["baby", "teeth"],
        "Venti denti che nascono, servono qualche anno e poi se ne vanno. Uno spreco? No: un progetto di ingegneria che aspetta la mascella giusta.",
        "Twenty teeth that appear, serve a few years and then leave. A waste? No: an engineering plan waiting for the right jaw.",
        "I denti da latte sono piccoli per una bocca piccola; quando i denti definitivi crescono sotto di loro, ne sciolgono le radici e li spingono fuori.",
        "Baby teeth are small for a small mouth; when the permanent teeth grow beneath them, they dissolve their roots and push them out.",
        [
            ("Una bocca a misura di bambino",
             "Un neonato ha una mascella lunga pochi centimetri. Non c'è spazio per trentadue denti grandi come quelli di un adulto, ma masticare serve presto. La soluzione della natura è una dentatura temporanea: venti denti piccoli, con lo smalto più sottile e le radici corte, che spuntano tra i sei mesi e i tre anni. Servono per mordere, parlare bene e tenere il posto ai successori. Sono chiamati denti da latte perché arrivano quando il bambino è ancora allattato.",
             "A mouth sized for a child",
             "A newborn's jaw is only a few centimetres long. There is no room for thirty-two adult-sized teeth, yet chewing is needed early. Nature's solution is a temporary set: twenty small teeth, with thinner enamel and short roots, appearing between six months and three years of age. They are used for biting, speaking clearly and holding a place for their successors. They are called milk teeth because they arrive while the child is still being nursed."),
            ("I successori aspettano sotto",
             "Mentre il bambino usa i denti da latte, i denti definitivi si stanno già formando dentro la mascella, sotto le radici dei primi. Le loro gemme esistono fin dalla nascita e crescono lentamente per anni, costruendo prima la corona e poi le radici. Le radiografie dei bambini mostrano due file di denti sovrapposte, come un esercito di riserva. Quando la mascella si allunga abbastanza, intorno ai sei anni, i definitivi iniziano a spingere verso l'alto.",
             "The successors wait below",
             "While the child uses the baby teeth, the permanent ones are already forming inside the jaw, beneath the roots of the first set. Their buds exist from birth and grow slowly for years, building the crown first and then the roots. Children's X-rays show two rows of teeth stacked on top of each other, like a reserve army. When the jaw has grown long enough, around age six, the permanent teeth start pushing upward."),
            ("Radici che si sciolgono",
             "Un dente da latte non cade perché si stacca: cade perché perde la radice. Quando il dente definitivo si avvicina, cellule speciali chiamate odontoclasti iniziano a demolire la radice del dente sopra, riassorbendone il tessuto. È un processo lento, che dura mesi, e il bambino non sente nulla. A un certo punto la radice è quasi scomparsa e la corona rimane attaccata solo alle gengive: ecco il dente che dondola, e infine il dente che si stacca con un colpetto.",
             "Roots that dissolve",
             "A baby tooth does not fall out because it comes loose: it falls out because it loses its root. As the permanent tooth approaches, special cells called odontoclasts start demolishing the root of the tooth above, reabsorbing its tissue. It is a slow process lasting months, and the child feels nothing. Eventually the root has almost vanished and the crown hangs only by the gums: that is the wobbly tooth, and finally the tooth that pops out with a nudge."),
            ("L'ordine delle cadute",
             "I denti da latte cadono quasi nello stesso ordine in cui sono spuntati. Prima gli incisivi centrali inferiori, verso i sei anni, poi quelli superiori, i laterali, i primi molari, i canini e infine i secondi molari, intorno ai dodici anni. Nel frattempo spuntano i molari definitivi, che non sostituiscono nessuno: crescono dietro, in uno spazio nuovo creato dalla mascella allungata. I terzi molari, i denti del giudizio, arrivano per ultimi, se arrivano.",
             "The order of the falls",
             "Baby teeth fall out in almost the same order in which they appeared. First the lower central incisors, around age six, then the upper ones, the lateral incisors, the first molars, the canines and finally the second molars, around age twelve. Meanwhile the permanent molars come in, replacing no one: they grow at the back, in new space created by the longer jaw. The third molars, the wisdom teeth, arrive last, if they arrive at all."),
            ("Quando qualcosa va storto",
             "A volte un dente definitivo nasce di lato e non riassorbe la radice giusta: il dente da latte resta lì mentre il nuovo spunta dietro, creando una doppia fila che i dentisti chiamano denti da squalo. In genere si risolve da sola. Altre volte il dente definitivo manca del tutto, un'agenesia, e il dente da latte può restare fino all'età adulta. Se invece un dente da latte cade troppo presto per una carie, gli altri si spostano e chiudono lo spazio, complicando l'arrivo del successore.",
             "When something goes wrong",
             "Sometimes a permanent tooth comes in to one side and does not reabsorb the right root: the baby tooth stays while the new one appears behind it, creating a double row dentists call shark teeth. It usually sorts itself out. Other times the permanent tooth is missing altogether, called agenesis, and the baby tooth can stay into adulthood. If a baby tooth falls out too early because of decay, the others shift and close the gap, making the successor's arrival harder."),
            ("Due dentature, molte storie",
             "Cambiare i denti una sola volta è una caratteristica dei mammiferi. Squali e coccodrilli li sostituiscono per tutta la vita, gli elefanti ne consumano sei serie di molari. L'uomo si ferma a due, perciò curare i denti da latte è importante: una carie non curata può danneggiare il definitivo che cresce sotto. Le culture di tutto il mondo hanno inventato riti per il dente caduto, dal topolino alla fatina, che aiutano i bambini a vivere con leggerezza un cambiamento del corpo.",
             "Two sets, many stories",
             "Replacing teeth only once is a mammal trait. Sharks and crocodiles replace them all their lives, and elephants wear through six sets of molars. Humans stop at two, so caring for baby teeth matters: an untreated cavity can damage the permanent tooth growing underneath. Cultures around the world have invented rituals for the fallen tooth, from the little mouse to the tooth fairy, helping children treat a change in their body with lightness."),
        ],
        ["body", "hourglass", "flask", "calendar", "medkit", "star"],
    ),
    lesson(
        C,
        "Leggere le analisi del sangue: 6 valori da conoscere",
        "Reading a blood test: 6 values worth knowing",
        ["analisi", "sangue", "valori"], ["blood", "test", "values"],
        "Il foglio delle analisi non è un enigma. In sei valori imparerai a leggere le righe che contano e a capire cosa chiedere al medico.",
        "A blood test report is not a riddle. In six values you'll learn to read the lines that matter and know what to ask your doctor.",
        "Capirai cosa misurano emoglobina, glicemia, colesterolo, creatinina, transaminasi e TSH, e come interpretare un valore fuori dall'intervallo.",
        "You'll understand what haemoglobin, blood sugar, cholesterol, creatinine, liver enzymes and TSH measure, and how to read an out-of-range value.",
        "Sei valori raccontano ossigeno, zuccheri, grassi, reni, fegato e tiroide: un asterisco non è una diagnosi, ma una domanda da portare al medico.",
        "Six values describe oxygen, sugar, fats, kidneys, liver and thyroid: an asterisk is not a diagnosis, but a question to bring to your doctor.",
        [
            ("1. Come è fatto il foglio",
             "Ogni riga ha tre parti: il nome dell'esame, il tuo risultato e l'intervallo di riferimento, cioè la fascia in cui rientra il 95 per cento delle persone sane. Un asterisco o una freccia segnala un valore fuori fascia. Ricorda due cose. Gli intervalli cambiano da laboratorio a laboratorio, perciò confronta sempre con quelli stampati sul tuo foglio. E un valore appena fuori non è una malattia: per definizione, una persona sana su venti ha almeno un risultato fuori intervallo per puro caso.",
             "1. How the report is laid out",
             "Each line has three parts: the test name, your result and the reference range, the band that 95 percent of healthy people fall into. An asterisk or arrow flags a value outside the band. Remember two things. Ranges vary between laboratories, so always compare with those printed on your own report. And a value just outside is not a disease: by definition, one healthy person in twenty has at least one out-of-range result by pure chance."),
            ("2. Emoglobina: l'ossigeno che viaggia",
             "L'emocromo conta le cellule del sangue. Il valore chiave è l'emoglobina, la proteina dei globuli rossi che trasporta ossigeno: circa 13-17 grammi per decilitro negli uomini, 12-15 nelle donne. Se è bassa si parla di anemia, e i sintomi sono stanchezza, fiato corto, pallore. Le cause più comuni sono carenza di ferro, perdite di sangue o poca vitamina B12. Accanto trovi il volume medio dei globuli rossi: se sono piccoli suggeriscono carenza di ferro, se grandi carenza di vitamine.",
             "2. Haemoglobin: oxygen on the move",
             "The blood count tallies your blood cells. The key value is haemoglobin, the red-cell protein that carries oxygen: roughly 13-17 grams per decilitre in men and 12-15 in women. When it is low we speak of anaemia, with symptoms like tiredness, breathlessness and pallor. The commonest causes are iron deficiency, blood loss or too little vitamin B12. Next to it you will find the mean red-cell volume: small cells suggest iron deficiency, large ones point to vitamin shortages."),
            ("3. Glicemia: lo zucchero a digiuno",
             "La glicemia misura il glucosio nel sangue dopo almeno otto ore senza mangiare. Sotto i 100 milligrammi per decilitro è normale; tra 100 e 125 è una zona di attenzione, spesso chiamata prediabete; da 126 in su, confermato in due occasioni, indica diabete. Un caffè zuccherato la mattina dell'esame può falsare tutto. Se il medico vuole una fotografia più lunga chiede l'emoglobina glicata, che riflette la media degli zuccheri degli ultimi tre mesi ed è il valore più affidabile per seguire il diabete.",
             "3. Blood sugar: fasting glucose",
             "Blood sugar measures glucose after at least eight hours without food. Below 100 milligrams per decilitre is normal; between 100 and 125 is a warning zone often called prediabetes; 126 and above, confirmed on two occasions, indicates diabetes. A sweetened coffee on the morning of the test can distort everything. When the doctor wants a longer picture they order glycated haemoglobin, which reflects the average sugar of the past three months and is the most reliable value for monitoring diabetes."),
            ("4. Colesterolo: buono, cattivo e totale",
             "Il colesterolo totale da solo dice poco. Guarda le sue parti. L'LDL è quello che si deposita nelle arterie: idealmente sotto 115, ma la soglia scende molto per chi ha altri rischi come pressione alta, fumo o diabete. L'HDL è quello protettivo: più alto è, meglio è, sopra 40 negli uomini e 50 nelle donne. I trigliceridi sono un altro grasso, sensibili a zuccheri e alcol, e dovrebbero stare sotto 150. È l'insieme, non un singolo numero, che il medico usa per stimare il rischio del cuore.",
             "4. Cholesterol: good, bad and total",
             "Total cholesterol on its own says little. Look at its parts. LDL is the kind that settles in the arteries: ideally below 115, but the threshold drops a lot for people with other risks such as high blood pressure, smoking or diabetes. HDL is the protective kind: the higher the better, above 40 in men and 50 in women. Triglycerides are another fat, sensitive to sugar and alcohol, and should stay below 150. It is the whole picture, not one number, that the doctor uses to estimate heart risk."),
            ("5. Creatinina e transaminasi: reni e fegato",
             "La creatinina è uno scarto dei muscoli che i reni filtrano via. Se sale, i reni faticano; dal suo valore il laboratorio calcola la velocità di filtrazione, che dovrebbe superare 90 e non scendere sotto 60. Le transaminasi, indicate come ALT e AST, sono enzimi che escono dalle cellule del fegato quando soffrono. Valori alti possono dipendere da alcol, fegato grasso, virus o farmaci. Un aumento passeggero dopo una settimana di eccessi o uno sforzo intenso è comune e spesso rientra da solo.",
             "5. Creatinine and liver enzymes: kidneys and liver",
             "Creatinine is a muscle waste product that the kidneys filter out. When it rises, the kidneys are struggling; from its value the lab calculates the filtration rate, which should be above 90 and not drop below 60. The transaminases, shown as ALT and AST, are enzymes that leak out of liver cells when they are suffering. High values can come from alcohol, fatty liver, viruses or medications. A temporary rise after a week of excess or a hard workout is common and often settles on its own."),
            ("6. TSH e il colloquio con il medico",
             "Il TSH è l'ormone che comanda la tiroide. Se è alto la tiroide lavora poco e ci si sente stanchi, infreddoliti, con la tendenza a ingrassare; se è basso lavora troppo, con cuore veloce, nervosismo e perdita di peso. L'intervallo tipico va da 0,4 a 4. Prima della visita, segna i valori fuori fascia e prepara tre domande: è un dato da ripetere, da approfondire o da ignorare? Portare le analisi precedenti aiuta: la tendenza nel tempo dice più di un singolo numero.",
             "6. TSH and the conversation with your doctor",
             "TSH is the hormone that drives the thyroid. When it is high the thyroid is underworking and you feel tired, cold and prone to weight gain; when low the thyroid is overworking, with a racing heart, nervousness and weight loss. The typical range runs from 0.4 to 4. Before the appointment, mark the out-of-range values and prepare three questions: is this a result to repeat, to investigate or to ignore? Bring your previous tests too: the trend over time says more than any single number."),
        ],
        ["book", "heart", "nutrition", "pulse", "medkit", "chatbubbles"],
    ),
    lesson(
        C,
        "Come funzionano i vaccini, spiegato passo per passo",
        "How vaccines work, step by step",
        ["vaccini", "anticorpi", "memoria"], ["vaccines", "antibodies", "memory"],
        "In sei passi vedrai cosa succede nel tuo corpo dopo una puntura: un allenamento del sistema immunitario, senza il rischio della partita vera.",
        "In six steps you'll see what happens in your body after a jab: a training session for the immune system, without the risk of the real match.",
        "Capirai come un vaccino insegna al sistema immunitario a riconoscere un microbo, perché servono i richiami e come si valutano sicurezza ed efficacia.",
        "You'll understand how a vaccine teaches the immune system to recognise a germ, why boosters are needed and how safety and effectiveness are assessed.",
        "Un vaccino mostra al corpo un pezzo innocuo del nemico; il sistema immunitario lo studia, produce anticorpi e conserva cellule della memoria pronte per l'incontro vero.",
        "A vaccine shows the body a harmless piece of the enemy; the immune system studies it, makes antibodies and keeps memory cells ready for the real encounter.",
        [
            ("1. Il sistema immunitario impara",
             "Il corpo ha due linee di difesa. La prima è rapida e generica: pelle, muco, cellule che divorano tutto ciò che sembra estraneo. La seconda è lenta ma precisa: linfociti che riconoscono una molecola specifica del microbo, chiamata antigene, e costruiscono armi su misura. La prima volta che incontra un virus, questa seconda linea ha bisogno di una o due settimane per organizzarsi. Nel frattempo il virus si moltiplica, e ci si ammala. Il vaccino serve a evitare proprio quel ritardo.",
             "1. The immune system learns",
             "The body has two lines of defence. The first is fast and generic: skin, mucus, cells that devour anything that looks foreign. The second is slow but precise: lymphocytes that recognise a specific molecule of the germ, called an antigen, and build tailor-made weapons. The first time it meets a virus, this second line needs one or two weeks to get organised. Meanwhile the virus multiplies, and we fall ill. The whole point of a vaccine is to avoid that delay."),
            ("2. Mostrare il nemico senza il pericolo",
             "Un vaccino contiene l'antigene, o le istruzioni per produrlo, ma non la malattia. Ci sono diversi modi per farlo. Virus inattivati, cioè uccisi, come nell'antipolio iniettabile. Virus attenuati, vivi ma indeboliti, come morbillo e rosolia. Pezzi purificati del microbo, come una proteina o un pezzo del suo involucro, nei vaccini per epatite B e papilloma. E i vaccini a RNA messaggero, che consegnano alle cellule la ricetta per costruire da sole una proteina del virus, che poi viene esposta e riconosciuta.",
             "2. Showing the enemy without the danger",
             "A vaccine contains the antigen, or the instructions to make it, but not the disease. There are several ways to do this. Inactivated viruses, that is killed ones, as in the injectable polio vaccine. Attenuated viruses, alive but weakened, as for measles and rubella. Purified pieces of the germ, such as a protein or part of its coat, in hepatitis B and HPV vaccines. And messenger RNA vaccines, which hand cells the recipe to build one viral protein themselves, which is then displayed and recognised."),
            ("3. Cosa succede nei giorni dopo",
             "Nel punto dell'iniezione le cellule sentinella catturano l'antigene e lo portano ai linfonodi più vicini, che si gonfiano leggermente. Qui i linfociti B che riconoscono quell'antigene si moltiplicano e iniziano a produrre anticorpi, proteine che si attaccano al microbo e lo neutralizzano. I linfociti T imparano a riconoscere le cellule infettate e a distruggerle. Il braccio dolente, la lieve febbre e la stanchezza di uno o due giorni sono i segni di questo lavoro: il sistema immunitario che si mette in moto.",
             "3. What happens in the following days",
             "At the injection site sentinel cells capture the antigen and carry it to the nearest lymph nodes, which swell slightly. There, the B lymphocytes that recognise the antigen multiply and start making antibodies, proteins that latch onto the germ and neutralise it. T lymphocytes learn to spot infected cells and destroy them. The sore arm, mild fever and a day or two of tiredness are the signs of this work: the immune system getting into gear."),
            ("4. La memoria e i richiami",
             "Finita la risposta, la maggior parte dei linfociti muore, ma una parte diventa cellule della memoria e può vivere anni o decenni. Se il vero microbo arriva, queste cellule lo riconoscono in poche ore e producono anticorpi in massa prima che l'infezione prenda piede. La memoria però non è sempre uguale: per alcune malattie basta una dose, per altre la risposta si rafforza con dosi ripetute a distanza di settimane o mesi. I richiami servono a rinfrescare la memoria quando gli anticorpi calano, o quando il virus cambia, come per l'influenza.",
             "4. Memory and boosters",
             "Once the response is over, most lymphocytes die, but some become memory cells and can live for years or decades. If the real germ arrives, these cells recognise it within hours and mass-produce antibodies before the infection takes hold. Memory is not always the same, though: for some diseases one dose is enough, for others the response strengthens with repeated doses weeks or months apart. Boosters refresh the memory when antibodies wane, or when the virus changes, as with influenza."),
            ("5. Come si misura sicurezza ed efficacia",
             "Prima di essere approvato, un vaccino passa tre fasi di studi: su poche decine di volontari per la sicurezza, su centinaia per la dose giusta, su decine di migliaia per confrontare vaccinati e non vaccinati. L'efficacia si esprime in percentuale: un'efficacia del 90 per cento significa che tra i vaccinati i casi sono il 90 per cento in meno rispetto ai non vaccinati. Dopo l'approvazione la sorveglianza continua e raccoglie ogni effetto sospetto, così da individuare eventi rari che gli studi non potevano vedere.",
             "5. How safety and effectiveness are measured",
             "Before approval, a vaccine goes through three phases of trials: a few dozen volunteers for safety, hundreds for the right dose, tens of thousands to compare vaccinated and unvaccinated people. Effectiveness is given as a percentage: 90 percent effectiveness means that among the vaccinated there are 90 percent fewer cases than among the unvaccinated. After approval, surveillance continues and collects every suspected effect, so that rare events the trials could not see are detected."),
            ("6. Immunità di gruppo",
             "Un vaccino protegge chi lo riceve, ma anche chi non può riceverlo: neonati, persone in chemioterapia, chi ha allergie gravi. Se abbastanza persone sono immuni, il microbo non trova ospiti a cui passare e le catene di contagio si spezzano. La soglia dipende da quanto è contagiosa la malattia: per il morbillo serve circa il 95 per cento della popolazione. È così che il vaiolo è stato cancellato dal mondo nel 1980 e la polio è quasi sparita. La protezione, in fondo, è un gesto collettivo.",
             "6. Herd immunity",
             "A vaccine protects the person who receives it, but also those who cannot: newborns, people on chemotherapy, those with severe allergies. If enough people are immune, the germ finds no hosts to pass to and chains of infection break. The threshold depends on how contagious the disease is: for measles about 95 percent of the population is needed. That is how smallpox was wiped from the world in 1980 and polio has almost vanished. Protection, in the end, is a collective act."),
        ],
        ["shield", "flask", "pulse", "time", "trophy", "people"],
    ),
    lesson(
        C,
        "Il sistema nervoso: come un pensiero muove una mano",
        "The nervous system: how a thought moves a hand",
        ["neuroni", "cervello", "movimento"], ["neurons", "brain", "movement"],
        "Decidi di prendere una tazza e la mano si muove. In mezzo ci sono miliardi di cellule e qualche decimo di secondo. Seguiamo il viaggio.",
        "You decide to pick up a cup and your hand moves. In between lie billions of cells and a few tenths of a second. Let's follow the journey.",
        "Capirai come un'intenzione nasce nel cervello, viaggia lungo il midollo e i nervi come impulso elettrico e diventa contrazione muscolare, con il feedback che corregge il gesto.",
        "You'll understand how an intention arises in the brain, travels down the spinal cord and nerves as an electrical impulse and becomes muscle contraction, with feedback correcting the movement.",
        "Un pensiero diventa movimento passando da corteccia motoria, midollo spinale e nervi fino al muscolo, mentre i sensi rimandano informazioni per correggere il gesto in tempo reale.",
        "A thought becomes movement by passing from the motor cortex through the spinal cord and nerves to the muscle, while the senses send information back to correct the gesture in real time.",
        [
            ("1. La cellula che parla a scintille",
             "Il neurone è la cellula base del sistema nervoso. Ha un corpo, tanti rami corti chiamati dendriti che ricevono segnali, e un ramo lungo, l'assone, che li trasmette. Il segnale è un impulso elettrico: una piccola onda di ioni che percorre l'assone fino a 120 metri al secondo. Alla fine dell'assone c'è la sinapsi, uno spazio minuscolo in cui il neurone rilascia molecole, i neurotrasmettitori, che accendono o frenano il neurone successivo. Ne abbiamo circa 86 miliardi, collegati da migliaia di miliardi di sinapsi.",
             "1. The cell that speaks in sparks",
             "The neuron is the basic cell of the nervous system. It has a body, many short branches called dendrites that receive signals, and one long branch, the axon, that transmits them. The signal is an electrical impulse: a small wave of ions running along the axon at up to 120 metres per second. At the end of the axon lies the synapse, a tiny gap where the neuron releases molecules, neurotransmitters, that switch the next neuron on or off. We have about 86 billion of them, linked by trillions of synapses."),
            ("2. Dove nasce la decisione",
             "L'intenzione di afferrare la tazza prende forma nella corteccia prefrontale e nelle aree premotorie, che pianificano il gesto: dove è la tazza, quanto è lontana, come va impugnata. Il piano passa alla corteccia motoria primaria, una striscia in cima al cervello che contiene una mappa del corpo: a ogni zona corrisponde una parte, con mani e viso molto più rappresentati di schiena e gambe. I neuroni della zona della mano si accendono e inviano l'ordine verso il basso.",
             "2. Where the decision is born",
             "The intention to grasp the cup takes shape in the prefrontal cortex and premotor areas, which plan the gesture: where the cup is, how far, how to hold it. The plan passes to the primary motor cortex, a strip across the top of the brain containing a map of the body: each zone matches a part, with hands and face far more represented than back and legs. The neurons in the hand zone fire and send the order downward."),
            ("3. La discesa lungo il midollo",
             "Gli assoni dei neuroni motori scendono dal cervello attraverso il tronco encefalico, dove la maggior parte incrocia il lato: l'emisfero sinistro comanda la mano destra e viceversa. Poi corrono nel midollo spinale, il cavo protetto dalle vertebre, fino al segmento del collo che governa il braccio. Qui fanno sinapsi con un secondo neurone, il motoneurone, il cui assone esce dalla colonna, si unisce ad altri in un nervo e raggiunge il muscolo. Il tutto avviene in circa venti millesimi di secondo.",
             "3. The descent along the spinal cord",
             "The axons of the motor neurons descend from the brain through the brainstem, where most of them cross sides: the left hemisphere controls the right hand and vice versa. They then run down the spinal cord, the cable protected by the vertebrae, to the neck segment that governs the arm. There they synapse with a second neuron, the motor neuron, whose axon leaves the spine, bundles with others into a nerve and reaches the muscle. All of this takes about twenty thousandths of a second."),
            ("4. L'impulso diventa forza",
             "Dove il nervo tocca il muscolo c'è la giunzione neuromuscolare. L'impulso fa rilasciare acetilcolina, che si lega alla fibra muscolare e scatena al suo interno un'ondata di calcio. Il calcio permette a due proteine, actina e miosina, di agganciarsi e scorrere l'una sull'altra: la fibra si accorcia. Migliaia di fibre che si accorciano insieme accorciano il muscolo, che tira il tendine e muove l'osso. Per un gesto delicato il cervello recluta poche fibre; per sollevare un peso, quasi tutte.",
             "4. The impulse becomes force",
             "Where the nerve touches the muscle lies the neuromuscular junction. The impulse releases acetylcholine, which binds to the muscle fibre and triggers a wave of calcium inside it. Calcium lets two proteins, actin and myosin, hook together and slide over each other: the fibre shortens. Thousands of fibres shortening together shorten the muscle, which pulls the tendon and moves the bone. For a delicate gesture the brain recruits few fibres; to lift a weight, almost all of them."),
            ("5. Il ritorno: sentire quello che fai",
             "Il movimento non è un ordine a senso unico. Nei muscoli, nei tendini e nella pelle ci sono recettori che misurano allungamento, tensione e contatto, e rimandano al midollo e al cervello un flusso continuo di informazioni. Il cervelletto confronta il movimento previsto con quello reale e corregge in corsa: se la tazza è più pesante del previsto, aumenta la forza prima che ti cada. Gli occhi guidano l'avvicinamento. Questa sensazione del proprio corpo nello spazio si chiama propriocezione, ed è il motivo per cui puoi toccarti il naso a occhi chiusi.",
             "5. The return trip: feeling what you do",
             "Movement is not a one-way order. In muscles, tendons and skin there are receptors that measure stretch, tension and contact, sending a continuous stream of information back to the spinal cord and brain. The cerebellum compares the intended movement with the real one and corrects on the fly: if the cup is heavier than expected, it boosts the force before it slips. The eyes guide the approach. This sense of your own body in space is called proprioception, and it is why you can touch your nose with your eyes closed."),
            ("6. Riflessi, abitudini e allenamento",
             "Alcuni movimenti saltano il cervello: quando tocchi una pentola bollente, il midollo fa ritirare la mano prima ancora che tu senta il dolore. Altri, come camminare o scrivere, con la pratica passano dalla corteccia a circuiti più profondi, i gangli della base, e diventano automatici. È così che un pianista non pensa a ogni dito. Ogni ripetizione rinforza le sinapsi coinvolte e riveste gli assoni di mielina, che accelera l'impulso. Imparare un gesto, in fondo, è ricablare un pezzo di te.",
             "6. Reflexes, habits and training",
             "Some movements skip the brain: when you touch a boiling pot, the spinal cord pulls your hand back before you even feel the pain. Others, like walking or writing, move with practice from the cortex to deeper circuits, the basal ganglia, and become automatic. That is how a pianist does not think about each finger. Every repetition strengthens the synapses involved and wraps the axons in myelin, which speeds the impulse. Learning a gesture is, in the end, rewiring a piece of yourself."),
        ],
        ["flash", "bulb", "layers", "fitness", "eye", "trophy"],
    ),
    lesson(
        C,
        "Camminare bene: quanto, come e perché conta",
        "Walking well: how much, how and why it matters",
        ["camminare", "passi", "salute"], ["walking", "steps", "health"],
        "Il farmaco più economico del mondo è una camminata. In sei passi scoprirai quanto basta, come farla meglio e cosa cambia nel corpo.",
        "The cheapest medicine in the world is a walk. In six steps you'll learn how much is enough, how to do it better and what changes inside your body.",
        "Capirai quanti passi servono davvero, come migliorare postura e ritmo, e quali effetti misurabili ha camminare su cuore, umore e longevità.",
        "You'll understand how many steps really matter, how to improve posture and pace, and what measurable effects walking has on heart, mood and longevity.",
        "Bastano 7-8 mila passi al giorno, con tratti a ritmo svelto, postura dritta e scarpe giuste, per ridurre in modo misurabile il rischio di malattie e migliorare umore e sonno.",
        "Around 7-8 thousand steps a day, with brisk stretches, upright posture and the right shoes, measurably cut disease risk and improve mood and sleep.",
        [
            ("1. Il mito dei diecimila passi",
             "Il numero diecimila non viene dalla medicina ma dal marketing: fu scelto nel 1965 da un'azienda giapponese per lanciare un contapassi, perché l'ideogramma di diecimila somiglia a una persona che cammina. Gli studi recenti raccontano una storia più incoraggiante. Il beneficio maggiore arriva passando da 3-4 mila passi a 7-8 mila: qui il rischio di morte per ogni causa cala di circa il 50 per cento. Oltre, i vantaggi crescono ancora ma più lentamente. Ogni mille passi in più contano, soprattutto per chi parte da poco.",
             "1. The ten-thousand-steps myth",
             "The number ten thousand comes not from medicine but from marketing: it was chosen in 1965 by a Japanese company launching a pedometer, because the character for ten thousand looks like a walking person. Recent studies tell a more encouraging story. The biggest gain comes from moving from 3-4 thousand steps to 7-8 thousand: here the risk of death from any cause drops by about 50 percent. Beyond that, benefits keep growing but more slowly. Every extra thousand steps counts, especially for those starting low."),
            ("2. Il ritmo che fa la differenza",
             "Non tutti i passi sono uguali. Camminare a passo svelto, intorno ai 100 passi al minuto o 5-6 chilometri all'ora, è considerata attività moderata: il respiro accelera ma puoi ancora parlare. Le linee guida chiedono 150 minuti alla settimana di questo tipo di movimento, cioè mezz'ora per cinque giorni. Un trucco semplice è alternare: tre minuti veloci e tre minuti tranquilli. Uno studio giapponese ha mostrato che questo schema migliora pressione e forza delle gambe più della stessa distanza a ritmo costante.",
             "2. The pace that makes the difference",
             "Not all steps are equal. Brisk walking, around 100 steps per minute or 5-6 kilometres an hour, counts as moderate activity: your breathing speeds up but you can still talk. Guidelines call for 150 minutes a week of this kind of movement, that is half an hour on five days. A simple trick is to alternate: three minutes fast, three minutes easy. A Japanese study showed this pattern improves blood pressure and leg strength more than the same distance at a steady pace."),
            ("3. La postura passo dopo passo",
             "Camminare bene comincia dalla testa: sguardo avanti, non sul telefono, mento parallelo al suolo. Spalle rilassate e indietro, non alzate. Braccia che oscillano naturalmente, piegate leggermente, in opposizione alle gambe. Il piede appoggia prima con il tallone, rulla sulla pianta e spinge con le dita. Il passo non deve essere troppo lungo: allungarlo troppo frena e carica le ginocchia. Meglio passi un po' più corti e frequenti. Attiva leggermente gli addominali, come se volessi allontanare l'ombelico dalla cintura.",
             "3. Posture, step by step",
             "Walking well starts at the head: gaze forward, not on your phone, chin parallel to the ground. Shoulders relaxed and back, not hunched. Arms swinging naturally, slightly bent, opposite to the legs. The foot lands heel first, rolls over the sole and pushes off with the toes. Do not overstride: too long a step brakes you and loads the knees. Shorter, more frequent steps are better. Gently engage your abdominals, as if pulling your navel away from your belt."),
            ("4. Cosa succede dentro",
             "Dopo pochi minuti il cuore pompa più sangue, i vasi si dilatano e la pressione, nelle ore successive, tende a scendere. I muscoli assorbono glucosio dal sangue senza bisogno di molta insulina: una camminata di quindici minuti dopo i pasti abbassa i picchi di zucchero. Le ossa, caricate dal peso, si rinforzano. Il cervello riceve più ossigeno e rilascia endorfine; camminare regolarmente riduce i sintomi di ansia e depressione lieve quanto alcuni farmaci. E nelle articolazioni il movimento fa circolare il liquido che nutre la cartilagine.",
             "4. What happens inside",
             "Within a few minutes the heart pumps more blood, vessels widen and blood pressure tends to fall over the following hours. Muscles take up glucose from the blood with little need for insulin: a fifteen-minute walk after meals lowers sugar spikes. Bones, loaded by your weight, get stronger. The brain receives more oxygen and releases endorphins; regular walking reduces symptoms of anxiety and mild depression as much as some medications do. And in the joints, movement circulates the fluid that feeds cartilage."),
            ("5. Scarpe, terreno e piccoli errori",
             "La scarpa giusta ha la suola flessibile davanti, un buon appoggio del tallone e spazio per le dita. Cambiale ogni 800-1000 chilometri: l'ammortizzazione si consuma anche se sembrano intatte. Alternare i terreni aiuta: l'asfalto è veloce, il sentiero allena equilibrio e caviglie, la salita rinforza cuore e glutei. Gli errori più comuni sono partire troppo forte dopo mesi di inattività, ignorare un dolore che dura più di due giorni e camminare sempre sullo stesso lato di una strada inclinata, che nel tempo sbilancia le anche.",
             "5. Shoes, terrain and small mistakes",
             "The right shoe has a flexible sole at the front, good heel support and room for the toes. Replace them every 800-1000 kilometres: the cushioning wears out even if they look intact. Varying terrain helps: asphalt is fast, trails train balance and ankles, hills strengthen heart and glutes. The commonest mistakes are starting too hard after months of inactivity, ignoring a pain that lasts more than two days, and always walking on the same side of a sloped road, which over time unbalances the hips."),
            ("6. Farla diventare un'abitudine",
             "La camminata migliore è quella che fai davvero. Aggancia i passi a qualcosa che fai già: scendere una fermata prima, telefonare camminando, un giro dell'isolato dopo cena. Le camminate brevi ripetute valgono quanto una lunga. Un contapassi o l'orologio aiutano a vedere i progressi, ma non serve inseguire numeri: la regola è aumentare del 10 per cento a settimana. Camminare in compagnia raddoppia la costanza. E la natura aggiunge un bonus: venti minuti in un parco abbassano il cortisolo più della stessa distanza in centro.",
             "6. Turning it into a habit",
             "The best walk is the one you actually take. Attach steps to things you already do: get off one stop early, take phone calls on foot, loop the block after dinner. Short repeated walks are worth as much as one long one. A step counter or watch helps you see progress, but there is no need to chase numbers: the rule is to add 10 percent a week. Walking with someone doubles your consistency. And nature adds a bonus: twenty minutes in a park lowers cortisol more than the same distance downtown."),
        ],
        ["fitness", "time", "body", "heart", "leaf", "calendar"],
    ),
]
