from v8_manual import story, lesson

C = "cultura"

ENTRIES = [
    story(
        C,
        "Perché il caffè si beve al bar e il tè con cerimonia?",
        "Why is coffee drunk at the bar and tea with ceremony?",
        ["caffè", "tè"], ["coffee", "tea"],
        "Un espresso in piedi in trenta secondi, un tè in ginocchio in due ore. Due bevande calde, due modi opposti di stare al mondo.",
        "An espresso standing up in thirty seconds, a tea kneeling for two hours. Two hot drinks, two opposite ways of being in the world.",
        "Il caffè è nato nelle città mercantili come bevanda della conversazione veloce; il tè in Cina e Giappone come pratica di attenzione legata a monaci e corti.",
        "Coffee grew up in trading cities as the drink of quick conversation; tea in China and Japan as a practice of attention tied to monks and courts.",
        [
            ("Due piante, due strade",
             "Il tè arriva dalle foglie di un arbusto della Cina meridionale ed è bevuto da almeno duemila anni. Il caffè nasce dai semi tostati di un frutto etiope e si diffonde solo dal Quattrocento, prima nello Yemen, poi nell'Impero ottomano. Il tè ha avuto secoli per diventare rito, filosofia e poesia. Il caffè è cresciuto in fretta, in un mondo di porti, mercanti e notizie che correvano. Le due bevande hanno assorbito i tempi in cui si sono diffuse.",
             "Two plants, two roads",
             "Tea comes from the leaves of a shrub from southern China and has been drunk for at least two thousand years. Coffee comes from the roasted seeds of an Ethiopian fruit and spread only from the fifteenth century, first in Yemen, then across the Ottoman Empire. Tea had centuries to become ritual, philosophy and poetry. Coffee grew up fast, in a world of ports, merchants and news that travelled quickly. Both drinks absorbed the times in which they spread."),
            ("Il tè dei monaci",
             "In Cina il tè era prima una medicina, poi una bevanda di corte e infine, con i monaci buddhisti, uno strumento di meditazione: teneva svegli e concentrati durante le lunghe sedute. Nel Giappone del Cinquecento il maestro Sen no Rikyu trasformò la preparazione in un'arte, il chanoyu, fondata su quattro principi: armonia, rispetto, purezza e tranquillità. Ogni gesto, dal modo di piegare il tovagliolo al suono dell'acqua, ha una forma precisa. Il tè è un pretesto per stare pienamente presenti.",
             "The monks' tea",
             "In China tea was first a medicine, then a court drink and finally, with Buddhist monks, a tool for meditation: it kept them awake and focused during long sittings. In sixteenth-century Japan the master Sen no Rikyu turned its preparation into an art, chanoyu, built on four principles: harmony, respect, purity and tranquillity. Every gesture, from folding the cloth to the sound of the water, has a precise form. Tea is a pretext for being fully present."),
            ("Il caffè dei mercanti",
             "Le prime caffetterie aprono a Istanbul nel Cinquecento, poi a Venezia nel 1645, a Londra e Parigi pochi anni dopo. Sono luoghi rumorosi dove si leggono giornali, si concludono affari e si discute di politica. A Londra le chiamavano università da un penny: il prezzo di una tazza dava accesso alle conversazioni. La Borsa di Londra e i Lloyd's nacquero in caffetterie. Il caffè è diventato la bevanda del pensiero rapido e dello scambio, l'opposto della contemplazione silenziosa.",
             "The merchants' coffee",
             "The first coffee houses opened in Istanbul in the sixteenth century, then Venice in 1645, London and Paris a few years later. They were noisy places where people read newspapers, closed deals and argued about politics. In London they were called penny universities: the price of a cup bought access to the conversations. The London Stock Exchange and Lloyd's were born in coffee houses. Coffee became the drink of quick thinking and exchange, the opposite of silent contemplation."),
            ("L'Italia e l'espresso",
             "L'espresso è un'invenzione industriale: la prima macchina a vapore è del 1884, quella a leva che crea la crema del 1948. Nasce per servire in fretta gli operai e gli impiegati delle città in crescita. Il caffè al banco, in piedi, costa meno perché occupa il locale per un minuto. La legge italiana ha a lungo fissato un prezzo calmierato per il caffè al banco, rendendolo un rito democratico: lo stesso caffè per il manager e per il muratore, uno accanto all'altro.",
             "Italy and the espresso",
             "Espresso is an industrial invention: the first steam machine dates from 1884, the lever machine that creates the crema from 1948. It was born to serve factory and office workers of growing cities quickly. Coffee at the counter, standing, costs less because it occupies the bar for a minute. Italian law long fixed a controlled price for counter coffee, making it a democratic ritual: the same coffee for the manager and the bricklayer, side by side."),
            ("Anche il tè ha avuto la sua fretta",
             "La cerimonia non è l'unico modo di bere il tè. In Inghilterra il tè delle cinque nasce nell'Ottocento come pausa tra pranzo e cena, con regole di galateo ma ritmo di conversazione. In India il chai si prepara bollito con latte e spezie e si vende a ogni angolo, in bicchierini da bere in un minuto. In Marocco il tè alla menta è ospitalità obbligatoria. In Russia il samovar teneva l'acqua calda tutto il giorno. Ogni cultura ha piegato la pianta ai propri tempi.",
             "Tea has had its hurry too",
             "Ceremony is not the only way to drink tea. In England, afternoon tea appeared in the nineteenth century as a pause between lunch and dinner, with rules of etiquette but a conversational pace. In India, chai is boiled with milk and spices and sold on every corner in small glasses to be drunk in a minute. In Morocco, mint tea is obligatory hospitality. In Russia, the samovar kept water hot all day. Each culture bent the plant to its own rhythms."),
            ("Due modi di fermarsi",
             "Le due bevande contengono la stessa molecola, la caffeina, ma il tè la accompagna con la teanina, che rilassa, e la rilascia più lentamente. Forse anche la chimica ha spinto una verso la calma e l'altra verso l'energia. Oggi le strade si incrociano: le caffetterie lente, con cinque minuti di attesa per una tazza filtrata, imitano il rito del tè; il tè in bottiglia si beve in corsa. Resta la lezione: una pausa può durare trenta secondi o due ore, e in entrambi i casi conta come la vivi.",
             "Two ways of pausing",
             "Both drinks contain the same molecule, caffeine, but tea pairs it with theanine, which relaxes, and releases it more slowly. Perhaps chemistry too pushed one toward calm and the other toward energy. Today the roads cross: slow coffee shops, with a five-minute wait for a filtered cup, imitate the tea ritual; bottled tea is drunk on the run. The lesson remains: a pause can last thirty seconds or two hours, and in both cases what counts is how you live it."),
        ],
        ["leaf", "school", "chatbubbles", "restaurant", "globe", "time"],
    ),
    story(
        C,
        "Da dove viene l'usanza di soffiare le candeline?",
        "Where does blowing out birthday candles come from?",
        ["candeline", "compleanno"], ["candles", "birthday"],
        "Luci accese, un desiderio segreto, un soffio. Un gesto che facciamo ogni anno senza chiederci chi l'ha inventato. La risposta passa da templi, bambini tedeschi e pasticceri.",
        "Lit flames, a secret wish, one breath. A gesture we repeat every year without asking who invented it. The answer passes through temples, German children and bakers.",
        "Le candeline uniscono torte rotonde greche offerte agli dei, il Kinderfest tedesco del Settecento e la pasticceria industriale che rese le torte accessibili a tutti.",
        "Birthday candles combine round Greek cakes offered to the gods, the German Kinderfest of the eighteenth century and industrial baking that made cakes affordable for all.",
        [
            ("Torte per la dea della Luna",
             "Nella Grecia antica si offrivano ad Artemide, dea della Luna, dolci rotondi con candele accese sopra: la forma ricordava il disco lunare e la luce il suo bagliore. Il fumo che saliva verso il cielo portava con sé le preghiere. Non erano compleanni, però. I greci e i romani celebravano il giorno di nascita di dei, imperatori e uomini importanti, quasi mai dei bambini. Il compleanno personale, come lo intendiamo oggi, era un'idea che ancora non esisteva.",
             "Cakes for the goddess of the Moon",
             "In ancient Greece round cakes with lit candles were offered to Artemis, goddess of the Moon: the shape recalled the lunar disc and the light her glow. The smoke rising toward the sky carried prayers with it. These were not birthdays, though. Greeks and Romans celebrated the birth days of gods, emperors and important men, almost never children. The personal birthday, as we understand it today, was an idea that did not yet exist."),
            ("Il Kinderfest tedesco",
             "La festa che riconosciamo nasce in Germania nel Settecento. Il Kinderfest era una giornata dedicata al bambino: al mattino riceveva una torta con tante candeline quanti erano gli anni, più una al centro, la luce della vita, che augurava di arrivare all'anno seguente. Le candele venivano tenute accese tutto il giorno e sostituite quando si consumavano; solo dopo cena il bambino le spegneva, formulava un desiderio e mangiava la torta. Una descrizione del 1746 racconta una festa con una candela per ogni anno.",
             "The German Kinderfest",
             "The party we recognise was born in eighteenth-century Germany. The Kinderfest was a day devoted to the child: in the morning they received a cake with as many candles as their years, plus one in the centre, the light of life, wishing them to reach the next year. The candles were kept burning all day and replaced as they burned down; only after dinner did the child blow them out, make a wish and eat the cake. An account from 1746 describes a party with one candle for each year."),
            ("Il soffio e il segreto",
             "Perché soffiare, e perché in silenzio? L'idea è antica: il fumo porta il desiderio verso il cielo, come le offerte greche, e un voto detto ad alta voce perde potere. Spegnere tutte le candele con un solo soffio è la prova che il desiderio si realizzerà. Alcuni studiosi vedono nel gesto anche una sopravvivenza di credenze sul fuoco che protegge dagli spiriti maligni, comuni nell'Europa contadina. In fondo, è una piccola magia domestica che tutti accettano di credere per un secondo.",
             "The breath and the secret",
             "Why blow, and why in silence? The idea is ancient: smoke carries the wish skyward, like the Greek offerings, and a vow spoken aloud loses its power. Putting out all the candles in one breath is proof that the wish will come true. Some scholars also see in the gesture a survival of beliefs about fire protecting against evil spirits, common in rural Europe. In the end it is a small domestic magic that everyone agrees to believe for one second."),
            ("Da lusso a torta per tutti",
             "Fino all'Ottocento zucchero, farina bianca e burro erano cari, e una torta di compleanno era un privilegio. La rivoluzione industriale cambiò tutto: lo zucchero di barbabietola abbassò i prezzi, i forni domestici migliorarono, il lievito in polvere rese le torte soffici e facili. Le pasticcerie iniziarono a vendere torte pronte e le candeline in scatola arrivarono nei negozi. Verso il 1900 la torta con le candeline era diventata una consuetudine della classe media in Europa e negli Stati Uniti.",
             "From luxury to everyone's cake",
             "Until the nineteenth century sugar, white flour and butter were expensive, and a birthday cake was a privilege. The industrial revolution changed everything: beet sugar lowered prices, home ovens improved, baking powder made cakes light and easy. Bakeries began selling ready-made cakes and boxed candles reached the shops. By 1900 the cake with candles had become a middle-class custom in Europe and the United States."),
            ("Una canzone da brevetto",
             "La colonna sonora arriva per ultima. Nel 1893 due sorelle americane, Patty e Mildred Hill, scrissero Good Morning to All per i bambini dell'asilo. Qualcuno cambiò le parole in Happy Birthday to You e la melodia si diffuse ovunque. Per decenni una casa editrice ne ha rivendicato il diritto d'autore, incassando milioni ogni anno da film e ristoranti, finché nel 2016 un tribunale l'ha dichiarata di pubblico dominio. Oggi è la canzone più cantata del mondo, in decine di lingue.",
             "A song worth a patent",
             "The soundtrack came last. In 1893 two American sisters, Patty and Mildred Hill, wrote Good Morning to All for kindergarten children. Someone changed the words to Happy Birthday to You and the tune spread everywhere. For decades a publisher claimed copyright on it, collecting millions a year from films and restaurants, until in 2016 a court declared it public domain. Today it is the most sung song in the world, in dozens of languages."),
            ("Il rito che resiste",
             "Nel 2017 uno studio ha mostrato che soffiare sulle candeline aumenta i batteri sulla glassa di quattordici volte. La notizia fece il giro del mondo, ma nessuno ha smesso. Il gesto sopravvive perché fa qualcosa che la ragione non può sostituire: raduna le persone che ti vogliono bene intorno a una luce, ferma il tempo per un istante e ti chiede di desiderare qualcosa. È una pausa collettiva mascherata da festa. E il rischio di qualche batterio, tutto sommato, lo accettiamo volentieri.",
             "The ritual that endures",
             "In 2017 a study showed that blowing out candles increases bacteria on the icing fourteen-fold. The news went around the world, but nobody stopped. The gesture survives because it does something reason cannot replace: it gathers the people who love you around a light, stops time for an instant and asks you to wish for something. It is a collective pause disguised as a party. And the risk of a few bacteria, all things considered, we gladly accept."),
        ],
        ["moon", "people", "sparkles", "restaurant", "musical-notes", "heart"],
    ),
    story(
        C,
        "Perché il venerdì si mangia pesce in tanti paesi?",
        "Why is fish eaten on Fridays in so many countries?",
        ["venerdì", "pesce"], ["Friday", "fish"],
        "Dalle mense scolastiche ai menu dei fast food, il venerdì è il giorno del pesce. Dietro c'è una regola religiosa di mille anni e qualche interesse economico.",
        "From school canteens to fast-food menus, Friday is fish day. Behind it lies a thousand-year-old religious rule and a few economic interests.",
        "L'astinenza dalla carne il venerdì, in memoria della morte di Cristo, ha fatto del pesce il piatto del giorno e ha plasmato flotte, mercati e persino il menu di McDonald's.",
        "Abstaining from meat on Fridays, in memory of Christ's death, made fish the dish of the day and shaped fishing fleets, markets and even the McDonald's menu.",
        [
            ("Una regola di penitenza",
             "Per la Chiesa cristiana il venerdì è il giorno della crocifissione, e fin dai primi secoli i fedeli lo osservavano con il digiuno o rinunciando alla carne. La carne degli animali a sangue caldo era considerata un cibo di festa, legato al piacere e alla forza. Il pesce, animale a sangue freddo, non contava come carne. Nel Medioevo la regola si estese a tutti i venerdì dell'anno, alla Quaresima e a molte vigilie: in totale quasi un terzo dei giorni erano di magro.",
             "A rule of penance",
             "For the Christian Church, Friday is the day of the crucifixion, and from the earliest centuries believers marked it by fasting or giving up meat. The flesh of warm-blooded animals was seen as festive food, linked to pleasure and strength. Fish, a cold-blooded animal, did not count as meat. In the Middle Ages the rule extended to every Friday of the year, to Lent and to many vigils: in total, almost a third of the days were lean days."),
            ("Un affare per i pescatori",
             "Milioni di persone che rinunciano alla carne per cento giorni all'anno creano un mercato enorme. Le flotte di aringhe del Mare del Nord e del Baltico fecero la fortuna della Lega Anseatica; il merluzzo salato e lo stoccafisso norvegese viaggiavano fino in Italia e in Spagna. Alcuni storici sostengono che la scoperta dei ricchi banchi di pesce al largo di Terranova, poco dopo Colombo, fu spinta anche dal bisogno di pesce da vendere nei giorni di magro d'Europa.",
             "Good business for fishermen",
             "Millions of people giving up meat for a hundred days a year create an enormous market. The herring fleets of the North Sea and the Baltic made the fortune of the Hanseatic League; Norwegian salt cod and stockfish travelled as far as Italy and Spain. Some historians argue that the discovery of the rich fishing banks off Newfoundland, shortly after Columbus, was also driven by the need for fish to sell on Europe's lean days."),
            ("Trucchi e eccezioni",
             "La definizione di pesce era elastica. Nei monasteri il castoro, che vive in acqua, veniva classificato come pesce, e così alcune anatre e persino il capibara in Sud America, con dispensa papale. In Inghilterra Enrico VIII, rotto con Roma, scoraggiò il pesce e l'industria crollò; il figlio Edoardo dovette reintrodurre i giorni di magro per legge, non per fede ma per salvare i pescatori e la marina, che dalle barche da pesca reclutava i marinai.",
             "Tricks and exceptions",
             "The definition of fish was elastic. In monasteries the beaver, which lives in water, was classified as fish, as were some ducks and even the capybara in South America, with papal dispensation. In England Henry VIII, having broken with Rome, discouraged fish and the industry collapsed; his son Edward had to reintroduce lean days by law, not out of faith but to save the fishermen and the navy, which recruited its sailors from fishing boats."),
            ("Dalla regola all'abitudine",
             "Nel 1966 la Chiesa cattolica ha reso l'astinenza del venerdì obbligatoria solo in Quaresima, lasciando il resto dell'anno alla libera scelta. Ma le abitudini sono più forti delle norme. Le mense delle scuole e delle aziende avevano già il pesce in menu il venerdì, le pescherie ricevevano il pesce fresco per quel giorno, le famiglie avevano le loro ricette. Il venerdì del pesce è sopravvissuto come tradizione culturale anche per chi non frequenta una chiesa.",
             "From rule to habit",
             "In 1966 the Catholic Church made Friday abstinence compulsory only during Lent, leaving the rest of the year to free choice. But habits are stronger than rules. School and company canteens already had fish on the Friday menu, fishmongers received fresh fish for that day, families had their recipes. Fish Friday survived as a cultural tradition even for those who never set foot in a church."),
            ("Il panino inventato per il venerdì",
             "Nel 1962 a Cincinnati un franchising McDonald's in un quartiere cattolico vedeva le vendite crollare ogni venerdì. Il gestore, Lou Groen, propose un panino con pesce fritto. La sede centrale era scettica e organizzò una gara con un panino all'ananas: vinse il pesce, e il Filet-O-Fish è ancora oggi nel menu di tutto il mondo. Anche il fish and chips inglese e il baccalà fritto del venerdì nel Sud Italia raccontano la stessa storia: una regola religiosa diventata cucina popolare.",
             "The sandwich invented for Friday",
             "In 1962 a McDonald's franchise in a Catholic neighbourhood of Cincinnati saw sales collapse every Friday. The manager, Lou Groen, proposed a fried fish sandwich. Headquarters was sceptical and set up a contest against a pineapple sandwich: the fish won, and the Filet-O-Fish is still on menus worldwide today. English fish and chips and the fried salt cod of Fridays in southern Italy tell the same story: a religious rule turned into popular cooking."),
            ("Cosa ci insegna un piatto",
             "Il pesce del venerdì mostra quanto le abitudini alimentari siano stratificate: un precetto spirituale, un interesse economico, la disponibilità del cibo e la forza della ripetizione settimanale. Regole simili esistono in tutte le culture, dal digiuno di Ramadan al kosher ebraico ai lunedì vegetariani di oggi. Ogni volta un limite a tavola diventa un ritmo condiviso che scandisce la settimana. La prossima volta che vedi il pesce nel menu del venerdì, saprai che stai mangiando mille anni di storia.",
             "What a dish teaches us",
             "Fish Friday shows how layered eating habits are: a spiritual precept, an economic interest, the availability of food and the power of weekly repetition. Similar rules exist in every culture, from the Ramadan fast to Jewish kosher laws to today's meat-free Mondays. Each time, a limit at the table becomes a shared rhythm that marks the week. Next time you see fish on a Friday menu, you will know you are eating a thousand years of history."),
        ],
        ["fish", "boat", "book", "calendar", "restaurant", "globe"],
    ),
    story(
        C,
        "Perché il bianco è il colore delle spose (solo da poco)?",
        "Why is white the bridal colour (only recently)?",
        ["bianco", "spose"], ["white", "brides"],
        "Sembra una tradizione eterna. Invece l'abito bianco ha meno di due secoli, e lo dobbiamo a una regina che voleva far lavorare i suoi merlettai.",
        "It seems an eternal tradition. Yet the white dress is less than two centuries old, and we owe it to a queen who wanted to give her lacemakers work.",
        "Fino all'Ottocento le spose portavano l'abito migliore, di qualsiasi colore; il bianco si impose dopo il matrimonio della regina Vittoria nel 1840, grazie a stampa, fotografia e industria.",
        "Until the nineteenth century brides wore their best dress in any colour; white took over after Queen Victoria's wedding in 1840, thanks to the press, photography and industry.",
        [
            ("Il vestito migliore, di ogni colore",
             "Per secoli una sposa indossava semplicemente il suo abito più bello, che poi avrebbe continuato a usare. Le contadine sceglievano colori scuri e resistenti, come il blu, il marrone o il nero, che non mostravano le macchie. Le nobili preferivano il rosso, il colore più costoso da tingere, oppure l'oro e il porpora, per mostrare la ricchezza della famiglia. Il bianco esisteva, ma era raro: si sporcava subito e non si poteva riutilizzare, un lusso che quasi nessuno poteva permettersi.",
             "The best dress, in any colour",
             "For centuries a bride simply wore her finest dress, which she would go on using afterwards. Peasant women chose dark, hard-wearing colours like blue, brown or black that did not show stains. Noblewomen preferred red, the most expensive colour to dye, or gold and purple, to display the family's wealth. White existed but was rare: it got dirty at once and could not be reused, a luxury almost nobody could afford."),
            ("Una regina e i suoi merlettai",
             "Il 10 febbraio 1840 la regina Vittoria sposò il principe Alberto con un abito di seta bianca coperto di pizzo di Honiton, un paese del Devon la cui industria del merletto era in crisi. La scelta fu anche un gesto politico a favore dei lavoratori inglesi. Vittoria rifiutò il velluto e l'ermellino delle regine precedenti e indossò una corona di fiori d'arancio invece di gioielli. Le incisioni del matrimonio finirono sui giornali di tutta Europa e in America: la moda era lanciata.",
             "A queen and her lacemakers",
             "On 10 February 1840 Queen Victoria married Prince Albert in a white silk dress covered in lace from Honiton, a Devon town whose lace industry was in crisis. The choice was also a political gesture in favour of English workers. Victoria refused the velvet and ermine of previous queens and wore a crown of orange blossom instead of jewels. Engravings of the wedding appeared in newspapers across Europe and America: the fashion was launched."),
            ("Perché proprio il bianco ha attecchito",
             "Le riviste femminili dell'epoca spiegarono il bianco come simbolo di purezza e innocenza, un significato che in realtà prima non aveva: nel Medioevo il colore della purezza era il blu della Madonna. Ma il bianco aveva un altro messaggio, più concreto: dire che la famiglia poteva permettersi un abito da indossare una sola volta. Fu anche la fotografia in bianco e nero, diffusa dagli anni Sessanta dell'Ottocento, a favorirlo, perché la sposa in bianco spiccava nella foto accanto allo sposo in nero.",
             "Why white in particular caught on",
             "Women's magazines of the time explained white as a symbol of purity and innocence, a meaning it had not really carried before: in the Middle Ages the colour of purity was the Virgin's blue. But white had another, more concrete message: it said the family could afford a dress to be worn only once. Black-and-white photography, widespread from the 1860s, also helped, because the bride in white stood out in the picture beside the groom in black."),
            ("Dalle élite a tutti",
             "Per decenni il bianco restò un privilegio. Le spose comuni continuavano con il vestito buono, spesso scuro, fino a metà Novecento. Il cambiamento arrivò con l'industria tessile e i grandi magazzini, che dopo la seconda guerra mondiale offrirono abiti bianchi in serie a prezzi accessibili. Il cinema di Hollywood, con Grace Kelly ed Elizabeth Taylor, fece il resto. Il boom economico rese possibile per la prima volta spendere una somma importante per un abito da usare un solo giorno.",
             "From the elite to everyone",
             "For decades white remained a privilege. Ordinary brides carried on with their good dress, often dark, until the mid-twentieth century. The change came with the textile industry and department stores, which after the Second World War offered mass-produced white gowns at accessible prices. Hollywood cinema, with Grace Kelly and Elizabeth Taylor, did the rest. The post-war boom made it possible for the first time to spend a significant sum on a dress to be worn for a single day."),
            ("Il resto del mondo",
             "In gran parte dell'Asia il bianco è il colore del lutto, non della festa. Le spose cinesi indossano tradizionalmente il rosso, simbolo di fortuna e gioia; quelle indiane il rosso o colori vivaci con ricami d'oro; in Giappone lo shiromuku, un kimono bianco, esisteva già da secoli ma con un significato diverso, la disponibilità della sposa a prendere i colori della nuova famiglia. Oggi molte spose asiatiche cambiano abito durante la festa, uno tradizionale e uno bianco all'occidentale.",
             "The rest of the world",
             "In much of Asia white is the colour of mourning, not celebration. Chinese brides traditionally wear red, a symbol of luck and joy; Indian brides red or vivid colours with gold embroidery; in Japan the shiromuku, a white kimono, had existed for centuries but with a different meaning, the bride's readiness to take on the colours of her new family. Today many Asian brides change during the celebration, one traditional dress and one Western-style white gown."),
            ("Una tradizione giovane",
             "L'abito bianco insegna come nascono le tradizioni: un gesto di una persona molto visibile, un mezzo di comunicazione che lo diffonde, un'industria che lo rende accessibile e una storia che gli dà un significato. In meno di due secoli qualcosa di eccezionale è diventato ovvio. Oggi molte spose scelgono di nuovo il colore, o un abito da riutilizzare, esattamente come facevano le loro antenate. Forse tra cento anni il bianco sembrerà una curiosità dell'epoca vittoriana.",
             "A young tradition",
             "The white dress shows how traditions are born: a gesture by a highly visible person, a medium that spreads it, an industry that makes it affordable and a story that gives it meaning. In less than two centuries something exceptional became obvious. Today many brides are choosing colour again, or a dress they can wear again, exactly as their ancestors did. Perhaps in a hundred years white will look like a curiosity of the Victorian age."),
        ],
        ["color-palette", "star", "camera", "cash", "globe", "heart"],
    ),
    story(
        C,
        "Chi ha deciso che la settimana ha sette giorni?",
        "Who decided the week has seven days?",
        ["settimana", "sette"], ["week", "seven"],
        "Il giorno segue il Sole, il mese la Luna, l'anno le stagioni. La settimana non segue niente. Eppure governa la vita di tutto il pianeta.",
        "The day follows the Sun, the month the Moon, the year the seasons. The week follows nothing at all. Yet it rules the life of the whole planet.",
        "La settimana di sette giorni nasce a Babilonia dalle fasi lunari e dai sette pianeti visibili, passa per il sabato ebraico e viene imposta all'impero da Costantino nel 321.",
        "The seven-day week arose in Babylon from lunar phases and the seven visible planets, passed through the Jewish Sabbath and was imposed on the empire by Constantine in 321.",
        [
            ("Un ciclo che non esiste in natura",
             "Nessun fenomeno astronomico dura sette giorni. La Luna compie il suo ciclo in circa 29 giorni e mezzo, che divisi per quattro fanno sette e un po'. Per questo i Babilonesi, grandi osservatori del cielo, segnavano un giorno speciale ogni sette, in corrispondenza approssimativa delle fasi lunari, e lo consideravano un giorno sfavorevole in cui non iniziare imprese. Ma il conto non tornava mai esattamente: ogni mese dovevano aggiungere un giorno o due di aggiustamento.",
             "A cycle that does not exist in nature",
             "No astronomical phenomenon lasts seven days. The Moon completes its cycle in about 29 and a half days, which divided by four gives seven and a bit. That is why the Babylonians, great sky watchers, marked a special day every seven, roughly matching the lunar phases, and considered it an unlucky day on which not to begin ventures. But the count never came out exactly: each month they had to add a day or two of adjustment."),
            ("Il numero dei pianeti",
             "Il sette era anche il numero dei corpi celesti che si muovono rispetto alle stelle fisse: Sole, Luna, Marte, Mercurio, Giove, Venere e Saturno. Gli astrologi ellenistici, tra il III e il I secolo avanti Cristo, assegnarono a ogni ora del giorno un pianeta e da questo derivarono un pianeta per ogni giorno. Nacque così la settimana planetaria, i cui nomi sopravvivono nelle lingue latine: lunedì dalla Luna, martedì da Marte, mercoledì da Mercurio, giovedì da Giove, venerdì da Venere.",
             "The number of the planets",
             "Seven was also the number of celestial bodies that move against the fixed stars: Sun, Moon, Mars, Mercury, Jupiter, Venus and Saturn. Hellenistic astrologers, between the third and first centuries BC, assigned a planet to each hour of the day and from this derived a planet for each day. So the planetary week was born, whose names survive in Latin languages: Monday from the Moon, Tuesday from Mars, Wednesday from Mercury, Thursday from Jupiter, Friday from Venus."),
            ("Il sabato che ha rotto il legame con la Luna",
             "Il popolo ebraico fece un passo decisivo: staccò la settimana dal cielo. Nel racconto della Genesi Dio crea il mondo in sei giorni e riposa il settimo, e il sabato diventa un ciclo continuo di sette giorni che non si ferma mai per aggiustarsi alla Luna. È la prima settimana davvero indipendente, fondata su un comandamento e non su un'osservazione. Da qui deriva l'idea di un giorno di riposo obbligatorio, che nessuna civiltà antica aveva avuto in questa forma.",
             "The Sabbath that broke the link with the Moon",
             "The Jewish people took a decisive step: they detached the week from the sky. In the Genesis story God creates the world in six days and rests on the seventh, and the Sabbath becomes a continuous seven-day cycle that never pauses to realign with the Moon. It is the first truly independent week, based on a commandment rather than an observation. From here comes the idea of a compulsory day of rest, which no ancient civilisation had held in this form."),
            ("Roma aveva otto giorni",
             "I Romani per secoli usarono una settimana di otto giorni, il ciclo nundinale, scandito dai giorni di mercato. La settimana di sette giorni arrivò con l'astrologia orientale e con le comunità ebraiche e cristiane, e per un periodo i due sistemi convissero nei calendari. Nel 321 l'imperatore Costantino, da poco convertito, dichiarò la domenica, il giorno del Sole, giorno di riposo per tribunali e botteghe. Da quel momento la settimana di sette giorni divenne legge in tutto l'impero.",
             "Rome had eight days",
             "For centuries the Romans used an eight-day week, the nundinal cycle, marked by market days. The seven-day week arrived with eastern astrology and with Jewish and Christian communities, and for a while the two systems coexisted in calendars. In 321 the emperor Constantine, recently converted, declared Sunday, the day of the Sun, a day of rest for courts and workshops. From then on the seven-day week became law across the empire."),
            ("I tentativi di cambiarla",
             "Nel 1793 la Francia rivoluzionaria introdusse la settimana di dieci giorni, con un solo giorno di riposo: fu odiata e abolita dopo dodici anni. L'Unione Sovietica provò nel 1929 una settimana di cinque giorni con turni di riposo a rotazione, così che le fabbriche non si fermassero mai; le famiglie non riuscivano più a vedersi e nel 1940 si tornò ai sette giorni. Ogni volta la settimana si è dimostrata più forte di chi voleva riformarla, perché è ormai scritta nelle abitudini di tutti.",
             "The attempts to change it",
             "In 1793 revolutionary France introduced a ten-day week with a single day of rest: it was hated and abolished after twelve years. The Soviet Union tried a five-day week in 1929 with rotating days off, so that factories never stopped; families could no longer see each other and in 1940 the seven days returned. Each time the week proved stronger than those who wanted to reform it, because by now it is written into everyone's habits."),
            ("Un ritmo inventato che ci governa",
             "Oggi la settimana è l'unità di tempo più universale: cristiani, ebrei, musulmani, e paesi laici la condividono, anche se il giorno di riposo cambia. Non ha base astronomica, ma ha una base umana: il bisogno di alternare fatica e riposo a un ritmo che il corpo sopporta. Studi recenti mostrano che umore, sonno e persino gli infarti seguono un ciclo settimanale, con il lunedì come giorno peggiore. La settimana è un'invenzione, ma ormai ci scorre nel sangue.",
             "An invented rhythm that governs us",
             "Today the week is the most universal unit of time: Christians, Jews, Muslims and secular countries all share it, even if the day of rest varies. It has no astronomical basis, but it has a human one: the need to alternate effort and rest at a rhythm the body can bear. Recent studies show that mood, sleep and even heart attacks follow a weekly cycle, with Monday as the worst day. The week is an invention, but by now it runs in our blood."),
        ],
        ["moon", "planet", "book", "library", "calendar", "time"],
    ),
    lesson(
        C,
        "Come nasce un dialetto: capire le lingue d'Italia",
        "How a dialect is born: understanding the languages of Italy",
        ["dialetto", "lingua", "latino"], ["dialect", "language", "Latin"],
        "Napoletano, veneto, siciliano: non sono italiano storpiato. In sei passi capirai da dove vengono e perché sono lingue a tutti gli effetti.",
        "Neapolitan, Venetian, Sicilian: they are not broken Italian. In six steps you'll see where they come from and why they are languages in their own right.",
        "Capirai che i dialetti italiani derivano dal latino parlato, non dall'italiano, e come storia, confini e scuola hanno deciso quale variante è diventata lingua nazionale.",
        "You'll understand that Italian dialects descend from spoken Latin, not from Italian, and how history, borders and schooling decided which variety became the national language.",
        "I dialetti sono sorelle dell'italiano, nate dal latino parlato in modo diverso in ogni regione; il toscano è diventato lingua nazionale per prestigio letterario, poi per scuola e televisione.",
        "Dialects are sisters of Italian, born from Latin spoken differently in each region; Tuscan became the national language through literary prestige, then through school and television.",
        [
            ("1. Non figli, ma fratelli",
             "L'errore più comune è pensare che i dialetti siano deformazioni dell'italiano. È il contrario: sono nati prima. Quando l'Impero romano si dissolse, il latino parlato dal popolo continuò a evolversi in ogni regione, lentamente e in modo diverso, senza una scuola che lo tenesse uniforme. Nell'arco di alcuni secoli nacquero decine di parlate: il veneziano, il milanese, il napoletano, il siciliano. Il toscano era una di queste, né più né meno. L'italiano di oggi è il toscano che ha fatto carriera.",
             "1. Not children, but siblings",
             "The commonest mistake is to think dialects are distortions of Italian. It is the other way round: they came first. When the Roman Empire dissolved, the Latin spoken by ordinary people kept evolving in every region, slowly and differently, with no school to keep it uniform. Over a few centuries dozens of tongues arose: Venetian, Milanese, Neapolitan, Sicilian. Tuscan was one of them, no more and no less. Today's Italian is the Tuscan that made a career."),
            ("2. Perché ogni valle parla diverso",
             "Le lingue cambiano quando le persone parlano tra loro e restano stabili dove gli scambi sono frequenti. Nell'Italia medievale montagne, fiumi e confini politici isolavano le comunità: ogni città-stato, ogni feudo aveva la sua parlata. Le popolazioni preromane lasciarono tracce nell'accento, come il celtico nel Nord e l'osco al Sud. Le dominazioni successive aggiunsero parole: l'arabo in Sicilia, il francese in Piemonte, lo spagnolo a Napoli. Il risultato è un mosaico dove a volte bastano dieci chilometri per cambiare vocali.",
             "2. Why every valley speaks differently",
             "Languages change when people talk to one another and stay stable where exchanges are frequent. In medieval Italy mountains, rivers and political borders isolated communities: every city-state, every fief had its own speech. Pre-Roman populations left traces in the accent, such as Celtic in the North and Oscan in the South. Later rulers added words: Arabic in Sicily, French in Piedmont, Spanish in Naples. The result is a mosaic where sometimes ten kilometres are enough to change the vowels."),
            ("3. La linea che divide l'Italia",
             "I linguisti tracciano una linea da La Spezia a Rimini. A nord i dialetti gallo-italici, con tratti simili al francese: le vocali finali cadono, si dice pan invece di pane. A sud le vocali restano, le consonanti raddoppiano, si dice pane con tutte le sue lettere e a Napoli le finali diventano indistinte. Il toscano sta in mezzo e conserva un suono più vicino al latino: è uno dei motivi per cui è stato percepito come più chiaro e più bello. Sardo e friulano, infine, sono lingue a parte, con storie ancora più antiche.",
             "3. The line that divides Italy",
             "Linguists draw a line from La Spezia to Rimini. North of it lie the Gallo-Italic dialects, with traits similar to French: final vowels drop, people say pan instead of pane. South of it vowels stay, consonants double, pane is pronounced with all its letters and in Naples the endings blur. Tuscan sits in between and keeps sounds closer to Latin: one reason it was felt to be clearer and more beautiful. Sardinian and Friulian, finally, are separate languages with even older histories."),
            ("4. Come il toscano ha vinto",
             "Nel Trecento tre scrittori fiorentini, Dante, Petrarca e Boccaccio, produssero opere talmente ammirate che il loro fiorentino divenne il modello per chi voleva scrivere in modo elegante. Nel Cinquecento il veneziano Pietro Bembo lo codificò in grammatica. Per secoli, però, restò una lingua scritta da pochi: nel 1861, all'Unità d'Italia, solo il 2-10 per cento della popolazione lo sapeva parlare. Fu scelto come lingua nazionale per prestigio letterario, non perché fosse il più diffuso.",
             "4. How Tuscan won",
             "In the fourteenth century three Florentine writers, Dante, Petrarch and Boccaccio, produced works so admired that their Florentine became the model for anyone wishing to write elegantly. In the sixteenth century the Venetian Pietro Bembo codified it into a grammar. For centuries, though, it remained a written language known to few: in 1861, at Italian unification, only 2 to 10 percent of the population could speak it. It was chosen as the national language for its literary prestige, not because it was the most widespread."),
            ("5. Scuola, guerra e televisione",
             "Per trasformare una lingua di libri in una lingua parlata da tutti servirono tre forze. La scuola obbligatoria insegnò a leggere e scrivere in italiano. La prima guerra mondiale mise nelle stesse trincee soldati di regioni diverse, costretti a capirsi. E la televisione, dal 1954, portò lo stesso italiano in ogni casa: il maestro Manzi con Non è mai troppo tardi insegnò a leggere a milioni di adulti. In cinquant'anni l'italiano passò da lingua minoritaria a lingua madre della maggioranza.",
             "5. School, war and television",
             "Turning a language of books into one spoken by everyone took three forces. Compulsory schooling taught reading and writing in Italian. The First World War put soldiers from different regions in the same trenches, forced to understand each other. And television, from 1954, brought the same Italian into every home: the teacher Manzi's programme Non è mai troppo tardi taught millions of adults to read. In fifty years Italian went from a minority language to the mother tongue of the majority."),
            ("6. Cosa resta e cosa si perde",
             "Oggi circa un italiano su sette parla soprattutto dialetto in famiglia, contro uno su tre negli anni Novanta. I dialetti si ritirano, ma non muoiono: vivono nella musica, nel cinema, nei social, e colorano l'italiano regionale che tutti parliamo senza accorgercene. L'UNESCO considera molte parlate italiane vulnerabili. Capire che un dialetto è una lingua con la stessa dignità storica dell'italiano cambia lo sguardo: non è ignoranza da correggere, ma un patrimonio di duemila anni che si parla ancora.",
             "6. What remains and what is lost",
             "Today about one Italian in seven speaks mainly dialect at home, against one in three in the 1990s. Dialects are retreating but not dying: they live in music, cinema and social media, and colour the regional Italian we all speak without noticing. UNESCO lists many Italian tongues as vulnerable. Understanding that a dialect is a language with the same historical dignity as Italian changes the way you look at it: not ignorance to be corrected, but a two-thousand-year heritage still being spoken."),
        ],
        ["library", "map", "compass", "book", "school", "chatbubbles"],
    ),
    lesson(
        C,
        "Capire il jazz: 6 cose da ascoltare",
        "Understanding jazz: 6 things to listen for",
        ["jazz", "swing", "improvvisazione"], ["jazz", "swing", "improvisation"],
        "Il jazz sembra caotico solo finché non sai cosa cercare. Sei ascolti guidati e una jam session diventerà una conversazione che puoi seguire.",
        "Jazz only sounds chaotic until you know what to look for. Six guided listens, and a jam session will become a conversation you can follow.",
        "Capirai come è costruito un brano jazz, cosa succede durante un'improvvisazione e come riconoscere swing, tema, soli e dialogo tra musicisti.",
        "You'll understand how a jazz piece is built, what happens during an improvisation and how to recognise swing, theme, solos and the dialogue between players.",
        "Ascolta il ritmo che dondola, il tema iniziale, i soli che lo reinventano, il dialogo tra strumenti, le armonie che colorano e il ritorno finale: il jazz è una conversazione con regole.",
        "Listen for the swinging rhythm, the opening theme, the solos that reinvent it, the dialogue between instruments, the colouring harmonies and the final return: jazz is a conversation with rules.",
        [
            ("1. Il ritmo che dondola",
             "Prima di tutto ascolta i piedi, non le note. Nel jazz il tempo non è diviso in parti uguali: le note vengono spinte leggermente in avanti o trattenute, creando quella sensazione di dondolio che si chiama swing. Il contrabbasso cammina con una nota per battito, il piatto della batteria segna il tempo con un fruscio costante e il charleston scatta sul secondo e sul quarto battito. Prova a battere le mani sul due e sul quattro, non sull'uno: se ti viene naturale, stai già sentendo il jazz.",
             "1. The rhythm that swings",
             "First of all listen with your feet, not your ears. In jazz, time is not divided into equal parts: notes are pushed slightly forward or held back, creating that rocking feeling called swing. The double bass walks with one note per beat, the ride cymbal marks time with a steady shimmer and the hi-hat snaps on the second and fourth beats. Try clapping on two and four, not on one: if it comes naturally, you are already feeling the jazz."),
            ("2. Il tema: la frase da ricordare",
             "Quasi ogni brano comincia con il tema, una melodia riconoscibile di 32 battute, spesso presa da una canzone di Broadway o dal blues. I musicisti la chiamano head. Ascoltala con attenzione: è la mappa di tutto ciò che seguirà. Memorizzane una frase, anche solo l'attacco. Nel corso del brano quella melodia scomparirà, ma la sua struttura armonica resterà sotto, come le fondamenta di una casa di cui si cambia ogni volta la facciata. Alla fine il tema tornerà, e lo riconoscerai come un vecchio amico.",
             "2. The theme: the phrase to remember",
             "Almost every piece begins with the theme, a recognisable melody of 32 bars, often taken from a Broadway song or the blues. Musicians call it the head. Listen closely: it is the map of everything that follows. Memorise one phrase, even just the opening. Over the course of the piece that melody will disappear, but its harmonic structure will stay underneath, like the foundations of a house whose facade changes every time. In the end the theme will return, and you will greet it like an old friend."),
            ("3. I soli: inventare sul momento",
             "Dopo il tema, ogni musicista a turno improvvisa un solo: crea sul momento una nuova melodia sugli stessi accordi del tema, per uno o più giri completi della struttura. Non è caos, è come parlare seguendo una grammatica. Ascolta come il solista inizia con poche note, costruisce tensione, arriva a un punto culminante e poi si calma per passare il testimone. Gli applausi a metà brano, che sorprendono chi non conosce il jazz, arrivano proprio alla fine di ogni solo, per ringraziare chi ha appena raccontato la sua storia.",
             "3. The solos: inventing on the spot",
             "After the theme, each musician in turn improvises a solo: they create a new melody on the spot over the same chords as the theme, for one or more complete passes through the structure. It is not chaos, it is like speaking within a grammar. Listen to how the soloist starts with a few notes, builds tension, reaches a climax and then settles to pass the baton. The applause mid-piece, which surprises newcomers to jazz, comes precisely at the end of each solo, thanking the player who has just told their story."),
            ("4. La conversazione tra strumenti",
             "Mentre uno improvvisa, gli altri non aspettano: rispondono. Il pianista inserisce accordi negli spazi lasciati dal solista, un gioco chiamato comping. Il batterista sottolinea una frase con un colpo di rullante, il contrabbassista cambia il disegno quando la tensione sale. A volte due strumenti si scambiano quattro battute a testa, i trading fours, come una battuta e una risposta. Ascolta un brano concentrandoti solo sul pianoforte dietro il sassofono: scoprirai un secondo discorso che prima non sentivi.",
             "4. The conversation between instruments",
             "While one player improvises, the others do not wait: they answer. The pianist drops chords into the gaps the soloist leaves, a game called comping. The drummer underlines a phrase with a snare hit, the bassist changes the pattern as tension rises. Sometimes two instruments exchange four bars each, trading fours, like a quip and a reply. Listen to a piece focusing only on the piano behind the saxophone: you will discover a second conversation you never heard before."),
            ("5. Le armonie che colorano",
             "Il jazz usa accordi più ricchi della musica pop: alle tre note di base ne aggiunge una quarta, una quinta, a volte una sesta, che danno quel colore dolceamaro tipico. Le note blue, leggermente calanti, vengono dal blues e portano la malinconia. Non serve conoscere la teoria per sentirle: nota quando un accordo ti sembra irrisolto, come una domanda, e quando invece arriva a casa. I musicisti giocano proprio su questa attesa, rimandando la risoluzione o sorprendendoti con una nota che non ti aspettavi.",
             "5. The harmonies that colour",
             "Jazz uses richer chords than pop music: to the three basic notes it adds a fourth, a fifth, sometimes a sixth, giving that typical bittersweet colour. Blue notes, slightly flattened, come from the blues and carry the melancholy. You need no theory to feel them: notice when a chord sounds unresolved, like a question, and when it finally comes home. Musicians play precisely with this expectation, delaying the resolution or surprising you with a note you did not expect."),
            ("6. Da dove partire",
             "Per allenare l'orecchio scegli brani con struttura chiara. Kind of Blue di Miles Davis del 1959 è lento, spazioso e permette di seguire ogni strumento. Take Five di Dave Brubeck fa sentire il tema e i soli in modo evidente. Ella Fitzgerald e Louis Armstrong insieme mostrano come anche la voce improvvisa. Ascolta lo stesso brano due volte: la prima seguendo il solista, la seconda la sezione ritmica. E se puoi, vai a un concerto dal vivo: il jazz è nato per essere visto mentre nasce.",
             "6. Where to start",
             "To train your ear choose pieces with a clear structure. Miles Davis's Kind of Blue from 1959 is slow, spacious and lets you follow every instrument. Dave Brubeck's Take Five makes the theme and solos obvious. Ella Fitzgerald and Louis Armstrong together show how the voice improvises too. Listen to the same piece twice: the first time following the soloist, the second time the rhythm section. And if you can, go to a live concert: jazz was born to be watched while it is being made."),
        ],
        ["musical-notes", "book", "mic", "chatbubbles", "color-palette", "star"],
    ),
    lesson(
        C,
        "Le religioni del mondo in 6 passi: cosa hanno in comune",
        "World religions in 6 steps: what they share",
        ["religioni", "fede", "riti"], ["religions", "faith", "rituals"],
        "Miliardi di persone pregano in modi diversi. In sei passi vedrai la mappa delle grandi religioni e scoprirai quanto si somigliano sotto la superficie.",
        "Billions of people pray in different ways. In six steps you'll see the map of the great religions and discover how alike they are beneath the surface.",
        "Capirai le differenze essenziali tra le grandi religioni del mondo e riconoscerai i sei elementi che quasi tutte condividono: testi, riti, etica, comunità, calendario e ricerca di senso.",
        "You'll understand the essential differences between the world's major religions and recognise the six elements almost all of them share: texts, rituals, ethics, community, calendar and the search for meaning.",
        "Le religioni differiscono su Dio e sull'aldilà, ma condividono libri sacri, riti di passaggio, una regola d'oro, comunità, feste cicliche e un modo di dare senso alla sofferenza.",
        "Religions differ on God and the afterlife, but share sacred books, rites of passage, a golden rule, community, cyclical festivals and a way of making sense of suffering.",
        [
            ("1. La mappa in numeri",
             "Circa otto persone su dieci nel mondo si dichiarano religiose. I cristiani sono circa 2,4 miliardi, divisi tra cattolici, protestanti e ortodossi. I musulmani 1,9 miliardi, sunniti in grande maggioranza e sciiti. Gli induisti 1,2 miliardi, quasi tutti in India. I buddhisti circa 500 milioni, soprattutto in Asia orientale. Gli ebrei sono 15 milioni, pochi ma con un'influenza storica enorme. Poi sikh, religioni tradizionali africane e cinesi, e oltre un miliardo di persone senza religione, in crescita in Europa e Asia orientale.",
             "1. The map in numbers",
             "About eight people in ten worldwide describe themselves as religious. Christians number about 2.4 billion, split between Catholics, Protestants and Orthodox. Muslims 1.9 billion, mostly Sunni with a Shia minority. Hindus 1.2 billion, almost all in India. Buddhists about 500 million, mainly in East Asia. Jews are 15 million, few in number but with enormous historical influence. Then Sikhs, traditional African and Chinese religions, and more than a billion people with no religion, a growing group in Europe and East Asia."),
            ("2. Due grandi famiglie",
             "Un modo semplice per orientarsi è distinguere due radici. Le religioni abramitiche, ebraismo, cristianesimo e islam, nascono in Medio Oriente, credono in un solo Dio creatore, in una rivelazione scritta e in un giudizio finale, e si riconoscono in Abramo come antenato. Le religioni indiane, induismo, buddhismo, giainismo e sikhismo, vedono il tempo come ciclico, credono nella rinascita e nel karma e cercano la liberazione da questo ciclo. Le tradizioni cinesi, come taoismo e confucianesimo, sono più filosofie di armonia che culti di un dio.",
             "2. Two great families",
             "A simple way to find your bearings is to distinguish two roots. The Abrahamic religions, Judaism, Christianity and Islam, arose in the Middle East, believe in a single creator God, in a written revelation and a final judgement, and recognise Abraham as an ancestor. The Indian religions, Hinduism, Buddhism, Jainism and Sikhism, see time as cyclical, believe in rebirth and karma and seek liberation from that cycle. Chinese traditions such as Taoism and Confucianism are more philosophies of harmony than worship of a god."),
            ("3. Libri e maestri",
             "Quasi tutte le religioni si fondano su testi considerati sacri o ispirati: la Torah, la Bibbia, il Corano, i Veda, i sutra buddhisti, il Guru Granth Sahib dei sikh. Questi libri vengono letti, cantati, memorizzati e interpretati da generazioni di studiosi. E quasi tutte hanno una figura fondatrice o un maestro esemplare: Mosè, Gesù, Maometto, il Buddha, Guru Nanak. Studiare una religione comincia sempre da lì: cosa dice il suo libro e come ha vissuto il suo maestro.",
             "3. Books and teachers",
             "Almost every religion rests on texts considered sacred or inspired: the Torah, the Bible, the Quran, the Vedas, the Buddhist sutras, the Sikh Guru Granth Sahib. These books are read, chanted, memorised and interpreted by generations of scholars. And almost all have a founding figure or exemplary teacher: Moses, Jesus, Muhammad, the Buddha, Guru Nanak. Studying a religion always starts there: what its book says and how its teacher lived."),
            ("4. La regola d'oro",
             "Un principio compare, con parole diverse, in praticamente ogni tradizione: tratta gli altri come vorresti essere trattato. Il Vangelo lo dice così; il Talmud ebraico invita a non fare agli altri ciò che è odioso per te; un detto di Maometto afferma che nessuno è credente finché non desidera per il fratello ciò che desidera per sé; il Mahabharata indù e i testi buddhisti e confuciani hanno versioni quasi identiche. Sotto le differenze di dottrina, l'etica di base converge sulla compassione e sulla reciprocità.",
             "4. The golden rule",
             "One principle appears, in different words, in practically every tradition: treat others as you would wish to be treated. The Gospel says it that way; the Jewish Talmud urges you not to do to others what is hateful to you; a saying of Muhammad states that no one is a believer until he wishes for his brother what he wishes for himself; the Hindu Mahabharata and Buddhist and Confucian texts have near-identical versions. Beneath doctrinal differences, basic ethics converge on compassion and reciprocity."),
            ("5. Riti, feste e comunità",
             "Ogni religione scandisce la vita con riti di passaggio, nascita, età adulta, matrimonio, morte, e l'anno con feste che tornano: Pasqua, Ramadan, Diwali, Yom Kippur, Vesak. Molte prevedono un tempo di digiuno o rinuncia e un giorno di riposo. Molte pregano a orari fissi, in una direzione, con il corpo in una postura. Questi gesti ripetuti insieme creano comunità: il senso di appartenere a qualcosa più grande e più antico di sé, che secondo la ricerca è uno dei benefici psicologici più solidi della pratica religiosa.",
             "5. Rituals, festivals and community",
             "Every religion marks life with rites of passage, birth, coming of age, marriage, death, and the year with returning festivals: Easter, Ramadan, Diwali, Yom Kippur, Vesak. Many prescribe a period of fasting or renunciation and a day of rest. Many pray at set hours, facing a direction, with the body in a posture. These gestures repeated together create community: the sense of belonging to something larger and older than oneself, which research finds to be one of the most robust psychological benefits of religious practice."),
            ("6. Dove divergono davvero",
             "Le differenze profonde riguardano tre domande. Quanti dei ci sono, uno, molti o nessuno. Cosa succede dopo la morte, resurrezione, rinascita o dissoluzione. E come si ottiene la salvezza, per fede, per opere, per conoscenza o per grazia. Su queste domande le religioni non sono intercambiabili, e rispettarle significa prenderle sul serio anche nelle differenze. Ma tutte rispondono a un bisogno comune: dare senso alla sofferenza, alla morte e al fatto stesso di esistere. È da lì che conviene partire per capirle.",
             "6. Where they truly diverge",
             "The deep differences concern three questions. How many gods there are, one, many or none. What happens after death, resurrection, rebirth or dissolution. And how salvation is reached, by faith, by works, by knowledge or by grace. On these questions religions are not interchangeable, and respecting them means taking them seriously in their differences too. But all of them answer a shared need: to make sense of suffering, of death and of the very fact of existing. That is where to start if you want to understand them."),
        ],
        ["globe", "layers", "book", "heart", "people", "star"],
    ),
    lesson(
        C,
        "Come si legge un fumetto: la grammatica delle vignette",
        "How to read a comic: the grammar of panels",
        ["fumetto", "vignette", "balloon"], ["comic", "panels", "balloons"],
        "Un fumetto non si guarda: si legge con un linguaggio tutto suo. Sei passi per vedere ciò che l'autore ha nascosto tra una vignetta e l'altra.",
        "A comic is not something you look at: you read it in a language of its own. Six steps to see what the author has hidden between one panel and the next.",
        "Capirai come vignette, spazi bianchi, balloon, onomatopee e composizione della pagina guidano il tempo e le emozioni della lettura, e saprai riconoscere le scelte di un autore.",
        "You'll understand how panels, gutters, balloons, sound effects and page layout steer the pace and emotions of reading, and you'll be able to spot an author's choices.",
        "Il fumetto racconta attraverso vignette e vuoti tra loro; forma dei balloon, lettering, dimensione delle inquadrature e composizione della tavola sono la grammatica che controlla tempo e sentimento.",
        "Comics tell stories through panels and the gaps between them; balloon shapes, lettering, panel size and page layout form the grammar that controls time and feeling.",
        [
            ("1. La vignetta è un'unità di tempo",
             "Ogni riquadro non è solo un'immagine: è un momento. Una vignetta larga e piena di dettagli ti trattiene più a lungo, quindi dilata il tempo della scena. Una vignetta stretta si legge in un istante e accelera. Una sequenza di riquadri uguali e regolari dà un ritmo costante, come un metronomo; un riquadro che rompe la griglia segnala che qualcosa di importante sta succedendo. La forma stessa parla: bordi ondulati indicano un sogno o un ricordo, l'assenza di bordo un tempo sospeso.",
             "1. A panel is a unit of time",
             "Each frame is not just a picture: it is a moment. A wide panel full of detail holds you longer, so it stretches the time of the scene. A narrow panel is read in an instant and speeds things up. A run of identical, regular panels sets a steady rhythm, like a metronome; a panel that breaks the grid signals something important is happening. The shape itself speaks: wavy borders mean a dream or memory, no border at all a suspended time."),
            ("2. Lo spazio bianco fa il lavoro",
             "Il vero segreto del fumetto sta tra le vignette, nello spazio bianco che i disegnatori chiamano gutter. Lì non è disegnato nulla, ma il lettore compie il salto: unisce due immagini e immagina cosa è successo in mezzo. Un uomo alza un'ascia in una vignetta, nella successiva si vede una città di notte con un urlo: il colpo lo hai dato tu, con la mente. Lo studioso Scott McCloud la chiama chiusura. Più le due vignette sono distanti nel tempo o nello spazio, più lavoro fa la tua immaginazione.",
             "2. The white space does the work",
             "The real secret of comics lies between the panels, in the white space cartoonists call the gutter. Nothing is drawn there, but the reader makes the leap: they join two images and imagine what happened in between. A man raises an axe in one panel, the next shows a city at night with a scream: you delivered the blow, in your mind. Scholar Scott McCloud calls this closure. The further apart the two panels are in time or space, the more work your imagination does."),
            ("3. I balloon hanno una voce",
             "La forma della nuvoletta è il tono della voce. Bordo liscio: parlato normale. Bordo frastagliato: grido. Nuvoletta fatta di bolle: pensiero. Tratteggiata: sussurro. Squadrata con angoli: voce da radio, telefono o robot. Anche la coda conta: indica chi parla e con quale intensità. Dentro il balloon, il lettering è un secondo strumento: caratteri grandi e in grassetto sono un urlo, piccoli e sottili un mormorio, tremolanti la paura. Un buon letterista fa sentire la voce dei personaggi senza che tu te ne accorga.",
             "3. Balloons have a voice",
             "The shape of the speech bubble is the tone of voice. Smooth outline: normal speech. Jagged outline: a shout. A bubble made of little bubbles: a thought. Dashed: a whisper. Squared with sharp corners: a voice from radio, phone or robot. The tail matters too: it shows who is speaking and how forcefully. Inside the balloon, lettering is a second instrument: large bold letters are a yell, small thin ones a murmur, shaky ones fear. A good letterer makes you hear the characters' voices without your noticing."),
            ("4. I suoni che si vedono",
             "Le onomatopee, bang, splash, crash, sono l'unico caso in cui il suono si disegna. Il loro aspetto è il volume: lettere enormi e spigolose per un'esplosione, lettere morbide che si dissolvono per un fruscio. I fumetti giapponesi le usano in modo raffinato, con suoni anche per il silenzio o lo sguardo. Ci sono poi i segni convenzionali che i lettori imparano senza studiarli: le linee di movimento dietro un corpo che corre, le goccioline di sudore per l'imbarazzo, la lampadina dell'idea, le stelline del dolore.",
             "4. Sounds you can see",
             "Onomatopoeia, bang, splash, crash, is the one case where sound is drawn. Its appearance is its volume: huge angular letters for an explosion, soft letters dissolving away for a rustle. Japanese comics use them with great refinement, with sounds even for silence or a stare. Then there are the conventional signs readers learn without studying them: motion lines behind a running body, sweat droplets for embarrassment, the light bulb of an idea, little stars for pain."),
            ("5. La pagina come un tutto",
             "Prima di leggere le singole vignette, l'occhio vede la tavola intera. Gli autori lo sanno e la compongono come un quadro: una grande immagine in basso a destra è una rivelazione che ti aspetta, perché ci arrivi per ultima; una griglia rigida di nove riquadri comunica ordine o oppressione. Il voltare pagina è uno strumento drammatico: l'ultima vignetta a destra crea l'attesa, la prima della pagina successiva la scioglie. Nei manga si legge da destra a sinistra, e il senso di lettura ribaltato cambia anche il ritmo.",
             "5. The page as a whole",
             "Before reading individual panels, the eye takes in the whole page. Authors know this and compose it like a painting: a large image at the bottom right is a revelation waiting for you, because you reach it last; a rigid nine-panel grid conveys order or oppression. Turning the page is a dramatic device: the last panel on the right creates anticipation, the first on the next page releases it. Manga are read right to left, and the reversed reading direction changes the rhythm too."),
            ("6. Rileggere per vedere",
             "La prova pratica: prendi una pagina che ti è piaciuta e rileggila tre volte. La prima seguendo solo la storia. La seconda contando le vignette e notando dove cambiano dimensione: lì l'autore ha deciso di rallentare o accelerare. La terza coprendo i testi con un dito e chiedendoti se capiresti comunque le emozioni. Il fumetto migliore è quello in cui disegno e parola non si ripetono ma si completano. Da Maus a Persepolis, da Tex a Dylan Dog, la grammatica è la stessa: ora sai vederla.",
             "6. Reread to see",
             "The practical test: take a page you enjoyed and reread it three times. The first time following only the story. The second counting the panels and noting where they change size: that is where the author chose to slow down or speed up. The third covering the text with a finger and asking whether you would still grasp the emotions. The best comics are those where picture and word do not repeat but complete each other. From Maus to Persepolis, from Tex to Dylan Dog, the grammar is the same: now you can see it."),
        ],
        ["image", "layers", "chatbubbles", "flash", "book", "eye"],
    ),
    lesson(
        C,
        "Le feste del calendario: perché cadono quando cadono",
        "Calendar holidays: why they fall when they do",
        ["feste", "calendario", "Pasqua"], ["holidays", "calendar", "Easter"],
        "Natale è sempre il 25 dicembre, Pasqua cambia ogni anno, il Ramadan gira tutto il calendario. Sei passi per capire la logica nascosta delle feste.",
        "Christmas is always 25 December, Easter changes every year, Ramadan drifts around the calendar. Six steps to grasp the hidden logic of holidays.",
        "Capirai perché alcune feste sono fisse e altre mobili, come Sole, Luna e antiche feste pagane hanno fissato le date, e come calcolare la Pasqua.",
        "You'll understand why some holidays are fixed and others move, how Sun, Moon and ancient pagan festivals set the dates, and how Easter is calculated.",
        "Le feste seguono tre calendari, solare, lunare e lunisolare: le fisse marcano solstizi e ricorrenze storiche, le mobili inseguono la Luna, e molte ricoprono antiche feste stagionali.",
        "Holidays follow three calendars, solar, lunar and lunisolar: fixed ones mark solstices and historical anniversaries, movable ones follow the Moon, and many overlay ancient seasonal festivals.",
        [
            ("1. Tre calendari, non uno",
             "Il mondo usa tre modi di contare l'anno. Il calendario solare, il nostro gregoriano, segue le stagioni con 365 giorni e un bisestile ogni quattro anni: le feste fissate su di esso cadono sempre nella stessa data. Il calendario lunare, come quello islamico, conta dodici mesi di Luna, cioè 354 giorni, e ogni anno anticipa di undici giorni rispetto alle stagioni. Il calendario lunisolare, ebraico e cinese, segue la Luna per i mesi ma aggiunge un tredicesimo mese ogni due o tre anni per restare agganciato alle stagioni.",
             "1. Three calendars, not one",
             "The world counts the year in three ways. The solar calendar, our Gregorian one, follows the seasons with 365 days and a leap day every four years: holidays fixed on it always fall on the same date. The lunar calendar, like the Islamic one, counts twelve Moon months, 354 days, and moves eleven days earlier each year relative to the seasons. The lunisolar calendar, Jewish and Chinese, follows the Moon for months but adds a thirteenth month every two or three years to stay hooked to the seasons."),
            ("2. Natale e il solstizio",
             "I Vangeli non dicono quando nacque Gesù. Il 25 dicembre fu scelto a Roma nel IV secolo e coincide con il periodo del solstizio d'inverno, quando i giorni ricominciano ad allungarsi. I Romani celebravano in quei giorni i Saturnali, con regali e banchetti, e il 25 la nascita del Sole Invitto. I popoli del Nord festeggiavano Yule con alberi sempreverdi e fuochi. Il cristianesimo sovrappose la nascita di Cristo, luce del mondo, a una festa della luce che già esisteva: l'abete, il vischio e i regali vengono da lì.",
             "2. Christmas and the solstice",
             "The Gospels do not say when Jesus was born. 25 December was chosen in Rome in the fourth century and coincides with the winter solstice period, when days begin to lengthen again. Romans celebrated the Saturnalia in those days, with gifts and feasts, and on the 25th the birth of the Unconquered Sun. Northern peoples kept Yule with evergreen trees and fires. Christianity overlaid the birth of Christ, light of the world, on a festival of light that already existed: the fir tree, mistletoe and presents come from there."),
            ("3. La Pasqua e la Luna",
             "La Pasqua è mobile perché insegue la Luna. Il concilio di Nicea, nel 325, stabilì che si celebra la prima domenica dopo la prima Luna piena che segue l'equinozio di primavera. Per questo oscilla tra il 22 marzo e il 25 aprile. La regola viene dalla Pasqua ebraica, Pesach, che cade il 14 del mese lunare di Nisan, e Gesù morì proprio in quei giorni. Dalla Pasqua dipendono a catena tutte le altre feste mobili: Carnevale, Quaresima, Ascensione e Pentecoste si contano all'indietro o in avanti da quella domenica.",
             "3. Easter and the Moon",
             "Easter moves because it chases the Moon. The Council of Nicaea, in 325, ruled that it is celebrated on the first Sunday after the first full Moon following the spring equinox. That is why it swings between 22 March and 25 April. The rule comes from the Jewish Passover, Pesach, which falls on the 14th of the lunar month of Nisan, and Jesus died in exactly those days. All other movable feasts hang on Easter in a chain: Carnival, Lent, Ascension and Pentecost are counted backward or forward from that Sunday."),
            ("4. Ramadan, il mese che viaggia",
             "Il calendario islamico è puramente lunare e non aggiunge mai mesi di aggiustamento. Il Ramadan, il mese del digiuno, comincia quando si avvista la nuova Luna e ogni anno arriva undici giorni prima: in trentatré anni compie un giro completo delle stagioni, cadendo a volte nelle notti lunghe d'inverno, a volte nelle giornate infinite dell'estate. Un musulmano di sessant'anni ha digiunato in tutte le stagioni. La festa che lo conclude, Eid al-Fitr, cambia data anche da un paese all'altro, secondo quando la Luna è stata vista.",
             "4. Ramadan, the travelling month",
             "The Islamic calendar is purely lunar and never adds adjustment months. Ramadan, the month of fasting, begins when the new Moon is sighted and each year arrives eleven days earlier: in thirty-three years it completes a full circuit of the seasons, falling sometimes in the long nights of winter, sometimes in the endless days of summer. A sixty-year-old Muslim has fasted in every season. The festival that ends it, Eid al-Fitr, can differ in date even between countries, depending on when the Moon was seen."),
            ("5. Il Capodanno cinese e Diwali",
             "Il Capodanno cinese cade sulla seconda Luna nuova dopo il solstizio d'inverno, tra il 21 gennaio e il 20 febbraio, e apre un anno legato a uno dei dodici animali dello zodiaco. È la migrazione umana più grande del mondo, con centinaia di milioni di persone che tornano a casa. Diwali, la festa indù delle luci, cade sulla Luna nuova tra ottobre e novembre e celebra il ritorno del principe Rama, la vittoria della luce sul buio. Entrambe sono feste lunisolari: cambiano data ma restano nella stessa stagione.",
             "5. Chinese New Year and Diwali",
             "Chinese New Year falls on the second new Moon after the winter solstice, between 21 January and 20 February, and opens a year linked to one of the twelve zodiac animals. It is the largest human migration in the world, with hundreds of millions of people travelling home. Diwali, the Hindu festival of lights, falls on the new Moon between October and November and celebrates the return of Prince Rama, the victory of light over darkness. Both are lunisolar festivals: they change date but stay in the same season."),
            ("6. Le feste inventate dagli Stati",
             "Accanto alle feste religiose ci sono quelle civili, fissate da leggi e quindi sempre nella stessa data. Il 1° maggio ricorda gli scioperi operai di Chicago del 1886. Il 2 giugno in Italia celebra il referendum del 1946 che scelse la Repubblica. Il 25 aprile la Liberazione del 1945. Il 4 luglio americano e il 14 luglio francese sono le rivoluzioni fondatrici. Ogni Stato sceglie cosa ricordare, e le date raccontano che tipo di nazione vuole essere. Guardare il calendario delle feste di un paese è leggere in breve la sua storia e le sue priorità.",
             "6. The holidays invented by states",
             "Alongside religious holidays are civil ones, fixed by law and therefore always on the same date. 1 May recalls the Chicago workers' strikes of 1886. 2 June in Italy celebrates the 1946 referendum that chose the Republic. 25 April marks the Liberation of 1945. The American 4 July and the French 14 July are founding revolutions. Every state chooses what to remember, and the dates reveal what kind of nation it wants to be. Reading a country's holiday calendar is reading its history and priorities in brief."),
        ],
        ["calendar", "sunny", "moon", "star", "sparkles", "map"],
    ),
]
