"""
PAUSE — Seed data (expansion pack).

85 additional curated stories in Italian to reach 100+ total.
Style guideline: 5 chapters, ~80-120 words each, real substantive content
following the "basics → main concept → depth" structure. All in Italian.
"""

GLOWS = ["#00E5FF", "#B200FF", "#FF6D00", "#FF006A", "#00E676"]

def _ch(items):
    out = []
    for i, (title, body, icon) in enumerate(items):
        out.append({
            "number": i + 1,
            "title": title,
            "body": body,
            "icon": icon,
            "glow_color": GLOWS[i % len(GLOWS)],
        })
    return out

# Category meta shortcuts
CAT = {
    "scienza":     ("Scienza",     "planet-outline",         "#00D2FF"),
    "spazio":      ("Spazio",      "rocket-outline",         "#B200FF"),
    "tecnologia":  ("Tecnologia",  "hardware-chip-outline",  "#00E676"),
    "natura":      ("Natura",      "leaf-outline",           "#00E676"),
    "animali":     ("Animali",     "paw-outline",            "#FF9100"),
    "storia":      ("Storia",      "book-outline",           "#FF6D00"),
    "psicologia":  ("Psicologia",  "sparkles-outline",       "#FF006A"),
    "corpo-umano": ("Corpo umano", "heart-outline",          "#FF006A"),
    "cultura":     ("Cultura",     "globe-outline",          "#00D2FF"),
    "curiosita":   ("Curiosità",   "help-circle-outline",    "#B200FF"),
}


def _story(sid, cat_id, title, highlights, hook, hero, chapters, summary, read=2, deep=3):
    name, icon, color = CAT[cat_id]
    return {
        "id": sid,
        "category_id": cat_id,
        "category_name": name,
        "category_icon": icon,
        "category_color": color,
        "title": title,
        "highlight_words": highlights,
        "hook": hook,
        "hero_image": hero,
        "reading_time_min": read,
        "deep_dive_time_min": deep,
        "chapters": _ch(chapters),
        "summary": summary,
    }


MORE_STORIES = [
    # ==================== SCIENZA (9) ====================
    _story(
        "gravity-newton-einstein",
        "scienza",
        "Cos'è davvero la gravità?",
        ["gravità"],
        "Ci fa cadere le mele in testa e tiene la Luna in orbita. Ma la gravità non è ciò che pensavi.",
        "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80&auto=format&fit=crop",
        [
            ("La visione di Newton",
             "Nel 1687 Isaac Newton pubblicò la legge di gravitazione universale: ogni oggetto con massa attrae ogni altro oggetto con una forza proporzionale al prodotto delle masse e inversamente proporzionale al quadrato della distanza. Questa formula bastò per calcolare le orbite dei pianeti, prevedere eclissi e mandare in seguito uomini sulla Luna. Ma non spiegava cosa fosse la gravità, solo come si comportava.", "flash"),
            ("L'idea di Einstein",
             "Nel 1915 Einstein rivoluzionò tutto con la relatività generale. La gravità non è una forza: è la deformazione dello spazio-tempo causata dalla massa. Un pianeta è come una palla pesante su un tappeto elastico: incurva il tessuto sottostante e gli oggetti vicini scivolano lungo la curva. Non vengono \"tirati\", cadono lungo la strada più corta in uno spazio deformato.", "aperture"),
            ("La luce cade",
             "Se la gravità curva lo spazio, anche la luce (che va sempre dritta nello spazio) sembrerà deviata quando passa vicino a masse grandi. Nel 1919 un'eclissi solare permise di misurarlo: le stelle vicino al Sole apparivano leggermente spostate. La teoria di Einstein era corretta. Oggi vediamo lo stesso effetto su scala cosmica come lenti gravitazionali attorno alle galassie.", "sunny"),
            ("Il tempo rallenta",
             "Vicino a un corpo massiccio, il tempo scorre più lentamente. Un orologio al livello del mare va più piano di uno in cima all'Everest, misurabilmente. I satelliti GPS devono correggere la relatività ogni giorno, altrimenti sbaglierebbero la posizione di chilometri in poche ore. Il tuo GPS funziona perché tiene conto di Einstein.", "hourglass"),
            ("Cosa non sappiamo ancora",
             "La relatività funziona per stelle e pianeti, la meccanica quantistica per atomi e particelle. Ma queste due teorie non si combinano: cercare la \"gravità quantistica\" è una delle sfide aperte della fisica. Le teorie delle stringhe e la loop quantum gravity provano risposte diverse. Per ora, la gravità resta sia semplice (le mele cadono) sia il più profondo mistero della scienza.", "sparkles"),
        ],
        "La gravità non è una forza: è la deformazione dello spazio-tempo causata dalla massa. È così che pianeti orbitano, luce curva e tempo rallenta.",
    ),
    _story(
        "how-dna-works",
        "scienza",
        "Cos'è il DNA e come ti fa essere te?",
        ["DNA"],
        "Due metri di stringhe chimiche in ogni cellula del tuo corpo contengono le istruzioni per costruirti.",
        "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=1200&q=80&auto=format&fit=crop",
        [
            ("Una molecola a spirale",
             "Il DNA è una molecola a doppia elica scoperta nel 1953 da Watson, Crick, Franklin e Wilkins. È lunga circa 2 metri in ogni tua cellula, arrotolata in uno spazio grande un milionesimo di millimetro. Composta da soli quattro \"mattoncini\" chimici chiamati basi (A, T, C, G), il loro ordine codifica tutte le informazioni per fare un essere umano.", "flask"),
            ("Le istruzioni per le proteine",
             "Sezioni specifiche di DNA sono i geni: ricette per costruire proteine. Le proteine sono le operaie del corpo: costruiscono muscoli, digeriscono cibo, portano ossigeno nel sangue. Il corpo umano ne produce oltre 100.000 tipi diversi. Ogni gene contiene la sequenza di aminoacidi che compongono una proteina specifica.", "construct"),
            ("23 paia di cromosomi",
             "Il DNA umano è organizzato in 46 cromosomi, 23 dalla madre e 23 dal padre. Contengono circa 20.000 geni. Il cromosoma Y, uno dei più piccoli, contiene i geni che avviano lo sviluppo maschile durante lo sviluppo embrionale. Bastano piccole variazioni nel DNA per farci essere così diversi tra fratelli.", "layers"),
            ("Il 99% è uguale",
             "Il DNA di due persone qualsiasi è al 99,9% identico. Solo lo 0,1% ci rende unici: colore degli occhi, gruppo sanguigno, predisposizione a malattie. Con gli scimpanzé condividiamo il 98,8%, con i topi il 90%, persino con le banane il 60%. Siamo molto più simili al resto della vita di quanto sembri.", "people"),
            ("Modificare il codice",
             "Con la tecnica CRISPR (dal 2012) possiamo tagliare il DNA in punti precisi e sostituire pezzi difettosi. Si stanno curando anemia falciforme, distrofie e alcuni tumori. Ma la stessa tecnica potrebbe modificare embrioni umani: solleva domande etiche enormi. Il DNA non è più solo destino: è, per la prima volta, modificabile.", "sparkles"),
        ],
        "Il DNA è una lunga stringa di quattro basi chimiche che contiene le istruzioni per costruire proteine, e quindi te. Condividiamo il 99,9% con qualsiasi altro umano.",
    ),
    _story(
        "quantum-basics",
        "scienza",
        "Cos'è la fisica quantistica in parole semplici?",
        ["fisica", "quantistica"],
        "La realtà, alle scale più piccole, non funziona come pensi. Ma anche il tuo telefono la usa.",
        "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il mondo delle piccole cose",
             "A scale piccolissime (atomi e sotto), le regole della fisica cambiano. Le particelle non si comportano come palline: possono essere in più posti contemporaneamente, saltare senza attraversare gli spazi intermedi, comunicare istantaneamente a grandi distanze. Non è un errore di misura: è come funziona davvero la natura.", "aperture"),
            ("La sovrapposizione",
             "Un elettrone, prima di essere osservato, non è in un posto: è in una \"sovrapposizione\" di tutti i posti possibili. Il celebre gatto di Schrödinger illustra il concetto: dentro una scatola chiusa un gatto legato a un evento quantistico è vivo e morto insieme, finché non apri la scatola. È strano ma è ciò che gli esperimenti mostrano.", "help-circle"),
            ("L'entanglement",
             "Due particelle possono essere \"legate\" in modo che, misurando una, si conosce istantaneamente lo stato dell'altra, anche se sono a chilometri di distanza. Einstein la chiamò \"azione spettrale a distanza\" e la considerava impossibile. Esperimenti degli ultimi 40 anni l'hanno invece confermata. Nessuna informazione viaggia, ma la correlazione è reale.", "link"),
            ("Perché serve",
             "La fisica quantistica non è astratta: senza di essa non esisterebbero transistor, laser, GPS, risonanza magnetica, LED. Il tuo smartphone contiene miliardi di transistor che funzionano grazie a effetti quantistici. La chimica moderna, dalla farmaceutica alle batterie, si basa sulla stessa teoria.", "flash"),
            ("Il futuro quantistico",
             "I computer quantistici, ancora in fase sperimentale, sfruttano sovrapposizione ed entanglement per risolvere in secondi problemi che ai computer classici richiederebbero migliaia di anni. Google, IBM e altri stanno costruendo i primi prototipi. Potrebbero rivoluzionare crittografia, ricerca farmaceutica e intelligenza artificiale nel prossimo decennio.", "sparkles"),
        ],
        "La fisica quantistica descrive il comportamento bizzarro della materia a scale minuscole: sovrapposizione, entanglement e effetti che il tuo smartphone usa ogni giorno.",
    ),
    _story(
        "why-evolution",
        "scienza",
        "Come funziona l'evoluzione (davvero)?",
        ["evoluzione"],
        "Non è una scala verso l'uomo. È un albero che si ramifica da 4 miliardi di anni, e siamo solo un ramoscello.",
        "https://images.unsplash.com/photo-1471520201477-47a62a269a87?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un'idea semplice",
             "Nel 1859 Charles Darwin pubblicò L'origine delle specie. L'idea: gli individui di una specie variano leggermente, e chi ha variazioni utili sopravvive meglio e lascia più figli. Nel corso di milioni di generazioni, piccole differenze si accumulano fino a creare nuove specie. Non serve un progettista, basta il tempo e la variazione casuale.", "leaf"),
            ("Le mutazioni",
             "Le variazioni nascono da errori casuali quando il DNA si copia. La maggior parte è neutra, alcune sono dannose, poche sono utili. Le utili si diffondono nelle generazioni successive perché aiutano a sopravvivere e riprodursi. È così che i colibrì hanno sviluppato becchi lunghi per i fiori tubolari, e le giraffe colli sempre più lunghi.", "flask"),
            ("Non c'è una direzione",
             "L'evoluzione non ha uno scopo. Non è \"migliorare\" o \"diventare più complessi\": è solo adattarsi all'ambiente. Alcuni organismi sono rimasti quasi identici per centinaia di milioni di anni (squali, cavallucci marini) perché il loro adattamento era già ottimo. La complessità non è un traguardo, solo una strategia tra molte.", "compass"),
            ("Prove ovunque",
             "L'evoluzione non è teoria nel senso comune: è verificata da paleontologia (fossili di transizione), genetica (parentele misurabili dal DNA), embriologia (embrioni di specie diverse si assomigliano nelle prime fasi), anatomia comparata. I virus (Covid, influenza) evolvono davanti ai nostri occhi ogni anno.", "search"),
            ("Siamo scimmie",
             "Non siamo \"evoluti dalle scimmie\": siamo scimmie. Condividiamo un antenato comune con gli scimpanzé circa 6-7 milioni di anni fa. La linea umana ha visto decine di specie (Australopiteco, Homo habilis, Homo erectus, Neanderthal, Denisovani). L'Homo sapiens è emerso in Africa circa 300.000 anni fa. Siamo il ramo che è rimasto.", "people"),
        ],
        "L'evoluzione è la selezione naturale di variazioni casuali del DNA nel corso di generazioni. Non ha direzione: si adatta soltanto.",
    ),
    _story(
        "why-water-strange",
        "scienza",
        "Perché l'acqua è così strana?",
        ["acqua", "strana"],
        "La sostanza più comune del pianeta è anche la più anomala che esista. E la vita esiste grazie alle sue stranezze.",
        "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=1200&q=80&auto=format&fit=crop",
        [
            ("Una molecola semplice",
             "L'acqua è H₂O: due atomi di idrogeno e uno di ossigeno. Sembra banale. Ma questa geometria produce una molecola \"polare\": un'estremità è leggermente positiva, l'altra negativa. Le molecole d'acqua si attirano tra loro come minuscoli magneti, formando i legami idrogeno che spiegano quasi tutte le sue stranezze.", "water"),
            ("Il ghiaccio galleggia",
             "Quasi tutte le sostanze diventano più dense quando si raffreddano. L'acqua no: sotto i 4°C si espande, e il ghiaccio è meno denso dell'acqua liquida. Se non fosse così, i laghi si ghiaccerebbero dal fondo verso la superficie e i pesci morirebbero. Il ghiaccio galleggiante è uno dei motivi per cui la vita acquatica sopravvive agli inverni.", "snow"),
            ("Solvente universale",
             "Grazie alla sua polarità, l'acqua scioglie più sostanze di qualsiasi altro liquido conosciuto. È per questo che il nostro sangue, la linfa delle piante e gli oceani possono trasportare nutrienti e sali. Senza questa proprietà, la biochimica come la conosciamo non funzionerebbe.", "flask"),
            ("Tensione superficiale",
             "I legami idrogeno tra le molecole in superficie creano una \"pelle\" che sostiene piccoli insetti (gerridi) e goccioline sferiche. È lo stesso motivo per cui l'acqua sale nei sottili tubi delle piante fino a metri d'altezza: il fenomeno si chiama capillarità e sfrutta la coesione tra molecole.", "leaf"),
            ("Regolatore climatico",
             "L'acqua ha una capacità termica altissima: assorbe e rilascia grandi quantità di calore senza cambiare troppo temperatura. Gli oceani mitigano i climi costieri, il tuo corpo (60% acqua) mantiene temperatura stabile anche in ambienti caldi o freddi. Senza questa proprietà, il pianeta oscillerebbe tra estremi impossibili per la vita.", "thermometer"),
        ],
        "I legami idrogeno rendono l'acqua unica: ghiaccio galleggiante, solvente universale, regolatore climatico. È il liquido perfetto per la vita.",
    ),
    _story(
        "photosynthesis-basics",
        "scienza",
        "Come fanno le piante a mangiare la luce?",
        ["piante", "luce"],
        "Ogni foglia è una piccola centrale energetica che trasforma la luce del Sole in zucchero. E in cambio, ossigena l'atmosfera.",
        "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80&auto=format&fit=crop",
        [
            ("La sfida della vita",
             "Ogni essere vivente ha bisogno di energia. Gli animali la prendono mangiando altri esseri viventi. Le piante hanno inventato una strategia diversa e straordinaria: prendere energia direttamente dal Sole, senza mangiare nessuno. Questo processo si chiama fotosintesi ed è alla base di quasi tutta la vita sulla Terra.", "leaf"),
            ("La clorofilla",
             "Le piante contengono nelle foglie un pigmento verde chiamato clorofilla. È verde perché assorbe la luce rossa e blu ma riflette quella verde. Quando la luce colpisce la clorofilla, gli elettroni vengono \"eccitati\" e questa energia viene usata per costruire molecole più complesse.", "color-palette"),
            ("Acqua + CO₂ + luce",
             "La ricetta della fotosintesi è: acqua (dalle radici) + anidride carbonica (dall'aria) + luce solare. Il risultato: glucosio (zucchero, che diventa cibo per la pianta) + ossigeno (rilasciato nell'aria). L'ossigeno che respiriamo viene quasi tutto da piante e alghe.", "water"),
            ("Un piccolo miracolo",
             "In una singola foglia possono avvenire migliaia di reazioni fotosintetiche al secondo. I \"cloroplasti\" sono i piccoli organelli che ospitano il processo. Le piante producono ogni anno oltre 100 miliardi di tonnellate di zuccheri, di cui viviamo direttamente o indirettamente.", "flash"),
            ("Il polmone del pianeta",
             "Le foreste tropicali producono circa il 20% dell'ossigeno del pianeta, gli oceani (tramite fitoplancton) circa il 70%. La deforestazione e l'inquinamento marino non minacciano solo la biodiversità: riducono la capacità del pianeta di ossigenarsi. Ogni albero è un piccolo alleato.", "planet"),
        ],
        "Le piante trasformano acqua, CO₂ e luce solare in zucchero e ossigeno. È la fabbrica energetica silenziosa che sostiene tutta la vita.",
    ),
    _story(
        "why-magnets",
        "scienza",
        "Perché i magneti attirano il ferro?",
        ["magneti", "ferro"],
        "Non c'è nessuna forza misteriosa. C'è un esercito invisibile di piccoli elettroni che marciano tutti nella stessa direzione.",
        "https://images.unsplash.com/photo-1614729375293-74e5cf67ebc3?w=1200&q=80&auto=format&fit=crop",
        [
            ("Ogni atomo è un mini-magnete",
             "Ogni atomo ha elettroni che ruotano attorno al nucleo. Il movimento delle cariche elettriche genera piccoli campi magnetici. Ogni atomo, in teoria, è come un piccolissimo magnete. Nella maggior parte dei materiali questi magneti sono orientati casualmente e si cancellano tra loro.", "atom"),
            ("Il ferro è speciale",
             "Nel ferro (e in cobalto e nichel) gli atomi si allineano naturalmente in gruppi chiamati domini magnetici. Se questi domini puntano tutti nella stessa direzione, il materiale diventa un magnete permanente. Un magnete non è altro che un pezzo di ferro con tutti i suoi domini allineati.", "layers"),
            ("Come attira gli altri",
             "Quando un magnete si avvicina a un pezzo di ferro non magnetizzato, il suo campo magnetico obbliga i domini interni a orientarsi. Il ferro diventa temporaneamente un magnete e si attira all'originale. Poi, quando allontani il magnete, i domini tornano al caos e il ferro non è più magnetico.", "arrow-forward"),
            ("Poli opposti",
             "Ogni magnete ha due poli, chiamati Nord e Sud. Poli uguali si respingono, poli opposti si attraggono. Non esistono magneti con un solo polo: se rompi un magnete a metà, ottieni due magneti più piccoli, ciascuno con Nord e Sud.", "swap-horizontal"),
            ("La Terra è un magnete",
             "Il nucleo terrestre di ferro fuso in rotazione genera un enorme campo magnetico che avvolge il pianeta. È ciò che orienta la bussola e ci protegge dalle particelle solari (creando anche le aurore). Il Polo Nord magnetico non coincide esattamente con il Nord geografico, e si sta lentamente spostando ogni anno.", "compass"),
        ],
        "I magneti funzionano perché i loro atomi di ferro sono allineati nella stessa direzione. La Terra stessa è un enorme magnete.",
    ),
    _story(
        "why-rain-falls",
        "scienza",
        "Come nasce la pioggia?",
        ["pioggia"],
        "Un ciclo silenzioso che l'acqua ripete da miliardi di anni. Il tuo bicchiere di stamattina probabilmente ha bevuto un T-Rex.",
        "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=1200&q=80&auto=format&fit=crop",
        [
            ("L'evaporazione",
             "Il Sole riscalda oceani, laghi e fiumi. Le molecole d'acqua più energetiche superano i legami che le tenevano insieme al liquido e diventano vapore. Ogni giorno oltre mille miliardi di tonnellate d'acqua evaporano dagli oceani del pianeta. Un'intera atmosfera invisibile di vapore acqueo.", "sunny"),
            ("La condensazione",
             "Salendo, il vapore incontra aria più fredda. Il freddo rallenta le molecole, che tornano a legarsi in goccioline microscopiche attaccate a granelli di polvere, pollini o sale marino. Miliardi di queste goccioline formano le nuvole. Le nuvole non sono \"gas\": sono acqua liquida sospesa.", "cloud"),
            ("Quando le gocce cadono",
             "Se le goccioline continuano a fondersi tra loro, crescono. Quando diventano abbastanza grandi da vincere la resistenza dell'aria, cadono: pioggia. Se in cima alla nuvola fa molto freddo, si formano cristalli di ghiaccio che scendono come neve o grandine, a seconda della temperatura sul percorso.", "water"),
            ("Il ciclo si ripete",
             "L'acqua che scende raggiunge terreni, fiumi, laghi, oceani, e ricomincia a evaporare. Il ciclo idrologico dura in media 9 giorni per una goccia. Ogni molecola d'acqua sulla Terra ha già fatto questo giro miliardi di volte, passando attraverso ere geologiche e specie ormai estinte.", "refresh"),
            ("Pioggia in altri mondi",
             "Non piove solo sulla Terra. Su Titano (luna di Saturno) piove metano liquido. Su Venere piove acido solforico. Su alcuni pianeti extrasolari giganti gassosi si pensa piova ferro fuso o diamanti. La pioggia è un fenomeno universale, con ingredienti diversi in ogni mondo.", "planet"),
        ],
        "La pioggia nasce da un ciclo di evaporazione, condensazione e caduta che l'acqua ripete di continuo. Ogni goccia ha già viaggiato attorno al pianeta miliardi di volte.",
    ),
    _story(
        "chemistry-basics",
        "scienza",
        "Cos'è davvero un atomo?",
        ["atomo"],
        "L'unità di tutto: sedie, aria, stelle, te. Ma se guardi da vicino è quasi tutta spazio vuoto.",
        "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il mattoncino della materia",
             "Tutto ciò che vedi, tocchi o respiri è fatto di atomi. Sono così piccoli che ne stanno miliardi in un granello di sabbia. Il concetto di atomo (dal greco \"indivisibile\") esiste dal 400 a.C., ma solo nell'Ottocento è stato dimostrato che esistevano davvero.", "layers"),
            ("Un nucleo minuscolo",
             "Al centro dell'atomo c'è il nucleo, formato da protoni (carica positiva) e neutroni (nessuna carica). Il nucleo è piccolissimo: se un atomo fosse grande come uno stadio, il nucleo sarebbe come una biglia al centro del campo. Il resto è quasi vuoto.", "aperture"),
            ("Elettroni intorno",
             "Attorno al nucleo si trovano gli elettroni (carica negativa). Non ruotano come pianeti: esistono in \"nubi di probabilità\" chiamate orbitali. Sono così leggeri che pesano quasi nulla rispetto al nucleo, ma sono loro a determinare come gli atomi si legano tra loro.", "planet"),
            ("Elementi diversi",
             "Il numero di protoni definisce l'elemento chimico. Un atomo con 1 protone è idrogeno, con 6 è carbonio, con 79 è oro. In natura ne esistono 92, e altri sono stati creati in laboratorio. Tutta la varietà di sostanze del pianeta nasce combinando questi 92 mattoncini.", "grid"),
            ("Sei per lo più vuoto",
             "Sommando tutti gli spazi vuoti negli atomi che ti compongono, se togliessimo il vuoto, il tuo corpo entrerebbe in un cubetto grande come un granello di zucchero. Non cadi attraverso il pavimento perché gli elettroni respingono altri elettroni con forza elettrica. Tocchi le cose senza toccare davvero nulla.", "sparkles"),
        ],
        "Gli atomi sono i mattoncini della materia: un nucleo denso e piccolo circondato da nubi di elettroni. Sei fatto di miliardi di miliardi di questi, ma sei quasi tutto spazio vuoto.",
    ),

    # ==================== SPAZIO (8) ====================
    _story(
        "moon-tides",
        "spazio",
        "Perché la Luna fa muovere il mare?",
        ["Luna", "mare"],
        "Alta e bassa marea due volte al giorno. Non è caso: è la Luna che ti tira delicatamente per i piedi.",
        "https://images.unsplash.com/photo-1522434860430-f1cef8b9ea60?w=1200&q=80&auto=format&fit=crop",
        [
            ("Gravità reciproca",
             "La Luna e la Terra si attirano a vicenda. La Terra è più grande, quindi la Luna orbita attorno a noi. Ma la Luna, pur essendo piccola, esercita una gravità sufficiente a spostare gli oceani. È come se ci tirasse leggermente da un lato, ogni istante.", "moon"),
            ("Due gobbe d'acqua",
             "L'acqua degli oceani viene attirata dalla Luna, formando una \"gobba\" nell'oceano rivolto verso di essa. Ma stranamente si forma un'altra gobba anche dal lato opposto, perché la Terra stessa viene attirata più della sua acqua sul lato lontano. Il risultato: due gobbe di alta marea.", "water"),
            ("Perché ruota",
             "Mentre la Terra gira su sé stessa, ogni punto del pianeta passa sotto queste due gobbe. Un luogo qualsiasi vive quindi due alte maree e due basse maree in 24 ore e 50 minuti (i 50 minuti extra sono perché anche la Luna si muove).", "refresh"),
            ("Non solo la Luna",
             "Anche il Sole contribuisce, con circa la metà dell'effetto lunare (più massiccio ma molto più lontano). Quando Sole e Luna sono allineati (luna piena e luna nuova), le maree sono più forti (\"sizigie\"). Quando formano un angolo di 90° (primo e ultimo quarto), sono più deboli.", "sunny"),
            ("La Luna rallenta la Terra",
             "L'attrito delle maree ruba lentamente energia rotazionale alla Terra. Il giorno terrestre si allunga di circa 2 millisecondi ogni secolo. Nel tempo dei dinosauri il giorno durava solo 22 ore. Nel frattempo la Luna si allontana di circa 3,8 cm all'anno. Tra qualche miliardo di anni ci saluterà davvero.", "arrow-forward"),
        ],
        "La gravità della Luna solleva gli oceani formando due gobbe di alta marea. Ecco perché il mare sale e scende due volte al giorno.",
    ),
    _story(
        "how-stars-die",
        "spazio",
        "Come muore una stella?",
        ["stella", "muore"],
        "Le stelle non brillano per sempre. E quando muoiono, spesso lo fanno con esplosioni visibili a distanze inimmaginabili.",
        "https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=1200&q=80&auto=format&fit=crop",
        [
            ("Una stella è un equilibrio",
             "Una stella è una palla di gas che fonde idrogeno in elio nel suo nucleo. La fusione produce energia (calore, luce) che spinge verso l'esterno, contrastando la gravità che vorrebbe collassare la stella su sé stessa. Finché c'è combustibile, l'equilibrio regge.", "flame"),
            ("Quando finisce il carburante",
             "Prima o poi l'idrogeno nel nucleo si esaurisce. La fusione rallenta, la gravità vince, il nucleo si contrae e si riscalda ancora di più. La stella comincia a fondere elementi più pesanti: elio, carbonio, ossigeno, silicio. In alcune stelle, arriva fino al ferro.", "hourglass"),
            ("Le stelle piccole",
             "Stelle come il nostro Sole non finiscono con esplosioni drammatiche. Si gonfiano diventando \"giganti rosse\" (il Sole inghiottirà Mercurio e Venere), poi espellono i loro strati esterni formando bellissime nebulose planetarie, e lasciano al centro un piccolo nucleo denso e caldo chiamato nana bianca, che si raffredda per miliardi di anni.", "sunny"),
            ("Le stelle grandi: supernova",
             "Stelle almeno 8 volte più massicce del Sole finiscono con un botto. Il nucleo di ferro non può più produrre energia dalla fusione, la gravità collassa tutto in una frazione di secondo. L'energia liberata è enorme: una supernova può brillare quanto un'intera galassia per settimane.", "flash"),
            ("Cosa resta",
             "Dopo una supernova, il nucleo può diventare una stella di neutroni (una \"palla\" di soli neutroni grande 20 km che pesa quanto due Soli) o, se la stella era abbastanza grande, un buco nero. Gli elementi pesanti forgiati durante la vita della stella (oro, uranio, iodio) vengono sparpagliati nell'universo. Il calcio nelle tue ossa è nato in una supernova.", "sparkles"),
        ],
        "Le stelle finiscono spente e piccole (nane bianche) o con esplosioni giganti (supernove). In entrambi i casi, arricchiscono l'universo con gli elementi che ci compongono.",
    ),
    _story(
        "why-sun-shines",
        "spazio",
        "Come fa il Sole a brillare da 5 miliardi di anni?",
        ["Sole", "brillare"],
        "Non brucia legna né gas. Il Sole è una bomba a idrogeno controllata dalla sua stessa gravità.",
        "https://images.unsplash.com/photo-1610296669228-602fa827fc1f?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un sistema enorme",
             "Il Sole è una stella di media grandezza: al suo centro potrebbero starci un milione di Terre. Si è formato circa 4,6 miliardi di anni fa da una nube di gas e polveri che collassò per gravità. Al centro la pressione e la temperatura sono così alte da innescare la fusione nucleare.", "sunny"),
            ("La fusione",
             "Nel nucleo solare, quattro protoni di idrogeno si fondono in un nucleo di elio, liberando una piccola quantità di energia. Miliardi di reazioni al secondo sommano un'immensa quantità di luce e calore che si propaga verso la superficie. Il Sole trasforma 4 milioni di tonnellate di materia in energia ogni secondo.", "flash"),
            ("Perché non esplode",
             "L'enorme spinta della fusione verso l'esterno è compensata dalla gravità del Sole stesso, che tenta di comprimerlo. Se la fusione aumenta, il Sole si dilata e si raffredda, riducendo la fusione. È un termostato naturale che tiene il Sole stabile per miliardi di anni.", "sync"),
            ("Il viaggio della luce",
             "Un fotone (particella di luce) prodotto nel nucleo del Sole impiega tra 100.000 e 1 milione di anni per raggiungere la superficie, rimbalzando continuamente tra particelle. Poi impiega solo 8 minuti per arrivare sulla Terra. La luce del sole che vedi oggi è iniziata durante l'era dei Neanderthal.", "hourglass"),
            ("Il futuro",
             "Tra circa 5 miliardi di anni il Sole finirà l'idrogeno del nucleo, si gonfierà in una gigante rossa e inghiottirà Mercurio, Venere e forse anche la Terra. Poi espellerà gli strati esterni e lascerà una piccola nana bianca. Ma stiamo tranquilli: molto prima, altre cose cambieranno la Terra.", "star"),
        ],
        "Il Sole brilla grazie alla fusione nucleare: idrogeno che diventa elio, con un equilibrio perfetto tra spinta della fusione e gravità.",
    ),
    _story(
        "how-many-galaxies",
        "spazio",
        "Quante galassie ci sono nell'universo?",
        ["galassie"],
        "Prova a contare le stelle di notte. Ogni singola galassia ne contiene miliardi. Poi moltiplica per due trilioni.",
        "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200&q=80&auto=format&fit=crop",
        [
            ("La nostra galassia",
             "La Via Lattea è la nostra galassia: una spirale con circa 200 miliardi di stelle. Il Sole è una stella normale nella periferia. La Via Lattea è larga circa 100.000 anni luce: la luce, che va velocissima, impiega 100.000 anni per attraversarla.", "planet"),
            ("Un solo tipo tra tanti",
             "Le galassie hanno forme diverse: spirali (come la nostra), ellittiche (a forma di uovo), irregolari (senza forma definita). Le più grandi contengono trilioni di stelle. Le più piccole (galassie nane) qualche miliardo. Ogni galassia è un piccolo universo a sé.", "grid"),
            ("Il conteggio",
             "Il telescopio spaziale Hubble ha puntato un pezzetto di cielo apparentemente vuoto e ha trovato migliaia di galassie. Estrapolando, si stimano tra 200 miliardi e 2 trilioni (2.000 miliardi) di galassie nell'universo osservabile. In pratica, per ogni essere umano vivente, ci sono circa 250 galassie.", "eye"),
            ("Distanze folli",
             "La galassia più vicina, Andromeda, è a 2,5 milioni di anni luce. La stiamo vedendo com'era quando i primi ominidi camminavano sulla Terra. Le galassie più lontane osservabili sono a oltre 13 miliardi di anni luce: la loro luce è partita quando l'universo era ancora giovane.", "arrow-forward"),
            ("Si allontanano",
             "Le galassie non stanno ferme: l'universo si espande e loro si allontanano l'una dall'altra. Più sono lontane, più velocemente si allontanano. Questo effetto, scoperto da Hubble nel 1929, è la base del Big Bang: se torniamo indietro nel tempo, tutto convergeva in un unico punto.", "arrow-back"),
        ],
        "L'universo contiene tra 200 miliardi e 2 trilioni di galassie, ciascuna con miliardi di stelle. E si allontanano tutte l'una dall'altra.",
    ),
    _story(
        "how-iss-works",
        "spazio",
        "Come funziona la Stazione Spaziale Internazionale?",
        ["Stazione", "Spaziale"],
        "Un laboratorio grande come un campo di calcio orbita da oltre 25 anni sopra le nostre teste, a 400 km d'altezza.",
        "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=1200&q=80&auto=format&fit=crop",
        [
            ("Cos'è",
             "La ISS è una struttura modulare in orbita bassa, a circa 400 km dalla Terra. Larga come un campo di calcio, pesa oltre 400 tonnellate. È stata costruita pezzo per pezzo a partire dal 1998, portata in orbita da razzi e navette. Ha ospitato astronauti in continuazione dal 2000: da allora c'è sempre qualcuno lassù.", "planet"),
            ("Come sta lassù",
             "La ISS non è \"sospesa\": è in caduta libera continua attorno alla Terra. Va così veloce (circa 28.000 km/h) che quando cade in avanti la Terra si incurva sotto di lei alla stessa velocità. È così che funziona ogni orbita. Ogni 90 minuti la ISS fa un giro completo del pianeta.", "rocket"),
            ("La microgravità",
             "A bordo tutto galleggia. Non perché non ci sia gravità (a 400 km la gravità è ancora quasi come a terra), ma perché la stazione e ciò che contiene cadono insieme. Gli astronauti sperimentano un ambiente detto microgravità: perfetto per esperimenti impossibili sulla Terra.", "cloud"),
            ("Cosa ci fanno",
             "La ISS è un laboratorio: si studiano effetti della microgravità su corpo umano (utile per future missioni su Marte), cristalli, farmaci, combustione. Si testano tecnologie per esplorazione spaziale. Gli astronauti vivono 6 mesi in media, tornando con osteoporosi temporanea e sistema muscolare atrofizzato.", "flask"),
            ("La sua fine",
             "La ISS invecchia. Dopo il 2030 verrà de-orbitata: un rientro controllato la farà bruciare nell'atmosfera e i resti cadranno nel Pacifico. Nel frattempo Cina e privati stanno costruendo stazioni alternative. La ISS ha aperto la strada, ma il futuro dell'abitazione umana nello spazio sarà più affollato.", "sparkles"),
        ],
        "La ISS orbita a 400 km d'altezza in caduta libera perpetua. È il più grande esperimento umano di vita nello spazio.",
    ),
    _story(
        "big-bang-basics",
        "spazio",
        "Cos'è il Big Bang, in parole semplici?",
        ["Big", "Bang"],
        "Non è un'esplosione. Non è avvenuto in un posto. Ed è il momento in cui è nato lo spazio-tempo.",
        "https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=1200&q=80&auto=format&fit=crop",
        [
            ("L'universo si espande",
             "Osservando le galassie, tutte si allontanano l'una dall'altra. Non solo: più sono lontane, più veloci se ne vanno. Se torniamo indietro nel tempo, tutto convergeva in un unico punto densissimo. Circa 13,8 miliardi di anni fa lo spazio stesso era piccolissimo e la temperatura era enorme.", "arrow-back"),
            ("Non un'esplosione",
             "Il termine \"Big Bang\" trae in inganno: non è avvenuto in un posto preciso, perché lo spazio stesso si stava espandendo ovunque. Era lo spazio a gonfiarsi, non oggetti che si allontanavano in uno spazio preesistente. È lo spazio che è diventato più grande.", "aperture"),
            ("I primi minuti",
             "Nei primi microsecondi si formarono le particelle fondamentali. Nei primi minuti nacquero i nuclei più leggeri: idrogeno, elio, un po' di litio. Ma l'universo era ancora troppo caldo perché la luce potesse viaggiare liberamente: era una nebbia opaca di plasma.", "flame"),
            ("La prima luce",
             "Circa 380.000 anni dopo il Big Bang, l'universo si era raffreddato abbastanza da far combinare elettroni e nuclei in atomi neutri. La luce, non più intrappolata dal plasma, finalmente si liberò. Quella luce originale, molto raffreddata dall'espansione, la vediamo ancora oggi come \"radiazione cosmica di fondo\", scoperta nel 1964.", "radio"),
            ("Prove concrete",
             "Il Big Bang non è un'ipotesi speculativa. Abbiamo tre prove indipendenti: (1) le galassie si allontanano come previsto; (2) l'abbondanza di elementi leggeri (idrogeno ed elio) corrisponde ai calcoli; (3) la radiazione cosmica di fondo è esattamente quella prevista. Fu una vittoria storica della scienza.", "checkmark-circle"),
        ],
        "13,8 miliardi di anni fa lo spazio-tempo era piccolissimo e caldissimo. Da allora si è espanso, formando galassie, stelle, pianeti e noi.",
    ),
    _story(
        "why-comets-tails",
        "spazio",
        "Perché le comete hanno la coda?",
        ["comete", "coda"],
        "Non sono \"stelle cadenti\": sono palle di ghiaccio sporco che, avvicinandosi al Sole, sputano una scia visibile a milioni di chilometri.",
        "https://images.unsplash.com/photo-1610296669228-602fa827fc1f?w=1200&q=80&auto=format&fit=crop",
        [
            ("Cos'è una cometa",
             "Una cometa è un piccolo corpo celeste (in genere pochi chilometri di diametro) fatto di ghiaccio, polveri e roccia. Nasce nelle regioni fredde ai confini del sistema solare (fascia di Kuiper, nube di Oort) e ogni tanto una perturbazione gravitazionale la lancia verso il Sole.", "snow"),
            ("Il nucleo",
             "Il cuore di una cometa si chiama nucleo. È scuro, pieno di crateri, e la sua composizione è simile a quella dei primi materiali del sistema solare (4,5 miliardi di anni fa). Studiare le comete è un po' come leggere un fossile del passato cosmico.", "cube"),
            ("Chioma e coda",
             "Quando la cometa si avvicina al Sole, il ghiaccio comincia a sublimare (passare direttamente da solido a gas). Attorno al nucleo si forma un alone di gas e polveri chiamato chioma, largo anche milioni di chilometri. La radiazione solare e il vento solare spingono la chioma nella direzione opposta al Sole: nasce la coda.", "cloud"),
            ("Due code, non una",
             "Le comete hanno spesso due code visibili: una di polvere (curva, giallastra, illuminata dalla luce solare riflessa) e una di gas ionizzato (dritta, azzurra, spinta dal vento solare). Sono strutture separate. E la coda punta sempre lontano dal Sole, anche mentre la cometa si allontana.", "git-branch"),
            ("Comete famose",
             "La cometa di Halley passa ogni 76 anni. La cometa NEOWISE è stata visibile a occhio nudo nel 2020. Le comete a periodo lungo possono impiegare migliaia o milioni di anni per un giro. Alcune, una volta viste, non torneranno più: si sono avvicinate troppo al Sole e sono state distrutte.", "sparkles"),
        ],
        "Le comete sono palle di ghiaccio del sistema solare esterno. Vicino al Sole, il ghiaccio sublima e produce chioma e coda: spettacolari, ma temporanee.",
    ),
    _story(
        "exoplanets-basics",
        "spazio",
        "Ci sono altri pianeti come la Terra?",
        ["altri", "pianeti"],
        "Ne abbiamo trovati oltre 5.000. Almeno alcuni potrebbero avere oceani, atmosfere e forse anche più.",
        "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il primo trovato",
             "Fino al 1995 non sapevamo se esistessero pianeti attorno ad altre stelle. Poi Michel Mayor e Didier Queloz scoprirono 51 Pegasi b, un pianeta gassoso attorno a una stella simile al Sole. Da allora, la caccia agli esopianeti è esplosa. Nel 2019 hanno vinto il Nobel.", "search"),
            ("Come li vediamo",
             "Non vediamo direttamente gli esopianeti: sono troppo piccoli e vicini alle loro stelle. Li scopriamo indirettamente: quando un pianeta passa davanti alla sua stella, la luce si oscura leggermente (metodo del transito, usato dal telescopio Kepler). Oppure osservando come la stella oscilla per la gravità del pianeta.", "eye"),
            ("Migliaia di scoperte",
             "Oggi conosciamo oltre 5.500 esopianeti confermati. Ce ne sono di ogni tipo: giganti gassosi più grandi di Giove, mini-nettuni, super-terre rocciose, e qualche pianeta di dimensioni simili alla Terra. Alcune stelle ospitano interi sistemi planetari.", "planet"),
            ("La zona abitabile",
             "Ci interessano soprattutto i pianeti nella \"zona abitabile\": la distanza dalla stella in cui l'acqua liquida può esistere. Troppo vicino: l'acqua evapora. Troppo lontano: si ghiaccia. La Terra è nella zona abitabile del Sole. Ne conosciamo decine, alcuni con dimensioni simili al nostro pianeta.", "water"),
            ("Vita altrove?",
             "Trapist-1, Proxima Centauri b, Kepler-452b sono candidati promettenti. Il telescopio James Webb (attivo dal 2022) può analizzare la luce delle loro atmosfere per cercare tracce di ossigeno, metano, acqua. Se troveremo firme di vita, sarà probabilmente entro il prossimo decennio. Sarebbe la scoperta più importante nella storia dell'umanità.", "sparkles"),
        ],
        "Abbiamo scoperto oltre 5.500 esopianeti, alcuni simili alla Terra e nella zona abitabile della loro stella. La ricerca di vita altrove è più vicina che mai.",
    ),

    # ==================== TECNOLOGIA (8) ====================
    _story(
        "how-gps-works",
        "tecnologia",
        "Come fa il GPS a sapere dove sei?",
        ["GPS"],
        "Un piccolo miracolo in tasca: 24 satelliti a 20.000 km d'altezza ti localizzano al metro. E sfruttano Einstein.",
        "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1200&q=80&auto=format&fit=crop",
        [
            ("Una costellazione di satelliti",
             "Il GPS (Global Positioning System) è basato su circa 24-30 satelliti che orbitano attorno alla Terra a circa 20.200 km d'altezza. Ogni satellite trasmette continuamente la sua posizione e l'orario esatto (con orologi atomici precisissimi). Da qualsiasi punto della Terra si vedono in cielo almeno 4 satelliti.", "planet"),
            ("Distanza dai satelliti",
             "Il tuo telefono riceve i segnali dai satelliti visibili. Sapendo l'orario di partenza e quello di arrivo, calcola quanto tempo il segnale ha impiegato e, moltiplicando per la velocità della luce, la distanza da quel satellite.", "wifi"),
            ("La trilaterazione",
             "Conoscere la distanza da un satellite ti mette su una sfera immaginaria attorno a lui. Con due satelliti, sei sull'intersezione di due sfere (un cerchio). Con tre, un punto (o due). Con quattro, la posizione esatta 3D + orario. Basta questo per sapere dove sei sulla Terra al metro.", "compass"),
            ("Serve Einstein",
             "Gli orologi dei satelliti, per la relatività, vanno leggermente più veloci di quelli a terra (meno gravità in orbita). Se il GPS non correggesse questi effetti, sbaglierebbe di circa 10 km al giorno. Ogni volta che il navigatore ti porta a destinazione, ringrazia Einstein.", "flash"),
            ("Non solo americano",
             "GPS è americano, ma ci sono sistemi paralleli: Galileo (Europa), GLONASS (Russia), BeiDou (Cina). Il tuo smartphone spesso usa tutti insieme per essere più preciso. Nelle città con grattacieli o boschi fitti la precisione cala perché i segnali rimbalzano o vengono bloccati.", "globe"),
        ],
        "Il GPS misura la distanza da almeno 4 satelliti sincronizzati con orologi atomici. Per essere preciso, corregge anche gli effetti relativistici di Einstein.",
    ),
    _story(
        "how-batteries-work",
        "tecnologia",
        "Come fa una batteria a conservare energia?",
        ["batteria"],
        "Non è un serbatoio pieno di elettricità: è un piccolo laboratorio chimico che trasforma reazioni in corrente.",
        "https://images.unsplash.com/photo-1494212088344-91b18d9d4c11?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non contiene elettricità",
             "Una batteria non contiene elettricità pronta all'uso, ma sostanze chimiche che, quando collegate a un circuito, reagiscono producendo un flusso di elettroni. In pratica, energia chimica che si trasforma in energia elettrica su richiesta.", "flash"),
            ("Due elettrodi",
             "Ogni batteria ha due elettrodi: uno positivo (catodo) e uno negativo (anodo), separati da un liquido o gel chiamato elettrolita. Quando li colleghi a un circuito, gli elettroni fluiscono dall'anodo al catodo attraverso il circuito, alimentando il tuo dispositivo.", "swap-horizontal"),
            ("Reazione controllata",
             "Nell'anodo avviene una reazione che libera elettroni. Nel catodo una reazione li assorbe. L'elettrolita permette agli ioni di muoversi da un elettrodo all'altro, chiudendo il ciclo. Quando le sostanze chimiche si esauriscono, la batteria è \"scarica\".", "flask"),
            ("Ricaricabili vs no",
             "Nelle batterie ricaricabili (litio, NiMH), applicando corrente al contrario si ripristinano le sostanze chimiche originali. Nelle batterie usa e getta (alcaline), la reazione non è reversibile. La chimica del litio è oggi la più diffusa perché conserva molta energia in poco spazio.", "refresh"),
            ("Il futuro",
             "Le batterie a stato solido (senza liquido) promettono maggiore densità, ricariche più veloci e minor rischio di incendio. Le batterie al sodio potrebbero sostituire il litio, molto più economiche. Nel prossimo decennio la mobilità elettrica dipenderà da questi progressi.", "sparkles"),
        ],
        "Una batteria conserva energia sotto forma chimica e la converte in elettricità quando serve, grazie al flusso di elettroni tra due elettrodi.",
    ),
    _story(
        "how-internet-works",
        "tecnologia",
        "Come funziona davvero internet?",
        ["internet"],
        "Non è una nuvola. È una rete di cavi di vetro sottomarini che uniscono i continenti alla velocità della luce.",
        "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=80&auto=format&fit=crop",
        [
            ("Una rete di reti",
             "Internet è la connessione di milioni di reti di computer. Ogni computer, telefono o server ha un indirizzo unico (IP address). Quando chiedi una pagina web, il tuo dispositivo manda una richiesta che deve raggiungere un server specifico, magari dall'altra parte del mondo.", "globe"),
            ("Pacchetti",
             "I dati non viaggiano interi: vengono spezzettati in pacchetti piccoli, ciascuno con un'etichetta che dice dove deve andare. Ogni pacchetto può prendere strade diverse. Se uno si perde, viene rispedito. Alla destinazione i pacchetti vengono ricomposti.", "cube"),
            ("Cavi sottomarini",
             "Il 99% del traffico internet intercontinentale passa attraverso cavi di fibra ottica sui fondali degli oceani. Sono lunghi migliaia di chilometri, spessi come un tubo da giardino, e trasportano dati alla velocità della luce. I satelliti sono un backup, ma la fibra è molto più veloce ed economica.", "boat"),
            ("Router e switch",
             "Sulla strada dei pacchetti ci sono milioni di router e switch: sono i \"vigili urbani\" della rete. Guardano l'etichetta dei pacchetti e decidono su quale cavo mandarli per farli arrivare più in fretta. Un router in Italia decide se un pacchetto va negli USA via Atlantico o via Pacifico.", "git-network"),
            ("DNS: la rubrica",
             "Ricordare che l'IP di Google è 142.250.185.78 sarebbe assurdo. Il DNS (Domain Name System) è una gigantesca rubrica che traduce nomi (google.com) in indirizzi IP. Ogni volta che apri un sito, dietro le quinte il DNS fa una \"chiamata rapida\" per trovarti il numero giusto.", "book"),
        ],
        "Internet è una rete di reti connessa da cavi sottomarini di fibra ottica. I dati viaggiano in pacchetti smistati da router alla velocità della luce.",
    ),
    _story(
        "how-encryption-works",
        "tecnologia",
        "Come fa WhatsApp a essere davvero privato?",
        ["WhatsApp", "privato"],
        "Anche se qualcuno intercettasse i tuoi messaggi, vedrebbe solo caratteri illeggibili. Ecco la magia della crittografia.",
        "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il problema",
             "Ogni messaggio inviato online passa attraverso decine di server e cavi. Chiunque abbia accesso a un pezzo di quel percorso (governi, hacker, provider) potrebbe leggere. Serviva un modo per proteggere il contenuto anche da chi trasporta i dati.", "eye"),
            ("Crittografia a chiave",
             "L'idea: trasformare il messaggio in una sequenza illeggibile usando una \"chiave\". Solo chi ha la chiave corretta può decifrarlo. In pratica: applichi una formula matematica al testo e ottieni un testo cifrato. Applichi la formula inversa e torni al testo originale.", "key"),
            ("Chiave pubblica e privata",
             "Le crittografie moderne usano due chiavi accoppiate: una pubblica (che tutti possono conoscere) e una privata (che solo tu conosci). Quello che viene cifrato con la chiave pubblica di qualcuno può essere decifrato solo con la sua chiave privata. È come una cassetta postale: chiunque può inserire lettere, solo tu puoi aprirla.", "lock-closed"),
            ("End-to-end",
             "WhatsApp e Signal usano crittografia end-to-end: quando invii un messaggio, viene cifrato sul tuo telefono con la chiave pubblica del destinatario. Solo il suo telefono, con la chiave privata, può decifrarlo. Neanche WhatsApp può leggere i tuoi messaggi in transito.", "shield-checkmark"),
            ("Non è infallibile",
             "La crittografia protegge il contenuto in transito, ma non il tuo telefono. Se qualcuno accede fisicamente al tuo dispositivo, o installa uno spyware, può leggere tutto. Anche i metadati (chi parla con chi, quando) spesso non sono cifrati e possono dire molto. La privacy assoluta non esiste.", "warning"),
        ],
        "La crittografia end-to-end cifra i messaggi con la chiave pubblica del destinatario. Solo chi ha la chiave privata può decifrarli.",
    ),
    _story(
        "how-ai-learns",
        "tecnologia",
        "Come fa un'AI a imparare?",
        ["AI", "imparare"],
        "Non è magia e non è \"pensiero\". È matematica: miliardi di parametri che si aggiustano finché non trovano gli schemi giusti.",
        "https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non è come noi",
             "Un'intelligenza artificiale non ragiona come una persona. È un sistema statistico enorme: date molte informazioni in input, cerca di produrre l'output più probabile in base agli esempi che ha visto. Non capisce, ma è bravissima a riconoscere schemi.", "aperture"),
            ("Reti neurali",
             "I modelli moderni si basano su reti neurali: strati di piccole unità matematiche connesse tra loro. Ogni unità riceve numeri in ingresso, li combina secondo dei pesi, e produce un numero in uscita. Impilando molti strati, si può rappresentare quasi qualsiasi funzione.", "layers"),
            ("Addestramento",
             "Per insegnare a una rete neurale, le si mostrano milioni di esempi con le risposte giuste. Ogni volta che sbaglia, i pesi delle connessioni vengono leggermente aggiustati per ridurre l'errore. Dopo miliardi di aggiustamenti, la rete impara a rispondere bene su nuovi esempi.", "school"),
            ("Perché serve tanto calcolo",
             "Un modello moderno come ChatGPT ha centinaia di miliardi di parametri (pesi). Ognuno deve essere calcolato e aggiornato durante l'addestramento. Servono migliaia di schede grafiche potenti che lavorano in parallelo per settimane. Il costo è enorme, e l'energia consumata anche.", "flash"),
            ("Limiti e rischi",
             "Un'AI è brava solo quanto i dati con cui è stata addestrata. Se i dati sono di parte, l'AI sarà di parte. Se le fai una domanda su un argomento che non conosce, può inventare risposte plausibili ma sbagliate (\"allucinazioni\"). Usarle con spirito critico è essenziale.", "warning"),
        ],
        "Un'AI impara aggiustando miliardi di parametri finché non riproduce bene gli schemi dei dati di addestramento. Non pensa, ma è bravissima a riconoscere pattern.",
    ),
    _story(
        "why-smartphones-fast",
        "tecnologia",
        "Perché uno smartphone è più potente di un PC di 20 anni fa?",
        ["smartphone", "potente"],
        "Un dispositivo che entra in tasca oggi è più veloce del supercomputer che portò l'uomo sulla Luna, di miliardi di volte.",
        "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?w=1200&q=80&auto=format&fit=crop",
        [
            ("La legge di Moore",
             "Nel 1965 Gordon Moore osservò che il numero di transistor su un chip raddoppia ogni due anni circa. Da allora la previsione si è avverata quasi sempre. Il risultato: i chip sono diventati miliardi di volte più potenti in 50 anni, e nel frattempo enormemente più economici.", "trending-up"),
            ("I transistor",
             "Il transistor è un piccolo interruttore elettrico che può stare acceso o spento (0 o 1). È il mattoncino di ogni computer. Un smartphone moderno contiene 10-15 miliardi di transistor su un chip grande come un'unghia. Nel 1971 un chip ne aveva 2.300.", "grid"),
            ("Come si fanno",
             "I chip vengono \"stampati\" con la fotolitografia: fasci di luce ultravioletta disegnano circuiti su fette di silicio con precisione di nanometri (miliardesimi di metro). Le macchine più avanzate (ASML in Olanda) costano oltre 200 milioni di dollari ciascuna.", "print"),
            ("Il segreto dello smartphone",
             "Un moderno smartphone integra sullo stesso chip: CPU (processore generale), GPU (grafica), NPU (intelligenza artificiale), modem 5G, chip di sicurezza. È un sistema-su-chip (SoC). Questa integrazione riduce distanze, consumi e permette prestazioni prima impossibili in un dispositivo piccolo.", "layers"),
            ("La fine di Moore",
             "Da qualche anno la miniaturizzazione dei transistor si sta avvicinando ai limiti fisici (atomi di silicio). L'industria sta cercando alternative: chip 3D impilati, materiali diversi (grafene), calcolo quantistico. I prossimi 20 anni saranno molto diversi dai precedenti.", "sparkles"),
        ],
        "Grazie alla legge di Moore, i chip raddoppiano potenza ogni 2 anni. Il tuo smartphone contiene miliardi di transistor su pochi millimetri quadrati.",
    ),
    _story(
        "what-is-blockchain",
        "tecnologia",
        "Cos'è la blockchain, in parole normali?",
        ["blockchain"],
        "Un registro digitale condiviso che nessuno può modificare da solo. Serve a Bitcoin, ma potrebbe cambiare molto altro.",
        "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un registro pubblico",
             "Immagina un enorme libro contabile che elenca tutte le transazioni mai avvenute. Ora immagina che copie identiche di questo libro siano distribuite su migliaia di computer nel mondo. Ogni volta che si aggiunge una pagina, tutte le copie si aggiornano insieme. Questa è la blockchain.", "book"),
            ("Blocchi collegati",
             "Le transazioni vengono raggruppate in \"blocchi\", ogni blocco contiene un \"riassunto matematico\" (hash) del blocco precedente. Se qualcuno prova a modificare un vecchio blocco, tutti i successivi hash non torneranno più. È come una catena: rompi un anello e tutti i successivi vanno rifatti.", "link"),
            ("Nessuno comanda",
             "Non c'è un'autorità centrale (banca, governo) che gestisce il registro. La rete di computer (\"nodi\") verifica ogni nuovo blocco e vota tramite un meccanismo di consenso. Nel Bitcoin il consenso avviene con il proof-of-work (chi risolve prima un problema matematico difficile pubblica il blocco).", "people"),
            ("Perché è potente",
             "In un sistema tradizionale, per fidarti di una transazione devi fidarti dell'intermediario (la banca). Con la blockchain la fiducia è nella matematica: puoi verificare tutto senza fidarti di nessuno. Utile per denaro, ma anche contratti, proprietà, votazioni, tracciabilità del cibo.", "shield-checkmark"),
            ("I limiti",
             "La blockchain è potente ma non risolve tutto. Le transazioni sono lente e costose (una transazione Bitcoin costa energia come una casa in un giorno). Non tutti i problemi richiedono un registro decentralizzato. Molti progetti \"blockchain\" hanno fallito perché il caso d'uso non lo richiedeva davvero.", "warning"),
        ],
        "La blockchain è un registro pubblico distribuito su migliaia di computer, matematicamente impossibile da modificare. Rimuove la necessità di intermediari.",
    ),
    _story(
        "how-3d-printing",
        "tecnologia",
        "Come fa una stampante 3D a creare oggetti dal nulla?",
        ["stampante", "3D"],
        "Non stampa: costruisce, strato dopo strato, come una pila di sottilissimi pancake. E può fare protesi, case, cibo, organi.",
        "https://images.unsplash.com/photo-1631624215749-b10b3dd7bca7?w=1200&q=80&auto=format&fit=crop",
        [
            ("L'idea",
             "Una stampante 3D non toglie materiale (come un tornio), aggiunge. Il modello digitale dell'oggetto viene \"affettato\" in centinaia di strati sottilissimi. La macchina deposita materiale strato dopo strato finché non ricostruisce l'oggetto completo.", "layers"),
            ("Il filamento",
             "Le stampanti 3D più diffuse usano fusione di filamento (FDM): un filo di plastica viene sciolto e rilasciato da un ugello mobile che disegna la forma dello strato attuale. Quando raffredda, il filo si solidifica. Uno strato dopo l'altro nasce un oggetto tridimensionale.", "flash"),
            ("Non solo plastica",
             "Esistono stampanti che usano resine liquide indurite con luce UV (SLA), polveri metalliche fuse da laser (SLM per titanio o acciaio inox), cemento per case, cioccolato, cellule staminali per organi bioingegnerizzati. La tecnica è la stessa, cambia il materiale.", "cube"),
            ("Applicazioni potenti",
             "Protesi personalizzate stampate in un giorno anziché mesi. Pezzi di ricambio unici per macchinari vecchi. Componenti aerospaziali con geometrie che non si potrebbero fare altrimenti. Case intere stampate in cemento in 24 ore. Ricambi ossei su misura. La stampa 3D non è futuro: è già presente.", "construct"),
            ("I limiti",
             "La stampa 3D è lenta rispetto alla produzione di massa. Un oggetto complesso può richiedere ore. La qualità finale spesso non regge il confronto con lavorazioni tradizionali. Ma dove serve personalizzazione, piccole quantità o geometrie impossibili, non ha rivali.", "warning"),
        ],
        "Una stampante 3D costruisce oggetti strato dopo strato, aggiungendo materiale invece che toglierlo. Può fare protesi, pezzi di ricambio, case e organi.",
    ),
]
