"""PAUSE v5 — ampliamento catalogo (parte C): Psicologia, Corpo umano, Cultura.
5 curiosità + 5 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ PSICOLOGIA ------------------------------
    mk("psicologia", "v5-brividi-musica",
       "Perché la musica ti fa venire i brividi?", ["brividi", "musica"],
       "Un ritornello che entra, una voce che sale, e la pelle si accappona. Il cervello ti sta ricompensando come se avessi mangiato o vinto qualcosa. Ma solo se sa aspettare.",
       "I brividi musicali nascono quando il cervello prevede cosa succederà nella musica e la previsione viene confermata o violata al momento giusto: rilascia dopamina, la stessa del cibo e del sesso. Circa metà delle persone li prova.",
       "",
       [
        ("Il cervello prevede sempre",
         "Ascoltando, il cervello indovina di continuo la nota successiva, sulla base di anni di canzoni. Quando l'attesa è tesa, una pausa prima del ritornello, una nota che sale, e poi si risolve, il circuito della ricompensa rilascia dopamina. È lo stesso segnale che ti dà il cibo quando hai fame."),
        ("Due ondate di dopamina",
         "Uno studio di Montreal con scansioni cerebrali ha mostrato che la dopamina arriva in due momenti: una parte nei secondi prima del passaggio atteso, per l'anticipazione, e una durante il picco. È il motivo per cui la stessa canzone ti dà i brividi anche alla centesima volta: sai cosa arriva, e l'attesa è parte del piacere."),
        ("Perché proprio la pelle",
         "L'ondata di emozione attiva il sistema nervoso autonomo, quello che gestisce anche la paura: il cuore accelera, i piccoli muscoli alla base dei peli si contraggono. È un residuo dei tempi in cui il pelo dritto serviva a sembrare più grandi o a tenere caldo. La musica lo dirotta su un'emozione che non ha nulla di pericoloso."),
        ("Non a tutti",
         "Solo il 50-55% delle persone prova i brividi musicali. Chi li prova ha in media più connessioni nervose tra la corteccia uditiva e le aree delle emozioni, e tende a punteggi più alti nel tratto di 'apertura all'esperienza'. Non è questione di gusti musicali: è un cablaggio."),
       ]),
    mk("psicologia", "v5-ricordi-flash",
       "Ricordi esattamente dove eri quel giorno? Probabilmente sbagli", ["ricordi", "sbagli"],
       "Tutti ricordano con nitidezza dove si trovavano quando è accaduto un evento storico. Il ricordo è vivido, sicuro, dettagliato. E spesso falso.",
       "I ricordi di eventi scioccanti, detti flashbulb, sembrano fotografie ma si deformano come tutti gli altri. La differenza è che la fiducia in essi non cala mai: dopo dieci anni il 40% dei dettagli è cambiato, ma la certezza è intatta.",
       "",
       [
        ("Un'istantanea che non lo è",
         "Il termine flashbulb, lampo di flash, nasce nel 1977 per descrivere i ricordi dell'assassinio di Kennedy: le persone ricordavano dov'erano, con chi, cosa facevano. La forte emozione sembrava aver scattato una foto. Ma nessuno aveva controllato se la foto fosse fedele."),
        ("L'esperimento del giorno dopo",
         "Dopo l'esplosione dello Space Shuttle Challenger nel 1986, uno psicologo fece scrivere ai suoi studenti, il giorno seguente, come avevano appreso la notizia. Due anni e mezzo dopo chiese loro di raccontarlo di nuovo. Un quarto dei racconti era completamente diverso, e la maggior parte conteneva errori importanti. Messi davanti al foglio scritto di loro pugno, molti dissero: 'È la mia scrittura, ma non è andata così'."),
        ("Perché si deformano",
         "Ogni volta che racconti un ricordo, lo ricostruisci e lo risalvi, e ogni ricostruzione può incorporare dettagli sentiti da altri, immagini viste in TV, la versione più drammatica. Gli eventi collettivi vengono raccontati moltissime volte: ecco perché finiscono per assomigliare a un film che tutti hanno visto piuttosto che a ciò che tu hai vissuto."),
        ("La fiducia non segue i fatti",
         "Lo studio più ampio, condotto su 3.000 americani dopo l'11 settembre, ha mostrato che dopo dieci anni circa il 40% dei dettagli era cambiato, ma la fiducia nel proprio ricordo restava altissima. Vivido e sicuro non significa vero. Vale anche per le testimonianze in tribunale, dove la certezza del testimone convince le giurie più della sua accuratezza."),
       ]),
    mk("psicologia", "v5-perche-ridiamo",
       "Perché ridiamo (e quasi mai per una battuta)?", ["ridiamo"],
       "Ridi trenta volte di più in compagnia che da solo. E se registri le conversazioni, scopri che quasi nessuna risata segue qualcosa di divertente. La risata non è per le barzellette.",
       "La risata è un segnale sociale più antico del linguaggio: dice 'sono con te, va tutto bene'. Solo il 10-20% delle risate segue qualcosa di umoristico. Anche i topi ridono, a frequenze che non sentiamo.",
       "",
       [
        ("Un segnale, non una reazione",
         "Il neuroscienziato Robert Provine ha osservato 1.200 episodi di risata in luoghi pubblici: meno del 20% seguiva una battuta. Il resto veniva dopo frasi come 'ci vediamo dopo' o 'ce l'ho fatta'. Chi parla ride più di chi ascolta. La risata punteggia il discorso e segnala appartenenza: ridiamo con le persone, non delle cose."),
        ("Più antica delle parole",
         "Scimpanzé e gorilla ridono quando giocano o vengono fatti loro il solletico, con un ansimare ritmico. I ratti emettono cinguettii ultrasonici quando giocano e cercano attivamente la mano che li fa ridere. La risata è nata come segnale di gioco, per dire 'ti sto inseguendo per finta', decine di milioni di anni prima che esistessero le battute."),
        ("Trenta volte più in compagnia",
         "Da solo, davanti a qualcosa di divertente, ridi poco: al massimo sorridi. La stessa cosa in un gruppo scatena risate fragorose. Per questo le sitcom aggiungevano le risate registrate e i comici lavorano meglio nelle sale piene: la risata è contagiosa perché il suo scopo è sincronizzare il gruppo."),
        ("A cosa serve davvero",
         "Ridere insieme abbassa il cortisolo, rilascia endorfine e aumenta la tolleranza al dolore misurabile. Nei gruppi che hanno riso insieme le persone si fidano di più e si rivelano più cose personali. Il solletico funziona solo se lo fa qualcun altro, e non a caso: la risata è, dall'inizio alla fine, una faccenda a due."),
       ]),
    mk("psicologia", "v5-ancoraggio",
       "Il primo numero che senti decide quanto pagherai", ["primo numero"],
       "Se ti chiedono se Gandhi è morto prima o dopo i 140 anni, e poi quanti anni aveva, risponderai un numero più alto di chi ha sentito 'prima o dopo i 9 anni'. Anche se sai che entrambi sono assurdi.",
       "L'ancoraggio è la tendenza a farsi influenzare dal primo valore disponibile, anche se irrilevante. Guida prezzi, trattative, stime e sentenze. Conoscerlo aiuta poco: l'unica difesa è produrre da soli un numero prima di sentire quello degli altri.",
       "",
       [
        ("La ruota truccata",
         "Nel 1974 Kahneman e Tversky fecero girare una ruota della fortuna che si fermava su 10 o 65 e poi chiesero quale percentuale di paesi africani fosse nell'ONU. Chi aveva visto 10 rispose in media 25%; chi aveva visto 65, 45%. Un numero casuale, dichiaratamente casuale, aveva spostato la stima di venti punti."),
        ("Come funziona",
         "Il cervello parte dal numero disponibile e si aggiusta da lì, ma si ferma troppo presto. Inoltre l'ancora attiva ricordi coerenti con essa: se senti 140 anni pensi alla longevità di Gandhi, se senti 9 alla sua fragilità. Anche i giudici esperti danno pene più lunghe se prima hanno lanciato un dado con numeri alti."),
        ("Lo usano su di te ogni giorno",
         "Il prezzo barrato accanto a quello scontato è un'ancora: 200 euro barrati rendono 120 una buona occasione, anche se il prodotto ne vale 80. Il menù mette un piatto carissimo in alto per far sembrare ragionevoli gli altri. Chi fa la prima offerta in una trattativa vince in media di più: fissa il centro della discussione."),
        ("La difesa",
         "Sapere dell'ancoraggio non ti immunizza: gli esperti ci cascano quanto gli altri. Funzionano due cose: decidere il tuo numero prima di sentire quello altrui, e cercare attivamente ragioni per cui l'ancora è sbagliata. Nelle trattative, fai tu la prima offerta, ambiziosa ma difendibile."),
       ]),
    mk("psicologia", "v5-noia",
       "Perché ci annoiamo (e a cosa serve la noia)?", ["annoiamo", "noia"],
       "In un esperimento, molte persone hanno preferito darsi scosse elettriche piuttosto che restare quindici minuti sole con i propri pensieri. La noia è così insopportabile per un motivo preciso.",
       "La noia è un segnale che l'attività corrente non vale l'attenzione che richiede: spinge a cercare qualcosa di più significativo. Chi la tollera è più creativo; chi la fugge con il telefono la rende cronica.",
       "",
       [
        ("Un allarme di attenzione sprecata",
         "La noia compare quando vuoi essere coinvolto in qualcosa ma non ci riesci: il compito è troppo facile, troppo difficile o troppo privo di senso. Il cervello segnala: 'questa attenzione potrebbe servire altrove'. È l'equivalente mentale della fame, e come la fame è spiacevole di proposito."),
        ("Le scosse elettriche",
         "In uno studio del 2014 all'Università della Virginia, i partecipanti dovevano restare 6-15 minuti in una stanza vuota, senza telefono, solo con i propri pensieri. Avevano la possibilità di darsi una piccola scossa elettrica, che in precedenza avevano definito spiacevole. Il 67% degli uomini e il 25% delle donne lo fecero almeno una volta. Uno, 190 volte."),
        ("Quello che la noia produce",
         "Nel 2013 due ricercatrici inglesi fecero copiare a un gruppo numeri da un elenco telefonico per quindici minuti, poi chiesero a tutti di inventare usi per due bicchieri di plastica. Gli annoiati produssero idee più numerose e più originali. La mente che vaga, senza compiti, connette cose lontane: è il cosiddetto default network, attivo proprio quando non stai facendo nulla."),
        ("Il telefono la peggiora",
         "Ogni volta che spegni la noia con uno scroll, il cervello impara che il sollievo è a un tocco di distanza e abbassa la soglia: ti annoi più in fretta e più spesso. Chi si annoia cronicamente riporta più ansia e meno soddisfazione. La noia va attraversata, non evitata: dopo pochi minuti scomodi il pensiero trova da solo dove andare."),
       ]),

    # ------------------------------ CORPO UMANO ------------------------------
    mk("corpo-umano", "v5-dita-acqua",
       "Perché le dita si arricciano nell'acqua?", ["dita", "arricciano"],
       "Dopo un bagno lungo i polpastrelli sembrano prugne secche. Per un secolo si è pensato che la pelle assorbisse acqua. Invece è il sistema nervoso, e ha uno scopo.",
       "Le rughe da acqua sono una reazione attiva dei nervi: i vasi sanguigni sotto la pelle si restringono e la pelle si ripiega. Il risultato funziona come i battistrada di un pneumatico: le dita bagnate afferrano meglio gli oggetti bagnati.",
       "",
       [
        ("Non è una spugna",
         "Se la pelle si gonfiasse di acqua, le rughe comparirebbero anche nelle persone con i nervi delle dita danneggiati. Invece non compaiono: i chirurghi lo usano come test per capire se un nervo è lesionato. Le rughe sono comandate dal sistema nervoso simpatico, lo stesso della sudorazione."),
        ("Il meccanismo",
         "L'acqua entra nei pori delle ghiandole del sudore e altera l'equilibrio salino. I nervi rispondono facendo contrarre i vasi sanguigni sotto la pelle: il volume dei polpastrelli diminuisce, ma la pelle in superficie resta la stessa e si ripiega. Bastano circa cinque minuti e l'effetto sparisce in dieci-venti una volta asciutti."),
        ("Come i pneumatici da pioggia",
         "Nel 2013 ricercatori di Newcastle fecero spostare a volontari biglie bagnate con dita lisce e con dita arricciate: con le rughe erano più rapidi del 12%. Con biglie asciutte, nessuna differenza. Le rughe formano canali che drenano l'acqua, esattamente come le scanalature di un pneumatico sull'asfalto bagnato."),
        ("Un adattamento antico",
         "Anche i macachi sviluppano le stesse rughe. L'ipotesi è che siano servite ai primati per muoversi su rocce bagnate e raccogliere cibo in acqua. Perché allora non le abbiamo sempre? Forse perché la pelle arricciata è meno sensibile e più fragile: meglio attivarla solo quando serve."),
       ]),
    mk("corpo-umano", "v5-capelli-bianchi",
       "Perché i capelli diventano bianchi?", ["capelli", "bianchi"],
       "Non 'diventano' bianchi: nascono già così. E la paura, quella di cui parlano le leggende, ha davvero un ruolo, scoperto solo nel 2020.",
       "Ogni capello nasce dal follicolo già colorato da cellule che producono melanina. Con l'età le cellule staminali che le rigenerano si esauriscono; il nuovo capello cresce senza pigmento. Lo stress può accelerare drasticamente l'esaurimento.",
       "",
       [
        ("Il colore si aggiunge alla base",
         "Il capello è fatto di cheratina, che di per sé è trasparente-giallastra. Nel follicolo, cellule chiamate melanociti iniettano granuli di melanina mentre il capello si forma: eumelanina per i bruni e neri, feomelanina per rossi e biondi. Il capello che vedi è morto: il colore che ha è quello che gli hanno dato alla nascita."),
        ("La riserva che finisce",
         "A ogni ciclo del capello, i melanociti muoiono e vengono rimpiazzati da una piccola riserva di cellule staminali nel follicolo. Con gli anni la riserva si consuma; quando finisce, il capello successivo cresce senza pigmento. Bianco non è un colore che si aggiunge: è la cheratina nuda. L'insieme di capelli bianchi e scuri dà il grigio."),
        ("La regola del 50-50-50",
         "In media a 50 anni il 50% delle persone ha il 50% di capelli bianchi. Ma la genetica domina: alcune popolazioni ingrigiscono a 25 anni, altre dopo i 60. Il fumo anticipa il processo, così come carenze di vitamina B12 e alcune malattie della tiroide."),
        ("La paura che imbianca, dimostrata",
         "Nel 2020 ricercatori di Harvard hanno sottoposto topi a stress e visto il pelo imbiancare in giorni. Il colpevole è la noradrenalina, rilasciata dai nervi del sistema di allarme: fa attivare e migrare via tutte le staminali del pigmento in un colpo solo, svuotando la riserva. Non tornano. La leggenda di Maria Antonietta incanutita in una notte è esagerata, ma il meccanismo esiste."),
       ]),
    mk("corpo-umano", "v5-fegato-rigenera",
       "Il fegato ricresce: puoi donarne metà e riaverlo intero", ["fegato", "ricresce"],
       "Nel mito, Prometeo era punito con un'aquila che gli divorava il fegato ogni giorno, e ogni notte il fegato ricresceva. I greci ci avevano azzeccato.",
       "Il fegato è l'unico organo umano capace di rigenerarsi quasi completamente: rimossi due terzi, torna alle dimensioni originali in poche settimane. Non ricresce la forma, ma il volume, con cellule che si moltiplicano su comando.",
       "",
       [
        ("Cinquecento lavori",
         "Il fegato pesa un chilo e mezzo e svolge oltre 500 funzioni: filtra il sangue, smonta alcol e farmaci, produce la bile per digerire i grassi, immagazzina zuccheri e vitamine, fabbrica le proteine della coagulazione. Un organo così centrale non poteva permettersi di essere fragile."),
        ("Le cellule che ricordano come dividersi",
         "Le cellule del fegato, gli epatociti, di solito riposano. Ma se una parte viene rimossa, segnali chimici nel sangue le svegliano e cominciano a dividersi tutte insieme, nel giro di 24 ore. In una settimana il volume perso è quasi recuperato; in uno o due mesi la funzione è completa. Non è vera rigenerazione della forma, come nelle salamandre: è crescita compensatoria."),
        ("Donare da vivi",
         "Un adulto sano può donare il lobo destro, fino al 60-70% del fegato, a un parente. Nel donatore la parte rimasta ricresce in sei-otto settimane; nel ricevente il pezzo trapiantato cresce fino alla misura adatta al suo corpo. Il primo trapianto da vivente, nel 1989, fu da madre a figlio."),
        ("Il limite",
         "La rigenerazione funziona finché il tessuto è sano. Danni ripetuti, da alcol, epatiti o grasso in eccesso, provocano cicatrici che sostituiscono il tessuto funzionante: è la cirrosi, che non torna indietro. Il fegato perdona molto, ma tiene il conto. E non manda segnali di dolore: quando fa male, è già tardi."),
       ]),
    mk("corpo-umano", "v5-cuore-stanca",
       "Perché il cuore non si stanca mai?", ["cuore", "stanca"],
       "Tre miliardi di battiti in una vita, senza un giorno di pausa. Se provi a stringere il pugno una volta al secondo, dopo dieci minuti smetti. Il cuore ha un altro tipo di muscolo.",
       "Il muscolo cardiaco ha cellule piene di mitocondri, brucia grassi in modo aerobico e riposa a ogni battito, tra una contrazione e l'altra. Sommando le pause, il cuore dorme circa metà della vita.",
       "",
       [
        ("Un muscolo diverso",
         "I muscoli delle braccia sono fatti di fibre che si affaticano perché producono acido lattico quando manca ossigeno. Il muscolo cardiaco ha un terzo del volume occupato da mitocondri, le centrali energetiche, contro il 2-5% dei muscoli comuni. Lavora quasi solo con ossigeno e non accumula scorie: non conosce l'indolenzimento."),
        ("Si riposa ogni secondo",
         "Ogni ciclo dura circa 0,8 secondi a riposo: 0,3 di contrazione, 0,5 di rilassamento in cui si riempie di sangue. Il cuore riposa più di quanto lavori. Il rilassamento è anche il momento in cui il muscolo stesso riceve sangue dalle coronarie, perché durante la contrazione le schiaccia."),
        ("Il proprio ritmo",
         "Il cuore non aspetta ordini dal cervello: un gruppo di cellule nell'atrio destro genera l'impulso da solo, circa 70 volte al minuto. Un cuore isolato, in una soluzione nutriente, continua a battere per ore. Il cervello si limita ad accelerarlo o frenarlo. Le cellule cardiache in una coltura si sincronizzano tra loro e pulsano insieme."),
        ("Cosa lo stanca davvero",
         "Il cuore soffre quando deve spingere contro resistenze troppo alte, la pressione arteriosa elevata, o quando le coronarie si restringono e gli tolgono ossigeno. Allora il muscolo si ispessisce, si irrigidisce o muore in parte. L'esercizio regolare fa il contrario: rende il cuore più grande, più efficiente e più lento a riposo, con anni di battiti in più a disposizione."),
       ]),
    mk("corpo-umano", "v5-giramento-testa",
       "Perché gira la testa dopo aver girato su te stesso?", ["gira la testa"],
       "Ti fermi, ma il mondo continua a ruotare per qualche secondo. Nelle tue orecchie c'è un liquido che non ha ancora capito che ti sei fermato.",
       "L'equilibrio si basa su tre canali pieni di liquido nell'orecchio interno. Girando, il liquido si mette in moto e continua a scorrere anche dopo che ti sei fermato: il cervello riceve il segnale di rotazione senza che gli occhi lo confermino, e va in conflitto.",
       "",
       [
        ("Tre anelli nell'orecchio",
         "Dietro il timpano, nell'orecchio interno, ci sono tre canali semicircolari orientati sui tre assi dello spazio, pieni di un liquido chiamato endolinfa. Quando la testa gira, il liquido per inerzia resta indietro e piega minuscole ciglia che segnalano al cervello la rotazione. È il sensore di movimento più antico dei vertebrati."),
        ("Il liquido che non si ferma",
         "Se giri per diversi secondi, l'endolinfa raggiunge la stessa velocità della testa e le ciglia si raddrizzano: il cervello smette di percepire la rotazione. Quando ti fermi di colpo, il liquido continua a girare per inerzia e piega le ciglia nella direzione opposta. Il cervello riceve: 'stai girando dall'altra parte'."),
        ("Gli occhi tradiscono",
         "Il cervello ordina agli occhi di compensare la rotazione che crede in corso, muovendoli a scatti: è il nistagmo che si vede nelle persone appena scese da una giostra. Gli occhi però vedono una stanza ferma. Il conflitto tra orecchio e vista è la sensazione di vertigine, e spesso di nausea: il cervello sospetta un veleno e prepara il vomito."),
        ("Come fanno i ballerini",
         "I ballerini e i pattinatori non hanno orecchie diverse: hanno un cervello allenato. Anni di piroette riducono le risposte del cervelletto ai segnali dell'orecchio interno, che vengono soppressi se non confermati dalla vista. Anche il trucco di fissare un punto e far scattare la testa a ogni giro limita il tempo in cui il liquido si mette in moto."),
       ]),

    # ------------------------------ CULTURA ------------------------------
    mk("cultura", "v5-applausi",
       "Perché battiamo le mani per dire che qualcosa ci è piaciuto?", ["battiamo le mani"],
       "In tutto il mondo, dal teatro allo stadio, il consenso si esprime allo stesso modo: mani che sbattono. Un gesto rumoroso, poco elegante, universale. E contagioso come uno sbadiglio.",
       "L'applauso è antico quanto Roma, dove era codificato e persino a pagamento. Funziona perché è il modo più semplice per un gruppo di produrre un suono collettivo. La sua durata dipende dal gruppo, non dalla qualità dello spettacolo.",
       "",
       [
        ("Roma: l'applauso su misura",
         "A Roma il pubblico aveva un repertorio: schioccare le dita per un gradimento tiepido, battere le mani per un successo, sventolare il lembo della toga per un trionfo. L'imperatore Nerone si portava dietro cinquemila soldati addestrati ad applaudire in tre stili diversi, e pretendeva applausi anche quando cantava lui."),
        ("La claque a pagamento",
         "Nel Cinquecento a Parigi nacque un mestiere: il claqueur, pagato dai teatri per applaudire al momento giusto e trascinare il pubblico. Nel Settecento esistevano agenzie con listini: tanto per una risata, tanto per un 'bis', tanto per le lacrime. L'Opéra di Parigi ne ebbe una ufficiale fino agli anni Trenta del Novecento."),
        ("Perché si diffonde",
         "Uno studio svedese del 2013 ha filmato gruppi durante gli applausi: la probabilità che una persona cominci a battere le mani dipende da quante intorno lo stanno già facendo, non da quanto le è piaciuto lo spettacolo. E si smette allo stesso modo: quando i primi si fermano, gli altri seguono in pochi secondi. La durata di un applauso misura il contagio, non l'entusiasmo."),
        ("Le alternative",
         "Non ovunque si applaude allo stesso modo. Nei parlamenti di tradizione britannica si batte la mano sul banco; nella lingua dei segni si sventolano le mani in aria; nelle chiese pentecostali si grida. E in molti paesi applaudire all'atterraggio di un aereo è normale, in altri imbarazzante: lo stesso gesto, con confini invisibili."),
       ]),
    mk("cultura", "v5-pizza-margherita",
       "La pizza Margherita non fu inventata per la regina", ["Margherita", "regina"],
       "La storia è perfetta: 1889, la regina Margherita a Napoli, il pizzaiolo Raffaele Esposito che crea una pizza tricolore in suo onore. Perfetta, e quasi certamente costruita a posteriori.",
       "Pizze con pomodoro, mozzarella e basilico esistevano a Napoli decenni prima del 1889. Il documento che attesta la visita reale è stato messo in discussione, e il nome Margherita probabilmente indicava la forma a fiore delle fette di mozzarella.",
       "",
       [
        ("La leggenda ufficiale",
         "Nel giugno 1889 il re Umberto I e la regina Margherita sono a Napoli. Il pizzaiolo Raffaele Esposito prepara tre pizze per la sovrana, che preferisce quella con pomodoro, mozzarella e basilico, i colori della bandiera. Una lettera di ringraziamento della Casa Reale è ancora esposta nella pizzeria Brandi. La storia entra in tutti i libri."),
        ("Le pizze esistevano già",
         "Nel 1830 un libro sulle usanze napoletane descrive pizze con 'mozzarella e basilico' e con 'pomodoro'. Nel 1866 Francesco De Bourcard elenca tra le pizze comuni quella 'con pomidoro e mozzarella e basilico'. La combinazione era popolare da almeno mezzo secolo prima che la regina arrivasse."),
        ("La lettera sospetta",
         "Lo storico Zachary Nowak ha esaminato il documento del 1889: la carta intestata è diversa da quella usata dalla Casa Reale nello stesso periodo, la firma del capo dei servizi di bocca non coincide con quelle autentiche e il timbro è insolito. Non è la prova di un falso, ma è abbastanza per non citarla come certezza."),
        ("Da dove viene il nome",
         "Una spiegazione più semplice: le fette di mozzarella disposte a raggiera sulla pizza ricordano i petali di una margherita. Anche una pizza 'alla mastunicola' e altre prendevano nome dall'aspetto. La storia della regina è probabilmente un'operazione di marketing riuscitissima, che ha trasformato un piatto di strada nel simbolo dell'Italia unita."),
       ]),
    mk("cultura", "v5-pollice-alzato",
       "Il pollice alzato non salvava i gladiatori", ["pollice alzato"],
       "Nei film il pubblico decide con il pollice se il gladiatore vive o muore: su per la vita, giù per la morte. È una scena che i romani non avrebbero riconosciuto.",
       "Le fonti romane parlano di 'pollice girato' per la condanna e di 'pollice premuto' nel pugno per la grazia, e il significato esatto è dibattuto. L'immagine moderna nasce da un quadro del 1872. Oggi il gesto cambia senso da paese a paese.",
       "",
       [
        ("Cosa dicono i testi",
         "Il poeta Giovenale scrive che la folla ordinava di uccidere 'con il pollice girato', pollice verso, senza dire in che direzione. Plinio e altri usano 'premere il pollice', probabilmente chiuderlo nel pugno, come segno di favore. Nessuna fonte antica descrive il pollice alzato come salvezza."),
        ("Un quadro cambia tutto",
         "Nel 1872 il pittore francese Jean-Léon Gérôme dipinge Pollice Verso: vestali che puntano il pollice in basso verso un gladiatore sconfitto. Il quadro ha un successo enorme e fissa la scena nell'immaginario. Ridley Scott ha dichiarato di aver deciso di girare Il gladiatore dopo aver visto proprio quel dipinto."),
        ("Come è diventato positivo",
         "Il pollice su come 'tutto bene' si diffonde nel Novecento, probabilmente dai piloti americani della Seconda guerra mondiale che lo usavano per segnalare ai meccanici che erano pronti al decollo. I soldati lo portarono in Europa, e Hollywood fece il resto. Il gesto di 'mi piace' di Facebook ha fatto il giro del mondo con quel significato."),
        ("Non ovunque",
         "In Iran, Iraq, Afghanistan e parti dell'Africa occidentale il pollice alzato è un insulto volgare. In Grecia era offensivo fino a pochi decenni fa. In Germania e Ungheria, in un bar, significa semplicemente 'uno': alzarlo ordinando la birra ti porterà una birra, non un complimento. E il gesto del sub significa 'risalgo', non 'tutto bene'."),
       ]),
    mk("cultura", "v5-natale-25",
       "Perché il Natale si festeggia il 25 dicembre?", ["25 dicembre"],
       "I Vangeli non dicono in che giorno nacque Gesù, e i primi cristiani non lo festeggiavano affatto. La data arrivò tre secoli dopo, e la scelta ha almeno due spiegazioni in competizione.",
       "La data del 25 dicembre appare per la prima volta a Roma nel 336. Potrebbe derivare dal calcolo che poneva il concepimento al 25 marzo, oppure dalla sovrapposizione con le feste romane del solstizio d'inverno e del Sole Invitto.",
       "",
       [
        ("Una festa che non esisteva",
         "Per i primi cristiani la data di nascita non aveva importanza: si celebrava la morte e la resurrezione. Nel II secolo circolavano ipotesi diverse: 20 maggio, 19 aprile, 17 novembre. Il primo documento che mette il Natale al 25 dicembre è un calendario romano del 336, sotto l'imperatore Costantino."),
        ("L'ipotesi del calcolo",
         "Alcuni teologi antichi ragionavano così: Gesù morì il 25 marzo secondo il loro calcolo, e le vite perfette dovevano durare un numero intero di anni, quindi fu concepito lo stesso giorno. Nove mesi dopo il 25 marzo è il 25 dicembre. Nella Chiesa d'Oriente il calcolo dava il 6 aprile e il Natale cadde il 6 gennaio, ancora oggi data dell'Epifania."),
        ("L'ipotesi del Sole",
         "Il 25 dicembre nel calendario romano era il solstizio d'inverno e dal 274 la festa del Sol Invictus, il Sole Invitto, istituita dall'imperatore Aureliano. Il giorno in cui la luce ricomincia a crescere era perfetto per celebrare la nascita di chi si definiva 'luce del mondo', e assorbiva una festa popolare già esistente."),
        ("I regali e l'albero",
         "I Saturnali romani, dal 17 al 23 dicembre, prevedevano banchetti, scambio di doni e candele. L'albero decorato arriva dalla Germania del Cinquecento e si diffonde nell'Ottocento grazie alla regina Vittoria e al marito tedesco. Babbo Natale rosso e panciuto è del 1931, disegnato per una pubblicità della Coca-Cola: il Natale è una stratificazione di duemila anni."),
       ]),
    mk("cultura", "v5-salute-starnuto",
       "Perché diciamo 'salute' quando qualcuno starnutisce?", ["salute", "starnutisce"],
       "Nessuno dice nulla se tossisci o ti soffi il naso. Ma allo starnuto scatta una parola automatica, in quasi ogni lingua del mondo. Il motivo è antico e un po' inquietante.",
       "Rispondere allo starnuto è un'usanza documentata già nell'antica Grecia e Roma. Si temeva che l'anima uscisse con il soffio o che lo starnuto annunciasse la peste; la formula era una protezione. Ogni lingua ha scelto la propria.",
       "",
       [
        ("Un presagio, non un raffreddore",
         "Nell'Odissea uno starnuto di Telemaco è letto come un segno favorevole degli dèi. Per greci e romani lo starnuto era un messaggio: veniva dalla testa, sede dello spirito, e non si poteva controllare. I romani rispondevano 'Salve' o 'Iuppiter conservet', che Giove ti conservi."),
        ("L'anima che scappa",
         "In molte culture si credeva che lo starnuto potesse far uscire l'anima dal corpo, o far entrare uno spirito maligno nell'attimo in cui la bocca era aperta e il corpo indifeso. La benedizione richiudeva la porta. È lo stesso motivo per cui in molte tradizioni ci si copre la bocca sbadigliando."),
        ("La peste e il papa",
         "Una tradizione fa risalire il 'Dio ti benedica' a papa Gregorio Magno, che durante la peste del 590 avrebbe ordinato di benedire chi starnutiva, perché lo starnuto era considerato il primo sintomo. Documenti coevi non lo confermano, ma la storia mostra come lo starnuto fosse associato alla malattia mortale più temuta."),
        ("Un giro del mondo",
         "Italiani e spagnoli augurano salute; tedeschi 'Gesundheit', anch'essa salute; inglesi 'bless you'; turchi 'vivi a lungo'; in arabo si risponde 'lode a Dio' e chi ha starnutito replica con una benedizione. In Giappone e Corea di solito non si dice nulla: è l'unica grande cultura in cui lo starnuto passa in silenzio."),
       ]),
]

LESSONS = [
    # ------------------------------ PSICOLOGIA ------------------------------
    L("psicologia", "v5-lez-distorsioni",
      "Le 4 distorsioni del pensiero che ti fanno stare peggio", ["distorsioni"],
      "Non è la situazione a farti soffrire, ma quello che il pensiero ci aggiunge. Ci sono quattro errori automatici che tutti facciamo, e riconoscerli è metà del lavoro.",
      "Riconoscere le distorsioni cognitive più comuni nei propri pensieri e imparare a metterle in discussione.",
      "Le distorsioni più frequenti sono il pensiero tutto-o-nulla, la catastrofizzazione, la lettura del pensiero e la generalizzazione. Si riconoscono dalle parole (sempre, mai, sicuramente) e si smontano chiedendo: quali prove ho?",
      [
       ("Passo 1 — Tutto o nulla",
        "'Se non è perfetto, è un fallimento.' Il pensiero in bianco e nero elimina le sfumature in cui vive la realtà. Segnali: parole come 'completamente', 'totalmente', 'un disastro'. Domanda utile: su una scala da 0 a 100, dove sta davvero? Raramente agli estremi."),
       ("Passo 2 — La catastrofe",
        "Un ritardo diventa un licenziamento, un mal di testa una malattia grave. La mente salta all'esito peggiore e lo tratta come probabile. Domanda utile: qual è lo scenario più probabile, non il peggiore? E se il peggiore accadesse davvero, cosa farei? Spesso la risposta è più gestibile della paura."),
       ("Passo 3 — Leggere nel pensiero",
        "'Sicuramente pensa che sono un incapace.' Attribuiamo agli altri giudizi che non abbiamo verificato, quasi sempre negativi e quasi sempre su di noi. Domanda utile: quali prove ho che pensi questo? Ci sono altre spiegazioni per il suo comportamento? Le persone pensano a noi molto meno di quanto crediamo."),
       ("Passo 4 — Generalizzare da un caso",
        "Un rifiuto diventa 'nessuno mi vuole', un errore 'sbaglio sempre'. Parole spia: sempre, mai, tutti, nessuno. Domanda utile: è vero al 100%? Trova una sola eccezione e la generalizzazione crolla. Scrivere il pensiero su carta e rileggerlo come se fosse di un amico è il modo più veloce per vederne la distorsione."),
      ]),
    L("psicologia", "v5-lez-feedback",
      "Dare un feedback che viene ascoltato: il metodo in 4 passi", ["feedback"],
      "Il 'panino' con complimento-critica-complimento non funziona: le persone sentono solo la critica e imparano a diffidare dei complimenti. Serve un metodo che sia chiaro senza ferire.",
      "Formulare una critica costruttiva che venga accolta invece che respinta, separando fatti, effetti e richieste.",
      "Descrivi il comportamento specifico e osservabile, spiega l'effetto che ha avuto, chiedi cosa ne pensa l'altro, concordate un cambiamento concreto. Mai sul carattere, sempre sui fatti, il prima possibile e in privato.",
      [
       ("Passo 1 — Il fatto, non la persona",
        "'Sei disorganizzato' è un giudizio sulla persona e scatena la difesa. 'Il report di martedì è arrivato due giorni dopo la scadenza' è un fatto che non si può negare. Descrivi ciò che una telecamera avrebbe registrato: cosa, quando, dove. Niente 'sempre', niente 'come al solito'."),
       ("Passo 2 — L'effetto",
        "Spiega le conseguenze concrete: 'Il cliente ha chiamato due volte e ho dovuto rimandare la presentazione.' L'effetto dà un motivo alla critica e la rende un problema condiviso, non un attacco. Se riguarda te, usa la prima persona: 'mi sono trovato in difficoltà', non 'mi hai messo in difficoltà'."),
       ("Passo 3 — Ascolta prima di proporre",
        "Chiedi: 'Cosa è successo dal tuo punto di vista?' e taci. Spesso c'è un motivo che non conosci. Anche quando non c'è, la persona che è stata ascoltata è disposta a cambiare; quella che si è sentita processata no. Il feedback è un dialogo, non un verdetto."),
       ("Passo 4 — Un accordo concreto",
        "Chiudi con un'azione verificabile: 'La prossima volta, se vedi che non ce la fai, avvisami il giorno prima.' Poi lascia andare. Regole di contorno: il prima possibile, entro pochi giorni; in privato, mai davanti ad altri; e i complimenti sinceri vanno dati a parte, quando sono meritati, non come anestetico prima della critica."),
      ]),
    L("psicologia", "v5-lez-motivazione",
      "Motivazione: perché i premi a volte la uccidono", ["motivazione", "premi"],
      "Bambini che amavano disegnare hanno smesso di farlo dopo essere stati premiati per i loro disegni. Il premio aveva trasformato un piacere in un lavoro.",
      "Distinguere motivazione intrinseca ed estrinseca e capire come alimentare la prima in sé stessi e negli altri.",
      "La motivazione intrinseca nasce da tre bisogni: sentirsi competenti, autonomi e connessi agli altri. I premi esterni funzionano per compiti noiosi ma spengono l'interesse per quelli creativi. Feedback e scelta funzionano meglio del denaro.",
      [
       ("Passo 1 — L'esperimento dei pennarelli",
        "Nel 1973 a Stanford si osservarono bambini che disegnavano spontaneamente. A un gruppo fu promesso un diploma per i disegni. Due settimane dopo, senza più premi, quel gruppo disegnava la metà del tempo rispetto a chi non era stato premiato. Il premio aveva detto loro: 'questa è una cosa che si fa per ottenere qualcos'altro'."),
       ("Passo 2 — Tre bisogni",
        "Secondo la teoria dell'autodeterminazione, la motivazione dal di dentro cresce quando ci sentiamo competenti (vediamo progressi), autonomi (abbiamo scelto noi) e connessi (conta per qualcuno). Togli uno dei tre e l'energia cala, qualunque sia il compenso."),
       ("Passo 3 — Quando i premi funzionano",
        "Per compiti ripetitivi e senza interesse intrinseco, come inserire dati, un bonus aumenta la produttività. Per compiti che richiedono creatività o soluzione di problemi, ricompense alte peggiorano le prestazioni: l'attenzione si restringe sul premio. Anche i premi inattesi, dati dopo, fanno meno danni di quelli promessi prima."),
       ("Passo 4 — Cosa fare in pratica",
        "Con te stesso: rendi visibili i progressi, scegli come fare le cose anche quando non puoi scegliere cosa, collega il compito a qualcuno a cui serve. Con figli o colleghi: sostituisci 'se fai X ti do Y' con feedback specifico su cosa hanno fatto bene e lascia margini di scelta. Il lavoro pagato non è il problema: lo è il pagamento usato come unico motivo."),
      ]),
    L("psicologia", "v5-lez-decisioni",
      "Prendere una decisione difficile: 4 strumenti che funzionano", ["decisione"],
      "Cambiare lavoro, trasferirsi, chiudere una relazione. Quando le opzioni pesano uguale la mente gira in tondo per settimane. Questi strumenti la fanno uscire dal cerchio.",
      "Applicare tecniche semplici per chiarire una decisione bloccata e ridurre il rimpianto successivo.",
      "Immagina la scelta fatta per dieci minuti, dieci mesi e dieci anni. Chiediti cosa consiglieresti a un amico nella stessa situazione. Definisci il peggior caso realistico. Fissa una scadenza e accetta che non esiste la scelta perfetta.",
      [
       ("Passo 1 — 10 minuti, 10 mesi, 10 anni",
        "Per ogni opzione chiediti: come mi sentirò tra dieci minuti, tra dieci mesi, tra dieci anni? Il primo orizzonte cattura la paura immediata, che tende a dominare; il terzo la mette in proporzione. Molte scelte spaventose a dieci minuti sono irrilevanti a dieci anni, e viceversa."),
       ("Passo 2 — Il consiglio all'amico",
        "Racconta la situazione come se fosse di un amico e chiediti cosa gli diresti. Con gli altri siamo più lucidi: vediamo i fatti, non la nostra ansia. La ricerca mostra che ragioniamo meglio sui problemi altrui che sui nostri, e il trucco della terza persona sposta il punto di vista quanto basta."),
       ("Passo 3 — Il peggior caso realistico",
        "Scrivi cosa succederebbe se andasse male, in modo concreto e non catastrofico. Poi: potrei recuperare? In quanto tempo? Quasi tutte le decisioni sono reversibili in qualche misura, e saperlo abbassa la posta. Le poche davvero irreversibili meritano più tempo; le altre, meno di quanto gliene diamo."),
       ("Passo 4 — Scadenza e accettazione",
        "Fissa una data entro cui decidere e raccogli solo le informazioni che possono cambiare la scelta, non tutte quelle disponibili. Poi decidi e smetti di ricalcolare: il rimpianto nasce dal continuare a confrontare, non dalla scelta. Chi decide accettando che l'opzione perfetta non esiste è più soddisfatto, a parità di risultato, di chi cerca la migliore in assoluto."),
      ]),
    L("psicologia", "v5-lez-stress",
      "Come funziona lo stress, e come usarlo invece di subirlo", ["stress"],
      "Il cuore batte forte prima di un esame: puoi leggerlo come 'sto crollando' o come 'il corpo mi prepara'. La differenza cambia la prestazione, e persino la salute.",
      "Capire la risposta fisiologica allo stress, distinguere quello acuto da quello cronico e adottare due strategie per gestirlo.",
      "Lo stress acuto è una risposta utile che mobilita energia. Diventa dannoso quando è cronico e senza recupero. Interpretarlo come attivazione anziché minaccia migliora la prestazione; il recupero attivo (movimento, sonno, relazioni) lo smaltisce.",
      [
       ("Passo 1 — L'allarme",
        "Davanti a una sfida, l'amigdala attiva in mezzo secondo il sistema nervoso simpatico: adrenalina, cuore accelerato, pupille dilatate, glucosio nel sangue. Dopo qualche minuto arriva il cortisolo, che mantiene l'energia disponibile. È il sistema che ha permesso ai nostri antenati di scappare dai predatori, e funziona ancora benissimo."),
       ("Passo 2 — Acuto contro cronico",
        "Una scarica di stress seguita da recupero rende più forte, come un allenamento. Il problema è quando l'allarme non si spegne: scadenze continue, preoccupazioni notturne, nessuna pausa. Il cortisolo cronico indebolisce il sistema immunitario, disturba il sonno, deposita grasso addominale e riduce la memoria. Non è lo stress a fare male: è la sua durata senza recupero."),
       ("Passo 3 — Cambiare etichetta",
        "In uno studio di Harvard, studenti istruiti a interpretare il batticuore come 'il corpo che si prepara' hanno ottenuto risultati migliori a un esame e mostrato vasi sanguigni più rilassati rispetto a chi lo leggeva come ansia. Il corpo fa la stessa cosa; ciò che cambia è se lo consideri un alleato. Prima di una prova, di' a te stesso: 'sono attivato', non 'sono agitato'."),
       ("Passo 4 — Il recupero attivo",
        "Lo stress è progettato per scaricarsi con il movimento: una camminata veloce dopo una giornata tesa brucia l'adrenalina accumulata. Il sonno ripristina i livelli di cortisolo. Il contatto con persone fidate rilascia ossitocina, che lo contrasta direttamente. Alcol e schermi fino a tardi sembrano rilassare ma impediscono proprio i tre meccanismi che smaltiscono davvero lo stress."),
      ]),

    # ------------------------------ CORPO UMANO ------------------------------
    L("corpo-umano", "v5-lez-idratazione",
      "Quanta acqua bere davvero: la regola dei due litri è un mito", ["acqua", "due litri"],
      "Otto bicchieri al giorno. Lo hai sentito mille volte, e non ha nessuna base scientifica. Il tuo corpo ha un sistema molto più preciso.",
      "Capire da dove viene il fabbisogno di acqua, come riconoscere la disidratazione e quando serve davvero bere di più.",
      "Il fabbisogno varia da 1,5 a oltre 3 litri secondo peso, clima e attività, e circa il 20-30% arriva dal cibo. La sete è un indicatore affidabile negli adulti sani; il colore delle urine è il controllo più semplice. Bere troppo è possibile e pericoloso.",
      [
       ("Passo 1 — Da dove viene la regola",
        "Nel 1945 un comitato americano scrisse che un adulto ha bisogno di circa 2,5 litri di acqua al giorno, aggiungendo che 'la maggior parte è già contenuta nei cibi'. La seconda frase si perse per strada. Frutta, verdura, minestre, ma anche pane e carne contengono acqua: un'alimentazione normale ne fornisce quasi un litro."),
       ("Passo 2 — La sete funziona",
        "Il cervello misura la concentrazione del sangue con una precisione dell'1%: quando sale, scatta la sete e i reni trattengono acqua. Negli adulti sani questo sistema basta. Fa eccezione chi ha più di 70 anni, in cui la sete si attenua, e i bambini piccoli durante febbre o caldo: lì va offerta acqua senza aspettare che la chiedano."),
       ("Passo 3 — Il controllo del colore",
        "Urine giallo paglierino: idratazione buona. Giallo scuro o ambra: bevi. Trasparenti come acqua: stai probabilmente bevendo più del necessario. Attenzione a vitamine e barbabietole che alterano il colore. Con caldo intenso, sport prolungato, febbre o diarrea il fabbisogno sale molto e la sete può non tenere il passo: lì si beve in anticipo."),
       ("Passo 4 — Quando troppo fa male",
        "Bere litri in poche ore senza sudare diluisce il sodio nel sangue: le cellule si gonfiano, incluse quelle del cervello. È l'iponatremia, che ha ucciso maratoneti e partecipanti a gare di bevute. Il tè e il caffè contano come acqua: l'effetto diuretico della caffeina è minimo nei consumatori abituali. La regola vera: bevi quando hai sete, controlla il colore, aumenta quando sudi."),
      ]),
    L("corpo-umano", "v5-lez-digestione",
      "Il viaggio di un boccone: la digestione in 4 tappe", ["digestione"],
      "Da quando mordi una mela a quando ne esce l'ultimo residuo passano uno o due giorni e nove metri di tubo. Ogni tratto fa un lavoro diverso.",
      "Seguire il percorso del cibo attraverso l'apparato digerente e capire cosa succede in ogni tappa.",
      "Bocca: masticazione e primi enzimi. Stomaco: acido e rimescolamento, 2-4 ore. Intestino tenue: la vera digestione e quasi tutto l'assorbimento, 6 metri. Colon: acqua recuperata, batteri al lavoro, 1-2 giorni.",
      [
       ("Passo 1 — Bocca ed esofago",
        "La digestione inizia prima del morso: il profumo fa produrre saliva, che contiene un enzima per gli amidi. Per questo il pane masticato a lungo diventa dolce. Il boccone, ridotto in poltiglia, scende per l'esofago spinto da onde muscolari: funziona anche a testa in giù. Alla base una valvola si apre e si richiude per non far risalire l'acido."),
       ("Passo 2 — Lo stomaco",
        "Un sacco muscoloso che rimescola il cibo con acido cloridrico a pH 2 e enzimi per le proteine. L'acido uccide i batteri e srotola le proteine per farle attaccare. La parete si protegge con uno strato di muco rinnovato di continuo. Dopo 2-4 ore, una poltiglia acida chiamata chimo passa a piccole dosi nell'intestino. I grassi rallentano tutto; i liquidi escono in minuti."),
       ("Passo 3 — L'intestino tenue",
        "Sei metri ripiegati con una superficie interna, tra pieghe e villi, paragonabile a un campo da tennis. Qui arrivano la bile del fegato, che emulsiona i grassi, e gli enzimi del pancreas, che spezzano tutto in mattoncini: zuccheri semplici, aminoacidi, acidi grassi. I villi li assorbono nel sangue. Il 90% dei nutrienti passa da qui, in 3-5 ore."),
       ("Passo 4 — Il colon",
        "Ciò che resta, fibre, acqua e cellule morte, entra nel colon. In 12-48 ore l'acqua viene recuperata e i trilioni di batteri residenti fermentano le fibre producendo gas e acidi grassi utili alle cellule intestinali. Il colore delle feci viene dalla bile degradata. Il tempo totale, da 24 a 72 ore, dipende da fibre, acqua e movimento: tre cose che puoi controllare."),
      ]),
    L("corpo-umano", "v5-lez-muscoli",
      "Come crescono i muscoli (e perché il dolore del giorno dopo non è acido lattico)", ["muscoli"],
      "Sollevi pesi, i muscoli si stancano, e due giorni dopo fanno male. Ma il muscolo non cresce in palestra: cresce mentre dormi, riparando piccoli danni.",
      "Capire il meccanismo dell'ipertrofia muscolare, cosa serve davvero per allenarsi con efficacia e cosa causa i dolori post-allenamento.",
      "Lo sforzo crea microlesioni nelle fibre; nelle 24-72 ore successive il corpo le ripara aggiungendo proteine, rendendole più grosse. Servono carico crescente, proteine e sonno. L'indolenzimento del giorno dopo è infiammazione da riparazione, non acido lattico.",
      [
       ("Passo 1 — Il danno utile",
        "Le fibre muscolari sono fasci di filamenti proteici che scorrono gli uni sugli altri. Uno sforzo vicino al limite, specialmente nella fase in cui il muscolo si allunga sotto carico, produce microscopiche rotture. Non è un incidente: è il segnale che avvia la ricostruzione, con un margine in più per la prossima volta."),
       ("Passo 2 — La riparazione",
        "Nelle 24-72 ore dopo, cellule satellite si fondono alle fibre danneggiate e il corpo sintetizza nuove proteine contrattili. La fibra diventa più spessa: è l'ipertrofia. Avviene a riposo, soprattutto nel sonno profondo quando l'ormone della crescita è al massimo. Allenare lo stesso muscolo ogni giorno interrompe la riparazione."),
       ("Passo 3 — Cosa serve davvero",
        "Tre cose. Un carico che aumenti nel tempo, in peso o ripetizioni: il muscolo si adatta solo a ciò che non sa ancora fare. Proteine, circa 1,6 grammi per chilo di peso al giorno, distribuite nei pasti: oltre non serve. Sonno, sette-nove ore. Gli integratori sono dettagli; il caffè prima dell'allenamento ha più prove a favore della maggior parte di essi."),
       ("Passo 4 — Il dolore del giorno dopo",
        "L'acido lattico viene smaltito entro un'ora dalla fine dello sforzo: non può essere lui. Il dolore che compare dopo 24-48 ore è infiammazione dei tessuti in riparazione, più forte con esercizi nuovi o in discesa. Non è indice di un buon allenamento né necessario per crescere. Muoversi leggermente lo attenua; il riposo assoluto lo prolunga."),
      ]),
    L("corpo-umano", "v5-lez-etichetta-nutrizionale",
      "Leggere un'etichetta alimentare in 4 mosse", ["etichetta"],
      "Sulla confezione c'è tutto quello che ti serve per decidere. Il problema è che è scritto perché tu guardi altrove: la parte davanti, con le promesse.",
      "Interpretare la tabella nutrizionale e la lista ingredienti di un prodotto confezionato per confrontare alternative.",
      "Ignora il fronte. Leggi la lista ingredienti: i primi tre sono ciò che stai mangiando davvero. Confronta i valori per 100 grammi, non per porzione. Controlla zuccheri, sale e grassi saturi con tre soglie semplici.",
      [
       ("Passo 1 — Il fronte è pubblicità",
        "'Senza zuccheri aggiunti', 'ricco di fibre', 'con vero frutto': frasi regolamentate ma scelte per distrarre. Un prodotto 'senza zuccheri aggiunti' può essere pieno di zuccheri della frutta concentrata; uno 'light' può contenere più zucchero della versione normale per compensare il grasso tolto. Gira la confezione."),
       ("Passo 2 — I primi tre ingredienti",
        "Gli ingredienti sono elencati in ordine di quantità decrescente. I primi tre costituiscono la maggior parte del prodotto. Se lo zucchero, con i suoi nomi alternativi come sciroppo di glucosio, destrosio, maltosio, succo concentrato, compare tra i primi, è un dolce, qualunque cosa dica il fronte. Una lista lunga con molti nomi chimici indica un prodotto molto trasformato."),
       ("Passo 3 — Confronta per 100 grammi",
        "Le porzioni sono decise dal produttore e spesso irrealistiche: 25 grammi di cereali, 5 biscotti. La colonna per 100 grammi è l'unica che permette di confrontare due prodotti. Soglie pratiche per 100 grammi: zuccheri sotto 5 grammi è poco, sopra 22 è molto; sale sotto 0,3 grammi è poco, sopra 1,5 è molto; grassi saturi sotto 1,5 è poco, sopra 5 è molto."),
       ("Passo 4 — Cosa contare davvero",
        "Non serve leggere tutto. Per la maggior parte delle persone contano quattro cose: zuccheri, sale, grassi saturi e fibre (più di 6 grammi per 100 è buono). Le calorie da sole dicono poco: 100 calorie di mandorle e di caramelle non hanno lo stesso effetto. E i prodotti senza etichetta, frutta, verdura, legumi, uova, sono quasi sempre la scelta più semplice."),
      ]),
    L("corpo-umano", "v5-lez-postura",
      "Mal di schiena da scrivania: 4 mosse che funzionano davvero", ["schiena", "scrivania"],
      "Otto ore seduti e la schiena protesta. La soluzione non è la sedia da 800 euro né la 'postura perfetta': è qualcosa di molto più semplice, e gratuito.",
      "Capire perché stare seduti a lungo fa male e applicare quattro accorgimenti concreti per ridurre il dolore lombare e cervicale.",
      "Il problema non è la postura sbagliata ma la postura fissa: i dischi e i muscoli hanno bisogno di variare. Alzati ogni 30-45 minuti, porta lo schermo all'altezza degli occhi, appoggia gli avambracci, rinforza il tronco con due esercizi.",
      [
       ("Passo 1 — Il nemico è l'immobilità",
        "I dischi tra le vertebre non hanno vasi sanguigni: si nutrono con il movimento, che li comprime e rilascia come spugne. Fermi per ore, si disidratano e i muscoli che sostengono la colonna si affaticano e si irrigidiscono. La ricerca mostra che la 'postura perfetta' mantenuta per ore fa male quanto quella scomposta. La postura migliore è la prossima."),
       ("Passo 2 — Alzati ogni 30-45 minuti",
        "Basta un minuto: in piedi, due passi, allungare le braccia sopra la testa, inarcare la schiena indietro. Bere acqua ti costringe ad alzarti per riempire il bicchiere e per il bagno: usalo come promemoria naturale. Le riunioni telefoniche si possono fare camminando."),
       ("Passo 3 — Sistema lo schermo",
        "La testa pesa 5 chili; inclinata in avanti di 45 gradi per guardare un portatile carica il collo con 20 chili. Alza lo schermo con una pila di libri finché il bordo superiore è all'altezza degli occhi, e usa una tastiera esterna. Gli avambracci appoggiati sul tavolo o sui braccioli scaricano le spalle. Il telefono, tienilo alto, non abbassare la testa."),
       ("Passo 4 — Due esercizi, tre volte a settimana",
        "Il plank, anche sulle ginocchia, 20-40 secondi per tre volte: rinforza i muscoli profondi che tengono la colonna. Il ponte: supino, ginocchia piegate, sollevare il bacino e tenere 5 secondi, dieci ripetizioni: rinforza glutei e lombari. Una schiena forte tollera la sedia; una sedia costosa non sostituisce una schiena forte. Se il dolore scende lungo la gamba o dura più di sei settimane, medico."),
      ]),

    # ------------------------------ CULTURA ------------------------------
    L("cultura", "v5-lez-cognomi",
      "Da dove viene il tuo cognome: le 4 origini dei cognomi italiani", ["cognome"],
      "Rossi, Esposito, Ferrari, Romano. Ogni cognome italiano è una piccola storia: un mestiere, un luogo, un padre, un soprannome. Ecco come decifrare il tuo.",
      "Riconoscere le quattro categorie di origine dei cognomi italiani e ricostruire il probabile significato del proprio.",
      "I cognomi si fissano tra il XIII e il XVI secolo. Derivano da: nome del padre (De Luca, Di Giovanni), mestiere (Ferrari, Sartori), luogo di provenienza (Romano, Lombardi, Della Valle) o soprannome fisico e caratteriale (Rossi, Basso, Allegri). I trovatelli ebbero cognomi speciali.",
      [
       ("Passo 1 — Perché sono nati",
        "Nel Medioevo bastava un nome: Giovanni. Con la crescita delle città, in ogni quartiere c'erano dieci Giovanni e servì distinguerli: Giovanni figlio di Pietro, Giovanni il fabbro, Giovanni da Lucca, Giovanni il rosso. Il Concilio di Trento nel 1563 obbligò le parrocchie a registrare i battesimi con nome e cognome, fissandoli per sempre."),
       ("Passo 2 — Padri e mestieri",
        "I patronimici derivano dal nome del padre: Di Giovanni, De Luca, Martini, Paoli, Giannini. In Sicilia e Calabria prevalgono con 'Di' e 'De'; in Toscana con la desinenza in -i, un plurale che indicava la famiglia. I mestieri: Ferrari e Ferraro (fabbro, il più diffuso), Sartori, Molinari, Pastore, Barbieri, Fornai, Vaccaro, Notaro. Il tuo antenato faceva quel lavoro nel Trecento."),
       ("Passo 3 — Luoghi e soprannomi",
        "I cognomi geografici indicano da dove veniva una famiglia immigrata: Romano, Lombardi, Napolitano, Greco, Tedesco, Pugliese, ma anche Montagna, Della Valle, Fontana, Dal Bosco. I soprannomi sono la categoria più colorita: Rossi (capelli rossi, il cognome più diffuso in Italia), Bianchi, Basso, Grasso, Mancini (mancino), Allegri, Selvaggi, Bevilacqua, Quattrocchi (portava gli occhiali)."),
       ("Passo 4 — I figli di nessuno e come indagare",
        "I bambini abbandonati ricevevano cognomi speciali: Esposito (esposto alla ruota), Proietti (gettato), Innocenti, Diotallevi, Trovato, Casadei, Degli Esposti. A Napoli Esposito è il cognome più diffuso. Per indagare il tuo: cerca la distribuzione geografica sui siti dedicati, spesso concentrata in pochi comuni, poi i registri parrocchiali del luogo. Nel giro di un pomeriggio puoi risalire di due o tre secoli."),
      ]),
    L("cultura", "v5-lez-gesti-italiani",
      "I gesti italiani: 4 gesti, cosa significano e da dove vengono", ["gesti"],
      "Gli stranieri li imitano, gli italiani non li notano. La mano a borsa, il mento sfiorato, le mani giunte che oscillano. Ognuno ha una grammatica precisa e una storia lunga.",
      "Conoscere significato, uso e origine di quattro gesti italiani comuni e capire perché l'Italia ne ha così tanti.",
      "L'Italia ha un vocabolario di oltre 250 gesti codificati, eredità delle città affollate e delle piazze in cui si parlava a distanza. La mano a borsa chiede 'cosa vuoi?', il mento sfiorato dice 'non me ne importa', le mani giunte oscillanti supplicano, l'indice sulla guancia significa 'buono'.",
      [
       ("Passo 1 — La mano a borsa",
        "Dita unite verso l'alto, polso che oscilla: 'Ma che vuoi?', 'Che stai dicendo?'. È il gesto italiano per eccellenza, tanto da essere diventato un'emoji nel 2020. Già rappresentato su vasi greci del IV secolo a.C. trovati in Italia meridionale, dove indicava una domanda. Il ritmo conta: lento è una domanda vera, veloce è esasperazione."),
       ("Passo 2 — Il mento e le mani giunte",
        "Le dita che sfiorano il mento dall'interno verso l'esterno: 'Non me ne importa niente'. All'estero viene spesso frainteso come insulto; in Italia è indifferenza teatrale. Le mani giunte che oscillano davanti al petto: 'Ti prego', 'Ma per favore', anche ironico. Deriva dalla preghiera e conserva la supplica, ma spesso quella di chi chiede di smetterla."),
       ("Passo 3 — Guancia, gola e occhio",
        "L'indice che ruota sulla guancia: 'Buono!', usato soprattutto con i bambini, forse dall'idea del cibo che si sente in bocca. La mano di taglio sotto la gola: 'Sono pieno', 'Ne ho fin qui', ma anche minaccia. L'indice che tira giù la palpebra: 'Occhio, stai attento' o 'Non ci credo, sono sveglio'."),
       ("Passo 4 — Perché proprio l'Italia",
        "Un'ipotesi: nelle città-stato affollate, piene di stranieri e dialetti diversi, i gesti erano una lingua franca visibile da un balcone all'altro. Un'altra: sotto dominazioni straniere i gesti permettevano di parlare senza farsi capire. Nel 1832 il canonico Andrea de Jorio catalogò i gesti napoletani in un libro ancora oggi consultato: molti sono identici a quelli dipinti sui vasi antichi."),
      ]),
    L("cultura", "v5-lez-miti-diluvio",
      "Perché tutte le culture raccontano un diluvio: come leggere un mito", ["mito", "diluvio"],
      "Noè, Gilgamesh, Manu in India, i miti degli aborigeni australiani. Popoli che non si sono mai incontrati raccontano la stessa storia di un'inondazione che cancella il mondo. Un caso?",
      "Capire come e perché i miti nascono, viaggiano e si somigliano, e imparare a leggerli come documenti storici e psicologici.",
      "I miti si somigliano per tre ragioni: eventi reali comuni (le inondazioni post-glaciali), diffusione tra popoli vicini (Gilgamesh precede Noè di mille anni) e strutture universali della mente umana che rendono alcune storie memorabili. Un mito va letto chiedendosi cosa spiegava e a chi.",
      [
       ("Passo 1 — Il diluvio prima di Noè",
        "L'Epopea di Gilgamesh, scritta in Mesopotamia intorno al 2100 a.C., racconta di Utnapishtim avvertito da un dio di costruire una barca, caricarvi animali e famiglia, e sopravvivere a un diluvio; libera poi tre uccelli per cercare terra. Il racconto biblico di Noè, scritto secoli dopo nella stessa regione, riprende la struttura passo per passo. I miti viaggiano con i mercanti e gli imperi."),
       ("Passo 2 — Un ricordo di eventi reali",
        "Alla fine dell'ultima glaciazione, tra 15.000 e 7.000 anni fa, il livello del mare salì di 120 metri e sommerse pianure abitate: il Mar Nero, il Golfo Persico, il ponte tra Australia e Nuova Guinea. Gli aborigeni australiani conservano racconti che descrivono coste oggi sott'acqua con dettagli verificati dai geologi. Alcuni miti sono memoria orale di 10.000 anni."),
       ("Passo 3 — Le strutture della mente",
        "Le storie che sopravvivono sono quelle facili da ricordare e da raccontare: una catastrofe, un eletto avvertito in anticipo, un rifugio, un nuovo inizio. Questa struttura funziona in ogni cultura perché parla di paure e speranze universali. Non serve un contatto: menti simili producono storie simili, come le lingue inventano parole simili per 'mamma'."),
       ("Passo 4 — Come leggere un mito",
        "Chiediti quattro cose: cosa spiega (l'origine del mondo, un rito, un paesaggio), a chi serviva (legittimare un re, insegnare una regola), quali dettagli concreti contiene (un luogo, una pianta, un evento) e come cambia tra versioni. Un mito non è una notizia falsa: è un contenitore in cui una comunità ha messo ciò che riteneva importante ricordare."),
      ]),
    L("cultura", "v5-lez-opera-lirica",
      "Andare all'opera per la prima volta senza sentirsi fuori posto", ["opera"],
      "Tre ore di canto in italiano antico, trame che sembrano assurde, un pubblico che sa quando applaudire. Con quattro cose da sapere, l'opera diventa quello che è sempre stata: uno spettacolo popolare.",
      "Capire come funziona un'opera lirica, cosa aspettarsi in teatro e come scegliere il primo titolo.",
      "L'opera è teatro cantato, nato in Italia intorno al 1600. La trama è semplice e va letta prima; la musica esprime le emozioni che le parole solo accennano. Si applaude dopo le arie famose e alla fine degli atti. Per iniziare: Tosca, La Traviata, Carmen, Il barbiere di Siviglia.",
      [
       ("Passo 1 — Cos'è e come è fatta",
        "Un'opera è una storia recitata cantando, con un'orchestra. È divisa in atti, e all'interno in recitativi, dove i personaggi dialogano e la trama avanza, e arie, dove uno si ferma e canta ciò che sente. Il duetto, il terzetto, il coro moltiplicano le voci. L'orchestra commenta: quando il tema d'amore torna in minore, sai che finirà male prima dei personaggi."),
       ("Passo 2 — Leggi la trama prima",
        "Le trame d'opera sono spesso melodrammatiche e i testi difficili da capire cantati. Leggi il riassunto sul programma o online, dieci minuti bastano. Molti teatri proiettano i sottotitoli sopra il palco o su schermi nel sedile. Liberato dal seguire la storia, puoi ascoltare cosa fa la musica: è lì che succede tutto."),
       ("Passo 3 — Le regole non scritte",
        "Vestiti come per un teatro, non serve lo smoking tranne alla prima. Arriva in anticipo: chi è in ritardo entra all'intervallo. Si applaude alla fine di un'aria famosa, dopo che l'orchestra ha concluso, e alla fine di ogni atto; 'Bravo', 'Brava', 'Bravi' secondo chi canta. I fischi in Italia esistono ancora e sono un giudizio, non maleducazione. Telefono spento, non silenzioso: la luce si vede."),
       ("Passo 4 — Da dove cominciare",
        "Scegli un'opera breve e melodica. Tosca di Puccini: due ore, thriller, tre arie celebri. La Traviata di Verdi: storia d'amore, valzer, il brindisi che conosci già. Carmen di Bizet: in francese, ritmo travolgente. Il barbiere di Siviglia di Rossini: comica, veloce. Prima di andare, ascolta l'opera una volta su una piattaforma di streaming: in teatro riconoscerai i momenti chiave e sarà tutta un'altra esperienza."),
      ]),
    L("cultura", "v5-lez-struttura-fiaba",
      "Come è fatta una fiaba: i 4 elementi che si ripetono in tutto il mondo", ["fiaba"],
      "Cenerentola esiste in Cina dal IX secolo, in Egitto, tra i nativi americani. Cappuccetto Rosso ha duemila anni. Le fiabe seguono uno schema così stabile che si può quasi scrivere una formula.",
      "Riconoscere la struttura universale delle fiabe e capire perché è sopravvissuta per millenni.",
      "Le fiabe hanno una mancanza iniziale, una partenza, prove con aiutanti e antagonisti, un ritorno trasformato. Vladimir Propp individuò 31 funzioni fisse nel 1928. Le fiabe servivano a trasmettere regole, paure e speranze in una forma che la memoria trattiene.",
      [
       ("Passo 1 — La mancanza e la partenza",
        "Ogni fiaba comincia con un equilibrio rotto: un divieto infranto, una carestia, una madre morta, un re senza eredi. L'eroe, spesso il più piccolo o il meno considerato, lascia casa. Il bosco, il mare, il castello lontano sono il mondo adulto. Propp lo chiamava 'allontanamento', ed è il primo dei suoi passaggi."),
       ("Passo 2 — Le prove e gli aiutanti",
        "L'eroe incontra un donatore che lo mette alla prova: una vecchia che chiede cibo, un animale da salvare. Se supera la prova ottiene un oggetto magico o un alleato. Poi affronta l'antagonista: orco, lupo, matrigna, drago. Le prove sono spesso tre, il numero che la memoria orale regge meglio."),
       ("Passo 3 — Il ritorno trasformato",
        "L'eroe vince, spesso con astuzia più che con forza, e torna. Ma non è più lo stesso: ha una sposa, un regno, un nome. Chi ha ingannato viene smascherato, chi ha aiutato ricompensato. Il lieto fine non è ingenuità: dice a chi ascolta che le prove hanno un senso e che i piccoli possono farcela."),
       ("Passo 4 — Perché sono uguali ovunque",
        "Nel 2016 due antropologi hanno applicato ai racconti popolari i metodi con cui i biologi ricostruiscono l'albero delle specie: alcune fiabe, come Il fabbro e il diavolo, risalgono a oltre 6.000 anni fa, prima della scrittura. Le fiabe sono la tecnologia più antica per trasmettere regole: non fidarti degli sconosciuti, mantieni le promesse, la gentilezza viene ripagata. La struttura fissa è il formato che ha permesso al messaggio di attraversare i millenni."),
      ]),
]
