"""PAUSE — traduzioni EN per le storie di ECONOMIA (v5.2)."""
from story_builder import en_entry as E

EN = {
    "eco-why-money-value": E(
        "Why does money have value if it's just paper?",
        ["money", "value"],
        "A banknote is a printed piece of paper. Yet it buys you bread, a trip, a home. Where does that value really come from?",
        "Money has value because we all trust together that it does: shared trust, not gold, is what holds up modern currencies.",
        [
            ("Before money there was barter",
             "For millennia humans traded goods directly: a sack of grain for a sheep, a jar of oil for a tool. The problem is the 'double coincidence of wants': I must find someone who wants exactly what I have and has exactly what I want. In complex societies this becomes impossible. A universal intermediary that everyone accepted was needed."),
            ("The birth of an intermediary",
             "Shells, salt, cattle, precious metals: many things have served as money in history. Metal coins won out because they were durable, divisible and hard to counterfeit. Gold and silver had 'intrinsic' value, but also a limit: they were heavy and scarce. Paper was born as a promise: a note worth the gold deposited in a bank."),
            ("Money today is pure trust",
             "Since 1971 the main currencies are no longer tied to gold: they are 'fiat', meaning they have value because the State decrees it and everyone accepts them. A 50-euro note isn't backed by precious metal in a vault. It's worth something because you know your baker will take it, and he knows his supplier will too. It's a self-reinforcing chain of trust."),
            ("Why trust can collapse",
             "When trust breaks, money quickly loses value. It happened in Germany in 1923 and in Zimbabwe in the 2000s: prices doubled within hours and it took wheelbarrows of banknotes to buy bread. This is hyperinflation. It proves the value of money isn't in the paper, but in the stability of the institutions backing it."),
            ("Digital money",
             "Today most money doesn't even exist physically: it's figures on banks' servers. When you get your salary, no one moves banknotes: only numbers in a database change. Cryptocurrencies pushed the idea further, trying to create trust without a State, through mathematics and computer networks. But the principle is the same: it's worth what we believe together."),
            ("The takeaway",
             "Money is one of the most powerful social inventions ever: a collective agreement that lets us cooperate among strangers. Understanding it changes how you see it: it's not magical nor an end in itself, but a tool of trust. And like all trust, it must be safeguarded, because it's more fragile than it seems."),
        ]),
    "eco-compound-interest": E(
        "Compound interest: the eighth wonder?",
        ["compound", "interest"],
        "Einstein reportedly called it the most powerful force in the universe. Small sums that, over time, become mountains of money.",
        "Compound interest grows savings exponentially: interest generates more interest, and time matters more than the starting amount.",
        [
            ("Simple vs compound interest",
             "With simple interest you earn a percentage each year only on the initial capital. With compound interest, instead, the interest is added to the capital and the following year it in turn generates interest. It's the difference between linear growth and growth that accelerates on itself. At first the difference is tiny, but over the years it becomes enormous."),
            ("The power of time",
             "Imagine 1,000 euros at 7% a year. After 10 years it becomes about 2,000, after 20 years about 4,000, after 30 years nearly 8,000. You added nothing: it's time doing the work. This is why starting to save at 25 instead of 40 can be worth more than double, for the same amounts paid in."),
            ("The rule of 72",
             "There's a mental trick to know how long it takes to double capital: divide 72 by the interest rate. At 6% it takes about 12 years (72÷6), at 9% about 8 years. It's a surprisingly accurate approximation that lets you sense the power of a return without a calculator."),
            ("It works in reverse too",
             "Compound interest is a friend when you invest, but a fierce enemy when you have debts. Credit cards and consumer loans apply the same mechanism: unpaid debt generates interest that adds to the debt, which generates more interest. That's how small unpaid sums can swell until they become unmanageable."),
            ("Why it's hard to perceive",
             "Our brain thinks linearly: we struggle to imagine curves that explode upward. That's why compound interest feels disappointing in the early years and then, suddenly, incredible. Those who quit early miss precisely the steepest part of the curve, the one that comes only with patience."),
            ("The takeaway",
             "You don't need to be rich to use it: you need time and consistency. Even small amounts paid in regularly, left to grow for decades, can turn into a large sum. The real secret isn't finding the perfect return, but starting early and not interrupting the process."),
        ]),
    "eco-inflation": E(
        "What is inflation and why do prices rise?",
        ["inflation", "prices"],
        "With 10 euros your grandparents could buy far more than today. It's not nostalgia: it's inflation, and it changes the very value of money over time.",
        "Inflation is the general rise in prices over time: it reduces money's purchasing power, often due to imbalances between demand, supply and the amount of money.",
        [
            ("What it really means",
             "Inflation measures how much, on average, the prices of goods and services rise in a year. If inflation is 3%, what costs 100 euros today will cost about 103 next year. It doesn't concern a single product, but the overall basket of a typical family's spending. Low, stable inflation is considered normal and even healthy."),
            ("Why prices rise",
             "The main causes are two. First: demand grows more than supply, so sellers can raise prices. Second: production costs rise (energy, raw materials, wages) and companies pass them on to the final price. There's a third factor: if there's too much money in circulation compared to available goods, each euro is worth less."),
            ("The enemy of idle savings",
             "Inflation silently erodes money left still. If you keep 1,000 euros under the mattress and inflation is 4%, after a year those 1,000 euros buy like 960. They haven't vanished, but they're worth less. That's why keeping everything liquid, without putting it to work, is a hidden but real loss."),
            ("Who wins and who loses",
             "Inflation penalizes those with liquid savings and those with fixed incomes that don't adjust. It favors instead those with fixed-rate debts: they repay the same nominal sum, but worth less in real terms. That's why heavily indebted governments sometimes don't fear a bit of inflation: it lightens the real weight of their debt."),
            ("The role of central banks",
             "Central banks, like the ECB, are tasked with keeping inflation near a target (usually 2%). Their main tool is interest rates: raising them makes money more expensive, curbs spending and cools prices. Lowering them stimulates the economy. It's a delicate balance between growth and stability."),
            ("The takeaway",
             "Inflation isn't inherently bad: the problem is when it's too high or unpredictable. Understanding it helps you make better choices, from asking for salary adjustments to not leaving all savings idle. Money isn't static: its value changes, and inflation is the measure of that change."),
        ]),
    "eco-supply-demand": E(
        "Supply and demand: the invisible law of prices",
        ["demand", "supply"],
        "Why does water cost almost nothing and a diamond a fortune, even though you can't live without water? The answer is an invisible balance.",
        "Price comes from the meeting of how much a good is wanted (demand) and how available it is (supply): scarcity, not usefulness, often decides value.",
        [
            ("The water and diamond paradox",
             "Water is essential to life, diamonds are not. Yet diamonds cost infinitely more. This paradox puzzled economists for centuries. The solution lies in scarcity: water is abundant, so the last liter is worth little; diamonds are rare, so each stone is precious. What counts is not total usefulness, but that of the last available unit."),
            ("The demand curve",
             "In general, the more a good costs, the fewer people buy it; the cheaper it is, the more people want it. It's the law of demand. But it doesn't apply equally to everything: for bread or essential medicines demand changes little with price, because you can't do without them. For an ice cream or a holiday, instead, a small increase can drive away many customers."),
            ("The supply curve",
             "From the sellers' side the opposite holds: the higher the price, the more it pays to produce and sell. If the price of coffee rises, more farmers grow it. If it collapses, many stop. Supply reacts to prices, but often slowly: planting a coffee tree and waiting for it to yield takes years."),
            ("The equilibrium point",
             "The market price forms where demand and supply meet: the quantity buyers want at that price matches the one sellers offer. If the price is too high, goods remain unsold and it falls; if it's too low, goods run out and it rises. It's a continuous adjustment, like a scale seeking balance."),
            ("When the balance breaks",
             "Sudden events shift the curves. A frost destroys crops: supply collapses and prices soar. A trend makes demand for a product explode: prices rise until production catches up. Speculation and monopolies can further distort this game, keeping prices artificially high or low."),
            ("The takeaway",
             "Behind every price tag there's a silent negotiation among millions of individual choices. No one decides from above how much bread should cost: it emerges from the meeting of those who sell and those who buy. Understanding supply and demand means reading the economic world as a huge system of signals."),
        ]),
    "eco-why-taxes": E(
        "Why do we pay taxes (and where do they go)?",
        ["taxes", "State"],
        "Every year part of what we earn goes to the State. A burden, sure. But without taxes, much of the world we take for granted would disappear.",
        "Taxes fund collective goods and services the market alone wouldn't provide: roads, healthcare, schools, justice and security for all.",
        [
            ("What taxes are",
             "Taxes are mandatory contributions that citizens and companies pay to the State. They're not payment for a specific service, but collective funding. In return, the State provides goods and services that concern everyone. It's a social pact as old as the first civilizations: already in Mesopotamia tributes on harvests and cattle were recorded."),
            ("Public goods",
             "Some things can't be sold individually: street lighting, national defense, justice. No company would provide them because it couldn't charge those who benefit. These are 'public goods', and taxes exist above all to fund them. Without a common contribution, we'd all be left without, even those willing to pay."),
            ("Where the money goes",
             "In European countries most revenue goes to healthcare, education, pensions and social assistance. The rest funds infrastructure, security, justice and the running of the State. A share, often large, goes to paying interest on public debt accumulated over the years. Every state budget is a snapshot of a society's priorities."),
            ("Progressivity: those who have more, pay more",
             "In many systems income taxes are progressive: the rate rises with income. The idea is that those who earn more can contribute proportionally more, reducing inequality. It's a debated principle: some consider it fair, others fear it discourages work and investment if pushed too high."),
            ("The problem of evasion",
             "When someone doesn't pay what they owe, the burden falls on others or services worsen. Tax evasion erodes trust in the system: if we sense that many don't pay, we're less willing to do so ourselves. That's why States invest heavily in controls and transparency, and increasingly in digital tools to track payments."),
            ("The takeaway",
             "Taxes aren't just a levy: they're the price of living together. The real question isn't 'taxes yes or no', but how much and how to collect and spend them. Behind the annoyance of the tax return there is, ultimately, the machine that keeps everyone's roads, hospitals and schools running."),
        ]),
    "eco-stock-market": E(
        "What is the stock market and why do shares rise and fall?",
        ["stock", "shares"],
        "Flashing numbers, wild charts, fortunes made and destroyed in a day. But what really happens when you buy a share?",
        "Buying a share means owning a tiny slice of a company: its price rises and falls based on how much the market believes in its future.",
        [
            ("A share is a piece of a company",
             "When you buy a share, you become a co-owner of a company, however tiny your part. If the company does well and grows, your slice is worth more; if it does badly, it's worth less. Companies sell shares to raise money to expand, without having to borrow it. In exchange, they give up part of their ownership and future profits."),
            ("Why the stock market exists",
             "The stock market is a place where these company slices are bought and sold. It serves two purposes: it lets firms raise capital and lets investors resell their shares whenever they want. Without such a market, whoever buys a stake would be stuck: liquidity, meaning being able to sell easily, is the real engine of the stock market."),
            ("What moves prices",
             "A share's price reflects expectations about the company's future. Good news, rising profits, new products: the price tends to go up. Bad news or fears: it goes down. Often the expectation matters more than the actual figure: if a company earns a lot but less than expected, the stock can even crash. The market bets on tomorrow, not today."),
            ("The role of emotions",
             "Markets aren't perfectly rational machines: they're made of people, with fear and greed. In moments of euphoria prices rise beyond reason (bubbles); in moments of panic they crash beyond justification. Great historic crashes, from 1929 to 2008, were amplified precisely by collective emotional reactions."),
            ("Risk and time horizon",
             "In the short term the stock market is unpredictable and can lose a lot quickly. In the long term, historically, the stock markets of developed countries have returned more than almost any other investment. The golden rule is not to invest money you need soon and to diversify, meaning not betting everything on a single company."),
            ("The takeaway",
             "The stock market isn't a casino nor a get-rich-quick machine: it's a way to share in the growth of companies over time. Those who treat it as a quick bet often lose; those who use it with patience and discipline are usually rewarded by the years."),
        ]),
    "eco-gdp": E(
        "GDP: the number that measures a country's wealth",
        ["GDP", "wealth"],
        "We hear that GDP grows or falls, and it seems to decide a nation's health. But what does it really measure, and what does it forget?",
        "GDP is the value of all goods and services produced in a country in a year: useful to measure economic activity, but blind to well-being and inequality.",
        [
            ("What GDP means",
             "GDP stands for Gross Domestic Product: it's the total value of all final goods and services produced within a country's borders in a year. If a baker sells bread for 100,000 euros and a workshop repairs cars for 200,000, both contribute to GDP. It's the most-used thermometer for measuring how much an economy is 'moving'."),
            ("Why everyone watches it",
             "A growing GDP usually means more production, more jobs and more income. A GDP falling for two quarters in a row is called a recession, and it often brings unemployment and cuts. That's why governments, businesses and markets follow GDP data with almost obsessive attention: it guides decisions affecting millions of people."),
            ("How it can grow",
             "GDP grows if production increases: more people working, more efficient machines, new technologies, or more consumption and investment. Growth is neither infinite nor automatic: it depends on innovation, education, infrastructure and stability. Countries that invest in knowledge and research tend to grow more solidly in the long run."),
            ("What GDP doesn't see",
             "GDP measures quantity, not quality of life. It doesn't record unpaid housework, volunteering or free time. It even counts as positive what stems from disasters: rebuilding after a flood raises GDP. And it says nothing about how wealth is distributed: a country can grow while inequality increases."),
            ("The alternatives",
             "Precisely for these limits, complementary indicators were born, like the Human Development Index, which also considers health and education, or measures of well-being and happiness. Some countries began using them alongside GDP. The idea isn't to throw away GDP, but to pair it with figures that better describe people's real lives."),
            ("The takeaway",
             "GDP is a useful but partial compass: it tells how much a country produces, not how well it's doing. Confusing it with a nation's happiness is a common mistake. A society's true wealth is also measured in health, time, environment and justice: things no single number can fully capture."),
        ]),
    "eco-brands-value": E(
        "Why can a logo be worth billions?",
        ["brand", "value"],
        "Two identical shirts, but one has a small symbol stitched on the chest and costs triple. The value of a brand is one of the magics of economics.",
        "A strong brand is valuable because it creates trust, recognizability and belonging: people pay more for what the logo promises, not just for the product.",
        [
            ("A brand is a promise",
             "A brand isn't just a logo: it's the set of expectations we associate with a name. When you see a familiar symbol, your brain instantly recalls memories, perceived quality, status. This mental shortcut has enormous economic value: it reduces the uncertainty of a purchase. You buy with more confidence something you 'know', even if you've never tried it."),
            ("Why we pay more",
             "Neuromarketing studies show that the same product is liked more if associated with a beloved brand. It's not naivety: the brand also sells identity and belonging. Wearing or using a certain brand tells others (and ourselves) who we think we are. That premium is, in part, the cost of a social message."),
            ("How it's built",
             "A strong brand is built with years of consistency: maintained quality, recognizable communication, repeated positive experiences. Trust is slow to earn and quick to lose. A single scandal can wipe out decades of reputation. That's why companies invest huge sums not only in advertising, but in caring for every customer contact."),
            ("The value in the books",
             "The most famous brands are worth, on their own, hundreds of billions: often more than the company's factories and machinery. This 'intangible' value is estimated and put on the balance sheet. When one company buys another, much of the price can concern the brand itself, meaning customers' trust, not the physical assets."),
            ("The risk of being too strong",
             "A hugely powerful brand also brings fragility. It becomes a target: counterfeits, criticism, boycotts. And it risks 'aging' if it doesn't renew itself: many historic brands vanished for failing to change with the public. A brand's value is never acquired forever: it must be defended and reinvented constantly."),
            ("The takeaway",
             "Behind a logo worth billions there's no magic, but psychology and accumulated trust. Recognizing this makes you a more aware consumer: you understand when you're paying for the product and when for the promise. Sometimes that promise is really worth the price; other times, it's just a symbol stitched on the chest."),
        ]),
    "eco-scarcity-choices": E(
        "Why we can't have it all: the science of choices",
        ["scarcity", "choices"],
        "Time, money, energy: everything is limited. Economics, even before money, is about how we choose when we can't have it all.",
        "Scarcity forces us to choose, and every choice has a hidden cost: what you give up. It's the concept of opportunity cost, the heart of economic thinking.",
        [
            ("Scarcity is everywhere",
             "Economics stems from a simple fact: desires are infinite, resources aren't. There isn't enough time, money or raw materials to satisfy everything we'd want. This holds for a person as for an entire country. Scarcity isn't a temporary problem to solve: it's the basic condition every economic choice must reckon with."),
            ("Every choice is a sacrifice",
             "Choosing to do one thing means giving up another. If you spend the evening studying, you give up seeing friends; if you buy a new smartphone, that money won't go to a trip. Economists call 'opportunity cost' the value of the best alternative you give up. It's an invisible but real cost, often more important than the price paid."),
            ("Thinking at the margin",
             "Decisions are rarely 'all or nothing': usually they're about a bit more or a bit less. Is it worth studying one more hour? Producing a thousand more units? Economic thinking compares the extra benefit with the extra cost of each small unit. This 'thinking at the margin' is one of the most powerful tools for deciding well."),
            ("Incentives matter",
             "People respond to incentives: they change behavior if costs and benefits change. A rise in the price of petrol pushes people to use the car less; a discount makes them buy more. Many problems are solved not with bans, but by changing incentives. And many policies fail because they ignore how people will actually react."),
            ("Sunk costs",
             "A classic mistake is being swayed by money or time already spent and unrecoverable: 'sunk costs'. Finishing a boring film because you paid for the ticket, or continuing a failing project because you've already invested so much. Economic logic says look ahead: what's lost is lost, only what's worth doing from now on counts."),
            ("The takeaway",
             "Economics, ultimately, is the science of choices in a limited world. Thinking in terms of opportunity cost, margin and incentives isn't just for economists: it helps you decide better in everyday life. You can't have it all, but you can choose more consciously what to say yes to."),
        ]),
    "eco-why-things-cost": E(
        "Why does the same product cost different prices?",
        ["price", "strategy"],
        "A flight that changes price every hour, a coffee that costs double at the airport. Prices aren't fixed: they're strategies studied in the finest detail.",
        "Companies vary prices based on demand, place, moment and the customer's willingness to pay: it's the science of pricing, not chance.",
        [
            ("The price doesn't just reflect cost",
             "You'd think a price is the production cost plus a margin. In reality, many companies start from the opposite question: how much is the customer willing to pay? Cost is the minimum floor, but the final price depends much more on perceived value and the context in which the purchase happens."),
            ("Dynamic pricing",
             "Flights, hotels and tickets change price constantly thanks to algorithms that read demand in real time. If many are searching for that flight, the price rises; if seats remain empty close to departure, it can drop. It's the same principle as taxis costing more in the rain: high price when demand is high."),
            ("Segmenting customers",
             "Companies know that different people would pay different amounts. So they create versions of the same product to charge each the most they're willing to spend: economy and business class, the basic subscription and the premium one. Discounts for students and seniors serve precisely to reach those who otherwise wouldn't buy."),
            ("The power of context",
             "The same coffee costs little at a suburban bar and a lot in a luxury hotel. The coffee doesn't change: the context and what you're willing to pay in that moment do. At an airport or stadium prices rise because you have no convenient alternatives. Scarcity of choice is a precious ingredient for those who set prices."),
            ("Psychological tricks",
             "9.99 instead of 10 seems much less, even if it's a one-cent difference: our brain reads the first digit. An expensive option placed nearby makes the others seem cheap. 'Limited-time' offers push us to decide quickly. These tricks exploit mental shortcuts we all use without noticing."),
            ("The takeaway",
             "The price you see is almost always a strategic choice, not an objective truth. Knowing this makes you a smarter buyer: you compare, wait for the right moment, don't get fooled by the 9.99. Behind every price tag there's someone who studied at length how to make you say yes."),
        ]),
}
