"""PAUSE — 5° step generato per ogni mini lezione (IT + EN).
Prodotto da generate_lesson_step5.py (gpt-5.4). Consumato da seed_lessons_a.py,
che lo appende come capitolo 5 di ogni lezione, così le mini lezioni hanno la
stessa gerarchia delle curiosità: 5 capitoli + la voce "Da ricordare"."""

STEP5 = {
    "lez-metodo-scientifico": {
        "it": ("Passo 5 — Provalo nella vita vera", "Questo metodo non serve solo in laboratorio o con le piante. Puoi usarlo quando ti chiedi perché dormi male, perché arrivi sempre tardi o perché la bolletta è salita. Prendi una sola domanda, scrivi una possibile causa e scegli un test semplice. Per esempio: \"Dormo male perché guardo il telefono a letto\". Per una settimana eviti lo schermo negli ultimi 30 minuti e tieni uguali il resto degli orari. Poi annoti com'è andata. Non stai cercando una risposta perfetta al primo colpo: stai allenando un'abitudine mentale utile, quella di sostituire impressioni vaghe con prove abbastanza buone per decidere meglio."),
        "en": ("Step 5 — Try it in real life", "This method is not just for labs or houseplants. You can use it when you wonder why you sleep badly, why you are always late, or why your energy bill jumped. Pick one question, write down one possible cause, and choose a simple test. For example: \"I sleep badly because I scroll on my phone in bed.\" For one week, skip screens for the last 30 minutes before sleep and keep the rest of your routine the same. Then note what happened. You are not hunting for a perfect answer on the first try. You are building a useful habit of mind: replacing vague impressions with evidence good enough to help you make better decisions."),
    },
    "lez-energia-conservazione": {
        "it": ("Passo 5 — Leggilo in bolletta", "Un buon test finale è guardare una bolletta elettrica. I consumi non sono scritti in joule ma in kilowattora: 1 kWh corrisponde a 3,6 milioni di joule. Se un phon da 1.500 watt resta acceso per un’ora, usa 1,5 kWh. Quell’energia non scompare: diventa soprattutto calore nell’aria, più un po’ di suono e movimento della ventola. Anche un caricabatterie o una lampadina stanno facendo la stessa cosa: trasformano energia elettrica in altre forme, con una parte inevitabilmente dispersa come calore. Pensare ai consumi così ti aiuta a capire perché “risparmiare energia” significa in realtà usare meno trasformazioni inutili."),
        "en": ("Step 5 — Read it on a bill", "A good final test is to look at an electricity bill. Energy use is not listed in joules but in kilowatt-hours: 1 kWh equals 3.6 million joules. If a 1,500-watt hair dryer runs for one hour, it uses 1.5 kWh. That energy does not vanish: it becomes mostly heat in the air, plus a little sound and motion from the fan. A phone charger or a light bulb is doing the same basic thing: turning electrical energy into other forms, with some of it inevitably spread out as heat. Thinking this way helps you see why “saving energy” really means avoiding unnecessary conversions."),
    },
    "lez-orientarsi-stelle": {
        "it": ("Passo 5 — Verifica prima di fidarti", "Prima di usare le stelle per scegliere una direzione, fai una rapida verifica con l’orizzonte. Alberi, montagne e palazzi possono farti credere che la Polare o il punto sotto la Croce del Sud siano più bassi o più alti di quanto siano davvero. Cerca quindi un tratto di orizzonte il più possibile libero e controlla che il cielo sia abbastanza limpido da distinguere bene le stelle di riferimento. Se hai un dubbio, ripeti il tracciamento una seconda volta dopo qualche minuto: le stelle si spostano lentamente, ma la geometria tra Grande Carro, Polare e polo resta uguale. Questa piccola conferma riduce molto gli errori di orientamento."),
        "en": ("Step 5 — Check before you trust it", "Before you use the stars to choose a direction, do a quick reality check against the horizon. Trees, hills, and buildings can make Polaris, or the point below the Southern Cross, seem lower or higher than it really is. So first find the clearest stretch of horizon you can, and make sure the sky is clear enough to pick out the reference stars confidently. If you are unsure, trace the line again a few minutes later: the stars drift slowly, but the geometry between the Big Dipper, Polaris, and the pole stays the same. That small double-check greatly reduces navigation mistakes."),
    },
    "lez-orbite-gravita": {
        "it": ("Passo 5 — Vederlo nella vita reale", "Un modo concreto per riconoscere un’orbita è guardare i satelliti che usi ogni giorno. Quelli bassi, vicini alla Terra, sentono una gravità più forte: corrono più veloci e fanno il giro in circa 90 minuti. Per questo molti satelliti per immagini e la Stazione Spaziale Internazionale passano spesso sopra zone diverse del pianeta. I satelliti geostazionari, invece, stanno molto più lontano: lì orbitano più lentamente e impiegano 24 ore, così restano sopra lo stesso punto dell’equatore. È lo stesso principio dei pianeti: cambiando distanza cambia la velocità necessaria, e da quella nasce anche la durata del giro."),
        "en": ("Step 5 — Seeing it in real life", "A practical way to spot an orbit is to look at the satellites you rely on every day. Low satellites, close to Earth, feel stronger gravity, so they must move faster and complete an orbit in about 90 minutes. That is why imaging satellites and the International Space Station sweep over different parts of the planet again and again. Geostationary satellites are much farther out. There, gravity is weaker, so they orbit more slowly and take 24 hours, which lets them stay above the same point on the equator. It is the same rule as for planets: change the distance, and you change the needed speed, which also changes the length of the orbit."),
    },
    "lez-password-sicura": {
        "it": ("Passo 5 — Provala nel mondo reale", "Ora applica il metodo a tre account diversi. Per la banca e l’email principale, lascia fare tutto al gestore di password: creerà stringhe lunghe e uniche che non devi ricordare. Per una password che vuoi tenere a mente, come quella del computer o del gestore stesso, inventa una frase di quattro o cinque parole casuali, lunga almeno 16 caratteri, senza riferimenti personali. Poi fai un controllo finale: potresti spiegarla a voce senza imbarazzo? La scriveresti su un post-it per non dimenticarla? Se la risposta è sì, semplificala nella struttura ma rendila più casuale nel contenuto. Sicura vuol dire anche praticabile ogni giorno."),
        "en": ("Step 5 — Try it in real life", "Now apply the method to three different accounts. For your bank and primary email, let a password manager do the work: it will create long, unique strings you never need to memorise. For one password you do want to remember, such as your computer login or the manager itself, invent a passphrase of four or five random words, at least 16 characters long, with nothing personal in it. Then do a final check: could you say it out loud without embarrassment? Would you be tempted to write it on a sticky note to avoid forgetting it? If yes, simplify the structure but make the words more random. Secure also has to work in everyday life."),
    },
    "lez-algoritmo": {
        "it": ("Passo 5 — Provalo nella vita reale", "Ora applica l’idea a un gesto quotidiano: decidere se uscire in bici. Scrivi un piccolo algoritmo in linguaggio naturale: controlla il meteo; se piove, scegli i mezzi; altrimenti controlla quanto tempo hai; se hai meno di 20 minuti, prendi comunque i mezzi; se hai tempo, verifica se la bici è pronta; finché non trovi lucchetto e luci, cercali; poi esci. Questo esercizio mostra una cosa utile: quando un problema sembra confuso, trasformarlo in passi lo rende più chiaro. Se ti blocchi, di solito manca una condizione precisa o un punto finale. Correggere un algoritmo spesso significa solo togliere ambiguità."),
        "en": ("Step 5 — Try it in real life", "Now apply the idea to an everyday decision: whether to go out by bike. Write a tiny algorithm in plain language: check the weather; if it is raining, take public transport; otherwise check how much time you have; if you have less than 20 minutes, take public transport anyway; if you have time, check whether the bike is ready; while you have not found the lock and lights, look for them; then leave. This exercise shows something useful: when a problem feels messy, turning it into steps makes it clearer. If you get stuck, a precise condition or an end point is usually missing. Improving an algorithm often just means removing ambiguity."),
    },
    "lez-ciclo-acqua": {
        "it": ("Fase 5 — Dal tetto al rubinetto", "Pensa a un temporale in città. Una parte dell’acqua cade su tetti e asfalto, entra nei tombini e finisce rapidamente in canali o fiumi, spesso senza ricaricare bene il suolo. Un’altra parte penetra nei terreni dei parchi e può raggiungere le falde, che alimentano molti acquedotti. Quando apri il rubinetto, quindi, stai usando acqua che magari è caduta come pioggia mesi o anni fa e ha fatto un viaggio lento sotto terra. Ecco perché superfici verdi, suoli permeabili e piccoli gesti quotidiani contano: aiutano l’acqua a rientrare nel ciclo utile, non solo a scorrere via in fretta."),
        "en": ("Phase 5 — From roof to tap", "Think about a city rainstorm. Some water lands on roofs and asphalt, runs into drains and reaches channels or rivers quickly, often without properly recharging the soil. Another portion sinks into park ground and can reach aquifers, which supply many water systems. So when you turn on the tap, you may be using water that fell as rain months or even years ago and travelled slowly underground. That is why green spaces, permeable ground and small daily choices matter: they help water re-enter the useful part of the cycle instead of rushing away at once. The cycle is global, but its most practical effects are local and very close to home."),
    },
    "lez-leggere-nuvole": {
        "it": ("Passo 5 — Fai una previsione breve", "Per chiudere il cerchio, prova a fare una previsione di sei ore usando solo ciò che vedi adesso e confrontala più tardi con il risultato reale. Se al mattino noti cumuli piccoli e separati, scrivi “stabile fino a sera”. Se i cirri aumentano e compare un alone, prova con “peggioramento entro domani”. Se il cielo si abbassa in uno strato grigio uniforme, aspettati pioggia debole ma continua. L’errore più comune è basarsi su una singola nuvola: conta invece la tendenza del cielo nell’arco di una o due ore, insieme al vento e alla direzione da cui arrivano le nubi. In pochi giorni il tuo occhio diventa molto più affidabile."),
        "en": ("Step 5 — Make a short forecast", "To tie it all together, try making a six-hour forecast using only what you can see now, then compare it with what actually happens later. If you spot small, separated cumulus in the morning, write down “stable until evening.” If cirrus is increasing and a halo appears, try “deterioration by tomorrow.” If the sky lowers into one even grey layer, expect light but steady rain. The most common mistake is judging from a single cloud: what matters is the sky’s trend over one or two hours, together with the wind and the direction the clouds are coming from. After a few days, your eye becomes much more reliable."),
    },
    "lez-classificare-animali": {
        "it": ("Passo 5 — Provalo nella vita reale", "La prossima volta che vedi un animale in un documentario, allo zoo o perfino su un cartello al parco, prova a classificarlo senza cercare subito il nome. Parti dalla domanda più ampia: ha la colonna vertebrale? Se sì, chiediti come respira, che rivestimento ha il corpo e come nascono i piccoli. Con una tartaruga, per esempio, arrivi a vertebrato, polmoni, squame secche, uova: rettile. Con una rana adulta: vertebrato, polmoni, pelle umida, uova: anfibio. Il trucco è usare più indizi insieme. Un solo dettaglio può confondere; la combinazione dei criteri, invece, ti porta quasi sempre alla classe giusta."),
        "en": ("Step 5 — Try it in real life", "Next time you see an animal in a documentary, at the zoo, or even on a sign in a park, try classifying it before looking up its name. Start with the broadest question: does it have a backbone? If yes, ask how it breathes, what covers its body, and how its young are born. With a turtle, for example, you get vertebrate, lungs, dry scales, eggs: reptile. With an adult frog: vertebrate, lungs, moist skin, eggs: amphibian. The key is to use several clues together. One feature alone can mislead you, but the combination of criteria will usually guide you to the right class."),
    },
    "lez-ecolocalizzazione": {
        "it": ("Passo 5 — Provalo nella vita reale", "Per sentire il principio senza strumenti, entra in una stanza vuota o sotto un portico e batti le mani una volta. Vicino a una parete il suono torna quasi subito e sembra più \"secco\"; in uno spazio grande o con superfici lontane la coda dell'eco è più lunga. Non stai misurando numeri come un pipistrello, ma il tuo cervello usa già quei ritorni per capire se un ambiente è stretto, ampio, morbido o duro. È anche il motivo per cui una chiesa, una palestra e un soggiorno arredato \"suonano\" in modo diverso. L'ecolocalizzazione, in forma semplice, è già dentro la tua esperienza quotidiana."),
        "en": ("Step 5 — Try it in real life", "To feel the principle without any equipment, step into an empty room or stand under a porch and clap once. Near a wall, the sound comes back almost immediately and feels sharper; in a larger space or one with distant hard surfaces, the echo lingers longer. You are not calculating numbers like a bat, but your brain is already using those returns to judge whether a place is tight, open, soft or hard. That is also why a church, a gym and a furnished living room all “sound” different. Echolocation, in a simple form, is already part of your everyday experience."),
    },
    "lez-linea-del-tempo": {
        "it": ("Passo 5 — Fai un controllo lampo", "Prima di fidarti del risultato, fai due verifiche rapide. Se converti un anno in secolo, chiediti se l’anno è all’inizio, nel mezzo o alla fine del secolo: 1900 deve stare nel XIX secolo, 1901 nel XX. Se lavori con date a.C., controlla che i numeri più grandi siano più antichi: 480 a.C. viene prima di 323 a.C. Se calcoli una durata che attraversa Cristo, ricordati di togliere uno e prova con un caso piccolo: da 1 a.C. a 1 d.C. passa 1 anno. Questo mini controllo evita quasi tutti gli errori tipici e ti rende molto più sicuro quando leggi libri, mappe o musei."),
        "en": ("Step 5 — Do a quick sanity check", "Before trusting your answer, do two fast checks. If you convert a year into a century, ask whether the year falls at the start, middle, or end of that century: 1900 must be in the 19th century, while 1901 begins the 20th. If you are working with BC dates, make sure larger numbers are earlier in time: 480 BC comes before 323 BC. If you calculate a span across the birth of Christ, remember to subtract one and test it with a tiny example: from 1 BC to AD 1 is 1 year. This brief check catches most common mistakes and makes you much steadier when reading books, maps, or museum timelines."),
    },
    "lez-valutare-fonte": {
        "it": ("Passo 5 — Provalo su un caso reale", "Immagina una foto che circola con la scritta: \"Proteste in città oggi\". Prima di condividerla, fai un controllo completo. Chi la pubblica: un testimone, un partito, una pagina anonima? Quando è stata scattata davvero: oggi o durante una manifestazione di anni fa? Per chi è confezionato il messaggio: cittadini, elettori, tifosi? Perché viene diffusa: documentare, mobilitare, spaventare? Infine cerca conferme indipendenti, magari con una ricerca inversa dell’immagine e con cronache locali. Spesso scopri che la foto è autentica ma il contesto è falso. È qui che si sbaglia più spesso: credere al documento e saltare il contorno, che invece ne cambia il significato."),
        "en": ("Step 5 — Try a real case", "Imagine a photo spreading with the caption: “Protests in the city today.” Before sharing it, run the full check. Who posted it: a witness, a party, an anonymous page? When was it actually taken: today, or during a demonstration years ago? For whom is the message shaped: residents, voters, supporters? Why is it being circulated: to document, mobilize, frighten? Then look for independent confirmation, maybe with a reverse image search and local reporting. You will often find that the photo itself is real but the context is false. That is the most common mistake: trusting the document and skipping the frame around it, even though that frame changes its meaning."),
    },
    "lez-memoria-tecniche": {
        "it": ("Passo 5 — Un esempio quotidiano", "Metti insieme tutto con un caso semplice: ricordare il nome di una persona appena conosciuta. Quando lo senti, presta attenzione e ripetilo subito una volta nella conversazione: aiuta la codifica. Poi crea un aggancio rapido, per esempio collega “Marco” a un amico con lo stesso nome o a un’immagine mentale. Dopo qualche minuto, prova a richiamarlo senza aiuti. Ripetilo più tardi nella giornata, poi il giorno dopo e a distanza di alcuni giorni. Se fai mente vuota, non è un fallimento: è proprio il tentativo di recupero che allena la memoria. Con nomi, concetti o liste, il principio resta identico."),
        "en": ("Step 5 — An everyday example", "Put it all together with a simple case: remembering the name of someone you’ve just met. When you hear it, pay attention and say it back once in conversation: that helps encoding. Then create a quick hook, such as linking “Maria” to someone you already know or to a vivid mental image. A few minutes later, try to recall it without help. Bring it back again later that day, then the next day, then a few days later. If you blank, that isn’t failure: the attempt to retrieve is exactly what trains memory. Whether it’s names, concepts, or lists, the same method applies."),
    },
    "lez-bias-conferma": {
        "it": ("Passo 5 — Provalo oggi", "Usalo su una decisione piccola ma reale, come scegliere un telefono, un integratore o un quartiere in cui trasferirti. Scrivi la tua ipotesi iniziale in una frase: “questo è la scelta migliore per me”. Poi imponiti una regola semplice: raccogli almeno due fonti affidabili contrarie e una informazione neutra prima di decidere. Nota anche come reagisci mentre leggi: irritazione, sollievo, voglia di chiudere la pagina sono segnali utili, perché spesso indicano che stai proteggendo un’idea più che valutando dei fatti. Alla fine, non chiederti “chi aveva ragione?”, ma “quale informazione ha davvero cambiato la qualità della mia decisione?”."),
        "en": ("Step 5 — Try it today", "Use it on a small but real decision, like choosing a phone, a supplement, or a neighbourhood to move to. Write your starting belief in one sentence: “this is the best option for me.” Then give yourself a simple rule: collect at least two reliable sources against your view and one neutral source before deciding. Also notice your reactions while reading: irritation, relief, or the urge to close the page are useful signals, because they often show you are protecting an idea rather than weighing facts. At the end, don’t ask, “who was right?” Ask, “which piece of information actually improved the quality of my decision?”"),
    },
}
