"""PAUSE v4 — ampliamento catalogo (parte C): Cultura, Curiosità, Economia.
3 curiosità + 3 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ CULTURA ------------------------------
    mk("cultura", "v4-okay-origine",
       "Da dove viene la parola più usata al mondo: OK", ["OK"],
       "Due lettere capite ovunque, da Tokyo a Buenos Aires. Nascono da uno scherzo ortografico su un giornale di Boston del 1839.",
       "OK nasce come abbreviazione scherzosa di 'oll korrect' nella stampa di Boston nel 1839, sopravvive grazie a una campagna elettorale e diventa globale con il telegrafo.",
       "",
       [
        ("Una moda di sigle sbagliate",
         "Nella Boston del 1838 i giovani giornalisti si divertivano ad abbreviare frasi scritte apposta male: 'KG' per 'know go' (no go), 'OW' per 'oll wright'. Il 23 marzo 1839 il Boston Morning Post stampò 'o.k.' per 'oll korrect', cioè 'all correct'. Doveva essere una battuta effimera."),
        ("Salvata da un presidente",
         "Nel 1840 il presidente Martin Van Buren, detto 'Old Kinderhook' dal suo paese natale, fece campagna con i club 'O.K.'. Lo slogan diffuse la sigla in tutto il Paese e le diede un doppio senso: Old Kinderhook è 'oll korrect'. Van Buren perse, OK vinse."),
        ("Perfetta per il telegrafo",
         "Con il telegrafo, le due lettere divennero il modo più rapido per confermare la ricezione di un messaggio: brevi, inconfondibili in Morse, senza ambiguità. Le ferrovie americane le adottarono negli anni Sessanta dell'Ottocento e da lì passò a tutto il mondo anglofono."),
        ("Le false origini",
         "Nel tempo sono nate decine di leggende: dal greco 'ola kala', dalla lingua choctaw 'okeh', dalle casse di biscotti 'Orrin Kendall', dai morti 'zero killed' della Guerra Civile. Tutte affascinanti, tutte smentite dal linguista Allen Walker Read, che nel 1963 rintracciò l'articolo del Boston Morning Post."),
       ]),
    mk("cultura", "v4-tredici-sfortuna",
       "Perché il 13 porta sfortuna (ma non ovunque)", ["13", "sfortuna"],
       "Grattacieli senza tredicesimo piano, aerei senza fila 13. Eppure in Italia il numero da temere è il 17 e in Cina il 4.",
       "Il 13 è temuto nei paesi cristiani per l'Ultima Cena e la mitologia nordica; l'Italia teme il 17 per una scritta latina, la Cina il 4 perché suona come 'morte'.",
       "",
       [
        ("Il tredicesimo a tavola",
         "All'Ultima Cena c'erano tredici commensali e il tredicesimo arrivato, secondo la tradizione, fu Giuda. Nella mitologia norrena, Loki fu il tredicesimo ospite non invitato a un banchetto degli dei, che finì con la morte di Baldr. Da qui il timore di essere tredici a tavola, ancora vivo in Francia."),
        ("Venerdì 13",
         "La combinazione con il venerdì è recente: si consolidò nel 1907 con il romanzo 'Friday, the Thirteenth' di Thomas Lawson, sul crollo di Wall Street in quel giorno. La leggenda che leghi la data all'arresto dei Templari (venerdì 13 ottobre 1307) è vera nella data, ma la superstizione è nata secoli dopo."),
        ("In Italia è il 17",
         "Il numero romano XVII si anagramma in VIXI, 'ho vissuto', cioè 'sono morto', iscrizione frequente sulle tombe romane. Per questo l'Alitalia non aveva la fila 17 e alcuni hotel italiani saltano la stanza 17. Il 13, da noi, è invece un numero fortunato: pensa al 'fare 13' al Totocalcio."),
        ("In Asia è il 4",
         "In cinese, giapponese e coreano il numero 4 si pronuncia quasi come la parola 'morte'. In Cina molti palazzi saltano i piani 4, 14 e 24, e le targhe con il 4 valgono meno. L'8, che suona come 'prosperità', è così ambito che le Olimpiadi di Pechino iniziarono l'8/8/2008 alle 8:08."),
       ]),
    mk("cultura", "v4-caffe-espresso",
       "Come l'Italia ha inventato l'espresso (e perché non è stata la prima con il caffè)", ["espresso"],
       "Il caffè arrivò a Venezia dai turchi; il bar all'italiana lo inventò un ingegnere milanese infastidito dalle lunghe attese.",
       "L'espresso nasce a Torino nel 1884 (Moriondo) e si perfeziona a Milano con Bezzera e Pavoni; la crema arriva solo nel 1948 con la leva di Gaggia.",
       "",
       [
        ("Venezia, 1645",
         "I chicchi arrivarono a Venezia dall'Impero Ottomano nel Seicento. Il primo caffè d'Europa aprì lì nel 1645; nel 1720 nasceva il Florian in piazza San Marco. Si beveva alla turca: bollito, denso, in tazze piccole. Il caffè era già italiano, ma non ancora 'espresso'."),
        ("L'ingegnere impaziente",
         "Nel 1884 Angelo Moriondo, a Torino, brevettò una macchina che usava vapore e pressione per preparare il caffè più in fretta, per servire tanti clienti insieme. Nel 1901 il milanese Luigi Bezzera aggiunse i gruppi per la tazza singola; Desiderio Pavoni ne comprò il brevetto e iniziò a produrla nel 1905."),
        ("La crema del 1948",
         "Quelle macchine, funzionando a vapore, bruciavano il caffè. Achille Gaggia, barista milanese, ideò nel 1938 e commercializzò nel 1948 una leva a molla che spingeva acqua calda ma non bollente a 9 atmosfere. Nacque la 'crema caffè': lo strato dorato che oggi definisce l'espresso."),
        ("Un rito, non una bevanda",
         "Il bar all'italiana, in piedi al bancone, veloce, con il prezzo del caffè quasi calmierato, è un'istituzione sociale. Nel 2022 l'Italia ha candidato il rito dell'espresso a patrimonio UNESCO. Trenta secondi di estrazione, 25 millilitri: una delle cose più brevi e più codificate della cultura italiana."),
       ]),

    # ------------------------------ CURIOSITÀ ------------------------------
    mk("curiosita", "v4-carta-sette-volte",
       "Perché non puoi piegare un foglio più di sette volte (e chi ci è riuscito)", ["piegare", "sette volte"],
       "Prova con qualsiasi foglio: alla settima piega si blocca. Una studentessa liceale ha dimostrato matematicamente come superare il limite.",
       "Ogni piega raddoppia lo spessore e dimezza la lunghezza; dopo 7 pieghe un foglio è 128 strati. Britney Gallivan nel 2002 ne fece 12 con carta igienica lunga 1,2 km.",
       "",
       [
        ("Il raddoppio esponenziale",
         "Un foglio è spesso 0,1 mm. Dopo una piega, 0,2; dopo sette, 12,8 mm, come 128 fogli impilati. La lunghezza intanto si è divisa per 128: un A4 lungo 30 cm diventa una striscia di 2 mm, più corta del suo spessore. Non c'è più nulla da piegare."),
        ("Se potessi continuare",
         "Con 23 pieghe il foglio sarebbe alto un chilometro. Con 42 arriverebbe alla Luna. Con 103 pieghe supererebbe il diametro dell'universo osservabile. È lo stesso raddoppio esponenziale degli interessi composti, delle epidemie e dei chicchi di riso sulla scacchiera."),
        ("La studentessa che sfidò il limite",
         "Nel 2002 Britney Gallivan, 16 anni, in California, ricavò una formula per la lunghezza minima di carta necessaria per un dato numero di pieghe. Poi comprò 1.200 metri di carta igienica speciale, la stese in un centro commerciale e la piegò 12 volte in un'unica direzione. Il record entrò nei libri di matematica."),
        ("Il segreto è la lunghezza",
         "Ogni piega 'consuma' carta nella curva: più strati ci sono, più larga è la curva. La formula di Gallivan calcola quanto serve. Con un foglio grande come un campo da calcio e un rullo compressore, un team di MIT ha raggiunto 13 pieghe nel 2012. Il limite non era sette: era la dimensione della carta."),
       ]),
    mk("curiosita", "v4-pop-corn",
       "Perché il pop-corn scoppia", ["pop-corn", "scoppia"],
       "Di tutti i cereali, solo il mais, e solo una varietà, esplode. Dentro ogni chicco c'è una pentola a pressione naturale.",
       "Il chicco di mais da pop-corn ha un guscio impermeabile; l'acqua interna diventa vapore a pressione fino a 9 atmosfere e, a 180 °C, fa esplodere l'amido in schiuma.",
       "",
       [
        ("Una pentola a pressione",
         "Il chicco di mais contiene circa il 14% di acqua, intrappolata in una matrice di amido e chiusa da un pericarpo, il guscio, durissimo e impermeabile. Scaldandolo, l'acqua diventa vapore ma non può uscire: la pressione sale fino a circa 9 atmosfere, come una pentola a pressione."),
        ("Il pop",
         "Intorno ai 180 °C il guscio cede. L'acqua surriscaldata si espande in un istante, l'amido gelatinizzato si gonfia in una schiuma di bolle e si solidifica all'aria in pochi millesimi di secondo. Il chicco si rovescia come un calzino: ciò che era dentro diventa fuori, 40 volte più grande."),
        ("Perché solo il mais",
         "Riso, grano e orzo hanno gusci porosi: il vapore esce piano e non si accumula pressione. Solo il mais 'everta', una varietà a chicco piccolo e duro, ha il pericarpo abbastanza forte e impermeabile. I chicchi che non scoppiano hanno una crepa nel guscio o troppa poca acqua dentro."),
        ("Il rumore non viene dal guscio",
         "Ricercatori francesi hanno filmato pop-corn a 2.900 fotogrammi al secondo: il 'pop' si sente quando il vapore esce, non quando il guscio si rompe. Ed è il rilascio del vapore a far saltare il chicco in aria, come un piccolo razzo. Un antipasto vecchio 6.000 anni, trovato in grotte del Perù e del New Mexico."),
       ]),
    mk("curiosita", "v4-strisce-zebra",
       "Le strisce delle zebre servono contro le mosche", ["strisce", "zebre"],
       "Per un secolo si è discusso se servissero a confondere i leoni. La risposta è arrivata vestendo dei cavalli con coperte a strisce.",
       "Le strisce confondono il sistema visivo delle mosche tse-tse e dei tafani, che non riescono ad atterrare sull'animale; è oggi la spiegazione con più prove.",
       "",
       [
        ("Le ipotesi classiche",
         "Camuffamento nell'erba alta? Le zebre stanno in savana aperta. Confondere i leoni in gruppo? I leoni cacciano di notte, quando le strisce non si vedono. Raffreddamento con micro-correnti d'aria? Misurato: non funziona. Per 150 anni nessuna ipotesi reggeva ai dati."),
        ("Il pattern delle mosche",
         "Nel 2014 Tim Caro confrontò le specie di equidi: quelle più striate vivono dove ci sono più mosche tse-tse e tafani, insetti che portano malattie mortali per i cavalli. La correlazione era netta. Restava da capire il meccanismo."),
        ("Cavalli in pigiama",
         "Nel 2019, in una fattoria inglese, i ricercatori vestirono cavalli con coperte nere, bianche e a strisce. Le mosche si avvicinavano ugualmente a tutti, ma su quelle a strisce non riuscivano ad atterrare: frenavano male e rimbalzavano. Le strisce sembrano confondere il calcolo della distanza negli occhi dell'insetto."),
        ("Un'idea da copiare",
         "Alcuni allevatori dipingono strisce bianche sulle mucche: uno studio giapponese ha misurato il 50% di morsi in meno. Le zebre non hanno scelto le strisce per bellezza o per i predatori grandi, ma per sfuggire ai piccoli. Spesso, in natura, il nemico vero è quello che non si vede."),
       ]),

    # ------------------------------ ECONOMIA ------------------------------
    mk("economia", "v4-tulipani-bolla",
       "La prima bolla finanziaria: un bulbo di tulipano per una casa", ["tulipano", "bolla"],
       "Nell'Olanda del 1637 un singolo bulbo poteva valere quanto una casa sui canali di Amsterdam. Poi, in una settimana, il crollo.",
       "La tulipomania olandese del 1636-37 vide i prezzi dei bulbi decuplicare e crollare del 99% in pochi giorni; è il modello di ogni bolla speculativa successiva.",
       "",
       [
        ("Un fiore esotico",
         "I tulipani arrivarono dall'Impero Ottomano nel Cinquecento. Rari, colorati, con venature imprevedibili (causate, si scoprì secoli dopo, da un virus), divennero uno status symbol per i ricchi mercanti dell'Età dell'oro olandese. Un bulbo fioriva una volta l'anno: la scarsità era garantita."),
        ("Comprare il futuro",
         "I bulbi si vendevano in inverno, quando erano sotto terra: si scambiavano contratti su fiori che nessuno aveva visto. Nel 1636 entrarono nel mercato artigiani e osti; i contratti passavano di mano dieci volte al giorno nelle taverne. Un bulbo 'Semper Augustus' arrivò a 10.000 fiorini: il prezzo di una casa di lusso."),
        ("Febbraio 1637",
         "Il 3 febbraio 1637, a un'asta di Haarlem, nessuno fece offerte. La notizia si diffuse in giorni: tutti volevano vendere, nessuno comprare. I prezzi caddero del 90-99%. I contratti furono in gran parte annullati per legge; l'economia olandese nel complesso resse, ma molte famiglie furono rovinate."),
        ("Lo schema che si ripete",
         "Un bene nuovo e difficile da valutare, storie di arricchimento rapido, ingresso di chi non capisce cosa compra, credito facile, e la convinzione che 'questa volta è diverso'. Ferrovie nel 1840, dot-com nel 2000, immobili nel 2007: cambiano i tulipani, non la dinamica."),
       ]),
    mk("economia", "v4-prezzi-99",
       "Perché i prezzi finiscono sempre con ,99", ["99"],
       "9,99 invece di 10. Lo sappiamo tutti, eppure funziona ancora. E l'origine potrebbe non avere nulla a che fare con la psicologia.",
       "Il cervello legge il prezzo da sinistra e 'ancora' sulla prima cifra: 9,99 sembra molto meno di 10. L'origine storica è però legata forse alla lotta contro i furti dei commessi.",
       "",
       [
        ("L'effetto cifra sinistra",
         "Leggiamo i numeri da sinistra e la prima cifra pesa più delle altre. 9,99 viene codificato come 'nove e qualcosa', 10,00 come 'dieci'. Negli esperimenti, alzare un prezzo da 34 a 39 dollari ha aumentato le vendite; alzarlo a 44 le ha ridotte. Il 9 finale funziona meglio di un prezzo più basso."),
        ("Un segnale di sconto",
         "Anni di saldi ci hanno insegnato che i prezzi 'tondi' sono di listino e quelli 'a 9' sono ribassati. Il 9 comunica 'occasione' anche quando non lo è. I marchi di lusso usano l'opposto: prezzi tondi, 1.200 e non 1.199, per segnalare che non hanno bisogno di trucchi."),
        ("La leggenda dei commessi",
         "L'origine storica più citata: alla fine dell'Ottocento, con prezzi come 99 cent, il commesso era costretto ad aprire il registratore di cassa per dare il resto, lasciando traccia della vendita. Con 1 dollaro tondo poteva intascare la banconota. La prova storica è debole, ma l'idea è plausibile."),
        ("Quando non funziona",
         "Se il cliente compra spesso lo stesso prodotto, impara il prezzo reale e l'effetto sparisce. E per chi calcola il totale del carrello, i ,99 sono una fatica che genera irritazione. Alcune catene stanno tornando ai prezzi tondi proprio per apparire più oneste. Il trucco funziona finché non lo noti."),
       ]),
    mk("economia", "v4-banconote-valore",
       "Perché una banconota vale qualcosa se è solo carta", ["banconota", "carta"],
       "Costa pochi centesimi stamparla e nessuno ti darà oro in cambio. Eppure ci fidiamo. Il denaro moderno regge su una sola cosa.",
       "Dal 1971 il denaro non è coperto da oro: vale perché lo Stato lo accetta per le tasse, la legge lo impone e tutti si aspettano che gli altri lo accettino. È fiducia organizzata.",
       "",
       [
        ("Dal metallo alla carta",
         "Le prime banconote, in Cina nel VII secolo e in Europa nel Seicento, erano ricevute: 'questo pezzo di carta vale tanto oro depositato in banca'. Pesavano meno delle monete ed erano più sicure da trasportare. La carta rappresentava il metallo."),
        ("1971: la fine dell'oro",
         "Fino al 1971 il dollaro era convertibile in oro a 35 dollari l'oncia e le altre valute erano agganciate al dollaro. Il 15 agosto 1971 Nixon sospese la convertibilità: da allora nessuna valuta al mondo è coperta da oro. Il denaro è 'fiat': vale perché così è stabilito."),
        ("Cosa lo sostiene davvero",
         "Tre cose. Lo Stato accetta solo quella moneta per pagare le tasse, creando una domanda garantita. La legge la rende 'a corso legale': un creditore deve accettarla. E soprattutto l'aspettativa: la accetto perché so che domani il panettiere la accetterà da me. È una fiducia circolare, ma solidissima finché dura."),
        ("Quando la fiducia si rompe",
         "Se lo Stato stampa troppo, ogni banconota vale meno: è l'inflazione. Nella Germania del 1923 un chilo di pane costava 400 miliardi di marchi e si bruciavano banconote per scaldarsi. Le banche centrali indipendenti esistono per questo: tenere la stampa lontana dalla tentazione politica."),
       ]),
]

LESSONS = [
    # ------------------------------ CULTURA ------------------------------
    L("cultura", "v4-lez-galateo-mondo",
      "Buone maniere nel mondo: 4 gesti che cambiano significato", ["gesti", "mondo"],
      "Il pollice in su, la mancia, il silenzio a tavola: ciò che è cortese a Roma può essere offensivo a Tokyo. Un mini-corso per viaggiare senza gaffe.",
      "Conoscere le principali differenze culturali nei gesti, nel saluto, a tavola e nel dare la mancia.",
      "Informati prima su gesti, saluti, regole a tavola e mance del paese: le regole variano molto e la buona volontà non basta a evitare le offese involontarie.",
      [
       ("Passo 1 — Le mani parlano lingue diverse",
        "Il pollice in su è positivo in Occidente ma volgare in Iran e parte del Medio Oriente. L'OK con le dita è offensivo in Brasile e Turchia. Indicare con il dito è scortese in molti paesi asiatici: usa la mano aperta. In Giappone non soffiarti il naso in pubblico; in Thailandia non toccare la testa a nessuno."),
       ("Passo 2 — Il saluto",
        "Stretta di mano ferma in Germania e Stati Uniti, più morbida in Asia. In Giappone un inchino leggero; in Thailandia il 'wai' con le mani giunte. Il bacio sulla guancia: due in Italia e Spagna, tre in Olanda e Svizzera, fino a quattro in alcune zone di Francia. Nel dubbio, aspetta e imita."),
       ("Passo 3 — A tavola",
        "In Giappone e Cina non piantare le bacchette nel riso: è un rito funebre. In Cina lasciare un po' di cibo è educato (hai avuto abbastanza); in India e Giappone finire tutto lo è. Fare rumore mangiando i noodles in Giappone è apprezzamento. In Francia le mani stanno sul tavolo, non in grembo. In India si mangia con la destra."),
       ("Passo 4 — La mancia",
        "Negli Stati Uniti è obbligatoria di fatto (18-22%): i camerieri hanno stipendi bassi. In Giappone e Corea è quasi offensiva: il servizio è incluso e impeccabile per definizione. In Europa il conto include il servizio e la mancia è un arrotondamento. In Cina non è attesa. Dieci minuti di ricerca prima del viaggio evitano imbarazzi."),
      ]),
    L("cultura", "v4-lez-leggere-poesia",
      "Come leggere una poesia senza sentirsi stupidi", ["poesia"],
      "Non si tratta di 'capire cosa voleva dire il poeta'. Si tratta di leggere lentamente e in modo diverso. Quattro passi che funzionano con Dante e con i testi delle canzoni.",
      "Avvicinarsi a una poesia con un metodo semplice: lettura ad alta voce, immagini, suono, e solo dopo il significato.",
      "Leggi ad alta voce due volte, individua le immagini concrete, ascolta il ritmo e le ripetizioni, e solo alla fine chiediti cosa ti fa sentire. Il significato arriva da lì.",
      [
       ("Passo 1 — Ad alta voce, due volte",
        "La poesia nasce per l'orecchio. Leggila a voce alta, seguendo la punteggiatura e non la fine del verso: molte frasi continuano sulla riga dopo. La prima volta ti perdi, è normale. La seconda cominci a sentire dove il testo rallenta, accelera, si ferma."),
       ("Passo 2 — Cerca le cose",
        "Sottolinea gli oggetti concreti: un albero, una mano, una finestra, la pioggia. Le poesie non parlano di 'tristezza': mostrano una sedia vuota. Le immagini sono la porta d'ingresso; il concetto astratto, se c'è, viene dopo e spesso lo costruisci tu."),
       ("Passo 3 — Ascolta il suono",
        "Ci sono parole che si ripetono? Suoni che tornano (rime, allitterazioni)? Versi corti che spezzano il ritmo? In 'M'illumino d'immenso' di Ungaretti quasi tutto è nella ripetizione delle m e nell'esplosione di luce di quattro parole. Il suono è già significato."),
       ("Passo 4 — Cosa ti fa sentire",
        "Solo ora chiediti: che effetto mi fa? Malinconia, energia, spiazzamento? Non esiste una risposta giusta da indovinare; esiste un incontro tra il testo e te. Se una poesia non ti dice nulla, passa a un'altra: nessuno ama tutta la musica, nessuno deve amare tutta la poesia."),
      ]),
    L("cultura", "v4-lez-imparare-lingua",
      "Imparare una lingua da adulti: cosa dice la ricerca in 4 punti", ["lingua"],
      "Non è troppo tardi e non serve un talento speciale. Serve fare le cose nell'ordine giusto e smettere di studiare come a scuola.",
      "Applicare i principi dell'acquisizione linguistica per imparare una lingua straniera in modo efficace da adulti.",
      "Molto input comprensibile, ripetizione distanziata del lessico, parlare presto anche male, e pochi minuti ogni giorno anziché una lezione a settimana.",
      [
       ("Passo 1 — Input, tanto e comprensibile",
        "Il cervello impara la lingua da ciò che capisce quasi tutto, non dalle regole. Guarda serie con sottotitoli nella lingua originale, ascolta podcast per principianti, leggi libri per bambini. Se capisci il 70-80%, sei nel punto giusto. Le regole di grammatica servono dopo, per mettere ordine, non per partire."),
       ("Passo 2 — Le parole giuste, ripetute al momento giusto",
        "Le 1.000 parole più frequenti coprono l'80% di una conversazione normale. Impara quelle, con frasi intere e non liste isolate, usando la ripetizione distanziata: un'app tipo Anki ti mostra la parola poco prima che la dimenticheresti. Dieci minuti al giorno bastano."),
       ("Passo 3 — Parla subito, anche male",
        "Aspettare di 'essere pronti' è il modo migliore per non parlare mai. Trova un tandem linguistico online, parla da solo descrivendo ciò che fai, registra messaggi vocali. Gli errori non si fissano: si correggono con l'esposizione. Un adulto ha un vantaggio sui bambini: sa già come funziona una lingua."),
       ("Passo 4 — Ogni giorno, poco",
        "Venti minuti al giorno battono tre ore la domenica: la memoria si consolida nel sonno, e sette notti sono meglio di una. Lega la lingua a una tua passione: cucina, calcio, videogiochi, in quella lingua. La motivazione dura quando la lingua è un mezzo per qualcosa che ami, non un fine."),
      ]),

    # ------------------------------ CURIOSITÀ ------------------------------
    L("curiosita", "v4-lez-stimare",
      "Stimare al volo: quanti, quanto, quanto grande", ["stimare"],
      "Quante persone in piazza? Quanto pesa quell'albero? Il metodo di Fermi ti permette di rispondere in un minuto senza cercare su internet, e di beccarci entro un fattore 2.",
      "Usare le stime di Fermi per rispondere a domande quantitative scomponendole in fattori conosciuti.",
      "Scomponi la domanda in pezzi che sai stimare, usa potenze di 10, moltiplica. Gli errori si compensano e arrivi vicino al vero. Poi verifica: è così che si impara a calibrarsi.",
      [
       ("Passo 1 — Scomponi",
        "Quanti accordatori di pianoforte ci sono a Milano? Non lo sai. Ma sai stimare: abitanti (1,4 milioni), famiglie (circa 600.000), quante hanno un piano (1 su 30, quindi 20.000), quante volte l'anno si accorda (1), quanti pianoforti accorda un professionista in un anno (4 al giorno per 200 giorni, 800). Risultato: 25. Il numero reale è vicino."),
       ("Passo 2 — Potenze di 10",
        "Non cercare la precisione: chiediti se una grandezza è 10, 100 o 1.000. Il cervello è pessimo con i numeri esatti ma discreto con gli ordini di grandezza. Gli errori per eccesso e per difetto nei vari fattori tendono a compensarsi: è il segreto del metodo."),
       ("Passo 3 — Ancore fisiche",
        "Tieni a mente qualche riferimento: un passo è quasi un metro; una persona occupa circa 2-4 per metro quadro in una folla compatta; un'auto pesa 1,5 tonnellate; un litro d'acqua un chilo; un adulto beve 2 litri al giorno. Con dieci ancore puoi stimare quasi tutto."),
       ("Passo 4 — Verifica e calibra",
        "Dopo la stima, cerca il dato vero. Eri entro un fattore 2? Ottimo. Entro un fattore 10? Chiediti quale fattore hai sbagliato. In un mese di giochi così, la tua intuizione per i numeri migliora in modo misurabile: è la differenza tra chi si fa impressionare dalle cifre e chi le capisce."),
      ]),
    L("curiosita", "v4-lez-perche-cielo-notte",
      "Perché di notte è buio: il paradosso che rivela l'età dell'universo", ["buio", "universo"],
      "Sembra una domanda da bambini. In realtà ha tenuto occupati gli astronomi per tre secoli, e la risposta dice qualcosa di enorme sul cosmo.",
      "Capire il paradosso di Olbers e come la sua soluzione dimostri che l'universo ha un'età finita.",
      "Se l'universo fosse infinito ed eterno, ogni direzione finirebbe su una stella e il cielo sarebbe luminoso. È buio perché l'universo ha un'età: la luce delle stelle troppo lontane non è ancora arrivata.",
      [
       ("Passo 1 — Il problema",
        "Immagina una foresta infinita: in qualunque direzione guardi, lo sguardo finisce su un tronco. Se l'universo fosse infinito e pieno di stelle da sempre, ogni linea di vista finirebbe su una stella e il cielo notturno sarebbe luminoso come il Sole. Non lo è. Qualcosa nelle premesse è sbagliato."),
       ("Passo 2 — Le false soluzioni",
        "'La polvere assorbe la luce': ma la polvere si scalderebbe fino a brillare a sua volta. 'Le stelle lontane sono troppo deboli': ma ce ne sono più, in proporzione, e le due cose si compensano esattamente. Per due secoli nessuna spiegazione ha retto."),
       ("Passo 3 — La risposta: il tempo",
        "L'universo ha 13,8 miliardi di anni. La luce viaggia a velocità finita, quindi possiamo vedere solo stelle la cui luce ha avuto il tempo di raggiungerci: una 'bolla' di circa 46 miliardi di anni luce di raggio. Oltre, ci sono stelle la cui luce non è ancora arrivata. Il cielo è buio perché l'universo è giovane."),
       ("Passo 4 — E l'espansione",
        "C'è un secondo effetto: l'universo si espande e la luce delle galassie lontane si 'stira' verso il rosso e l'infrarosso, fuori dal visibile. Il bagliore del Big Bang è ancora lì, in ogni direzione, ma stirato fino alle microonde: è la radiazione cosmica di fondo. Il cielo notturno, in un certo senso, brilla davvero. Solo non a occhio nudo."),
      ]),
    L("curiosita", "v4-lez-coincidenze",
      "Perché le coincidenze non sono così incredibili", ["coincidenze"],
      "Pensi a una persona e ti chiama. In una stanza di 23 persone due fanno il compleanno lo stesso giorno. La matematica dice che sarebbe strano il contrario.",
      "Capire perché eventi apparentemente improbabili accadono spesso, usando il paradosso del compleanno e la legge dei grandi numeri.",
      "Con tante occasioni, anche eventi rari accadono di sicuro. Ricordiamo le coincidenze e dimentichiamo i milioni di non-coincidenze. In 23 persone, la probabilità di due compleanni uguali è oltre il 50%.",
      [
       ("Passo 1 — Il paradosso del compleanno",
        "Quante persone servono in una stanza perché due festeggino lo stesso giorno con probabilità superiore al 50%? Non 183: bastano 23. Il trucco: non stai confrontando una persona con le altre, ma ogni coppia possibile. Con 23 persone ci sono 253 coppie. Con 60 persone la probabilità supera il 99%."),
       ("Passo 2 — La legge dei numeri davvero grandi",
        "Un evento che ha una probabilità di uno su un milione al giorno, in Italia con 60 milioni di abitanti, succede a 60 persone ogni giorno. Sognare un parente la notte in cui muore è raro per te, ma in un Paese succede continuamente a qualcuno. E quel qualcuno lo racconta."),
       ("Passo 3 — La memoria selettiva",
        "Quante volte hai pensato a una persona che non ha chiamato? Migliaia. Non le ricordi, perché non è successo niente. Ricordi l'unica volta in cui ha chiamato. Il cervello archivia i colpi a segno e cancella i buchi nell'acqua: è così che nasce la sensazione che 'non può essere un caso'."),
       ("Passo 4 — Prova a contare",
        "Per una settimana annota ogni volta che ti viene in mente una persona e se ti contatta entro 24 ore. Ti troverai con una lista di 50 pensieri e magari un contatto. Non toglie la magia all'incontro fortunato: aggiunge la comprensione di quanto sia comune l'insolito in un mondo affollato."),
      ]),

    # ------------------------------ ECONOMIA ------------------------------
    L("economia", "v4-lez-budget-50-30-20",
      "Il budget 50/30/20: gestire lo stipendio in 4 passi", ["budget"],
      "Non serve un foglio Excel con 40 categorie. Una regola semplice usata da milioni di persone per sapere dove finiscono i soldi ogni mese.",
      "Impostare un budget mensile con la regola 50/30/20 e adattarla alla propria situazione.",
      "Metà del netto per le necessità, il 30% per i desideri, il 20% per risparmio e debiti. Automatizza il risparmio il giorno dello stipendio e rivedi le proporzioni ogni tre mesi.",
      [
       ("Passo 1 — Parti dal netto",
        "Prendi quello che entra davvero sul conto ogni mese, dopo tasse e contributi. Se hai entrate variabili, usa la media degli ultimi sei mesi al ribasso. Questo è il 100% da dividere. Non contare bonus e tredicesime: quelli sono extra da destinare al risparmio."),
       ("Passo 2 — 50% necessità",
        "Affitto o mutuo, bollette, spesa alimentare, trasporti per il lavoro, assicurazioni, rate obbligatorie. Se superano il 50%, il problema non è il caffè al bar: è la voce grande, di solito la casa. Non è colpa tua, ma è lì che vale la pena agire nel medio periodo."),
       ("Passo 3 — 30% desideri, 20% futuro",
        "Il 30% è per ciò che rende la vita piacevole: ristoranti, viaggi, abbonamenti, vestiti non necessari. Senza sensi di colpa, ma dentro il limite. Il 20% va a risparmio, investimenti e rimborso anticipato dei debiti. Prima il fondo di emergenza (3-6 mesi di spese), poi il resto."),
       ("Passo 4 — Automatizza e rivedi",
        "Il giorno dello stipendio, un bonifico automatico sposta il 20% su un conto separato. Ciò che non vedi non lo spendi. Ogni tre mesi controlla: le proporzioni tornano? Se il 20% è impossibile oggi, parti dal 5% e alza di un punto ogni trimestre. La regola è una bussola, non una gabbia."),
      ]),
    L("economia", "v4-lez-leggere-busta-paga",
      "Leggere la busta paga: dove finiscono i soldi tra lordo e netto", ["busta paga"],
      "Tra ciò che costi all'azienda e ciò che arriva sul conto c'è quasi la metà. Quattro passi per capire le voci e controllare che tutto sia corretto.",
      "Interpretare le voci principali di una busta paga italiana: lordo, contributi, IRPEF, detrazioni, netto.",
      "Dal lordo si tolgono i contributi pensionistici (circa 9%), poi l'IRPEF a scaglioni ridotta dalle detrazioni, poi le addizionali locali. Controlla ferie, TFR e livello.",
      [
       ("Passo 1 — Il lordo e il costo azienda",
        "In alto trovi la retribuzione lorda mensile, definita dal contratto collettivo (CCNL) e dal tuo livello. Non è il tuo costo per l'azienda: quella paga anche contributi a suo carico, circa il 30% in più. Se il lordo è 2.000 euro, all'azienda costi circa 2.600."),
       ("Passo 2 — I contributi",
        "La prima trattenuta è la tua quota di contributi previdenziali, circa il 9,19% del lordo, versata all'INPS per la pensione. Sono soldi tuoi, differiti. Sulla parte che resta (l'imponibile fiscale) si calcolano le tasse."),
       ("Passo 3 — IRPEF e detrazioni",
        "L'IRPEF si calcola a scaglioni: le prime fasce di reddito sono tassate meno, le successive di più. Da quanto risulta si sottraggono le detrazioni: per lavoro dipendente, per figli e familiari a carico, per spese sanitarie e mutuo nella dichiarazione dei redditi. Poi si aggiungono le addizionali regionale e comunale."),
       ("Passo 4 — Controlla il resto",
        "In basso trovi il netto, ma non fermarti lì. Verifica: ferie e permessi maturati e goduti (i residui sono soldi), il TFR accantonato (circa un mese di stipendio l'anno), gli straordinari pagati, il livello contrattuale corretto. Gli errori in busta paga sono più comuni di quanto si pensi e prescrivono in pochi anni."),
      ]),
    L("economia", "v4-lez-domanda-offerta",
      "Domanda e offerta: perché i prezzi salgono e scendono", ["domanda", "offerta"],
      "I biglietti del concerto esauriti, le mascherine nel 2020, le case in centro: dietro ogni prezzo c'è lo stesso meccanismo. Impararlo ti rende un consumatore e un cittadino più lucido.",
      "Capire come domanda e offerta determinano i prezzi e riconoscere il meccanismo negli esempi quotidiani.",
      "Il prezzo sale quando molti vogliono una cosa scarsa e scende quando ne abbonda o pochi la vogliono. Il prezzo è un segnale che sposta risorse: capirlo spiega rincari, saldi e carenze.",
      [
       ("Passo 1 — La domanda",
        "La domanda è quanto la gente vuole comprare a ogni prezzo. A prezzo basso, tanti compratori; a prezzo alto, pochi. Cambia con il reddito, le mode, i sostituti disponibili: se il prezzo della carne sale, la domanda di legumi cresce. Il cornetto a 1 euro lo compri; a 5 ci pensi."),
       ("Passo 2 — L'offerta",
        "L'offerta è quanto i produttori vogliono vendere a ogni prezzo. A prezzo alto conviene produrre di più; a prezzo basso, meno. Dipende dai costi, dalla tecnologia, dal numero di concorrenti. Quando il prezzo del grano sale, più agricoltori seminano grano l'anno dopo."),
       ("Passo 3 — L'equilibrio e lo squilibrio",
        "Il prezzo si assesta dove ciò che si vuole comprare eguaglia ciò che si vuole vendere. Se il prezzo è troppo basso, la merce finisce: biglietti esauriti in 10 minuti, code, bagarini. Se è troppo alto, resta invenduta: saldi di fine stagione. La carenza e lo spreco sono il segnale che il prezzo è 'sbagliato'."),
       ("Passo 4 — Il prezzo è informazione",
        "Nel 2020 le mascherine passarono da 10 centesimi a 2 euro: brutto, ma quel prezzo convinse centinaia di fabbriche a produrne, e in tre mesi il prezzo crollò. Bloccare un prezzo per legge elimina il segnale: spesso il risultato è lo scaffale vuoto. Capire il meccanismo non significa amarlo, ma permette di discutere soluzioni che funzionano."),
      ]),
]
