"""PAUSE v4 — ampliamento catalogo (parte A): Scienza, Spazio, Tecnologia, Natura.
3 curiosità + 3 mini lezioni per categoria, scritte a mano in italiano.
Le traduzioni EN vengono generate a posteriori dalla pipeline (generate_content.py)."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ SCIENZA ------------------------------
    mk("scienza", "v4-ghiaccio-galleggia",
       "Perché il ghiaccio galleggia sull'acqua?", ["ghiaccio", "galleggia"],
       "Quasi tutti i solidi affondano nel proprio liquido. L'acqua fa il contrario, e senza questa stranezza la vita sulla Terra sarebbe molto diversa.",
       "Congelando, le molecole d'acqua si dispongono in un reticolo esagonale più spazioso: il ghiaccio è meno denso e galleggia, isolando laghi e mari dal freddo.",
       "",
       [
        ("Un'eccezione alla regola",
         "Di solito un materiale solido è più compatto del suo liquido, perché le molecole si fermano e si stringono. L'acqua però, sotto i 4 °C, comincia a espandersi. Quando congela occupa circa il 9% di volume in più: ecco perché una bottiglia piena lasciata nel freezer si spacca."),
        ("La colpa è dei legami a idrogeno",
         "Ogni molecola d'acqua può stringere fino a quattro legami a idrogeno con le vicine. Nel ghiaccio questi legami si ordinano in un reticolo esagonale pieno di spazi vuoti. Nel liquido, invece, le molecole scivolano l'una sull'altra e riempiono meglio lo spazio. Più vuoti significa meno densità, e ciò che è meno denso galleggia."),
        ("Una coperta per i laghi",
         "Se il ghiaccio affondasse, i laghi gelerebbero dal fondo verso l'alto e diventerebbero blocchi solidi ogni inverno. Invece lo strato in superficie fa da isolante: sotto, l'acqua resta liquida intorno ai 4 °C e pesci, alghe e microrganismi sopravvivono fino alla primavera."),
        ("Lo stesso motivo dei fiocchi di neve",
         "La simmetria a sei lati del reticolo di ghiaccio è anche il motivo per cui i fiocchi di neve hanno sempre sei punte. La forma che vedi su una manica in inverno è il ritratto ingrandito di come le molecole d'acqua si sono date la mano."),
       ]),
    mk("scienza", "v4-sale-neve",
       "Perché il sale scioglie la neve sulle strade?", ["sale", "neve"],
       "Camion che spargono sale prima di una nevicata: un gesto semplice che nasconde una legge fisica valida per ogni liquido.",
       "Il sale abbassa il punto di congelamento dell'acqua: mescolato alla neve crea una salamoia che resta liquida anche sotto zero, fino a circa -9 °C con il sale comune.",
       "",
       [
        ("Un equilibrio disturbato",
         "A 0 °C ghiaccio e acqua convivono in equilibrio: tante molecole congelano quante se ne sciolgono. Il sale, dissolvendosi, si mette in mezzo con i suoi ioni e rende più difficile alle molecole d'acqua ricostruire il reticolo del ghiaccio. Per congelare servono temperature più basse."),
        ("Fino a dove funziona",
         "Con il cloruro di sodio, il sale da cucina, l'effetto arriva fino a circa -9 °C; sotto quella soglia la salamoia gela lo stesso. Per questo nei paesi molto freddi si usa il cloruro di calcio, che funziona fino a -30 °C e, sciogliendosi, rilascia anche calore."),
        ("Serve un po' d'acqua per partire",
         "Il sale secco su ghiaccio secco fa poco: deve prima dissolversi in un velo di acqua liquida. Ecco perché spesso si sparge una soluzione salina liquida prima della nevicata: la strada è già 'pronta' e la neve, cadendo, non riesce ad attaccarsi all'asfalto."),
        ("Il lato oscuro",
         "Il sale corrode auto, ponti e tubature e finisce nei fiumi e nel suolo, danneggiando piante e fauna. Molte città sperimentano alternative come succo di barbabietola, sabbia o semplici limiti alla quantità sparsa: la fisica funziona, ma ha un costo ambientale."),
       ]),
    mk("scienza", "v4-microonde",
       "Come fa il microonde a scaldare il cibo senza scaldarsi?", ["microonde"],
       "Il piatto esce bollente, ma il forno resta freddo. Dentro quella scatola non c'è fuoco: c'è una radio potente sintonizzata sull'acqua.",
       "Le microonde fanno vibrare le molecole d'acqua, zuccheri e grassi miliardi di volte al secondo; l'attrito tra molecole diventa calore direttamente dentro il cibo.",
       "",
       [
        ("Una radio da 2,45 gigahertz",
         "Al cuore del forno c'è il magnetron, un dispositivo che genera onde elettromagnetiche a 2,45 miliardi di oscillazioni al secondo. Sono le stesse onde radio del Wi-Fi, ma con una potenza migliaia di volte maggiore, confinate in una scatola metallica che le riflette."),
        ("Le molecole d'acqua ballano",
         "La molecola d'acqua ha un lato leggermente positivo e uno negativo: è un piccolo magnete elettrico. Il campo delle microonde cambia direzione 4,9 miliardi di volte al secondo e le molecole cercano di seguirlo, ruotando avanti e indietro. Quello sfregamento frenetico è calore."),
        ("Perché il piatto resta freddo",
         "Vetro, ceramica e plastica non hanno molecole polari che rispondono così alle onde: le lasciano passare. Si scaldano solo per contatto con il cibo. Il metallo invece riflette le onde e, se ha punte o bordi, accumula cariche che scoccano scintille."),
        ("Le zone fredde",
         "Le onde rimbalzano nel forno e creano punti dove si sommano e punti dove si annullano, distanti circa 6 cm. Per questo il piatto gira e per questo il centro di una lasagna resta a volte gelato mentre i bordi bollono: mescolare a metà cottura risolve più del tempo extra."),
       ]),

    # ------------------------------ SPAZIO ------------------------------
    mk("spazio", "v4-luna-stessa-faccia",
       "Perché vediamo sempre la stessa faccia della Luna?", ["stessa faccia", "Luna"],
       "Da millenni l'umanità osserva lo stesso volto lunare. Il lato nascosto è stato fotografato solo nel 1959. Eppure la Luna ruota.",
       "La Luna ruota su se stessa esattamente nel tempo in cui orbita intorno alla Terra: la rotazione sincrona, prodotta dalle forze di marea, ci mostra sempre lo stesso emisfero.",
       "",
       [
        ("Ruota, ma al ritmo giusto",
         "La Luna compie un giro su se stessa in 27,3 giorni, lo stesso tempo che impiega a orbitare intorno alla Terra. Il risultato è che mentre si sposta lungo l'orbita ruota quanto basta per mantenere lo stesso lato rivolto verso di noi. Se non ruotasse affatto, vedremmo tutta la sua superficie in un mese."),
        ("Il freno delle maree",
         "Non è un caso: la gravità terrestre deforma leggermente la Luna, creando un rigonfiamento. Miliardi di anni fa la Luna ruotava più in fretta, ma quel rigonfiamento agiva come un freno, finché la rotazione non si è agganciata all'orbita. Si chiama blocco mareale e succede a molte lune del Sistema Solare."),
        ("In realtà ne vediamo il 59%",
         "L'orbita lunare è leggermente ellittica e inclinata, così la Luna 'oscilla' un po' vista da Terra. Queste librazioni ci lasciano sbirciare oltre i bordi: nel corso del tempo vediamo circa il 59% della superficie, non solo il 50%."),
        ("Il lato nascosto non è oscuro",
         "Il lato che non vediamo riceve la stessa luce solare del nostro: durante la Luna nuova è completamente illuminato. È solo 'lontano', non 'buio'. La sonda sovietica Luna 3 lo fotografò per la prima volta nel 1959, rivelando una superficie quasi priva dei grandi mari scuri che vediamo da casa."),
       ]),
    mk("spazio", "v4-giorno-venere",
       "Su Venere un giorno dura più di un anno", ["Venere", "giorno"],
       "Il pianeta più simile alla Terra per dimensioni ha un calendario che sembra uno scherzo: gira su se stesso più lentamente di quanto giri intorno al Sole.",
       "Venere ruota in 243 giorni terrestri, al contrario degli altri pianeti, ma orbita intorno al Sole in 225: il suo giorno sidereo è più lungo del suo anno.",
       "",
       [
        ("Un pianeta al rallentatore",
         "Venere impiega 243 giorni terrestri per compiere una rotazione completa su se stesso, ma solo 225 per completare un'orbita intorno al Sole. È l'unico pianeta del Sistema Solare in cui il 'giorno', inteso come rotazione, supera l'anno."),
        ("E ruota al contrario",
         "Visto dall'alto del polo nord, quasi tutti i pianeti ruotano in senso antiorario. Venere lo fa in senso orario: su Venere il Sole sorge a ovest e tramonta a est. Forse un impatto gigantesco in passato, forse l'attrito con la sua densa atmosfera, hanno rallentato e ribaltato la sua rotazione."),
        ("Quanto dura un giorno solare",
         "Combinando rotazione retrograda e orbita, il tempo tra un'alba e la successiva su Venere è di circa 117 giorni terrestri. Un abitante immaginario vedrebbe meno di due albe in un anno venusiano."),
        ("Un'atmosfera che corre",
         "Mentre il suolo si muove lentissimo, l'atmosfera di anidride carbonica e nubi di acido solforico compie un giro del pianeta in appena quattro giorni, con venti a 360 km/h. Questa 'super-rotazione' resta uno dei grandi misteri della meteorologia planetaria."),
       ]),
    mk("spazio", "v4-fascia-asteroidi",
       "La fascia degli asteroidi non è un campo minato", ["asteroidi"],
       "Nei film le astronavi schivano rocce a raffica. Nella realtà una sonda attraversa la fascia degli asteroidi senza nemmeno accorgersene.",
       "Gli asteroidi tra Marte e Giove sono milioni, ma dispersi in un volume enorme: la distanza media tra uno e l'altro è di circa un milione di chilometri.",
       "",
       [
        ("Tanti, ma lontanissimi",
         "Nella fascia principale si stimano oltre un milione di asteroidi più grandi di un chilometro. Sembrano tanti, ma sono sparsi in un anello che ha una circonferenza di miliardi di chilometri e uno spessore di decine di milioni. In media, tra un asteroide e il vicino ci sono circa un milione di chilometri, quasi tre volte la distanza Terra-Luna."),
        ("Poca massa, in fondo",
         "Se mettessimo insieme tutti gli asteroidi della fascia, otterremmo un corpo con circa il 3% della massa della Luna. Metà di quella massa è concentrata in quattro oggetti: Cerere, Vesta, Pallade e Igea. Il resto sono briciole cosmiche."),
        ("Le sonde ci passano tranquille",
         "Pioneer 10 attraversò la fascia nel 1972 senza incidenti, e da allora oltre una dozzina di sonde hanno fatto lo stesso. La NASA calcola che la probabilità di colpire un asteroide per caso durante la traversata sia di circa una su un miliardo."),
        ("Un pianeta mancato",
         "Perché non si è formato un pianeta lì? La gravità di Giove, il gigante vicino, agitava le orbite di quei frammenti impedendo loro di aggregarsi con calma. La fascia è il cantiere di un pianeta che non è mai stato completato."),
       ]),

    # ------------------------------ TECNOLOGIA ------------------------------
    mk("tecnologia", "v4-touchscreen",
       "Come fa il touchscreen a sentire il tuo dito?", ["touchscreen", "dito"],
       "Funziona con la punta delle dita ma non con i guanti né con una matita. Il segreto non è la pressione: è l'elettricità che hai nel corpo.",
       "Gli schermi capacitivi hanno una griglia di elettrodi trasparenti carica elettricamente; il dito, conduttore, ruba un po' di carica e il telefono calcola dove.",
       "",
       [
        ("Una griglia invisibile",
         "Sotto il vetro c'è uno strato di ossido di indio-stagno, un materiale trasparente ma conduttore, inciso in file e colonne finissime. Il telefono mantiene su questa griglia una piccola carica elettrica e la misura centinaia di volte al secondo."),
        ("Il dito è un conduttore",
         "Il corpo umano è pieno d'acqua e sali: conduce elettricità. Quando il dito si avvicina al vetro, attira una parte della carica della griglia, cambiando la capacità elettrica in quel punto. Il processore confronta righe e colonne e trova le coordinate esatte."),
        ("Perché i guanti non funzionano",
         "Lana e pelle sono isolanti: il dito è troppo lontano dal vetro per disturbare il campo. I guanti 'touch' hanno fili conduttivi sulle punte che portano la carica del corpo fino allo schermo. Lo stesso principio spiega perché il display impazzisce se è bagnato: anche le gocce d'acqua conducono."),
        ("Prima c'erano gli schermi a pressione",
         "I vecchi navigatori e palmari usavano schermi resistivi: due strati flessibili che si toccavano sotto la pressione di uno stilo. Funzionavano con qualsiasi oggetto, ma erano opachi, imprecisi e non capivano due dita insieme. Con l'iPhone del 2007 il capacitivo divenne lo standard."),
       ]),
    mk("tecnologia", "v4-gps",
       "Il GPS funziona grazie alla relatività di Einstein", ["GPS", "Einstein"],
       "Ventiquattro satelliti, orologi atomici e una correzione che sembra fantascienza: senza tenere conto della curvatura del tempo, il navigatore sbaglierebbe di chilometri.",
       "Il GPS misura la posizione dal tempo che i segnali impiegano ad arrivare; gli orologi dei satelliti vanno più veloci di 38 microsecondi al giorno per la relatività e vengono corretti.",
       "",
       [
        ("Un cronometro nel cielo",
         "Ogni satellite GPS trasmette continuamente l'ora esatta e la propria posizione. Il ricevitore confronta l'ora di arrivo del segnale con quella di partenza: la differenza, moltiplicata per la velocità della luce, dà la distanza. Con almeno quattro satelliti il telefono calcola dove si trova."),
        ("Un errore di un miliardesimo",
         "La luce percorre 30 centimetri in un nanosecondo. Un orologio sbagliato di un solo microsecondo sposta la posizione di 300 metri. Per questo a bordo ci sono orologi atomici al cesio e al rubidio, stabili al miliardesimo di secondo al giorno."),
        ("Il tempo lassù scorre diverso",
         "Secondo la relatività ristretta, gli orologi in movimento veloce rallentano: i satelliti a 14.000 km/h perdono 7 microsecondi al giorno. Ma la relatività generale dice che lontano dalla massa terrestre il tempo accelera: a 20.000 km di quota guadagnano 45 microsecondi. Bilancio netto: +38 microsecondi al giorno."),
        ("Senza Einstein, 10 km al giorno",
         "Se quell'anticipo non venisse corretto, l'errore di posizione crescerebbe di circa 10 chilometri ogni giorno. Gli orologi dei satelliti vengono quindi regolati in fabbrica per battere leggermente più lenti. Ogni volta che il navigatore ti porta a destinazione, stai verificando la teoria del 1915."),
       ]),
    mk("tecnologia", "v4-cavi-sottomarini",
       "Internet viaggia in fondo al mare, non nello spazio", ["cavi", "mare"],
       "Pensiamo ai satelliti, ma il 99% del traffico tra continenti scorre in cavi spessi come un tubo da giardino posati sul fondo degli oceani.",
       "Oltre 1,4 milioni di km di cavi in fibra ottica collegano i continenti; ognuno trasporta centinaia di terabit al secondo con impulsi di luce.",
       "",
       [
        ("Un tubo da giardino con dentro la luce",
         "Un cavo sottomarino moderno ha il diametro di circa 2-3 cm in acque profonde. Dentro ci sono poche coppie di fibre ottiche, sottili come capelli, protette da acciaio, rame e polietilene. Ogni coppia trasporta decine di terabit al secondo: milioni di videochiamate contemporanee."),
        ("Posati da navi speciali",
         "Navi apposite srotolano il cavo per settimane, a una velocità di circa 200 km al giorno. Vicino alla costa il cavo viene interrato con un aratro sottomarino per proteggerlo da ancore e reti da pesca, la prima causa di guasti. Al largo giace semplicemente sul fondo, anche a 8.000 metri."),
        ("Ripetitori ogni 70 km",
         "La luce nella fibra si affievolisce. Ogni 60-100 km un ripetitore, alimentato da migliaia di volt inviati lungo il cavo stesso, la rigenera. Un cavo transatlantico ha centinaia di questi amplificatori, progettati per durare 25 anni senza manutenzione."),
        ("Perché non i satelliti",
         "Un segnale via satellite geostazionario fa un viaggio di 72.000 km e arriva con un ritardo di mezzo secondo. In fibra, Londra-New York richiede circa 60 millisecondi. I satelliti servono dove i cavi non arrivano, ma la spina dorsale di internet è, letteralmente, sott'acqua."),
       ]),

    # ------------------------------ NATURA ------------------------------
    mk("natura", "v4-foglie-autunno",
       "Perché le foglie cambiano colore in autunno?", ["foglie", "colore"],
       "Rosso, giallo, arancione: i colori d'autunno non vengono creati dall'albero. In parte erano lì da sempre, nascosti.",
       "Quando la clorofilla si degrada, emergono i pigmenti gialli già presenti; il rosso invece viene prodotto apposta con gli zuccheri intrappolati nella foglia.",
       "",
       [
        ("Il verde che copre tutto",
         "In estate la foglia è piena di clorofilla, il pigmento che cattura la luce per la fotosintesi. È così abbondante che maschera gli altri pigmenti. Ma la clorofilla è costosa da mantenere e si consuma in fretta: l'albero deve rinnovarla di continuo."),
        ("Il giallo era già lì",
         "Con giorni più corti e notti fredde, l'albero smette di produrre clorofilla e recupera l'azoto che contiene, portandolo nei rami per l'inverno. Sotto il verde che sbiadisce emergono i carotenoidi, gialli e arancioni: gli stessi pigmenti delle carote, presenti nella foglia da sempre."),
        ("Il rosso è una scelta",
         "Le tinte rosse e viola vengono dalle antocianine, che l'albero produce solo in autunno. Uno strato di cellule alla base del picciolo blocca il passaggio degli zuccheri, che restano intrappolati e vengono trasformati in pigmento. Forse serve da 'crema solare' per proteggere la foglia mentre l'albero recupera le ultime sostanze utili."),
        ("La ricetta del foliage perfetto",
         "Giornate soleggiate producono molto zucchero, notti fresche ma senza gelo lo intrappolano: è la combinazione che accende gli aceri del New England e i faggi degli Appennini. Un autunno piovoso e tiepido dà colori spenti. Il meteo di settembre decide lo spettacolo di ottobre."),
       ]),
    mk("natura", "v4-fulmini",
       "Cosa succede davvero in un fulmine", ["fulmine"],
       "Dura meno di un secondo, scalda l'aria a cinque volte la temperatura del Sole e colpisce la Terra 100 volte al secondo. E parte quasi sempre dal basso.",
       "Un fulmine è una scarica che neutralizza cariche accumulate nella nube; il canale visibile risale dal suolo alla nube e scalda l'aria fino a 30.000 °C, generando il tuono.",
       "",
       [
        ("Una batteria nelle nubi",
         "In un cumulonembo, correnti violente fanno scontrare cristalli di ghiaccio e chicchi di grandine. Negli urti si scambiano elettroni: i cristalli leggeri, positivi, salgono; la grandine, negativa, scende. La base della nube diventa un enorme polo negativo, e il suolo sotto, per induzione, positivo."),
        ("Il canale invisibile",
         "Quando la tensione supera la resistenza dell'aria, dalla nube scende un 'leader' a scalini, un canale ionizzato quasi invisibile che avanza a zig-zag di 50 metri alla volta. Dal suolo, da alberi e antenne, salgono a incontrarlo scariche positive. Quando si toccano, il circuito si chiude."),
        ("Il lampo che vedi sale",
         "Il bagliore accecante è la scarica di ritorno: una corrente di 30.000 ampere che risale dal suolo alla nube lungo il canale, a un terzo della velocità della luce. Scalda l'aria a 30.000 °C in un istante; l'aria esplode, e quell'onda d'urto è il tuono. Ogni 3 secondi tra lampo e tuono corrispondono a circa 1 km."),
        ("Non colpisce mai due volte? Falso",
         "L'Empire State Building viene colpito circa 25 volte all'anno. Il fulmine cerca il percorso più breve: punti alti e isolati sono i preferiti. Per questo in un temporale all'aperto non ci si ripara sotto un albero solitario: meglio accovacciarsi in una zona bassa, lontano da oggetti alti."),
       ]),
    mk("natura", "v4-funghi-rete",
       "Sotto i tuoi piedi c'è un internet di funghi", ["funghi", "rete"],
       "Nel bosco gli alberi non sono individui isolati: scambiano zuccheri, acqua e segnali di allarme attraverso una rete sotterranea di filamenti fungini.",
       "Le micorrize collegano le radici degli alberi con filamenti di funghi; attraverso questa rete passano nutrienti e segnali chimici che aiutano l'intera foresta.",
       "",
       [
        ("Un patto vecchio 400 milioni di anni",
         "Circa il 90% delle piante terrestri vive in simbiosi con i funghi. Le ife, filamenti sottilissimi, avvolgono o penetrano le radici: il fungo cede acqua, fosforo e azoto che estrae dal suolo meglio delle radici; la pianta ricambia con zuccheri prodotti dalla fotosintesi, fino al 30% del suo raccolto."),
        ("Alberi collegati tra loro",
         "Lo stesso fungo può connettere decine di alberi, anche di specie diverse. Esperimenti con carbonio marcato hanno mostrato che gli zuccheri passano da un albero all'altro attraverso la rete. Le grandi 'piante madri' di una foresta risultano collegate a centinaia di plantule più giovani."),
        ("Segnali di allarme",
         "Quando una pianta viene attaccata da afidi, le vicine collegate dalla rete fungina attivano le loro difese chimiche prima di essere toccate. Il meccanismo esatto è ancora studiato, ma la rete sembra trasportare anche informazione, non solo cibo."),
        ("Cosa significa per noi",
         "Un albero da solo in un campo arato vive peggio di uno nel bosco. Tagliare gli alberi più vecchi, o rivoltare il suolo, distrugge una rete costruita in decenni. Le foreste che rigenerano meglio sono quelle dove il 'wood wide web' è rimasto intatto."),
       ]),
]

LESSONS = [
    # ------------------------------ SCIENZA ------------------------------
    L("scienza", "v4-lez-densita",
      "Densità: perché le cose galleggiano o affondano", ["densità"],
      "Una nave di acciaio galleggia, un chiodo affonda. Non è il peso a decidere: è un rapporto che puoi imparare in quattro passi.",
      "Capire il concetto di densità e usarlo per prevedere se un oggetto galleggia in un liquido.",
      "La densità è massa diviso volume. Un oggetto galleggia se la sua densità media è minore di quella del liquido: per questo una nave cava galleggia e un chiodo pieno affonda.",
      [
       ("Passo 1 — Massa e volume non bastano da soli",
        "Prendi un chilo di piume e un chilo di ferro: stessa massa, volume diversissimo. La densità mette insieme le due cose: quanta massa sta in un certo spazio. Si calcola dividendo la massa per il volume. L'acqua ha densità 1 grammo per centimetro cubo: è il riferimento perfetto."),
       ("Passo 2 — La regola del galleggiamento",
        "Un oggetto immerso spinge via un volume d'acqua pari al suo. Se quell'acqua pesa più dell'oggetto, l'oggetto galleggia; se pesa meno, affonda. Tradotto: galleggia ciò che ha densità minore del liquido. Il legno di pino (0,5) galleggia, il ferro (7,8) affonda, l'olio (0,9) resta sopra l'acqua."),
       ("Passo 3 — La densità media conta, non il materiale",
        "Una nave è fatta di acciaio ma è quasi tutta aria: la sua densità media, acciaio più aria, è minore di quella dell'acqua. Se si riempie d'acqua, la densità media sale e affonda. Lo stesso vale per un sottomarino, che regola i serbatoi di zavorra per salire o scendere."),
       ("Passo 4 — Prova a casa",
        "Metti un uovo in un bicchiere d'acqua: affonda. Aggiungi tre cucchiai di sale e mescola: l'uovo risale, perché l'acqua salata è più densa. È lo stesso motivo per cui nel Mar Morto si galleggia senza sforzo. Hai appena usato la densità per fare una previsione e verificarla."),
      ]),
    L("scienza", "v4-lez-atomo",
      "Com'è fatto un atomo, spiegato senza formule", ["atomo"],
      "Tutto ciò che tocchi è fatto di atomi, eppure sono quasi interamente vuoti. Ecco come immaginarli in modo corretto in quattro passi.",
      "Descrivere la struttura dell'atomo (nucleo, protoni, neutroni, elettroni) e capire cosa distingue un elemento dall'altro.",
      "L'atomo ha un nucleo minuscolo e densissimo di protoni e neutroni, circondato da elettroni. Il numero di protoni decide l'elemento; gli elettroni decidono come reagisce.",
      [
       ("Passo 1 — Un nucleo in uno stadio vuoto",
        "Immagina uno stadio di calcio: il nucleo è una biglia al centro del campo, gli elettroni sono moscerini che volano sugli spalti. In mezzo, nulla. L'atomo è 99,99% spazio vuoto: se togliessimo il vuoto da tutti gli atomi dell'umanità, la materia rimasta starebbe in una zolletta di zucchero."),
       ("Passo 2 — Il nucleo: protoni e neutroni",
        "Nel nucleo stanno i protoni, con carica positiva, e i neutroni, senza carica. Il numero di protoni è la carta d'identità dell'elemento: 1 è idrogeno, 6 è carbonio, 8 è ossigeno, 79 è oro. Cambiare il numero di protoni significa cambiare elemento: è ciò che avviene nelle stelle e nei reattori."),
       ("Passo 3 — Gli elettroni: la parte sociale",
        "Gli elettroni, negativi, non girano su orbite come pianeti: occupano regioni di probabilità, come nuvole. Gli elettroni più esterni decidono con chi l'atomo si lega. Il sodio ne ha uno 'di troppo', il cloro uno 'in meno': insieme formano il sale da cucina."),
       ("Passo 4 — Isotopi, la variante",
        "Stessi protoni ma diverso numero di neutroni: sono gli isotopi. Il carbonio-12 è quello comune, il carbonio-14 è radioattivo e si dimezza ogni 5.730 anni: misurando quanto ne resta si datano reperti antichi. Stesso elemento, stessa chimica, orologio diverso."),
      ]),
    L("scienza", "v4-lez-leggere-etichetta",
      "Leggere un'etichetta chimica: cosa c'è davvero nel flacone", ["etichetta"],
      "Detersivi, cosmetici, alimenti: dietro nomi lunghi si nascondono pochi concetti. Impara a decodificarli in quattro passi.",
      "Interpretare gli ingredienti e i simboli di pericolo su un'etichetta di un prodotto di uso quotidiano.",
      "Gli ingredienti sono elencati in ordine decrescente di quantità, i nomi INCI sono standard internazionali, i pittogrammi rossi indicano pericoli specifici.",
      [
       ("Passo 1 — L'ordine racconta la ricetta",
        "Per legge gli ingredienti compaiono in ordine di quantità decrescente. Se 'Aqua' è al primo posto, il prodotto è soprattutto acqua. Se lo zucchero compare tra i primi tre di un alimento, è un dolce anche se non sembra. Gli ultimi ingredienti, sotto l'1%, possono essere in qualsiasi ordine."),
       ("Passo 2 — I nomi lunghi non sono un allarme",
        "Sodium chloride è il sale. Tocopherol è la vitamina E. Sodium laureth sulfate è un tensioattivo che fa la schiuma. I nomi INCI sono uguali in tutto il mondo per permettere confronti. 'Naturale' non significa 'innocuo': il veleno del ricino è naturalissimo."),
       ("Passo 3 — I pittogrammi rossi",
        "I rombi con bordo rosso sono standardizzati: il punto esclamativo significa irritante, la fiamma infiammabile, il corrosivo mostra una mano rovinata, l'albero morto indica pericolo per l'ambiente. Sotto trovi le frasi H (pericoli) e P (precauzioni): 'P102: tenere fuori dalla portata dei bambini'."),
       ("Passo 4 — Prova con tre prodotti",
        "Prendi uno shampoo, un detersivo e un biscotto. Per ciascuno trova: il primo ingrediente, un nome che non conosci da cercare, e l'eventuale pittogramma. Bastano cinque minuti per passare da 'leggo nomi strani' a 'so cosa sto usando'."),
      ]),

    # ------------------------------ SPAZIO ------------------------------
    L("spazio", "v4-lez-fasi-luna",
      "Le fasi della Luna: capirle una volta per tutte", ["fasi", "Luna"],
      "Non è l'ombra della Terra. È solo una questione di angoli tra tre corpi. In quattro passi imparerai a leggere la Luna come un orologio.",
      "Spiegare perché la Luna cambia forma e riconoscere se sta crescendo o calando.",
      "Le fasi dipendono da quanta parte illuminata della Luna vediamo dalla Terra. Il ciclo dura 29,5 giorni. Gobba a ovest (destra) cresce, gobba a est (sinistra) cala.",
      [
       ("Passo 1 — Metà Luna è sempre illuminata",
        "Il Sole illumina sempre metà della Luna, come fa con la Terra. Quello che cambia è quanta di quella metà illuminata guarda verso di noi. Quando la Luna è tra noi e il Sole, vediamo il lato buio: Luna nuova. Quando la Terra è in mezzo, vediamo tutto il lato illuminato: Luna piena."),
       ("Passo 2 — Il ciclo di 29,5 giorni",
        "Dalla Luna nuova: primo quarto dopo circa 7 giorni (metà destra illuminata), Luna piena dopo 15, ultimo quarto dopo 22, e di nuovo Luna nuova dopo 29,5. Il mese del calendario deriva proprio da questo ciclo."),
       ("Passo 3 — Cresce o cala? La regola della D e della C",
        "Nell'emisfero nord, se la parte illuminata è a destra e forma una D, la Luna è crescente. Se è a sinistra e forma una C, è calante. Un trucco italiano: 'gobba a ponente, Luna crescente; gobba a levante, Luna calante'. Nell'emisfero sud le regole si invertono."),
       ("Passo 4 — Non confonderla con l'eclissi",
        "Le fasi non hanno nulla a che fare con l'ombra della Terra. Quella entra in gioco solo durante un'eclissi lunare, quando la Luna piena attraversa l'ombra terrestre e diventa rossastra. Se la Luna fosse oscurata dalla Terra ogni mese, non avremmo mai la Luna piena luminosa."),
      ]),
    L("spazio", "v4-lez-anno-luce",
      "Anno luce: come misurare distanze che non si possono percorrere", ["anno luce"],
      "Non è un tempo, è una distanza. E capirlo cambia il modo in cui guardi il cielo: stai vedendo il passato.",
      "Capire cos'è un anno luce, quanto vale e perché guardare lontano significa guardare indietro nel tempo.",
      "Un anno luce è la distanza percorsa dalla luce in un anno: circa 9.460 miliardi di km. Vedere una stella a 100 anni luce significa vederla com'era 100 anni fa.",
      [
       ("Passo 1 — Partiamo dalla velocità della luce",
        "La luce viaggia a circa 300.000 km al secondo: in un secondo fa sette volte il giro della Terra. Dalla Luna arriva in 1,3 secondi, dal Sole in 8 minuti e 20 secondi. Già qui i chilometri diventano scomodi: 150 milioni per il Sole."),
       ("Passo 2 — Un anno di viaggio",
        "Moltiplica 300.000 km per i secondi in un anno (circa 31,5 milioni): ottieni circa 9.460 miliardi di km. Quello è un anno luce. Proxima Centauri, la stella più vicina dopo il Sole, sta a 4,2 anni luce: con la sonda più veloce mai costruita servirebbero migliaia di anni."),
       ("Passo 3 — Guardare è guardare nel passato",
        "Se una stella è a 100 anni luce, la luce che ti colpisce l'occhio stanotte è partita 100 anni fa. La stella potrebbe essere già esplosa e non lo sapremmo per un secolo. La galassia di Andromeda è a 2,5 milioni di anni luce: la vedi com'era quando i primi umani camminavano in Africa."),
       ("Passo 4 — Le scale del cosmo",
        "La Via Lattea misura circa 100.000 anni luce. L'universo osservabile ha un raggio di circa 46 miliardi di anni luce. La prossima volta che guardi il cielo, prova a dire per una stella: 'la sto vedendo com'era nel...'. È il modo più semplice di sentire la profondità del cosmo."),
      ]),
    L("spazio", "v4-lez-riconoscere-pianeti",
      "Come riconoscere un pianeta a occhio nudo", ["pianeta"],
      "Quel puntino brillante non è una stella. Con tre indizi e nessun telescopio puoi distinguere Venere, Giove, Marte e Saturno.",
      "Distinguere i pianeti visibili dalle stelle e sapere dove cercarli nel cielo.",
      "I pianeti non scintillano, stanno vicino alla linea del Sole (eclittica) e si spostano nelle settimane. Venere è il più brillante, Marte è rossastro, Giove è bianco e forte, Saturno giallo pallido.",
      [
       ("Passo 1 — Non scintillano",
        "Le stelle sono puntini così piccoli che la turbolenza dell'aria li fa tremolare. I pianeti sono dischi minuscoli ma estesi: la loro luce si media e resta ferma. Se un astro brilla con luce stabile, quasi 'solida', è probabilmente un pianeta."),
       ("Passo 2 — Stanno sulla strada del Sole",
        "I pianeti orbitano quasi sullo stesso piano della Terra, quindi in cielo appaiono lungo la fascia percorsa da Sole e Luna, l'eclittica. Non cercarli vicino alla Stella Polare: guarda dove passa il Sole di giorno, verso sud in Italia."),
       ("Passo 3 — I colori li tradiscono",
        "Venere è l'oggetto più brillante dopo la Luna, visibile solo poco dopo il tramonto o prima dell'alba. Giove è bianco e molto luminoso, anche a mezzanotte. Marte ha un chiaro tono rosso-arancio. Saturno è giallastro e più debole. Mercurio è raro, bassissimo sull'orizzonte al crepuscolo."),
       ("Passo 4 — Verifica nel tempo",
        "'Pianeta' in greco significa 'errante'. Segna la posizione del tuo candidato rispetto alle stelle vicine e ricontrolla dopo una o due settimane: se si è spostato, è un pianeta. Un'app del cielo conferma la scoperta, ma il metodo funziona da 3.000 anni senza."),
      ]),

    # ------------------------------ TECNOLOGIA ------------------------------
    L("tecnologia", "v4-lez-riconoscere-phishing",
      "Riconoscere un'email di phishing in 4 controlli", ["phishing"],
      "Le truffe via email non sono più piene di errori di ortografia. Ma lasciano sempre quattro indizi, se sai dove guardare.",
      "Individuare le email fraudolente controllando mittente, urgenza, link e richiesta.",
      "Controlla il vero indirizzo del mittente, diffida dell'urgenza, leggi il link prima di cliccare, e ricorda: nessuna azienda seria chiede password via email.",
      [
       ("Passo 1 — Guarda l'indirizzo, non il nome",
        "Il nome visualizzato può essere qualsiasi cosa: 'Poste Italiane' può arrivare da servizio@poste-verifica.xyz. Tocca o passa il mouse sul mittente per vedere l'indirizzo completo. Il dominio, ciò che sta dopo la @, deve essere esattamente quello ufficiale, senza trattini o parole in più."),
       ("Passo 2 — L'urgenza è un'arma",
        "'Il tuo account sarà bloccato entro 24 ore', 'pacco in attesa, paga 1,99 €'. Le truffe creano fretta per impedirti di riflettere. Le comunicazioni vere raramente minacciano. Se senti l'ansia salire, è un segnale: fermati proprio in quel momento."),
       ("Passo 3 — Leggi il link prima di cliccare",
        "Tieni premuto sul link (o passa il mouse) per vedere l'indirizzo reale. 'intesasanpaolo.com.verifica-login.net' porta a 'verifica-login.net', non alla banca: conta l'ultima parte prima della prima barra. In dubbio, non cliccare: apri il sito digitandolo tu nel browser."),
       ("Passo 4 — Nessuno chiede la password",
        "Banche, poste, corrieri e social non chiedono mai password, PIN o codici via email o SMS. Se un'email lo fa, è falsa al 100%. Segnala come spam, cancella e, se hai già inserito dati, cambia subito la password e avvisa la banca. Il tempo di reazione conta."),
      ]),
    L("tecnologia", "v4-lez-cloud",
      "Cosa significa davvero 'salvato nel cloud'", ["cloud"],
      "Le tue foto non stanno in una nuvola. Stanno in un capannone, su dischi rigidi, copiate più volte. Ecco come funziona in quattro passi.",
      "Capire dove finiscono fisicamente i dati nel cloud, come vengono protetti e cosa può andare storto.",
      "Il cloud è un insieme di data center: i tuoi file sono copiati su più dischi e più sedi, cifrati in transito. Il rischio principale non è la perdita ma l'accesso al tuo account.",
      [
       ("Passo 1 — Il computer di qualcun altro",
        "Quando salvi una foto nel cloud, viene inviata via internet a un data center: un edificio con migliaia di server, sistemi di raffreddamento e generatori di emergenza. Google, Apple, Amazon e Microsoft ne possiedono centinaia. 'Cloud' è solo un nome comodo per 'computer di qualcun altro'."),
       ("Passo 2 — Copie, copie, copie",
        "Il tuo file non esiste in un solo posto: viene replicato su più dischi e spesso in più data center a centinaia di km di distanza. Se un disco si rompe, e capita ogni giorno, il sistema ricostruisce la copia mancante in automatico. Per questo perdere dati nel cloud per un guasto è rarissimo."),
       ("Passo 3 — Cifratura: in viaggio e a riposo",
        "I dati viaggiano cifrati (il lucchetto HTTPS) e sono cifrati anche sui dischi. Ma nella maggior parte dei servizi il fornitore possiede la chiave, per poterti offrire ricerca e anteprime. Solo i servizi 'end-to-end' non possono leggere i tuoi file: più privacy, ma password persa uguale dati persi."),
       ("Passo 4 — Il vero rischio sei tu",
        "Il cloud non perde i file; le persone perdono gli account. Una password debole o riutilizzata è la porta d'ingresso più comune. Attiva la verifica in due passaggi, tieni una copia locale delle cose insostituibili e controlla ogni tanto quali app hanno accesso al tuo account."),
      ]),
    L("tecnologia", "v4-lez-batteria",
      "Far durare la batteria del telefono: cosa funziona davvero", ["batteria"],
      "Mezzi miti e vecchi consigli non valgono più per le batterie al litio. Quattro regole basate su come funzionano davvero.",
      "Capire come si degrada una batteria al litio e adottare le abitudini che ne allungano la vita.",
      "Le batterie al litio soffrono il caldo e gli estremi di carica. Tenerle tra il 20 e l'80%, evitare il calore e non temere le ricariche parziali allunga la vita di anni.",
      [
       ("Passo 1 — Dimentica l'effetto memoria",
        "Le vecchie batterie al nichel andavano scaricate del tutto. Quelle al litio no: scaricarle a zero le stressa. Una batteria al litio ha un numero limitato di cicli completi, circa 500-1000, ma una ricarica dal 50 al 100% conta solo mezzo ciclo. Ricariche brevi e frequenti vanno benissimo."),
       ("Passo 2 — Gli estremi fanno male",
        "Restare a lungo al 100% o vicino allo 0% accelera l'usura chimica. La zona comoda è tra il 20 e l'80%. Molti telefoni hanno una 'ricarica ottimizzata' che si ferma all'80% di notte e completa poco prima della sveglia: attivala."),
       ("Passo 3 — Il calore è il vero nemico",
        "Sopra i 35 °C la batteria si degrada molto più in fretta. Evita di caricare il telefono sotto il cuscino, in auto al sole o mentre giochi con la ricarica rapida. Se lo senti caldo mentre carica, togli la cover. Il freddo invece riduce l'autonomia temporaneamente ma non rovina la cella."),
       ("Passo 4 — Controlla lo stato",
        "Nelle impostazioni trovi la 'salute' della batteria: sotto l'80% della capacità originale è tempo di sostituirla, spesso per pochi euro. Ricorda: una batteria che dura poco in una giornata è un problema di autonomia (schermo, app); una che si degrada in un anno è un problema di abitudini."),
      ]),

    # ------------------------------ NATURA ------------------------------
    L("natura", "v4-lez-fotosintesi",
      "La fotosintesi in 4 passi: come una foglia fa il cibo dalla luce", ["fotosintesi"],
      "Ogni boccone che mangi e ogni respiro che fai dipendono da una reazione che avviene in silenzio dentro le foglie.",
      "Descrivere cosa entra e cosa esce dalla fotosintesi e perché è alla base di quasi tutta la vita.",
      "Con luce, acqua e anidride carbonica, la clorofilla produce zuccheri e libera ossigeno. È la reazione che alimenta quasi tutte le catene alimentari e l'atmosfera respirabile.",
      [
       ("Passo 1 — Gli ingredienti",
        "Servono tre cose: acqua, assorbita dalle radici; anidride carbonica, che entra dalle foglie attraverso pori microscopici chiamati stomi; e luce, catturata dalla clorofilla, il pigmento verde. Tutto avviene nei cloroplasti, piccole fabbriche dentro le cellule della foglia."),
       ("Passo 2 — Spaccare l'acqua",
        "La luce fornisce l'energia per rompere le molecole d'acqua. Dall'acqua vengono presi elettroni e idrogeno; l'ossigeno che rimane viene rilasciato nell'aria. Sì: l'ossigeno che respiri proviene dall'acqua, non dall'anidride carbonica."),
       ("Passo 3 — Costruire lo zucchero",
        "Con l'energia catturata, la pianta lega l'anidride carbonica dell'aria in molecole di zucchero (glucosio). Quello zucchero è cibo, materiale da costruzione per cellulosa e legno, e riserva per l'inverno sotto forma di amido. Un albero è aria e acqua solidificate con la luce."),
       ("Passo 4 — Perché ti riguarda",
        "Ogni catena alimentare inizia qui: l'erba, la mucca, la bistecca. Il petrolio e il carbone sono fotosintesi di milioni di anni fa. E l'atmosfera al 21% di ossigeno esiste perché alghe e piante la producono da 2,5 miliardi di anni. Ogni respiro è un prestito dalle foglie."),
      ]),
    L("natura", "v4-lez-orientarsi-natura",
      "Orientarsi senza bussola: 4 indizi che la natura ti dà", ["orientarsi"],
      "Il telefono è scarico e non conosci la zona. Sole, ombre, muschio e stelle possono dirti dove sei rivolto, se sai leggerli.",
      "Usare Sole, ombre e riferimenti naturali per trovare i punti cardinali senza strumenti.",
      "A mezzogiorno il Sole è a sud (in Italia). Il metodo del bastone e dell'ombra dà una linea est-ovest. Il muschio è un indizio debole; le stelle sono il metodo notturno più affidabile.",
      [
       ("Passo 1 — Il Sole a mezzogiorno",
        "Nell'emisfero nord il Sole a mezzogiorno solare (circa le 13 con l'ora legale) è verso sud. Sorge a est e tramonta a ovest solo agli equinozi; in estate sorge a nord-est, in inverno a sud-est. È un riferimento grossolano ma sempre disponibile con il cielo sereno."),
       ("Passo 2 — Il bastone e l'ombra",
        "Pianta un bastone dritto nel terreno e segna la punta dell'ombra con un sasso. Aspetta 15-20 minuti e segna di nuovo. La linea tra i due sassi va da ovest (primo segno) a est (secondo). Mettiti con il primo sasso a sinistra e il secondo a destra: stai guardando a nord."),
       ("Passo 3 — Il muschio, con cautela",
        "Il muschio cresce dove c'è più umidità e ombra, spesso il lato nord di tronchi e rocce. Ma in un bosco fitto o vicino a un torrente cresce ovunque. Usalo solo come conferma di altri indizi, mai da solo. Lo stesso vale per i formicai, che spesso hanno il lato più ripido a nord."),
       ("Passo 4 — Di notte, la Polare",
        "Trova il Grande Carro, prendi le due stelle del bordo esterno del 'pentolone' e prolunga la loro distanza cinque volte: arrivi alla Stella Polare, che indica il nord con un errore inferiore a un grado. Combinando Sole di giorno e Polare di notte hai una bussola sempre con te."),
      ]),
    L("natura", "v4-lez-leggere-fiume",
      "Leggere un fiume: capire cosa succede sott'acqua guardando la superficie", ["fiume"],
      "Increspature, pieghe e schiuma raccontano cosa c'è sul fondo. Quattro passi per capire un corso d'acqua prima di attraversarlo o pescarci.",
      "Interpretare le forme sulla superficie di un fiume per capire correnti, ostacoli e profondità.",
      "Acqua liscia e scura è profonda; increspature indicano fondo basso; una V rivolta verso valle segnala un ostacolo sommerso; la schiuma bianca è aria e corrente forte.",
      [
       ("Passo 1 — Liscio e scuro significa profondo",
        "Dove l'acqua scorre liscia, quasi oleosa, e appare scura, il fondo è lontano e la corrente rallenta: sono le 'pozze', dove i pesci riposano. Sembra tranquilla ma è il punto peggiore per attraversare a piedi: puoi non toccare il fondo."),
       ("Passo 2 — Le increspature dicono basso",
        "Superficie ondulata e rumorosa, con tante piccole onde: il fondo è vicino e sassoso. È la 'rapida' o il 'raschio'. Ricco di ossigeno, è dove gli insetti acquatici abbondano. Se devi attraversare, è qui, camminando di traverso alla corrente e mai in linea con essa."),
       ("Passo 3 — La V rovesciata",
        "Una V con la punta rivolta a valle indica un sasso o un tronco appena sotto la superficie: l'acqua si divide su di esso. Una V con la punta a monte indica invece un passaggio libero tra due ostacoli. I canoisti seguono le V verso monte e schivano quelle verso valle."),
       ("Passo 4 — La schiuma e i mulinelli",
        "Schiuma bianca significa aria mescolata all'acqua: corrente forte e turbolenta, poco galleggiamento. Dietro un grande masso si forma un 'rigiro' dove l'acqua torna indietro: un rifugio per pesci e canoe, ma anche una trappola sotto le cascate. Dopo la pioggia, il fiume cambia lettura: rileggilo ogni volta."),
      ]),
]
