"""PAUSE — storie aggiuntive: natura (+4), storia (+4), corpo-umano (+4)."""
from story_builder import mk

STORIES = [
    # ----------------------------- NATURA -----------------------------
    mk("natura", "nat-why-leaves-fall",
       "Perché le foglie cambiano colore e cadono in autunno?",
       ["foglie", "autunno"],
       "Un giorno gli alberi sono verdi, poi si accendono di rosso e oro, infine si spogliano. Non è morte: è una strategia di sopravvivenza raffinatissima.",
       "In autunno gli alberi ritirano la clorofilla per risparmiare energia: emergono i colori nascosti e le foglie cadono per superare l'inverno.",
       "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop",
       [
        ("Il verde è clorofilla",
         "Le foglie sono verdi grazie alla clorofilla, il pigmento che cattura la luce del Sole per produrre energia attraverso la fotosintesi. Durante la bella stagione la clorofilla è così abbondante da coprire tutti gli altri colori presenti nella foglia. Il verde che vediamo è, in fondo, il colore della fabbrica di energia dell'albero al lavoro."),
        ("I colori erano già lì",
         "Rossi, arancioni e gialli dell'autunno non compaiono dal nulla: molti di questi pigmenti erano presenti tutto l'anno, nascosti dal verde dominante. Quando la clorofilla si ritira, emergono. È come spegnere una luce verde molto forte e scoprire che sotto c'erano altri colori che aspettavano solo di essere visti."),
        ("Perché l'albero si prepara",
         "Con l'accorciarsi delle giornate e il freddo in arrivo, mantenere le foglie diventa poco conveniente: fotosinterizzano poco e disperdono acqua. L'albero recupera allora le sostanze preziose dalle foglie e le immagazzina nei rami e nel tronco. È una ritirata strategica per non sprecare risorse nella stagione difficile."),
        ("La caduta programmata",
         "Alla base di ogni foglia si forma uno strato di cellule speciali che, poco a poco, la stacca dal ramo. La foglia cade dolcemente, quasi come per decisione dell'albero. Perdere le foglie evita che il gelo e la neve danneggino l'albero e riduce la perdita d'acqua durante l'inverno, quando le radici assorbono a fatica."),
        ("Chi resta verde",
         "Non tutti gli alberi si spogliano: le conifere, come pini e abeti, mantengono aghi resistenti al freddo tutto l'anno. I loro aghi, sottili e cerati, perdono poca acqua e sopportano il gelo. Sono strategie diverse per lo stesso problema: come sopravvivere all'inverno senza morire di sete o di freddo."),
        ("Cosa portarti a casa",
         "Lo spettacolo dell'autunno non è un declino, ma un'intelligente manovra di risparmio energetico. Ogni foglia rossa che cade è il segno di un albero che si prepara, con precisione, a tornare verde in primavera. La natura non spreca: persino lasciar andare fa parte di un piano."),
       ]),

    mk("natura", "nat-lightning",
       "Cos'è davvero un fulmine?",
       ["fulmine", "elettricità"],
       "Un lampo accecante, un boato che fa tremare. Il fulmine è una delle forze più spettacolari della natura, ed è pura elettricità liberata in un istante.",
       "Il fulmine è una scarica elettrica gigantesca tra nuvola e suolo: l'aria si separa in cariche opposte finché la corrente esplode per riequilibrarle.",
       "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200&q=80&auto=format&fit=crop",
       [
        ("Cariche in cielo",
         "Dentro un temporale, correnti d'aria violente fanno urtare tra loro cristalli di ghiaccio e goccioline. Questi scontri separano le cariche elettriche: quelle positive tendono a salire in alto, quelle negative ad accumularsi in basso. La nuvola diventa così una gigantesca batteria carica, con enormi tensioni pronte a scaricarsi."),
        ("La scintilla gigante",
         "Quando la differenza di carica diventa troppo grande, l'aria non riesce più a fare da isolante. Si apre allora un canale conduttore e la corrente esplode: è il fulmine, una scintilla lunga chilometri. In una frazione di secondo passa una quantità di energia enorme, riequilibrando bruscamente le cariche separate."),
        ("Più caldo del Sole",
         "Il canale del fulmine si scalda fino a circa 30.000 gradi, cinque volte la superficie del Sole. Questo calore improvviso fa espandere l'aria in modo esplosivo, generando un'onda d'urto: è il tuono. Vediamo il lampo subito perché la luce è velocissima, mentre il suono arriva dopo, viaggiando molto più lentamente."),
        ("Contare i secondi",
         "Puoi stimare la distanza di un temporale contando i secondi tra lampo e tuono: ogni tre secondi corrisponde a circa un chilometro. Se lampo e tuono sono quasi simultanei, il fulmine è vicinissimo e pericoloso. È un piccolo calcolo che sfrutta proprio la grande differenza di velocità tra luce e suono."),
        ("Fulmini e vita",
         "I fulmini non sono solo distruttivi: contribuiscono a trasformare l'azoto dell'aria in forme utilizzabili dalle piante, fertilizzando naturalmente il suolo. Alcune teorie suggeriscono che scariche elettriche simili possano aver avuto un ruolo nelle reazioni chimiche all'origine della vita sulla Terra primordiale. Bellezza e utilità nello stesso lampo."),
        ("Cosa portarti a casa",
         "Il fulmine è elettricità che conosciamo bene nelle prese di casa, portata a una scala colossale dalla natura. Dietro quel lampo che ci fa sobbalzare c'è la stessa fisica di una scintilla, moltiplicata milioni di volte. Rispettarlo significa capire quanta energia il cielo può scatenare in un istante."),
       ]),

    mk("natura", "nat-mushrooms-network",
       "Il 'social network' segreto delle piante",
       ["funghi", "piante"],
       "Sotto ai nostri piedi, nei boschi, esiste una rete nascosta che collega gli alberi e permette loro di scambiarsi cibo e messaggi. Non è fantascienza.",
       "Reti di funghi collegano le radici degli alberi permettendo scambi di nutrienti e segnali: un vero 'internet' sotterraneo che tiene insieme la foresta.",
       "https://images.unsplash.com/photo-1520681279154-51b3fb4ea0f8?w=1200&q=80&auto=format&fit=crop",
       [
        ("Un'alleanza antichissima",
         "Gran parte delle piante vive in simbiosi con funghi microscopici che avvolgono le loro radici. Le piante forniscono ai funghi zuccheri prodotti con la fotosintesi; i funghi, con i loro sottili filamenti, aiutano le radici ad assorbire acqua e minerali. È una collaborazione che dura da centinaia di milioni di anni, alla base delle foreste."),
        ("La rete che collega gli alberi",
         "Questi filamenti fungini, chiamati micelio, si estendono nel suolo collegando le radici di alberi diversi, anche di specie diverse. Si forma così una rete sotterranea vastissima, soprannominata dagli scienziati la \"wood wide web\": una sorta di internet naturale che intreccia un'intera foresta sotto la superficie."),
        ("Scambi di cibo",
         "Attraverso questa rete gli alberi possono trasferirsi nutrienti. Un grande albero al sole può inviare zuccheri a un giovane albero cresciuto all'ombra, aiutandolo a sopravvivere. Alberi morenti a volte \"donano\" le loro risorse ai vicini prima di spegnersi. La foresta si comporta, in parte, come una comunità che si sostiene."),
        ("Messaggi di allarme",
         "La rete trasporta anche segnali. Quando una pianta è attaccata da insetti, può inviare avvertimenti chimici ai vicini attraverso i funghi. Questi, allertati, iniziano a produrre difese prima ancora di essere colpiti. È una forma di comunicazione che ci fa ripensare a cosa significhi \"intelligenza\" nel mondo vegetale."),
        ("Non tutto è armonia",
         "La foresta non è però solo cooperazione idilliaca. Alcune piante sfruttano la rete per rubare risorse senza dare nulla in cambio; alcuni funghi manipolano gli scambi a proprio vantaggio. È un ecosistema complesso, fatto di alleanze ma anche di competizione e inganni, proprio come le reti sociali degli esseri umani."),
        ("Cosa portarti a casa",
         "Camminando in un bosco, cammini sopra una rete viva e brulicante che collega ogni albero. Le piante non sono individui isolati e silenziosi, ma parte di una comunità connessa. Questa scoperta cambia il modo di guardare una foresta: non un insieme di alberi, ma un unico organismo intrecciato."),
       ]),

    mk("natura", "nat-tides",
       "Perché il mare sale e scende? Il mistero delle maree",
       ["maree", "Luna"],
       "Due volte al giorno, in molte coste, il mare avanza e si ritira di metri. Un respiro lento del pianeta guidato da qualcosa di lontanissimo: la Luna.",
       "Le maree nascono dalla gravità della Luna (e in parte del Sole) che attira l'acqua degli oceani: la rotazione terrestre le fa salire e scendere ritmicamente.",
       "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80&auto=format&fit=crop",
       [
        ("La Luna tira l'acqua",
         "La Luna esercita una forza di gravità su tutta la Terra, ma l'acqua degli oceani, essendo libera di muoversi, risponde più della terraferma. L'attrazione lunare crea un rigonfiamento d'acqua sul lato del pianeta rivolto verso la Luna. Lì il mare si alza: è l'alta marea. È una carezza gravitazionale a 380.000 chilometri di distanza."),
        ("Due gobbe, non una",
         "Curiosamente, c'è un secondo rigonfiamento anche sul lato opposto della Terra, lontano dalla Luna. Dipende dal fatto che la parte solida del pianeta, più vicina, viene \"tirata\" via dall'acqua sul lato lontano. Il risultato sono due gobbe d'acqua opposte, che spiegano perché in molte coste ci sono due alte maree al giorno."),
        ("Il ruolo della rotazione",
         "Mentre la Terra ruota su sé stessa in 24 ore, ogni costa passa alternativamente sotto i rigonfiamenti e nelle zone \"vuote\". Ecco perché il mare sale e scende ritmicamente durante la giornata. Non è l'acqua a viaggiare intorno al mondo: è la Terra che gira sotto le gobbe d'acqua tenute in posizione dalla Luna."),
        ("Anche il Sole partecipa",
         "Pure il Sole, molto più grande ma molto più lontano, contribuisce alle maree. Quando Sole, Terra e Luna sono allineati (luna nuova o piena), le loro attrazioni si sommano e le maree sono più forti: le \"sizigie\". Quando formano un angolo retto, in parte si annullano, e le maree sono più deboli."),
        ("Coste diverse, maree diverse",
         "L'ampiezza delle maree cambia moltissimo a seconda della forma delle coste e dei fondali. In alcune baie l'acqua può salire e scendere di oltre dieci metri, incanalata e amplificata; in mari chiusi come il Mediterraneo le maree sono minime. La stessa forza cosmica produce effetti diversissimi da luogo a luogo."),
        ("Cosa portarti a casa",
         "Le maree sono il segno tangibile che siamo legati ai corpi celesti: un satellite lontano muove ogni giorno oceani interi. Guardare il mare ritirarsi e tornare significa osservare, in diretta, la gravità che tiene insieme il sistema Terra-Luna. Un respiro del pianeta scandito dal cielo."),
       ]),

    # ----------------------------- STORIA -----------------------------
    mk("storia", "sto-great-wall",
       "La Grande Muraglia si vede davvero dallo spazio?",
       ["Muraglia", "spazio"],
       "È una delle 'verità' più ripetute al mondo: l'unica opera umana visibile dallo spazio. Peccato che sia, quasi del tutto, una leggenda.",
       "La Grande Muraglia non è visibile a occhio nudo dallo spazio: è lunghissima ma stretta. Il mito nacque prima ancora che l'uomo andasse in orbita.",
       "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1200&q=80&auto=format&fit=crop",
       [
        ("Un'opera colossale",
         "La Grande Muraglia cinese è tra le costruzioni più imponenti mai realizzate: un sistema di mura, torri e fortificazioni lungo migliaia di chilometri, costruito e ricostruito nel corso di molti secoli. Serviva a difendere gli imperi cinesi dalle incursioni dei popoli del nord. Milioni di persone lavorarono, e morirono, alla sua costruzione."),
        ("Il mito dello spazio",
         "Da tempo si ripete che sia l'unica opera umana visibile dallo spazio o addirittura dalla Luna. L'idea circolava già nell'Ottocento, molto prima che qualcuno andasse in orbita. Divenne una di quelle \"verità\" ripetute così spesso da non essere mai messe in discussione, entrando nei libri di scuola di mezzo mondo."),
        ("La smentita",
         "In realtà la Muraglia è lunghissima ma molto stretta, larga pochi metri, e del colore del terreno circostante. Dalla bassa orbita terrestre è pressoché invisibile a occhio nudo, e dalla Luna del tutto impossibile da scorgere. Diversi astronauti hanno confermato di non essere riusciti a distinguerla senza strumenti."),
        ("Cosa si vede davvero",
         "Dallo spazio, le cose umane più evidenti sono altre: le luci delle città di notte, grandi aeroporti, autostrade, campi coltivati geometrici, dighe. Sono opere più larghe o più luminose, che risaltano meglio della sottile Muraglia. La visibilità dipende dalla larghezza e dal contrasto, non dalla lunghezza o dalla fama."),
        ("Perché il mito resiste",
         "Le leggende affascinanti sono dure a morire, soprattutto quando lusingano l'orgoglio umano: l'idea di aver costruito qualcosa di visibile dal cosmo è irresistibile. Anche dopo le smentite degli astronauti, il mito continua a circolare. È un ottimo esempio di come una bella storia possa battere i fatti per generazioni."),
        ("Cosa portarti a casa",
         "La Grande Muraglia è straordinaria per davvero, ma non per il motivo che tutti ripetono. La sua vera grandezza è storica e umana, non la presunta visibilità dallo spazio. È un invito a diffidare delle \"verità\" che nessuno verifica mai: a volte le ripetiamo solo perché suonano bene."),
       ]),

    mk("storia", "sto-rosetta",
       "Come abbiamo imparato a leggere i geroglifici?",
       ["geroglifici", "Rosetta"],
       "Per oltre mille anni nessuno al mondo sapeva più leggere gli antichi geroglifici egizi. Poi una pietra ritrovata per caso riaprì la porta del passato.",
       "La Stele di Rosetta, con lo stesso testo in tre scritture, permise di decifrare i geroglifici: una svolta che restituì voce a tremila anni di storia egizia.",
       "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1200&q=80&auto=format&fit=crop",
       [
        ("Una lingua dimenticata",
         "Gli antichi egizi scrissero con i geroglifici per oltre tremila anni. Ma con il declino della loro civiltà, la conoscenza di quella scrittura andò perduta. Per più di mille anni nessuno seppe più leggerli: i monumenti coperti di simboli erano muti, e si pensava fossero semplici immagini simboliche, non una vera lingua."),
        ("Il ritrovamento",
         "Nel 1799, durante la campagna napoleonica in Egitto, alcuni soldati trovarono una grande pietra scura vicino alla città di Rosetta. Era incisa con lo stesso testo in tre scritture diverse: geroglifico, una scrittura egizia più corsiva e il greco antico. Fu subito chiaro che poteva essere la chiave per un enigma millenario."),
        ("La chiave del greco",
         "Gli studiosi sapevano leggere il greco antico. Se il testo greco diceva la stessa cosa degli altri due, si poteva usare come traduzione di partenza per decifrare gli altri. Era come avere lo stesso libro in una lingua nota e in due sconosciute: un ponte per attraversare l'abisso del tempo."),
        ("L'intuizione decisiva",
         "Dopo anni di lavoro, all'inizio dell'Ottocento, il francese Jean-François Champollion ebbe l'intuizione decisiva: i geroglifici non erano solo simboli, ma rappresentavano anche suoni, come un alfabeto. Confrontando i nomi dei faraoni scritti nelle diverse versioni, riuscì a ricostruire il valore fonetico dei segni e a leggere finalmente la scrittura."),
        ("Un intero mondo ritrovato",
         "La decifrazione aprì le porte a tremila anni di storia: leggi, poesie, lettere, iscrizioni religiose, contabilità quotidiana. Improvvisamente gli antichi egizi potevano di nuovo \"parlare\". Nacque l'egittologia moderna. Un'unica pietra trovata per caso restituì la voce a una delle più grandi civiltà della storia umana."),
        ("Cosa portarti a casa",
         "La storia della Stele di Rosetta mostra quanto sia fragile la memoria di una civiltà e quanto possa essere prezioso un singolo indizio. Un frammento di pietra, la conoscenza di una lingua e anni di paziente studio hanno riacceso una luce spenta da millenni. A volte il passato aspetta solo qualcuno capace di rileggerlo."),
       ]),

    mk("storia", "sto-printing-press",
       "La stampa: l'invenzione che cambiò il mondo",
       ["stampa", "libri"],
       "Prima di lei, ogni libro era copiato a mano, uno per uno, per mesi. Poi arrivò una macchina che moltiplicò le parole e, con esse, le idee.",
       "La stampa a caratteri mobili di Gutenberg rese i libri economici e diffusi: la conoscenza smise di essere privilegio di pochi e alimentò rivoluzioni culturali.",
       "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80&auto=format&fit=crop",
       [
        ("Il mondo prima della stampa",
         "Fino a metà Quattrocento, in Europa ogni libro veniva copiato a mano, di solito da monaci amanuensi. Un singolo volume poteva richiedere mesi di lavoro ed era costosissimo. I libri erano rari, riservati a chiese, sovrani e pochi ricchi. Saper leggere era inutile per la maggioranza, che ai libri non aveva alcun accesso."),
        ("L'idea di Gutenberg",
         "Intorno al 1450 il tedesco Johannes Gutenberg mise a punto la stampa a caratteri mobili: singole lettere di metallo che si potevano comporre, inchiostrare e premere sulla carta, poi ricomporre per pagine diverse. La tecnica non era del tutto nuova in Asia, ma Gutenberg la perfezionò creando un sistema efficiente e ripetibile su larga scala."),
        ("Libri per tutti",
         "L'effetto fu esplosivo. Ciò che prima richiedeva mesi ora si moltiplicava in centinaia di copie in poco tempo. I prezzi crollarono, i libri si diffusero. Nel giro di pochi decenni milioni di volumi circolavano in Europa. La conoscenza cominciò a sfuggire al controllo di poche élite e a raggiungere un pubblico sempre più ampio."),
        ("Idee incontrollabili",
         "Con i libri viaggiarono le idee, e nessuno poteva più fermarle facilmente. La Riforma protestante si diffuse grazie a testi stampati in grandi quantità. Scoperte scientifiche circolarono rapidamente tra studiosi lontani. La stampa creò per la prima volta qualcosa di simile a un'opinione pubblica, capace di mettere in discussione le autorità."),
        ("La spinta all'alfabetizzazione",
         "Con più libri disponibili e più economici, crebbe l'interesse a saper leggere. Nel corso dei secoli l'alfabetizzazione si allargò, alimentando istruzione, scienza e dibattito. La stampa non fu solo una tecnologia, ma un moltiplicatore di tutte le altre idee umane: un'invenzione che rese possibili tante altre rivoluzioni."),
        ("Cosa portarti a casa",
         "La stampa è forse l'esempio più chiaro di come una tecnologia possa cambiare la storia non per ciò che è, ma per ciò che permette: la libera circolazione delle idee. Ogni volta che leggi qualcosa che qualcuno non voleva farti sapere, raccogli l'eredità di quella macchina di cinque secoli fa."),
       ]),

    mk("storia", "sto-spices",
       "Perché le spezie hanno cambiato la storia del mondo?",
       ["spezie", "commercio"],
       "Pepe, cannella, noce moscata: oggi in ogni cucina, un tempo valevano quanto l'oro. Per queste polveri profumate si scoprirono continenti e si combatterono guerre.",
       "Le spezie erano rare, preziose e frutto di rotte lunghissime: la sete di controllarle spinse l'Europa alle grandi esplorazioni e al colonialismo.",
       "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80&auto=format&fit=crop",
       [
        ("Oro in polvere",
         "Nel Medioevo e nel Rinascimento le spezie erano beni di lusso straordinari. Il pepe si contava grano per grano, la noce moscata valeva cifre folli. Servivano a conservare e insaporire i cibi, ma erano anche simboli di ricchezza e status. Possedere spezie rare significava mostrare al mondo il proprio potere economico."),
        ("Rotte lunghissime",
         "Le spezie provenivano da terre lontanissime, soprattutto dall'Asia e dalle isole dell'attuale Indonesia. Prima di arrivare in Europa attraversavano mari, deserti e decine di intermediari, ognuno dei quali aumentava il prezzo. A ogni passaggio il costo lievitava, tanto che il prodotto finale poteva valere una fortuna."),
        ("La spinta a esplorare",
         "Gli europei sognavano di raggiungere direttamente le fonti delle spezie, saltando gli intermediari e i loro rincari. Fu proprio questa sete a spingere le grandi esplorazioni: Colombo cercava una rotta occidentale verso le Indie delle spezie e trovò per caso l'America. Vasco da Gama aprì la via per mare verso l'India."),
        ("Guerre e imperi",
         "Il controllo delle spezie divenne una posta enorme. Portogallo, Spagna, Olanda e Inghilterra si contesero rotte e isole con guerre spietate. Interi arcipelaghi furono conquistati e sfruttati per il monopolio di un solo prodotto. La ricerca del profitto sulle spezie fu uno dei motori del colonialismo europeo e delle sue violenze."),
        ("Da lusso a quotidiano",
         "Col tempo, l'aumento dei commerci e delle coltivazioni fece crollare i prezzi. Le spezie un tempo regali divennero comuni, disponibili sugli scaffali di ogni cucina. Ciò che aveva mosso imperi finì per costare pochi centesimi. Un destino curioso per polveri che avevano riscritto la mappa del mondo."),
        ("Cosa portarti a casa",
         "La prossima volta che macini del pepe, pensa che quel gesto banale è l'eco di secoli di viaggi, ricchezze e conflitti. Le spezie mostrano come il desiderio umano per qualcosa di raro possa cambiare la geografia, l'economia e la storia intera di interi continenti."),
       ]),

    # -------------------------- CORPO UMANO --------------------------
    mk("corpo-umano", "cor-why-hiccup",
       "Perché ci viene il singhiozzo (e a cosa serve)?",
       ["singhiozzo", "diaframma"],
       "Un 'hic' improvviso e incontrollabile, che a volte non se ne va per minuti. Il singhiozzo è tanto fastidioso quanto misterioso: forse è un ricordo evolutivo.",
       "Il singhiozzo è una contrazione involontaria del diaframma seguita dalla chiusura di scatto delle corde vocali: forse un residuo del nostro lontano passato acquatico.",
       "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=1200&q=80&auto=format&fit=crop",
       [
        ("Cosa succede quando singhiozzi",
         "Il singhiozzo nasce da una contrazione improvvisa e involontaria del diaframma, il grande muscolo che sta sotto i polmoni e ci fa respirare. Subito dopo, le corde vocali si chiudono di scatto bloccando l'aria: è quel blocco a produrre il tipico suono \"hic\". Tutto avviene in una frazione di secondo, senza che possiamo controllarlo."),
        ("Le cause comuni",
         "Spesso il singhiozzo compare dopo aver mangiato troppo in fretta, bevuto bevande gassate, riso o parlato molto: cose che fanno entrare aria in eccesso o irritano il diaframma. Anche emozioni forti e sbalzi di temperatura possono scatenarlo. Nella maggior parte dei casi è innocuo e passa da solo in pochi minuti."),
        ("Un riflesso senza scopo?",
         "La cosa strana è che il singhiozzo non sembra avere alcuna funzione utile per noi oggi. A differenza di tosse o starnuto, che proteggono le vie respiratorie, non serve a espellere nulla. Questa apparente inutilità ha portato gli scienziati a cercare la sua origine molto lontano, nel nostro passato evolutivo."),
        ("L'ipotesi del passato acquatico",
         "Una teoria affascinante lo collega agli antenati anfibi, come i girini, che alternano respirazione con polmoni e branchie. Il movimento del singhiozzo somiglia a quello con cui questi animali spingono l'acqua sulle branchie chiudendo le vie aeree. Il singhiozzo sarebbe un antichissimo riflesso rimasto \"acceso\" nel nostro corpo."),
        ("Rimedi veri e falsi",
         "Trattenere il respiro o bere acqua a piccoli sorsi funziona perché aumenta l'anidride carbonica o stimola nervi che \"resettano\" il riflesso. Molti altri rimedi popolari sono più che altro suggestione. Se però il singhiozzo dura giorni, non è normale e va indagato: raramente può segnalare un problema di salute."),
        ("Cosa portarti a casa",
         "Il singhiozzo è probabilmente un fossile vivente dentro di noi: un riflesso ereditato da antenati lontanissimi, oggi privo di scopo ma ancora ben presente. Quel fastidioso \"hic\" è, in fondo, un piccolo saluto del nostro passato evolutivo che riaffiora quando meno ce lo aspettiamo."),
       ]),

    mk("corpo-umano", "cor-gut-brain",
       "Il 'secondo cervello' nascosto nella pancia",
       ["intestino", "cervello"],
       "Le farfalle nello stomaco, le decisioni 'di pancia'. Non sono solo modi di dire: l'intestino ha una rete nervosa propria che dialoga di continuo con la testa.",
       "L'intestino possiede milioni di neuroni e comunica costantemente con il cervello: influenza umore, decisioni e benessere, anche grazie ai batteri che lo abitano.",
       "https://images.unsplash.com/photo-1533640924469-f04e06f8898d?w=1200&q=80&auto=format&fit=crop",
       [
        ("Neuroni nella pancia",
         "Lungo le pareti dell'intestino si trova una rete di centinaia di milioni di neuroni, tanti da essere soprannominata \"secondo cervello\". Questo sistema può regolare la digestione in modo autonomo, senza aspettare ordini dal cervello vero e proprio. È una centralina nervosa sorprendentemente sofisticata nascosta nel nostro addome."),
        ("Un dialogo continuo",
         "Intestino e cervello sono collegati da un grande nervo, il vago, e da segnali chimici che viaggiano nei due sensi. La pancia invia al cervello molte più informazioni di quante ne riceva. Non è un caso se lo stress ci chiude lo stomaco o se un'emozione forte ci provoca le famose \"farfalle\": è comunicazione reale, non metafora."),
        ("Il ruolo dei batteri",
         "Nell'intestino vivono trilioni di batteri, il microbiota, che non sono semplici passeggeri: producono sostanze che influenzano il nostro umore e persino il funzionamento del cervello. Una parte importante della serotonina, legata al benessere, viene prodotta proprio nell'intestino. Ciò che mangiamo nutre anche questi microscopici alleati."),
        ("Umore e pancia",
         "Studi crescenti collegano la salute intestinale allo stato d'animo. Squilibri nel microbiota sono stati associati a ansia e depressione in alcune ricerche. L'idea che \"siamo ciò che mangiamo\" assume così un significato più profondo: la dieta potrebbe influenzare non solo il corpo, ma anche il modo in cui ci sentiamo."),
        ("Decisioni di pancia",
         "Le sensazioni viscerali che proviamo davanti a una scelta hanno una base reale: il corpo invia al cervello segnali che partecipano alle nostre decisioni, spesso prima ancora del ragionamento cosciente. Le intuizioni \"di pancia\" non sono magia, ma il risultato di questo intenso scambio tra corpo e mente."),
        ("Cosa portarti a casa",
         "La vecchia separazione netta tra testa e pancia è sempre più sfumata: siamo un sistema unico, in cui l'intestino ha una voce importante. Prendersi cura di ciò che mangiamo significa prendersi cura anche del nostro cervello e del nostro umore. La saggezza popolare, per una volta, aveva intuito qualcosa di vero."),
       ]),

    mk("corpo-umano", "cor-why-fingerprints",
       "Perché abbiamo le impronte digitali (e sono tutte diverse)?",
       ["impronte", "unicità"],
       "Ognuno di noi porta sui polpastrelli un disegno unico, diverso persino tra gemelli identici. Non serve solo alla polizia: ha una funzione antichissima.",
       "Le impronte digitali si formano prima della nascita e sono uniche per ciascuno: probabilmente migliorano presa e tatto, più che 'firmare' la nostra identità.",
       "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=1200&q=80&auto=format&fit=crop",
       [
        ("Un disegno che nasce prima di noi",
         "Le impronte digitali si formano già nel grembo materno, intorno al terzo-quarto mese di gestazione. Dipendono da come la pelle cresce e si piega mentre il feto si sviluppa, influenzata da tanti minuscoli fattori casuali. Per questo il disegno finale è imprevedibile e resta poi identico per tutta la vita, salvo cicatrici profonde."),
        ("Uniche per ciascuno",
         "Non esistono due persone con impronte identiche, nemmeno i gemelli omozigoti, che pure condividono lo stesso DNA. La ragione è che le impronte non sono scritte solo nei geni, ma dipendono anche dalle piccole variazioni casuali dello sviluppo nel grembo. Sono un esempio perfetto di come caso e biologia si intreccino."),
        ("A cosa servono davvero",
         "Prima ancora che per identificarci, le impronte hanno probabilmente una funzione pratica. I loro solchi potrebbero migliorare la presa su superfici lisce o bagnate, un po' come il battistrada di un pneumatico. Aiutano anche il senso del tatto, amplificando le minuscole vibrazioni quando le dita scorrono su una superficie."),
        ("La scoperta forense",
         "L'idea di usarle per identificare le persone è relativamente recente, di poco più di un secolo fa. La loro unicità e permanenza le rese perfette per riconoscere gli individui. Le impronte lasciate dai residui di sudore e grasso della pelle divennero una prova preziosa, rivoluzionando le indagini criminali in tutto il mondo."),
        ("Oltre le dita",
         "Disegni unici simili si trovano anche altrove: sul palmo, sulla pianta dei piedi e persino, in modo diverso, nell'iride dell'occhio. Molte tecnologie moderne, dagli smartphone ai controlli di sicurezza, sfruttano proprio queste caratteristiche irripetibili del corpo per riconoscerci in modo rapido e affidabile."),
        ("Cosa portarti a casa",
         "Le impronte digitali sono un piccolo capolavoro del corpo: nate dal caso, uniche per ciascuno, utili alla presa e al tatto. Il loro uso per identificarci è quasi un effetto collaterale della loro straordinaria varietà. Portiamo sui polpastrelli una firma che nessun altro al mondo possiede."),
       ]),

    mk("corpo-umano", "cor-why-dreams",
       "Perché sogniamo?",
       ["sogni", "sonno"],
       "Ogni notte il cervello ci porta in mondi impossibili, per poi dimenticarli quasi subito. I sogni restano uno dei più grandi misteri della mente umana.",
       "Sogniamo soprattutto nel sonno REM: i sogni aiuterebbero a consolidare i ricordi, elaborare le emozioni e 'allenare' il cervello, ma il mistero resta aperto.",
       "https://images.unsplash.com/photo-1541199249251-f713e6145474?w=1200&q=80&auto=format&fit=crop",
       [
        ("Cosa succede quando sogniamo",
         "I sogni più vividi avvengono in una fase del sonno chiamata REM, quando gli occhi si muovono rapidamente sotto le palpebre e il cervello è quasi attivo come da svegli. Il corpo, però, resta paralizzato: un meccanismo che ci impedisce di agire fisicamente ciò che sogniamo. Attraversiamo più cicli di REM ogni notte."),
        ("Consolidare i ricordi",
         "Una delle teorie più solide è che il sonno, e i sogni, aiutino a fissare i ricordi. Durante la notte il cervello sembra rielaborare le esperienze della giornata, rafforzando ciò che è importante e scartando il superfluo. I sogni potrebbero essere, in parte, l'eco di questo lavoro di archiviazione della memoria."),
        ("Elaborare le emozioni",
         "Un'altra ipotesi vede i sogni come una palestra emotiva. Riviviamo in forma simbolica paure, desideri e tensioni, forse per smussarne l'impatto. Chi dorme bene tende a gestire meglio le emozioni del giorno dopo. I sogni, spesso strani o inquietanti, potrebbero aiutarci a metabolizzare ciò che ci turba."),
        ("Allenare il cervello",
         "Alcuni scienziati pensano che sognare situazioni di pericolo serva ad \"allenare\" le nostre risposte, in un ambiente sicuro. Affrontare in sogno minacce e sfide potrebbe preparare il cervello ad affrontarle nella realtà. Sarebbe un simulatore notturno, ereditato da un lontano passato in cui i pericoli erano quotidiani."),
        ("Perché li dimentichiamo",
         "La maggior parte dei sogni svanisce pochi minuti dopo il risveglio. Dipende dal fatto che, durante il sonno, le sostanze cerebrali che fissano i ricordi sono a livelli bassi. Ricordiamo un sogno solo se ci svegliamo proprio mentre lo stiamo facendo. Ecco perché spesso restiamo con la sensazione di aver sognato senza sapere cosa."),
        ("Cosa portarti a casa",
         "Nonostante secoli di studi, non abbiamo ancora una risposta definitiva sul perché sogniamo: probabilmente i sogni fanno più cose insieme, dalla memoria alle emozioni. Ogni notte il cervello ci regala uno spettacolo privato e misterioso. Che serva a molto o a poco, è una delle esperienze più universali e affascinanti dell'essere umani."),
       ]),
]
