"""PAUSE v7 — pareggio catalogo: Arte & Design e Geografia & Viaggi a 28 contenuti.
3 curiosità + 3 mini lezioni per categoria, 6 capitoli ciascuna, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ ARTE ------------------------------
    mk("arte", "v7-quadri-al-contrario",
       "Perché i musei appendono i quadri a quell'altezza?", ["altezza", "musei"],
       "Entri in una sala e i dipinti sembrano tutti in fila alla stessa quota, come se si fossero messi d'accordo. Non è un caso né un gusto: è una misura precisa, e ha una storia.",
       "La maggior parte dei musei allinea il centro dei quadri a circa 150-155 cm da terra, l'altezza media degli occhi. La regola è recente: fino all'Ottocento le opere si accatastavano dal pavimento al soffitto.",
       "",
       [
        ("Il muro come un mosaico",
         "Nei Salon parigini del Settecento e dell'Ottocento i quadri coprivano le pareti fino al soffitto, incorniciati a pochi centimetri l'uno dall'altro. La posizione era una classifica: i lavori premiati all'altezza degli occhi, gli esordienti 'al cielo', dove nessuno li vedeva. Gli artisti facevano carte false per evitare le file più alte, e alcuni dipingevano figure più grandi del necessario per essere leggibili da lontano."),
        ("La rivoluzione dello spazio vuoto",
         "Tra fine Ottocento e inizio Novecento le cose cambiano. I mercanti di Parigi e i musei tedeschi iniziano a esporre una sola fila di quadri, distanziati, su pareti chiare. L'idea è che ogni opera meriti aria intorno per essere vista da sola. Nel 1929 il Museum of Modern Art di New York adotta questo stile in modo sistematico, e il 'cubo bianco' diventa lo standard dei musei di tutto il mondo."),
        ("La misura degli occhi",
         "La convenzione attuale fissa il centro dell'opera a 57-60 pollici da terra, cioè tra 145 e 155 centimetri: l'altezza media dello sguardo di un adulto in piedi. Non il bordo inferiore, il centro: così un quadro grande e uno piccolo si guardano con lo stesso gesto. Molti musei hanno un'asticella di legno tagliata a misura che gli allestitori chiamano semplicemente 'la misura'."),
        ("Quando la regola si rompe",
         "Non tutto è a 150 centimetri. Le pale d'altare rinascimentali venivano dipinte per stare in alto, sopra un altare, con la prospettiva calcolata dal basso: appese all'altezza degli occhi appaiono strane, con i pavimenti che sembrano inclinati. I musei più attenti le rialzano. Al contrario, i quadri per bambini o le mostre di disegni si abbassano, e le opere pensate per essere guardate dall'alto vanno a terra."),
        ("La luce e la distanza",
         "Insieme all'altezza, gli allestitori decidono la distanza dalla parete opposta, la regola pratica dice una volta e mezzo la diagonale del quadro, e l'angolo della luce, di solito 30 gradi dall'alto per evitare riflessi e ombre della cornice. Ogni lampada è dosata in lux: per gli acquerelli e i disegni, fragili, non più di 50; per i dipinti a olio fino a 200. Per questo alcune sale sembrano buie: è per far durare le opere altri secoli."),
        ("Guarda dove guardi",
         "La prossima volta che entri in un museo, prova a notare la regola prima di infrangerla: i centri dei quadri formano una linea invisibile che corre lungo la sala. Poi abbassati o alzati sulle punte: vedrai come cambiano riflessi, colori e persino il senso di alcune figure. E se un'opera ti sembra 'sbagliata', chiediti per quale altezza era stata pensata. Il quadro non si è mosso; a essere spostato è il tuo punto di vista."),
       ]),
    mk("arte", "v7-graffiti-pompei",
       "I graffiti sui muri esistevano già a Pompei", ["graffiti", "Pompei"],
       "Insulti, dichiarazioni d'amore, conti della spesa, pubblicità elettorale. Sui muri di Pompei sono incisi più di undicimila messaggi, e leggerli è come aprire i social di duemila anni fa.",
       "A Pompei sono stati catalogati oltre 11.000 graffiti incisi o dipinti: propaganda elettorale, poesie, insulti e messaggi d'amore. Erano una forma normale di comunicazione, non vandalismo, e raccontano la vita quotidiana meglio dei testi ufficiali.",
       "",
       [
        ("Scrivere sui muri era normale",
         "Nel mondo romano un muro intonacato era una superficie pubblica su cui era lecito scrivere. Si incideva con uno stilo o un chiodo, o si dipingeva con pennelli e colori rossi. I pittori di scritte erano professionisti, gli 'scriptores', pagati per la propaganda elettorale, e firmavano il loro lavoro. Nessuno pensava di sporcare: era il modo più rapido per raggiungere chi passava."),
        ("La campagna elettorale sui muri",
         "Circa un quarto dei graffiti pompeiani sono manifesti elettorali: 'I fornai chiedono che Gaio Giulio Polibio sia eletto edile, porta il pane buono'. Gruppi di mestiere, quartieri e perfino i giocatori di dadi sostenevano i candidati. Alcuni erano ironici: 'Ti raccomandano i ladruncoli' e 'i bevitori tardivi ti sostengono tutti'. La politica locale funzionava a colpi di pennello."),
        ("Amore, gelosia e insulti",
         "Tra i messaggi più numerosi ci sono quelli d'amore, con versi ripresi dai poeti e storpiati: 'Chi ama viva, chi non sa amare muoia, e muoia due volte chi proibisce di amare'. Non mancano gli insulti, spesso indirizzati per nome, e i vanti dei clienti nelle taverne e nei lupanari. Alcune scritte sono conversazioni: una risposta incisa sotto la frase di qualcun altro, con giorni di distanza."),
        ("La spesa e i conti",
         "Su una parete di una casa qualcuno ha annotato la spesa di otto giorni: pane, olio, vino, formaggio, cipolle, e una voce 'per lo schiavo'. Altrove si contano gli incassi di una locanda e i debiti di un cliente. I muri erano anche lavagne: un maestro fece scrivere l'alfabeto a un bambino, e ci sono esercizi di calcolo con errori corretti."),
        ("Firme di visitatori",
         "Gli stessi turisti dell'antichità lasciavano la firma. Nel teatro e nell'anfiteatro sono incisi i nomi dei gladiatori con il conto delle vittorie, e frasi come 'Celado il Trace fa sospirare le ragazze'. Vicino alla porta di Nocera un viaggiatore scrisse: 'Mi meraviglio, o muro, che tu non sia crollato sotto il peso di tante sciocchezze'. Un commento che funziona anche oggi sotto qualunque post."),
        ("Perché sono preziosi",
         "I testi degli scrittori romani parlano di imperatori e battaglie; i graffiti danno la voce a fornai, schiavi, donne, bambini e tifosi. Grazie a loro sappiamo quanto costava una brocca di vino, come si tifava, come ci si insultava e come si corteggiava. Per questo ogni scritta viene fotografata e catalogata, e le più fragili sono protette con vetri. Il muro di Pompei è il più grande social network mai scavato."),
       ]),
    mk("arte", "v7-ombre-cinema",
       "Perché il buio in sala rende i film più belli", ["buio", "film"],
       "Al cinema si spengono le luci, a casa abbassiamo le tapparelle. Sembra solo una questione di riflessi sullo schermo, ma il buio lavora sul tuo cervello in modi che i pittori conoscevano già.",
       "Il buio elimina i riferimenti spaziali e fa sì che l'occhio giudichi i colori dello schermo come luce, non come oggetti. Migliora il contrasto percepito, aumenta l'immersione e sincronizza l'attenzione di tutta la sala.",
       "",
       [
        ("Un contrasto che non esiste",
         "Nessuno schermo può mostrare il nero: può solo non emettere luce, e il pixel spento assume il colore della sala. In una stanza illuminata il nero del film è grigio; nel buio totale il cervello, non avendo nulla di più scuro con cui confrontarlo, lo legge come nero assoluto. Il contrasto che percepisci non è dello schermo: è del contesto. È il motivo per cui la stessa TV sembra un'altra di sera."),
        ("La lezione dei pittori",
         "Caravaggio e i pittori barocchi avevano capito il trucco tre secoli prima del cinema: uno sfondo buio fa brillare qualunque luce. Nelle loro tele le figure emergono dal nero e l'occhio non può che andare dove il pittore vuole. Il cinema ha ripreso il metodo: la sala oscura è il fondo scuro del quadro, e lo schermo è la sola sorgente. Non è un caso che i registi parlino di 'dipingere con la luce'."),
        ("Senza riferimenti, ci si perde dentro",
         "Nel buio scompaiono le pareti, le poltrone, le persone accanto: il cervello perde i riferimenti che gli ricordano di essere seduto in una stanza. Gli studi sull'immersione mostrano che la sensazione di 'essere' nel film cresce quando il campo visivo è occupato solo dallo schermo. È lo stesso principio per cui si spengono le luci a teatro dal 1876, quando Wagner lo impose al suo teatro di Bayreuth."),
        ("Le pupille e il tempo",
         "Al buio le pupille si dilatano e la retina passa alla visione notturna, più sensibile ma più lenta ad adattarsi. Servono circa venti minuti per una visione completa: è il motivo per cui i primi minuti di trailer e pubblicità sono più luminosi e i film cominciano spesso con scene scure. Uno schermo di telefono acceso in sala resetta l'adattamento dei vicini: per questo dà così fastidio."),
        ("Ridere insieme",
         "Il buio fa anche un'altra cosa: sincronizza. Non vedendosi, gli spettatori si sentono meno osservati e reagiscono di più, e le risate e i sussulti si propagano per contagio uditivo. Le ricerche mostrano che una commedia vista in una sala piena e oscura fa ridere circa il doppio della stessa vista da soli. La sala buia è un dispositivo sociale oltre che ottico."),
        ("Il cinema a casa, fatto bene",
         "Per avvicinarsi all'effetto sala non serve un proiettore. Spegni le luci, o lascia una sola lampada dietro lo schermo: la luce di sfondo neutra riduce l'affaticamento senza rovinare il contrasto. Disattiva la modalità 'vivida' della TV, pensata per i negozi illuminati, e scegli quella 'cinema' o 'filmmaker'. E metti via il telefono: il film è un quadro di Caravaggio e la sua cornice buia sei tu."),
       ]),
    # ------------------------------ GEOGRAFIA ------------------------------
    mk("geografia", "v7-fusi-orari-strani",
       "Il paese dove il fuso orario è a metà ora", ["fuso orario", "metà"],
       "In India sono le 12:30 quando a Londra sono le 7. In Nepal le 12:45. E in Cina un paese largo cinquemila chilometri ha un'ora sola. I fusi orari non seguono il Sole: seguono la politica.",
       "I fusi orari teorici sono 24 fasce di 15 gradi, ma quelli reali sono decisi dai governi: l'India usa +5:30, il Nepal +5:45, la Cina un solo fuso per tutto il paese e la Spagna quello dell'Europa centrale per una scelta del 1940.",
       "",
       [
        ("Un'ora ogni 15 gradi, in teoria",
         "La Terra ruota di 360 gradi in 24 ore, quindi ogni 15 gradi di longitudine il Sole culmina un'ora dopo. Nel 1884 una conferenza a Washington fissò il meridiano di Greenwich come zero e propose 24 fasce regolari. Sulla carta è perfetto. Ma le fasce tagliano città, stati e famiglie a metà, e nessun governo ha voglia che i suoi cittadini vivano su due orari."),
        ("L'India e la mezz'ora",
         "L'India si estende su quasi 30 gradi di longitudine, due fusi teorici. Alla nascita della repubblica, nel 1947, per non favorire né Calcutta né Bombay si scelse la via di mezzo: il meridiano di Allahabad, a +5:30 rispetto a Greenwich. Il Nepal fece un passo oltre per distinguersi dal grande vicino: +5:45, calcolato sul monte Gauri Shankar. Anche l'Iran, l'Afghanistan e parte dell'Australia usano mezz'ore."),
        ("La Cina con un orologio solo",
         "La Cina copre cinque fusi teorici ma dal 1949 ne usa uno solo, quello di Pechino. Nell'estremo ovest, nello Xinjiang, il Sole sorge alle dieci del mattino d'inverno e gli uffici aprono di conseguenza. Molti abitanti uiguri usano di fatto un'ora locale non ufficiale, due ore indietro, e chiedere 'a che ora ci vediamo' richiede di specificare quale delle due."),
        ("La Spagna vive in un'ora sbagliata",
         "Madrid è più a ovest di Londra, eppure ha l'ora di Berlino. Nel 1940 Franco spostò gli orologi avanti di un'ora per allinearsi alla Germania e nessuno li ha più rimessi indietro. Il risultato: in Spagna si pranza alle due e si cena alle dieci, ma rispetto al Sole sono le una e le nove. Ogni tanto il parlamento discute di tornare all'ora di Greenwich, come il Portogallo."),
        ("La linea dove cambia il giorno",
         "Dall'altra parte del mondo corre la linea del cambiamento di data, che zigzaga nel Pacifico per non tagliare arcipelaghi. Nel 1995 Kiribati la spostò a est per unificare il paese in un solo giorno, e da allora le sue isole più orientali sono le prime a salutare l'anno nuovo. Le Samoa nel 2011 saltarono direttamente da giovedì 29 a sabato 31 dicembre per allinearsi ai partner commerciali in Australia e Nuova Zelanda."),
        ("Chi ha più fusi di tutti",
         "La Francia ha dodici fusi orari, più di qualunque altro paese, grazie ai territori d'oltremare dalla Polinesia alla Guyana. La Russia ne ha undici su un solo continente. E lo spazio? Sulla Stazione Spaziale Internazionale, dove il Sole sorge sedici volte al giorno, si usa l'ora di Greenwich: un compromesso tra Houston e Mosca. Il tempo, ovunque, è una convenzione che si negozia."),
       ]),
    mk("geografia", "v7-fiume-che-scorre-al-contrario",
       "Il fiume che scorre in due direzioni", ["fiume", "direzioni"],
       "A Chicago un fiume che finiva nel lago oggi ne esce. In Cambogia un affluente inverte il corso ogni anno. E il Mississippi, per una notte, tornò indietro. I fiumi non sono così ostinati come sembrano.",
       "Il Chicago River fu invertito artificialmente nel 1900 per allontanare le acque reflue dal lago Michigan; il Tonlé Sap in Cambogia cambia direzione ogni monsone; nel 1811 un terremoto fece scorrere il Mississippi al contrario per alcune ore.",
       "",
       [
        ("Chicago cambia verso",
         "Alla fine dell'Ottocento Chicago scaricava tutto nel suo fiume, che sfociava nel lago Michigan: la stessa acqua che la città beveva. Le epidemie di colera e tifo erano regolari. Nel 1900 gli ingegneri completarono un canale che, sfruttando un dislivello minimo, fece invertire il corso: da allora il fiume esce dal lago e porta le acque verso il Mississippi. Il lago tornò potabile e St. Louis, a valle, fece causa."),
        ("Il fiume-pendolo della Cambogia",
         "Il Tonlé Sap collega il grande lago omonimo al Mekong. Nella stagione secca scorre dal lago verso il fiume. Quando arrivano i monsoni, il Mekong si gonfia tanto da spingere l'acqua all'indietro, il fiume si inverte e il lago cresce fino a cinque volte. Milioni di pesci seguono l'acqua e i villaggi galleggianti si spostano con loro: la festa nazionale dell'acqua, a novembre, celebra il momento in cui il fiume torna a scorrere 'giusto'."),
        ("La notte in cui il Mississippi tornò indietro",
         "Il 7 febbraio 1812 un terremoto violentissimo colpì il Missouri. Il letto del Mississippi si sollevò e per alcune ore il fiume più grande dell'America del Nord scorse verso nord, creando cascate temporanee e il lago Reelfoot, che esiste ancora. I barcaioli raccontarono di essere stati trascinati controcorrente. Non fu un'inversione permanente, ma dimostrò quanto poco basti a un fiume per cambiare idea."),
        ("I fiumi che si scambiano",
         "In Amazzonia il Casiquiare fa una cosa che sui libri non dovrebbe esistere: collega due bacini diversi. Nasce dall'Orinoco e sfocia nel Rio Negro, affluente dell'Amazzonia, funzionando da canale naturale tra due dei fiumi più grandi del mondo. Per gli idrologi è un caso quasi unico di 'biforcazione fluviale' stabile, e i pesci lo usano per passare da un sistema all'altro."),
        ("Le maree che risalgono",
         "In molti estuari il fiume scorre all'indietro due volte al giorno. Sul Rio delle Amazzoni la marea crea la pororoca, un'onda che risale il fiume per centinaia di chilometri e che i surfisti cavalcano per minuti interi. Sul Severn, in Inghilterra, e sul Qiantang, in Cina, il fenomeno attira folle: l'acqua del mare, spinta dalla marea, vince il fiume e lo fa scorrere verso la sorgente."),
        ("Perché ci importa",
         "I fiumi che cambiano direzione ricordano che la geografia non è fissa. I delta si spostano, i meandri si tagliano da soli, e le dighe possono trasformare un fiume in un lago o in un rigagnolo. Capire come e perché l'acqua cambia verso serve a costruire città più sicure e a non dare per scontato il paesaggio che vediamo: la mappa di oggi è una fotografia di un istante."),
       ]),
    mk("geografia", "v7-deserto-piu-grande",
       "Il deserto più grande del mondo è coperto di ghiaccio", ["deserto", "ghiaccio"],
       "Pensiamo alle dune del Sahara, ma un deserto si misura in pioggia, non in sabbia. E il posto più secco della Terra è anche il più freddo.",
       "Un deserto è una zona con meno di 250 millimetri di precipitazioni all'anno. Con questo criterio l'Antartide, 14 milioni di km², è il deserto più grande del mondo, seguito dall'Artico; il Sahara è solo il più grande deserto caldo.",
       "",
       [
        ("Cos'è davvero un deserto",
         "Per i geografi il deserto non ha a che fare con la temperatura né con la sabbia: è un luogo dove cade poca acqua, meno di 250 millimetri l'anno, e dove ne evapora più di quanta ne arriva. Con questa definizione il Sahara è un deserto, ma lo sono anche le steppe fredde della Mongolia e le calotte polari. La sabbia copre solo un quinto del Sahara: il resto è roccia e ghiaia."),
        ("L'Antartide, secca come nessun altro luogo",
         "Nell'interno dell'Antartide cadono meno di 50 millimetri di neve all'anno, l'equivalente in acqua di una bottiglia per metro quadrato. L'aria è così fredda da non poter trattenere vapore. Il ghiaccio che vediamo si è accumulato in centinaia di migliaia di anni, fiocco dopo fiocco. Nelle Valli Secche di McMurdo non piove né nevica da circa due milioni di anni e i venti asciugano ogni cosa: i corpi delle foche smarrite restano mummificati per secoli."),
        ("La classifica dei deserti",
         "Antartide, 14 milioni di chilometri quadrati. Artico, quasi altrettanto. Poi il Sahara con 9 milioni, il primo deserto caldo, grande quanto gli Stati Uniti. Seguono il deserto arabico, il Gobi, il Kalahari e la Patagonia. In tutto i deserti coprono circa un terzo delle terre emerse, e un miliardo di persone vive in zone aride."),
        ("Il posto più secco dove vive gente",
         "Ad Arica, nel deserto di Atacama in Cile, la media è di meno di un millimetro di pioggia all'anno e alcune stazioni meteo non hanno registrato una goccia per decenni. Eppure ci vivono duecentomila persone, grazie ai fiumi che scendono dalle Ande e alla nebbia costiera, la camanchaca, che viene catturata con reti verticali e trasformata in acqua potabile. Il cielo così limpido ospita i più grandi telescopi del mondo."),
        ("Il Sahara era verde",
         "Diecimila anni fa il Sahara era una savana con laghi, ippopotami e pescatori: le pitture rupestri del Tassili mostrano mandrie e nuotatori. Un lieve cambiamento nell'inclinazione dell'asse terrestre spostò i monsoni verso sud, e nel giro di poche migliaia di anni il verde si ritirò. I deserti si muovono: il Sahara oggi avanza e si ritira di decine di chilometri a seconda dei decenni, e il ciclo tornerà."),
        ("Perché la definizione conta",
         "Chiamare deserto l'Antartide non è pignoleria: aiuta a capire che il problema dell'acqua non è il caldo ma il bilancio tra ciò che arriva e ciò che se ne va. Molte città in zone temperate vivono già un 'deserto' stagionale e lo affrontano con le stesse tecniche del Cile e dell'Arabia: raccolta della nebbia, dissalazione, riuso. Il deserto non è un luogo lontano: è una condizione, e sta a noi tenerlo a distanza."),
       ]),
]

LESSONS = [
    # ------------------------------ ARTE ------------------------------
    L("arte", "v7-lez-scultura-materiali",
      "Riconoscere una scultura: marmo, bronzo, terracotta in 6 passi", ["scultura", "materiali"],
      "Davanti a una statua chiediamo 'chi è?' ma quasi mai 'di cosa è fatta?'. Eppure il materiale racconta tecnica, epoca e prezzo, e si riconosce con pochi indizi.",
      "Distinguere i principali materiali della scultura a colpo d'occhio e capire cosa dicono su come e quando l'opera è stata fatta.",
      "Il marmo si toglie, il bronzo si fonde in cavo, la terracotta si modella e si cuoce. Guarda i puntelli, il colore, il peso apparente e le superfici: ogni materiale lascia firme diverse.",
      [
       ("Passo 1 — Togliere o aggiungere",
        "Tutta la scultura si divide in due famiglie. Nella prima si toglie materiale da un blocco: marmo, pietra, legno. Nella seconda si aggiunge o si modella: argilla, cera, gesso, e da questi modelli si fonde il bronzo. Chi toglie non può tornare indietro, ed è per questo che Michelangelo diceva di 'liberare' la figura dal blocco; chi modella può correggere all'infinito. Il primo indizio: chiediti se l'artista poteva sbagliare."),
       ("Passo 2 — Il marmo e i suoi puntelli",
        "Il marmo è pesante e fragile alle sporgenze: un braccio teso si spezza sotto il proprio peso. Per questo le statue antiche hanno tronchi d'albero, panneggi o piccoli sostegni che collegano le parti sottili al corpo: sono i puntelli. Il marmo bianco lucidato lascia passare la luce per qualche millimetro e sembra pelle; con il tempo ingiallisce e prende macchie. Le copie romane di originali greci in bronzo si riconoscono proprio dai puntelli aggiunti."),
       ("Passo 3 — Il bronzo è vuoto",
        "Una statua in bronzo non è un blocco pieno: è un guscio di pochi millimetri, fuso intorno a un'anima di argilla con la tecnica della cera perduta. Per questo può fare ciò che al marmo è proibito: cavalli impennati, braccia tese, figure in equilibrio su un piede. Il colore va dal dorato del bronzo nuovo al verde della patina antica. Cerca i segni di saldatura tra le parti e i piccoli tappi rotondi dove i fori di fusione sono stati chiusi."),
       ("Passo 4 — Terracotta e gesso",
        "La terracotta è argilla modellata e cotta: rossastra o color sabbia, leggera, con superfici che conservano le impronte delle dita e degli strumenti. Era il materiale dei bozzetti e delle opere economiche, ma anche di capolavori come l'esercito di Xi'an. Il gesso, bianco e opaco, serviva per i calchi e i modelli in scala: se in un museo vedi una statua bianca ma con dettagli un po' molli e senza venature, probabilmente è un calco."),
       ("Passo 5 — Il legno e la policromia",
        "Le sculture in legno erano quasi sempre dipinte: i santi delle chiese medievali con incarnati rosa, vesti dorate e occhi di vetro. Se oggi le vedi in legno nudo, è perché il colore è caduto o è stato rimosso da restauri ottocenteschi che preferivano il 'materiale sincero'. Anche i marmi greci erano colorati: la statua bianca è un'idea moderna. Cerca le tracce di pigmento nelle pieghe e nelle orecchie."),
       ("Passo 6 — Metti insieme gli indizi",
        "Davanti alla prossima statua fai il giro completo e rispondi: ha puntelli? Allora è pietra. Ha pose impossibili e colore verde-bruno? Bronzo. È leggera, rossastra, con impronte? Terracotta. Uniformemente bianca e opaca? Gesso. Poi leggi la targhetta e controlla. In tre visite riconoscerai i materiali senza pensarci, e comincerai a vedere la cosa più interessante: come ogni artista ha lottato con i limiti del suo."),
      ]),
    L("arte", "v7-lez-leggere-fotografia",
      "Leggere una fotografia: 6 domande per capire cosa ti sta dicendo", ["fotografia", "domande"],
      "Vediamo migliaia di immagini al giorno e le crediamo vere perché sono foto. Ma ogni scatto è una serie di scelte, e leggerle è una competenza che si impara.",
      "Analizzare una fotografia, di cronaca o d'arte, riconoscendo le scelte di chi l'ha fatta e il loro effetto su chi guarda.",
      "Inquadratura, punto di vista, luce, istante, cosa manca e didascalia: sei scelte che trasformano la realtà in un racconto. Impara a vederle e nessuna immagine ti sembrerà più neutra.",
      [
       ("Passo 1 — Cosa c'è dentro, cosa è fuori",
        "L'inquadratura è la scelta più potente: il fotografo decide dove finisce il mondo. Una folla ripresa stretta sembra enorme, la stessa folla dall'alto può essere trenta persone in una piazza vuota. Chiediti sempre cosa potrebbe esserci appena fuori dai bordi. Le foto più discusse della storia sono spesso ritagli: la stessa immagine, allargata, racconta un'altra storia."),
       ("Passo 2 — Da dove guarda",
        "Il punto di vista assegna un ruolo. Dal basso, un soggetto diventa imponente o minaccioso: è così che si fotografano statue e dittatori. Dall'alto, appare piccolo e vulnerabile. Alla stessa altezza degli occhi, alla pari. I fotografi di bambini si inginocchiano proprio per questo. Un politico ripreso dal basso e uno dall'alto nello stesso articolo non sono un caso."),
       ("Passo 3 — La luce decide l'umore",
        "Luce frontale e piatta: neutra, da documento. Laterale: volumi e drammaticità, come nei ritratti in bianco e nero. Controluce: silhouette e mistero. Luce dura del mezzogiorno: ombre nette, tensione. Luce morbida di un cielo nuvoloso: intimità. Il fotografo sceglie l'ora, il lato e la qualità della luce, o le aspetta per ore. Prova a nominare la luce in ogni foto che guardi: in una settimana lo farai in automatico."),
       ("Passo 4 — L'istante scelto",
        "Una foto dura una frazione di secondo estratta da un flusso. Il fotografo Cartier-Bresson lo chiamava 'momento decisivo': il salto sulla pozzanghera, la mano a mezz'aria, l'espressione tra due espressioni. Un volto colto mentre sbatte le palpebre sembra addormentato; a metà parola, arrabbiato. Le foto di cronaca che 'dicono tutto' sono spesso un istante che, in movimento, non avrebbe significato nulla."),
       ("Passo 5 — Cosa manca",
        "L'assenza è una scelta come la presenza. Una spiaggia paradisiaca senza il resort sullo sfondo, una manifestazione senza la polizia, o con solo la polizia. Chiediti chi non c'è, e perché. Poi guarda il lavoro sull'immagine: il bianco e nero elimina informazioni e aggiunge solennità; i colori saturati rendono tutto più intenso di quanto fosse. Nessuna di queste operazioni è una bugia, ma tutte sono una voce che ti parla."),
       ("Passo 6 — La didascalia comanda",
        "L'ultimo passo è il testo. La stessa foto di un uomo che corre con una borsa diventa 'un ladro in fuga' o 'un padre in ritardo' a seconda della didascalia. Nelle notizie, leggi prima l'immagine da sola e formula una tua ipotesi, poi il testo: dove non coincidono è il punto interessante. Esercizio finale: prendi una foto sul tuo telefono e scrivile tre didascalie diverse, vere tutte e tre. Avrai capito come funziona il potere delle immagini."),
      ]),
    L("arte", "v7-lez-musica-classica-orientarsi",
      "Ascoltare la musica classica senza sentirsi persi: 6 passi", ["musica classica", "ascoltare"],
      "Trenta minuti di sinfonia possono sembrare un muro. Ma la musica classica ha una grammatica semplice: temi che tornano, tensioni che si risolvono, forme che si ripetono da tre secoli.",
      "Ascoltare un brano classico riconoscendone la struttura e i temi, per passare dal sottofondo all'attenzione.",
      "Cerca il tema, seguilo quando torna cambiato, nota la tensione e la risoluzione, riconosci le grandi forme e scegli tre brani da riascoltare più volte: la familiarità è il segreto del piacere.",
      [
       ("Passo 1 — Trova il tema",
        "Quasi ogni brano classico comincia presentando una melodia riconoscibile, il tema, come un personaggio all'inizio di un romanzo. Nella Quinta di Beethoven sono le quattro note che tutti conoscono. Il tuo primo compito è solo questo: individuarlo nei primi trenta secondi e canticchiarlo mentalmente. Tutto il resto del brano sarà quel personaggio che viaggia, si traveste e torna."),
       ("Passo 2 — Seguilo quando torna",
        "Il gioco della musica classica è la variazione: il tema riappare più lento, più acuto, spezzato, suonato dai violoncelli invece che dai violini, in tonalità minore e più cupa. Ogni volta che lo riconosci sotto un travestimento, il cervello prova un piccolo piacere, lo stesso di un indovinello risolto. È l'ascolto 'attivo': non attendere che la musica ti colpisca, ma cercare il tema come si cerca un volto in una folla."),
       ("Passo 3 — Tensione e risoluzione",
        "La musica occidentale funziona come una frase con un punto finale. Alcuni accordi suonano 'in sospeso' e chiedono di essere risolti; il compositore ritarda quella risoluzione per creare attesa, poi la concede. Prova a notare quando il brano sembra 'domandare' e quando 'risponde'. I finali che sembrano non arrivare mai, con l'orchestra che insiste, sono il compositore che gioca con la tua voglia di chiusura."),
       ("Passo 4 — Le grandi forme",
        "Tre forme coprono la maggior parte del repertorio. La sinfonia: quattro movimenti, in genere veloce, lento, danzante, veloce. Il concerto: un solista dialoga e gareggia con l'orchestra, in tre movimenti. La sonata e il quartetto: la stessa idea in piccolo, per uno o quattro strumenti. Conoscere la scaletta aiuta come conoscere gli atti di un'opera teatrale: sai dove sei e cosa aspettarti."),
       ("Passo 5 — Riconosci gli strumenti",
        "Un'orchestra è divisa in famiglie e ognuna ha un carattere. Archi: la voce principale, calda e continua. Legni, flauto, oboe, clarinetto, fagotto: colori, spesso i solisti delle melodie malinconiche. Ottoni, corni, trombe, tromboni: potenza e solennità. Percussioni: ritmo e drammaticità. Durante l'ascolto prova a indovinare chi sta suonando il tema in quel momento e perché il compositore ha scelto proprio quella voce."),
       ("Passo 6 — Il programma di tre brani",
        "La familiarità è la chiave del piacere musicale: quasi nessuno ama un brano al primo ascolto. Scegli tre pezzi di dieci minuti al massimo, per esempio il primo movimento della Quinta di Beethoven, l'Adagio del Concerto per clarinetto di Mozart e la Danza ungherese n. 5 di Brahms, e ascoltali una volta al giorno per una settimana, con le domande dei passi precedenti in mente. Al settimo giorno saranno tuoi, e avrai un metodo per tutto il resto."),
      ]),
    # ------------------------------ GEOGRAFIA ------------------------------
    L("geografia", "v7-lez-orientarsi-senza-gps",
      "Orientarsi senza telefono: 6 metodi che funzionano davvero", ["orientarsi", "senza telefono"],
      "Batteria scarica, nessun segnale, un sentiero che si biforca. Il Sole, le stelle, un orologio e un po' di attenzione bastano a trovare il nord, di giorno e di notte.",
      "Trovare i punti cardinali con il Sole, l'orologio, la Stella Polare e gli indizi del paesaggio, e usarli per non perdersi.",
      "Il Sole a mezzogiorno indica il sud, l'orologio lo trasforma in bussola, la Stella Polare segna il nord di notte. Vento, muschio e neve danno indizi; una mappa mentale prima di partire vale più di tutto.",
      [
       ("Passo 1 — Il Sole e l'ora",
        "Nell'emisfero nord il Sole sorge grosso modo a est, culmina a sud verso le 12 (le 13 con l'ora legale) e tramonta a ovest. A metà mattina è quindi a sud-est, a metà pomeriggio a sud-ovest. Basta questo per un orientamento grossolano. La tua ombra a mezzogiorno punta a nord. Ricorda che in estate l'alba e il tramonto si spostano molto verso nord-est e nord-ovest: 'il Sole sorge a est' è vero solo agli equinozi."),
       ("Passo 2 — L'orologio come bussola",
        "Con un orologio a lancette, o disegnandone uno su carta con l'ora attuale, punta la lancetta delle ore verso il Sole. La bisettrice tra la lancetta e le 12 indica il sud. Con l'ora legale usa l'1 al posto delle 12. È preciso a una decina di gradi, più che sufficiente per capire in che direzione va la valle. Nell'emisfero sud si fa l'opposto: punta le 12 verso il Sole e la bisettrice indica il nord."),
       ("Passo 3 — La Stella Polare",
        "Di notte trova il Grande Carro, sette stelle a forma di pentola, e prolunga di cinque volte la distanza tra le due stelle del bordo esterno: arrivi a una stella non molto luminosa ma isolata, la Polare, che indica il nord con un errore di meno di un grado. La sua altezza sull'orizzonte è uguale alla tua latitudine. Se il Carro è basso o nascosto, usa Cassiopea, la W dall'altra parte della Polare."),
       ("Passo 4 — Gli indizi del paesaggio",
        "Nessuno è affidabile da solo, insieme aiutano. Il muschio cresce dove c'è umidità, spesso a nord dei tronchi, ma non sempre. La neve resta più a lungo sui versanti nord. Gli anelli degli alberi tagliati sono più larghi verso sud. Le antenne paraboliche delle case in Europa puntano verso sud-sud-est, e sono l'indizio più affidabile in città. I venti dominanti piegano gli alberi isolati sempre nella stessa direzione: informati su quale sia nella tua zona."),
       ("Passo 5 — La mappa in testa",
        "Il metodo più efficace si usa prima di partire: guarda la mappa e memorizza tre cose. Dove sta il nord rispetto alla direzione in cui vai, quale grande riferimento lineare, un fiume, una strada, una cresta, ti accompagna e da che lato, e qual è la 'linea di sicurezza' che, seguita, ti porta comunque a un luogo abitato. In caso di dubbio, scendere lungo l'acqua porta quasi sempre a una strada."),
       ("Passo 6 — L'esercizio della settimana",
        "Per una settimana, ogni volta che esci, prova a dire in che direzione stai camminando prima di controllare sulla mappa del telefono. Usa il Sole, le ombre, le parabole. Segna quante volte hai indovinato. Il primo giorno sbaglierai spesso, il quinto quasi mai: la percezione della direzione è una capacità che si allena e che i navigatori ci hanno fatto perdere. Riprendertela è gratis e non finisce mai la batteria."),
      ]),
    L("geografia", "v7-lez-leggere-clima",
      "Perché il clima è così: leggere una città in 6 passi", ["clima", "città"],
      "Roma e New York sono alla stessa latitudine, eppure a New York nevica ogni inverno. Lisbona è più a sud di Napoli ma ha estati più fresche. Il clima di un luogo si spiega con pochi fattori, sempre gli stessi.",
      "Capire il clima di qualunque città a partire da latitudine, mare, correnti, altitudine, venti e forma del territorio.",
      "Latitudine, distanza dal mare, correnti oceaniche, altitudine, venti dominanti e barriere montuose: sei fattori che combinati spiegano perché in un posto piove, gela o fa caldo tutto l'anno.",
      [
       ("Passo 1 — La latitudine dà l'energia",
        "Più si è vicini all'equatore, più il Sole è alto e l'energia ricevuta è alta e costante tutto l'anno. Ai tropici non ci sono stagioni termiche ma stagioni delle piogge; alle medie latitudini le quattro stagioni; ai poli sei mesi di luce e sei di buio. La latitudine è il punto di partenza di ogni ragionamento: ma da sola spiega poco, come mostrano Roma e New York."),
       ("Passo 2 — Il mare è un termosifone",
        "L'acqua si scalda e si raffredda lentamente: le città costiere hanno inverni più miti ed estati meno roventi delle città interne. Per questo Lisbona, sull'Atlantico, è più fresca di Madrid in agosto pur essendo più a sud. Il clima continentale, lontano dal mare, ha escursioni enormi: a Ulan Bator si passa da -30 a +30 nel corso dell'anno. Regola pratica: più sei lontano dal mare, più estremi saranno inverno ed estate."),
       ("Passo 3 — Le correnti spostano il calore",
        "Non tutti i mari sono uguali. La Corrente del Golfo porta acqua calda dai Caraibi fino alla Norvegia: per questo Bergen, alla latitudine della Groenlandia meridionale, ha porti liberi dal ghiaccio e inverni piovosi ma miti. Sulla costa americana la corrente è fredda e scende dall'Artico: ecco perché New York gela. Sulle coste occidentali dei continenti, dal Perù alla Namibia, le correnti fredde creano deserti costieri e nebbie."),
       ("Passo 4 — Ogni cento metri, mezzo grado",
        "Salendo, la temperatura scende di circa 0,6 gradi ogni 100 metri. Città come Quito o Bogotà, quasi sull'equatore ma a 2.500-2.800 metri, hanno una 'primavera eterna' intorno ai 15 gradi. In Italia, la stessa giornata è di 30 gradi a Bolzano e di 12 sul passo dello Stelvio. L'altitudine è l'unico fattore che l'uomo sceglie facilmente: le città coloniali dei tropici sono state fondate in collina proprio per questo."),
       ("Passo 5 — I venti e le montagne",
        "Il vento porta l'umidità del mare verso terra; quando incontra una catena montuosa, sale, si raffredda e scarica la pioggia sul versante esposto. Oltre la cresta scende asciutto e caldo: è l'ombra pluviometrica. Per questo a ovest della Sierra Nevada la California è verde e a est c'è il deserto del Nevada; il Piemonte è più piovoso della pianura padana orientale; la Patagonia argentina è arida mentre il Cile, dall'altra parte delle Ande, è coperto di foreste."),
       ("Passo 6 — Leggi la tua città",
        "Ora applica i sei fattori a dove vivi. Qual è la latitudine? Quanto dista il mare e che corrente ha? A che altitudine sei? Da dove arrivano i venti che portano pioggia, e c'è una montagna che li ferma? Scrivi le risposte in cinque righe: avrai spiegato il tuo clima meglio di molti articoli. Poi prova con la prossima città in cui andrai in vacanza, prima di leggere le previsioni: saprai già cosa mettere in valigia."),
      ]),
    L("geografia", "v7-lez-viaggiare-leggeri",
      "Fare la valigia in 6 passi: viaggiare leggeri senza rinunce", ["valigia", "leggeri"],
      "Ogni viaggio finisce con un terzo dei vestiti mai indossati e un bagaglio che pesa come un'ancora. Un metodo per portare tutto ciò che serve, e nient'altro.",
      "Preparare un bagaglio compatto e completo per qualunque viaggio, con un metodo ripetibile che riduce peso, stress e imprevisti.",
      "Parti dalle attività, non dai giorni; scegli una tavolozza di colori; arrotola; usa una lista fissa; lascia un quarto di spazio vuoto; verifica il peso e le regole della compagnia. Il bagaglio leggero è una decisione, non una rinuncia.",
      [
       ("Passo 1 — Conta le attività, non i giorni",
        "L'errore classico è un cambio al giorno. Ragiona invece per situazioni: camminare, cena fuori, spiaggia, pioggia, freddo serale. Per ogni situazione basta un capo o due, che si ripeteranno. Per una settimana in città bastano tre maglie, due pantaloni, un capo elegante, una giacca leggera e un intimo per quattro giorni: si lava nel lavandino con il sapone dell'hotel. Nessuno si accorge se ripeti un vestito; tu ti accorgerai del peso in meno."),
       ("Passo 2 — Una tavolozza di colori",
        "Scegli due colori neutri, per esempio blu e beige, e un colore d'accento. Ogni capo deve stare bene con ogni altro: così cinque pezzi diventano dieci combinazioni. Evita il capo 'speciale' che si abbina a una cosa sola: è quello che torna a casa pulito. Le scarpe sono il peso maggiore: due paia al massimo, una comoda per camminare e una che vada anche la sera, indossando la più pesante in viaggio."),
       ("Passo 3 — Arrotola e comprimi",
        "I vestiti arrotolati stretti occupano meno spazio delle pile e si stropicciano meno. Metti i rotoli in cubi di stoffa o in sacchetti per categoria: cercare un calzino non disfa più tutto. I capi tecnici in lana merino o sintetici leggeri asciugano in una notte e non prendono odori: costano di più ma sostituiscono tre magliette di cotone. Le bottiglie di plastica si sostituiscono con flaconi da viaggio, riempiti a metà."),
       ("Passo 4 — La lista che non cambia",
        "Scrivi una volta sola la tua lista base, salvala sul telefono e usala per ogni viaggio, spuntando. Includi le cose che non si vedono e si dimenticano: caricabatterie, adattatore, medicinali con la ricetta, una copia dei documenti in una tasca diversa, un sacchetto per il bucato, una borsa pieghevole per la spesa. La lista toglie l'ansia del 'cosa dimentico' e ti fa preparare il bagaglio in mezz'ora."),
       ("Passo 5 — Lascia spazio vuoto",
        "Chiudi la valigia con un quarto di spazio libero. Servirà per ciò che compri, per i vestiti sporchi che occupano più dei puliti e per la sciarpa che avrai comprato perché fa più freddo del previsto. Un bagaglio pieno al cento per cento alla partenza è un problema al ritorno. La regola vale doppio per chi viaggia con lo zaino: un carico al 75 per cento si porta molto meglio sulla schiena."),
       ("Passo 6 — Pesa, controlla, parti",
        "Prima di partire pesa il bagaglio con una bilancia da valigia o su quella da cucina: le compagnie low cost applicano limiti stretti e le penali costano più del biglietto. Controlla le regole per liquidi e batterie e tieni a portata di mano ciò che serve al controllo. Ultimo gesto: apri la valigia e togli una cosa. Se dopo tre viaggi non l'hai mai rimpianta, cancellala dalla lista. Il bagaglio perfetto si costruisce viaggio dopo viaggio, per sottrazione."),
      ]),
]
