"""PAUSE — 10 storie categoria GEOGRAFIA & VIAGGI (scritte a mano, IT)."""
from story_builder import mk

IMG = [
    "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1439405326854-014607f694d7?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1520681279154-51b3fb4ea0f8?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop",
]

STORIES = [
    mk("geografia", "geo-why-timezones",
       "Perché esistono i fusi orari?",
       ["fusi", "orari"],
       "Quando a Roma è mezzogiorno, a Tokyo è già sera e a New York è notte fonda. Un sistema che diamo per scontato, ma nato meno di 150 anni fa.",
       "I fusi orari esistono perché la Terra ruota e il Sole illumina le zone in momenti diversi: furono standardizzati nell'Ottocento grazie alle ferrovie.",
       IMG[0],
       [
        ("Il tempo segue il Sole",
         "Per gran parte della storia, ogni città regolava l'orologio sul Sole locale: mezzogiorno era quando il Sole era più alto in cielo. Questo significava che città vicine avevano orari leggermente diversi. Andava benissimo in un mondo lento, dove un viaggio durava giorni e nessuno notava pochi minuti di scarto tra un luogo e l'altro."),
        ("Le ferrovie cambiano tutto",
         "Con l'arrivo dei treni, la faccenda divenne un caos. Come si scrive un orario ferroviario se ogni stazione ha un'ora diversa? Gli incidenti e le coincidenze mancate spinsero alla standardizzazione. La necessità di coordinare i viaggi su lunghe distanze fu il vero motore che portò a inventare un tempo condiviso."),
        ("La nascita dei fusi",
         "Nel 1884 una conferenza internazionale a Washington divise il mondo in 24 fusi orari, ciascuno di circa 15 gradi di longitudine. Fu scelto l'osservatorio di Greenwich, a Londra, come meridiano zero di riferimento. Da lì si contano le ore in avanti verso est e indietro verso ovest, creando l'ordinato mosaico temporale che usiamo oggi."),
        ("Confini tortuosi",
         "Sulla carta i fusi dovrebbero essere fasce verticali regolari, ma nella realtà i confini serpeggiano per seguire quelli degli Stati. Alcuni Paesi enormi, come la Cina, usano un solo fuso orario nonostante attraversino più fasce: una scelta politica per unificare la nazione, anche se all'ovest il Sole sorge con ore di ritardo sull'orologio."),
        ("Curiosità dai fusi",
         "Alcuni luoghi hanno fusi \"strani\", spostati di mezz'ora o di 45 minuti, come parti dell'India e del Nepal. La linea del cambio di data, nel Pacifico, separa un giorno dall'altro: attraversandola puoi \"viaggiare nel tempo\" di un giorno intero. E vicino ai poli, dove i fusi si stringono tutti, il tempo diventa quasi una convenzione arbitraria."),
        ("Cosa portarti a casa",
         "I fusi orari sembrano una legge naturale, ma sono un'invenzione recente, nata dal bisogno di coordinarci in un mondo diventato veloce. Sono un esempio perfetto di come la tecnologia (i treni, poi gli aerei) ci abbia costretti a mettere d'accordo qualcosa di sfuggente come il tempo stesso."),
       ]),

    mk("geografia", "geo-highest-mountain",
       "L'Everest è davvero la montagna più alta?",
       ["Everest", "montagna"],
       "Tutti sanno che l'Everest è il tetto del mondo. Ma la risposta dipende da come misuri 'alto': ci sono montagne che, per certi versi, lo battono.",
       "L'Everest è la vetta più alta sul livello del mare, ma non la montagna più alta dalla base, né il punto più lontano dal centro della Terra.",
       IMG[1],
       [
        ("Il tetto del mondo",
         "L'Everest, tra Nepal e Tibet, raggiunge 8.849 metri sul livello del mare: è la vetta che si spinge più in alto rispetto alla superficie degli oceani. Per questo è universalmente considerato la montagna più alta del pianeta. Scalarlo resta una delle imprese più ambite e pericolose dell'alpinismo, con la sua \"zona della morte\" oltre gli 8.000 metri."),
        ("Alto rispetto a cosa?",
         "Ma \"altezza\" è ambigua. Se misuriamo una montagna dalla sua base al suo vertice, l'Everest perde il primato. La sua base è già su un altopiano elevato, quindi il dislivello reale è meno impressionante di quanto sembri. La domanda \"quanto è alta\" nasconde in realtà più modi diversi di misurare."),
        ("La montagna più alta dalla base",
         "Il Mauna Kea, alle Hawaii, misurato dalla sua base sul fondo dell'oceano fino alla cima, supera i 10.000 metri: più dell'Everest. La maggior parte di esso è sommersa nell'acqua, quindi emerge \"solo\" per circa 4.200 metri. Dalla base al vertice, però, è la montagna più alta della Terra."),
        ("Il punto più vicino allo spazio",
         "C'è un terzo modo di vedere la cosa. La Terra non è una sfera perfetta: è schiacciata ai poli e rigonfia all'equatore. Per questo la cima del vulcano Chimborazo, in Ecuador, vicino all'equatore, è il punto della superficie terrestre più lontano dal centro del pianeta, e quindi il più vicino allo spazio, pur essendo molto più basso dell'Everest in metri sul mare."),
        ("Montagne che crescono",
         "Le montagne non sono immobili: l'Everest cresce di alcuni millimetri l'anno, perché la placca indiana continua a spingere contro quella asiatica. I terremoti possono invece abbassarne la quota di colpo. Le altezze che troviamo sui libri sono fotografie di un processo geologico ancora in corso, lento ma inarrestabile."),
        ("Cosa portarti a casa",
         "\"Qual è la montagna più alta?\" ha almeno tre risposte diverse a seconda di cosa intendiamo: sul mare vince l'Everest, dalla base il Mauna Kea, dal centro della Terra il Chimborazo. Un promemoria che anche le domande più semplici, in geografia, nascondono sfumature sorprendenti."),
       ]),

    mk("geografia", "geo-why-oceans-salty",
       "Perché il mare è salato e i fiumi no?",
       ["mare", "sale"],
       "Beviamo l'acqua dei fiumi ma non quella del mare. Eppure i fiumi finiscono nel mare. Da dove arriva tutto quel sale, e perché non se ne va?",
       "Il mare è salato perché i fiumi trasportano minerali erosi dalle rocce: l'acqua evapora e torna dolce, ma il sale resta e si accumula nel tempo.",
       IMG[2],
       [
        ("Un lento accumulo",
         "L'acqua piovana, leggermente acida, cade sulle rocce e ne scioglie piccole quantità di minerali, tra cui i sali. I fiumi raccolgono queste sostanze e le trasportano fino al mare. Ogni fiume porta pochissimo sale, ma il processo va avanti da miliardi di anni. Il mare è, in un certo senso, il grande contenitore dove tutto questo si è accumulato."),
        ("Perché i fiumi restano dolci",
         "Se i fiumi trasportano sale, perché la loro acqua non è salata? Perché scorrono: l'acqua è di passaggio, non si ferma abbastanza da concentrare i sali. La quantità che portano è minima rispetto al volume che scorre di continuo verso il mare. È come una tubatura che consegna il sale senza mai tenerlo."),
        ("La trappola dell'evaporazione",
         "Nel mare avviene la differenza cruciale. Il Sole fa evaporare l'acqua, che sale come vapore puro e ricade come pioggia dolce, alimentando di nuovo i fiumi. Ma il sale non evapora: resta indietro nel mare. Così, ciclo dopo ciclo, l'acqua se ne va e torna, mentre il sale si accumula sempre di più."),
        ("Non solo dai fiumi",
         "Una parte del sale arriva anche dal fondo degli oceani, dalle sorgenti idrotermali e dall'attività vulcanica sottomarina, che rilasciano minerali direttamente nell'acqua. Il mare è quindi salato per un doppio contributo: quello che scende dalla terraferma e quello che sale dalle profondità della crosta terrestre."),
        ("Mari più salati di altri",
         "Non tutti i mari sono uguali. Il Mar Morto è così salato da permettere di galleggiare senza sforzo, perché evapora tantissimo in un clima caldo e riceve poca acqua dolce. I mari in regioni fredde o alimentati da grandi fiumi sono meno salati. La salinità è un equilibrio delicato tra apporti d'acqua ed evaporazione."),
        ("Cosa portarti a casa",
         "Il sapore salato del mare è il risultato di miliardi di anni di erosione ed evaporazione: un gigantesco imbuto che raccoglie i minerali della terraferma e li trattiene. Ogni volta che assaggi l'acqua di mare, in fondo assaggi la lenta consumazione delle rocce di tutto il pianeta."),
       ]),

    mk("geografia", "geo-borders",
       "Perché i confini degli Stati hanno forme così strane?",
       ["confini", "Stati"],
       "Linee dritte nel deserto, curve improvvise lungo i fiumi, enclavi impossibili. Le forme degli Stati raccontano guerre, trattati e compromessi di secoli.",
       "I confini nascono da geografia, storia e potere: montagne e fiumi ne tracciano alcuni, ma molti sono linee artificiali decise a tavolino da trattati e imperi.",
       IMG[3],
       [
        ("Confini naturali",
         "Molti confini seguono elementi geografici evidenti: catene montuose, fiumi, coste. Sono barriere naturali facili da riconoscere e difendere. Le Alpi, i Pirenei, il Rio Grande hanno separato popoli e Stati per secoli. Questi confini tendono a essere stabili proprio perché la natura stessa segna la linea, senza bisogno di paletti."),
        ("Linee dritte artificiali",
         "In molte regioni, soprattutto in Africa e in America, i confini sono righe perfettamente dritte. Non seguono nulla di naturale: furono tracciati con il righello da potenze coloniali europee che si spartirono territori lontani, spesso senza conoscerli. Queste linee ignoravano popoli, lingue e culture, con conseguenze che pesano ancora oggi."),
        ("Confini che dividono popoli",
         "Quando un confine taglia in due un popolo, nascono tensioni durature. Comunità con la stessa lingua e tradizione si ritrovano in Stati diversi, o gruppi rivali costretti dentro lo stesso Paese. Molti conflitti contemporanei affondano le radici in confini disegnati a tavolino, senza tener conto di chi ci viveva davvero."),
        ("Enclavi e curiosità",
         "Esistono confini bizzarri: enclavi, cioè territori di uno Stato completamente circondati da un altro; villaggi tagliati in due da una linea di frontiera che passa dentro le case. Alcuni nascono da antichi trattati feudali mai aggiornati. Sono cicatrici della storia rimaste impresse sulla mappa, spesso fonte di aneddoti curiosi."),
        ("Confini che cambiano",
         "I confini non sono eterni: si spostano con guerre, indipendenze, unificazioni e accordi. Nell'ultimo secolo la mappa del mondo è cambiata continuamente, con la nascita e la scomparsa di decine di Stati. Ciò che oggi ci sembra ovvio e definitivo, tra qualche generazione potrebbe apparire molto diverso."),
        ("Cosa portarti a casa",
         "Ogni linea su una carta geografica è una storia condensata: di geografia, potere, accordi e conflitti. I confini sembrano dati di fatto, ma sono costruzioni umane, spesso arbitrarie. Leggerli con occhio critico significa capire che dietro ogni frontiera ci sono scelte, e non di rado ingiustizie, del passato."),
       ]),

    mk("geografia", "geo-why-deserts",
       "Perché i deserti si formano dove si formano?",
       ["deserti", "clima"],
       "Non solo sabbia rovente: esistono deserti gelidi e deserti costieri. La loro posizione sulla Terra non è casuale, ma segue regole precise del clima.",
       "I deserti nascono dove l'aria è secca: soprattutto lungo due fasce tropicali dove correnti atmosferiche discendenti impediscono la formazione di pioggia.",
       IMG[4],
       [
        ("Cosa è un deserto",
         "Un deserto non è definito dal caldo o dalla sabbia, ma dalla scarsità di precipitazioni: cade pochissima pioggia. Con questa definizione, anche l'Antartide è un deserto, il più grande del mondo, pur essendo ghiacciato. Il tratto comune è l'aridità: poca acqua disponibile, che rende difficile la vita per piante e animali."),
        ("Le fasce tropicali",
         "La maggior parte dei grandi deserti caldi si trova lungo due fasce, a circa 30 gradi a nord e a sud dell'equatore. Non è un caso: qui l'aria, che era salita calda e umida all'equatore scaricando pioggia, ridiscende ormai secca. Quest'aria discendente impedisce la formazione di nuvole e piogge, creando cinture aride tutt'intorno al globo."),
        ("L'effetto delle montagne",
         "Le catene montuose creano deserti \"d'ombra\". Quando l'aria umida sale lungo un versante, si raffredda e scarica pioggia; superata la cima, ridiscende secca sull'altro lato, lasciandolo arido. Molti deserti si trovano proprio dietro grandi montagne, protetti dalle piogge come da un muro. È il fenomeno dell'ombra pluviometrica."),
        ("Deserti costieri e freddi",
         "Esistono deserti anche lungo alcune coste, come l'Atacama in Cile, tra i luoghi più aridi della Terra: correnti oceaniche fredde raffreddano l'aria e bloccano la pioggia. E ci sono i deserti freddi dell'Asia centrale e dei poli, dove l'aria gelida trattiene pochissima umidità. Il caldo non è affatto un requisito."),
        ("Deserti che si muovono",
         "I deserti non sono immobili: si espandono e si restringono nei secoli, seguendo i cambiamenti climatici. Il Sahara, migliaia di anni fa, era una savana verde con laghi e animali. Oggi la desertificazione, spinta anche dalle attività umane, minaccia di trasformare in deserto terre un tempo fertili in varie parti del mondo."),
        ("Cosa portarti a casa",
         "La posizione dei deserti non è capriccio del caso, ma il risultato di correnti atmosferiche, montagne e oceani. Capirlo trasforma la mappa del mondo in una storia leggibile: dietro ogni distesa arida c'è una logica climatica precisa. E ci ricorda quanto sia sottile l'equilibrio tra una terra verde e una arida."),
       ]),

    mk("geografia", "geo-population",
       "Perché la gente vive ammassata in certi posti e non in altri?",
       ["popolazione", "città"],
       "Su una mappa notturna della Terra, alcune zone brillano di luci e altre sono buie. Miliardi di persone si concentrano su una piccola parte del pianeta. Perché?",
       "La popolazione si concentra dove ci sono acqua, terre fertili, clima mite e coste: la geografia fisica ha guidato per millenni dove gli esseri umani si stabiliscono.",
       IMG[0],
       [
        ("L'acqua prima di tutto",
         "Le grandi civiltà sono nate lungo i fiumi: Nilo, Tigri, Eufrate, Indo, Fiume Giallo. L'acqua serve per bere, coltivare, trasportare merci. Ancora oggi le densità di popolazione più alte si trovano vicino a fiumi, laghi e coste. Dove manca l'acqua, come nei grandi deserti, gli esseri umani restano pochi e sparsi."),
        ("Terre fertili",
         "Il suolo conta enormemente. Le pianure alluvionali, arricchite dai sedimenti dei fiumi, permettono agricoltura abbondante e quindi sostentano molte persone. Zone montuose, rocciose o ghiacciate producono poco cibo e ospitano popolazioni ridotte. La capacità di nutrire la gente ha sempre stabilito quante persone un territorio potesse reggere."),
        ("Il clima giusto",
         "Gli esseri umani prediligono climi temperati: né il gelo estremo dei poli né il caldo torrido dei deserti. Le fasce a clima mite, con stagioni gestibili, ospitano la maggioranza della popolazione mondiale. Il clima influenza cosa si può coltivare, quanta energia serve per sopravvivere e persino le malattie diffuse in una zona."),
        ("Il richiamo delle coste",
         "Le zone costiere sono densamente popolate: offrono pesca, commerci marittimi, porti e scambi con il mondo. Gran parte delle megalopoli si affaccia sul mare o su grandi vie d'acqua. Il mare è stato per secoli l'autostrada principale dell'umanità, e vivere vicino a un porto significava accesso a ricchezza e opportunità."),
        ("Storia e scelte umane",
         "Non tutto è geografia: anche storia, politica ed economia contano. Una città può crescere attorno a una miniera, a un incrocio commerciale o a una decisione politica. Le migrazioni verso i centri industriali hanno svuotato campagne e riempito metropoli. Oggi oltre metà dell'umanità vive in città, una tendenza in continua crescita."),
        ("Cosa portarti a casa",
         "La distribuzione degli esseri umani sul pianeta non è casuale: segue acqua, suolo, clima e coste, poi la storia. La mappa notturna della Terra, con le sue luci concentrate, è in fondo una mappa di dove la natura ha reso più facile vivere. La geografia, silenziosamente, ha plasmato dove siamo tutti noi."),
       ]),

    mk("geografia", "geo-map-lies",
       "Perché tutte le mappe del mondo 'mentono'?",
       ["mappe", "proiezioni"],
       "La Groenlandia sembra grande quanto l'Africa, ma è quattordici volte più piccola. Ogni mappa piatta del mondo contiene una distorsione inevitabile.",
       "È impossibile rappresentare fedelmente una sfera su un piano: ogni mappa deve sacrificare qualcosa tra forme, aree e distanze, distorcendo la realtà.",
       IMG[1],
       [
        ("Il problema della sfera",
         "La Terra è (quasi) una sfera; una mappa è piatta. Non esiste modo di appiattire una superficie sferica senza stirarla o strapparla da qualche parte. Prova a schiacciare una buccia d'arancia su un tavolo: si spacca e si deforma. Ogni mappa del mondo è un compromesso: per guadagnare in una qualità, ne perde un'altra."),
        ("La mappa che tutti conosciamo",
         "La proiezione più famosa, quella di Mercatore, è nata nel 1569 per la navigazione: mantiene corrette le direzioni, utilissimo per le rotte delle navi. Ma per farlo gonfia enormemente le zone vicine ai poli. Ecco perché la Groenlandia appare gigantesca e i Paesi tropicali sembrano più piccoli di quanto siano davvero."),
        ("Distorsioni con conseguenze",
         "Queste deformazioni non sono neutre. Ingrandire l'Europa e il Nord del mondo e rimpicciolire l'Africa e i Paesi equatoriali ha, secondo alcuni, influenzato per secoli la percezione dell'importanza relativa dei continenti. Una mappa non è mai solo tecnica: trasmette anche un punto di vista, spesso senza che ce ne accorgiamo."),
        ("Altre proiezioni, altri difetti",
         "Esistono decine di proiezioni alternative. Alcune mantengono corrette le aree ma distorcono le forme (i continenti appaiono \"schiacciati\"); altre cercano un equilibrio tra i vari errori. Non ne esiste una perfetta: la scelta dipende dallo scopo. Una mappa per navigare, una per studiare le superfici e una per la scuola possono essere tutte diverse."),
        ("Anche il centro è una scelta",
         "Perché mettiamo l'Europa al centro e il Nord in alto? Non c'è una legge fisica: nello spazio non esiste \"su\" e \"giù\". È una convenzione storica. Esistono mappe con il Sud in alto o centrate sul Pacifico, che ci spiazzano proprio perché rompono un'abitudine che credevamo naturale e oggettiva."),
        ("Cosa portarti a casa",
         "Nessuna mappa del mondo dice la verità completa: tutte mentono un po', perché devono. Saperlo ti rende un lettore di mappe più critico: ti chiedi cosa è stato distorto e perché. Dietro qualcosa di apparentemente neutro come una cartina si nascondono scelte tecniche, storiche e culturali."),
       ]),

    mk("geografia", "geo-rivers-civilization",
       "Perché le grandi città nascono quasi sempre vicino all'acqua?",
       ["fiumi", "città"],
       "Londra sul Tamigi, Il Cairo sul Nilo, Parigi sulla Senna. Guarda le metropoli del mondo: quasi tutte hanno un fiume o un mare accanto. Non è un caso.",
       "L'acqua ha offerto per millenni ciò che serve a una città: da bere, per irrigare, per trasportare merci e difendersi. I fiumi sono stati le prime autostrade.",
       IMG[2],
       [
        ("La linfa della vita",
         "Una città ha bisogno di enormi quantità d'acqua: per bere, cucinare, lavarsi. Prima degli acquedotti moderni, l'unico modo per garantirla a migliaia di persone era costruire vicino a una fonte affidabile. Un fiume o un lago erano la scelta ovvia. Senza acqua vicina, nessun insediamento poteva crescere oltre una certa dimensione."),
        ("Coltivare per sfamare",
         "Le pianure attraversate dai fiumi sono fertili: le piene depositano sedimenti ricchi di nutrienti. Il Nilo, con le sue inondazioni annuali, rese possibile la civiltà egizia. Un territorio capace di produrre cibo in abbondanza poteva sostenere una popolazione numerosa, liberando alcune persone dal lavoro nei campi per dedicarsi ad altro."),
        ("Le autostrade dell'antichità",
         "Prima delle strade asfaltate e dei treni, muovere merci pesanti via terra era lentissimo e costoso. Sull'acqua, invece, una barca poteva trasportare enormi carichi con poca fatica. I fiumi e i mari erano le grandi vie commerciali. Una città su un corso d'acqua navigabile diventava naturalmente un centro di scambi e ricchezza."),
        ("Difesa e potere",
         "Un fiume o il mare offrivano anche protezione: un ostacolo naturale contro gli invasori, un fossato già pronto. Molte città sorsero su isole fluviali o su promontori difesi dall'acqua. Controllare un guado o un porto significava controllare i commerci e i movimenti: un potere strategico enorme in mano a chi possedeva quel punto."),
        ("Il rovescio della medaglia",
         "Vivere vicino all'acqua ha però un prezzo: le alluvioni. Le stesse piene che portavano fertilità potevano distruggere case e raccolti. Molte civiltà svilupparono ingegneria idraulica, argini e canali proprio per domare i fiumi. Ancora oggi molte metropoli combattono contro il rischio di inondazioni, aggravato dai cambiamenti climatici."),
        ("Cosa portarti a casa",
         "Guardando una mappa delle grandi città, l'acqua racconta la loro origine: era vita, cibo, trasporto e difesa insieme. Anche nell'era degli acquedotti e degli aerei, quel legame antico è rimasto impresso nella geografia urbana. Le nostre metropoli sorgono spesso dove, millenni fa, scorreva la scelta più sensata."),
       ]),

    mk("geografia", "geo-plate-tectonics",
       "I continenti si muovono davvero?",
       ["continenti", "placche"],
       "Sembra assurdo, ma l'Africa e il Sudamerica una volta erano attaccati. I continenti viaggiano, lentissimamente, sotto i nostri piedi in questo istante.",
       "La superficie terrestre è divisa in placche che si muovono di pochi centimetri l'anno: il loro lento viaggio crea montagne, terremoti, vulcani e nuovi oceani.",
       IMG[3],
       [
        ("Un'intuizione geniale",
         "All'inizio del Novecento, lo scienziato Alfred Wegener notò che le coste dell'Africa e del Sudamerica combaciavano come i pezzi di un puzzle. Propose che un tempo i continenti fossero uniti in un unico supercontinente, chiamato Pangea, poi frammentatosi. L'idea fu derisa per decenni: sembrava impossibile che masse così enormi potessero spostarsi."),
        ("Le prove nascoste",
         "Wegener aveva ragione. Fossili identici di piante e animali si trovano su continenti oggi separati da oceani: impossibile, se non fossero stati uniti. Anche le formazioni rocciose combaciano tra terre lontanissime. Queste tracce, sparse in tutto il mondo, raccontavano una storia comune di continenti un tempo abbracciati."),
        ("Il motore sotto i piedi",
         "Il meccanismo fu compreso più tardi: la crosta terrestre è divisa in grandi placche che galleggiano su uno strato di roccia calda e semifluida. Il calore interno della Terra genera lenti moti convettivi che trascinano le placche. Si muovono di pochi centimetri l'anno, più o meno quanto crescono le nostre unghie, ma su tempi geologici percorrono migliaia di chilometri."),
        ("Dove le placche si incontrano",
         "Ai bordi delle placche succede quasi tutto ciò che è drammatico in geologia. Dove si scontrano, si sollevano montagne come l'Himalaya, ancora in crescita. Dove una scivola sotto l'altra, nascono vulcani e terremoti violenti. Dove si allontanano, il magma risale e crea nuova crosta, allargando gli oceani centimetro dopo centimetro."),
        ("Il futuro della mappa",
         "Il movimento continua. Tra decine di milioni di anni l'Africa potrebbe spaccarsi lungo la Rift Valley, l'Atlantico allargarsi ancora, il Mediterraneo chiudersi mentre l'Africa preme sull'Europa. Gli scienziati ipotizzano che i continenti torneranno a riunirsi in un nuovo supercontinente, lontanissimo nel tempo. La mappa che conosciamo è solo un fotogramma."),
        ("Cosa portarti a casa",
         "Il suolo che ci sembra l'immagine stessa della stabilità è in realtà in perenne, lentissimo movimento. Montagne, oceani e terremoti sono le manifestazioni di questo viaggio invisibile. La deriva dei continenti ci ricorda che anche le cose che diamo per più immutabili, su scala abbastanza grande, cambiano di continuo."),
       ]),

    mk("geografia", "geo-why-travel",
       "Perché viaggiare ci cambia davvero?",
       ["viaggio", "mente"],
       "Non è solo relax o foto da mostrare. Viaggiare, quando lo facciamo bene, lascia un segno profondo su come pensiamo e vediamo il mondo. Ecco perché.",
       "Viaggiare ci espone a novità e prospettive diverse: sfida le nostre abitudini mentali, aumenta empatia e creatività e ci fa vedere la nostra vita da fuori.",
       IMG[4],
       [
        ("Il cervello ama la novità",
         "Quando siamo in un luogo nuovo, il cervello è più attento e presente: tutto è da decifrare, nulla è automatico. Questa attenzione intensa fa sì che i ricordi di viaggio siano spesso più vividi della routine. Uscire dagli schemi abituali risveglia una curiosità che nella vita di sempre tende ad addormentarsi."),
        ("Rompere gli automatismi",
         "A casa viviamo in gran parte con il pilota automatico: stessi percorsi, stessi gesti. Viaggiare ci obbliga a risolvere piccoli problemi nuovi di continuo: orientarsi, comunicare, adattarsi. Questa ginnastica mentale rende più flessibili e allena a gestire l'imprevisto, una capacità utile ben oltre le vacanze."),
        ("Vedere altre prospettive",
         "Incontrare culture diverse mostra che il nostro modo di vivere non è l'unico possibile né \"quello giusto per natura\". Abitudini, cibi, valori che credevamo universali si rivelano scelte tra tante. Questo allarga la mente e nutre l'empatia: capiamo che dietro comportamenti diversi ci sono ragioni, storie e logiche differenti dalle nostre."),
        ("Guardare la propria vita da fuori",
         "La distanza fisica crea distanza mentale. Lontano dai problemi quotidiani, spesso li vediamo con più chiarezza: cosa conta davvero, cosa vogliamo cambiare. Molte persone prendono decisioni importanti proprio in viaggio, non per magia del luogo, ma perché finalmente hanno spazio per pensare senza il rumore di sempre."),
        ("Non basta spostarsi",
         "Attenzione però: viaggiare non cambia automaticamente nessuno. Chi resta chiuso, evita ogni contatto e cerca ovunque le comodità di casa torna spesso identico a com'era partito. Il cambiamento nasce dall'apertura: parlare con la gente, provare l'ignoto, accettare il disorientamento. È l'atteggiamento, più della destinazione, a fare la differenza."),
        ("Cosa portarti a casa",
         "Viaggiare ci cambia quando ci lasciamo davvero attraversare da ciò che incontriamo. Non servono mete esotiche: anche esplorare con occhi nuovi ciò che è vicino può avere lo stesso effetto. Il vero souvenir di un buon viaggio non è nella valigia, ma nel modo leggermente diverso in cui, tornati, guardiamo il mondo e noi stessi."),
       ]),
]
