"""PAUSE v5 — ampliamento catalogo (parte B): Natura, Animali, Storia.
5 curiosità + 5 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ NATURA ------------------------------
    mk("natura", "v5-seme-germoglia",
       "Come fa un seme a sapere quando germogliare?", ["seme", "germogliare"],
       "Può restare nel terreno per anni, secco e apparentemente morto. Poi una primavera decide che è il momento. Chi glielo dice?",
       "Il seme misura acqua, temperatura, luce e persino la durata delle notti. Solo quando i segnali coincidono sblocca gli ormoni che avviano la crescita. Alcuni aspettano il fuoco o un passaggio nell'intestino di un animale.",
       "",
       [
        ("Una capsula del tempo",
         "Dentro il guscio c'è un embrione di pianta e una scorta di cibo, il tutto disidratato al 5-10% di acqua. In questo stato il metabolismo è quasi zero: semi di loto vecchi di 1.300 anni hanno germogliato, e un seme di palma da dattero di 2.000 anni, trovato a Masada, è oggi un albero adulto."),
        ("Il primo segnale è l'acqua",
         "Quando il terreno si inumidisce, il seme assorbe acqua e si gonfia, spaccando il guscio. Ma non basta: se germogliasse a ogni pioggia d'autunno, il gelo lo ucciderebbe. Molti semi hanno un blocco chimico, l'acido abscissico, che va smantellato prima."),
        ("Contare le settimane di freddo",
         "Molti semi delle zone temperate devono passare settimane sotto i 5 gradi prima di poter germogliare: è la vernalizzazione. Il freddo degrada lentamente l'ormone che li blocca. Così il seme 'sa' che l'inverno è passato davvero e non è solo una giornata tiepida di novembre. I giardinieri lo imitano mettendo i semi in frigo."),
        ("Chi aspetta il fuoco",
         "Alcuni pini e molte piante australiane rilasciano o attivano i semi solo con il calore di un incendio: dopo il fuoco c'è luce, spazio e cenere ricca di nutrienti. Altri semi hanno bisogno degli acidi dello stomaco di un uccello per ammorbidire il guscio. Ogni specie ha sintonizzato il proprio calendario su ciò che le dà più probabilità di sopravvivere."),
       ]),
    mk("natura", "v5-neve-bianca",
       "Perché la neve è bianca se il ghiaccio è trasparente?", ["neve", "bianca"],
       "Un cubetto di ghiaccio lascia passare la luce. Un fiocco di neve è fatto della stessa cosa, eppure un prato nevicato abbaglia. Il segreto è nell'aria.",
       "Ogni cristallo di neve è trasparente, ma un manto è fatto di miliardi di cristalli con aria in mezzo. La luce rimbalza da una superficie all'altra migliaia di volte e ne esce in tutte le direzioni, con tutti i colori insieme: bianco.",
       "",
       [
        ("Il ghiaccio non assorbe quasi nulla",
         "Il ghiaccio puro lascia passare tutti i colori quasi alla stessa maniera: per questo è trasparente, come il vetro. Assorbe solo un pochino di rosso, motivo per cui il ghiaccio molto spesso, nei ghiacciai e negli iceberg, appare azzurro."),
        ("Miliardi di piccoli specchi",
         "Un manto nevoso è composto da cristalli minuscoli separati da aria. Ogni volta che la luce passa da aria a ghiaccio o viceversa, una parte viene riflessa. In un centimetro di neve avvengono migliaia di riflessi in direzioni casuali. La luce entra e ne esce dispersa ovunque, senza che nessun colore venga sottratto: la somma di tutti i colori è il bianco."),
        ("Lo stesso trucco dello zucchero",
         "Un cristallo di zucchero è trasparente, la zolletta è bianca. Il sale, il vetro macinato, la schiuma del mare: tutti materiali trasparenti che diventano bianchi quando sono ridotti in frammenti con aria in mezzo. Il bianco non è quasi mai un colore della materia, è un colore della struttura."),
        ("Perché la neve vecchia è grigia",
         "Con il tempo i cristalli si fondono in grani più grandi, l'aria diminuisce e i riflessi calano: la neve diventa traslucida e poi ghiaccio. Polvere e fuliggine assorbono luce e la scuriscono. La neve fresca riflette fino al 90% della luce, ed è il motivo per cui in montagna ci si scotta anche a febbraio e la neve pulita rallenta il riscaldamento del pianeta."),
       ]),
    mk("natura", "v5-geyser",
       "Come funziona un geyser?", ["geyser"],
       "Ogni novanta minuti, con la puntualità di un treno, una colonna d'acqua bollente sale a quaranta metri. Sotto c'è una pentola a pressione naturale grande come un palazzo.",
       "Acqua di pioggia si infiltra fino a rocce riscaldate dal magma, si surriscalda oltre 100 gradi per la pressione della colonna sopra di lei, e quando si forma la prima bolla il sistema esplode in un getto. Poi si ricarica.",
       "",
       [
        ("Tre ingredienti rari",
         "Servono acqua abbondante, una fonte di calore vicina alla superficie e un sistema di fessure a forma di collo di bottiglia. La combinazione è così rara che i geyser sono circa mille in tutto il mondo, e metà si trovano a Yellowstone, sopra un antico supervulcano."),
        ("Acqua a 200 gradi che non bolle",
         "La pioggia scende per centinaia di metri e incontra rocce roventi. Sul fondo, il peso della colonna d'acqua alza la pressione e quindi il punto di ebollizione: l'acqua raggiunge i 200 gradi restando liquida. È esattamente il principio della pentola a pressione, con il tappo fatto di acqua."),
        ("La catena che esplode",
         "Quando una parte dell'acqua in alto si scalda a sufficienza, forma le prime bolle che spingono un po' d'acqua fuori dalla bocca. Il peso sopra diminuisce, la pressione cala di colpo e l'acqua surriscaldata sottostante bolle tutta insieme, espandendosi 1.500 volte in vapore. Il getto svuota il condotto in pochi minuti."),
        ("La ricarica e la puntualità",
         "Poi il serbatoio si riempie di nuovo e il ciclo ricomincia. Old Faithful, a Yellowstone, erutta ogni 60-110 minuti da quando è stato scoperto nel 1870. I terremoti possono cambiare le fessure e alterare il ritmo: alcuni geyser si sono spenti per sempre dopo una scossa, altri sono nati."),
       ]),
    mk("natura", "v5-fiori-notte",
       "Perché alcuni fiori si chiudono di notte?", ["fiori", "notte"],
       "Tulipani, margherite e ninfee la sera abbassano le serrande. Non dormono: eseguono una strategia con un orologio interno preciso al minuto.",
       "I fiori si chiudono per proteggere polline e nettare da freddo, rugiada e insetti inutili, e riaprono quando gli impollinatori giusti sono attivi. Il movimento è guidato da un orologio interno che funziona anche al buio.",
       "",
       [
        ("Il polline è prezioso",
         "Produrre polline e nettare costa energia. Di notte, quando api e farfalle diurne riposano, un fiore aperto spreca profumo, si bagna di rugiada che rovina il polline e rischia il gelo. Chiudersi significa proteggere l'investimento e riaprirlo al mattino, fresco e attraente."),
        ("Come si muove senza muscoli",
         "Il movimento nasce dall'acqua: le cellule alla base dei petali si gonfiano o si svuotano, e la parte che cresce più in fretta fa piegare il petalo. Nei tulipani, l'interno del petalo cresce con il caldo e lo apre; con il freddo cresce l'esterno e lo chiude. È una crescita lentissima ma ripetuta ogni giorno."),
        ("L'orologio che non guarda il Sole",
         "Nel 1729 l'astronomo de Mairan mise una mimosa in un armadio buio: continuava ad aprire e chiudere le foglie ogni 24 ore. Le piante hanno un orologio interno, lo stesso tipo di ritmo circadiano che abbiamo noi. La luce serve solo a rimetterlo in orario ogni mattina."),
        ("I fiori della notte",
         "Altri fanno il contrario: la bella di notte, il gelsomino notturno e molti cactus si aprono al tramonto, bianchi e profumatissimi per farsi trovare da falene e pipistrelli. Linneo propose nel 1751 un orologio floreale: un'aiuola con specie che si aprono a ore diverse, per leggere l'ora guardando i fiori."),
       ]),
    mk("natura", "v5-odore-pioggia",
       "Da dove viene l'odore della pioggia?", ["odore", "pioggia"],
       "Le prime gocce sull'asfalto caldo, e l'aria cambia profumo. Quel profumo ha un nome, petrichor, e nasce dai batteri del terreno.",
       "Il profumo di pioggia è geosmina, una molecola prodotta da batteri del suolo, liberata nell'aria dalle gocce che colpiscono il terreno secco e la sollevano come minuscoli aerosol. Il naso umano la sente a concentrazioni infinitesimali.",
       "",
       [
        ("Un nome inventato nel 1964",
         "Due ricercatori australiani lo chiamarono petrichor, dal greco 'pietra' e 'sangue degli dei'. Studiando rocce e argille scoprirono che il profumo non veniva dalla pioggia ma da ciò che la pioggia solleva dal terreno: oli vegetali accumulati nella stagione secca e una molecola in particolare."),
        ("La geosmina",
         "È prodotta dagli streptomiceti, batteri del suolo che la rilasciano quando producono spore. Il naso umano la percepisce a 5 parti per trilione: una goccia in una piscina olimpica. È lo stesso odore della terra appena vangata, delle barbabietole e, quando finisce nell'acqua del rubinetto, del sapore 'di terra' che a volte sentiamo."),
        ("Le gocce che diventano spray",
         "Nel 2015 il MIT ha filmato con telecamere ad alta velocità cosa succede quando una goccia colpisce terreno poroso: intrappola bollicine d'aria che risalgono e scoppiano, lanciando nell'aria una nebbia di goccioline minuscole. È così che la geosmina si stacca dal suolo e arriva al naso. Piogge leggere su terreno caldo producono più aerosol di un temporale."),
        ("Perché ci piace",
         "Una teoria: i nostri antenati, come i cammelli oggi, trovavano l'acqua seguendo quell'odore, e il cervello lo ha collegato a qualcosa di buono. Gli streptomiceti, dal canto loro, la producono per attirare piccoli artropodi che ne disperdono le spore. Il profumo che ami è un annuncio pubblicitario batterico."),
       ]),

    # ------------------------------ ANIMALI ------------------------------
    mk("animali", "v5-colibri",
       "Il colibrì: un cuore che batte 1.200 volte al minuto", ["colibrì", "1.200"],
       "Pesa quanto una moneta, vola all'indietro, e per non morire di fame ogni notte va in una specie di coma. È l'animale a sangue caldo più estremo che esista.",
       "Il colibrì batte le ali fino a 80 volte al secondo e ha il metabolismo più alto tra i vertebrati: deve mangiare metà del suo peso in nettare al giorno. Di notte abbassa la temperatura di 20 gradi per sopravvivere fino all'alba.",
       "",
       [
        ("Un elicottero con le piume",
         "Le ali del colibrì ruotano alla spalla e disegnano un otto nell'aria: generano sostentamento sia in avanti che indietro. È l'unico uccello capace di restare fermo in aria a piacimento e di volare a marcia indietro. Il ronzio che dà loro il nome inglese, hummingbird, è il suono di 50-80 battiti al secondo."),
        ("Una fornace da mantenere",
         "Il cuore arriva a 1.260 battiti al minuto in volo, il respiro a 250 al minuto. In proporzione al peso, un colibrì consuma energia come un essere umano che dovesse mangiare 150 chili di cibo al giorno. Visita fino a 2.000 fiori al giorno e ricorda quali ha già svuotato e quanto tempo impiegano a riempirsi."),
        ("La notte è il problema",
         "Senza mangiare per otto ore un colibrì morirebbe. La soluzione è il torpore: la temperatura corporea scende da 40 a 18 gradi, il cuore rallenta a 50 battiti, il consumo cala del 95%. All'alba si riscalda in venti minuti tremando, e riparte a cercare fiori."),
        ("Una migrazione impossibile",
         "Il colibrì golarubino, tre grammi, attraversa il Golfo del Messico senza scalo: 800 chilometri sul mare, venti ore di volo. Prima di partire raddoppia il peso in grasso. È come se un essere umano corresse una maratona ogni ora per un giorno intero, senza bere."),
       ]),
    mk("animali", "v5-gatto-piedi",
       "Perché i gatti atterrano sempre in piedi?", ["gatti", "in piedi"],
       "Lasciato cadere a pancia in su, in meno di un secondo si è rigirato. Sembra violare la fisica: come si ruota in aria senza appoggiarsi a niente?",
       "Il gatto piega la schiena e ruota la parte anteriore e quella posteriore in direzioni diverse, cambiando la forma del corpo per non violare la conservazione del momento angolare. Servono 30 centimetri di caduta e un orecchio interno velocissimo.",
       "",
       [
        ("Il problema che ha confuso i fisici",
         "Un corpo che cade senza ruotare non può cominciare a ruotare da solo: il momento angolare deve conservarsi. Eppure il gatto lo fa. Nel 1894 il fisico Marey lo filmò con una camera a 60 fotogrammi al secondo e scoprì il trucco: il gatto non ruota tutto insieme."),
        ("Due metà che girano al contrario",
         "Il gatto piega la colonna a metà. Ritrae le zampe anteriori e stende quelle posteriori: la metà davanti, più compatta, ruota molto; quella dietro, allargata, ruota poco in direzione opposta. Poi inverte: stende le anteriori, ritrae le posteriori e ruota la metà dietro. Somma zero per la fisica, gatto in piedi per il gatto."),
        ("Un giroscopio nelle orecchie",
         "Il riflesso parte dall'orecchio interno, che percepisce l'orientamento in millisecondi, e dagli occhi. Per completare la manovra servono circa 30 centimetri di caduta. Sotto quell'altezza il gatto può non farcela: le cadute dal divano fanno più danni di quanto si creda."),
        ("Il paradosso dei grattacieli",
         "Uno studio veterinario di New York sui gatti caduti da palazzi trovò che quelli precipitati da oltre sette piani avevano meno fratture di quelli caduti da meno. Raggiunta la velocità massima, circa 100 km/h, il gatto smette di sentire l'accelerazione, si rilassa e si allarga come uno scoiattolo volante, frenando e distribuendo l'impatto."),
       ]),
    mk("animali", "v5-formiche-capo",
       "Le formiche non hanno un capo (e la regina non comanda)", ["formiche", "capo"],
       "Milioni di individui costruiscono città, coltivano funghi e fanno guerre organizzate. Nessuno dà ordini. La regina, in realtà, è solo una macchina per fare uova.",
       "Le colonie funzionano per regole semplici seguite da ogni formica, come seguire e depositare tracce di odore. Dalla somma di comportamenti locali emerge un'intelligenza collettiva senza nessuno che progetti o decida.",
       "",
       [
        ("Una regina senza corona",
         "La regina non ha idea di cosa succeda nel formicaio. Il suo lavoro è deporre uova, migliaia al giorno in alcune specie, per anni. Non dà istruzioni: le operaie decidono quanto nutrirla e persino se sostituirla. Il nome le fu dato da osservatori umani che davano per scontata una gerarchia."),
        ("Segui l'odore",
         "Una formica che trova cibo torna al nido lasciando una scia di feromoni. Altre la seguono e la rinforzano; la scia verso la fonte più vicina si rinforza più in fretta perché viene percorsa più volte. Senza nessuna mappa, la colonia trova il percorso più breve. Gli informatici copiano questo algoritmo per instradare il traffico internet."),
        ("Il ruolo dipende dall'incontro",
         "Ogni formica cambia mestiere in base a quante compagne incontra e cosa stanno facendo. Se incrocia troppe foraggiatrici, resta a casa; se ne incontra poche, esce. Il numero di foraggiatrici si regola da solo, come un termostato. Le formiche del deserto Cataglyphis decidono in questo modo ogni mattina quante uscire."),
        ("Ciò che nessuna formica sa fare",
         "Nessuna singola formica sa costruire un nido con canali di ventilazione, né coltivare funghi, né formare un ponte vivente. Lo fa la colonia. I biologi la chiamano superorganismo: un'entità con un metabolismo, una temperatura interna e una durata di vita, il cui cervello è distribuito su un milione di corpi."),
       ]),
    mk("animali", "v5-camaleonte",
       "Il camaleonte non cambia colore per nascondersi", ["camaleonte"],
       "È la leggenda più diffusa del regno animale: si mimetizza con lo sfondo. In realtà cambia colore per parlare, per litigare e per regolare la temperatura. E lo fa con dei cristalli.",
       "I camaleonti cambiano colore soprattutto per comunicare emozioni e stato sociale e per scaldarsi o raffreddarsi. Il meccanismo non usa pigmenti ma nanocristalli nella pelle che, allargandosi, riflettono luce di colori diversi.",
       "",
       [
        ("Il colore di riposo è già mimetico",
         "Il verde o il marrone di base del camaleonte lo nasconde già bene tra le foglie. I cambiamenti spettacolari, giallo brillante, arancione, strisce nere, lo rendono più visibile, non meno. Succedono quando due maschi si incontrano, quando corteggia una femmina o quando è stressato."),
        ("Cristalli che si allargano",
         "Nel 2015 ricercatori di Ginevra hanno scoperto il meccanismo: nella pelle c'è uno strato di cellule piene di nanocristalli di guanina disposti in reticolo. Quando il camaleonte è calmo il reticolo è stretto e riflette il blu, che con il pigmento giallo dà verde. Quando si eccita le cellule si allargano, il reticolo si distende e riflette giallo, arancione, rosso."),
        ("Un termostato sulla pelle",
         "Un secondo strato di cristalli più profondo riflette gli infrarossi. Al mattino freddo il camaleonte si scurisce per assorbire più calore; nel caldo di mezzogiorno si schiarisce. Il colore è anche un sistema di climatizzazione per un animale che non produce calore proprio."),
        ("Chi si mimetizza davvero",
         "Il vero campione del travestimento è il polpo, che imita in meno di un secondo colore, motivo e persino la rugosità di una roccia grazie a sacche di pigmento controllate dai nervi. Il camaleonte è lento, richiede secondi o minuti, e non guarda lo sfondo: guarda gli altri camaleonti."),
       ]),
    mk("animali", "v5-delfini-nome",
       "I delfini si chiamano per nome", ["delfini", "nome"],
       "Ogni delfino inventa da cucciolo un fischio che è solo suo. Gli altri lo imparano e lo usano per chiamarlo. Non è un modo di dire: è un nome.",
       "Ogni tursiope sviluppa nel primo anno un fischio-firma unico. Gli altri delfini lo imitano per richiamare proprio quell'individuo, e lo ricordano per oltre vent'anni: la memoria sociale più lunga documentata fuori dalla specie umana.",
       "",
       [
        ("Il fischio-firma",
         "Nei primi mesi ogni cucciolo di tursiope compone un fischio con un profilo di frequenza tutto suo, diverso da quello della madre e dei compagni. Lo userà per tutta la vita per dire 'sono io, sono qui'. Nell'acqua torbida, dove vedere è difficile, è l'equivalente di annunciarsi entrando in una stanza."),
        ("Copiare il fischio dell'altro",
         "Nel 2013 ricercatori scozzesi hanno registrato i fischi-firma di delfini selvatici, li hanno riprodotti con un altoparlante sott'acqua e hanno osservato: solo il delfino a cui il fischio apparteneva rispondeva, chiamando a sua volta. Quando i delfini imitano il fischio di un compagno, stanno chiamando quello specifico individuo."),
        ("Vent'anni dopo",
         "In un acquario della Florida, delfini separati da oltre venti anni hanno riconosciuto il fischio del vecchio compagno di vasca, avvicinandosi all'altoparlante. Ricordare un nome per due decenni, senza sentirlo mai nel frattempo, supera qualsiasi altra memoria sociale nota negli animali."),
        ("Non è ancora una lingua",
         "Un nome non fa un vocabolario. I delfini hanno anche clic per l'ecolocalizzazione e altri fischi legati a emozioni e attività, ma non c'è prova di una grammatica. Eppure dare un nome a sé stessi e agli altri era considerato, fino a pochi anni fa, qualcosa di esclusivamente umano."),
       ]),

    # ------------------------------ STORIA ------------------------------
    mk("storia", "v5-dieci-giorni-persi",
       "Nel 1582 sparirono dieci giorni dal calendario", ["dieci giorni"],
       "Giovedì 4 ottobre 1582. Il giorno dopo era venerdì 15 ottobre. Nessuno dormì per undici giorni: fu un errore di calcolo vecchio di 1.600 anni che andava corretto.",
       "Il calendario giuliano sbagliava di 11 minuti l'anno; in sedici secoli si era accumulato un ritardo di 10 giorni e la Pasqua scivolava verso l'estate. Papa Gregorio XIII li cancellò e cambiò la regola degli anni bisestili.",
       "",
       [
        ("Undici minuti l'anno",
         "Giulio Cesare nel 46 a.C. aveva fissato l'anno a 365 giorni e 6 ore, con un bisestile ogni 4 anni. Ma l'anno vero dura 365 giorni, 5 ore, 48 minuti e 45 secondi. Undici minuti in più sembrano niente, eppure fanno un giorno ogni 128 anni. Nel Cinquecento l'equinozio di primavera cadeva l'11 marzo invece del 21."),
        ("Il problema era la Pasqua",
         "La Pasqua si calcola dalla luna piena dopo l'equinozio di primavera. Se la data dell'equinozio scivola, la Pasqua finisce fuori stagione. Per la Chiesa era intollerabile. Il papa Gregorio XIII incaricò astronomi e matematici, tra cui il calabrese Luigi Lilio, di risolvere il problema."),
        ("Il taglio e la nuova regola",
         "La soluzione: saltare dieci giorni per riportare l'equinozio al 21 marzo, e correggere la regola. Gli anni secolari, come 1700, 1800, 1900, non sono più bisestili, tranne quelli divisibili per 400: il 2000 lo è stato, il 2100 non lo sarà. Così l'errore si riduce a un giorno ogni 3.300 anni."),
        ("Un'Europa con due date",
         "Solo i paesi cattolici adottarono subito la riforma. L'Inghilterra aspettò fino al 1752, quando saltò 11 giorni tra proteste popolari. La Russia passò al gregoriano solo nel 1918: la Rivoluzione d'Ottobre, secondo il nostro calendario, avvenne a novembre. Per due secoli una lettera da Roma a Londra arrivava, sulla carta, prima di essere spedita."),
       ]),
    mk("storia", "v5-napoleone-basso",
       "Napoleone non era basso", ["Napoleone", "basso"],
       "Il 'complesso di Napoleone' è entrato nel linguaggio comune. Ma l'imperatore era alto quanto la media dei francesi dell'epoca, o più. L'equivoco nasce da un'unità di misura e dalla propaganda inglese.",
       "Napoleone misurava circa 1,68-1,70 metri, sopra la media dell'epoca. La confusione nasce dal 'piede francese', più lungo di quello inglese, e dalle caricature britanniche che lo rimpicciolirono per ridicolizzarlo.",
       "",
       [
        ("Cinque piedi e due pollici",
         "All'autopsia, nel 1821, il suo medico registrò un'altezza di 5 piedi e 2 pollici. In unità inglesi sarebbero 1,57 metri: un uomo basso. Ma il medico era francese e usava il piede francese, circa il 6,6% più lungo. Convertito correttamente: quasi 1,69 metri."),
        ("La media dell'epoca",
         "Il francese medio della sua generazione misurava circa 1,65 metri. Napoleone era quindi nella norma o leggermente sopra. Il soprannome 'piccolo caporale' era affettuoso e nasceva dalla familiarità con i soldati, non dalla statura."),
        ("La propaganda che ha vinto",
         "Il caricaturista inglese James Gillray lo disegnò per anni come un ometto isterico con un cappello enorme, 'Little Boney'. Le vignette circolavano in tutta Europa e Napoleone stesso disse che Gillray gli aveva fatto più danni di dieci generali. Anche la guardia imperiale, selezionata tra uomini altissimi, lo faceva sembrare piccolo al confronto."),
        ("Un mito che resiste",
         "Nel 1926 lo psicologo Alfred Adler descrisse il bisogno di compensare un senso di inferiorità e la cultura popolare gli attaccò il nome di Napoleone. Il complesso esiste, l'esempio no. Il cappello e la mano nel gilet, entrambi veri, sono bastati a fissare per sempre un'immagine sbagliata."),
       ]),
    mk("storia", "v5-anno-senza-estate",
       "Il 1816, l'anno senza estate", ["senza estate"],
       "Neve a giugno in New England, raccolti distrutti in Europa, carestie in Cina. La causa era un vulcano indonesiano di cui nessuno in Occidente aveva sentito parlare.",
       "Nell'aprile 1815 il vulcano Tambora eruttò con la più grande esplosione degli ultimi mille anni, lanciando nella stratosfera aerosol che oscurarono il Sole per un anno. Il raffreddamento globale portò carestie, migrazioni e, per caso, Frankenstein.",
       "",
       [
        ("Un'esplosione sentita a 2.000 chilometri",
         "Il Tambora, sull'isola di Sumbawa, perse 1.400 metri di altezza in pochi giorni. Il boato fu udito a Sumatra, l'isola fu sepolta sotto la cenere e circa 90.000 persone morirono nell'immediato. Circa 100 chilometri cubi di roccia finirono in aria, e decine di milioni di tonnellate di zolfo nella stratosfera."),
        ("Un velo intorno al pianeta",
         "L'anidride solforosa diventò goccioline di acido solforico che si diffusero su tutto il globo, riflettendo la luce del Sole. La temperatura media dell'emisfero nord calò di quasi un grado. Sembra poco, ma bastò a spostare le stagioni: gelate a luglio, piogge incessanti, tramonti rosso sangue che i pittori come Turner riprodussero senza saperne il motivo."),
        ("Fame e migrazioni",
         "In Europa il raccolto del 1816 fallì; i prezzi del grano raddoppiarono e in Svizzera si mangiarono muschio e gatti. Decine di migliaia di persone emigrarono dalla Germania verso l'America e dalla Nuova Inghilterra verso l'Ovest. In India il monsone impazzito favorì una nuova varietà di colera che si diffuse nel mondo."),
        ("Il mostro nato dalla pioggia",
         "Sul lago di Ginevra, un gruppo di amici inglesi bloccati in casa dal maltempo si sfidò a scrivere storie di paura. La diciottenne Mary Shelley scrisse Frankenstein; il medico John Polidori Il vampiro, antenato di Dracula. E in Germania, la carestia che rese i cavalli troppo costosi spinse Karl Drais a inventare la bicicletta."),
       ]),
    mk("storia", "v5-quarantena-venezia",
       "La quarantena fu inventata a Venezia, e durava davvero quaranta giorni", ["quarantena", "Venezia"],
       "Una parola che abbiamo imparato a conoscere bene nasce nelle lagune del Trecento, quando nessuno sapeva cosa fosse un batterio ma tutti avevano capito una cosa: il contagio viaggiava con le navi.",
       "Dopo la peste nera del 1348, le repubbliche marinare imposero alle navi sospette di attendere isolate prima di sbarcare: 30 giorni a Ragusa, poi 40 a Venezia, da cui il nome. Venezia costruì i primi lazzaretti del mondo.",
       "",
       [
        ("Trenta giorni a Ragusa",
         "La prima legge scritta risale al 1377 a Ragusa, l'attuale Dubrovnik, allora sotto influenza veneziana: chi arrivava da zone infette doveva restare un mese in un luogo isolato prima di entrare in città. Il concetto di incubazione non esisteva, ma l'osservazione era corretta: chi si ammalava lo faceva entro poche settimane."),
        ("Perché proprio quaranta",
         "Venezia allungò il periodo a quaranta giorni, quarantena in dialetto. Il numero aveva un peso simbolico: i quaranta giorni di Cristo nel deserto, del diluvio, della Quaresima. E medicalmente era prudente: copriva abbondantemente l'incubazione della peste, che è di 2-7 giorni, più il decorso della malattia."),
        ("Le prime isole-ospedale",
         "Nel 1423 Venezia trasformò l'isola di Santa Maria di Nazareth in un ospedale per appestati: da Nazareth, storpiato, nasce la parola lazzaretto. Nel 1468 aggiunse il Lazzaretto Nuovo per le quarantene preventive di merci e persone sane. Le merci venivano arieggiate, i tessuti fumigati con erbe: inutile contro il batterio, ma efficace contro le pulci che lo portavano."),
        ("Un sistema copiato in tutto il Mediterraneo",
         "Genova, Marsiglia, Malta costruirono i propri lazzaretti sul modello veneziano. Venezia creò anche i Provveditori alla Sanità, il primo ufficio pubblico di salute con poteri di polizia, e i passaporti sanitari che certificavano la provenienza da porti puliti. Il sistema restò in uso per quattro secoli, fino alla scoperta dei microbi."),
       ]),
    mk("storia", "v5-primo-sciopero",
       "Il primo sciopero della storia lo fecero gli operai delle tombe egizie", ["sciopero", "egizie"],
       "Nel 1159 a.C., sotto Ramesse III, gli artigiani che scavavano le tombe dei faraoni incrociarono le braccia. Il motivo: gli stipendi in grano erano in ritardo di 18 giorni.",
       "Un papiro conservato a Torino racconta la protesta degli operai di Deir el-Medina: si sedettero davanti ai templi, negoziarono con gli scribi e ottennero le razioni arretrate. È la prima azione sindacale documentata.",
       "",
       [
        ("Un villaggio di specialisti",
         "A Deir el-Medina, vicino alla Valle dei Re, vivevano gli scalpellini, i disegnatori e i pittori che costruivano le tombe reali. Erano operai qualificati e alfabetizzati, pagati in grano, birra, pesce e verdure con cadenza mensile. Non erano schiavi: le piramidi e le tombe furono costruite da lavoratori stipendiati."),
        ("Le razioni non arrivano",
         "Nel 29esimo anno di Ramesse III l'Egitto era in difficoltà economica e le consegne di grano cominciarono a saltare. Dopo 18 giorni di ritardo, gli operai superarono i muri del cantiere e scesero verso i templi funerari, sedendosi sul retro: 'Abbiamo fame', dissero agli scribi, 'sono passati 18 giorni del mese'."),
        ("La trattativa",
         "Gli scribi corsero a riferire, distribuirono razioni parziali e gli operai tornarono al lavoro, per poi rifermarsi al successivo ritardo. Le proteste si ripeterono per mesi. Lo scriba Amennakht documentò tutto, compresa una frase di un operaio: 'Non torneremo. Dite ai vostri superiori che è la fame che ci fa parlare'."),
        ("Il papiro di Torino",
         "Il resoconto è scritto su un papiro oggi al Museo Egizio di Torino. È la testimonianza più antica di lavoratori che si organizzano collettivamente per rivendicare un diritto. I faraoni erano dèi viventi, eppure i loro operai sapevano che senza le loro mani nessuna tomba sarebbe stata pronta per l'eternità."),
       ]),
]

LESSONS = [
    # ------------------------------ NATURA ------------------------------
    L("natura", "v5-lez-riconoscere-alberi",
      "Riconoscere gli alberi dalle foglie in 4 passi", ["alberi", "foglie"],
      "Quercia, faggio, acero, tiglio: li vedi ogni giorno e non sai come si chiamano. Con quattro domande sulla foglia arrivi al nome nella maggior parte dei casi.",
      "Identificare le specie di alberi più comuni in Italia osservando forma, margine e disposizione delle foglie.",
      "Prima chiediti: aghi o foglie? Poi: foglia semplice o composta? Poi: margine liscio, dentato o lobato? Infine: come sono disposte sul ramo? Quattro risposte restringono a poche specie.",
      [
       ("Passo 1 — Aghi, squame o foglie larghe",
        "Aghi in fascetti di due o tre: pino. Aghi singoli, appiattiti e morbidi: abete bianco. Aghi rigidi a sezione quadrata che pungono: abete rosso. Squame piatte sovrapposte: cipresso o tuia. Se la foglia è larga e piatta, passa al secondo passo."),
       ("Passo 2 — Semplice o composta",
        "Una foglia composta è formata da più foglioline attaccate a un asse comune: se stacchi la fogliolina, non c'è la gemma alla base. Foglioline disposte come le dita di una mano: ippocastano. Come una piuma, in coppie: frassino, noce, robinia. Se la foglia è una lamina unica, vai avanti."),
       ("Passo 3 — Il margine racconta",
        "Margine liscio e foglia ovale con nervature parallele ai bordi: faggio, se ha peli sottili al bordo. Margine con denti fini e foglia a cuore asimmetrica: tiglio. Margine a lobi arrotondati: quercia. Lobi appuntiti in forma di mano: acero o platano. Il platano ha la corteccia a chiazze, l'acero i frutti a elica."),
       ("Passo 4 — Disposizione sul ramo e conferma",
        "Guarda come nascono le foglie: a coppie opposte (acero, frassino) o alternate lungo il ramo (quercia, faggio, tiglio, betulla). Poi cerca una conferma: la corteccia bianca della betulla, le ghiande della quercia, i frutti a elica dell'acero. Due indizi che concordano ti danno il nome con buona sicurezza."),
      ]),
    L("natura", "v5-lez-terremoti",
      "Come nasce un terremoto e cosa fare quando arriva", ["terremoto"],
      "Il suolo sotto di te si muove ogni giorno di pochi millimetri, senza che te ne accorga. Ogni tanto, dove si è incastrato, si libera tutto insieme.",
      "Capire il meccanismo delle placche e delle faglie, cosa misura la magnitudo e i comportamenti corretti durante una scossa.",
      "La crosta terrestre è divisa in placche che si muovono di pochi centimetri l'anno. Dove si incastrano accumulano energia elastica, che si libera di colpo lungo una faglia: il terremoto. Durante la scossa: riparati sotto un tavolo robusto, lontano da vetri, non correre fuori.",
      [
       ("Passo 1 — Un puzzle in movimento",
        "La superficie terrestre è divisa in una dozzina di grandi placche rigide che galleggiano sul mantello caldo e lento. Si muovono di 2-10 centimetri l'anno, la velocità con cui crescono le unghie. L'Italia è schiacciata tra la placca africana che sale e quella euroasiatica: per questo gli Appennini tremano."),
       ("Passo 2 — L'elastico che si spezza",
        "Ai bordi le placche non scivolano lisce: si incastrano per attrito e si deformano come un elastico teso, per decenni o secoli. Quando lo sforzo supera la resistenza della roccia, la faglia scatta di colpo, anche di metri, e l'energia accumulata si propaga come onde. Il punto di rottura è l'ipocentro; il punto in superficie sopra di esso, l'epicentro."),
       ("Passo 3 — Cosa dice la magnitudo",
        "La scala è logaritmica: ogni punto in più significa circa 32 volte più energia. Un terremoto di magnitudo 6 libera l'energia di mille bombe di Hiroshima; un 7 di trentamila. Ma i danni dipendono anche da profondità, distanza e soprattutto dagli edifici: un 6 in Giappone fa pochi danni, in un centro storico non rinforzato può essere devastante."),
       ("Passo 4 — Cosa fare durante e dopo",
        "Dentro casa: non correre verso le scale o fuori, dove cadono cornicioni. Riparati sotto un tavolo robusto o nel vano di una porta in muro portante, lontano da finestre e mobili alti. Fuori: allontanati da edifici e linee elettriche. Dopo: chiudi il gas, esci con calma senza ascensore, aspettati altre scosse. Prepara ora una torcia, acqua e i documenti in un punto facile da raggiungere."),
      ]),
    L("natura", "v5-lez-suolo",
      "Il suolo: perché un pugno di terra è vivo", ["suolo", "terra"],
      "In un cucchiaio di terra ci sono più organismi che esseri umani sul pianeta. Il suolo non è polvere: è un ecosistema che produce il 95% del nostro cibo e ci mette secoli a formarsi.",
      "Capire com'è fatto il suolo, come si forma e perché è una risorsa quasi non rinnovabile.",
      "Il suolo è roccia sminuzzata, materia organica in decomposizione, acqua, aria e miliardi di organismi. Si forma alla velocità di un centimetro ogni 100-400 anni e si perde in pochi anni per erosione e cemento.",
      [
       ("Passo 1 — La ricetta",
        "Circa metà del volume è minerale: sabbia, limo e argilla nati dalla frantumazione della roccia. Un quarto è acqua, un quarto aria negli spazi tra i grani. E poi il 5% che cambia tutto: la materia organica, cioè resti di piante, animali e l'humus scuro che ne deriva. Senza quella, è solo polvere."),
       ("Passo 2 — Gli abitanti",
        "In un grammo di terreno fertile vivono fino a un miliardo di batteri, chilometri di filamenti di funghi, migliaia di protozoi e nematodi. Poi acari, collemboli, lombrichi: un lombrico rimescola decine di tonnellate di terra per ettaro ogni anno. Tutti insieme smontano ciò che muore e restituiscono nutrienti alle radici."),
       ("Passo 3 — Gli strati",
        "Scavando trovi in alto la lettiera di foglie, poi lo strato scuro ricco di humus e radici, poi uno più chiaro dove i minerali si accumulano, e infine la roccia madre in frantumi. Ogni strato ha una funzione, e il profilo racconta migliaia di anni di clima e vegetazione."),
       ("Passo 4 — Quanto è fragile",
        "Servono 100-400 anni per formare un centimetro di suolo. Una pioggia intensa su un campo arato in pendenza ne porta via millimetri in un giorno. In Europa ogni anno si cementificano centinaia di chilometri quadrati di terreno fertile, che non tornerà. Lasciare il suolo coperto da piante, evitare di ararlo troppo e restituirgli materia organica sono le tre regole che lo mantengono vivo."),
      ]),
    L("natura", "v5-lez-ecosistema",
      "Come funziona un ecosistema: i 4 ruoli che reggono tutto", ["ecosistema"],
      "Uno stagno, un bosco, la tua siepe: ognuno è una rete dove nulla si spreca. Bastano quattro ruoli per capire chi fa cosa e perché togliere una specie fa crollare le altre.",
      "Riconoscere produttori, consumatori, decompositori e i flussi di energia in qualsiasi ambiente naturale.",
      "I produttori (piante) catturano energia solare. I consumatori la mangiano, in più livelli. I decompositori riciclano tutto in nutrienti per i produttori. L'energia entra e si disperde, la materia gira in cerchio.",
      [
       ("Passo 1 — I produttori",
        "Piante, alghe e alcuni batteri sono gli unici a fabbricare cibo dal nulla: con la fotosintesi trasformano luce, acqua e anidride carbonica in zuccheri. Tutta l'energia dell'ecosistema entra da qui. Per questo la quantità di verde decide quanta vita può esistere in un ambiente."),
       ("Passo 2 — I consumatori a piani",
        "Gli erbivori mangiano le piante, i carnivori mangiano gli erbivori, i superpredatori mangiano i carnivori. A ogni passaggio si perde circa il 90% dell'energia in calore e movimento: servono 100 chili di erba per fare 10 chili di coniglio e 1 chilo di volpe. Ecco perché i predatori sono pochi e le piante sono ovunque."),
       ("Passo 3 — I decompositori, i veri riciclatori",
        "Funghi, batteri, lombrichi e insetti smontano foglie morte, carcasse ed escrementi e li trasformano in sostanze minerali che le radici possono riassorbire. Senza di loro, le foreste sarebbero sepolte da metri di foglie in pochi anni e i nutrienti finirebbero bloccati nei cadaveri."),
       ("Passo 4 — Cosa succede se togli un pezzo",
        "Nel parco di Yellowstone i lupi furono sterminati nel 1926. I cervi esplosero, mangiarono i giovani salici lungo i fiumi, i castori sparirono, le sponde crollarono. Reintrodotti i lupi nel 1995, i salici ricrebbero, i castori tornarono e i fiumi cambiarono corso. Una specie chiave tiene insieme una rete: guarda la tua siepe e chiediti chi lo fa lì."),
      ]),
    L("natura", "v5-lez-compost",
      "Fare il compost in casa: dai rifiuti alla terra in 4 passi", ["compost"],
      "Un terzo di ciò che butti nella spazzatura potrebbe diventare terra fertile sul balcone. Serve un contenitore, un po' di pazienza e capire chi lavora per te.",
      "Avviare e gestire una compostiera domestica evitando cattivi odori e ottenendo terriccio in pochi mesi.",
      "Alterna scarti umidi (verdura, frutta, caffè) e secchi (foglie, cartone) in proporzione circa 1 a 2, mantieni umido come una spugna strizzata, rigira ogni due settimane. In 3-6 mesi hai terriccio scuro che profuma di bosco.",
      [
       ("Passo 1 — Il contenitore e il posto",
        "Una compostiera da giardino, un bidone con fori di aerazione o, in appartamento, una vermicompostiera con lombrichi. Sistemalo all'ombra, a contatto con la terra se possibile, così gli organismi del suolo salgono da soli. Sul fondo uno strato di rametti per far circolare aria."),
       ("Passo 2 — Verdi e marroni",
        "I 'verdi' sono umidi e ricchi di azoto: bucce, avanzi di verdura, fondi di caffè, erba tagliata. I 'marroni' sono secchi e ricchi di carbonio: foglie, cartone senza inchiostri, segatura, gusci d'uovo. Regola pratica: due parti di marrone per una di verde. Troppo verde puzza; troppo marrone non si decompone. Evita carne, pesce, latticini e cibi cotti oleosi."),
       ("Passo 3 — Aria e acqua",
        "I batteri che fanno il lavoro respirano: rigira il mucchio ogni due settimane con una forca. Deve essere umido come una spugna strizzata: se gocciola aggiungi cartone, se è polveroso bagnalo. Un compost sano è tiepido al centro, anche 50-60 gradi nelle prime settimane, e non puzza mai: odora di sottobosco."),
       ("Passo 4 — Raccogliere e usare",
        "Dopo 3-6 mesi il fondo diventa scuro, friabile e irriconoscibile. Setaccialo, rimetti nel mucchio ciò che non è pronto e usa il resto: due dita sulla superficie dei vasi, mescolato al terriccio per i trapianti, intorno agli alberi in autunno. Hai chiuso un cerchio che la natura chiude da sempre."),
      ]),

    # ------------------------------ ANIMALI ------------------------------
    L("animali", "v5-lez-ibernazione",
      "L'ibernazione: come si sopravvive all'inverno spegnendosi", ["ibernazione"],
      "Un orso passa cinque mesi senza mangiare, bere né urinare. Un pipistrello scende a un battito al minuto. Non dormono: fanno qualcosa di molto più radicale.",
      "Capire cosa succede nel corpo di un animale in ibernazione, chi lo fa davvero e perché gli esseri umani non ci riescono.",
      "L'ibernazione abbassa temperatura, battito e metabolismo fino al 2% del normale per settimane o mesi, con brevi risvegli. L'orso fa una versione leggera. Gli umani non hanno l'interruttore, ma la medicina studia come imitarla.",
      [
       ("Passo 1 — Non è sonno",
        "Nel sonno il cervello è attivo e la temperatura cala di un grado. Nell'ibernazione vera la temperatura corporea scende quasi a quella dell'ambiente, anche a 2-3 gradi, il cuore passa da 400 battiti a 5, il respiro si ferma per minuti. Il cervello mostra meno attività che nel coma. Svegliare un animale così richiede ore."),
       ("Passo 2 — Il carburante",
        "Un ghiro o una marmotta raddoppia il peso in autunno accumulando grasso. Poi consuma quasi solo quello, lentamente: una marmotta perde metà del peso in sei mesi. Ogni 1-3 settimane si riscalda per qualche ora, probabilmente per dormire davvero e riattivare il sistema immunitario, poi si rispegne."),
       ("Passo 3 — L'orso, un caso a parte",
        "L'orso scende solo di 4-5 gradi e può svegliarsi in fretta, quindi tecnicamente fa un torpore invernale. Ma non mangia, non beve e non elimina rifiuti per mesi: ricicla l'urea in proteine e non perde massa muscolare né ossea, cosa che un umano immobile a letto farebbe in poche settimane. I medici lo studiano per l'osteoporosi e i viaggi spaziali."),
       ("Passo 4 — Perché noi no",
        "Alcuni primati, i lemuri del Madagascar, ibernano: quindi il programma genetico non è così lontano da noi. Ma gli umani non hanno il meccanismo che abbassa il termostato interno in sicurezza. In terapia intensiva si usa già l'ipotermia controllata, 33 gradi, per proteggere il cervello dopo un arresto cardiaco: una piccola ibernazione medica."),
      ]),
    L("animali", "v5-lez-comunicazione-animale",
      "Come parlano gli animali: i 4 canali della comunicazione", ["comunicazione"],
      "Un cane che scodinzola, una lucciola che lampeggia, un elefante che brontola a frequenze che non senti. Parlano tutti, ma su canali diversi. Ecco come ascoltarli.",
      "Riconoscere i quattro canali principali della comunicazione animale e interpretare qualche segnale comune.",
      "Gli animali comunicano con suoni, segnali visivi, odori e vibrazioni o tatto. Ogni specie privilegia il canale che funziona meglio nel suo ambiente: la notte favorisce odori e suoni, l'acqua i suoni, la luce del giorno i colori e le posture.",
      [
       ("Passo 1 — I suoni",
        "Il canale più familiare. Gli uccelli cantano per difendere il territorio e trovare un partner, con dialetti regionali. Gli elefanti usano infrasuoni sotto i 20 hertz che viaggiano per chilometri nel terreno e che percepiscono con i piedi. Le balene cantano melodie che cambiano di anno in anno come mode."),
       ("Passo 2 — I segnali visivi",
        "Posture, colori, movimenti. Il cane che scodinzola a destra è più rilassato di quello che scodinzola a sinistra, e la coda alta rigida non è amicizia ma tensione. Il pavone fa la ruota, la seppia fa scorrere onde di colore sulla pelle, la lucciola lampeggia con un codice specifico per specie: i maschi di alcune specie predatrici imitano il codice delle femmine di altre per attirarle e mangiarle."),
       ("Passo 3 — Gli odori",
        "Il canale più antico e più diffuso. Le formiche vivono in un mondo di feromoni: allarme, traccia, riconoscimento del nido. I cani leggono nell'urina di un altro cane sesso, stato di salute e da quanto è passato. Le falene femmine emettono molecole che un maschio sente da chilometri. Gli odori durano nel tempo: sono messaggi lasciati per chi passerà dopo."),
       ("Passo 4 — Vibrazioni e tatto",
        "I ragni leggono le vibrazioni della tela per distinguere preda, vento e partner. Le api danzano nel buio dell'alveare e le compagne sentono la danza con le antenne. Le talpe battono la testa nelle gallerie. Le scimmie si spulciano per ore: la pulizia è un pretesto, il messaggio è alleanza. Quando accarezzi il tuo gatto stai usando lo stesso canale."),
      ]),
    L("animali", "v5-lez-insetti-utili",
      "Gli insetti utili in giardino: chi lavora per te", ["insetti utili"],
      "Prima di spruzzare qualcosa contro 'gli insetti', vale la pena sapere che la maggior parte sta dalla tua parte. Ecco i quattro alleati da riconoscere e proteggere.",
      "Riconoscere i principali insetti utili del giardino e creare le condizioni perché restino.",
      "Coccinelle e sirfidi mangiano afidi; api e bombi impollinano; le vespe parassitoidi controllano bruchi e mosche; i carabidi ripuliscono il terreno di notte. Fiori semplici, un angolo incolto e niente insetticidi li tengono lì.",
      [
       ("Passo 1 — I mangiatori di afidi",
        "Una coccinella adulta mangia 50 afidi al giorno, la sua larva, che sembra un piccolo alligatore grigio e arancione, anche di più: molti la schiacciano credendola dannosa. I sirfidi sono mosche travestite da vespe, con volo fermo a mezz'aria; le loro larve, piccole e verdastre, svuotano intere colonie di afidi sulle rose."),
       ("Passo 2 — Gli impollinatori",
        "Non solo l'ape da miele: in Italia vivono oltre mille specie di api selvatiche, spesso solitarie e senza pungiglione efficace. I bombi lavorano anche al freddo e con la pioggia, quando le api restano a casa. Un orto senza impollinatori produce zucchine che marciscono prima di crescere."),
       ("Passo 3 — I parassitoidi e i predatori notturni",
        "Minuscole vespe, spesso invisibili, depongono le uova dentro bruchi e afidi, che diventano incubatrici. Un afide gonfio, color bronzo e immobile, è una 'mummia': lascialo, ne usciranno altre vespe. Di notte escono i carabidi, coleotteri neri e veloci, che mangiano lumache, uova e larve al suolo."),
       ("Passo 4 — Come tenerli con te",
        "Pianta fiori semplici e aperti: finocchio, aneto, calendula, borragine, aromatiche lasciate fiorire. Lascia un angolo con erba alta e un mucchietto di legna per l'inverno. Non usare insetticidi, nemmeno 'naturali' ad ampio spettro: uccidono prima gli alleati che i parassiti. Tollera qualche afide: è il cibo che tiene le coccinelle in giardino."),
      ]),
    L("animali", "v5-lez-mimetismo",
      "Mimetismo: 4 strategie per non farsi vedere (o farsi credere pericolosi)", ["mimetismo"],
      "Un ramoscello che cammina, una farfalla con gli occhi di gufo, un serpente innocuo che ruba i colori a uno mortale. La natura ha inventato l'inganno molto prima di noi.",
      "Distinguere le principali forme di mimetismo e capire quale vantaggio evolutivo offre ciascuna.",
      "Il camuffamento nasconde; il mascheramento imita un oggetto; il mimetismo batesiano copia una specie pericolosa senza esserlo; quello mülleriano unisce più specie pericolose sotto la stessa livrea di avvertimento.",
      [
       ("Passo 1 — Sparire nello sfondo",
        "La forma più semplice: colori e motivi che ricalcano l'ambiente. La lepre artica bianca d'inverno e bruna d'estate, la sogliola che copia il fondale, il leopardo che nella luce a chiazze della foresta scompare. Le zebre, controintuitivamente, confondono i predatori in branco: le strisce in movimento rendono difficile isolare un individuo."),
       ("Passo 2 — Fingersi un oggetto",
        "L'insetto stecco imita un ramoscello e oscilla al vento; la mantide orchidea ha petali al posto delle zampe; alcuni bruchi sembrano escrementi di uccello. Non si nascondono nello sfondo: sono qualcosa che il predatore vede ma non considera cibo. Il pesce foglia dell'Amazzonia si lascia trasportare dalla corrente come una foglia morta."),
       ("Passo 3 — Rubare la reputazione a un altro",
        "Il mimetismo batesiano: una specie innocua copia i colori di una pericolosa. Il serpente reale, innocuo, ha gli anelli rosso-giallo-nero del corallo mortale. I sirfidi hanno le strisce delle vespe senza pungiglione. Funziona finché i copioni sono meno numerosi degli originali: se il predatore incontra troppi falsi, smette di credere al segnale."),
       ("Passo 4 — Un'uniforme condivisa",
        "Il mimetismo mülleriano: più specie davvero pericolose convergono sugli stessi colori, così un predatore impara la lezione una sola volta e la applica a tutte. Api, vespe e calabroni con il loro giallo e nero; le farfalle Heliconius del Sudamerica, tossiche, che si scambiano motivi tra specie diverse. Anche gli occhi finti sulle ali delle farfalle rientrano nell'inganno: uno scatto d'ali e il predatore vede un gufo."),
      ]),
    L("animali", "v5-lez-estinzione",
      "Perché le specie si estinguono, e cosa ne ha salvate alcune", ["estinzione"],
      "Il dodo, il piccione migratore, il tilacino. E poi il bisonte, la balena grigia, il lupo italiano tornati dall'orlo. Cosa fa la differenza tra le due liste?",
      "Capire le cause principali di estinzione oggi e i quattro interventi che si sono dimostrati efficaci.",
      "Le cause moderne sono perdita di habitat, caccia e pesca eccessive, specie invasive e clima. Funzionano: proteggere e collegare gli habitat, regolare la caccia, rimuovere gli invasori dalle isole, reintrodurre in natura individui allevati.",
      [
       ("Passo 1 — Cinque volte prima di noi",
        "La Terra ha visto cinque estinzioni di massa, l'ultima quella dei dinosauri 66 milioni di anni fa. Il tasso naturale è di circa una specie di mammifero estinta ogni 200 anni. Oggi il ritmo è stimato 100-1.000 volte superiore, e la causa non è un asteroide ma un'unica specie molto numerosa."),
       ("Passo 2 — Le quattro cause",
        "La prima è la perdita di habitat: foreste che diventano campi, zone umide che diventano città. La seconda è il prelievo diretto: il piccione migratore, forse l'uccello più numeroso della storia con miliardi di individui, fu cacciato fino all'ultimo esemplare nel 1914. Terza, le specie introdotte: ratti e gatti hanno spazzato via decine di uccelli sulle isole. Quarta, il clima che cambia più in fretta di quanto le specie si spostino."),
       ("Passo 3 — Cosa ha funzionato",
        "Il bisonte americano, da 30 milioni a poche centinaia, oggi conta 500.000 capi grazie a riserve e divieto di caccia. La balena grigia si è ripresa dopo la moratoria sulla caccia del 1986. In Nuova Zelanda intere isole sono state liberate dai ratti e i kakapo sono passati da 51 a oltre 250. Il lupo in Italia, quasi sparito negli anni Settanta, oggi supera i 3.000 individui."),
       ("Passo 4 — La lezione",
        "Le specie si salvano quando si interviene in tempo e si toglie la causa, non quando si cerca di allevare gli ultimi dieci esemplari. I corridoi che collegano aree protette contano più delle aree isolate. E una specie salvata ne trascina altre: proteggere il lupo ha protetto boschi e fiumi. Ogni specie che perdiamo è un esperimento di miliardi di anni che non si ripete."),
      ]),

    # ------------------------------ STORIA ------------------------------
    L("storia", "v5-lez-datare-reperti",
      "Come si dà una data a un reperto: 4 metodi", ["datare", "reperto"],
      "Un osso, un coccio, una trave di legno. Come fa un archeologo a dire che hanno 3.000 anni e non 300? Non lo indovina: lo misura, con orologi diversi.",
      "Conoscere i principali metodi di datazione, i loro limiti e quando si usa ciascuno.",
      "La stratigrafia dice cosa è più vecchio di cosa. Il carbonio-14 data materiali organici fino a 50.000 anni. Gli anelli degli alberi datano il legno all'anno esatto. Metodi come potassio-argon e luminescenza coprono milioni di anni su rocce e ceramiche.",
      [
       ("Passo 1 — Gli strati: prima e dopo",
        "Il metodo più antico e ancora fondamentale. Il terreno si deposita a strati: ciò che sta sotto è più vecchio di ciò che sta sopra, salvo rimescolamenti. Se in uno strato c'è una moneta con la data, tutto quello strato è almeno di quell'epoca. La stratigrafia dà un ordine relativo, non un'età assoluta."),
       ("Passo 2 — Il carbonio-14",
        "Ogni essere vivente assorbe carbonio, incluso il raro carbonio-14 radioattivo. Alla morte smette, e il C-14 decade dimezzandosi ogni 5.730 anni. Misurando quanto ne resta in un osso, un seme o un tessuto si calcola quando è morto, con errori di qualche decennio. Funziona fino a circa 50.000 anni; oltre, ne resta troppo poco."),
       ("Passo 3 — Gli anelli e i vulcani",
        "Gli alberi aggiungono un anello l'anno, largo o stretto secondo il clima: confrontando la sequenza di una trave con archivi di migliaia di anni si trova l'anno esatto in cui fu tagliata. Per le rocce e i fossili antichi milioni di anni si usano altri elementi radioattivi con decadimenti lentissimi, come il potassio-argon nelle ceneri vulcaniche che racchiudono i reperti."),
       ("Passo 4 — Incrociare sempre",
        "Nessun metodo è infallibile: il C-14 va calibrato perché il carbonio nell'atmosfera variava; un legno può essere stato riutilizzato secoli dopo il taglio. Gli archeologi incrociano più metodi e cercano coerenza. La Sindone di Torino fu datata al C-14 tra il 1260 e il 1390 da tre laboratori indipendenti: la convergenza è ciò che rende una data solida."),
      ]),
    L("storia", "v5-lez-rivoluzione-agricola",
      "La rivoluzione agricola: la scelta che ha cambiato la specie", ["rivoluzione agricola"],
      "Per 200.000 anni siamo stati cacciatori nomadi. Poi, in poche migliaia di anni, ci siamo fermati a coltivare. Fu un progresso? La risposta è meno ovvia di quanto sembri.",
      "Capire quando, dove e perché l'umanità è passata all'agricoltura e quali conseguenze ha avuto sulla salute, sulla società e sul pianeta.",
      "Circa 11.000 anni fa, in Medio Oriente e poi in Cina, America e Africa, gruppi umani cominciarono a coltivare piante e allevare animali. Ottennero più cibo e più figli, ma anche malattie, disuguaglianza e lavoro più duro.",
      [
       ("Passo 1 — Dove e quando",
        "Accadde indipendentemente in almeno sette regioni: nella Mezzaluna fertile con grano e orzo intorno al 9500 a.C., in Cina con riso e miglio, in Mesoamerica con mais, nelle Ande con patata, in Africa con sorgo. Non un'invenzione diffusa, ma la stessa risposta a un clima che si stabilizzava dopo l'ultima glaciazione."),
       ("Passo 2 — Perché fermarsi",
        "I cacciatori-raccoglitori mangiavano vario e lavoravano meno ore. Ma la popolazione cresceva, le prede diminuivano e le piante selvatiche più produttive, raccolte e riseminate, cambiavano: chicchi più grandi che non cadono da soli. La scelta non fu consapevole: ogni generazione fece un passo piccolo, e dopo qualche secolo tornare indietro era impossibile."),
       ("Passo 3 — Il prezzo",
        "Gli scheletri dei primi agricoltori sono più bassi, con più carie e segni di anemia: dieta monotona a base di cereali. Vivere fermi accanto agli animali fece nascere morbillo, tubercolosi e influenza. Le riserve di grano dovevano essere difese e amministrate: nacquero magazzini, soldati, tasse, re. La disuguaglianza è figlia del granaio."),
       ("Passo 4 — Quel che ha reso possibile",
        "In cambio, l'agricoltura sostiene 100 volte più persone per chilometro quadrato. Le eccedenze liberarono tempo per artigiani, scribi, sacerdoti: la scrittura nacque per contare sacchi di orzo. Città, tecnologia, arte, scienza esistono grazie a quella scelta. Oggi siamo 8 miliardi e il 40% delle terre emerse è coltivato: l'esperimento iniziato 11.000 anni fa è ancora in corso."),
      ]),
    L("storia", "v5-lez-nascita-citta",
      "Come nasce una città: le 4 condizioni che si ripetono", ["città"],
      "Roma, Baghdad, New York, Shenzhen. Epoche e continenti diversi, ma se guardi bene le città nascono sempre per le stesse ragioni.",
      "Riconoscere i fattori che fanno nascere e crescere una città, e applicarli per leggere la storia di quella in cui vivi.",
      "Una città ha bisogno di acqua e cibo dall'intorno, di una posizione su una via di scambio, di una funzione che attiri persone (mercato, tempio, potere) e di una ragione per restare, come sicurezza o lavoro. Quando una condizione salta, la città declina.",
      [
       ("Passo 1 — Acqua e un entroterra che nutre",
        "Le prime città, Uruk in Mesopotamia intorno al 3500 a.C., nascono dove i fiumi permettono irrigazione e trasporto. Una città non produce il proprio cibo: serve una campagna intorno abbastanza fertile e un modo per portare il raccolto dentro le mura. Roma crebbe sul Tevere, Parigi sulla Senna, Il Cairo sul Nilo."),
       ("Passo 2 — Un incrocio",
        "Dove le vie di scambio si incontrano, le merci si fermano e cambiano mano: un porto, un guado, un valico, un incrocio di carovane. Venezia tra Oriente e Occidente, Samarcanda sulla Via della Seta, Chicago dove ferrovie e Grandi Laghi si toccano. Il commercio porta persone, e le persone portano altre persone."),
       ("Passo 3 — Una funzione che attira",
        "Molte città nascono intorno a un tempio, a una fortezza, a una sede di potere: Gerusalemme, Mecca, ma anche Washington o Brasilia, costruite per decisione. Altre intorno a una risorsa: le città minerarie, le città industriali come Manchester. Quando la funzione sparisce, come le miniere di Detroit o le città fantasma dell'oro, la città rischia di svuotarsi."),
       ("Passo 4 — Leggere la tua città",
        "Guarda la mappa della città in cui vivi: c'è un fiume o un porto? Dov'è il centro più antico, e su quale via passava? Che cosa produceva? Le città che durano millenni sono quelle che hanno cambiato funzione mantenendo la posizione: Roma da capitale d'impero a città santa a capitale nazionale. La posizione è per sempre; il motivo può cambiare."),
      ]),
    L("storia", "v5-lez-medioevo",
      "Il Medioevo non era buio: 4 luoghi comuni da smontare", ["Medioevo"],
      "Mille anni di storia ridotti a peste, roghi e ignoranza. È il periodo più frainteso di tutti, e la colpa è di chi venne dopo e voleva sembrare più brillante.",
      "Riconoscere i principali luoghi comuni sul Medioevo e sostituirli con ciò che le fonti mostrano davvero.",
      "L'espressione 'secoli bui' fu inventata da umanisti e illuministi per esaltare la propria epoca. Nel Medioevo nacquero università, banche, occhiali, orologi meccanici e le cattedrali; nessuno colto credeva che la Terra fosse piatta e la caccia alle streghe è in gran parte un fenomeno moderno.",
      [
       ("Passo 1 — Chi ha inventato i secoli bui",
        "Il termine nasce con Petrarca nel Trecento e viene rafforzato nel Settecento: gli intellettuali di allora avevano bisogno di un periodo oscuro tra l'antichità classica e sé stessi per sembrare una rinascita. Mille anni, dal 476 al 1492, dalla caduta di Roma alla scoperta dell'America, non possono essere un'unica cosa."),
       ("Passo 2 — La Terra piatta e la scienza",
        "Nessuno studioso medievale credeva la Terra piatta: la sfericità era nota dai greci e insegnata nelle scuole. Le università di Bologna, Parigi e Oxford nascono tra l'XI e il XII secolo. I monaci copiarono i testi antichi che oggi leggiamo. Gli occhiali sono del 1280, l'orologio meccanico del 1300, i mulini a vento e la stampa a caratteri mobili europea chiudono il periodo."),
       ("Passo 3 — Streghe e violenza",
        "La grande caccia alle streghe, con decine di migliaia di vittime, è tra il 1550 e il 1700: piena età moderna, dopo Copernico e la stampa. Nel Medioevo la Chiesa considerava a lungo la stregoneria una superstizione da non prendere sul serio. La violenza c'era, ma l'Europa del Cinquecento e Seicento, con le guerre di religione, fu più sanguinosa."),
       ("Passo 4 — Cosa gli dobbiamo",
        "Il sistema bancario, le lettere di cambio e la contabilità nascono nelle città italiane del Duecento. Il Parlamento inglese, la Magna Carta, i comuni con i loro statuti. La musica polifonica, la notazione musicale, la rima nella poesia. La prossima volta che senti 'roba da Medioevo' per indicare qualcosa di arretrato, ricorda che stai parlando dell'epoca che ha inventato l'università."),
      ]),
    L("storia", "v5-lez-moneta-antica",
      "Leggere una moneta antica: cosa racconta un pezzo di metallo", ["moneta"],
      "Un dischetto ossidato trovato in un campo può dire chi governava, cosa voleva far credere ai sudditi, quanto valeva il pane e dove passava il commercio. Basta sapere dove guardare.",
      "Interpretare gli elementi di una moneta antica per ricavarne informazioni storiche.",
      "Il volto indica l'autorità che l'ha emessa; le scritte danno nome, titoli e spesso l'anno di regno; il rovescio è propaganda in immagini; il metallo e il peso raccontano l'economia. Il luogo del ritrovamento parla dei commerci.",
      [
       ("Passo 1 — Il volto e il nome",
        "Sulla faccia principale c'è quasi sempre il sovrano o un simbolo della città. Intorno, la legenda: sulle monete romane abbreviazioni come IMP CAES per imperatore Cesare, poi il nome e i titoli. Il numero dopo COS indica quante volte è stato console: permette di datare la moneta a un anno o due."),
       ("Passo 2 — Il rovescio, un manifesto",
        "Il retro era il mezzo di comunicazione di massa dell'antichità. Un imperatore mostrava una vittoria militare, un ponte appena costruito, una dea della pace o dell'abbondanza per dire che tutto andava bene. Cambiavano ogni anno: le monete sono i comunicati stampa dell'epoca, arrivati fino a noi."),
       ("Passo 3 — Il metallo mente poco",
        "Il denario romano del I secolo era argento quasi puro; nel III secolo conteneva il 5% d'argento su una base di rame: l'impero stampava moneta per pagare l'esercito e l'inflazione galoppava. Pesare e analizzare le monete permette di ricostruire crisi economiche di cui nessuno scrisse."),
       ("Passo 4 — Dove è stata trovata",
        "Monete romane in India, dirham arabi in Scandinavia, denari veneziani in Etiopia: i ritrovamenti disegnano le rotte del commercio. Un tesoretto sepolto in fretta racconta un'invasione; una moneta consumata dall'uso ha circolato a lungo. Se ne trovi una, segna il punto esatto: la posizione vale quanto l'oggetto."),
      ]),
]
