"""PAUSE v5 — ampliamento catalogo (parte A): Scienza, Spazio, Tecnologia.
5 curiosità + 5 mini lezioni per categoria, scritte a mano in italiano.
Le traduzioni EN vengono generate a posteriori dalla pipeline (generate_content.py)."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ SCIENZA ------------------------------
    mk("scienza", "v5-arcobaleno-arco",
       "Perché l'arcobaleno è un arco e ha sempre gli stessi colori?", ["arcobaleno", "arco"],
       "Ogni volta la stessa sequenza, ogni volta la stessa curva. Non è un caso: è geometria pura fatta di gocce d'acqua.",
       "Ogni goccia di pioggia piega e riflette la luce del Sole a un angolo di circa 42 gradi. Tutte le gocce che stanno su quel cono ti rimandano luce: il cono visto di fronte è un cerchio, e la terra ne taglia via metà.",
       "",
       [
        ("Un prisma grande quanto una goccia",
         "La luce del Sole sembra bianca ma contiene tutti i colori. Quando entra in una goccia d'acqua rallenta e cambia direzione, ma non tutti i colori si piegano allo stesso modo: il violetto devia di più, il rosso di meno. La luce si apre come un ventaglio, esattamente come in un prisma di vetro."),
        ("Il rimbalzo sul fondo",
         "Dentro la goccia, la luce colpisce la parete opposta e torna indietro verso di te. Uscendo si piega ancora una volta. Il risultato di questo percorso è che il rosso esce a circa 42 gradi rispetto al raggio del Sole, il violetto a circa 40. Ogni goccia rimanda una fetta di colore precisa."),
        ("Perché è un cerchio",
         "Tutte le gocce che si trovano a 42 gradi dalla linea che va dal Sole al tuo occhio ti mandano luce rossa; quelle a 40 gradi ti mandano violetto. Quei punti formano un cono con la punta nel tuo occhio, e un cono visto di fronte è un cerchio. L'orizzonte taglia la parte bassa: da un aereo l'arcobaleno appare intero, tondo."),
        ("Il tuo arcobaleno è solo tuo",
         "Poiché il cerchio è centrato sul tuo occhio, chi ti sta accanto vede un arcobaleno costruito da gocce diverse. Non puoi raggiungerne la fine: spostandoti, si sposta con te. E il secondo arcobaleno più pallido, con i colori invertiti, nasce dalla luce che ha rimbalzato due volte dentro le gocce."),
       ]),
    mk("scienza", "v5-metallo-freddo",
       "Perché il metallo sembra più freddo del legno, se hanno la stessa temperatura?", ["metallo", "freddo"],
       "Tocca la gamba di una sedia e il piano del tavolo: stessa stanza, stessa temperatura, sensazioni opposte. La tua pelle non misura i gradi.",
       "La pelle percepisce quanto calore perde, non la temperatura dell'oggetto. Il metallo conduce il calore molto rapidamente e lo porta via dalle dita; il legno lo fa lentamente e sembra tiepido.",
       "",
       [
        ("Un termometro che non esiste",
         "Non abbiamo sensori che leggono i gradi di un oggetto. I recettori della pelle misurano la temperatura della pelle stessa e quanto in fretta cambia. Se il calore scappa dalle dita in fretta, il cervello traduce quel flusso con la parola 'freddo'."),
        ("La conducibilità termica",
         "Nel metallo gli elettroni liberi trasportano il calore con estrema efficienza: l'alluminio conduce circa mille volte meglio del legno. Toccando il metallo, il calore della mano si diffonde subito in tutto l'oggetto. Il legno, pieno di aria e fibre, lo trattiene vicino al punto di contatto, che si scalda e smette di sottrarre calore."),
        ("La prova al contrario",
         "Lascia una padella e un tagliere di legno al sole d'estate, entrambi a 50 gradi. La padella scotta e il legno è appena caldo. Stesso principio, direzione opposta: ora il metallo spinge calore nella tua mano più in fretta di quanto il sangue riesca a portarlo via."),
        ("Perché conta nella vita reale",
         "È il motivo per cui i manici delle pentole sono in plastica o legno, le maniglie in ottone sembrano gelide d'inverno e una coperta di lana 'scalda' pur non producendo calore: intrappola aria e rallenta la fuga del tuo calore. Una casa ben isolata funziona esattamente come il tagliere."),
       ]),
    mk("scienza", "v5-candela",
       "Cosa brucia davvero in una candela?", ["candela", "brucia"],
       "Sembra ovvio: brucia la cera. Ma se avvicini un fiammifero a un blocco di cera, non prende fuoco. Il segreto è nello stoppino, ma non nel modo in cui pensi.",
       "Lo stoppino non brucia: risucchia cera fusa e la fa evaporare. È il vapore di cera, mescolato con l'aria, a bruciare. La fiamma è una piccola fabbrica chimica autoalimentata.",
       "",
       [
        ("Il fiammifero scalda, non accende",
         "La fiamma del fiammifero scioglie la cera in cima allo stoppino e la porta a evaporare. Il vapore di cera, fatto di lunghe molecole di idrocarburi, si mescola con l'ossigeno e a quel punto sì, si accende. Da quel momento la fiamma produce da sola il calore che le serve per continuare."),
        ("Lo stoppino è una cannuccia",
         "La cera fusa sale lungo le fibre di cotone per capillarità, lo stesso fenomeno che fa risalire l'acqua in un tovagliolo. Lo stoppino è intrecciato per piegarsi verso il bordo della fiamma, dove la temperatura è alta e la punta si consuma lentamente. Senza cera che lo raffredda, brucerebbe in pochi secondi."),
        ("Le zone della fiamma",
         "Alla base, azzurra, c'è la combustione più completa e più calda, circa 1.400 gradi. Al centro, scura, c'è vapore di cera non ancora bruciato. La parte gialla è fatta di minuscole particelle di carbonio incandescenti: è la fuliggine che brilla prima di bruciare a sua volta. Il giallo che vedi è materia solida che emette luce per il calore."),
        ("La goccia che sale",
         "La fiamma ha la forma allungata perché l'aria calda sale e trascina con sé i gas, richiamando aria fresca dal basso. Nella Stazione Spaziale, senza gravità, l'aria calda non sale: la fiamma diventa una sfera azzurra e quasi invisibile, e rischia di soffocare nei propri gas."),
       ]),
    mk("scienza", "v5-suono-acqua",
       "Perché il suono viaggia più veloce nell'acqua che nell'aria?", ["suono", "acqua"],
       "Sott'acqua tutto sembra ovattato, eppure il suono corre quattro volte più veloce. Le balene lo sanno e ne approfittano da milioni di anni.",
       "Il suono è una spinta che passa di molecola in molecola. Nell'acqua le molecole sono vicine e legate: la spinta si trasmette a 1.500 metri al secondo contro i 340 dell'aria. Nell'acciaio supera i 5.000.",
       "",
       [
        ("Una fila di persone che si spingono",
         "Il suono non è materia che viaggia: è un'onda di compressione. Immagina una fila di persone che si passano una spinta. Se sono distanti, ognuno deve fare un passo prima di toccare il vicino; se sono a contatto, la spinta passa istantaneamente. Le molecole d'aria sono lontane, quelle d'acqua praticamente a contatto."),
        ("Non conta solo la densità",
         "Si potrebbe pensare che più un materiale è denso, più il suono è lento, perché c'è più massa da muovere. Ma conta anche la rigidità: quanto il materiale resiste a essere compresso. L'acqua è quasi incomprimibile e questa rigidità vince sulla massa. Nell'acciaio la rigidità è enorme: il suono corre a oltre 5 chilometri al secondo."),
        ("Perché sott'acqua senti male",
         "Se il suono va veloce, perché in piscina tutto è confuso? Perché le tue orecchie sono progettate per l'aria: il timpano riceve male le vibrazioni dell'acqua e il suono arriva anche attraverso le ossa del cranio, arrivando a entrambe le orecchie quasi insieme. Il cervello non riesce più a capire da dove venga."),
        ("Il telefono delle balene",
         "A circa mille metri di profondità esiste uno strato dove il suono resta intrappolato e viaggia per migliaia di chilometri senza disperdersi. Le balene azzurre emettono canti a bassissima frequenza dentro questo canale: un individuo al largo dell'Irlanda può, in teoria, essere udito vicino alle Azzorre."),
       ]),
    mk("scienza", "v5-bolle-sapone",
       "Perché le bolle di sapone sono colorate se il sapone è trasparente?", ["bolle", "colorate"],
       "Acqua e sapone, entrambi incolori. Eppure la bolla è un caleidoscopio che cambia fino a diventare, un istante prima di scoppiare, quasi nera.",
       "La parete della bolla è un film sottilissimo. La luce che si riflette sulla faccia esterna e quella sulla faccia interna si sommano o si cancellano a seconda dello spessore: i colori sono interferenza, non pigmento.",
       "",
       [
        ("Due riflessi quasi uguali",
         "La parete di una bolla è un sandwich: sapone, acqua, sapone, spesso poche centinaia di nanometri. Quando la luce arriva, una parte rimbalza sulla superficie esterna e una parte entra, rimbalza su quella interna e riesce. Due onde quasi identiche, ma una ha fatto un percorso leggermente più lungo."),
        ("Quando le onde si incontrano",
         "Se il percorso extra è pari a una lunghezza d'onda intera, le due onde sono in fase e si rinforzano: quel colore brilla. Se è pari a mezza lunghezza d'onda, cresta contro valle si annullano: quel colore sparisce. Ogni spessore della parete cancella alcuni colori ed esalta gli altri."),
        ("Una mappa dello spessore",
         "I colori che vedi sono in realtà una mappa: le zone rosa e verdi sono più spesse, quelle blu e gialle più sottili. La gravità fa scivolare l'acqua verso il basso, per questo le bande di colore scorrono e la parte alta della bolla si assottiglia per prima."),
        ("Il nero che annuncia la fine",
         "Quando lo spessore scende sotto i 20 nanometri, il percorso extra diventa trascurabile ma il riflesso interno inverte la fase: tutte le onde si cancellano e la bolla appare nera. Un attimo dopo il film è troppo sottile per reggersi e scoppia. Lo stesso principio colora le macchie d'olio sull'asfalto e le ali delle libellule."),
       ]),

    # ------------------------------ SPAZIO ------------------------------
    mk("spazio", "v5-saturno-galleggia",
       "Saturno galleggerebbe in una vasca da bagno", ["Saturno", "galleggerebbe"],
       "Il secondo pianeta più grande del Sistema Solare è così leggero, in proporzione, che se trovassi un oceano abbastanza vasto resterebbe a galla.",
       "Saturno ha una densità media di 0,69 grammi per centimetro cubo, inferiore a quella dell'acqua. È fatto quasi solo di idrogeno ed elio, gonfiati su un nucleo relativamente piccolo.",
       "",
       [
        ("Un gigante di gas",
         "Saturno ha un diametro nove volte quello della Terra, ma è composto per oltre il 90% di idrogeno e per il resto quasi solo di elio, i due elementi più leggeri che esistono. Mettendo insieme tutta la sua massa e dividendola per il volume si ottiene una densità di 0,69: l'acqua ha 1."),
        ("Come un pallone con un sasso dentro",
         "Nel profondo c'è probabilmente un nucleo di roccia e metallo grande dieci o venti volte la Terra. Sopra, strati di idrogeno così compresso da comportarsi come un metallo liquido, e poi migliaia di chilometri di gas. È il gas a fare il volume, il nucleo a fare quasi tutta la massa."),
        ("La vasca non esiste, ma l'idea è giusta",
         "Nessun oceano potrebbe contenere Saturno, e se esistesse la sua gravità spappolerebbe il pianeta. Ma il calcolo è corretto: a parità di volume Saturno pesa meno dell'acqua, quindi galleggerebbe. Giove, con densità 1,33, affonderebbe come un sasso."),
        ("Perché è così schiacciato",
         "Saturno ruota in appena 10 ore e mezza. Un corpo così leggero e veloce si gonfia all'equatore: il suo diametro polare è il 10% più corto di quello equatoriale. Visto al telescopio non è una sfera ma un'ellisse, con gli anelli che gli danno il profilo più riconoscibile del cielo."),
       ]),
    mk("spazio", "v5-astronauti-alti",
       "Nello spazio gli astronauti diventano più alti", ["più alti"],
       "Al rientro sulla Terra molti astronauti scoprono di essere cresciuti di qualche centimetro. Non è un mito: è la colonna vertebrale che si rilassa.",
       "Senza il peso del corpo che li comprime, i dischi tra le vertebre si espandono e la schiena si allunga fino a 5 centimetri. L'effetto sparisce in pochi giorni sulla Terra, ma lascia dolori e rischi di ernia.",
       "",
       [
        ("Ventitré cuscinetti sotto pressione",
         "Tra le vertebre ci sono dischi di cartilagine pieni di acqua che fanno da ammortizzatori. Durante il giorno, in piedi, il peso li schiaccia e perdi circa un centimetro; di notte, sdraiato, riassorbono liquido e lo recuperi. In orbita è come essere sdraiati per sei mesi di fila."),
        ("Fino a cinque centimetri",
         "Senza compressione i dischi si gonfiano al massimo e le curve naturali della colonna si distendono. Gli astronauti guadagnano in media tre centimetri, con punte di cinque. Le tute vengono cucite con margini per farci stare la nuova statura, e i sedili della capsula di rientro tengono conto della crescita."),
        ("Non è tutto un vantaggio",
         "Oltre metà degli astronauti soffre di mal di schiena in orbita. I muscoli profondi che stabilizzano la colonna, non più sollecitati, si indeboliscono. Al rientro, quando il peso torna di colpo su dischi gonfi e muscoli deboli, il rischio di ernia è quadruplo rispetto alla popolazione generale."),
        ("Anche il viso cambia",
         "Con la stessa logica, i fluidi che la gravità di solito tiene nelle gambe salgono verso la testa: il viso si gonfia, le gambe si assottigliano, e la pressione dentro il cranio spinge sui bulbi oculari alterando la vista. Il corpo umano è progettato per un pianeta, e lo ricorda in ogni dettaglio."),
       ]),
    mk("spazio", "v5-corpo-senza-tuta",
       "Cosa succede davvero a un corpo nello spazio senza tuta", ["senza tuta"],
       "Nei film esplodi, congeli all'istante o il sangue bolle. La realtà è meno spettacolare e più strana: avresti circa quindici secondi lucidi.",
       "Nel vuoto non si esplode: la pelle tiene. Si perde conoscenza in 15 secondi per mancanza di ossigeno, si gonfia il corpo, e la morte arriva in un paio di minuti. Il freddo, invece, è l'ultimo dei problemi.",
       "",
       [
        ("Non trattenere il respiro",
         "L'istinto sarebbe trattenere il fiato, ma è la cosa peggiore: senza pressione esterna l'aria nei polmoni si espande e li lacera. Chi è stato esposto per errore al vuoto in camere di test racconta di aver sentito la saliva bollire sulla lingua, perché a pressione zero l'acqua evapora a temperatura corporea."),
        ("Quindici secondi di lucidità",
         "Il sangue continua a circolare ma non trasporta più ossigeno ai tessuti: il cervello ne ha riserva per circa 15 secondi, poi si perde coscienza. Il corpo si gonfia fino al doppio del volume perché l'acqua nei tessuti tende a evaporare, ma la pelle è abbastanza elastica da non rompersi. Niente esplosioni."),
        ("Il sangue non bolle",
         "Il sistema circolatorio è chiuso e mantiene una sua pressione: il sangue resta liquido. È la ragione per cui un'esposizione breve, sotto i 60-90 secondi, può essere sopravvissuta se si viene ripressurizzati in fretta. È successo davvero, nel 1966, a un tecnico NASA: svenne dopo 14 secondi e si riprese senza danni."),
        ("Il freddo arriva lentamente",
         "Lo spazio è a -270 gradi, ma è vuoto: non c'è aria che porti via il calore per contatto. Il corpo perde calore solo irraggiando, un processo lento. Un corpo abbandonato nello spazio impiegherebbe ore a congelare e, al Sole, si scalderebbe da un lato e gelerebbe dall'altro."),
       ]),
    mk("spazio", "v5-pioggia-diamanti",
       "Su Nettuno e Urano piovono diamanti", ["diamanti"],
       "A miliardi di chilometri dal Sole, dentro due pianeti color ghiaccio, il carbonio viene schiacciato fino a diventare la pietra più preziosa della Terra. E poi cade.",
       "Nelle profondità di Urano e Nettuno, pressione e temperatura spezzano il metano e comprimono il carbonio in diamanti, che affondano verso il nucleo come una grandine preziosa. Esperimenti di laboratorio hanno riprodotto il fenomeno.",
       "",
       [
        ("Un oceano di metano compresso",
         "Urano e Nettuno sono 'giganti di ghiaccio': sotto l'atmosfera c'è un denso strato di acqua, ammoniaca e metano compressi. A circa 10.000 chilometri di profondità la pressione è milioni di volte quella terrestre e la temperatura supera i 5.000 gradi: condizioni in cui le molecole si comportano in modi impossibili in superficie."),
        ("Il metano si spezza",
         "Il metano è un atomo di carbonio legato a quattro di idrogeno. A quelle pressioni i legami si rompono: l'idrogeno scappa e gli atomi di carbonio, liberi e compressi, si dispongono nel reticolo più compatto che conoscono, quello del diamante. Cristalli che crescono e, più densi di ciò che li circonda, cominciano a cadere."),
        ("Ricreato con un laser",
         "Nel 2017 un gruppo di ricercatori ha sparato impulsi laser su una plastica ricca di carbonio e idrogeno, simulando per un miliardesimo di secondo le condizioni interne di Nettuno. I raggi X hanno mostrato nascere nanodiamanti in tempo reale. Era la prima prova diretta che la pioggia di diamanti è fisicamente possibile."),
        ("Un calore che si spiega",
         "Nettuno emette più energia di quanta ne riceva dal Sole, e nessuno sapeva bene perché. I diamanti che affondano attraverso migliaia di chilometri liberano energia per attrito, come una pioggia che riscalda invece di raffreddare. Attorno al nucleo potrebbe esserci uno strato di diamante spesso quanto un continente."),
       ]),
    mk("spazio", "v5-tempesta-giove",
       "Su Giove c'è una tempesta più grande della Terra da almeno 350 anni", ["tempesta", "350 anni"],
       "La Grande Macchia Rossa gira da quando la osservavano con i primi telescopi. Dentro ci starebbe il nostro pianeta intero, e non sappiamo ancora perché non si spegne.",
       "La Grande Macchia Rossa è un anticiclone largo circa 16.000 chilometri con venti oltre i 400 km/h. Su Giove non c'è terra che rallenti le tempeste, e la macchia si nutre di quelle più piccole che inghiotte.",
       "",
       [
        ("Un anticiclone alto quanto un pianeta",
         "La macchia è una zona di alta pressione che ruota in senso antiorario, completando un giro ogni sei giorni terrestri. Si innalza di otto chilometri sopra le nubi circostanti e affonda per almeno 300 verso il basso, secondo le misure della sonda Juno. È una torre di gas in rotazione."),
        ("Perché non si consuma",
         "Sulla Terra gli uragani muoiono quando toccano terra e perdono la fonte di calore e umidità. Giove non ha una superficie: la tempesta gira sopra un oceano di idrogeno senza attrito. In più le correnti a getto ai suoi lati scorrono in direzioni opposte e la tengono intrappolata come una biglia in una scanalatura, alimentandola."),
        ("Il rosso resta un mistero",
         "Il colore potrebbe nascere da composti di ammoniaca e acetilene colpiti dalla luce ultravioletta in alta quota, una sorta di scottatura chimica. Ma la formula esatta non è nota, e la tonalità cambia: dal mattone al salmone chiaro, a seconda degli anni."),
        ("Si sta restringendo",
         "Nel 1800 la macchia era larga circa 40.000 chilometri, tre Terre affiancate. Oggi ne misura circa 16.000 e si è fatta più tonda. Alcuni pensano che sparirà entro qualche decennio, altri che si stia semplicemente riorganizzando. Ogni notte serena, con un buon telescopio, puoi vedere una cosa che potrebbe non esistere più tra cent'anni."),
       ]),

    # ------------------------------ TECNOLOGIA ------------------------------
    mk("tecnologia", "v5-qr-rovinato",
       "Come fa un codice QR a funzionare anche se è graffiato o sporco?", ["codice QR", "graffiato"],
       "Un adesivo mezzo strappato, una macchia di caffè, un angolo piegato: il telefono lo legge lo stesso. Non è fortuna, è matematica progettata per fallire bene.",
       "Il QR contiene dati ridondanti grazie a un codice di correzione d'errore: fino al 30% dei quadratini può mancare e il messaggio viene ricostruito. I tre quadrati grandi servono a orientarsi.",
       "",
       [
        ("I tre angoli che orientano",
         "I quadrati grandi in tre angoli sono i marcatori di posizione: permettono alla fotocamera di capire dove inizia il codice, quanto è inclinato e a che distanza si trova. Li riconosce da qualsiasi angolazione perché il rapporto tra nero e bianco al loro interno è sempre 1:1:3:1:1. Il quarto angolo manca di proposito: così si capisce l'orientamento."),
        ("Bit sparsi per la griglia",
         "Il testo o il link vengono convertiti in una sequenza di zero e uno, quindi disposti nella griglia a zig-zag partendo dal basso a destra. Prima della stampa una maschera inverte alcuni quadratini per evitare grandi zone tutte nere o tutte bianche che confonderebbero la fotocamera."),
        ("La magia di Reed-Solomon",
         "Insieme ai dati, il QR memorizza blocchi extra calcolati con l'algoritmo Reed-Solomon, lo stesso dei CD e delle trasmissioni spaziali. Sono come un riassunto matematico dei dati: se mancano alcuni pezzi, il riassunto permette di ricalcolare quelli persi. Al livello massimo di correzione, si può perdere fino al 30% del codice."),
        ("Per questo puoi metterci un logo",
         "I QR con un'immagine al centro sfruttano proprio la ridondanza: il logo copre una parte dei dati e il lettore la ricostruisce come se fosse un graffio. Il limite è che ogni quadratino perso è un margine in meno: un QR con logo grande e un po' sporco può smettere di funzionare."),
       ]),
    mk("tecnologia", "v5-streaming-sgrana",
       "Perché il video in streaming a volte diventa sgranato per qualche secondo?", ["streaming", "sgranato"],
       "La partita si trasforma in una poltiglia di quadrati, poi torna nitida. Non è il tuo schermo: è un compromesso che il servizio prende ogni due secondi.",
       "Il video viene inviato a pezzi di pochi secondi in più qualità diverse. Se la connessione rallenta, il player sceglie la versione più leggera, quella con meno dettagli, per non fermarsi. È lo streaming adattivo.",
       "",
       [
        ("Un film è troppo grosso",
         "Un'ora di video non compresso peserebbe centinaia di gigabyte. La compressione salva per intero solo un fotogramma ogni tanto e, per gli altri, memorizza soltanto cosa è cambiato. In una scena statica cambia poco e si risparmia; in una folla in movimento cambia tutto e servono molti più dati."),
        ("Lo stesso film in sei versioni",
         "I server conservano il video in più qualità, da bassissima risoluzione a 4K, spezzato in segmenti di due-sei secondi. Il player scarica il segmento successivo mentre guardi quello corrente e misura quanto è arrivato in fretta. Se la connessione regge, sale di qualità; se rallenta, scende."),
        ("Meglio sgranato che fermo",
         "La ricerca sugli spettatori è chiara: una pausa con la rotellina è vissuta molto peggio di un calo temporaneo di qualità. Per questo il player preferisce mostrare un segmento a bassa risoluzione, pieno di quadrati, piuttosto che fermarsi. Appena la rete migliora, il segmento successivo torna nitido."),
        ("Perché proprio la partita",
         "Negli eventi live il ritardo deve essere minimo, quindi il player tiene pochissimi secondi di scorta e ha meno margine per assorbire i rallentamenti. E lo sport, con l'erba piena di dettagli e telecamere in movimento, è tra i contenuti più difficili da comprimere: i quadrati si vedono di più."),
       ]),
    mk("tecnologia", "v5-contactless",
       "Come fa la carta contactless a pagare senza batteria?", ["contactless", "batteria"],
       "Nessuna pila, nessun cavo, nessun interruttore. Eppure appoggiandola al lettore la carta calcola, firma e risponde in meno di mezzo secondo.",
       "Il lettore emette un campo magnetico che induce corrente nell'antenna della carta: è il lettore ad alimentarla. Il chip si accende, esegue un calcolo crittografico unico per quella transazione e risponde via radio.",
       "",
       [
        ("L'antenna nascosta",
         "Dentro la carta corre una spirale di filo di rame lungo i bordi, collegata al chip dorato. Quando la avvicini al lettore, il campo magnetico oscillante di quest'ultimo, a 13,56 megahertz, attraversa la spirale e ci induce una corrente. È lo stesso principio del caricabatterie wireless del telefono, in miniatura."),
        ("Un computer che vive un istante",
         "La corrente indotta è minuscola, ma il chip consuma pochissimo. In quei millisecondi si avvia, riceve i dati della transazione dal lettore e genera un codice di autorizzazione firmato con una chiave segreta che non esce mai dalla carta. Poi trasmette la risposta modulando il campo, e si spegne quando la allontani."),
        ("Perché non basta copiarla",
         "Il codice che la carta produce cambia a ogni pagamento: include un contatore e i dati specifici di quella transazione. Anche se qualcuno lo intercettasse, non potrebbe riutilizzarlo. È il motivo per cui il contactless è più sicuro della vecchia banda magnetica, che invece si può clonare con un lettore da pochi euro."),
        ("Quattro centimetri di portata",
         "Il campo del lettore decade molto rapidamente con la distanza: oltre pochi centimetri non c'è energia sufficiente ad accendere il chip. Per questo il famoso 'furto passando accanto in metropolitana' è tecnicamente molto difficile. I portafogli schermati aggiungono un margine, ma il vero limite è la fisica."),
       ]),
    mk("tecnologia", "v5-cuffie-rumore",
       "Come fanno le cuffie a cancellare il rumore?", ["cancellare", "rumore"],
       "Indossi le cuffie in aereo e il rombo dei motori sparisce, senza che ci sia più gomma o imbottitura. Quel silenzio è un suono aggiunto, non tolto.",
       "Un microfono ascolta il rumore esterno, un chip ne calcola l'onda inversa e la riproduce nell'auricolare. Cresta contro valle, le due onde si annullano. Funziona benissimo sui suoni costanti e bassi, molto meno su quelli improvvisi.",
       "",
       [
        ("Il suono è un'onda, e le onde si sommano",
         "Un suono è una serie di compressioni e rarefazioni dell'aria. Se ne aggiungi uno identico ma sfasato di mezza onda, dove uno spinge l'altro tira: la pressione totale resta ferma e non senti nulla. È la stessa interferenza distruttiva che rende nere le bolle di sapone, applicata all'aria."),
        ("Una corsa contro il tempo",
         "Il microfono esterno cattura il rumore un attimo prima che raggiunga il tuo orecchio. Il processore ha frazioni di millisecondo per invertire l'onda e mandarla al piccolo altoparlante. Un secondo microfono dentro il padiglione controlla il risultato e corregge. Tutto questo migliaia di volte al secondo."),
        ("Perché il rombo sì e le voci no",
         "Il rumore di un motore o di un treno è grave e regolare: facile da prevedere e da invertire. Le voci, i clacson e il pianto di un bambino sono acuti e imprevedibili: quando il chip ha calcolato la risposta, l'onda è già cambiata. Per le alte frequenze si affidano ancora alla vecchia gomma dell'imbottitura."),
        ("Nato per i piloti",
         "Il primo prototipo fu costruito nel 1978 da Amar Bose durante un volo, infastidito dal rumore che rovinava le sue nuove cuffie. Le prime versioni servirono ai piloti di aerei leggeri, poi ai passeggeri, oggi a chi lavora in ufficio. La sensazione di pressione che alcuni provano è il cervello che nota un silenzio troppo perfetto per essere naturale."),
       ]),
    mk("tecnologia", "v5-foto-notturne",
       "Come fa il telefono a scattare foto luminose di notte?", ["foto", "notte"],
       "Il sensore è grande quanto un'unghia, molto più piccolo di quello di una vera macchina fotografica. Eppure la modalità notte tira fuori dettagli che il tuo occhio non vede.",
       "La modalità notte non scatta una foto: ne scatta decine in pochi secondi, le allinea compensando il tremore della mano e le somma. Il segnale si accumula, il rumore casuale si media e sparisce.",
       "",
       [
        ("Il problema è la luce che manca",
         "Un sensore trasforma fotoni in elettroni. Di notte ne arrivano pochi e il segnale è debole rispetto al 'rumore' elettronico casuale del sensore: ecco i puntini colorati delle foto scure. Allungare il tempo di esposizione raccoglie più luce, ma la mano trema e tutto diventa mosso."),
        ("Molte foto brevi invece di una lunga",
         "La soluzione è scattare una raffica di 10-30 immagini brevi, ognuna abbastanza rapida da non risultare mossa. Il software le confronta, individua i dettagli comuni e le sovrappone pixel per pixel, correggendo i piccoli spostamenti della mano. È come tenere il telefono perfettamente fermo per tre secondi."),
        ("Il rumore si cancella da solo",
         "Il segnale vero, la scena, è uguale in ogni scatto e sommandolo cresce. Il rumore invece è casuale: in un fotogramma un pixel è troppo chiaro, nell'altro troppo scuro. Facendo la media si annulla. Con 16 scatti, il rapporto tra segnale e rumore migliora di quattro volte."),
        ("Un po' di invenzione",
         "L'ultimo passo è l'intelligenza artificiale: riconosce cieli, volti e testi e li tratta in modo diverso, riducendo il rumore nel cielo ma preservando i dettagli della pelle. A volte esagera e aggiunge nitidezza che non esisteva. La foto notturna è un'interpretazione della scena, non una registrazione."),
       ]),
]

LESSONS = [
    # ------------------------------ SCIENZA ------------------------------
    L("scienza", "v5-lez-stati-materia",
      "Solido, liquido, gas: i passaggi di stato spiegati bene", ["passaggi di stato"],
      "Il ghiaccio si scioglie, l'acqua bolle, il vapore si condensa sul vetro. Dietro c'è una sola idea: quanto si agitano le molecole.",
      "Capire cosa cambia tra solido, liquido e gas e prevedere cosa succede scaldando o raffreddando una sostanza.",
      "Lo stato dipende dall'equilibrio tra l'agitazione delle molecole e le forze che le tengono insieme. Scaldare significa agitare di più: si passa da solido a liquido a gas. Raffreddare fa il percorso inverso.",
      [
       ("Passo 1 — Le molecole non stanno mai ferme",
        "Anche in un cubetto di ghiaccio le molecole vibrano. La temperatura misura proprio questa agitazione. Nel solido vibrano restando al loro posto, come persone che ballano sul posto in una folla stretta. Le forze di attrazione tra molecole vincono e la forma resta fissa."),
       ("Passo 2 — Il liquido: liberi ma vicini",
        "Scaldando, l'agitazione cresce fino a rompere l'ordine: le molecole restano a contatto ma scivolano l'una sull'altra. Il liquido prende la forma del recipiente ma mantiene il suo volume. La temperatura a cui succede, il punto di fusione, è una carta d'identità: 0 gradi per l'acqua, 1.064 per l'oro."),
       ("Passo 3 — Il gas: ognuno per sé",
        "Con ancora più energia le molecole si staccano del tutto e volano libere, riempiendo tutto lo spazio disponibile. L'evaporazione avviene a ogni temperatura, solo dalla superficie; l'ebollizione avviene quando anche dentro il liquido si formano bolle di vapore. In montagna, con meno pressione, l'acqua bolle a 90 gradi e la pasta cuoce peggio."),
       ("Passo 4 — Il percorso inverso e i salti",
        "Raffreddando, il gas condensa in liquido, come il vapore sullo specchio del bagno, e il liquido solidifica. Alcune sostanze saltano un passaggio: il ghiaccio secco passa da solido a gas direttamente, per sublimazione, ed è il fumo bianco degli spettacoli. La brina che si forma sui vetri d'inverno è il salto inverso, dal vapore direttamente al ghiaccio."),
      ]),
    L("scienza", "v5-lez-reazione-chimica",
      "Come riconoscere una reazione chimica: 4 segnali", ["reazione chimica"],
      "Sciogliere lo zucchero nel caffè e far cuocere un uovo sembrano cose simili. Solo una delle due è una reazione chimica. Ecco come distinguerle.",
      "Distinguere una trasformazione fisica da una reazione chimica e riconoscere i segnali che una reazione sta avvenendo.",
      "In una reazione chimica gli atomi si ricombinano in molecole nuove e non si torna indietro facilmente. I segnali sono cambio di colore, produzione di gas, formazione di un solido, calore o luce.",
      [
       ("Passo 1 — Fisico o chimico?",
        "Lo zucchero sciolto nel caffè è ancora zucchero: se fai evaporare l'acqua lo ritrovi. È una trasformazione fisica. L'uovo cotto invece non torna crudo: le proteine hanno cambiato struttura in modo permanente. Il test è semplice: le sostanze di partenza esistono ancora o sono diventate qualcos'altro?"),
       ("Passo 2 — Il gas e il colore",
        "Il bicarbonato nell'aceto frigge: quelle bolle sono anidride carbonica appena creata, un gas che prima non c'era. La mela tagliata che diventa marrone, il ferro che arrugginisce, il pane che si dora: ogni volta che compare un colore nuovo, atomi si sono ricombinati."),
       ("Passo 3 — Il solido che appare e il calore",
        "Se mescoli due liquidi trasparenti e compare qualcosa di torbido o un sedimento, si è formato un composto insolubile: un precipitato. Se il contenitore si scalda da solo, come una mano che stringe il calcare con l'acido, o si raffredda, come una busta di ghiaccio istantaneo, l'energia dei legami è cambiata."),
       ("Passo 4 — Niente si perde",
        "In ogni reazione il numero di atomi di ciascun elemento resta identico: si scambiano solo i partner. La legna che brucia sembra sparire, ma il suo carbonio è tutto nell'anidride carbonica salita nel camino e il suo idrogeno nel vapore. Se pesassi tutto, gas compresi, il totale sarebbe uguale a prima."),
      ]),
    L("scienza", "v5-lez-pressione",
      "La pressione: perché la pentola a pressione cucina in metà tempo", ["pressione"],
      "Una pentola con il coperchio bloccato, un fischio, e il bollito è pronto in venti minuti. Dietro c'è un concetto che spiega anche le orecchie tappate in aereo.",
      "Capire cos'è la pressione, come si lega alla temperatura di ebollizione e dove la incontriamo ogni giorno.",
      "La pressione è forza spalmata su una superficie. Nei gas nasce dagli urti delle molecole sulle pareti. Aumentare la pressione alza la temperatura di ebollizione dell'acqua: a 2 atmosfere bolle a 120 gradi e il cibo cuoce più in fretta.",
      [
       ("Passo 1 — Forza divisa per superficie",
        "Un tacco a spillo e una scarpa da ginnastica reggono la stessa persona, ma solo il primo lascia un buco nel parquet: la stessa forza si concentra su una superficie minima. La pressione è forza divisa per area. Per questo un chiodo ha la punta e un letto di chiodi non fa male: la forza si spalma su centinaia di punte."),
       ("Passo 2 — I gas spingono ovunque",
        "Nell'aria miliardi di molecole rimbalzano sulle superfici: la somma degli urti è la pressione atmosferica, circa un chilo per centimetro quadrato. Non la senti perché spinge uguale dentro e fuori il tuo corpo. In aereo la pressione della cabina cala e l'aria nell'orecchio medio spinge il timpano verso fuori: ecco la sensazione tappata."),
       ("Passo 3 — Bollire dipende dalla pressione",
        "L'acqua bolle quando il suo vapore spinge quanto l'aria sopra di lei. Meno pressione, bolle prima: a 3.000 metri a 90 gradi. Più pressione, bolle dopo. La pentola a pressione blocca il vapore, la pressione sale a circa 2 atmosfere e l'acqua resta liquida fino a 120 gradi: i tessuti duri della carne si sciolgono in metà tempo."),
       ("Passo 4 — Dove la ritrovi",
        "La valvola che fischia rilascia il vapore in eccesso per non superare il limite. La pressione delle gomme distribuisce il peso dell'auto; quella del sangue si misura in millimetri di mercurio; a 10 metri sott'acqua raddoppia, per questo i sub risalgono lentamente. È la stessa grandezza, in scenari diversi."),
      ]),
    L("scienza", "v5-lez-calore-temperatura",
      "Calore e temperatura non sono la stessa cosa", ["calore", "temperatura"],
      "Una scintilla a 1.000 gradi non ti brucia; una vasca a 60 sì. Se ti sembra un paradosso, è perché confondi due parole che usiamo come sinonimi.",
      "Distinguere calore e temperatura e usare la differenza per capire fenomeni quotidiani, dal mare che rinfresca al termosifone.",
      "La temperatura dice quanto si agitano in media le molecole; il calore è l'energia che passa da un corpo più caldo a uno più freddo. Un corpo piccolo può essere caldissimo ma contenere poca energia.",
      [
       ("Passo 1 — Temperatura: la media",
        "La temperatura misura l'agitazione media delle molecole di un corpo. Non dipende da quanto è grande: un cucchiaio e una pentola d'acqua bollente sono entrambi a 100 gradi. È un'intensità, come il volume della musica, non una quantità."),
       ("Passo 2 — Calore: l'energia in viaggio",
        "Il calore è energia che passa da un oggetto più caldo a uno più freddo, fino a quando le temperature si eguagliano. La pentola contiene molta più energia del cucchiaio, perché ha molte più molecole agitate. Una scintilla è a 1.000 gradi ma ha così poche molecole che cede alla pelle un'energia trascurabile."),
       ("Passo 3 — Il calore specifico",
        "Non tutti i materiali si scaldano allo stesso modo. Per alzare di un grado un chilo d'acqua serve quattro volte l'energia che serve per un chilo d'aria, e dieci volte quella per il ferro. L'acqua è una spugna di energia: il mare si scalda lentamente d'estate e la rilascia lentamente d'inverno, rendendo le coste più miti."),
       ("Passo 4 — Applicalo in casa",
        "Un termosifone in ghisa resta caldo a lungo dopo lo spegnimento perché ha accumulato molto calore; uno in alluminio si raffredda in fretta. Una borsa d'acqua calda scalda il letto per ore mentre una pietra della stessa temperatura si esaurisce prima. Quando scegli tra due cose 'alla stessa temperatura', chiediti quanta energia contengono."),
      ]),
    L("scienza", "v5-lez-acidi-basi",
      "Acidi e basi in cucina: il pH spiegato con limone e bicarbonato", ["pH", "acidi"],
      "Il limone pizzica, il sapone è scivoloso, il bicarbonato spegne il bruciore di stomaco. Sono tutti indizi della stessa scala, quella del pH.",
      "Capire cosa misura il pH, riconoscere acidi e basi comuni e prevedere cosa succede quando si incontrano.",
      "Il pH misura la concentrazione di ioni idrogeno in una soluzione, da 0 a 14: sotto 7 è acido, 7 è neutro, sopra 7 è basico. Acidi e basi si neutralizzano a vicenda, spesso producendo gas o sale e acqua.",
      [
       ("Passo 1 — Una scala da 0 a 14",
        "Il pH conta quanti ioni idrogeno liberi ci sono in una soluzione. La scala è logaritmica: ogni punto in meno significa dieci volte più acido. Il succo di limone è a 2, il caffè a 5, l'acqua pura a 7, il sangue a 7,4, il sapone a 9-10, la candeggina a 12."),
       ("Passo 2 — Riconoscere un acido",
        "Gli acidi hanno sapore aspro e cedono ioni idrogeno: aceto, limone, pomodoro, bibite gassate, yogurt. Reagiscono con il calcare: per questo l'aceto pulisce il bollitore incrostato. Sciolgono anche lo smalto dei denti, che è il motivo per cui il dentista sconsiglia di sorseggiare bibite per ore."),
       ("Passo 3 — Riconoscere una base",
        "Le basi sono scivolose al tatto e spesso amare: bicarbonato, sapone, ammoniaca, candeggina. Sciolgono i grassi trasformandoli in molecole solubili in acqua, che è esattamente il modo in cui il sapone lava. Le più forti, come la soda caustica, sono pericolose quanto un acido forte."),
       ("Passo 4 — Quando si incontrano",
        "Acido più base dà neutralizzazione. Bicarbonato nell'aceto: schiuma di anidride carbonica, ed è il lievito istantaneo dei dolci. Bicarbonato nello stomaco: neutralizza l'acido in eccesso e il bruciore passa. Il cavolo rosso cambia colore da rosso a blu a verde con il pH: bollilo e avrai un indicatore fatto in casa per testare tutto ciò che trovi in cucina."),
      ]),

    # ------------------------------ SPAZIO ------------------------------
    L("spazio", "v5-lez-eclissi",
      "Le eclissi: come nascono e perché non succedono ogni mese", ["eclissi"],
      "Il Sole sparisce in pieno giorno, la Luna diventa rossa. Due spettacoli che i nostri antenati temevano e che oggi possiamo prevedere al secondo.",
      "Capire la differenza tra eclissi solare e lunare, perché avvengono e perché sono rare.",
      "Un'eclissi solare avviene quando la Luna passa tra Terra e Sole e proietta la sua ombra su di noi; una lunare quando la Terra si mette tra Sole e Luna. Non succede ogni mese perché l'orbita lunare è inclinata di 5 gradi.",
      [
       ("Passo 1 — Tre corpi in fila",
        "Un'eclissi è una questione di ombre. Quando la Luna nuova passa esattamente tra Terra e Sole, la sua ombra tocca la superficie terrestre: eclissi solare. Quando la Luna piena entra nel cono d'ombra della Terra: eclissi lunare. Servono tre corpi perfettamente allineati."),
       ("Passo 2 — Perché non tutti i mesi",
        "La Luna gira intorno alla Terra ogni mese, ma la sua orbita è inclinata di circa 5 gradi rispetto a quella terrestre intorno al Sole. Quasi sempre, quando è nuova o piena, passa un po' sopra o un po' sotto la linea. Solo due volte l'anno l'incrocio cade nel punto giusto: sono le stagioni delle eclissi."),
       ("Passo 3 — Solare: una coincidenza fortunata",
        "Il Sole è 400 volte più grande della Luna ma anche 400 volte più lontano: nel cielo hanno quasi la stessa dimensione. Per questo la Luna può coprirlo esattamente e mostrare la corona, l'atmosfera del Sole. L'ombra è larga appena 100-200 chilometri e corre sulla Terra a 1.700 km/h: la totalità dura pochi minuti e si vede solo da una fascia stretta."),
       ("Passo 4 — Lunare: la Luna rossa",
        "L'ombra della Terra è enorme e l'eclissi lunare si vede da tutto l'emisfero notturno, per ore. La Luna non sparisce ma diventa rossa: l'atmosfera terrestre piega verso di lei un po' di luce solare, filtrando i blu, esattamente come in un tramonto. Stai vedendo tutti i tramonti e le albe del mondo proiettati contemporaneamente sulla Luna."),
      ]),
    L("spazio", "v5-lez-sistema-solare-scala",
      "Il Sistema Solare in scala: quanto è vuoto davvero", ["in scala"],
      "Nei poster i pianeti sono in fila, vicini, colorati. Nella realtà, se il Sole fosse un pallone da calcio, la Terra sarebbe un granello di sabbia a 25 metri.",
      "Costruire un modello mentale corretto delle distanze e delle dimensioni nel Sistema Solare.",
      "Se il Sole fosse un pallone di 22 cm, la Terra sarebbe un granello di 2 mm a 24 metri, Giove una biglia a 125 metri e Nettuno un pisello a 720 metri. Lo spazio è quasi tutto vuoto.",
      [
       ("Passo 1 — Riduci il Sole a un pallone",
        "Il Sole ha un diametro di 1,4 milioni di chilometri. Facciamolo diventare un pallone da calcio di 22 centimetri: ogni centimetro vale circa 63.000 chilometri. Questo è il nostro metro. Tutto il resto va ridotto con la stessa proporzione."),
       ("Passo 2 — I pianeti interni",
        "Mercurio è un granello di 0,8 millimetri a 9 metri dal pallone. Venere e la Terra sono granelli di 2 millimetri a 17 e 24 metri. Marte, un millimetro, a 36 metri. La Luna, mezzo millimetro, a 6 centimetri dalla Terra. Tra questi granelli non c'è nulla: solo vuoto e luce."),
       ("Passo 3 — I giganti lontani",
        "Giove, il più grande, è una biglia di 2,2 centimetri a 125 metri. Saturno, 1,9 centimetri, a 230 metri. Urano e Nettuno, poco meno di un centimetro, a 460 e 720 metri. Per percorrere il modello devi camminare dieci minuti, e i pianeti che incontri stanno tutti in una mano."),
       ("Passo 4 — Oltre Nettuno, il nulla",
        "La sonda Voyager 1, l'oggetto umano più lontano, nel modello sarebbe a circa 4 chilometri dal pallone. La stella più vicina, Proxima Centauri, a 6.500 chilometri: un altro pallone da calcio dall'altra parte dell'oceano. Ogni volta che vedi un poster con i pianeti affiancati, ricorda che mente su tutto tranne che sull'ordine."),
      ]),
    L("spazio", "v5-lez-telescopio",
      "Come funziona un telescopio (e perché quello grande vede il passato)", ["telescopio"],
      "Non serve a ingrandire, come molti credono. Serve a raccogliere luce. E più ne raccoglie, più indietro nel tempo riesce a guardare.",
      "Capire cosa fa davvero un telescopio, la differenza tra lenti e specchi e perché osservare lontano significa osservare il passato.",
      "Un telescopio è un secchio per la luce: più è largo, più fotoni raccoglie e più deboli sono gli oggetti che mostra. L'ingrandimento è secondario. La luce impiega tempo a viaggiare: guardare lontano è guardare indietro.",
      [
       ("Passo 1 — Un secchio per la luce",
        "La tua pupilla è larga 7 millimetri: raccoglie pochissima luce e le galassie restano invisibili. Un telescopio da 20 centimetri raccoglie 800 volte più luce, uno da 10 metri due milioni di volte. Il diametro è la caratteristica che conta: decide quanto debole può essere un oggetto per essere visto."),
       ("Passo 2 — Lenti o specchi",
        "I primi telescopi, come quello di Galileo, usavano lenti: la luce le attraversa e viene concentrata. Ma le lenti grandi sono pesanti, si deformano e separano i colori. Newton propose gli specchi: la luce rimbalza su una superficie curva verso un punto. Tutti i grandi telescopi moderni sono a specchio, sostenuto da dietro."),
       ("Passo 3 — L'ingrandimento è l'ultimo dei problemi",
        "Ingrandire è facile: basta cambiare oculare. Ma ingrandire un'immagine debole e sfocata dà solo una macchia più grande. L'atmosfera, con la sua turbolenza, limita comunque il dettaglio: per questo i telescopi si costruiscono in alta montagna o si lanciano nello spazio, dove l'aria non tremola."),
       ("Passo 4 — Guardare il passato",
        "La luce viaggia a 300.000 chilometri al secondo, ma le distanze sono immense. La Luna la vedi com'era 1,3 secondi fa, il Sole 8 minuti fa, la galassia di Andromeda 2,5 milioni di anni fa. Il telescopio spaziale James Webb raccoglie luce partita 13 miliardi di anni fa: sta fotografando l'universo bambino, non come è ora."),
      ]),
    L("spazio", "v5-lez-costellazioni",
      "Le costellazioni di ogni stagione: cosa cercare nel cielo", ["costellazioni"],
      "Ogni sera il cielo cambia un po', e in un anno fa un giro completo. Bastano quattro figure, una per stagione, per non sentirsi più persi di notte.",
      "Riconoscere una costellazione guida per ciascuna stagione e capire perché il cielo notturno cambia durante l'anno.",
      "Il cielo notturno cambia perché la Terra gira intorno al Sole e di notte guardiamo in direzioni diverse. Inverno: Orione. Primavera: Leone. Estate: il Triangolo estivo. Autunno: Pegaso e Cassiopea.",
      [
       ("Passo 1 — Perché il cielo cambia",
        "Di notte guardi nella direzione opposta al Sole. Poiché la Terra gira intorno al Sole in un anno, quella direzione cambia di circa un grado al giorno. Le stelle che a gennaio sono alte a mezzanotte, a luglio sono dietro il Sole e invisibili. Le costellazioni non si muovono: siamo noi a cambiare finestra."),
       ("Passo 2 — Inverno: Orione, il cacciatore",
        "La figura più facile del cielo: tre stelle allineate a formare la cintura, quattro agli angoli. In alto a sinistra Betelgeuse, rossa; in basso a destra Rigel, azzurra. Prolunga la cintura verso il basso e trovi Sirio, la stella più luminosa del cielo. Sotto la cintura, una macchia sfumata: la nebulosa dove nascono stelle."),
       ("Passo 3 — Primavera ed estate",
        "In primavera cerca il Leone: un punto interrogativo rovesciato, la testa, con la stella Regolo alla base. In estate tre stelle brillanti formano il Triangolo estivo: Vega quasi allo zenit, Deneb nel Cigno, Altair nell'Aquila. In una notte senza luci, in mezzo passa la fascia lattiginosa della Via Lattea."),
       ("Passo 4 — Autunno e le stelle fisse",
        "In autunno domina il Grande Quadrato di Pegaso, quattro stelle di uguale luminosità, e vicino la W di Cassiopea. Alcune figure non tramontano mai dall'Italia: il Grande Carro e Cassiopea girano intorno alla Polare tutto l'anno, su lati opposti. Se ne trovi una, hai l'altra e hai il nord."),
      ]),
    L("spazio", "v5-lez-assenza-peso",
      "Perché gli astronauti fluttuano: non è assenza di gravità", ["fluttuano", "gravità"],
      "A 400 chilometri di altezza la gravità terrestre è ancora quasi al 90%. Eppure sulla Stazione Spaziale tutto galleggia. Il motivo è che stanno cadendo, in continuazione.",
      "Capire che in orbita la gravità è quasi intera e che il galleggiamento è l'effetto di una caduta libera perpetua.",
      "In orbita la gravità è circa il 90% di quella al suolo. La Stazione cade verso la Terra ma si muove così velocemente di lato, 28.000 km/h, che la curva della caduta segue la curva del pianeta. Cadere insieme a tutto ciò che ti circonda si sente come non pesare.",
      [
       ("Passo 1 — La gravità c'è, eccome",
        "La gravità diminuisce con la distanza, ma 400 chilometri sono pochi rispetto ai 6.400 del raggio terrestre. Sulla Stazione Spaziale peseresti il 90% di quanto pesi a casa. Se la Stazione si fermasse, cadrebbe a terra come un sasso. Quindi il galleggiamento ha un'altra spiegazione."),
       ("Passo 2 — La palla di cannone di Newton",
        "Immagina di sparare una palla di cannone in orizzontale da una montagna: cade descrivendo un arco. Più veloce spari, più lontano cade. A 28.000 chilometri l'ora l'arco della caduta ha la stessa curvatura della Terra: la palla cade in continuazione, ma il suolo si allontana sotto di lei alla stessa velocità. Questa è un'orbita."),
       ("Passo 3 — Cadere insieme",
        "La Stazione cade e gli astronauti dentro cadono con lei, alla stessa velocità. Non c'è pavimento che li fermi, quindi nessuna forza li spinge: è la sensazione di non avere peso. La stessa cosa provi per un istante in un ascensore che scende di colpo o su una montagna russa in cima alla discesa."),
       ("Passo 4 — Anche la Luna cade",
        "La Luna fa esattamente lo stesso: cade verso la Terra da 4,5 miliardi di anni, ma la sua velocità laterale la fa mancare il bersaglio ogni volta. E la Terra cade intorno al Sole. Un'orbita è una caduta che non finisce mai, non un posto dove la gravità si è spenta."),
      ]),

    # ------------------------------ TECNOLOGIA ------------------------------
    L("tecnologia", "v5-lez-bluetooth-wifi",
      "Bluetooth, Wi-Fi e 5G: cosa cambia davvero", ["Bluetooth", "Wi-Fi"],
      "Sono tutte onde radio, spesso alle stesse frequenze. Eppure una collega le cuffie, una la casa e una il mondo. La differenza è nel compromesso.",
      "Capire le differenze di portata, consumo e velocità tra Bluetooth, Wi-Fi e rete cellulare e scegliere quale usare quando.",
      "Bluetooth: pochi metri, consumo minimo, pochi dati, per accessori. Wi-Fi: decine di metri, molti dati, per la casa. Cellulare: chilometri, antenne dell'operatore, per muoverti. Stesse onde, potenze e protocolli diversi.",
      [
       ("Passo 1 — Tutte onde radio",
        "Bluetooth e Wi-Fi trasmettono spesso a 2,4 gigahertz, la stessa frequenza del forno a microonde. Il 5G usa bande da 700 megahertz fino a decine di gigahertz. Sono la stessa cosa della radio FM, solo a frequenze più alte e con dati digitali al posto della musica. La differenza sta in potenza, portata e regole di conversazione."),
       ("Passo 2 — Bluetooth: il sussurro",
        "Progettato per consumare pochissimo: una cuffia trasmette con un millesimo della potenza di un router. Per questo arriva a 10 metri e una batteria minuscola dura ore. Cambia frequenza 1.600 volte al secondo per evitare interferenze. Perfetto per collegare due dispositivi vicini, inadatto a scaricare un film."),
       ("Passo 3 — Wi-Fi: la voce di casa",
        "Il router grida più forte e usa canali più larghi: trasporta centinaia di megabit al secondo per decine di metri. La banda 5 gigahertz è più veloce ma attraversa peggio i muri; quella 2,4 arriva più lontano ma è affollata. Il Wi-Fi porta il segnale di internet, che arriva a casa via cavo o fibra, fino ai tuoi dispositivi."),
       ("Passo 4 — Cellulare: la rete che ti segue",
        "Le antenne dell'operatore coprono celle da qualche centinaio di metri a decine di chilometri e si passano il tuo telefono mentre ti muovi. Il 5G aggiunge frequenze alte per velocità enormi a corto raggio e tempi di risposta minimi. Consuma più batteria del Wi-Fi perché il telefono deve gridare fino all'antenna: quando sei a casa, il Wi-Fi ti fa risparmiare energia e dati."),
      ]),
    L("tecnologia", "v5-lez-due-fattori",
      "Autenticazione a due fattori: attivarla e non restare chiusi fuori", ["due fattori"],
      "La password da sola è come una serratura con la chiave sotto lo zerbino. Il secondo fattore è la catenella. Ecco come metterla senza perderne la chiave.",
      "Capire cos'è l'autenticazione a due fattori, scegliere il metodo più sicuro e conservare i codici di recupero.",
      "Il secondo fattore è qualcosa che hai, oltre a qualcosa che sai. App di codici o chiavette fisiche sono più sicure dell'SMS. Salva sempre i codici di recupero in un luogo sicuro offline.",
      [
       ("Passo 1 — Sapere, avere, essere",
        "Un accesso può basarsi su qualcosa che sai (password), qualcosa che hai (telefono, chiavetta) o qualcosa che sei (impronta, viso). Due fattori significano due categorie diverse. Una password rubata da sola non basta più: al ladro servirebbe anche il tuo telefono."),
       ("Passo 2 — SMS, app o chiavetta",
        "Il codice via SMS è meglio di niente, ma può essere intercettato clonando la SIM. Le app di autenticazione generano codici che cambiano ogni 30 secondi direttamente sul telefono, senza rete: molto più solide. Le chiavette fisiche USB o NFC sono il massimo: funzionano solo sul sito vero e sono immuni al phishing."),
       ("Passo 3 — Dove attivarlo per primo",
        "Parti dall'email principale: è la chiave che resetta tutte le altre password. Poi banca, account del telefono, social. Nelle impostazioni cerca 'sicurezza' o 'verifica in due passaggi', scansiona il QR con l'app e conferma con il primo codice. Cinque minuti per account."),
       ("Passo 4 — Non chiuderti fuori",
        "Ogni servizio ti dà codici di recupero monouso: stampali o scrivili e mettili con i documenti, mai solo sul telefono che potresti perdere. Alcune app di autenticazione fanno backup cifrato sul cloud: attivalo. Quando cambi telefono, trasferisci l'app prima di resettare il vecchio."),
      ]),
    L("tecnologia", "v5-lez-app-server",
      "Cosa succede quando tocchi un'app: il viaggio di una richiesta", ["richiesta", "server"],
      "Premi 'ordina' e in un secondo compare la conferma. In quel secondo la tua richiesta ha attraversato mezzo continente e parlato con tre computer diversi.",
      "Capire il dialogo tra un'app sul telefono e i server, cosa sono le API e perché a volte 'il servizio non risponde'.",
      "L'app sul telefono è solo l'interfaccia. Quando agisci, invia una richiesta via internet a un server, che controlla, salva nel database e risponde. Il formato di questo dialogo è l'API. Se il server è lento o giù, l'app resta ferma.",
      [
       ("Passo 1 — L'app è la vetrina",
        "Quello che vedi sullo schermo, pulsanti e liste, vive sul telefono. Ma i dati veri, il tuo saldo o gli ordini, stanno su computer remoti chiamati server. L'app è una vetrina che mostra ciò che il server le passa. Per questo senza connessione mostra dati vecchi o nulla."),
       ("Passo 2 — La richiesta in viaggio",
        "Toccando 'ordina', l'app compone un messaggio strutturato: chi sei, cosa vuoi, dove. Lo cifra e lo affida alla rete, che lo fa saltare di router in router fino al centro dati, spesso in un altro paese. Tutto in decine di millisecondi."),
       ("Passo 3 — API: la lingua comune",
        "Il server espone un menu di richieste possibili, con regole precise su come formularle e cosa risponde: è l'API. L'app del ristorante, il sito e il corriere parlano tutti con lo stesso server tramite la stessa API. Il server controlla la tua identità, verifica il pagamento, salva l'ordine nel database e risponde con un codice: 200 tutto bene, 401 non autorizzato, 500 errore interno."),
       ("Passo 4 — Quando non funziona",
        "Se vedi una rotellina infinita, il colpevole può essere ovunque lungo il percorso: il tuo Wi-Fi, un cavo interrotto, un server sovraccarico perché tutti ordinano alle 20. Le app moderne salvano una copia locale per mostrarti qualcosa anche offline, e riprovano da sole. Il pulsante 'aggiorna' spesso rimanda semplicemente la stessa richiesta."),
      ]),
    L("tecnologia", "v5-lez-motore-ricerca",
      "Come funziona un motore di ricerca in 4 passi", ["motore di ricerca"],
      "Digiti tre parole e in mezzo secondo hai la risposta tra miliardi di pagine. Non sta cercando in quel momento: ha già fatto il lavoro prima.",
      "Capire come un motore di ricerca scopre, archivia e ordina le pagine web e perché alcune compaiono prima.",
      "Programmi automatici visitano il web di continuo e copiano le pagine. Il testo viene spezzato in un indice, come quello di un libro. Alla tua domanda il motore consulta l'indice e ordina i risultati per rilevanza e autorevolezza.",
      [
       ("Passo 1 — I crawler esplorano",
        "Programmi chiamati crawler visitano le pagine, ne leggono il contenuto e seguono ogni link che trovano, poi ricominciano. Così scoprono pagine nuove e rivisitano quelle vecchie per vedere se sono cambiate. È un lavoro senza fine: il web ha centinaia di miliardi di pagine e ne aggiunge milioni al giorno."),
       ("Passo 2 — L'indice, come quello di un libro",
        "Per ogni parola trovata, il motore annota in quali pagine compare e dove. Cercare 'ricetta carbonara' non significa leggere il web: significa aprire la voce 'carbonara' nell'indice e incrociarla con 'ricetta'. È lo stesso trucco dell'indice analitico in fondo a un manuale, su scala planetaria."),
       ("Passo 3 — L'ordine dei risultati",
        "Migliaia di pagine contengono le tue parole. Chi viene primo? Conta quanto la pagina è pertinente: le parole nel titolo, la lingua, la freschezza. E conta l'autorevolezza: quante altre pagine affidabili la linkano. L'idea originale di Google fu proprio questa: un link è un voto. Oggi si aggiungono centinaia di segnali, inclusa la tua posizione."),
       ("Passo 4 — I risultati sono personali e pagati",
        "In cima spesso ci sono annunci: pagine che hanno pagato per comparire su quella parola, sempre segnalati. Sotto, i risultati organici, che possono variare in base a dove sei e cosa hai cercato prima. Aggiungere virgolette cerca la frase esatta, un meno esclude una parola: due trucchi che restringono davvero il campo."),
      ]),
    L("tecnologia", "v5-lez-backup",
      "Backup 3-2-1: non perdere mai più foto e documenti", ["backup", "3-2-1"],
      "Un telefono caduto in acqua, un computer rubato, un clic sbagliato. I tuoi ricordi digitali esistono in un solo posto? Allora non esistono ancora davvero.",
      "Impostare una strategia di backup semplice e affidabile seguendo la regola 3-2-1.",
      "Tre copie dei dati, su due supporti diversi, di cui una fuori casa. In pratica: originale sul telefono, copia su un disco esterno, copia sul cloud. Automatizza e verifica una volta l'anno che le copie si aprano.",
      [
       ("Passo 1 — Perché una copia non basta",
        "Dischi e telefoni si guastano: circa il 2-5% dei dischi muore ogni anno, e prima o poi tocca a tutti. Il cloud protegge dalla rottura ma non dai tuoi errori: se cancelli una foto sincronizzata, sparisce anche lì. Ransomware, furti e incendi colpiscono tutto ciò che sta in un solo posto."),
       ("Passo 2 — Tre copie, due supporti",
        "La regola: tre copie totali, di cui l'originale è una. Le altre due su supporti di tipo diverso, per esempio un disco esterno e il cloud. Così un difetto che colpisce un tipo di dispositivo non tocca l'altro. Un disco esterno da 2 terabyte costa quanto una cena e contiene la vita di una famiglia."),
       ("Passo 3 — Una copia lontana da casa",
        "L'ultimo numero, 1, è la copia fuori sede: se la casa brucia o viene svaligiata, il disco nel cassetto sparisce con il computer. Il cloud risolve il problema senza sforzo. In alternativa, un secondo disco a casa di un parente, aggiornato ogni pochi mesi."),
       ("Passo 4 — Automatizza e prova",
        "Il backup che dipende dalla tua memoria non verrà fatto. Attiva la sincronizzazione automatica delle foto sul cloud e programma il backup del computer sul disco esterno ogni notte in cui è collegato. Poi, una volta l'anno, prova davvero a recuperare un file: un backup mai testato è una speranza, non una copia."),
      ]),
]
