"""PAUSE — traduzioni EN per le storie di ARTE (v5.2)."""
from story_builder import en_entry as E

EN = {
    "arte-mona-lisa": E(
        "Why is the Mona Lisa the most famous painting in the world?",
        ["Mona Lisa", "famous"],
        "A small portrait behind bulletproof glass, surrounded every day by huge crowds. But what makes the Mona Lisa so special?",
        "The Mona Lisa is famous for Leonardo's revolutionary technique, but its worldwide fame arose above all from a sensational theft in 1911.",
        [
            ("A revolutionary portrait",
             "When Leonardo painted it, around 1503, portraits were stiff and in profile. He chose a three-quarter pose, a gaze directed straight at the viewer and an ambiguous smile. He used the sfumato technique: blurred outlines, soft transitions between light and shadow, with no sharp lines. The result is a face that seems alive, almost in motion."),
            ("The mystery of the smile",
             "That smile appears different depending on where you look: it seems stronger if you look at the eyes, fainter if you fix on the mouth. It's an effect linked to how the human eye perceives detail at the center and edges of vision. Leonardo, a scholar of optics and anatomy, exploited this to create an expression that changes as you observe it."),
            ("The theft that made it legendary",
             "For centuries it was admired by experts, but wasn't a mass icon. Everything changed in 1911, when a Louvre employee stole it, hiding it under his coat. For two years newspapers worldwide talked about it, its image everywhere. When it returned to the museum, it was by then the most sought-after woman on the planet."),
            ("The power of reproduction",
             "In the twentieth century the Mona Lisa's image was reproduced everywhere: ads, parodies, artworks. Artists like Duchamp and Warhol reinterpreted it. Every copy and every joke increased its fame, in a self-feeding cycle: it's famous because it's famous. Fame, at some point, becomes a force independent of the work itself."),
            ("The value of the original",
             "Today there are millions of perfect reproductions, yet crowds want to see 'that' panel. It's the allure of authenticity: knowing you're before the object touched by Leonardo. The aura of the original, said philosopher Walter Benjamin, doesn't transfer to copies. It's why we travel to see in person what we could look at in a photo."),
            ("The takeaway",
             "The Mona Lisa is masterpiece and media phenomenon at once. Its artistic greatness is real, but the planetary fame comes from a story of thefts, reproductions and collective curiosity. It reminds us that a work's value depends not only on the canvas, but on the stories built around it."),
        ]),
    "arte-golden-ratio": E(
        "The golden ratio: the number of beauty?",
        ["golden", "ratio"],
        "A number, 1.618, recurring in sunflowers, shells and countless artworks. Is it the secret formula of beauty or just a fascinating myth?",
        "The golden ratio is a proportion found in nature and used in art: pleasing to the eye, but its role as the 'secret of beauty' is partly legend.",
        [
            ("What the golden ratio is",
             "The golden ratio is a particular proportion: divide a line into two parts so that the ratio between the whole and the larger part equals that between the larger and the smaller part. The result is an irrational number, about 1.618, denoted by the Greek letter phi. It has fascinating mathematical properties that have intrigued scholars for millennia."),
            ("The spiral in nature",
             "Linked to the golden ratio is the Fibonacci sequence, where each number is the sum of the two before it. These numbers appear in the arrangement of sunflower seeds, in pine cone scales, in shell spirals. It's not mysticism: it's the most efficient way to pack growing elements without wasting space."),
            ("Its use in art",
             "Many artists and architects used proportions close to phi to organize their works, from the Parthenon to some Renaissance compositions. The idea is that rectangles and divisions based on the golden ratio look harmonious to the eye. The golden rectangle, in particular, is considered balanced and pleasant, neither too square nor too elongated."),
            ("Myth or reality?",
             "Beware, though: many alleged uses of the golden ratio in art are exaggerations or after-the-fact overinterpretations. With enough imagination, you can 'find' golden rectangles almost anywhere. Several masterpieces attributed to phi actually follow different proportions. The number's allure has fueled as many legends as facts."),
            ("Why we like it",
             "Experiments on aesthetic preferences give mixed results: some people prefer proportions close to the golden ratio, others don't. Beauty depends a lot on culture, context and habit. Probably the golden ratio is one of many pleasing proportions, not the one magic formula. But its recurrence in nature remains genuinely surprising."),
            ("The takeaway",
             "The golden ratio is real in mathematics and in nature, less certain as a universal key to beauty. It's worth knowing for the elegance of its numbers, without falling for the myth that it explains every masterpiece. Sometimes the real wonder lies precisely at the border between rigorous science and fascinating legend."),
        ]),
    "arte-color-psychology": E(
        "Why do colors make us feel emotions?",
        ["colors", "emotions"],
        "Red fires us up, blue calms, yellow cheers. Colors speak a language we feel before we understand it. But why?",
        "Colors influence emotions and behavior through biology and culture: instinctive reactions mix with learned meanings, different from society to society.",
        [
            ("Color is light, not matter",
             "Color isn't a fixed property of objects: it's how the brain interprets the different wavelengths of reflected light. An apple is 'red' because it absorbs almost all waves except the red ones, which bounce toward your eyes. Color, in a sense, exists inside us more than outside."),
            ("Instinctive reactions",
             "Some responses to colors seem biological. Red draws attention and can slightly speed the heartbeat: it's the color of blood and danger, useful to notice quickly. Blue and green tones, associated with sky and vegetation, tend to relax us. These are ancient links, rooted in our evolutionary history."),
            ("The weight of culture",
             "But much of the meaning of colors is learned and varies greatly. In the West white is purity and marriage; in many Eastern cultures it's the color of mourning. Red is luck in China and danger elsewhere. There's no universal dictionary of colors: each society writes its own over the course of its history."),
            ("Colors and marketing",
             "Companies choose colors with extreme care. Red and yellow stimulate appetite and urgency, often used in fast food. Blue communicates reliability, which is why it dominates banks and technology. It's not an exact science, but decades of testing have shown the right color can change how we perceive a product."),
            ("Colors and spaces",
             "Environments too use colors to influence us. Light walls make rooms seem bigger and brighter; warm tones make a place cozy; green in hospitals aims to reassure. The light and color of a space can change the mood of those who inhabit it, often without our noticing."),
            ("The takeaway",
             "Colors speak to us in a double voice: the instinctive one of biology and the learned one of culture. That's why the same shade can calm or alarm depending on who looks at it and where. Noticing how colors make you feel is a small exercise in awareness of the world around you."),
        ]),
    "arte-why-modern-art": E(
        "Why does modern art sometimes look like 'stuff I could do too'?",
        ["modern", "art"],
        "A canvas with a dot, a urinal in a museum, a banana taped to a wall. Provocation, scam or something deeper?",
        "Modern art shifts value from 'know-how' to the idea: understanding it requires knowing the context and the questions it poses, not just the visible technique.",
        [
            ("Art changes its question",
             "For centuries art sought to faithfully represent reality: the more realistic, the better it was. But with the invention of photography, this task passed to the machine. Artists then asked: if it's no longer necessary to copy the world, what is art for? The answer revolutionized everything that came after."),
            ("From making to the idea",
             "Modern and contemporary art often shifts value from technique to the idea. What counts is no longer just how hard the work is to make, but what thought, provocation or question it sets in motion. The urinal exhibited by Duchamp in 1917 wasn't beautiful: it was a challenge to the very concept of 'what can be art'."),
            ("The role of context",
             "An ordinary object, placed in a museum and signed by an artist, changes meaning. Context transforms the reading: it invites us to look at it with different eyes, to ask ourselves why it's there. Much contemporary art is precisely a reflection on this: who decides what is art, and by what rules?"),
            ("Simple doesn't mean easy",
             "'I could have done it too' is the most common reaction. But often the point isn't manual difficulty: it's having been the first to think of it, at that historical moment, with that meaning. After someone opens a path it seems obvious; before, it wasn't at all. The originality of the intuition is itself a value."),
            ("The market and value",
             "There's also an uncomfortable side: the art market moves enormous sums and sometimes inflates prices for financial and prestige reasons, more than artistic ones. Not everything expensive is deep, and not everything provocative has something to say. A pinch of healthy skepticism is legitimate."),
            ("The takeaway",
             "Modern art can irritate, and that's fine: often it wants to. Before dismissing it, though, it's worth asking what question it's posing. Sometimes you'll discover a powerful idea; other times, just cleverness. Learning to tell them apart is already a way of looking at art with more mature eyes."),
        ]),
    "arte-perspective": E(
        "Perspective: how do you paint depth on a flat surface?",
        ["perspective", "depth"],
        "A painting is a flat surface, yet it feels like we could step inside it. How did artists learn to fool our eyes so well?",
        "Perspective is a set of geometric rules, discovered in the Renaissance, that simulate depth on a flat surface by fooling the eye's perception.",
        [
            ("The problem of the plane",
             "A sheet or a canvas has two dimensions: width and height. The real world has three, with depth. For centuries painters struggled to render this third dimension: distant and near figures all looked on the same plane, as in many medieval paintings, beautiful but 'flattened'. A method to organize space was needed."),
            ("The Renaissance discovery",
             "In the fifteenth century, in Florence, Brunelleschi and then others formalized linear perspective. The idea: parallel lines receding into the distance seem to converge toward a point on the horizon, the vanishing point. By following precise geometric rules, one could build a believable space, where objects shrink with distance in a mathematically exact way."),
            ("How it fools the eye",
             "Perspective works because it imitates what our visual system actually does: distant objects project smaller images on the retina. By reproducing this effect on the canvas, the brain 'reads' depth even though it knows the surface is flat. It's a conscious illusion we willingly surrender to."),
            ("Other depth tricks",
             "Beyond lines, artists use other cues: distant objects are paler and blurrier (aerial perspective), warm colors seem to advance and cool ones to recede, overlap indicates what's in front. Combining these cues, a good painter can build deep and convincing spaces even without rigorous geometry."),
            ("Breaking the rules",
             "Once mastered, perspective has also been deliberately broken. Modern artists, from Cézanne to Picasso, showed multiple viewpoints together or flattened space on purpose, to express something new. Knowing the rules served precisely to surpass them consciously, not out of ignorance."),
            ("The takeaway",
             "Perspective is one of the most elegant meetings of art and mathematics: geometric rules in the service of emotion. Next time a painting seems 'real' to you, remember you're looking at an illusion built with care. And that behind that magic there was a true revolution of thought."),
        ]),
    "arte-why-statues-white": E(
        "Were Greek statues really white?",
        ["statues", "colors"],
        "We imagine classical antiquity as a world of pure white marble. What if I told you that temples and statues were actually painted in vivid colors?",
        "Greek and Roman statues were originally painted with bright colors: the white marble we admire today is the result of time, not the original look.",
        [
            ("The myth of white",
             "Museums, films and books have accustomed us to imagining antiquity as a world of immaculate marble. White statues, pristine temples, a pure and sober aesthetic. This image has deeply shaped the Western idea of classical elegance. But it's a misunderstanding born much later, in the Renaissance and above all the eighteenth century."),
            ("The truth of pigments",
             "Modern scientific analyses, with raking light and ultraviolet rays, have revealed traces of pigments on many ancient statues and temples. They were painted in bright reds, blues, yellows and gildings. The statues' eyes had colors, the clothes had decorative patterns. Antiquity was a riot of color, not an elegant desert of white."),
            ("Why the color disappeared",
             "Over the centuries the pigments degraded from exposure to weather, light and the soil in which many works lay buried. When they were rediscovered, the color had almost entirely vanished. Only the marble remained, and it was wrongly assumed it had always been that way."),
            ("A mistake that became taste",
             "Eighteenth-century scholars, admiring the by-then-white statues, theorized that the whiteness of marble was the supreme ideal of classical beauty. This idea influenced Neoclassical art and the collective imagination. Sometimes traces of color were even removed because considered 'impurities'. A misunderstanding was thus elevated to an aesthetic canon."),
            ("Reconstructing the colors",
             "Today archaeologists and restorers make colored reconstructions of ancient statues. At first they're jarring: they almost look kitsch to our eyes used to white. Yet they're closer to the original than the immaculate versions are. They force us to revise an image of antiquity we thought was certain."),
            ("The takeaway",
             "The whiteness of classical statues is an illusion created by time and by a misinterpretation. Art history is made not only of discoveries, but also of misunderstandings that become tradition. Seeing ancient statues in color is a healthy exercise: it reminds us the past was more alive and varied than we imagine."),
        ]),
    "arte-design-everyday": E(
        "Why are some objects easy to use and others not?",
        ["design", "objects"],
        "A door you push when it needed pulling. An incomprehensible remote. Good design is invisible; bad design makes us feel stupid every day.",
        "Good design communicates by itself how to use an object: when something is hard to use, it's almost always the project's fault, not the user's.",
        [
            ("Design is communication",
             "Every object 'tells' us how to use it, through its shape. A handle invites grasping, a flat plate pushing. When the message is clear, no instructions are needed: you get it at a glance. Design isn't just aesthetics, it's above all silent communication between the object and the user."),
            ("'Norman doors'",
             "Designer Don Norman gave a name to a widespread phenomenon: doors that confuse. Those with a pull handle that must be pushed, or with no clue as to which side opens. They're so common the problem bears his name. The lesson: if people constantly make mistakes, the flaw is in the design."),
            ("Affordances and signals",
             "Well-designed objects exploit 'affordances': visual hints about what you can do with them. A button looks pressable, a slider draggable. Adding clear signals, like a plate where to push or an arrow, guides without needing words. The good designer anticipates errors and makes them impossible."),
            ("Feedback matters",
             "A good object responds to our actions: a click when you press, a light that turns on, a vibration. This feedback confirms something happened. Its absence breeds uncertainty: should I press again? Did it work? Many daily frustrations come from mute objects that don't tell us what's happening."),
            ("Simplicity is hard",
             "Making something easy to use is far more complex than filling it with functions. It requires removing, not adding; understanding how real people think, not engineers. The most beloved products often do few things but do them very well, hiding behind apparent ease an enormous amount of design work."),
            ("The takeaway",
             "Next time you fumble with a door or a remote, don't feel stupid: it's probably badly designed. Good design works for you, silently, making natural what is complex. It's a form of respect for whoever will use the object, and it shows precisely when it goes unnoticed."),
        ]),
    "arte-street-art": E(
        "How did graffiti become million-dollar art?",
        ["street", "art"],
        "From an act of vandalism prosecuted by law to works auctioned for staggering sums. Street art has overturned every rule of the art world.",
        "Street art went from illegality to global cultural phenomenon: it brought art out of museums, but raises questions about authenticity and the market.",
        [
            ("The rebellious roots",
             "Modern street art was born in the cities of the 1970s, among the graffiti of New York neighborhoods. It was the expression of communities often on the margins, a way to leave a mark and say 'I exist'. Born as an illegal and anonymous act, it had a rebellious, protest character deeply tied to the territory."),
            ("From wall to gallery",
             "Over time some street artists reached worldwide fame. Their works, once erased by authorities, began to be photographed, protected, even removed from walls and sold. An art born to be free and for everyone entered the market circuit, in a short-circuit that still sparks debate."),
            ("The case of anonymity",
             "Some of the most famous street artists keep their anonymity. This mystery fuels the myth and, paradoxically, the commercial value of the works. The hidden identity becomes part of the brand. It's one of many contradictions: an anti-system movement that ends up using the logics of the system it criticized."),
            ("Ephemeral by nature",
             "Street art is made to live outdoors, exposed to rain, smog and erasure. This fragility is part of its meaning: it's art of the moment, of the place. Freezing it in a climate-controlled gallery somewhat betrays its spirit. Some artists have even self-destroyed their works to protest their commodification."),
            ("Cities as museums",
             "Today many cities commission murals to regenerate neighborhoods and attract tourism. Urban art has become a tool of renewal and local identity. Some fear this tames it, turning rebellion into decoration. But it's undeniable that it brought art into the daily life of millions of people."),
            ("The takeaway",
             "Street art tells how something considered vandalism can become celebrated culture, with all the contradictions that entails. It reminds us the boundaries of art are mobile and constantly renegotiated. And that, sometimes, a city's walls say more about us than many paintings hung in museums."),
        ]),
    "arte-music-emotion": E(
        "Why does music move us so much?",
        ["music", "emotion"],
        "A few notes and we get chills, teary eyes, goosebumps. Sounds organized in time that touch deep chords inside us. But how?",
        "Music acts on brain and emotions through rhythm, expectation and memory: our mind predicts sounds and reacts when they're confirmed or surprised.",
        [
            ("Sound organized in time",
             "Music is, at its base, sound organized in time: pitches, rhythms and timbres arranged in patterns. It has no literal meaning like words, yet it communicates powerful emotions. This ability to move us without 'saying' anything precise is one of its most fascinating and universal mysteries, present in every known human culture."),
            ("The brain predicts",
             "Listening to music, the brain continually anticipates what will come next, based on learned patterns. When a melody goes where we expect, we feel satisfaction; when it surprises us with an unexpected note, an emotional jolt is triggered. The play between expectation and surprise is at the root of many musical chills."),
            ("Rhythm and body",
             "Rhythm engages us physically: we tend to move, tap our foot, synchronize. This link between sound and movement is ancient and unites us with others. Dancing or singing together releases substances tied to pleasure and social bonding. Music was probably born also as a group glue, even before entertainment."),
            ("The power of memory",
             "A song can suddenly take us back to a precise moment of life: a love, a trip, a loss. Music binds strongly to memories and to the emotions felt while listening. That's why some melodies move us not only for how they sound, but for all they carry with them in our personal history."),
            ("Culture and learning",
             "Not all musical emotions are universal: much depends on what we're used to. A scale that sounds sad to us may seem neutral or cheerful in another tradition. From childhood we learn the 'language' of our culture's music, and that shapes our emotional reactions more than we think."),
            ("The takeaway",
             "Music moves us because it weaves biology, expectation, body, memory and culture into a single experience. It's at once deeply personal and universally human. There's nothing irrational in the chills it gives us: they're the audible trace of how mind and heart work together."),
        ]),
    "arte-why-photos-good": E(
        "What makes a photograph beautiful?",
        ["photography", "composition"],
        "Billions of photos taken every day, but only some really stop us. It's not (only) about gear: it's about vision.",
        "A beautiful photo comes from composition, light and the chosen instant: what counts isn't the expensive camera, but the eye of whoever decides what to include and when to shoot.",
        [
            ("It's not the camera",
             "People often think you need expensive gear for beautiful photos. In reality the decisive factor is whoever looks through the lens. An experienced photographer with a phone beats a beginner with a professional camera. Technology helps, but the difference is made by the vision, choice and timing of whoever shoots."),
            ("Light is everything",
             "'Photography' literally means 'writing with light'. The quality and direction of light transform a scene: the soft light of dawn or sunset (the 'golden hour') is loved because it sculpts faces and creates atmosphere. The hard light of noon flattens and casts sharp shadows. Learning to see light is the first step."),
            ("The rule of thirds",
             "A classic composition guideline: imagine the scene divided by two horizontal and two vertical lines, like a grid. Placing the subject along these lines or at their intersections creates images more dynamic than the plain center. It's not a law, but a starting point that gives balance without rigidity."),
            ("What to leave out",
             "Photographing is as much about including as excluding. Often a photo improves by removing the superfluous: getting closer, changing angle, eliminating distracting elements in the background. The edge of the frame is a powerful creative choice. Deciding what to leave out focuses attention on what really matters."),
            ("The decisive moment",
             "Photographer Cartier-Bresson spoke of the 'decisive moment': that instant when the elements of a scene align perfectly. A gesture, a look, a geometry lasting a fraction of a second. Knowing how to anticipate and catch that instant distinguishes the memorable shot from the banal one. It's patience and intuition together."),
            ("The takeaway",
             "A beautiful photo is a decision, not chance: where to stand, when to shoot, what to include. These are choices anyone can train, phone in hand. Next time don't think about the gear: think about light, composition and the instant. The rest is just a tool in the service of your vision."),
        ]),
}
