"""
PAUSE — Seed data (expansion pack B).
~35 additional stories for natura, animali, storia, psicologia, corpo-umano,
cultura, curiosità.
"""

GLOWS = ["#00E5FF", "#B200FF", "#FF6D00", "#FF006A", "#00E676"]

def _ch(items):
    out = []
    for i, (title, body, icon) in enumerate(items):
        out.append({
            "number": i + 1, "title": title, "body": body,
            "icon": icon, "glow_color": GLOWS[i % len(GLOWS)],
        })
    return out

CAT = {
    "scienza":     ("Scienza",     "planet-outline",         "#00D2FF"),
    "spazio":      ("Spazio",      "rocket-outline",         "#B200FF"),
    "tecnologia":  ("Tecnologia",  "hardware-chip-outline",  "#00E676"),
    "natura":      ("Natura",      "leaf-outline",           "#00E676"),
    "animali":     ("Animali",     "paw-outline",            "#FF9100"),
    "storia":      ("Storia",      "book-outline",           "#FF6D00"),
    "psicologia":  ("Psicologia",  "sparkles-outline",       "#FF006A"),
    "corpo-umano": ("Corpo umano", "heart-outline",          "#FF006A"),
    "cultura":     ("Cultura",     "globe-outline",          "#00D2FF"),
    "curiosita":   ("Curiosità",   "help-circle-outline",    "#B200FF"),
}

def _story(sid, cat_id, title, hi, hook, hero, ch, summary, read=2, deep=3):
    n, i, c = CAT[cat_id]
    return {"id": sid, "category_id": cat_id, "category_name": n, "category_icon": i, "category_color": c,
            "title": title, "highlight_words": hi, "hook": hook, "hero_image": hero,
            "reading_time_min": read, "deep_dive_time_min": deep, "chapters": _ch(ch), "summary": summary}


MORE_STORIES_B = [
    # ==================== NATURA (5) ====================
    _story("volcanoes-basics", "natura",
        "Cosa c'è davvero dentro un vulcano?", ["vulcano"],
        "Non è lava che ribolle in eterno. È un sistema idraulico enorme che collega la superficie al cuore della Terra.",
        "https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=1200&q=80&auto=format&fit=crop",
        [
            ("La Terra è calda dentro", "Sotto la crosta terrestre (10-70 km di spessore) c'è il mantello: roccia semisolida a 1.000-3.000°C. In alcune zone la roccia si scioglie parzialmente formando magma. Il magma è meno denso della roccia solida attorno e tende a salire, come una bolla in un liquido viscoso.", "flame"),
            ("La camera magmatica", "Prima di arrivare in superficie il magma si accumula in \"camere\" nella crosta, a 1-10 km di profondità. Qui può restare per secoli o millenni, cambiando composizione, temperatura, contenuto di gas. Sono queste camere il motore delle eruzioni.", "cube"),
            ("Perché eruttano", "Quando la pressione dei gas disciolti (soprattutto vapor acqueo, CO₂ e zolfo) supera la resistenza delle rocce sovrastanti, il vulcano erutta. È lo stesso principio di una bottiglia di spumante scossa: aprila e la pressione spinge fuori tutto.", "flash"),
            ("Diversi tipi", "I vulcani \"a scudo\" (Hawaii) hanno lava fluida ed eruzioni tranquille. Gli stratovulcani (Vesuvio, Fuji) hanno lava viscosa che intrappola gas: eruzioni esplosive. Le supervulcani (Yellowstone) sono giganteschi e rari, con eruzioni che possono modificare il clima globale.", "grid"),
            ("Non solo distruzione", "I vulcani creano terreni fertilissimi (l'agricoltura attorno all'Etna, al Vesuvio prospera). Portano in superficie minerali preziosi. Emettono gas che fanno parte dell'atmosfera. Senza il vulcanismo, la Terra non avrebbe forse mai avuto vita.", "sparkles"),
        ],
        "I vulcani sono valvole di sfogo che collegano il magma sotterraneo alla superficie. Distruttivi, ma indispensabili alla vita del pianeta."),
    _story("why-seasons", "natura",
        "Perché ci sono le stagioni?", ["stagioni"],
        "Non è perché la Terra si avvicina al Sole. Il vero motivo è che il pianeta è storto.",
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop",
        [
            ("L'asse inclinato", "La Terra ruota su un asse inclinato di 23,5° rispetto al piano dell'orbita attorno al Sole. Non è verticale come una trottola perfetta. Questa piccola inclinazione è la responsabile di tutto ciò che chiamiamo stagioni.", "compass"),
            ("Estate ed inverno", "Nel mese di giugno l'emisfero nord è inclinato verso il Sole: i raggi arrivano più diretti e le giornate sono più lunghe. È estate. A dicembre invece è inclinato dall'altra parte: raggi obliqui, giorni corti, inverno. L'emisfero sud vive il contrario.", "sunny"),
            ("Non è la distanza", "La Terra è leggermente più vicina al Sole a gennaio (perielio) rispetto a luglio. Ma la differenza è piccolissima: 3%. L'inclinazione batte la distanza. Anche il pianeta più vicino al Sole non avrebbe stagioni se avesse asse verticale.", "planet"),
            ("Equinozi e solstizi", "Ai solstizi (21 giugno, 21 dicembre) l'inclinazione è massima. Agli equinozi (21 marzo, 23 settembre) l'asse è perpendicolare alla direzione del Sole: giorno e notte durano quasi uguale ovunque sul pianeta. Le civiltà antiche costruivano monumenti (Stonehenge, Machu Picchu) proprio per marcare questi momenti.", "hourglass"),
            ("Alla lunga cambia", "L'inclinazione dell'asse oscilla tra 22° e 24,5° in cicli di circa 41.000 anni. Queste variazioni (cicli di Milankovitch) hanno contribuito a innescare le grandi ere glaciali degli ultimi milioni di anni. Le stagioni sono le stesse, ma la loro intensità cambia lentamente nei millenni.", "sparkles"),
        ],
        "Le stagioni esistono perché la Terra è inclinata di 23,5°. Ogni emisfero riceve raggi più diretti o obliqui a seconda del periodo."),
    _story("how-trees-live", "natura",
        "Come fa un albero a vivere così a lungo?", ["albero", "vivere"],
        "Alcuni alberi sono più vecchi delle piramidi. Hanno un trucco che gli animali non hanno mai avuto.",
        "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un modo diverso di crescere", "Gli animali crescono fino a una taglia poi si fermano e cominciano a invecchiare. Gli alberi crescono per tutta la vita, aggiungendo nuovi strati di legno e nuove foglie ogni anno. Non hanno un \"corpo finito\": sono sistemi in espansione perpetua.", "leaf"),
            ("Le parti vive", "In realtà solo una piccola parte di un albero è viva: un sottile strato appena sotto la corteccia (cambio) e le foglie. Il resto è legno morto, come un'impalcatura. Questo permette all'albero di sostenere strutture enormi senza dover mantenere in vita tutta la massa.", "layers"),
            ("Se una parte muore, sopravvive", "Un albero può perdere rami, foglie, persino gran parte del tronco e continuare a vivere. Un animale con lo stesso danno morirebbe. Gli alberi sono organismi modulari: se un pezzo si rompe, un altro pezzo continua.", "shield-checkmark"),
            ("Comunicano tra loro", "Studi recenti mostrano che gli alberi \"parlano\" attraverso reti di funghi sotterranei chiamate reti micorriziche. Si scambiano zuccheri, avvisano dei parassiti, aiutano piante malate. In una foresta i più vecchi \"nutrono\" i più giovani della loro specie.", "git-network"),
            ("Vecchi come civiltà", "Il pino Bristlecone in California ha oltre 4.800 anni. Alcuni ulivi in Sardegna ne hanno 3.500. Il vecchio Tjikko in Svezia (con radici clonali) 9.500. Gli alberi hanno visto Egizi, Romani, Rinascimento, guerre mondiali. Camminarci accanto è camminare in mezzo a testimoni silenziosi di millenni.", "sparkles"),
        ],
        "Gli alberi crescono per tutta la vita, sono per lo più legno morto, comunicano attraverso reti fungine e possono superare i 4.000 anni."),
    _story("why-oceans-salty", "natura",
        "Perché il mare è salato ma i fiumi no?", ["mare", "salato"],
        "Milioni di fiumi scaricano acqua dolce nell'oceano ogni secondo. Eppure il mare resta salato. Come mai?",
        "https://images.unsplash.com/photo-1439405326854-014607f694d7?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un lento accumulo", "L'acqua piovana pura è dolce. Ma cadendo sulla terra scioglie piccole quantità di sali dalle rocce e dal terreno, e li trasporta ai fiumi. I fiumi non ci sembrano salati perché la concentrazione è piccolissima: uno o due grammi per litro.", "water"),
            ("Fiumi verso mare", "Ogni anno i fiumi versano circa 4 miliardi di tonnellate di sali negli oceani. Piccole quantità che si accumulano per miliardi di anni. L'oceano è come una vasca da bagno: l'acqua entra ed esce (per evaporazione), ma i sali restano intrappolati.", "arrow-forward"),
            ("Evaporazione", "L'acqua degli oceani evapora e ricade come pioggia sulla terra. Ma i sali non evaporano: restano lì. Ogni ciclo lascia i mari un pochino più salati. Dopo 4 miliardi di anni la concentrazione media è 35 g di sale per litro.", "sunny"),
            ("Non è sempre stato così", "Nell'era arcaica gli oceani erano meno salati di oggi. Si stima che continuino a diventare leggermente più salati, ma il ritmo è lentissimo: impercettibile in una vita umana. In alcuni bacini chiusi (Mar Morto) la salinità è molto più alta perché non c'è sbocco: solo evaporazione, il sale si accumula.", "flask"),
            ("Il ciclo continua", "L'acqua del rubinetto che bevi oggi ha probabilmente attraversato le nuvole, i fiumi e gli oceani miliardi di volte. Ha bevuto dinosauri, si è ghiacciata nell'era glaciale, e ora è qui. Il ciclo idrologico è uno dei più affascinanti della Terra.", "refresh"),
        ],
        "I fiumi portano piccole quantità di sali all'oceano da miliardi di anni. L'acqua evapora, il sale resta: il mare diventa sempre più salato."),
    _story("how-glaciers-move", "natura",
        "I ghiacciai si muovono davvero?", ["ghiacciai", "muovono"],
        "Sembrano statue di ghiaccio ferme, ma scendono a valle di metri all'anno. Ecco perché.",
        "https://images.unsplash.com/photo-1520681279154-51b3fb4ea0f8?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un fiume solido", "Un ghiacciaio non è un blocco statico: è un fiume di ghiaccio. Si forma dove nevica più di quanto si sciolga per centinaia di anni. La neve si comprime nel proprio peso e diventa ghiaccio compatto. Quando lo strato supera una certa massa, comincia a scorrere.", "snow"),
            ("Come si muove", "Il ghiaccio sotto pressione si comporta come un liquido molto lento. La parte alta del ghiacciaio scivola lentamente verso valle sotto il suo stesso peso, un po' come lava viscosa. In fondo, dove tocca la roccia, l'acqua di fusione lo lubrifica facendolo scivolare.", "water"),
            ("Metri all'anno", "La velocità dipende da pendenza, temperatura, peso. In media un ghiacciaio scende di 10-100 metri all'anno. Alcuni ghiacciai in Groenlandia scivolano fino a 40 metri al giorno. Impossibile da vedere a occhio nudo, ma fotografie a distanza di anni lo mostrano chiaramente.", "arrow-forward"),
            ("Scolpiscono il territorio", "Trascinando rocce e sedimenti, i ghiacciai hanno scolpito valli, laghi, fiordi in tutto il mondo. Le Alpi hanno la loro forma perché grandi ghiacciai le hanno modellate durante le glaciazioni. Anche il New York a Manhattan poggia su rocce lisciate da un antico ghiacciaio.", "construct"),
            ("Stanno sparendo", "Con il riscaldamento globale, quasi tutti i ghiacciai del mondo si stanno ritirando. Il ghiacciaio dell'Adamello, il più grande italiano, ha perso metà del volume in un secolo. Meno ghiacciai significa meno acqua d'estate per fiumi, agricoltura e persone. Uno dei problemi più urgenti del secolo.", "warning"),
        ],
        "I ghiacciai scorrono lentamente sotto il loro peso, scolpiscono valli e paesaggi. Ma oggi si stanno ritirando quasi ovunque."),

    # ==================== ANIMALI (5) ====================
    _story("why-dogs-love-us", "animali",
        "Perché i cani ci amano così tanto?", ["cani", "amano"],
        "Non è per il cibo. È il risultato di 30.000 anni di co-evoluzione uomo-cane. E il tuo cane lo sente più di quanto pensi.",
        "https://images.unsplash.com/photo-1552053831-71594a27632d?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non sono lupi", "I cani discendono dai lupi ma sono diventati un'altra specie migliaia di anni fa. Alcune migliaia di anni di convivenza con gli umani hanno selezionato individui più tolleranti, più attenti agli umani, meno diffidenti. Sono letteralmente stati modellati dall'evoluzione per stare con noi.", "paw"),
            ("Guardano i nostri occhi", "I lupi evitano il contatto visivo prolungato (segnale di sfida). I cani lo cercano. Quando un cane e il suo umano si guardano, entrambi rilasciano ossitocina, l'ormone dell'affetto. È lo stesso meccanismo che lega madre e neonato.", "eye"),
            ("Capiscono le emozioni", "I cani riconoscono espressioni facciali umane e distinguono voci felici da voci arrabbiate. Alcuni studi mostrano che quando l'umano è triste, il cane risponde con comportamenti consolatori. Sono empatici in un modo che pochi altri animali domestici replicano.", "heart"),
            ("Un linguaggio a parte", "L'abbaio è quasi unico dei cani: i lupi adulti quasi non abbaiano. Sembra che sia un'invenzione evolutiva per comunicare con noi. I cani possono anche imparare centinaia di parole umane. Chaser, un border collie, ne riconosceva oltre 1.000.", "megaphone"),
            ("Un'amicizia unica", "Nessun altro animale è così legato all'uomo. I gatti sono affettuosi ma indipendenti. I cavalli obbediscono ma non ci cercano. I cani ci scelgono. Se ti fai una passeggiata con il tuo cane, sei parte di un'alleanza che dura da 30.000 anni.", "sparkles"),
        ],
        "I cani sono co-evoluti con gli umani per essere emotivamente sintonizzati con noi. Rilasciano ossitocina quando ci guardano negli occhi."),
    _story("shark-facts", "animali",
        "Gli squali sono davvero i cattivi del mare?", ["squali"],
        "Uccidono meno di 10 persone all'anno nel mondo. Noi ne uccidiamo 100 milioni. Chi dovrebbe temere chi?",
        "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80&auto=format&fit=crop",
        [
            ("Predatori antichi", "Gli squali esistono da oltre 400 milioni di anni: prima dei dinosauri, prima degli alberi. Sono sopravvissuti a 5 estinzioni di massa. Ne esistono oltre 500 specie, dal minuscolo squalo pigmeo (20 cm) al massiccio squalo balena (12 metri, che mangia solo plancton).", "layers"),
            ("Come vedono", "Gli squali hanno vista scarsa in acque torbide, ma un olfatto eccezionale (percepiscono una goccia di sangue in una piscina olimpica). E hanno un \"senso\" extra: ricettori elettrici (ampolle di Lorenzini) che rilevano i campi elettrici deboli generati dai muscoli delle prede. Percepiscono il cuore che batte.", "eye"),
            ("Attacchi rari", "In media gli squali uccidono 6-10 persone all'anno nel mondo. Le mucche ne uccidono più di 20, gli hippopotami 500, le zanzare oltre 700.000 (via malaria). La probabilità di essere uccisi da uno squalo è più bassa che essere colpiti da un fulmine.", "shield-checkmark"),
            ("Noi vs loro", "Ogni anno gli umani uccidono circa 100 milioni di squali, soprattutto per la zuppa di pinne (finning) e come by-catch della pesca industriale. Un terzo delle specie di squalo è a rischio estinzione. Senza squali, gli ecosistemi marini collassano.", "trending-down"),
            ("Cambiare punto di vista", "Molti attacchi \"agli umani\" sono in realtà morsi esplorativi: lo squalo ci scambia per una foca ma capisce subito che siamo troppo ossuti. Non siamo prede naturali. Il vero mostro del mare, statisticamente, è chiunque abbia inventato il finning.", "eye-off"),
        ],
        "Gli squali sono predatori antichi, meno pericolosi delle zanzare e vitali per gli ecosistemi. Ma li stiamo eliminando 10 milioni di volte più velocemente di quanto ci feriscano."),
    _story("elephants-memory", "animali",
        "Gli elefanti dimenticano davvero mai?", ["elefanti", "dimenticano"],
        "Il modo di dire è vero. E ha una spiegazione neurologica che ha sorpreso persino gli scienziati.",
        "https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il cervello più grande della terra", "Gli elefanti hanno un cervello di circa 5 kg, il più grande di qualsiasi animale terrestre (il nostro pesa 1,4 kg). Il numero di neuroni nel cervelletto è tre volte il nostro. Un cervello enorme che gestisce corpi enormi e vite lunghe.", "aperture"),
            ("Mappe mentali", "Le matriarche degli elefanti (le femmine più anziane) memorizzano rotte migratorie di migliaia di chilometri, sorgenti d'acqua nascoste, zone pericolose. In siccità estreme portano il branco a stagni che avevano visto vent'anni prima. La sopravvivenza del gruppo dipende dalla memoria dell'anziana.", "map"),
            ("Ricordano volti", "Studi mostrano che gli elefanti riconoscono decine di individui della loro specie, e ricordano umani specifici anche dopo anni. Un elefante è tornato a salutare un ricercatore che l'aveva liberato da una trappola 20 anni prima.", "people"),
            ("Piangono i morti", "Passando accanto ai resti di un elefante morto, gli altri si fermano, li toccano con la proboscide, li annusano a lungo. Restano vicino anche per ore. Non è antropomorfismo: è un comportamento documentato in centinaia di osservazioni. Sono tra i pochissimi animali che sembrano riconoscere la morte.", "heart"),
            ("Cultura in movimento", "Le tradizioni di un branco (dove bere, come difendersi, quali vie prendere) vengono tramandate. Se le matriarche vengono uccise (dal bracconaggio), il branco perde generazioni di conoscenza. Un elefante non è un individuo isolato: è nodo di una rete di memoria collettiva.", "sparkles"),
        ],
        "Il cervello enorme degli elefanti li rende capaci di memorizzare rotte, individui e trasmettere conoscenza culturale al branco. La memoria è la loro sopravvivenza."),
    _story("bird-migration", "animali",
        "Come fanno gli uccelli migratori a non perdersi?", ["uccelli", "migratori"],
        "Ogni anno miliardi di uccelli attraversano continenti. E arrivano precisi al metro. Senza mappe, senza GPS.",
        "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un viaggio enorme", "La sterna artica migra ogni anno dall'Artico all'Antartide e ritorno: 90.000 km. La sua vita di 30 anni copre oltre 2 milioni di km, quasi 3 viaggi Terra-Luna. E arriva sempre nello stesso posto. Non è caso, è un'abilità straordinaria.", "airplane"),
            ("Il Sole", "Molti uccelli si orientano con il Sole. Tenendo conto dell'ora del giorno e dell'angolo del Sole rispetto alla direzione voluta, sanno se stanno andando a nord o a sud. Hanno una \"bussola solare\" interna che compensa il movimento del Sole nel cielo.", "sunny"),
            ("Le stelle", "Gli uccelli che migrano di notte usano le stelle. Studi con planetari artificiali mostrano che nascono già capaci di riconoscere pattern stellari. Il cielo è il loro atlante notturno.", "star"),
            ("Il campo magnetico", "Gli uccelli hanno cellule sensibili al campo magnetico terrestre. Nell'occhio (o nel becco) sensori microscopici rilevano il magnetismo e lo trasformano in un \"senso\" cosciente della direzione. Alcuni scienziati pensano che gli uccelli letteralmente \"vedano\" il campo magnetico come una guida visiva sovrapposta al paesaggio.", "compass"),
            ("Imparano crescendo", "Alcune specie ereditano la rotta geneticamente (canna sarda). Altre imparano dai genitori (oche). Le mappe cognitive sono così precise che, se sposti geograficamente giovani uccelli prima della prima migrazione, alcuni riescono comunque ad arrivare a destinazione. Un sapere iscritto nei geni e nell'esperienza.", "school"),
        ],
        "Gli uccelli migratori si orientano con Sole, stelle e campo magnetico terrestre. Alcuni ereditano geneticamente la rotta, altri la imparano dai genitori."),
    _story("penguins-cold", "animali",
        "Come fanno i pinguini a non congelare?", ["pinguini", "congelare"],
        "Vivono a -50°C senza problemi. Il loro segreto? Un'ingegneria termica che le case moderne stanno solo ora imitando.",
        "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?w=1200&q=80&auto=format&fit=crop",
        [
            ("Vestiti a tre strati", "I pinguini hanno tre strati isolanti: piume esterne, piume interne, grasso spesso fino a 3 cm. Le piume esterne impermeabili trattengono aria calda, come una piuma d'oca. Le interne sono un secondo strato isolante. Il grasso è la coperta finale.", "layers"),
            ("Piedi che non congelano", "I pinguini stanno sul ghiaccio ma i piedi non congelano. Il segreto è un sistema di controcorrente: le arterie che vanno ai piedi scorrono accanto alle vene che tornano. Il sangue caldo in uscita scalda quello freddo in ingresso. Quasi nessun calore viene disperso.", "swap-horizontal"),
            ("Si stringono", "I pinguini imperatore, i più grandi, resistono agli inverni antartici (-40°C, vento a 200 km/h) formando enormi gruppi di migliaia di individui strettamente compatti. Ognuno riscalda l'altro. Ruotano lentamente: chi è al centro va all'esterno, chi era all'esterno si sposta al centro. Democrazia termica.", "people"),
            ("Nuotano a temperatura variabile", "Nell'acqua gelida i pinguini possono ridurre la temperatura corporea dei muscoli fino a 11°C e mantenerla stabile per ore. Quando escono si riscaldano in fretta. È un adattamento fisiologico unico tra gli uccelli.", "water"),
            ("Genitori inflessibili", "Il maschio dell'imperatore cova l'uovo tenendolo sui piedi coperti da una pelle calda mentre la femmina cerca cibo. Passa mesi senza mangiare a -40°C. Non si sposta di un metro. Il tasso di sopravvivenza del pulcino dipende quasi tutto dal padre. Uno degli esempi più estremi di dedizione paterna in natura.", "heart"),
        ],
        "I pinguini sopravvivono al freddo estremo con isolamento a strati, sistemi di scambio termico e cooperazione sociale. Ingegneria evolutiva perfetta."),

    # ==================== STORIA (5) ====================
    _story("egyptian-pyramids", "storia",
        "Come furono costruite le piramidi?", ["piramidi"],
        "Non da schiavi. Non da alieni. Da operai pagati, con tecniche che stiamo capendo solo ora, 4.500 anni dopo.",
        "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1200&q=80&auto=format&fit=crop",
        [
            ("La Grande Piramide", "La piramide di Cheope a Giza è alta 146 metri (originariamente), pesa 6 milioni di tonnellate, contiene circa 2,3 milioni di blocchi di pietra. Fu costruita in circa 20 anni intorno al 2560 a.C. Per 3.800 anni fu la struttura più alta del mondo, superata solo dalla cattedrale di Lincoln nel 1311.", "layers"),
            ("Non schiavi, operai", "Le vecchie storie parlavano di schiavi frustati. Ma gli scavi archeologici moderni hanno trovato tombe di operai con ossa che mostrano nutrizione adeguata, cure mediche, e le loro tombe erano onorevolmente vicine alle piramidi. Erano lavoratori pagati, spesso contadini che lavoravano d'inverno durante le piene del Nilo.", "people"),
            ("Il trasporto delle pietre", "Come spostavano blocchi da 2-15 tonnellate? Un affresco antico mostra la risposta: bagnavano la sabbia davanti alle slitte. Simulazioni moderne confermano che riduce l'attrito del 50%. Altre pietre viaggiavano su chiatte sul Nilo, sfruttando la corrente naturale.", "water"),
            ("Le rampe", "Come alzavano i blocchi in cima? Probabilmente con rampe interne a spirale, di cui recenti scansioni hanno trovato tracce. Non serviva magia: matematica, geometria, ingegneria pratica. Gli egizi avevano scriba specializzati che pianificavano ogni pietra.", "trending-up"),
            ("Perché durano", "Le piramidi sono durate 4.500 anni grazie alla geometria: il peso spinge sempre verso il centro, la struttura è auto-stabilizzante. Molte tempeste, terremoti, guerre sono passate senza scalfirle. Un capolavoro di ingegneria che ancora oggi impariamo a capire.", "shield-checkmark"),
        ],
        "Le piramidi furono costruite da operai pagati, con tecniche brillanti (bagnare la sabbia, rampe interne) e una precisione matematica che dura da 4.500 anni."),
    _story("printing-press", "storia",
        "Perché la stampa a caratteri mobili ha cambiato tutto?", ["stampa"],
        "Una macchina di legno del 1450 ha fatto crollare imperi, avviato la scienza moderna e reso possibile la tua istruzione.",
        "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80&auto=format&fit=crop",
        [
            ("Prima del 1450", "Prima della stampa i libri venivano copiati a mano dai monaci amanuensi. Un solo libro poteva richiedere anni. Un libro costava quanto una casa. I libri erano rari, gelosamente custoditi in poche biblioteche, e leggerli era privilegio di pochissimi.", "book"),
            ("Gutenberg", "Nel 1450 circa Johannes Gutenberg, orafo tedesco, unì tre invenzioni: caratteri metallici mobili riutilizzabili, un inchiostro adatto, una pressa modificata dai torchi da vino. Con il suo sistema poteva stampare una pagina in minuti invece che giorni.", "hammer"),
            ("Esplosione di libri", "In 50 anni furono stampati oltre 20 milioni di libri in Europa (contro le poche migliaia scritte a mano prima). Il prezzo dei libri crollò. La conoscenza smise di essere privilegio dei monasteri: raggiunse commercianti, artigiani, chiunque sapesse leggere.", "trending-up"),
            ("La Riforma", "Nel 1517 Lutero pubblicò le sue 95 tesi. In poche settimane furono stampate e diffuse in tutta Europa. Senza la stampa, sarebbero rimaste tra i pochi teologi di Wittenberg. Con la stampa fecero saltare l'unità della cristianità: nacque la Riforma protestante.", "flame"),
            ("Rivoluzione scientifica", "La stampa permise a scienziati di ogni angolo d'Europa di leggere gli stessi testi, confrontarsi, costruire su idee altrui. Galileo, Copernico, Newton dovevano tutto alla capacità di distribuire libri rapidamente. La scienza moderna è figlia della stampa.", "sparkles"),
        ],
        "La stampa a caratteri mobili di Gutenberg (1450) democratizzò la conoscenza, alimentò la Riforma protestante e rese possibile la scienza moderna."),
    _story("french-revolution", "storia",
        "Perché scoppiò la Rivoluzione Francese?", ["Rivoluzione", "Francese"],
        "Una nazione ricca, un re dorato, un popolo che moriva di fame. E un'estate del 1789 che cambiò l'Europa per sempre.",
        "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80&auto=format&fit=crop",
        [
            ("La Francia disuguale", "Alla fine del 1700 la Francia era divisa in tre \"stati\": clero (1%), nobiltà (2%), tutti gli altri (97%). Solo il terzo stato pagava le tasse. Le carestie del 1788 avevano affamato le città. Il popolo aveva sempre meno da mangiare mentre a Versailles il re banchettava.", "people"),
            ("Debiti giganti", "Luigi XVI aveva ereditato debiti enormi (guerre americane, sperperi di corte). Per finanziarli convocò gli Stati Generali nel maggio 1789. Il terzo stato chiese riforme profonde. Quando fu ignorato, si autoproclamò Assemblea Nazionale, promettendo di dare una costituzione alla Francia.", "trending-down"),
            ("La Bastiglia", "Il 14 luglio 1789 il popolo di Parigi assaltò la Bastiglia, prigione reale simbolo dell'assolutismo. Ci trovarono pochi prigionieri ma tanta polvere da sparo. Fu il segnale che il popolo era pronto a prendersi con la forza ciò che il re non voleva concedere.", "flame"),
            ("Diritti dell'uomo", "In agosto l'Assemblea approvò la Dichiarazione dei diritti dell'uomo e del cittadino: tutti gli uomini nascono liberi e uguali, la sovranità appartiene alla nazione. Erano concetti rivoluzionari che avrebbero ispirato il mondo intero. Ancora oggi sono la base di quasi tutte le costituzioni democratiche.", "document"),
            ("Terrore e Napoleone", "La rivoluzione ebbe fasi terribili: il Terrore (1793-94) mandò migliaia alla ghigliottina, incluso il re. Poi Napoleone Bonaparte prese il potere nel 1799 e portò le idee rivoluzionarie in tutta Europa con la sua armata. Anche dopo la sua sconfitta, il mondo europeo non fu più quello di prima. Le monarchie assolute erano al tramonto.", "sparkles"),
        ],
        "La Rivoluzione Francese scoppiò per disuguaglianza, carestia e debito. Il 14 luglio 1789 il popolo di Parigi assaltò la Bastiglia: nacque l'idea di sovranità popolare."),
    _story("world-war-1", "storia",
        "Perché scoppiò la Prima Guerra Mondiale?", ["Prima", "Guerra"],
        "Un colpo di pistola in una piccola città balcanica trascinò 32 nazioni e uccise 20 milioni di persone. Come fu possibile?",
        "https://images.unsplash.com/photo-1454486837617-ce8e1ba5ebfe?w=1200&q=80&auto=format&fit=crop",
        [
            ("L'Europa polveriera", "Nel 1914 l'Europa era stipata di rivalità: Germania e Francia (dopo la guerra del 1870), Austria-Ungheria e Russia (per i Balcani), Regno Unito e Germania (per la marina), Serbia e Austria (per il nazionalismo slavo). Un sistema di alleanze rigide legava tutti: se uno entrava in guerra, gli altri erano trascinati.", "flame"),
            ("Sarajevo, 28 giugno 1914", "L'arciduca Francesco Ferdinando, erede al trono austroungarico, fu assassinato a Sarajevo da Gavrilo Princip, nazionalista serbo. In pochi giorni l'Austria dichiarò guerra alla Serbia, la Russia mobilitò per difendere gli slavi, la Germania per aiutare l'Austria, la Francia e il Regno Unito per contrattaccare. Le alleanze erano una trappola.", "swap-horizontal"),
            ("Le trincee", "Presto la guerra si impantanò in trincee lunghe centinaia di chilometri dalla Manica alle Alpi. I soldati vivevano tra fango, ratti, gas, cadaveri. Milioni morirono per conquistare pochi metri. Furono introdotti tank, aerei, mitragliatrici. Fu la prima guerra industriale.", "cube"),
            ("L'entrata italiana", "L'Italia inizialmente era neutrale. Poi nel 1915 entrò a fianco di Francia e Regno Unito (Patto di Londra) sperando di ottenere terre austriache (Trento, Trieste). Furono anni terribili sull'Isonzo e sull'altipiano di Asiago. Vittoria finale a Vittorio Veneto (1918) al costo di 650.000 morti italiani.", "people"),
            ("Fine e conseguenze", "Nel 1918 la Germania crollò. Il trattato di Versailles la umiliò con debiti enormi e territori sottratti. Da questa umiliazione nacquero il fascismo e il nazismo. La \"guerra per porre fine a tutte le guerre\" preparò la seconda. La Prima Guerra Mondiale è la ferita che aprì il novecento.", "sparkles"),
        ],
        "La Prima Guerra Mondiale scoppiò per un sistema di alleanze rigide dopo l'assassinio di Sarajevo. Milioni morirono nelle trincee, e il trattato di Versailles seminò la Seconda Guerra."),
    _story("vikings-truth", "storia",
        "I vichinghi erano davvero solo barbari?", ["vichinghi"],
        "Elmi con le corna? Falso. Solo razziatori? Falso. La verità sui vichinghi è più sofisticata di come li ha dipinti Hollywood.",
        "https://images.unsplash.com/photo-1531074057936-6afa10dd7d16?w=1200&q=80&auto=format&fit=crop",
        [
            ("Chi erano", "I vichinghi erano popolazioni della Scandinavia (Norvegia, Danimarca, Svezia) tra il 793 e il 1066. Non erano un unico popolo: erano contadini, mercanti, artigiani, esploratori, e sì, guerrieri. La parola \"vichingo\" significa \"chi va in spedizione\": era un mestiere, non un'etnia.", "boat"),
            ("Esploratori formidabili", "Su navi lunghe e agili (drakkar), attraversarono l'Atlantico. Colonizzarono l'Islanda, la Groenlandia. Leif Erikson raggiunse il Nord America (\"Vinland\") intorno all'anno 1000, cinque secoli prima di Colombo. Andarono anche a est fino al Mar Nero e Costantinopoli. Erano marinai insuperabili.", "compass"),
            ("Commercianti", "Meno noti dei razziatori, i vichinghi erano commercianti sofisticati. Vendevano ambra, pellicce, schiavi. Compravano argento, spezie, seta. Le loro reti commerciali collegavano il Nord Europa al Medio Oriente. Molte città moderne (Dublino, York, Kiev) furono fondate o cresciute da vichinghi.", "cash"),
            ("Niente corna sull'elmo", "L'immagine con corna è pura invenzione: nasce da opere teatrali dell'Ottocento e film americani. Gli elmi vichinghi reali (pochi trovati) sono semplici, di ferro, senza fronzoli. Corna avrebbero rischiato di impigliarsi. Erano guerrieri pragmatici, non stilisti.", "eye-off"),
            ("La società", "Le società vichinghe avevano assemblee (\"thing\") dove uomini liberi discutevano leggi. L'Islanda nel 930 fondò l'Althing, uno dei parlamenti più antichi al mondo. Le donne avevano diritti più ampi che altrove (potevano divorziare, ereditare, gestire fattorie). Erano lontani dallo stereotipo di violenza indiscriminata.", "people"),
        ],
        "I vichinghi non erano solo razziatori: esploravano continenti, commerciavano fino al Mar Nero, fondavano parlamenti. E no, non avevano corna."),

    # ==================== PSICOLOGIA (5) ====================
    _story("why-we-dream", "psicologia",
        "A cosa servono davvero i sogni?", ["sogni"],
        "Non sono profezie né rumore casuale. Ogni notte il tuo cervello ti manda in un teatro segreto, con un motivo preciso.",
        "https://images.unsplash.com/photo-1531353826977-0941b4779a1c?w=1200&q=80&auto=format&fit=crop",
        [
            ("Quando sogniamo", "I sogni più vividi accadono durante la fase REM (Rapid Eye Movement), che si ripete ogni 90 minuti circa. In quella fase il cervello è attivo quasi come da svegli, ma i muscoli sono paralizzati (per non muoversi durante il sogno). Ognuno di noi sogna circa 2 ore ogni notte.", "moon"),
            ("Consolidano memoria", "Studi mostrano che durante il REM il cervello \"rigioca\" le esperienze recenti a velocità aumentata, trasferendo informazioni dalla memoria breve a quella lunga. Dormire dopo aver studiato aumenta significativamente la ritenzione.", "book"),
            ("Elaborano emozioni", "Il REM è ricco di attività nell'amigdala (centro delle emozioni). I sogni permettono di rivivere paure, gioie, ansie in un ambiente sicuro, e ridurre il loro impatto emotivo. Chi non dorme bene fatica a gestire lo stress il giorno dopo.", "heart"),
            ("Palestra creativa", "Molti sogni uniscono ricordi in modi bizzarri. Alcuni scienziati pensano che questa \"associazione libera\" allena la creatività. Molte grandi intuizioni (la struttura del benzene di Kekulé, le melodie di Paul McCartney) sono nate letteralmente da sogni.", "bulb"),
            ("Perché li dimentichi", "Ricordiamo solo il 5-10% dei sogni. La sostanza chimica che consolida i ricordi (norepinefrina) è quasi assente durante il REM. Un sogno esiste veramente solo se ti svegli durante o subito dopo. Il resto svanisce, come previsto.", "sparkles"),
        ],
        "I sogni consolidano memoria, elaborano emozioni e stimolano creatività durante la fase REM. Ne ricordi solo il 5%, ma servono comunque."),
    _story("procrastination", "psicologia",
        "Perché rimandiamo sempre le cose importanti?", ["rimandiamo"],
        "Non è pigrizia. È il modo in cui il tuo cervello fugge dalle emozioni scomode. E c'è un modo per fregarlo.",
        "https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non è pigrizia", "La procrastinazione è spesso vista come debolezza di volontà. La ricerca psicologica moderna dice invece: è una strategia di regolazione emotiva. Rimandi non perché sei pigro, ma perché il compito ti fa sentire ansia, noia o inadeguatezza, e evitarlo dà sollievo immediato.", "sad"),
            ("Il cervello sceglie il presente", "Il cervello umano ha una parte razionale (corteccia prefrontale) che pensa al futuro, e una parte limbica che vuole ricompense immediate. Quando si scontrano, la parte immediata spesso vince. Rimandare è la vittoria del \"me di adesso\" sul \"me di domani\".", "swap-horizontal"),
            ("Ansia da compito", "Compiti che ci mettono in relazione con l'immagine di noi stessi (\"e se non fossi capace?\") producono ansia. Evitarli è un modo per non affrontare quell'emozione. Il costo (ritardi, colpe) arriva dopo, ma nel momento sembra il male minore.", "warning"),
            ("Il ciclo peggiora", "Più rimandi, più ansia si accumula, più eviti. È un circolo che si autoalimenta. Alcune persone entrano in ciclo per settimane su compiti che risolverebbero in un'ora. La colpa non risolve, anzi ti fa sentire peggio, e quindi ti fa procrastinare ancora.", "refresh"),
            ("Come uscirne", "Le strategie che funzionano: (1) fai solo 5 minuti, spesso continuerai; (2) spezzetta il compito in micro-passi; (3) sostituisci il senso di colpa con l'autocompassione (perdonare sé stessi rompe il ciclo); (4) elimina distrazioni fisiche. Non si combatte la procrastinazione con la forza di volontà, ma con l'ambiente e la gentilezza verso sé stessi.", "sparkles"),
        ],
        "La procrastinazione non è pigrizia ma fuga dalle emozioni scomode del compito. Si risolve con micro-passi e autocompassione, non con più senso di colpa."),
    _story("fear-basics", "psicologia",
        "Cos'è davvero la paura?", ["paura"],
        "Un sistema di allarme antichissimo. Utile per sopravvivere ai leoni, meno per superare un colloquio di lavoro.",
        "https://images.unsplash.com/photo-1541199249251-f713e6145474?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un antico salvavita", "La paura è un'emozione base condivisa da quasi tutti gli animali. Nasce nell'amigdala, una piccola struttura del cervello. La sua funzione è preparare il corpo a due reazioni: fuggire o combattere. È un sistema di allarme che ha aiutato la nostra specie a sopravvivere per centinaia di migliaia di anni.", "flash"),
            ("Cosa succede nel corpo", "Quando percepisci pericolo, l'amigdala allerta l'ipotalamo che rilascia adrenalina e cortisolo. Il cuore accelera, il respiro si fa breve, la pupilla si dilata, i muscoli si tendono, la digestione si ferma. Sei pronto a scattare via o a difenderti. Il tuo corpo è diventato una macchina di sopravvivenza in 300 millisecondi.", "heart"),
            ("Reale e immaginato", "L'amigdala non distingue tra un pericolo reale (un cane che ringhia) e uno immaginato (pensare a un colloquio). La reazione fisica è la stessa. Ecco perché l'ansia cronica logora: il corpo vive costantemente in modalità di allarme senza scarico.", "eye"),
            ("Le fobie", "Una fobia è una paura appresa e amplificata. Il cervello ha collegato uno stimolo (ragno, altezze, spazi chiusi) alla reazione di panico. Ripetendo l'esperienza in situazioni sicure (esposizione graduale), la paura si attenua. Le terapie moderne funzionano proprio così.", "swap-horizontal"),
            ("Non è nemica", "La paura non è debolezza né malattia. È intelligenza evolutiva. Le persone coraggiose non sono quelle senza paura: sono quelle che agiscono nonostante la paura. Riconoscerla, nominarla, ascoltarla senza obbedirle sempre è una delle chiavi del benessere emotivo.", "sparkles"),
        ],
        "La paura è un sistema di allarme dell'amigdala che prepara il corpo a fuggire o combattere. Utile ai leoni, meno alle situazioni sociali moderne."),
    _story("memory-basics", "psicologia",
        "Perché dimentichiamo (e come funziona la memoria)?", ["dimentichiamo"],
        "Non è che perdi i ricordi. È che il tuo cervello sceglie con cura cosa tenere. E ogni ricordo che riprendi lo riscrive.",
        "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&q=80&auto=format&fit=crop",
        [
            ("Tre memorie", "Non hai una memoria sola. Hai una memoria sensoriale (millisecondi), a breve termine (secondi/minuti), a lungo termine (giorni-decenni). L'informazione passa di livello solo se la usi. Se ripeti un numero di telefono ad alta voce, ha più possibilità di finire in memoria lunga.", "layers"),
            ("Non è un video", "Molti pensano che il ricordo sia una registrazione fedele di un evento. Non è così. Il cervello ricostruisce ogni volta il ricordo unendo frammenti, riempiendo i vuoti con ipotesi. Testimoni oculari degli stessi eventi ricordano dettagli diversi, spesso contraddittori.", "aperture"),
            ("Riscrivere ogni volta", "Ogni volta che richiami un ricordo, il cervello lo riscrive. Se lo richiami in stato emotivo alterato, si mescola con quella emozione. Un ricordo felice ripensato in depressione può diventare triste per sempre. La memoria è meno archivio, più cronaca in continua revisione.", "refresh"),
            ("Perché dimentichi nomi", "Nomi propri sono difficili perché non hanno significato di per sé (\"Marco\" non descrive nulla). Il cervello ricorda meglio ciò che ha senso emotivo, visivo, associativo. Provate a legare un nome a un'immagine mentale ridicola: funziona.", "help-circle"),
            ("Ricordare per dimenticare", "Studi mostrano che dimenticare non è un difetto: è funzionale. Se ricordassimo tutto, saremmo sopraffatti. Il cervello scarta di continuo ciò che sembra inutile. Chi soffre di iperthymesia (memoria autobiografica totale) descrive la vita come opprimente. Il tuo cervello ti sta proteggendo dimenticando.", "sparkles"),
        ],
        "La memoria non è un video ma una ricostruzione: ogni volta che ricordi, riscrivi. Dimenticare è funzionale, non un difetto."),
    _story("empathy-basics", "psicologia",
        "Cos'è l'empatia (e perché non ce l'hanno tutti)?", ["empatia"],
        "Un superpotere sociale che alcuni cervelli hanno di serie, altri devono coltivare. E che sta scomparendo dagli anni '90.",
        "https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non è simpatia", "Empatia significa \"sentire dentro\": la capacità di mettersi nei panni di un altro. È diversa dalla simpatia (voler bene) o dalla compassione (voler aiutare). Empatia è capire cosa prova l'altro, anche se non condividi la sua situazione.", "heart"),
            ("Due tipi", "L'empatia cognitiva è capire razionalmente cosa un altro pensa (\"lui è triste per...\"). L'empatia affettiva è sentire realmente ciò che prova (senti tu stesso un peso allo stomaco quando vedi qualcuno soffrire). Persone possono avere una senza l'altra: alcuni sanno decifrare emozioni ma non le condividono, altri sentono tanto ma non capiscono.", "swap-horizontal"),
            ("I neuroni specchio", "Nel cervello ci sono neuroni chiamati \"specchio\" che si attivano sia quando fai un'azione sia quando la vedi fare a qualcuno. Vedere qualcuno felice attiva i circuiti della felicità dentro di te. È la base biologica dell'empatia.", "aperture"),
            ("Chi ne ha meno", "Nell'autismo l'empatia cognitiva è ridotta ma l'affettiva spesso è intatta o superiore alla media. Negli psicopatici avviene il contrario: sanno leggere perfettamente le emozioni ma non le sentono. Sono capacità distinte, e alcune persone hanno più di una senza l'altra.", "people"),
            ("Sta diminuendo", "Studi longitudinali mostrano che negli ultimi 30 anni l'empatia media è calata del 40%. Le cause probabili: social media (rimuovono contesto emotivo), competizione culturale, isolamento fisico. L'empatia si allena leggendo narrativa, ascoltando storie, spegnendo il telefono a cena. È una competenza, non un dono innato.", "sparkles"),
        ],
        "L'empatia è la capacità di sentire (o capire) cosa prova un altro. Ha basi neurologiche nei neuroni specchio ma può essere allenata come un muscolo."),

    # ==================== CORPO UMANO (4) ====================
    _story("immune-system", "corpo-umano",
        "Come funziona il sistema immunitario?", ["sistema", "immunitario"],
        "Un esercito silenzioso di trilioni di cellule che combatte per te ogni secondo. E che dimentica raramente un nemico.",
        "https://images.unsplash.com/photo-1583912267550-d64c1f43fa89?w=1200&q=80&auto=format&fit=crop",
        [
            ("Due linee di difesa", "Il sistema immunitario ha due strati: quello innato (rapido, generico) e quello adattivo (lento ma preciso). L'innato attacca ogni intruso senza distinguere. L'adattivo impara chi sono i nemici e produce anticorpi specifici. Insieme sono un sistema di sicurezza multi-livello.", "shield-checkmark"),
            ("I globuli bianchi", "Ci sono decine di tipi di globuli bianchi. I macrofagi mangiano i patogeni. I neutrofili sciamano nelle ferite. I linfociti T uccidono cellule infette. I linfociti B producono anticorpi. Ogni tipo ha un ruolo specifico in una coreografia complessa.", "people"),
            ("La memoria", "Quando affronti un virus, il sistema adattivo genera cellule di memoria che restano per anni o decenni. Se lo stesso virus torna, la risposta è quasi istantanea. È perché il morbillo si prende una volta sola, ed è la base dei vaccini: insegnano al sistema senza che tu debba ammalarti.", "book"),
            ("Quando sbaglia bersaglio", "A volte il sistema immunitario attacca cellule del proprio corpo credendole nemiche: sono le malattie autoimmuni (lupus, sclerosi multipla, tiroidite). Il perché di questo errore è ancora in gran parte un mistero. Gli scienziati stanno cercando modi per riequilibrare il sistema.", "warning"),
            ("Perché serve dormire", "Durante il sonno il sistema immunitario produce citochine e cellule di memoria. Dormire poco riduce significativamente la resistenza alle infezioni. Chi dorme meno di 6 ore ha 4 volte più probabilità di prendere un raffreddore rispetto a chi dorme 7-8 ore. La miglior medicina è quella del sonno.", "moon"),
        ],
        "Il sistema immunitario è un esercito di trilioni di cellule con due strati (innato e adattivo). Impara dai nemici e crea memoria per proteggerti in futuro."),
    _story("how-skin-works", "corpo-umano",
        "Perché la pelle è l'organo più straordinario?", ["pelle"],
        "Due metri quadrati di sensore, scudo, termoregolatore, laboratorio. E si rinnova completamente ogni mese.",
        "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=1200&q=80&auto=format&fit=crop",
        [
            ("Il più grande organo", "La pelle di un adulto pesa circa 4 kg e copre 2 m². È il più grande organo del corpo. Non è solo un rivestimento: è un organo complesso con nervi, vasi, ghiandole, cellule immunitarie. Fa più cose di qualsiasi altro organo.", "layers"),
            ("Tre strati", "Epidermide (esterna, impermeabile, scudo). Derma (media, con collagene, elasticità, sensori). Ipoderma (interna, grasso e isolamento). Ogni strato ha funzioni specifiche. Un taglio superficiale guarisce in ore, uno profondo che raggiunge il derma può lasciare cicatrice.", "grid"),
            ("Sentimenti sotto la pelle", "In ogni cm² di pelle ci sono migliaia di terminazioni nervose che rilevano pressione, calore, dolore, vibrazione. È il tuo principale organo di senso per il mondo fisico. È anche legata alle emozioni: arrossisci, sudi, hai la pelle d'oca sentendo un ricordo commovente.", "heart"),
            ("Regolatore termico", "La pelle mantiene la temperatura corporea. Quando fa caldo, i vasi si dilatano e si suda per raffreddare. Quando fa freddo, i vasi si stringono e si crea pelle d'oca (contrazione dei peli per intrappolare aria calda: residuo evolutivo di quando avevamo il pelo lungo).", "thermometer"),
            ("Si rinnova", "Le cellule dello strato esterno cadono continuamente: perdi circa 40.000 cellule di pelle al minuto. In 4-6 settimane la tua epidermide è completamente nuova. Nel corso di una vita perderai circa 18 kg di pelle. Sei letteralmente una versione diversa di te ogni mese.", "refresh"),
        ],
        "La pelle è il più grande organo del corpo: scudo, sensore, regolatore termico. Si rinnova completamente ogni 4-6 settimane."),
    _story("how-taste-works", "corpo-umano",
        "Perché i sapori non sono solo 5 (o forse sì)?", ["sapori"],
        "Dolce, salato, aspro, amaro, umami. Il gusto è chimica pura, ma ciò che chiamiamo \"sapore\" è per lo più naso.",
        "https://images.unsplash.com/photo-1533640924469-f04e06f8898d?w=1200&q=80&auto=format&fit=crop",
        [
            ("Cinque gusti base", "La lingua distingue solo 5 gusti: dolce (zuccheri), salato (sodio), aspro (acidi), amaro (potenzialmente tossici), umami (amminoacidi come glutammato, sapore del brodo). Tutto il resto che chiami \"sapore\" viene dall'olfatto.", "flask"),
            ("Non solo sulla punta", "L'idea che la punta della lingua sia per il dolce e il retro per l'amaro è un mito. Ogni parte della lingua percepisce tutti i gusti. Le papille gustative sono distribuite ovunque sulla lingua, sul palato, in gola.", "eye"),
            ("Naso è tutto", "Il 90% del \"gusto\" che percepisci in realtà è olfatto. Prova a mangiare qualcosa mentre ti tappi il naso: il cibo diventa quasi insapore. Molecole volatili salgono dalla bocca alla parte alta del naso, dove i recettori olfattivi le riconoscono.", "leaf"),
            ("Perché amiamo il dolce", "L'evoluzione ci ha fatti nascere amanti del dolce: in natura significava zuccheri = energia. Ci ha fatti sospettosi dell'amaro: in natura molte tossine sono amare. Oggi, in un mondo pieno di zucchero, questa predisposizione si è ritorta contro di noi.", "warning"),
            ("Il gusto invecchia", "Alla nascita hai circa 10.000 papille gustative. A 60 anni te ne restano circa 5.000. Questo è uno dei motivi per cui gli anziani sopportano cibi più speziati o salati: percepiscono meno intensamente. Anche il gusto invecchia.", "sparkles"),
        ],
        "La lingua distingue 5 gusti: dolce, salato, aspro, amaro, umami. Ma il 90% del sapore è olfatto: senza naso, mangiare è quasi insapore."),
    _story("blood-basics", "corpo-umano",
        "Cosa c'è davvero nel tuo sangue?", ["sangue"],
        "Un fiume di 5 litri che scorre nel tuo corpo, che consegna ossigeno, combatte infezioni, ripara ferite e ti tiene in vita ogni secondo.",
        "https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=1200&q=80&auto=format&fit=crop",
        [
            ("Cinque litri", "Un adulto ha circa 5 litri di sangue, che circolano completamente in un minuto. Il cuore batte 100.000 volte al giorno, spingendo il sangue attraverso 100.000 km di vasi (se si allineassero, farebbero 2 volte il giro della Terra).", "water"),
            ("Cosa contiene", "Il sangue è per il 55% plasma (liquido con sali, proteine, ormoni) e per il 45% cellule: globuli rossi (portano ossigeno), globuli bianchi (difesa), piastrine (coagulazione). Un solo millilitro contiene circa 5 miliardi di globuli rossi.", "layers"),
            ("Il ferro dell'emoglobina", "I globuli rossi contengono emoglobina, una proteina con atomi di ferro. Il ferro lega l'ossigeno nei polmoni e lo rilascia in tutti gli altri tessuti. Ferro basso significa meno ossigeno consegnato: si chiama anemia, provoca stanchezza cronica.", "flash"),
            ("I gruppi", "Il tipo di sangue è determinato da proteine (antigeni) sui globuli rossi. I gruppi A, B, AB, 0 e il fattore Rh sono le combinazioni. In trasfusioni bisogna abbinare correttamente: sangue di gruppo sbagliato è attaccato dagli anticorpi del ricevente, con conseguenze potenzialmente letali.", "shield-checkmark"),
            ("Si rinnova", "I globuli rossi vivono circa 120 giorni. Il midollo osseo ne produce 2 milioni al secondo, per tutta la vita. Se doni sangue, in poche settimane il tuo corpo lo ricrea. È uno dei tessuti più rigenerativi che possieda.", "refresh"),
        ],
        "Il sangue trasporta ossigeno (via emoglobina), difende dalle infezioni, coagula le ferite. Il midollo osseo ne produce milioni di cellule ogni secondo."),

    # ==================== CULTURA (4) ====================
    _story("why-many-languages", "cultura",
        "Perché parliamo lingue così diverse?", ["lingue", "diverse"],
        "7.000 lingue nel mondo. Alcune sono cugine, altre estranee. Dietro c'è una storia di viaggi, isolamento e invenzioni geniali.",
        "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&q=80&auto=format&fit=crop",
        [
            ("7000 lingue", "Nel mondo si parlano circa 7.000 lingue. Alcune con miliardi di parlanti (cinese mandarino, inglese, spagnolo), altre con solo poche decine. Ogni lingua è un modo unico di organizzare pensiero, emozioni, tempo, spazio.", "globe"),
            ("Famiglie linguistiche", "Molte lingue derivano da antiche \"lingue madri\". Italiano, spagnolo, francese, romeno vengono tutte dal latino. Inglese, tedesco, olandese da una radice germanica. Questi rami condividono grammatica, parole, suoni per antica parentela. L'italiano e l'hindi hanno una radice comune (indoeuropea) di 6.000 anni fa.", "git-branch"),
            ("Isolamento genera differenze", "Quando un gruppo migra o si separa, la lingua evolve indipendentemente. In pochi secoli emergono differenze irriducibili. Il latino parlato in Roma è diventato italiano in Italia, spagnolo in Iberia, francese in Gallia. Isole geografiche o culturali producono lingue uniche in pochi millenni.", "arrow-forward"),
            ("Perché scrittura non è ovunque", "La scrittura è stata inventata solo poche volte nella storia (Sumer, Egitto, Cina, Mesoamerica). La maggior parte delle lingue del mondo è nata senza scrittura. Molte scritture attuali sono derivate da una sola: l'alfabeto fenicio, madre di greco, latino, arabo, ebraico.", "book"),
            ("Lingue che muoiono", "Ogni due settimane muore una lingua nel mondo. Un anziano che è l'ultimo parlante di una lingua porta con sé un pezzo unico di cultura, memoria, poesia. Le grandi lingue commerciali stanno assorbendo le piccole. L'UNESCO segue attivamente circa 3.000 lingue a rischio.", "warning"),
        ],
        "Le 7.000 lingue del mondo nascono da isolamento culturale e migrazioni. Molte condividono antiche radici comuni, ma ne muore una ogni due settimane."),
    _story("origin-alphabet", "cultura",
        "Chi ha inventato l'alfabeto?", ["alfabeto"],
        "26 lettere che compongono ogni testo che leggerai in vita. Chi le ha inventate e perché sono così poche?",
        "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80&auto=format&fit=crop",
        [
            ("Prima non c'erano lettere", "La prima scrittura era pittografica: disegni che rappresentavano oggetti o concetti (Egitto, Mesopotamia, Cina). Ma servivano migliaia di segni per esprimere tutto: solo scribi specializzati sapevano leggere. Non era democratica.", "book"),
            ("L'idea rivoluzionaria", "Intorno al 1800 a.C. nelle miniere del Sinai qualcuno ebbe un'idea geniale: usare i pittogrammi non per rappresentare cose ma suoni. Il disegno di una casa non significava più \"casa\", ma il suono B (perché \"casa\" in semitico iniziava con B). Bastavano poche decine di simboli per scrivere qualsiasi parola.", "sparkles"),
            ("I Fenici", "I Fenici (mercanti del Mediterraneo, 1500 a.C.) affinarono questo alfabeto in 22 lettere semplici e portabili. Con la loro flotta lo diffusero in tutto il Mediterraneo. Era un alfabeto \"consonantico\": senza vocali.", "boat"),
            ("I Greci aggiungono le vocali", "I Greci presero l'alfabeto fenicio e aggiunsero le vocali (A, E, I, O, U). Nasce così il primo vero alfabeto completo (VIII sec. a.C.). Da lì derivano: latino (che usi tu ora), cirillico (russo), copto, e centinaia di altri.", "git-branch"),
            ("Ancora oggi", "L'alfabeto latino con leggere variazioni copre circa il 40% della popolazione mondiale. Ha reso la scrittura accessibile, la stampa possibile, l'istruzione di massa realtà. 26 letterine sviluppate da minatori semitici hanno cambiato il mondo più di molte guerre.", "grid"),
        ],
        "L'alfabeto è nato tra i minatori semitici (1800 a.C.), è stato diffuso dai Fenici e completato con vocali dai Greci. Da lì tutti gli alfabeti moderni."),
    _story("chess-history", "cultura",
        "Perché gli scacchi affascinano da 1500 anni?", ["scacchi"],
        "Nati in India, cresciuti in Persia, perfezionati in Europa. Un gioco che riflette guerra, matematica e psicologia.",
        "https://images.unsplash.com/photo-1560174038-da43ac74f01b?w=1200&q=80&auto=format&fit=crop",
        [
            ("Nasce come guerra", "Gli scacchi nascono in India intorno al VI secolo come \"chaturanga\", una simulazione di battaglia con fanteria, cavalleria, elefanti, carri (che sono diventati pedone, cavallo, alfiere, torre). Il re al centro rappresentava il generale.", "shield-checkmark"),
            ("Attraverso i secoli", "I persiani lo adottarono come shatranj, gli arabi lo diffusero nel Medio Oriente e in Nord Africa. Arrivò in Europa attraverso la Spagna e la Sicilia (XI secolo). Nel Rinascimento le regole moderne emersero: la regina divenne la pezzo più potente, i pedoni potevano fare la mossa doppia.", "arrow-forward"),
            ("Un universo di possibilità", "Il numero di posizioni possibili in una partita di scacchi è più grande del numero di atomi nell'universo osservabile. Nessuna partita è mai identica a un'altra. Ogni mossa apre un albero di variazioni infinite.", "aperture"),
            ("Cervello vs macchina", "Nel 1997 Deep Blue di IBM sconfisse il campione del mondo Kasparov: fu la prima volta che un computer batté un umano di quel livello. Oggi anche uno smartphone gioca meglio di qualsiasi umano. Ma il fascino del gioco tra umani non è calato: anzi.", "hardware-chip"),
            ("Perché tanti giocatori", "Secondo la FIDE ci sono oltre 600 milioni di giocatori di scacchi nel mondo. Il gioco è economico, universale, non richiede lingua. Recentemente serie TV (\"La regina degli scacchi\") e piattaforme online hanno riacceso l'interesse. È uno dei pochi giochi ancora capaci di connettere generazioni e culture.", "sparkles"),
        ],
        "Gli scacchi nascono in India nel VI secolo come simulazione di guerra. Le posizioni possibili sono più degli atomi dell'universo osservabile."),
    _story("why-we-cry", "cultura",
        "Perché piangiamo?", ["piangiamo"],
        "Nessun altro animale versa lacrime emotive. Un mistero evolutivo che risolve più problemi di quanto pensi.",
        "https://images.unsplash.com/photo-1583223904441-a5cdec5c1cef?w=1200&q=80&auto=format&fit=crop",
        [
            ("Tre tipi di lacrime", "Il tuo occhio produce tre tipi di lacrime chimicamente diversi: quelle basali (lubrificano continuamente), quelle riflesse (reazione a fumo o cipolla), quelle emotive. Solo la terza è unica agli umani (probabilmente).", "water"),
            ("Contengono ormoni", "Le lacrime emotive contengono livelli più alti di ormoni dello stress (cortisolo, prolattina) rispetto a quelle riflesse. Piangere è letteralmente eliminare stress dal corpo. Molti riferiscono di sentirsi meglio dopo un pianto: è chimicamente vero.", "flask"),
            ("Segnale sociale", "Piangere è visibile agli altri. Segnala vulnerabilità e attiva empatia. Molte teorie evolutive suggeriscono che il pianto emotivo si sia sviluppato come strumento di connessione sociale nei gruppi umani. Chi piangeva riceveva più aiuto e conforto.", "people"),
            ("Perché anche di gioia", "Anche gioia intensa, orgoglio, sollievo possono farci piangere. Alcuni ricercatori pensano sia un modo del corpo di gestire emozioni troppo intense per essere elaborate. È come un valve di sfogo emotivo, che scarica qualsiasi eccesso, positivo o negativo.", "heart"),
            ("Chi piange di più", "Le donne piangono in media 5 volte al mese, gli uomini 1. Non è solo cultura: il testosterone inibisce la produzione di lacrime emotive. Prima della pubertà maschi e femmine piangono uguale. In molte culture antiche, piangere pubblicamente era prerogativa maschile durante lutti importanti.", "sparkles"),
        ],
        "Il pianto emotivo è unico agli umani. Le lacrime contengono ormoni dello stress: piangere è chimicamente scaricare tensione. E attiva empatia negli altri."),

    # ==================== CURIOSITA (4) ====================
    _story("why-lefties", "curiosita",
        "Perché il 10% delle persone è mancino?", ["mancino"],
        "Non è casuale, non è un difetto e non è cultura. È un mistero che i biologi cercano di risolvere da un secolo.",
        "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80&auto=format&fit=crop",
        [
            ("Un numero costante", "Circa il 10% degli esseri umani è mancino. La proporzione è stabile in tutte le culture, in tutte le epoche, in tutti i continenti. Anche nei fossili preistorici e nelle pitture rupestri, circa il 10% delle mani è sinistra. È una caratteristica antica e stabile.", "hand-left"),
            ("Uno svantaggio evolutivo?", "In una società di destri, essere mancini è più difficile: strumenti, porte, scrittura sono pensati per destri. In passato la percentuale doveva essere ancora più penalizzante. Eppure il 10% resta costante. Deve esserci un vantaggio compensativo.", "warning"),
            ("Vantaggio nel combattimento", "Una teoria: negli scontri fisici, i mancini hanno un vantaggio a sorpresa (gli avversari sono abituati a colpi di destro). Studi mostrano che negli sport di combattimento (pugilato, scherma, arti marziali) i mancini vincono più della loro proporzione. La stessa cosa potrebbe essere accaduta nella preistoria.", "flash"),
            ("Cervelli diversi", "Il cervello del mancino è più simmetrico rispetto a quello del destro (le funzioni sono meno lateralizzate). Alcuni studi mostrano più creatività divergente, meno rigidità di pensiero. Molti artisti, matematici, musicisti sono mancini (Leonardo, Einstein, Bach forse, Kurt Cobain).", "sparkles"),
            ("Non è solo la mano", "L'80% di ciò che chiamiamo \"mancinismo\" è determinato geneticamente. Non è solo la mano: molti mancini preferiscono anche gamba, occhio, orecchio sinistri. C'è una lateralità cerebrale complessiva che influenza molte piccole cose. E che continua a incuriosire gli scienziati.", "aperture"),
        ],
        "Circa il 10% degli umani è mancino, stabile in ogni cultura. Il vantaggio evolutivo probabile è la sorpresa nel combattimento. Ha anche cervelli più simmetrici."),
    _story("colors-cant-see", "curiosita",
        "Ci sono colori che non puoi vedere?", ["colori"],
        "Sì, milioni. Il tuo occhio è un sensore limitato. Le api vedono altre cose, i serpenti pure. Il mondo è più colorato di come lo percepisci.",
        "https://images.unsplash.com/photo-1489493887464-892be6d1daae?w=1200&q=80&auto=format&fit=crop",
        [
            ("Solo una finestra", "L'occhio umano vede solo le onde elettromagnetiche tra 380 e 780 nanometri (violetto → rosso). Ma esistono molte più lunghezze d'onda: radio, microonde, infrarosso, ultravioletto, raggi X, gamma. Vediamo meno dell'1% dello spettro elettromagnetico.", "eye"),
            ("Le api vedono ultravioletto", "Le api hanno recettori sensibili all'ultravioletto. Molti fiori hanno pattern UV invisibili a noi ma perfettamente visibili alle api, come frecce che indicano il nettare. Quello che chiamiamo \"un girasole giallo\" ha per un'ape una decorazione UV incredibile.", "flower"),
            ("Serpenti vedono calore", "Alcuni serpenti (crotalo, boa) hanno organi che rilevano infrarosso, cioè calore. Vedono topi al buio come figure luminose contro sfondo freddo. Un mondo termico che noi possiamo solo intuire con telecamere speciali.", "flame"),
            ("Colori impossibili", "Se qualcuno riuscisse a stimolare i coni del rosso e del verde contemporaneamente (di norma si escludono), il cervello vedrebbe un colore che non esiste in natura. Alcuni esperimenti riportano un colore \"rosso-verde\" descritto come indescrivibile. Esistono colori che il tuo cervello sa creare ma che non hai mai visto.", "aperture"),
            ("I mantis shrimp", "I gamberi mantide hanno 16 tipi di recettori di colore (noi ne abbiamo 3). Vedono probabilmente un mondo così ricco che neanche riusciamo a immaginare. Il colore non è nel mondo: è nella percezione. Ogni specie vive un pianeta cromatico diverso.", "sparkles"),
        ],
        "Vediamo meno dell'1% dello spettro elettromagnetico. Api, serpenti e mantis shrimp vedono mondi cromatici radicalmente diversi dal nostro."),
    _story("time-zones", "curiosita",
        "Perché ci sono i fusi orari?", ["fusi", "orari"],
        "Prima delle ferrovie non servivano. Oggi 40 fusi diversi complicano voli, chiamate e capodanni. Ecco come sono nati.",
        "https://images.unsplash.com/photo-1509909756405-be0199881695?w=1200&q=80&auto=format&fit=crop",
        [
            ("Ora locale", "Fino a fine '800, ogni città aveva la sua ora locale in base alla posizione del Sole. Mezzogiorno era quando il Sole era al punto più alto. Roma, Milano e Napoli avevano ore leggermente diverse. Nessun problema: viaggiare tra città richiedeva ore o giorni.", "sunny"),
            ("Le ferrovie", "Con l'arrivo delle ferrovie nell'800 nacque un problema: gli orari dei treni erano un caos, ogni stazione aveva la sua ora. Servivano orari standardizzati, altrimenti sarebbe stato impossibile programmare partenze e arrivi. Nel 1884 la conferenza di Washington divise il mondo in 24 fusi da 15° ciascuno.", "swap-horizontal"),
            ("Da Greenwich in poi", "Il meridiano zero fu fissato a Greenwich, Londra. Da lì i fusi orari si contano verso est e ovest. L'Italia è UTC+1 (o UTC+2 in ora legale). New York UTC-5, Tokyo UTC+9. In teoria semplice, in pratica pieno di eccezioni.", "compass"),
            ("Eccezioni divertenti", "La Cina ha un solo fuso orario nazionale, nonostante sia larga come 5. India e Sri Lanka sono a mezz'ora di distanza (UTC+5:30). Il Nepal è a UTC+5:45. Alcune isole del Pacifico hanno saltato un giorno intero cambiando fuso. E la Corea del Nord ha cambiato l'ora tre volte in dieci anni.", "warning"),
            ("Ora legale", "L'ora legale (spostare avanti l'orologio in estate) fu inventata per risparmiare energia. La sua efficacia è discussa. L'UE ha annunciato di voler abolirla ma non l'ha fatto. Cambiare orologio due volte l'anno costa jet-lag, incidenti e disturbi del sonno. È forse un residuo del passato che sopravvive per inerzia.", "sparkles"),
        ],
        "I fusi orari furono creati nel 1884 per organizzare le ferrovie. Prima ogni città aveva la sua ora. Oggi la Cina ha un solo fuso, il Nepal ne ha uno a 5:45."),
    _story("why-mirror-flip", "curiosita",
        "Perché lo specchio ti inverte destra e sinistra?", ["specchio"],
        "Il tuo lato destro nello specchio diventa sinistra. Ma il pavimento resta sotto. Come sceglie lo specchio cosa girare?",
        "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1200&q=80&auto=format&fit=crop",
        [
            ("Non ti inverte davvero", "Contrariamente all'intuizione, lo specchio non inverte destra e sinistra. Ti inverte davanti-dietro. La mano che tu vedi \"a destra\" nello specchio è la mano che tu hai a destra: solo che dal punto di vista del riflesso è a sinistra.", "swap-horizontal"),
            ("Fai la prova", "Punta il dito verso lo specchio: il riflesso lo punta verso di te. Alza la mano destra: il riflesso alza la mano che tu vedi a destra ma che, se il riflesso fosse una persona reale, sarebbe la sua sinistra. Lo specchio inverte l'asse perpendicolare, non l'asse orizzontale.", "arrow-forward"),
            ("Perché sembra sinistra-destra", "L'illusione nasce dal fatto che il cervello immagina che il riflesso sia una persona che ci guarda. E una persona di fronte a te ha la destra dove tu hai la sinistra. Ma il riflesso non è una persona che ha ruotato: è solo un'immagine invertita di profondità.", "aperture"),
            ("Testo negli specchi", "Il testo negli specchi appare invertito solo per come lo leggiamo, non perché lo specchio giri le lettere. Se scrivi \"AMBULANZA\" al contrario, sarà leggibile allo specchio. È il motivo per cui i camion delle ambulanze hanno la scritta \"AZNALUBMA\" davanti: gli automobilisti la leggono correttamente allo specchio retrovisore.", "medkit"),
            ("Sarai tu?", "Il volto che vedi allo specchio non è il tuo vero volto. È il tuo volto invertito. Le persone che ti conoscono ti vedono in modo leggermente diverso da come tu ti vedi. Foto e video ti mostrano il tuo vero volto: molti trovano strano come suonano/appaiono, perché sono abituati alla loro versione speculare.", "sparkles"),
        ],
        "Lo specchio non inverte destra-sinistra: inverte davanti-dietro. L'illusione nasce dal fatto che il cervello immagina il riflesso come una persona ruotata di fronte."),
]
