"""PAUSE v4 — ampliamento catalogo (parte B): Animali, Storia, Psicologia, Corpo umano.
3 curiosità + 3 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ ANIMALI ------------------------------
    mk("animali", "v4-polpo-cervelli",
       "Il polpo ha nove cervelli e tre cuori", ["polpo", "cervelli"],
       "Sa aprire barattoli, riconoscere le persone e cambiare colore in un istante. Ed è un mollusco, parente delle lumache.",
       "Il polpo ha un cervello centrale e uno per ogni braccio, tre cuori e sangue blu; è tra gli invertebrati più intelligenti e la sua intelligenza si è evoluta indipendentemente dalla nostra.",
       "",
       [
        ("Due terzi dei neuroni nelle braccia",
         "Il polpo ha circa 500 milioni di neuroni, quanti un cane. Ma solo un terzo sta nel cervello centrale: il resto è distribuito nelle otto braccia, ognuna con un proprio ganglio. Un braccio può esplorare, assaggiare e afferrare in autonomia mentre l'animale guarda altrove."),
        ("Tre cuori e sangue blu",
         "Due cuori pompano il sangue attraverso le branchie, il terzo lo distribuisce al corpo. Il sangue è blu perché usa il rame (emocianina) invece del ferro per trasportare l'ossigeno. Quando il polpo nuota, il cuore principale si ferma: per questo preferisce camminare sul fondo."),
        ("Un genio tra i molluschi",
         "Nei laboratori i polpi risolvono labirinti, aprono contenitori con tappo a vite, riconoscono volti umani e giocano con oggetti. Alcuni sono fuggiti dalla vasca di notte per mangiare i pesci di quella accanto e tornare indietro. Tutto questo con un'anatomia che non condivide nulla con la nostra."),
        ("Un'intelligenza aliena",
         "L'antenato comune tra noi e il polpo era un verme di 600 milioni di anni fa senza cervello vero. L'intelligenza del polpo è nata per una strada completamente diversa dalla nostra: studiarlo è il modo più vicino che abbiamo per incontrare una mente non umana."),
       ]),
    mk("animali", "v4-migrazione-anguille",
       "Il mistero delle anguille che nascono in mezzo all'Atlantico", ["anguille", "Atlantico"],
       "Per 2.000 anni nessuno ha mai visto un'anguilla riprodursi. Aristotele pensava nascessero dal fango. La verità è ancora più strana.",
       "Le anguille europee nascono nel Mar dei Sargassi, attraversano l'oceano da larve, vivono decenni nei fiumi europei e tornano a morire dove sono nate, per 6.000 km.",
       "",
       [
        ("Nessuno le ha mai viste deporre",
         "Per secoli l'origine delle anguille fu un enigma: non si trovavano mai uova né esemplari maturi. Aristotele ipotizzò che nascessero dal fango, Plinio da pezzi di pelle strofinati sulle rocce. Sigmund Freud, da studente, passò settimane a dissezionarne centinaia in cerca dei testicoli, senza successo."),
        ("La culla nei Sargassi",
         "Solo nel 1922 il biologo danese Johannes Schmidt, dopo vent'anni di campionamenti, trovò le larve più piccole nel Mar dei Sargassi, a est delle Bahamas. Le anguille di tutta Europa nascono lì. Le larve, trasparenti e a forma di foglia, si lasciano trasportare dalla Corrente del Golfo per 1-3 anni."),
        ("Una vita in tre forme",
         "Arrivate alle coste europee diventano 'cieche', anguille di vetro trasparenti che risalgono i fiumi. Lì crescono per 10-20 anni come anguille gialle. Poi, un autunno, cambiano: occhi enormi, pancia argentata, stomaco che si dissolve. Smettono di mangiare e partono verso il mare."),
        ("Il viaggio finale",
         "Percorrono fino a 6.000 km, nuotando a centinaia di metri di profondità di giorno e in superficie di notte, senza cibo, per 6-12 mesi. Nel 2022 alcune sono state seguite con trasmettitori fino ai Sargassi. Della riproduzione in sé, però, non esiste ancora una singola osservazione diretta."),
       ]),
    mk("animali", "v4-cane-naso",
       "Il naso di un cane può sentire il tempo", ["naso", "cane"],
       "Non annusa solo cosa è passato di lì: sa da quanto. E dal fiato può capire se sei nervoso, malato o incinta.",
       "Il cane ha 300 milioni di recettori olfattivi contro i nostri 6 milioni e un cervello dedicato agli odori 40 volte più grande in proporzione; percepisce la 'storia' degli odori nel tempo.",
       "",
        [
        ("Un naso costruito diversamente",
         "Quando un cane inspira, una piega nel naso separa l'aria: una parte va ai polmoni, l'altra a una camera dedicata solo all'olfatto, dove può ristagnare e venire analizzata. Le narici lavorano in modo indipendente, così il cane capisce da quale lato arriva l'odore, come noi con l'udito stereo."),
        ("Cinquanta milioni di volte più sensibile",
         "Il cane ha fino a 300 milioni di recettori olfattivi, noi circa 6 milioni. Riesce a percepire alcune sostanze diluite in una parte su un trilione: l'equivalente di un cucchiaino di zucchero in due piscine olimpioniche. Le razze da fiuto come il Bloodhound seguono tracce vecchie di giorni."),
        ("Annusare il tempo",
         "Un odore lasciato ieri è più debole di uno di un'ora fa. Il cane confronta l'intensità delle impronte di una traccia e capisce in che direzione la persona camminava: verso dove le orme sono più fresche. Percepisce il passato recente come una sequenza, quasi un filmato olfattivo."),
        ("Medici a quattro zampe",
         "Cani addestrati individuano tumori, cali di glicemia, crisi epilettiche in arrivo e infezioni annusando fiato, pelle o urina, con accuratezza spesso superiore al 90%. Sentono le molecole che il corpo rilascia quando qualcosa non va, molto prima che un esame le rilevi."),
       ]),

    # ------------------------------ STORIA ------------------------------
    mk("storia", "v4-biblioteca-alessandria",
       "La Biblioteca di Alessandria non bruciò in una notte", ["Biblioteca", "Alessandria"],
       "L'immagine di un incendio che cancella il sapere antico è potente ma sbagliata. La fine della biblioteca più famosa fu molto più lenta e più banale.",
       "La Biblioteca declinò per secoli: tagli ai fondi, purghe di studiosi, guerre civili e incendi parziali. Il colpo finale fu l'indifferenza, non una fiamma.",
       "",
       [
        ("La più grande del mondo antico",
         "Fondata intorno al 285 a.C. dai Tolomei, arrivò forse a mezzo milione di rotoli di papiro. Gli studiosi erano stipendiati dal re; ogni nave che attraccava veniva perquisita e i libri copiati. Qui Eratostene misurò la circonferenza terrestre e Euclide scrisse gli Elementi."),
        ("Cesare e il primo fuoco",
         "Nel 48 a.C. Giulio Cesare, assediato ad Alessandria, incendiò le navi nel porto. Le fiamme si estesero ai magazzini vicini e bruciarono decine di migliaia di rotoli, forse depositi in attesa di catalogazione. Fu un colpo grave, ma la Biblioteca continuò a funzionare per secoli."),
        ("La morte lenta",
         "Nel 145 a.C. Tolomeo VIII espulse gli intellettuali stranieri. I fondi si ridussero, i papiri non copiati si sbriciolavano in 200 anni. Nel 272 l'imperatore Aureliano distrusse il quartiere reale; nel 391 il tempio del Serapeo, con la biblioteca 'figlia', fu chiuso. Ogni generazione perse un pezzo."),
        ("La vera lezione",
         "Non serve un incendio per perdere il sapere: basta smettere di pagare chi lo copia. Molto di ciò che c'era sopravvisse altrove, a Costantinopoli, Baghdad, nei monasteri. E ciò che si perse, si perse soprattutto perché nessuno lo ritenne più abbastanza importante da ricopiarlo."),
       ]),
    mk("storia", "v4-cleopatra-piramidi",
       "Cleopatra era più vicina a noi che alle piramidi", ["Cleopatra", "piramidi"],
       "La immaginiamo tra i faraoni e le sfingi. Ma quando Cleopatra nacque, la Grande Piramide era già un monumento antico di 2.500 anni.",
       "La Grande Piramide fu costruita intorno al 2560 a.C.; Cleopatra visse dal 69 al 30 a.C. Tra i due c'è più tempo che tra Cleopatra e il primo iPhone.",
       "",
       [
        ("Facciamo i conti",
         "La Piramide di Cheope risale al 2560 a.C. circa. Cleopatra VII nacque nel 69 a.C. Tra i due: quasi 2.500 anni. Da Cleopatra a oggi ne sono passati poco più di 2.050. Cleopatra è quindi cronologicamente più vicina a noi che ai costruttori delle piramidi."),
        ("Una greca sul trono d'Egitto",
         "Cleopatra apparteneva alla dinastia dei Tolomei, discendenti di un generale macedone di Alessandro Magno. La corte parlava greco; lei fu la prima della sua famiglia, in 300 anni, a imparare l'egiziano. Parlava, secondo Plutarco, nove lingue."),
        ("L'Egitto per gli egizi era già antico",
         "Ai tempi di Cleopatra le piramidi erano già mete turistiche per greci e romani, che ci incidevano graffiti. Gli egizi stessi facevano restauri su templi di mille anni prima. La civiltà egizia durò 3.000 anni: più del tempo che ci separa dai suoi ultimi faraoni."),
        ("Perché ci confondiamo",
         "Il nostro cervello comprime il passato remoto: 'antichità' diventa un unico blocco. Un trucco per orientarsi: Roma fondata (753 a.C.) sta quasi a metà tra piramidi e Cleopatra. E Tyrannosaurus rex e Stegosaurus, che immaginiamo insieme, sono separati da 80 milioni di anni."),
       ]),
    mk("storia", "v4-guerra-piu-breve",
       "La guerra più breve della storia durò 38 minuti", ["guerra", "38 minuti"],
       "Il 27 agosto 1896, tra il Regno Unito e il sultanato di Zanzibar, iniziò e finì un conflitto prima che a Londra facessero colazione.",
       "La guerra anglo-zanzibariana del 1896 durò tra 38 e 45 minuti: la flotta britannica bombardò il palazzo del sultano che aveva preso il potere senza il loro consenso.",
       "",
       [
        ("Una successione sgradita",
         "Il 25 agosto 1896 il sultano di Zanzibar, filo-britannico, morì improvvisamente. Suo cugino Khalid bin Barghash occupò il palazzo e si autoproclamò sultano. Il trattato con Londra prevedeva che ogni successore avesse l'approvazione britannica: Khalid non l'aveva chiesta."),
        ("L'ultimatum",
         "I britannici gli diedero fino alle 9 del mattino del 27 agosto per lasciare il palazzo. Khalid radunò 2.800 uomini, qualche cannone e lo yacht reale. Nella baia, cinque navi da guerra britanniche puntarono i cannoni sul palazzo."),
        ("38 minuti",
         "Alle 9:02 iniziò il bombardamento. Il palazzo di legno prese fuoco, lo yacht fu affondato, i cannoni di Khalid messi a tacere in pochi minuti. Alle 9:40 la bandiera del sultano fu abbattuta e il fuoco cessò. Circa 500 zanzibariani morirono o furono feriti; un solo marinaio britannico rimase ferito."),
        ("Il dopo",
         "Khalid fuggì nel consolato tedesco e fu portato in esilio in Tanganica. I britannici installarono il loro candidato e, come indennizzo, chiesero agli zanzibariani di pagare le munizioni sparate. Fu uno degli episodi più brutalmente sbilanciati dell'età degli imperi."),
       ]),

    # ------------------------------ PSICOLOGIA ------------------------------
    mk("psicologia", "v4-effetto-zeigarnik",
       "Perché le cose lasciate a metà ti restano in testa", ["a metà", "testa"],
       "Un messaggio non risposto, una serie interrotta sul cliffhanger, un lavoro incompleto: il cervello non li lascia andare. Ha un nome, ed è anche un trucco utile.",
       "L'effetto Zeigarnik: i compiti incompleti restano più accessibili in memoria di quelli finiti. Spiega i cliffhanger, l'ansia da lista e come vincere la procrastinazione.",
       "",
       [
        ("I camerieri di Vienna",
         "Negli anni Venti la psicologa Bluma Zeigarnik notò che i camerieri ricordavano perfettamente le ordinazioni non ancora pagate, ma le dimenticavano subito dopo il conto. In laboratorio confermò: chi veniva interrotto durante un compito lo ricordava quasi due volte meglio di chi lo finiva."),
        ("Una tensione che cerca chiusura",
         "Un compito iniziato crea una tensione mentale che resta attiva finché non è risolto. È il motivo per cui una serie che finisce l'episodio sul momento cruciale ti costringe a vedere il prossimo, e per cui un messaggio letto e non risposto torna a galla mentre cerchi di dormire."),
        ("Il rovescio: il caos delle liste",
         "Dieci cose aperte sono dieci tensioni in sottofondo che consumano attenzione. Studi recenti mostrano però che basta scrivere un piano concreto per il compito, non farlo, per far calare la tensione: il cervello si fida che sarà gestito e smette di ricordartelo."),
        ("Usalo a tuo favore",
         "Per iniziare qualcosa che rimandi da settimane, lavoraci solo cinque minuti: una volta aperto, il compito ti tirerà a finirlo. Gli scrittori usano il trucco al contrario: smettono a metà di una frase, così il giorno dopo ripartono senza fatica. Il cervello odia le cose a metà: mettilo al lavoro."),
       ]),
    mk("psicologia", "v4-paradosso-scelta",
       "Troppe opzioni ti rendono meno felice", ["opzioni", "felice"],
       "Ventiquattro marmellate vendono meno di sei. Più scelta sembra libertà, ma spesso è paralisi, e dopo la scelta arriva il rimpianto.",
       "Il paradosso della scelta: oltre una certa soglia, più opzioni riducono la probabilità di decidere e la soddisfazione per la decisione presa.",
       "",
       [
        ("L'esperimento delle marmellate",
         "In un supermercato californiano, un banco con 24 marmellate attirava più curiosi di uno con 6. Ma solo il 3% dei visitatori del banco grande comprava, contro il 30% di quello piccolo. Più opzioni, dieci volte meno acquisti."),
        ("Perché ci blocchiamo",
         "Ogni opzione in più è un confronto in più da fare e una rinuncia in più da giustificare. Con molte alternative cresce il timore di sbagliare: aspettiamo, rimandiamo, o scegliamo l'opzione predefinita. Nei piani pensione, ogni 10 fondi in più fanno calare le adesioni del 2%."),
        ("Il rimpianto dopo",
         "Chi sceglie tra molte opzioni è meno soddisfatto anche quando sceglie bene: le alternative scartate restano in mente come 'e se'. Lo psicologo Barry Schwartz distingue i massimizzatori, che cercano il meglio assoluto e soffrono, dai soddisfacenti, che si fermano al 'abbastanza buono' e vivono meglio."),
        ("Ridurre per decidere",
         "Prima di scegliere, fissa 2-3 criteri che contano davvero e scarta tutto ciò che non li rispetta. Datti un tempo limite. E una volta deciso, smetti di cercare: il confronto continuo non migliora la scelta, peggiora solo l'umore. Meno menu, più cena."),
       ]),
    mk("psicologia", "v4-effetto-spettatore",
       "Perché in mezzo alla folla nessuno interviene", ["folla", "nessuno"],
       "Più persone assistono a un'emergenza, meno probabile è che qualcuno aiuti. Non per crudeltà: per un meccanismo che si può disinnescare con una frase.",
       "L'effetto spettatore: la responsabilità si diluisce tra i presenti e ognuno guarda gli altri per capire se è grave. Rivolgersi a una persona specifica lo interrompe.",
       "",
       [
        ("Un caso che cambiò la psicologia",
         "Nel 1964 a New York Kitty Genovese fu aggredita sotto casa; i giornali scrissero che 38 vicini avevano visto senza intervenire. La cifra era esagerata, ma spinse due psicologi, Darley e Latané, a studiare in laboratorio perché i gruppi reagiscono peggio dei singoli."),
        ("La responsabilità si divide",
         "Nei loro esperimenti, chi credeva di essere l'unico testimone di una crisi interveniva nell'85% dei casi. Chi pensava che ci fossero altre quattro persone, solo nel 31%. Se siamo in dieci, ognuno sente un decimo del dovere. E tutti pensano: 'qualcuno avrà già chiamato'."),
        ("Guardiamo gli altri per capire",
         "In una situazione ambigua cerchiamo negli altri il segnale che è grave. Ma anche gli altri stanno guardando noi, e tutti vedono facce calme. È l'ignoranza pluralistica: un gruppo di persone preoccupate che si convincono a vicenda che non succede nulla."),
        ("Come romperlo",
         "Se sei tu ad avere bisogno: indica una persona precisa. 'Tu, con la giacca blu, chiama il 112' funziona molto meglio di 'aiuto'. Se sei tu il testimone: agisci per primo, anche solo chiedendo 'tutto bene?'. Una persona che si muove sblocca tutte le altre."),
       ]),

    # ------------------------------ CORPO UMANO ------------------------------
    mk("corpo-umano", "v4-pelle-oca",
       "Perché ci viene la pelle d'oca (e a cosa serviva)", ["pelle d'oca"],
       "Freddo, paura, un brano di musica che ti colpisce: la pelle si increspa. È un riflesso che aveva senso quando eravamo molto più pelosi.",
       "La pelle d'oca è la contrazione dei muscoli alla base dei peli, un riflesso ereditato dai mammiferi pelosi per isolarsi dal freddo o apparire più grandi. In noi resta come eco emotiva.",
       "",
       [
        ("Piccoli muscoli sotto ogni pelo",
         "Alla base di ogni pelo c'è un muscolo minuscolo, l'erettore del pelo. Quando il sistema nervoso simpatico lo attiva, il pelo si raddrizza e la pelle intorno si solleva formando la 'bollicina'. È involontario: non puoi farlo apposta né fermarlo."),
        ("Un cappotto per animali pelosi",
         "In un gatto o in un orso, sollevare il pelo intrappola uno strato d'aria che isola dal freddo. E rende l'animale più grosso: il gatto che 'si gonfia' davanti a un cane sta usando lo stesso riflesso per intimidire. Per i nostri antenati pelosi funzionava allo stesso modo."),
        ("Oggi serve a poco",
         "Con i peli corti che abbiamo, l'effetto termico è trascurabile. Il riflesso però è rimasto collegato agli stessi circuiti: freddo e adrenalina. Per questo la paura, la rabbia e la sorpresa lo scatenano ancora, anche in una stanza calda."),
        ("I brividi della musica",
         "Circa la metà delle persone prova pelle d'oca ascoltando musica, di solito in un passaggio inatteso: un crescendo, l'ingresso di una voce. Il cervello rilascia dopamina come per una ricompensa. Chi lo prova più spesso ha più connessioni tra aree uditive ed emotive: è un tratto, non un caso."),
       ]),
    mk("corpo-umano", "v4-stomaco-acido",
       "Il tuo stomaco potrebbe sciogliere una lametta", ["stomaco", "lametta"],
       "Dentro di te c'è un acido forte quanto quello delle batterie. E la domanda giusta non è come digerisce il cibo, ma perché non digerisce te.",
       "L'acido cloridrico dello stomaco ha pH 1-2; le pareti si difendono con uno strato di muco e bicarbonato e si rinnovano completamente ogni pochi giorni.",
       "",
       [
        ("pH 1,5",
         "Le cellule della parete gastrica producono acido cloridrico che porta il pH dello stomaco tra 1 e 2, simile a quello dell'acido delle batterie. In esperimenti di laboratorio, lamette da barba immerse in succo gastrico si sono dissolte in circa 24 ore. Il compito dell'acido è denaturare le proteine e uccidere i microbi."),
        ("Lo scudo di muco",
         "La parete non si scioglie grazie a uno strato di muco spesso meno di un millimetro, ricco di bicarbonato che neutralizza l'acido proprio a contatto con le cellule. Il muco si rinnova di continuo e le cellule dello stomaco vengono sostituite ogni 3-5 giorni: è uno dei tessuti che si ricambia più in fretta."),
        ("Quando lo scudo cede",
         "Un batterio, l'Helicobacter pylori, riesce a vivere nel muco neutralizzando l'acido intorno a sé e lo indebolisce: è la causa principale delle ulcere, insieme all'abuso di antinfiammatori. Per decenni si credette che le ulcere dipendessero dallo stress; chi lo scoprì, Barry Marshall, bevve una coltura del batterio per dimostrarlo e vinse il Nobel."),
        ("Il bruciore",
         "Il reflusso non è acido 'in eccesso': è acido nel posto sbagliato. L'esofago non ha lo scudo dello stomaco e brucia. Un pasto abbondante, sdraiarsi subito dopo o il fumo rilassano la valvola che separa i due organi. Lo stomaco è fatto per contenere quel fuoco; il resto di te no."),
       ]),
    mk("corpo-umano", "v4-sbadiglio",
       "Perché sbadigliamo (e perché è contagioso)", ["sbadiglio", "contagioso"],
       "Non è per mancanza di ossigeno: quella teoria è stata smentita. Le ipotesi vere sono più interessanti e riguardano il cervello e l'empatia.",
       "Lo sbadiglio probabilmente raffredda il cervello e segnala il passaggio tra stati di vigilanza; il contagio è legato all'empatia e cresce con la vicinanza sociale.",
       "",
       [
        ("Non è l'ossigeno",
         "L'idea che sbadigliamo per prendere più ossigeno è stata testata negli anni Ottanta: far respirare più ossigeno o più anidride carbonica non cambia la frequenza degli sbadigli. Sbadigliano anche i feti nel grembo, dove non respirano affatto."),
        ("Un condizionatore per il cervello",
         "L'ipotesi oggi più solida: lo sbadiglio raffredda il cervello. La grande inspirazione e lo stiramento della mascella aumentano il flusso di sangue fresco verso la testa. Le persone sbadigliano di più con la fronte calda e meno con un impacco freddo, e più in estate che in inverno."),
        ("Un segnale di transizione",
         "Sbadigliamo quando passiamo da uno stato all'altro: prima di dormire, al risveglio, quando ci annoiamo o quando siamo tesi prima di un esame. Anche i paracadutisti sbadigliano prima del lancio. Sembra un modo del corpo per 'resettare' l'attenzione."),
        ("Il contagio dell'empatia",
         "Vedere, sentire o anche solo leggere di uno sbadiglio ne innesca uno nel 40-60% delle persone. L'effetto è più forte tra familiari e amici che tra estranei, e compare nei bambini solo intorno ai 4-5 anni, insieme all'empatia. Anche i cani sbadigliano quando sbadiglia il loro padrone."),
       ]),
]

LESSONS = [
    # ------------------------------ ANIMALI ------------------------------
    L("animali", "v4-lez-osservare-uccelli",
      "Riconoscere gli uccelli in città: il metodo in 4 passi", ["uccelli"],
      "Anche nel quartiere più cementificato vivono 20-30 specie. Impara a distinguerle con il metodo dei birdwatcher, senza binocolo.",
      "Identificare gli uccelli comuni osservando dimensione, forma, comportamento e canto.",
      "Parti da taglia e sagoma, poi guarda come si muove e dove sta, infine ascolta. Cinque specie urbane ti bastano per iniziare a leggere il cielo del quartiere.",
      [
       ("Passo 1 — Taglia e sagoma",
        "Prima del colore, chiediti: è grande come un passero, un merlo o un piccione? Ha coda lunga o corta, becco sottile o robusto? La gazza è inconfondibile per la coda lunga; il codirosso per la coda che trema. Il colore inganna con la luce; la forma no."),
       ("Passo 2 — Come si muove",
        "Il merlo corre e si ferma a terra a scatti. La cinciallegra fa acrobazie a testa in giù sui rami. Il pettirosso salta e ti guarda. Il rondone non si posa mai e vola urlando in gruppo. Il comportamento è una firma più affidabile del piumaggio."),
       ("Passo 3 — Dove sta",
        "Piccioni sui cornicioni, storni in stormi serali sugli alberi, passeri nelle siepi, gabbiani sui tetti alti, taccole sui campanili. Ogni specie ha un posto preferito. Chiediti 'chi mi aspetto qui?' e la lista dei sospetti si riduce a tre."),
       ("Passo 4 — Ascolta",
        "Il merlo canta melodie flautate al tramonto. La cinciallegra ripete 'ti-ciù ti-ciù' come una pompa. Il rondone fischia acuto in volo. Il piccione fa il classico tubare. Un'app di riconoscimento dei canti confermerà le tue ipotesi: dopo dieci sessioni non ti servirà più."),
      ]),
    L("animali", "v4-lez-incontro-fauna",
      "Cosa fare se incontri un animale selvatico", ["selvatico"],
      "Un cinghiale al parco, una vipera sul sentiero, un cane sconosciuto: reagire male è la causa principale degli incidenti. Quattro regole valide quasi sempre.",
      "Sapere come comportarsi con gli animali selvatici più comuni in Italia per evitare rischi a sé e all'animale.",
      "Non correre, non dare le spalle, non avvicinarti ai cuccioli, non dare da mangiare. Datti spazio con calma e lascia sempre all'animale una via di fuga.",
      [
       ("Passo 1 — Fermati e non correre",
        "La fuga scatena l'istinto di inseguimento nei predatori e il panico negli erbivori. Fermati, parla con voce bassa e ferma per farti riconoscere come umano, e arretra lentamente senza voltare le spalle. Quasi tutti gli animali vogliono solo che tu te ne vada."),
       ("Passo 2 — Il cinghiale",
        "È l'incontro più frequente in Italia. Non è aggressivo se non si sente minacciato, ma una femmina con i piccoli attacca per difenderli. Non metterti tra lei e i cuccioli, allontanati in diagonale e, se carica, mettiti dietro un albero o su un punto alto. Mai dargli da mangiare: è ciò che li porta in città."),
       ("Passo 3 — Serpenti e insetti",
        "Le vipere mordono solo se calpestate o toccate: guarda dove metti mani e piedi, batti i bastoncini sul sentiero, e se ne vedi una fermati e lasciala andare. In caso di morso, stai calmo, immobilizza l'arto e vai in ospedale: niente incisioni, lacci o succhiamenti. Per vespe e calabroni: allontanati senza agitare le braccia."),
       ("Passo 4 — Il cane sconosciuto",
        "Non fissarlo negli occhi, non urlare, non correre. Resta di lato, braccia ferme, e ignoralo. Se si avvicina, lascia che ti annusi. Se attacca, metti tra te e lui uno zaino o una giacca. Con un cane al guinzaglio del tuo, mettiti tra i due e allontanati. Il 90% degli incontri finisce con un'annusata."),
      ]),
    L("animali", "v4-lez-catena-alimentare",
      "La catena alimentare: perché i predatori sono sempre pochi", ["catena alimentare"],
      "Miliardi di insetti, milioni di rane, migliaia di serpenti, pochi falchi. Non è un caso: è una legge dell'energia che puoi capire in quattro passi.",
      "Capire come l'energia passa tra i livelli di una catena alimentare e perché ogni livello è più piccolo del precedente.",
      "A ogni passaggio della catena alimentare si trasferisce solo circa il 10% dell'energia. Per questo i predatori al vertice sono pochi e sono i primi a scomparire quando l'ecosistema soffre.",
      [
       ("Passo 1 — Tutto parte dal Sole",
        "Le piante catturano l'energia del Sole con la fotosintesi: sono i produttori. Gli erbivori che le mangiano sono consumatori primari; i carnivori che mangiano erbivori sono secondari; chi mangia i carnivori è al vertice. I decompositori, funghi e batteri, chiudono il cerchio riciclando i morti."),
       ("Passo 2 — La regola del 10%",
        "Quando un coniglio mangia erba, usa gran parte dell'energia per vivere, muoversi e scaldarsi. Solo circa il 10% diventa 'coniglio', cioè cibo disponibile per la volpe. Lo stesso vale a ogni livello: 1.000 kg di erba fanno 100 kg di conigli, che fanno 10 kg di volpe."),
       ("Passo 3 — La piramide",
        "Per questo gli ecosistemi hanno la forma di una piramide: tanta biomassa vegetale alla base, sempre meno salendo. Un leone ha bisogno di un territorio con migliaia di erbivori, che hanno bisogno di chilometri quadrati di savana. Non ci saranno mai tanti leoni quante gazzelle."),
       ("Passo 4 — Perché i predatori sono fragili",
        "Chi sta in alto dipende da tutti i livelli sotto. Un pesticida che riduce gli insetti del 30% può cancellare i rapaci di una zona. E le tossine si concentrano salendo: il mercurio è più alto nel tonno che nelle sardine. Proteggere i predatori significa proteggere tutto ciò che sta sotto."),
      ]),

    # ------------------------------ STORIA ------------------------------
    L("storia", "v4-lez-leggere-mappa-storica",
      "Leggere una mappa storica senza farsi ingannare", ["mappa storica"],
      "Confini, nomi e colori raccontano il punto di vista di chi disegnava. Quattro passi per capire cosa una mappa mostra e cosa nasconde.",
      "Interpretare una mappa storica considerando data, autore, proiezione e scelte grafiche.",
      "Chiediti chi ha fatto la mappa, quando, per chi e cosa ha scelto di non mostrare. Confini netti su carta erano spesso sfumati sul terreno.",
      [
       ("Passo 1 — Data e autore",
        "La stessa regione nel 1500 e nel 1800 ha nomi e confini diversi. Cerca la data di stesura, non solo il periodo rappresentato: una mappa dell'Impero Romano disegnata nel 1900 riflette le idee del 1900. E l'autore: un cartografo veneziano e uno ottomano coloravano il Mediterraneo in modo opposto."),
       ("Passo 2 — Il centro e l'orientamento",
        "Chi fa la mappa si mette al centro. Le mappe medievali europee avevano Gerusalemme al centro e l'est in alto; quelle cinesi la Cina; le nostre l'Europa. Il nord in alto è una convenzione degli ultimi 500 anni, non una legge di natura."),
       ("Passo 3 — I confini erano sfumati",
        "Una linea netta su carta suggerisce controllo totale. Ma nel 1700 un impero controllava città e strade, non ogni villaggio nel bosco. I colori pieni sulle mappe coloniali dell'Africa rappresentavano pretese, non presenza reale: molte zone 'francesi' non avevano mai visto un francese."),
       ("Passo 4 — Cosa manca",
        "Una mappa dei regni europei non mostra i popoli senza stato. Una mappa delle 'scoperte' non mostra chi già viveva lì. Chiediti sempre: cosa ha scelto di non disegnare? Il silenzio di una mappa dice quanto le sue linee."),
      ]),
    L("storia", "v4-lez-fonti-primarie",
      "Fonte primaria o secondaria? Come capire di chi ti stai fidando", ["fonti"],
      "Un diario, un libro di scuola, un documentario: non valgono uguale. Sapere distinguerli è la prima abilità dello storico e serve anche a leggere le notizie.",
      "Distinguere fonti primarie e secondarie e valutare i limiti di ciascuna.",
      "Primaria: prodotta al tempo dei fatti da chi li ha vissuti. Secondaria: scritta dopo, interpretando le primarie. Entrambe hanno punti ciechi; il metodo è confrontarle.",
      [
       ("Passo 1 — La primaria è testimone",
        "Lettere, diari, foto, decreti, oggetti, registrazioni: tutto ciò che è nato nel momento dei fatti o da chi c'era. Non è automaticamente vero: una lettera di propaganda è primaria e falsa. Ma ti mette a contatto diretto con quel tempo, senza filtri successivi."),
       ("Passo 2 — La secondaria interpreta",
        "Libri di storia, biografie, documentari, articoli di enciclopedia: qualcuno ha letto le fonti primarie e le ha messe in ordine per te. È utile perché sintetizza e dà contesto, ma aggiunge il punto di vista dell'autore e della sua epoca. Un manuale del 1930 e uno del 2020 raccontano la stessa guerra in modo diverso."),
       ("Passo 3 — Le domande da fare a ogni fonte",
        "Chi l'ha prodotta? Quando? Per chi? Perché? Un generale scrive le memorie per difendere la propria reputazione. Un giornale ha una linea editoriale. Un censimento serve a tassare. Nessuna fonte è neutra; conoscere lo scopo ti dice dove cercare le distorsioni."),
       ("Passo 4 — Il metodo del confronto",
        "Una fonte sola non basta mai. Cerca almeno due testimoni indipendenti, meglio se in disaccordo: dove concordano, probabilmente c'è un fatto; dove divergono, c'è un'interpretazione da capire. Funziona con la Rivoluzione francese e con la notizia di stamattina."),
      ]),
    L("storia", "v4-lez-perche-cadono-imperi",
      "Perché cadono gli imperi: 4 schemi che si ripetono", ["imperi"],
      "Roma, i Maya, gli Ottomani, l'URSS: storie diversissime con sorprendenti punti in comune. Un modello per leggere passato e presente.",
      "Riconoscere i fattori ricorrenti nel declino delle grandi civiltà: sovraestensione, crisi fiscale, legittimità, shock esterni.",
      "Gli imperi raramente cadono per una sola causa: si sovraestendono, non riescono più a finanziarsi, perdono la fiducia delle élite e dei sudditi, e uno shock esterno fa il resto.",
      [
       ("Passo 1 — Sovraestensione",
        "Ogni impero cresce finché il costo di difendere i confini supera i benefici delle conquiste. Roma nel III secolo aveva 10.000 km di frontiere da presidiare. La Spagna del Cinquecento combatteva su tre continenti. Espandersi porta ricchezza; mantenere l'espansione la consuma."),
       ("Passo 2 — Crisi fiscale",
        "Eserciti e burocrazie costano. Quando le entrate non bastano, gli imperi svalutano la moneta (Roma ridusse l'argento nel denario dal 90% al 5%), tassano fino a spingere i contadini a fuggire, o si indebitano. La Francia del 1789 spendeva metà del bilancio per interessi sul debito."),
       ("Passo 3 — Perdita di legittimità",
        "Un impero regge finché élite e sudditi credono che valga la pena sostenerlo. Guerre civili per la successione, corruzione visibile, promesse non mantenute erodono quel consenso. L'URSS non fu invasa: nel 1991 semplicemente quasi nessuno era più disposto a difenderla."),
       ("Passo 4 — Lo shock finale",
        "Peste, carestia, cambiamento climatico, un nemico nuovo: lo shock esterno di solito è l'ultimo colpo, non la causa. Sistemi sani lo assorbono; sistemi già fragili crollano. I Maya soffrirono decenni di siccità, ma le città che caddero erano quelle già divise dalle guerre. Guarda sempre le cause lente dietro l'evento veloce."),
      ]),

    # ------------------------------ PSICOLOGIA ------------------------------
    L("psicologia", "v4-lez-abitudini",
      "Costruire un'abitudine in 4 passi (e perché la forza di volontà non basta)", ["abitudine"],
      "Non è una questione di carattere: è un circuito del cervello che puoi progettare. Ecco il metodo che funziona secondo le ricerche.",
      "Applicare il ciclo segnale-azione-ricompensa per creare una nuova abitudine e farla durare.",
      "Un'abitudine è un ciclo: segnale, azione, ricompensa. Rendila piccola, aggancia il segnale a qualcosa che già fai, premiati subito e non saltare mai due volte di seguito.",
      [
       ("Passo 1 — Rendila ridicolmente piccola",
        "Il cervello resiste alle grandi novità. 'Corro 5 km' fallisce; 'mi metto le scarpe da corsa' riesce. La versione minima costruisce il circuito; la durata arriva dopo. Due minuti di qualsiasi cosa, ogni giorno, valgono più di un'ora una volta a settimana."),
       ("Passo 2 — Aggancia a un segnale esistente",
        "Le abitudini partono da un segnale: un orario, un luogo, un gesto precedente. Usa la formula 'Dopo che [cosa già faccio], farò [nuova azione]'. 'Dopo il caffè del mattino, leggo una pagina'. Il caffè diventa il grilletto e non devi ricordartene."),
       ("Passo 3 — Premiati subito",
        "Il cervello rinforza ciò che dà piacere immediato, non tra sei mesi. Dopo l'azione, fai qualcosa che ti piace: spunta una casella, ascolta la tua canzone, bevi il tè buono. Sembra infantile ma è così che si consolida un circuito: azione seguita da ricompensa, ripetuto."),
       ("Passo 4 — Mai due volte di fila",
        "Saltare un giorno non rovina nulla; saltarne due inizia una nuova abitudine: quella di saltare. La regola 'mai due volte di seguito' perdona l'imprevisto e blocca la deriva. Le abitudini richiedono in media 66 giorni per diventare automatiche: la costanza imperfetta batte la perfezione a intermittenza."),
      ]),
    L("psicologia", "v4-lez-ascolto-attivo",
      "Ascolto attivo: farsi capire ascoltando meglio", ["ascolto"],
      "La maggior parte delle discussioni non fallisce per quello che si dice, ma per quello che non si ascolta. Una tecnica in quattro passi usata da mediatori e terapeuti.",
      "Praticare l'ascolto attivo in una conversazione difficile per ridurre i conflitti e capire davvero l'altro.",
      "Ascolta senza preparare la risposta, riformula ciò che hai capito, chiedi invece di supporre, e riconosci l'emozione prima di discutere il contenuto.",
      [
       ("Passo 1 — Smetti di preparare la risposta",
        "Mentre l'altro parla, di solito stiamo già costruendo la replica. Prova a fare solo una cosa: capire. Guarda l'altro, non interrompere, tollera qualche secondo di silenzio dopo che ha finito. Chi si sente ascoltato abbassa il tono da solo."),
       ("Passo 2 — Riformula",
        "Ripeti con parole tue ciò che hai capito: 'Se ho capito bene, ti ha dato fastidio che non ti abbia avvisato'. Non è un trucco: serve a verificare e mostra che hai davvero ascoltato. Se hai capito male, l'altro corregge subito, prima che il malinteso cresca."),
       ("Passo 3 — Chiedi, non supporre",
        "Sostituisci 'lo fai sempre per...' con 'cosa ti ha spinto a...?'. Le domande aperte, che iniziano con cosa e come (evita 'perché', suona accusatorio), fanno emergere il motivo reale. Le supposizioni sul motivo altrui sono sbagliate più spesso di quanto crediamo."),
       ("Passo 4 — Prima l'emozione, poi il merito",
        "Se l'altro è arrabbiato, discutere i fatti è inutile: la parte razionale del cervello è offline. Riconosci prima l'emozione: 'Capisco che sei deluso'. Non significa dargli ragione; significa riaprire il canale. Solo dopo si può parlare di chi aveva torto."),
      ]),
    L("psicologia", "v4-lez-gestire-ansia",
      "Gestire un momento di ansia: 4 tecniche che funzionano in 5 minuti", ["ansia"],
      "Cuore che accelera, mente che corre. Il corpo è entrato in modalità pericolo per errore. Ecco come dirgli che può uscire.",
      "Usare tecniche basate sulla fisiologia per ridurre un picco di ansia in pochi minuti.",
      "Allunga l'espirazione per attivare il sistema calmante, ancora i sensi al presente, dai un nome all'emozione e ricorda che il picco passa in pochi minuti.",
      [
       ("Passo 1 — Espira più a lungo di quanto inspiri",
        "L'ansia accelera il respiro. L'espirazione lunga attiva il nervo vago, il freno del corpo. Prova il 4-7-8: inspira dal naso per 4 secondi, trattieni per 7, espira dalla bocca per 8. Oppure il 'doppio sospiro': due brevi inspirazioni dal naso e una lunga espirazione. Quattro cicli bastano per sentire la differenza."),
       ("Passo 2 — Torna nei sensi",
        "L'ansia vive nel futuro immaginato. Riportati al presente con il 5-4-3-2-1: nomina 5 cose che vedi, 4 che senti al tatto, 3 che odi, 2 che annusi, 1 che gusti. Costringe il cervello a elaborare il qui e ora invece dello scenario catastrofico."),
       ("Passo 3 — Dagli un nome",
        "Dire, anche solo mentalmente, 'sto provando ansia per la riunione' riduce l'attivazione dell'amigdala, la centralina della paura. Le neuroscienze lo chiamano 'affect labeling': mettere in parole un'emozione la rende un oggetto che osservi, non un'onda che ti travolge."),
       ("Passo 4 — Ricorda che è un'onda",
        "Il picco di adrenalina dura fisiologicamente pochi minuti, poi il corpo lo smaltisce. Non devi 'combatterlo': devi aspettare che passi facendo i passi 1-3. Se gli attacchi sono frequenti o ti limitano, parlarne con un professionista è la scelta più efficace: l'ansia si cura molto bene."),
      ]),

    # ------------------------------ CORPO UMANO ------------------------------
    L("corpo-umano", "v4-lez-leggere-battito",
      "Leggere il proprio battito: cosa dice il cuore a riposo", ["battito"],
      "Il polso è il dato di salute più facile da misurare e uno dei più informativi. Quattro passi per misurarlo bene e capire cosa significa.",
      "Misurare correttamente la frequenza cardiaca a riposo e interpretarne i valori.",
      "Misura al risveglio, per 60 secondi. Tra 60 e 100 è normale; più basso negli allenati. Un aumento costante di 5-10 battiti segnala stress, malattia in arrivo o poco recupero.",
      [
       ("Passo 1 — Quando e come misurare",
        "Il valore più utile è quello a riposo: appena sveglio, prima di alzarti e prima del caffè. Appoggia due dita (non il pollice, ha un suo battito) sul polso sotto la base del pollice o sul collo a lato della trachea. Conta per 60 secondi interi: i conteggi da 15 secondi moltiplicati amplificano gli errori."),
       ("Passo 2 — I valori normali",
        "Per un adulto, tra 60 e 100 battiti al minuto è normale. Gli sportivi di resistenza scendono a 40-50: il cuore è più efficiente e pompa più sangue per battito. Sopra i 100 a riposo (tachicardia) o sotto i 50 senza allenamento vale una visita. Nei bambini i valori sono più alti."),
       ("Passo 3 — La tendenza conta più del numero",
        "Il tuo valore personale è la base. Se una mattina è 8-10 battiti sopra il solito, il corpo sta lavorando su qualcosa: infezione in arrivo, sonno scarso, alcol la sera prima, allenamento non recuperato. Gli atleti usano questo segnale per decidere se allenarsi."),
       ("Passo 4 — Ritmo, non solo frequenza",
        "Senti anche la regolarità. Qualche battito 'saltato' occasionale è comune e benigno. Un ritmo caoticamente irregolare, invece, può indicare fibrillazione atriale, frequente dopo i 65 anni e spesso silenziosa. Se lo noti, un elettrocardiogramma di 10 minuti chiarisce tutto."),
      ]),
    L("corpo-umano", "v4-lez-sonno-cicli",
      "I cicli del sonno: perché a volte 6 ore bastano e 8 no", ["sonno", "cicli"],
      "Non conta solo quanto dormi, ma in che punto del ciclo ti svegli. Capire le fasi del sonno ti permette di svegliarti meglio con lo stesso tempo.",
      "Conoscere le fasi del sonno e usare i cicli di 90 minuti per pianificare orari di sonno migliori.",
      "Il sonno procede in cicli di circa 90 minuti (leggero, profondo, REM). Svegliarsi al termine di un ciclo è più facile che nel mezzo del sonno profondo. Punta a 5 cicli, 7,5 ore.",
      [
       ("Passo 1 — Le fasi",
        "Ogni notte attraversi più volte tre stati: sonno leggero (N1-N2), sonno profondo (N3) e sonno REM, quello dei sogni vividi. Il profondo ripara il corpo e consolida la memoria; il REM elabora emozioni e apprendimenti. La prima metà della notte è ricca di sonno profondo, la seconda di REM."),
       ("Passo 2 — Il ciclo da 90 minuti",
        "Le fasi si susseguono in cicli di 90-110 minuti. Al termine di ogni ciclo si torna vicini alla veglia: è il momento in cui svegliarsi è naturale. Svegliarsi nel mezzo del sonno profondo, invece, produce quella sensazione di stordimento che dura mezz'ora, l'inerzia del sonno."),
       ("Passo 3 — Fai i conti all'indietro",
        "Devi alzarti alle 7? Cinque cicli sono 7,5 ore: dormi alle 23:30 (più 10-15 minuti per addormentarti). Se vai a letto tardi, 6 ore (4 cicli) possono farti sentire meglio di 7 ore (4 cicli e mezzo). Non è una regola rigida: i cicli variano da persona a persona, ma la logica regge."),
       ("Passo 4 — Proteggi il profondo",
        "Il sonno profondo si concentra nelle prime ore e soffre di alcol, pasti pesanti tardi e camere calde. Il REM si concentra al mattino e soffre della sveglia anticipata: chi dorme 5 ore taglia soprattutto quello. Orari regolari, anche nel weekend, sono l'intervento singolo più efficace."),
      ]),
    L("corpo-umano", "v4-lez-primo-soccorso",
      "Le 4 mosse di primo soccorso che tutti dovrebbero sapere", ["primo soccorso"],
      "Nei primi minuti di un'emergenza non c'è ancora l'ambulanza: ci sei tu. Quattro azioni semplici che salvano vite, spiegate senza tecnicismi.",
      "Conoscere le azioni base davanti a una persona che non risponde, che soffoca o che sanguina molto.",
      "Chiama il 112 subito. Se non respira, comprimi il torace al centro, forte e veloce. Se soffoca, colpi tra le scapole e spinte addominali. Se sanguina, premi forte sulla ferita.",
      [
       ("Passo 1 — Sicurezza e chiamata",
        "Prima assicurati che la scena sia sicura per te. Poi scuoti la persona per le spalle e chiama a voce alta. Se non risponde, chiama il 112 (o fallo chiamare, indicando una persona precisa) e metti il telefono in vivavoce: l'operatore ti guiderà. Non perdere tempo a cercare il portafogli o i documenti."),
       ("Passo 2 — Non respira: comprimi",
        "Se non respira o respira solo con rantoli, inizia le compressioni: mani sovrapposte al centro del torace, braccia tese, comprimi di 5-6 cm a ritmo di 100-120 al minuto (il tempo di 'Stayin' Alive'). Non fermarti fino all'arrivo dei soccorsi o di un defibrillatore, che ti parla e ti guida. Le compressioni da sole, senza respirazione bocca a bocca, sono efficaci."),
       ("Passo 3 — Soffoca: colpi e spinte",
        "Se tossisce, incoraggialo a tossire. Se non riesce a respirare né parlare: 5 colpi decisi tra le scapole con il palmo, poi 5 spinte addominali (dietro la persona, pugno sopra l'ombelico, tira verso di te e in alto). Alterna finché il corpo estraneo esce. Se perde coscienza, inizia le compressioni."),
       ("Passo 4 — Sanguina molto: premi",
        "Per un'emorragia grave, premi direttamente sulla ferita con un panno o le mani, forte, senza mollare per 10 minuti. Se il sangue inzuppa il panno, aggiungine un altro sopra senza togliere il primo. Solleva l'arto se possibile. I lacci si usano solo per arti e solo se la pressione non basta. Un corso di 4 ore di primo soccorso trasforma queste parole in gesti automatici: vale la pena."),
      ]),
]
