"""PAUSE v5 — ampliamento catalogo (parte E): Arte & Design, Geografia & Viaggi.
5 curiosità + 5 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ ARTE ------------------------------
    mk("arte", "v5-blu-oltremare",
       "Il blu era più costoso dell'oro", ["blu", "oro"],
       "Nei quadri medievali e rinascimentali il manto della Madonna è quasi sempre blu. Non per simbolismo, o non solo: quel colore veniva da una sola montagna in Afghanistan e costava più del metallo prezioso.",
       "Il blu oltremare si otteneva macinando lapislazzuli estratti in Afghanistan e portati 'oltre il mare'. Un'oncia costava più di un'oncia d'oro. I contratti specificavano quanto blu usare e per quali figure. Nel 1826 un chimico francese lo sintetizzò, e il prezzo crollò di 100 volte.",
       "",
       [
        ("Una sola miniera al mondo",
         "Per millenni il lapislazzuli di qualità veniva da un'unica valle, Sar-e-Sang, nel nord-est dell'Afghanistan. Arrivava in Europa attraverso Venezia, da 'oltre il mare', da cui il nome. Estrarre il pigmento era un lavoro di settimane: macinare, impastare con cera e resine, lavare più volte per separare il blu puro dalle impurità grigie."),
        ("Scritto nel contratto",
         "I committenti pagavano il pigmento a parte, e i contratti lo specificavano: tanto oltremare, di quella qualità, per il manto della Vergine. Il blu andava alla figura più importante non per tradizione ma perché era il colore più caro. Una veste blu dipinta era un'ostentazione di ricchezza, come l'oro della cornice. Molti pittori usavano l'azzurrite, più economica, per cieli e sfondi, e tenevano l'oltremare per pochi centimetri quadrati."),
        ("Vermeer e il debito",
         "Johannes Vermeer usava oltremare con una prodigalità unica: nella Ragazza con l'orecchino di perla il turbante, ma anche sotto altri colori, mescolato nelle ombre per renderle luminose. Quando morì nel 1675 lasciò la moglie con undici figli e debiti enormi: il blu è tra i sospettati."),
        ("Il crollo del 1826",
         "Nel 1824 la Francia offrì un premio a chi avesse sintetizzato l'oltremare. Due anni dopo il chimico Jean-Baptiste Guimet ci riuscì partendo da argilla, soda e zolfo: chimicamente identico, a un centesimo del prezzo. Il blu diventò un colore come gli altri. Oggi il vero oltremare di lapislazzuli si produce ancora, per restauratori e pochi artisti, e costa circa 15.000 euro al chilo."),
       ]),
    mk("arte", "v5-ritratti-sorriso",
       "Perché nei ritratti antichi nessuno sorride?", ["ritratti", "sorride"],
       "Secoli di volti seri, labbra serrate, sguardi fissi. Non era per i denti guasti né perché fosse impossibile tenere la posa. Sorridere, in un ritratto, era considerato volgare.",
       "Il sorriso a bocca aperta nei ritratti era associato a ubriachi, buffoni e personaggi di basso rango. Un ritratto costava una fortuna e doveva fissare la dignità di una persona per i posteri. Tutto cambia con la fotografia istantanea e la pubblicità del Novecento.",
       "",
       [
        ("Il sorriso dei buffoni",
         "Nell'arte europea fino al Settecento, la bocca aperta e i denti in vista comparivano quasi solo in scene di genere: taverne, contadini, giullari, bambini, peccatori. Un nobile non rideva in pubblico e tanto meno in un'immagine destinata a durare. Nel 1703 un trattato francese di buone maniere consigliava di non mostrare i denti nemmeno ridendo."),
        ("Un'immagine per sempre",
         "Un ritratto richiedeva ore di posa in più sedute, ma soprattutto era l'unica immagine che di te sarebbe rimasta. Doveva comunicare status, virtù, autorità: il sorriso è un'espressione fugace, e fissarla sembrava congelare una smorfia. Anche quando i denti erano sani, non li si mostrava."),
        ("Le eccezioni scandalose",
         "Nel 1787 Élisabeth Vigée Le Brun espose un autoritratto con la figlia in cui sorride mostrando i denti: la critica parlò di 'affettazione che artisti, amanti del gusto e persone di buon senso condannano all'unanimità'. Il sorriso appena accennato della Gioconda, senza denti, era il massimo consentito, e proprio per la sua ambiguità è diventato celebre."),
        ("Cheese",
         "Le prime fotografie richiedevano decine di secondi di posa e la gente teneva le espressioni dei ritratti. Il sorriso arriva negli anni Venti e Trenta del Novecento con due spinte: le macchine istantanee Kodak, vendute come strumenti per catturare momenti felici, e la pubblicità che associava il sorriso a salute e successo. Nel giro di una generazione, non sorridere in foto divenne strano."),
       ]),
    mk("arte", "v5-helvetica",
       "Perché lo stesso carattere tipografico è su metà delle insegne del mondo?", ["carattere", "insegne"],
       "Metropolitana di New York, American Airlines, BMW, i moduli delle tasse americane, migliaia di loghi. Un solo alfabeto disegnato in Svizzera nel 1957 è diventato invisibile a forza di essere ovunque.",
       "L'Helvetica fu disegnato nel 1957 da Max Miedinger per la fonderia Haas di Basilea, come carattere neutro e leggibile. Il nome, che significa 'svizzero', e la diffusione tramite le macchine di fotocomposizione lo resero il volto della modernità aziendale.",
       "",
       [
        ("Nato per essere neutro",
         "Nel dopoguerra i grafici svizzeri cercavano un design pulito, razionale, senza ornamenti. Il direttore della fonderia Haas commissionò a Max Miedinger un carattere senza grazie che migliorasse un modello tedesco del 1896. Il risultato, chiamato prima Neue Haas Grotesk, aveva forme chiuse, spaziatura stretta e nessuna personalità apparente: proprio ciò che volevano."),
        ("Un nome da esportazione",
         "Nel 1960 la casa madre tedesca Stempel volle venderlo a livello internazionale e cambiò il nome in Helvetica, dal latino per Svizzera, sfruttando la reputazione di precisione del paese. Il carattere arrivò sulle macchine da scrivere e di fotocomposizione, e negli anni Settanta era lo standard nelle agenzie di tutto il mondo."),
        ("Il volto delle aziende",
         "Negli anni Sessanta e Settanta le grandi società rifacevano la propria immagine e volevano sembrare moderne, affidabili, universali. Helvetica diceva esattamente quello. Lo adottarono American Airlines, Lufthansa, BMW, Panasonic, Jeep, la metropolitana di New York nel 1989, il governo americano per i moduli. Nel 2007 un intero documentario gli fu dedicato."),
        ("Amato e odiato",
         "Per molti designer Helvetica è la perfezione della neutralità; per altri, la noia istituzionale che ha reso tutte le città uguali. Apple lo usò come carattere di sistema fino al 2015, poi lo sostituì con un carattere proprio. Se non lo riconosci, è normale: è disegnato per non farsi notare. Ma ora che sai che esiste, lo vedrai dappertutto."),
       ]),
    mk("arte", "v5-david-proporzioni",
       "Il David di Michelangelo ha la testa e le mani troppo grandi, di proposito", ["David", "troppo grandi"],
       "Guardato da vicino, il David ha una testa sproporzionata e mani enormi. Non è un errore del genio: la statua non era pensata per essere vista da vicino, né da terra.",
       "Il David doveva stare su un contrafforte del Duomo di Firenze, a decine di metri di altezza. Michelangelo ingrandì testa e mani perché viste dal basso e da lontano apparissero corrette. Poi la statua fu messa in piazza, ad altezza d'uomo, e le proporzioni si notarono.",
       "",
       [
        ("Un blocco maledetto",
         "Il blocco di marmo era stato cavato nel 1464 per una serie di profeti da mettere sui contrafforti del Duomo, a circa 80 metri di altezza. Due scultori ci avevano rinunciato: era alto, stretto e pieno di venature. Rimase abbandonato per 35 anni nel cortile dell'Opera del Duomo. Nel 1501 il ventiseienne Michelangelo lo prese."),
        ("Scolpire per il cielo",
         "Una statua vista da sotto, a grande distanza, subisce una deformazione prospettica: la testa sembra piccola, le gambe lunghe, i dettagli del volto svaniscono. Gli scultori antichi lo sapevano e correggevano. Michelangelo allargò la testa, le mani e il torace, e assottigliò le gambe, così che dalla piazza la figura apparisse armoniosa."),
        ("Il cambio di programma",
         "Finita nel 1504, la statua era troppo bella e troppo pesante, sei tonnellate, per essere issata lassù. Una commissione di artisti, tra cui Leonardo e Botticelli, discusse dove metterla. Vinse Piazza della Signoria, davanti al Palazzo, come simbolo della Repubblica fiorentina che sfidava i potenti. Ad altezza di sguardo, le correzioni divennero visibili."),
        ("L'occhio strabico",
         "Nel 2000 scansioni digitali hanno rivelato che il David guarda in due direzioni: l'occhio sinistro fissa avanti, il destro è girato più a destra. Dal profilo di ciascun lato il volto appare perfetto; da davanti, leggermente strabico. Michelangelo probabilmente lo scolpì così perché la statua fosse vista dai due lati, mai frontalmente. La mano destra sproporzionata, infine, potrebbe alludere al soprannome di David, 'manu fortis', forte di mano."),
       ]),
    mk("arte", "v5-van-gogh-vendette",
       "Van Gogh vendette un solo quadro in vita (forse)", ["Van Gogh", "un solo quadro"],
       "Oggi i suoi girasoli valgono centinaia di milioni. Nel 1890 morì convinto di essere un fallimento. La leggenda del genio incompreso è vera, ma la storia dei quadri venduti è più complicata.",
       "In dieci anni Van Gogh dipinse circa 900 quadri e ne vendette con certezza uno, La vigna rossa, per 400 franchi nel 1890. Il fratello Theo lo mantenne per tutta la vita. La fama arrivò grazie alla cognata Johanna, che dopo la morte di entrambi promosse l'opera per trent'anni.",
       "",
       [
        ("Dieci anni, 900 quadri",
         "Van Gogh cominciò a dipingere a 27 anni, dopo aver fallito come commerciante d'arte, insegnante e predicatore. In dieci anni produsse circa 900 dipinti e 1.100 disegni, un'opera ogni 36 ore negli ultimi due anni. Nei 70 giorni ad Auvers, prima di morire, dipinse 70 tele."),
        ("La vigna rossa",
         "Nel febbraio 1890 la pittrice belga Anna Boch comprò La vigna rossa a una mostra di Bruxelles per 400 franchi, circa 2.000 euro di oggi. È l'unica vendita documentata a un'estranea. Alcune fonti ne suggeriscono altre minori, un autoritratto scambiato con un mercante, qualche tela ceduta per pagare debiti, ma nessuna ha prove solide."),
        ("Il fratello che pagava tutto",
         "Theo van Gogh, mercante d'arte a Parigi, mandò a Vincent circa 150 franchi al mese per dieci anni, un salario da operaio, ricevendo in cambio i quadri e 650 lettere. Vincent morì nel luglio 1890; Theo, distrutto, sei mesi dopo. Le tele, centinaia, finirono in casa della vedova di Theo, Johanna Bonger, 28 anni, con un neonato."),
        ("La donna che lo rese famoso",
         "Johanna avrebbe potuto vendere tutto in blocco. Invece studiò le lettere, organizzò mostre, prestò opere ai musei, vendette con parsimonia per far salire il valore e nel 1914 pubblicò la corrispondenza tra i fratelli. Quando morì, nel 1925, Van Gogh era già un mito. Il museo di Amsterdam nasce dalla collezione che lei rifiutò di disperdere."),
       ]),

    # ------------------------------ GEOGRAFIA ------------------------------
    mk("geografia", "v5-point-nemo",
       "Il punto della Terra più lontano da qualsiasi terra", ["più lontano"],
       "Nel Pacifico c'è un punto dove le persone più vicine non sono su un'isola: sono in orbita, sulla Stazione Spaziale. E sul fondo giacciono centinaia di navicelle.",
       "Point Nemo, a 48°52' Sud e 123°23' Ovest, è a 2.688 chilometri dalla terra più vicina in ogni direzione. È così isolato che le agenzie spaziali lo usano come cimitero per satelliti e stazioni in rientro. La Stazione Spaziale, a 400 km, passa più vicina di qualsiasi isola.",
       "",
       [
        ("Calcolato nel 1992",
         "Il punto fu individuato da un ingegnere croato, Hrvoje Lukatela, con un programma che cercava sulla sfera terrestre la posizione equidistante da tre terre emerse. Le tre: l'isola Ducie a nord, Motu Nui vicino all'Isola di Pasqua a nord-est, l'isola Maher in Antartide a sud. Tutte a 2.688 chilometri. Il nome viene dal capitano Nemo di Verne, nessuno in latino."),
        ("Un deserto d'acqua",
         "La zona sta al centro del Vortice del Pacifico Meridionale, una corrente circolare che tiene lontane le acque ricche di nutrienti delle coste. Il risultato è uno dei tratti di oceano meno vivi del pianeta: acqua limpidissima e quasi vuota. Nessuna rotta commerciale ci passa. Una nave ci arriva al massimo poche volte l'anno, per le regate intorno al mondo."),
        ("Il cimitero degli astronauti",
         "Dal 1971 le agenzie spaziali dirigono qui i rientri controllati: oltre 260 oggetti, tra cui la stazione sovietica Mir da 120 tonnellate, sei stazioni Saljut e più di 140 navi cargo russe. Cadere nell'oceano più deserto del mondo minimizza i rischi. Nel 2031 è previsto qui il rientro della Stazione Spaziale Internazionale."),
        ("La leggenda di Cthulhu",
         "Nel 1928 lo scrittore H.P. Lovecraft collocò la città sommersa del suo mostro Cthulhu a 47°9' Sud e 126°43' Ovest: a poche centinaia di chilometri da Point Nemo, 64 anni prima che venisse calcolato. Nel 1997 idrofoni registrarono nella zona un suono potentissimo e misterioso, il Bloop, poi attribuito alla frattura di un iceberg. Le coincidenze, qui, sono l'unica compagnia."),
       ]),
    mk("geografia", "v5-samoa-giorno",
       "Il paese che ha cancellato un venerdì per cambiare fuso orario", ["cancellato", "venerdì"],
       "Le Samoa sono andate a dormire giovedì 29 dicembre 2011 e si sono svegliate sabato 31. Il 30 dicembre non è mai esistito. Il motivo: fare affari con chi aveva un giorno di vantaggio.",
       "Le Samoa erano appena a est della linea del cambio di data, quindi un giorno indietro rispetto ad Australia e Nuova Zelanda, i loro partner commerciali. Nel 2011 saltarono la linea, perdendo il 30 dicembre e guadagnando 24 ore in comune con i vicini. Nel 1892 avevano fatto il salto opposto.",
       "",
       [
        ("Una linea che si può spostare",
         "La linea del cambio di data corre nel Pacifico approssimativamente lungo il meridiano opposto a Greenwich, ma zigzaga per non tagliare i paesi. Attraversandola verso ovest si salta un giorno avanti. Non è fissata da nessun trattato: ogni Stato decide da quale lato stare, e la linea si adegua."),
        ("Il salto del 1892",
         "Nel 1892 le Samoa, che commerciavano soprattutto con gli Stati Uniti, decisero di passare al lato americano: vissero due volte il 4 luglio, festeggiando il giorno dell'indipendenza americana con due giorni di feste. Per 119 anni furono l'ultimo posto al mondo dove finiva la giornata."),
        ("Il salto del 2011",
         "Nel frattempo l'economia si era spostata: Australia e Nuova Zelanda, a poche ore di volo, erano i primi partner. Ma quando a Apia era venerdì, a Sydney era già sabato: le settimane lavorative in comune erano quattro giorni. Il primo ministro annunciò il salto. Alle 23:59 di giovedì 29 dicembre 2011 gli orologi passarono alle 00:00 di sabato 31. Dipendenti pagati per il giorno mancato, compleanni del 30 spostati."),
        ("I vicini rimasti indietro",
         "Le Samoa Americane, a 70 chilometri, sono rimaste dall'altro lato: oggi tra le due isole c'è un giorno intero di differenza, e chi vuole festeggiare due volte il Capodanno può prendere un volo di 30 minuti. Kiribati nel 1995 spostò la linea di 3.000 chilometri per unire il proprio paese in un solo giorno, diventando il primo posto a entrare nel nuovo millennio."),
       ]),
    mk("geografia", "v5-citta-piu-fredda",
       "La città dove a -50 gradi la scuola resta aperta", ["-50 gradi"],
       "A Jakutsk, in Siberia, 350.000 persone vivono in un posto dove l'inverno medio è -40 e le auto restano accese per mesi. È la grande città più fredda del mondo, e ha regole tutte sue.",
       "Jakutsk, capitale della Repubblica di Sacha in Russia, ha temperature medie di gennaio intorno a -40 gradi e un record di -64. La città è costruita su palafitte sul permafrost, le scuole chiudono solo sotto i -50 e il mercato del pesce vende all'aperto pesce congelato come legna.",
       "",
       [
        ("Perché così fredda",
         "Jakutsk sta a 62 gradi di latitudine, non più a nord di Trondheim in Norvegia. Ma è nel cuore del continente, a migliaia di chilometri da qualsiasi oceano che possa mitigare il clima, in una conca dove l'aria gelida ristagna. Di notte in inverno la temperatura scende regolarmente sotto i -45. In estate può superare i 30: l'escursione annuale sfiora i 100 gradi."),
        ("Costruire sul ghiaccio",
         "Il terreno è permafrost, congelato fino a centinaia di metri di profondità. Un edificio riscaldato appoggiato direttamente scioglierebbe il suolo e affonderebbe. Per questo tutte le case stanno su pali di cemento piantati nel ghiaccio, con un metro d'aria sotto. Le tubature corrono in superficie, isolate, perché scavare è impossibile. Il riscaldamento centralizzato cittadino non si spegne mai."),
        ("La vita quotidiana",
         "Le auto restano accese tutta la notte o dormono in garage riscaldati: a -40 la benzina si addensa e la gomma dei pneumatici si crepa. Gli occhiali si appannano e gelano in pochi secondi, quindi si evitano. Il mercato all'aperto vende pesce e carne congelati in piedi, come tronchi. La scuola chiude solo sotto i -50 per i bambini piccoli e sotto i -55 per i grandi."),
        ("Il posto ancora più freddo",
         "A 900 chilometri a est, il villaggio di Ojmjakon, 500 abitanti, detiene il record di temperatura per un luogo abitato: -67,7 gradi nel 1933. Il nome significa 'acqua che non gela', per una sorgente termale vicina. La regione di Sacha è grande come l'India con un milione di abitanti: il freddo, più di ogni confine, decide dove vivono gli esseri umani."),
       ]),
    mk("geografia", "v5-sahara-verde",
       "Il Sahara era verde, con laghi e ippopotami", ["Sahara", "verde"],
       "Sotto le dune ci sono letti di fiumi, fossili di pesci e pitture rupestri con mandrie e nuotatori. Fino a 5.000 anni fa il più grande deserto caldo del mondo era una savana. E tornerà a esserlo.",
       "Tra 11.000 e 5.000 anni fa il Sahara riceveva monsoni abbondanti grazie a una diversa inclinazione dell'asse terrestre: laghi grandi come mari, fiumi, elefanti e pescatori. Il ciclo si ripete ogni 20.000 anni circa, e l'inverdimento è già avvenuto decine di volte.",
       "",
       [
        ("Le prove sotto la sabbia",
         "Radar satellitari mostrano sotto le dune reti di antichi fiumi lunghi centinaia di chilometri. Nel Ciad il Mega-Lago Ciad copriva 400.000 chilometri quadrati, più del Mar Caspio. Nel deserto egiziano si trovano ossa di pesci, ippopotami, coccodrilli e resti di villaggi di pescatori con ami e arpioni."),
        ("La grotta dei nuotatori",
         "Sull'altopiano del Gilf Kebir, nel Sahara egiziano, una grotta scoperta nel 1933 conserva pitture di figure umane che sembrano nuotare, insieme a giraffe, bovini e antilopi. Hanno circa 8.000 anni. Oggi la pioggia più vicina cade a centinaia di chilometri. Chi le dipinse viveva in un mondo di acqua e pascoli."),
        ("Il pendolo dell'asse terrestre",
         "L'asse della Terra oscilla lentamente e cambia l'intensità delle stagioni con un ciclo di circa 20.000 anni. Quando l'estate dell'emisfero nord cade nel punto dell'orbita più vicino al Sole, il Nord Africa si scalda di più, richiama il monsone dall'Atlantico e le piogge arrivano fin nel cuore del deserto. Il Sahara verde è la regola ciclica; quello secco di oggi è una fase."),
        ("La fine e il prossimo inizio",
         "Circa 5.500 anni fa le piogge si ritirarono nel giro di pochi secoli. Le popolazioni migrarono verso il Nilo, e la concentrazione di persone lungo il fiume è tra le cause della nascita dell'Egitto dei faraoni. Il prossimo inverdimento è previsto tra circa 10.000 anni. La sabbia del Sahara, intanto, attraversa l'Atlantico e fertilizza l'Amazzonia: 27 milioni di tonnellate l'anno."),
       ]),
    mk("geografia", "v5-mediterraneo-secco",
       "Il Mediterraneo si è seccato completamente, e poi si è riempito in due anni", ["Mediterraneo", "seccato"],
       "Sei milioni di anni fa lo Stretto di Gibilterra si chiuse. Il mare evaporò lasciando un deserto di sale profondo tre chilometri. Poi l'Atlantico trovò una breccia, e arrivò la più grande inondazione della storia della Terra.",
       "Circa 5,96 milioni di anni fa i movimenti tettonici chiusero il collegamento con l'Atlantico. In poche migliaia di anni il Mediterraneo evaporò quasi del tutto. 5,33 milioni di anni fa l'oceano ruppe lo sbarramento e riempì il bacino in meno di due anni con una cascata alta chilometri.",
       "",
       [
        ("Un mare che perde",
         "Il Mediterraneo evapora più acqua di quanta ne ricevano fiumi e pioggia: senza l'Atlantico che entra da Gibilterra, si abbasserebbe di circa un metro l'anno. Quando la placca africana spinse la Spagna e il Marocco a chiudere lo stretto, il conto alla rovescia partì. In poche migliaia di anni restarono alcuni laghi salati sul fondo, fino a 3-5 chilometri sotto il livello attuale."),
        ("Il deserto di sale",
         "Sotto i fondali di tutto il Mediterraneo si trova uno strato di sale e gesso spesso fino a tre chilometri, un milione di chilometri cubi: la crisi di salinità del Messiniano. Fu individuato negli anni Settanta dalle perforazioni. I fiumi scavarono canyon profondi: sotto il delta del Nilo c'è una gola più profonda del Grand Canyon, sepolta dai sedimenti."),
        ("L'inondazione Zancleana",
         "Poi l'Atlantico trovò una via. L'ipotesi più accreditata, dal 2009: l'acqua cominciò a filtrare, scavò un canale, e il canale si allargò in modo esplosivo. Al picco, entravano nel bacino 100 milioni di metri cubi al secondo, mille volte l'Amazzonia, e il livello saliva di dieci metri al giorno. Il Mediterraneo si riempì in un periodo tra pochi mesi e due anni. Sul fondo dello Stretto c'è ancora il canale scavato, largo chilometri."),
        ("Le tracce di oggi",
         "Il sale del Messiniano è sotto i piedi di tutto il Mediterraneo e viene estratto in Sicilia. L'inondazione spiega perché la fauna marina del Mediterraneo è quasi tutta atlantica. E il bilancio negativo continua: se Gibilterra si chiudesse di nuovo, cosa che la tettonica renderà probabile tra qualche milione di anni, il ciclo ricomincerebbe."),
       ]),
]

LESSONS = [
    # ------------------------------ ARTE ------------------------------
    L("arte", "v5-lez-guardare-quadro",
      "Come guardare un quadro: 4 passi per non passare oltre in 8 secondi", ["guardare", "quadro"],
      "Il visitatore medio di un museo guarda un'opera per otto secondi, poi legge la targhetta per quindici. Invertire l'ordine e aggiungere tre domande cambia tutto.",
      "Osservare un dipinto con metodo, ricavarne informazioni e piacere senza bisogno di conoscere la storia dell'arte.",
      "Prima guarda senza leggere: cosa vedi, letteralmente. Poi chiediti dove va l'occhio e perché. Poi cerca cosa fa la luce e il colore. Solo alla fine leggi la targhetta e confronta.",
      [
       ("Passo 1 — Inventario, senza giudicare",
        "Prima di leggere qualunque cosa, un minuto intero davanti all'opera. Elenca ciò che vedi, in modo letterale: quante figure, cosa fanno, cosa c'è sullo sfondo, che oggetti compaiono. Non 'una scena triste' ma 'una donna seduta, la testa appoggiata alla mano, una lettera in grembo'. È il passo che quasi tutti saltano, ed è dove il quadro racconta di più."),
       ("Passo 2 — Dove va l'occhio",
        "Nota dove hai guardato per primo e dove sei andato dopo. Il pittore lo ha deciso: con il contrasto di luce, con la posizione, con le linee, un braccio, una strada, uno sguardo, che conducono da un punto all'altro. Chiediti cosa è al centro e cosa è ai margini, e chi guarda chi dentro il quadro. La composizione è il racconto prima delle parole."),
       ("Passo 3 — Luce, colore, materia",
        "Da dove viene la luce? È naturale, di candela, impossibile? Cosa illumina e cosa lascia nell'ombra? I colori sono pochi o tanti, caldi o freddi, e dove il pittore ha messo il colore più acceso? Avvicinati: le pennellate sono invisibili o spesse e veloci? La materia dice quanto il pittore voleva farsi vedere al lavoro."),
       ("Passo 4 — Adesso la targhetta",
        "Leggi titolo, autore, data. Confronta con ciò che hai visto: la donna con la lettera è del 1660, in Olanda, dove le lettere d'amore erano un tema. Cosa cambia sapere la data? Cosa ti aspettavi che fosse diverso? Poi torna al quadro un'ultima volta. Quattro passi, cinque minuti: hai visto più di chi ha attraversato tre sale."),
      ]),
    L("arte", "v5-lez-regola-terzi",
      "La regola dei terzi: comporre una foto o un'immagine in 4 mosse", ["regola dei terzi"],
      "La stessa scena, due foto: una piatta, una che funziona. Spesso la differenza è dove hai messo il soggetto. Una griglia di quattro linee ti fa decidere meglio.",
      "Applicare la regola dei terzi e altri tre principi di composizione per migliorare subito foto e immagini.",
      "Dividi l'inquadratura in nove rettangoli con due linee orizzontali e due verticali. Metti il soggetto su una linea o su un incrocio, non al centro. Allinea l'orizzonte a una linea. Lascia spazio davanti a chi guarda o si muove. Poi rompi la regola quando serve simmetria.",
      [
       ("Passo 1 — La griglia",
        "Attiva la griglia nella fotocamera del telefono: compaiono due linee verticali e due orizzontali che dividono lo schermo in nove parti. I quattro incroci sono i punti dove l'occhio si posa più volentieri. Il centro esatto è il punto più statico dell'immagine: mettere il soggetto lì produce foto da documento."),
       ("Passo 2 — Soggetto e orizzonte",
        "Sposta il volto, l'albero, la barca su un incrocio o lungo una linea verticale. L'orizzonte va su una delle due linee orizzontali: in basso se il cielo è interessante, in alto se lo è il terreno. Mai a metà, che divide la foto in due immagini che si contendono l'attenzione. Il mare a un terzo dal basso e il cielo sopra: la formula di quasi tutti i paesaggi riusciti."),
       ("Passo 3 — Lo spazio davanti",
        "Se una persona guarda a sinistra, lasciale spazio a sinistra, non dietro la testa. Se un'auto si muove verso destra, dalle strada davanti. L'occhio di chi guarda segue lo sguardo e il movimento del soggetto: se trova subito il bordo, la foto sembra tagliata. Vale anche per i ritratti: gli occhi sulla linea superiore, mai al centro."),
       ("Passo 4 — Quando romperla",
        "La regola dei terzi crea tensione e movimento. Ma se vuoi calma, solennità, ordine, il centro e la simmetria funzionano: una facciata, un riflesso in un lago, un volto frontale. I registi come Wes Anderson costruiscono uno stile sulla simmetria perfetta. La regola non è una legge: è la scelta di default da cui deviare consapevolmente, non per caso."),
      ]),
    L("arte", "v5-lez-scegliere-font",
      "Scegliere un carattere: 4 regole per non sbagliare font", ["carattere", "font"],
      "Un invito in Comic Sans, un curriculum in Papyrus, un cartello con cinque caratteri diversi. Il testo era corretto, il messaggio è andato perso. La tipografia parla prima delle parole.",
      "Capire la differenza tra le famiglie di caratteri, abbinarle e usarle con misura in documenti, presentazioni e inviti.",
      "Con grazie (serif) per testi lunghi su carta e tono classico; senza grazie (sans) per schermi e tono moderno. Massimo due caratteri per documento, uno per i titoli e uno per il testo. Dimensioni con contrasto netto, righe non oltre 70 caratteri.",
      [
       ("Passo 1 — Grazie o senza",
        "Le grazie sono i piccoli tratti alle estremità delle lettere: Times, Garamond, Georgia. Guidano l'occhio lungo la riga e sono ideali per pagine di testo stampato; comunicano tradizione, autorevolezza, letteratura. I caratteri senza grazie, Helvetica, Arial, Roboto, sono puliti e reggono meglio sugli schermi; dicono modernità, chiarezza, tecnologia. Un romanzo in Arial e un'app in Garamond stonano entrambi."),
       ("Passo 2 — Massimo due",
        "Un documento ha bisogno di un carattere per il testo e al massimo uno per i titoli. Abbina un serif e un sans con proporzioni simili, per esempio Georgia per il testo e Helvetica per i titoli, oppure usa un solo carattere variando peso e dimensione: grassetto grande per i titoli, normale per il testo. Tre caratteri o più sembrano sempre un volantino di quartiere."),
       ("Passo 3 — Dimensioni e spazio",
        "Il testo corrente su carta va tra 10 e 12 punti, su schermo tra 16 e 18 pixel. I titoli devono avere un contrasto netto, almeno il doppio, non appena più grandi. L'interlinea intorno al 140-150% della dimensione del carattere. Righe di 50-70 caratteri: più lunghe stancano, più corte spezzettano. Lo spazio bianco non è spreco: è ciò che rende leggibile il resto."),
       ("Passo 4 — I caratteri da evitare e perché",
        "Comic Sans fu disegnato per i fumetti di un programma per bambini: fuori da lì sembra infantile. Papyrus e i caratteri 'a tema' impongono un'atmosfera che raramente coincide con la tua. I caratteri decorativi vanno bene solo per una parola in un titolo. Nel dubbio: Georgia o Garamond per il testo, Helvetica o un sans di sistema per i titoli, e nessuno se ne accorgerà. È il complimento migliore che la tipografia possa ricevere."),
      ]),
    L("arte", "v5-lez-storia-arte-tappe",
      "Cinquecento anni di pittura in 4 tappe", ["pittura", "tappe"],
      "Dal Rinascimento all'astrattismo, la pittura occidentale ha cambiato completamente ciò che voleva fare. Con quattro punti di riferimento puoi collocare quasi ogni quadro che incontri.",
      "Costruire una mappa mentale della storia della pittura occidentale dal Quattrocento al Novecento, per riconoscere epoca e intenzione di un'opera.",
      "Rinascimento (1400-1600): rappresentare il mondo con la prospettiva. Barocco (1600-1750): emozionare con luce e movimento. Impressionismo (1870-1900): dipingere la percezione, non l'oggetto. Avanguardie (1900-1950): scomporre la forma e abbandonare la figura.",
      [
       ("Passo 1 — Rinascimento: la finestra sul mondo",
        "A Firenze intorno al 1420 Brunelleschi codifica la prospettiva e Masaccio la usa: il quadro diventa una finestra su uno spazio credibile. Si studia l'anatomia, si riscopre l'antico, si dipingono corpi e architetture misurabili. Leonardo, Michelangelo, Raffaello portano il metodo alla perfezione. Riconoscilo: spazi ordinati, luce chiara, figure calme e idealizzate."),
       ("Passo 2 — Barocco: il teatro",
        "Dopo il 1600 la Chiesa della Controriforma vuole commuovere e convincere. Caravaggio inventa la luce che taglia il buio e i santi con la faccia della gente di strada; Rubens il movimento, le carni, la diagonale; Bernini la scultura che sembra fermarsi a metà gesto. Riconoscilo: contrasti forti, emozione, corpi in torsione, l'attimo colto al culmine."),
       ("Passo 3 — Impressionismo: l'occhio",
        "Nel 1874 a Parigi un gruppo di rifiutati dal Salon ufficiale espone da solo. Monet, Renoir, Degas dipingono all'aperto, veloci, ciò che l'occhio vede prima che il cervello lo nomini: la luce su un fiume a un'ora precisa, non 'un fiume'. La fotografia, appena nata, ha liberato la pittura dal dovere di documentare. Riconoscilo: pennellate visibili, colori puri accostati, soggetti quotidiani, nessun contorno netto."),
       ("Passo 4 — Avanguardie: la forma si rompe",
        "Cézanne mostra che un oggetto si può dipingere da più punti di vista insieme; Picasso e Braque nel 1907 lo scompongono in piani: il cubismo. Kandinskij nel 1910 elimina l'oggetto: solo colore e forma, come la musica. Da qui si diramano espressionismo, surrealismo, astrazione. Riconoscilo: la domanda non è più 'cosa rappresenta' ma 'cosa fa'. Quando ti sembra 'roba che potrei fare anch'io', sei arrivato qui: e la domanda giusta è perché nessuno l'aveva fatto prima."),
      ]),
    L("arte", "v5-lez-leggere-edificio",
      "Leggere un edificio: riconoscere 4 stili architettonici in strada", ["edificio", "stili"],
      "Passeggiando in una città europea attraversi otto secoli di architettura senza accorgertene. Quattro indizi, finestre, colonne, decorazioni, materiali, ti dicono quando è stato costruito ciò che hai davanti.",
      "Riconoscere gotico, rinascimentale, barocco e moderno dagli elementi visibili di una facciata.",
      "Gotico: archi a punta, guglie, vetrate, verticalità. Rinascimento: simmetria, archi a tutto sesto, colonne classiche, proporzioni misurate. Barocco: curve, decorazioni abbondanti, facciate mosse. Moderno: linee rette, niente ornamenti, vetro, cemento e acciaio.",
      [
       ("Passo 1 — Gotico (1150-1500): verso l'alto",
        "Guarda gli archi: se sono a punta, sei nel gotico. Le finestre sono alte e strette, spesso con vetrate colorate e trafori di pietra a forma di fiore o fiamma. Contrafforti esterni e archi rampanti scaricano il peso e permettono muri sottili. Guglie, pinnacoli, doccioni con mostri. Il Duomo di Milano e Notre-Dame: tutto tende verso l'alto."),
       ("Passo 2 — Rinascimento (1400-1600): la misura",
        "Archi a tutto sesto, semicircolari. Facciate simmetriche divise in piani regolari da cornici orizzontali. Colonne e lesene con i capitelli antichi: dorico, ionico, corinzio. Finestre rettangolari con timpani triangolari. Bugnato al piano terra, pietre sporgenti e squadrate. Palazzo Strozzi a Firenze o Palazzo Farnese a Roma: ordine e proporzione, nessun eccesso."),
       ("Passo 3 — Barocco (1600-1750): il movimento",
        "La facciata si curva, avanza e rientra. Colonne accoppiate, timpani spezzati o curvi, statue, volute, stucchi, cornici sovrapposte. Le finestre hanno cornici elaborate, le chiese cupole ovali. Tutto è pensato per sorprendere e per la luce che scivola sulle superfici mosse. Il Borromini a Roma, le chiese di Lecce, la Reggia di Caserta. Se la facciata sembra respirare, è barocco."),
       ("Passo 4 — Moderno (1920-oggi): via gli ornamenti",
        "Nessuna decorazione: la forma segue la funzione. Linee rette, superfici lisce, tetti piani, finestre a nastro o intere pareti di vetro. Cemento armato lasciato a vista, acciaio, pilastri che sollevano l'edificio da terra. Il Bauhaus, Le Corbusier, i grattacieli di vetro. Dagli anni Ottanta il postmoderno reintroduce citazioni e colori in modo ironico. Ora guarda la tua via: quanti secoli attraversi in cento metri?"),
      ]),

    # ------------------------------ GEOGRAFIA ------------------------------
    L("geografia", "v5-lez-coordinate",
      "Latitudine e longitudine: leggere le coordinate in 4 passi", ["coordinate"],
      "41.9028° N, 12.4964° E. Due numeri e un punto preciso sulla Terra, senza ambiguità. Il sistema ha 2.000 anni e funziona ancora meglio degli indirizzi.",
      "Capire il sistema di coordinate geografiche, leggerle e usarle su una mappa o sul telefono.",
      "La latitudine misura la distanza dall'equatore, da 0 a 90 gradi Nord o Sud. La longitudine misura la distanza dal meridiano di Greenwich, da 0 a 180 gradi Est o Ovest. Un grado di latitudine è sempre 111 chilometri; un grado di longitudine si restringe verso i poli.",
      [
       ("Passo 1 — La latitudine: quanto sei a nord",
        "Immagina la Terra tagliata a fette parallele all'equatore. L'equatore è 0 gradi, il Polo Nord 90 gradi Nord, il Polo Sud 90 gradi Sud. Roma è a circa 42 gradi Nord. La latitudine si può misurare da soli: nell'emisfero nord, l'altezza della Stella Polare sopra l'orizzonte in gradi è la tua latitudine. Un grado vale sempre circa 111 chilometri."),
       ("Passo 2 — La longitudine: quanto sei a est",
        "Le fette verticali, i meridiani, passano tutti per i poli. Serviva uno zero, e nel 1884 si scelse quello di Greenwich, a Londra. Da lì si conta fino a 180 gradi verso Est e verso Ovest. Roma è a circa 12 gradi Est. La longitudine fu per secoli impossibile da misurare in mare: servivano orologi precisi, e il problema fu risolto solo nel Settecento."),
       ("Passo 3 — Gradi, minuti, secondi o decimali",
        "Un grado si divide in 60 minuti e un minuto in 60 secondi: 41°54'10'' N. Oppure, più comodo per i computer, in decimali: 41.9028. Per convertire, dividi i minuti per 60 e i secondi per 3.600. Il segno nei decimali: Nord ed Est positivi, Sud e Ovest negativi. Roma è 41.90, 12.50; Buenos Aires è -34.60, -58.38."),
       ("Passo 4 — Usarle davvero",
        "Tieni premuto un punto qualunque su una mappa del telefono e compaiono le sue coordinate. Incolla due numeri nella ricerca e la mappa ti porta lì. In emergenza in montagna, i soccorsi chiedono proprio queste: sapere leggerle sul proprio telefono può fare la differenza. Un grado di longitudine all'equatore vale 111 chilometri, a Roma 83, al circolo polare 44: ecco perché le mappe piatte deformano il Nord."),
      ]),
    L("geografia", "v5-lez-montagne",
      "Come nascono le montagne (e perché le Alpi crescono ancora)", ["montagne"],
      "Sulla cima del Monte Bianco ci sono rocce che erano fondali oceanici. Sull'Everest, fossili marini. Le montagne sono il risultato di uno scontro lentissimo che continua sotto i tuoi piedi.",
      "Capire i tre modi in cui si formano le montagne e riconoscerli nel paesaggio.",
      "Le montagne nascono quando due placche si scontrano e la crosta si accartoccia (Alpi, Himalaya), quando una placca scivola sotto l'altra e fonde producendo vulcani (Ande, Etna), o quando la crosta si spacca e i blocchi si sollevano (Sierra Nevada). L'erosione le smonta mentre crescono.",
      [
       ("Passo 1 — Lo scontro: le pieghe",
        "Quando due continenti si scontrano, nessuno dei due affonda: la crosta si comprime, si piega e si accavalla come un tappeto spinto contro un muro. L'India, staccatasi dall'Africa, ha urtato l'Asia 50 milioni di anni fa e continua a spingere: l'Himalaya cresce di 5 millimetri l'anno. Le Alpi nascono dallo stesso processo, tra Africa ed Europa, e i loro strati sono visibilmente piegati e ribaltati."),
       ("Passo 2 — La subduzione: i vulcani",
        "Se una placca oceanica incontra un continente, essendo più densa scivola sotto e affonda nel mantello. Scendendo rilascia acqua che fa fondere la roccia sopra: il magma risale e forma una catena di vulcani. Le Ande sono così, con il Pacifico che si infila sotto il Sudamerica. Il Giappone, le Cascade americane, e in parte l'Appennino con l'Etna e il Vesuvio."),
       ("Passo 3 — La frattura: i blocchi",
        "Dove la crosta viene stirata invece che compressa, si spacca lungo faglie e i blocchi si inclinano: uno sale, l'altro scende. Nascono catene con un versante ripido e uno dolce, e valli piatte in mezzo. La Sierra Nevada in California, le montagne del Nevada, la Rift Valley africana, dove il continente si sta letteralmente aprendo in due."),
       ("Passo 4 — Costruire e demolire",
        "Mentre la tettonica solleva, ghiaccio, acqua e vento smontano. Le Alpi crescono di circa un millimetro l'anno e ne perdono quasi altrettanto per erosione. Gli Appalachi e gli Urali erano alti come l'Himalaya e sono ridotti a colline: montagne vecchie, arrotondate. Le Alpi sono giovani, aguzze, ancora in cantiere. Guarda un profilo montuoso: le cime affilate dicono gioventù, le dolci dicono centinaia di milioni di anni."),
      ]),
    L("geografia", "v5-lez-correnti-clima",
      "Perché Roma e New York hanno inverni così diversi alla stessa latitudine", ["latitudine", "clima"],
      "Roma e New York sono quasi alla stessa distanza dall'equatore. A gennaio Roma ha 8 gradi, New York zero e bufere di neve. La differenza non viene dal cielo: viene dal mare.",
      "Capire come correnti oceaniche, venti dominanti e continentalità decidono il clima di un luogo più della latitudine.",
      "La latitudine fissa quanta energia solare arriva, ma le correnti oceaniche la ridistribuiscono: la Corrente del Golfo scalda l'Europa occidentale. I venti da ovest portano quel calore sulla terraferma. Lontano dagli oceani il clima è estremo, vicino è mite.",
      [
       ("Passo 1 — Il Sole decide il punto di partenza",
        "Alla stessa latitudine arriva la stessa quantità di energia solare: Roma e New York, intorno ai 41 gradi Nord, dovrebbero avere lo stesso clima. Anche Londra è alla latitudine di Calgary in Canada, e Milano a quella di Montreal. Eppure i climi non c'entrano nulla. Qualcosa sposta il calore da un posto all'altro."),
       ("Passo 2 — Il nastro trasportatore dell'oceano",
        "La Corrente del Golfo porta acqua calda dai Caraibi verso nord-est, attraverso l'Atlantico, fino alla Norvegia: trasporta energia pari a un milione di centrali elettriche. L'Europa occidentale è scaldata dal basso da un oceano tiepido. La costa orientale americana, invece, riceve la corrente fredda del Labrador che scende dall'Artico."),
       ("Passo 3 — I venti da ovest",
        "Alle medie latitudini i venti dominanti soffiano da ovest verso est. In Europa arrivano dall'Atlantico caldo e portano aria mite e umida sulla terraferma. A New York arrivano dal continente americano, gelido in inverno e rovente in estate: l'oceano è lì, ma dal lato sbagliato. Lo stesso vale per la costa ovest americana, mite come l'Europa, e per l'Asia orientale, estrema come New York."),
       ("Passo 4 — La distanza dal mare",
        "L'acqua si scalda e si raffredda lentamente, la terra in fretta. Vicino al mare le stagioni si smorzano, nell'interno dei continenti si esasperano: Jakutsk ha 100 gradi di differenza tra estate e inverno, Lisbona 15. La ricetta del clima: latitudine per la base, correnti e venti per gli aggiustamenti, distanza dal mare per gli estremi. Con questi tre puoi prevedere il clima di quasi ogni città guardando la mappa."),
      ]),
    L("geografia", "v5-lez-jet-lag",
      "Battere il jet lag: 4 passi prima, durante e dopo il volo", ["jet lag"],
      "Sei ore di fuso e per una settimana ti svegli alle quattro di notte con la fame. Il tuo orologio interno si sposta di circa un'ora al giorno, ma puoi aiutarlo a fare più in fretta.",
      "Capire cosa causa il jet lag e applicare strategie pratiche su luce, sonno e pasti per ridurlo.",
      "Il jet lag è il conflitto tra l'orologio interno e l'ora locale. Si risolve con la luce, che è il segnale principale: cercala al mattino locale andando a est, alla sera andando a ovest. Sposta i pasti sull'ora di destinazione, evita alcol in volo e non dormire di pomeriggio all'arrivo.",
      [
       ("Passo 1 — Capire il problema",
        "Nel cervello un orologio di circa 24 ore regola sonno, temperatura, ormoni e fame, e si sincronizza con la luce. Volando attraverso sei fusi orari il corpo resta sull'ora di casa e ci mette circa un giorno per ogni ora di differenza a riallinearsi. Verso est è più dura: devi anticipare, e l'orologio interno preferisce ritardare."),
       ("Passo 2 — Prima di partire",
        "Nei due o tre giorni prima, sposta sonno e pasti di un'ora al giorno verso l'orario di destinazione: se vai a est, vai a letto e alzati prima; se vai a ovest, dopo. Imposta l'orologio sull'ora di arrivo appena sali a bordo e comincia a comportarti di conseguenza: se là è notte, dormi; se è giorno, resta sveglio anche se il volo è al buio."),
       ("Passo 3 — In volo",
        "Bevi molta acqua: l'aria della cabina è più secca del deserto e la disidratazione peggiora tutto. Evita alcol e caffè, che frammentano il sonno. Se devi dormire, mascherina, tappi e un cuscino per il collo; se devi restare sveglio, alzati e cammina ogni ora. Mangia agli orari della destinazione, non quando passa il carrello."),
       ("Passo 4 — All'arrivo: la luce",
        "La luce è il comando più forte per l'orologio interno. Verso est, cerca luce di mattina ed evitala la sera: anticipa l'orologio. Verso ovest, cerca luce nel tardo pomeriggio: lo ritarda. Esci, cammina, niente occhiali da sole nelle ore giuste. Non fare pisolini lunghi: massimo 20 minuti, prima delle 15. Cena leggera all'ora locale e a letto solo all'ora locale, anche se sei distrutto alle 19. Il primo giorno è duro, dal secondo si scende in fretta."),
      ]),
    L("geografia", "v5-lez-leggere-valle",
      "Leggere un paesaggio: chi ha scavato questa valle?", ["paesaggio", "valle"],
      "Una valle a V o a U, un lago in alto, un masso enorme nel mezzo di un prato. Il paesaggio è un libro scritto da acqua e ghiaccio, e con quattro indizi sai leggere chi ha fatto cosa.",
      "Riconoscere le forme create dai fiumi e dai ghiacciai e ricostruire la storia di un paesaggio di montagna.",
      "Una valle a V stretta è opera di un fiume; una valle a U larga con fondo piatto e pareti ripide è opera di un ghiacciaio. I laghi alpini in conche, i massi erratici e i cordoni di detriti sono firme del ghiaccio. Le terrazze e i meandri sono firme dell'acqua.",
      [
       ("Passo 1 — V o U",
        "Un fiume scava verso il basso e la valle si allarga solo per il crollo dei versanti: il profilo è una V, stretta in fondo, con il fiume che ne occupa tutto il letto. Un ghiacciaio è largo centinaia di metri e spesso decine: raschia il fondo e i fianchi insieme, lasciando una U con pareti ripide e fondo piatto. Le grandi valli alpine, Valle d'Aosta, Valtellina, sono U con un fiume oggi piccolo in mezzo: il ghiaccio se n'è andato 12.000 anni fa."),
       ("Passo 2 — Le firme del ghiaccio",
        "Valli laterali che sboccano in alto sulla parete della valle principale, con cascate: il ghiacciaio grande scavava più in profondità di quelli piccoli. Conche circolari sotto le creste, spesso con un laghetto: i circhi dove il ghiaccio nasceva. Massi enormi isolati in mezzo a un prato, di roccia diversa da quella intorno: trasportati dal ghiaccio e lasciati lì. Colline allungate di ghiaia e sassi: le morene, i detriti spinti dal fronte."),
       ("Passo 3 — Le firme dell'acqua",
        "Un fiume in pianura serpeggia: i meandri erodono all'esterno delle curve e depositano all'interno, e con il tempo si spostano, lasciando lanche e anse abbandonate. Terrazze piatte a gradini lungo la valle: antichi fondovalle da cui il fiume è sceso. Conoidi a ventaglio dove un torrente sbocca in una valle più grande: detriti depositati quando la pendenza cala di colpo. Le gole strette e profonde: il fiume ha inciso roccia dura mentre il territorio si sollevava."),
       ("Passo 4 — Mettere insieme la storia",
        "Sali su un punto alto e guarda la valle. Forma a U con gradini laterali e morene: un ghiacciaio l'ha modellata nell'ultima glaciazione. Il fiume nel fondo ha poi inciso una piccola V nella U, e i torrenti laterali hanno costruito conoidi su cui, non a caso, sorgono i paesi, al sicuro dalle piene. I laghi prealpini, Como, Garda, Maggiore, riempiono le conche scavate dalle lingue glaciali che uscivano dalle Alpi. Ogni paesaggio è una sequenza: chi ha letto l'ordine, ha capito il posto."),
      ]),
]
