"""PAUSE — traduzioni EN per le storie di GEOGRAFIA (v5.2)."""
from story_builder import en_entry as E

EN = {
    "geo-why-timezones": E(
        "Why do time zones exist?",
        ["time", "zones"],
        "When it's noon in Rome, in Tokyo it's already evening and in New York it's deep night. A system we take for granted, but born less than 150 years ago.",
        "Time zones exist because the Earth rotates and the Sun lights up areas at different moments: they were standardized in the 1800s thanks to the railways.",
        [
            ("Time follows the Sun",
             "For most of history, every city set its clock by the local Sun: noon was when the Sun was highest in the sky. This meant nearby cities had slightly different times. It worked fine in a slow world, where a journey took days and no one noticed a few minutes of gap between one place and another."),
            ("Railways change everything",
             "With the arrival of trains, the matter became chaos. How do you write a railway timetable if every station has a different time? Accidents and missed connections pushed toward standardization. The need to coordinate travel over long distances was the real engine that led to inventing a shared time."),
            ("The birth of the zones",
             "In 1884 an international conference in Washington divided the world into 24 time zones, each about 15 degrees of longitude. The Greenwich observatory, in London, was chosen as the zero meridian of reference. From there hours are counted forward toward the east and backward toward the west, creating the orderly temporal mosaic we use today."),
            ("Winding borders",
             "On paper the zones should be regular vertical bands, but in reality the borders wind to follow those of states. Some huge countries, like China, use a single time zone despite spanning several bands: a political choice to unify the nation, even though in the west the Sun rises hours late by the clock."),
            ("Curiosities from the zones",
             "Some places have 'odd' zones, offset by half an hour or 45 minutes, like parts of India and Nepal. The International Date Line, in the Pacific, separates one day from another: crossing it you can 'time travel' by a whole day. And near the poles, where all the zones tighten together, time becomes almost an arbitrary convention."),
            ("The takeaway",
             "Time zones seem a natural law, but they're a recent invention, born from the need to coordinate in a world that became fast. They're a perfect example of how technology (trains, then planes) forced us to agree on something as elusive as time itself."),
        ]),
    "geo-highest-mountain": E(
        "Is Everest really the highest mountain?",
        ["Everest", "mountain"],
        "Everyone knows Everest is the roof of the world. But the answer depends on how you measure 'high': there are mountains that, in some ways, beat it.",
        "Everest is the highest peak above sea level, but not the tallest mountain from base to top, nor the point farthest from the center of the Earth.",
        [
            ("The roof of the world",
             "Everest, between Nepal and Tibet, reaches 8,849 meters above sea level: it's the peak that rises highest relative to the surface of the oceans. That's why it's universally considered the highest mountain on the planet. Climbing it remains one of mountaineering's most coveted and dangerous feats, with its 'death zone' beyond 8,000 meters."),
            ("High compared to what?",
             "But 'height' is ambiguous. If we measure a mountain from its base to its summit, Everest loses the record. Its base is already on a high plateau, so the real vertical rise is less impressive than it seems. The question 'how tall is it' actually hides several different ways of measuring."),
            ("The tallest mountain from base",
             "Mauna Kea, in Hawaii, measured from its base on the ocean floor to the top, exceeds 10,000 meters: more than Everest. Most of it is submerged in water, so it emerges 'only' about 4,200 meters. From base to summit, however, it's the tallest mountain on Earth."),
            ("The point closest to space",
             "There's a third way of seeing it. The Earth isn't a perfect sphere: it's flattened at the poles and bulging at the equator. That's why the summit of the Chimborazo volcano, in Ecuador, near the equator, is the point of Earth's surface farthest from the planet's center, and thus closest to space, despite being much lower than Everest in meters above sea level."),
            ("Mountains that grow",
             "Mountains aren't motionless: Everest grows a few millimeters a year, because the Indian plate keeps pushing against the Asian one. Earthquakes can instead lower its height suddenly. The heights we find in books are snapshots of a geological process still underway, slow but unstoppable."),
            ("The takeaway",
             "'What's the highest mountain?' has at least three different answers depending on what we mean: above sea level Everest wins, from the base Mauna Kea, from the Earth's center Chimborazo. A reminder that even the simplest questions, in geography, hide surprising nuances."),
        ]),
    "geo-why-oceans-salty": E(
        "Why is the sea salty and rivers aren't?",
        ["sea", "salt"],
        "We drink river water but not sea water. Yet rivers flow into the sea. Where does all that salt come from, and why doesn't it leave?",
        "The sea is salty because rivers carry minerals eroded from rocks: the water evaporates and returns fresh, but the salt stays and builds up over time.",
        [
            ("A slow accumulation",
             "Rainwater, slightly acidic, falls on rocks and dissolves small amounts of minerals, including salts. Rivers gather these substances and carry them to the sea. Each river brings very little salt, but the process has gone on for billions of years. The sea is, in a sense, the great container where all this has accumulated."),
            ("Why rivers stay fresh",
             "If rivers carry salt, why isn't their water salty? Because they flow: the water is passing through, it doesn't stay long enough to concentrate the salts. The amount they carry is minimal compared to the volume that flows constantly toward the sea. It's like a pipe delivering salt without ever keeping it."),
            ("The evaporation trap",
             "In the sea the crucial difference happens. The Sun evaporates the water, which rises as pure vapor and falls again as fresh rain, feeding the rivers once more. But salt doesn't evaporate: it stays behind in the sea. So, cycle after cycle, the water leaves and returns, while the salt accumulates more and more."),
            ("Not just from rivers",
             "Part of the salt also comes from the ocean floor, from hydrothermal vents and underwater volcanic activity, which release minerals directly into the water. The sea is therefore salty due to a double contribution: what comes down from the land and what rises from the depths of the crust."),
            ("Some seas saltier than others",
             "Not all seas are the same. The Dead Sea is so salty that you can float effortlessly, because it evaporates a lot in a hot climate and receives little fresh water. Seas in cold regions or fed by large rivers are less salty. Salinity is a delicate balance between water input and evaporation."),
            ("The takeaway",
             "The salty taste of the sea is the result of billions of years of erosion and evaporation: a giant funnel that collects the minerals of the land and holds them. Every time you taste sea water, you're in a way tasting the slow wearing-down of all the planet's rocks."),
        ]),
    "geo-borders": E(
        "Why do country borders have such strange shapes?",
        ["borders", "states"],
        "Straight lines in the desert, sudden curves along rivers, impossible enclaves. The shapes of states tell of wars, treaties and compromises over centuries.",
        "Borders arise from geography, history and power: mountains and rivers trace some, but many are artificial lines decided at a table by treaties and empires.",
        [
            ("Natural borders",
             "Many borders follow obvious geographic features: mountain ranges, rivers, coasts. They're natural barriers easy to recognize and defend. The Alps, the Pyrenees, the Rio Grande have separated peoples and states for centuries. These borders tend to be stable precisely because nature itself marks the line, with no need for stakes."),
            ("Straight artificial lines",
             "In many regions, especially in Africa and America, borders are perfectly straight lines. They follow nothing natural: they were traced with a ruler by European colonial powers dividing up distant territories, often without knowing them. These lines ignored peoples, languages and cultures, with consequences that still weigh today."),
            ("Borders that divide peoples",
             "When a border cuts a people in two, lasting tensions arise. Communities with the same language and tradition find themselves in different states, or rival groups forced into the same country. Many contemporary conflicts have roots in borders drawn at a table, without regard for who actually lived there."),
            ("Enclaves and curiosities",
             "There are bizarre borders: enclaves, meaning territories of one state completely surrounded by another; villages cut in two by a frontier line running through the houses. Some arise from ancient feudal treaties never updated. They're scars of history left imprinted on the map, often a source of curious anecdotes."),
            ("Borders that change",
             "Borders aren't eternal: they shift with wars, independences, unifications and agreements. In the last century the world map changed continuously, with the birth and disappearance of dozens of states. What seems obvious and definitive to us today, in a few generations might look very different."),
            ("The takeaway",
             "Every line on a map is a condensed story: of geography, power, agreements and conflicts. Borders seem facts, but they're human constructions, often arbitrary. Reading them with a critical eye means understanding that behind every frontier there are choices, and not rarely injustices, of the past."),
        ]),
    "geo-why-deserts": E(
        "Why do deserts form where they form?",
        ["deserts", "climate"],
        "Not just scorching sand: there are freezing deserts and coastal deserts. Their position on Earth isn't random, but follows precise climate rules.",
        "Deserts arise where the air is dry: mostly along two tropical belts where descending atmospheric currents prevent rain from forming.",
        [
            ("What a desert is",
             "A desert isn't defined by heat or sand, but by the scarcity of precipitation: very little rain falls. By this definition, even Antarctica is a desert, the largest in the world, despite being frozen. The common trait is aridity: little available water, which makes life hard for plants and animals."),
            ("The tropical belts",
             "Most large hot deserts lie along two belts, at about 30 degrees north and south of the equator. It's no coincidence: here the air, which had risen warm and humid at the equator dumping rain, descends now dry. This descending air prevents clouds and rain from forming, creating arid belts all around the globe."),
            ("The effect of mountains",
             "Mountain ranges create 'shadow' deserts. When humid air rises along one slope, it cools and dumps rain; past the peak, it descends dry on the other side, leaving it arid. Many deserts lie precisely behind great mountains, sheltered from rain as if by a wall. It's the phenomenon of the rain shadow."),
            ("Coastal and cold deserts",
             "There are deserts along some coasts too, like the Atacama in Chile, one of the most arid places on Earth: cold ocean currents chill the air and block rain. And there are the cold deserts of Central Asia and the poles, where frigid air holds very little moisture. Heat isn't a requirement at all."),
            ("Deserts that move",
             "Deserts aren't motionless: they expand and shrink over centuries, following climate changes. The Sahara, thousands of years ago, was a green savanna with lakes and animals. Today desertification, driven also by human activity, threatens to turn once-fertile lands into desert in various parts of the world."),
            ("The takeaway",
             "The position of deserts isn't a whim of chance, but the result of atmospheric currents, mountains and oceans. Understanding it turns the world map into a readable story: behind every arid expanse there's a precise climatic logic. And it reminds us how thin the balance is between green land and arid land."),
        ]),
    "geo-population": E(
        "Why do people live crammed in certain places and not others?",
        ["population", "cities"],
        "On a nighttime map of Earth, some areas glow with lights and others are dark. Billions of people concentrate on a small part of the planet. Why?",
        "Population concentrates where there's water, fertile land, mild climate and coasts: physical geography has guided for millennia where humans settle.",
        [
            ("Water first of all",
             "The great civilizations were born along rivers: Nile, Tigris, Euphrates, Indus, Yellow River. Water is needed for drinking, farming, transporting goods. Even today the highest population densities are near rivers, lakes and coasts. Where water is lacking, as in the great deserts, humans remain few and scattered."),
            ("Fertile lands",
             "Soil matters enormously. Floodplains, enriched by river sediments, allow abundant agriculture and thus support many people. Mountainous, rocky or icy areas produce little food and host small populations. The ability to feed people has always determined how many a territory could hold."),
            ("The right climate",
             "Humans prefer temperate climates: neither the extreme cold of the poles nor the scorching heat of deserts. The mild-climate belts, with manageable seasons, host the majority of the world's population. Climate influences what can be grown, how much energy is needed to survive and even the diseases prevalent in an area."),
            ("The lure of coasts",
             "Coastal areas are densely populated: they offer fishing, maritime trade, ports and exchanges with the world. Most megacities face the sea or great waterways. The sea was for centuries humanity's main highway, and living near a port meant access to wealth and opportunity."),
            ("History and human choices",
             "Not everything is geography: history, politics and economics count too. A city can grow around a mine, a trade crossroads or a political decision. Migrations toward industrial centers emptied countrysides and filled metropolises. Today over half of humanity lives in cities, a continually growing trend."),
            ("The takeaway",
             "The distribution of humans on the planet isn't random: it follows water, soil, climate and coasts, then history. The nighttime map of Earth, with its concentrated lights, is ultimately a map of where nature made it easiest to live. Geography, silently, has shaped where all of us are."),
        ]),
    "geo-map-lies": E(
        "Why do all world maps 'lie'?",
        ["maps", "projections"],
        "Greenland looks as big as Africa, but it's fourteen times smaller. Every flat map of the world contains an inevitable distortion.",
        "It's impossible to faithfully represent a sphere on a plane: every map must sacrifice something among shapes, areas and distances, distorting reality.",
        [
            ("The problem of the sphere",
             "The Earth is (almost) a sphere; a map is flat. There's no way to flatten a spherical surface without stretching or tearing it somewhere. Try squashing an orange peel on a table: it splits and deforms. Every world map is a compromise: to gain in one quality, it loses another."),
            ("The map we all know",
             "The most famous projection, Mercator's, was born in 1569 for navigation: it keeps directions correct, very useful for ships' routes. But to do so it hugely inflates the areas near the poles. That's why Greenland appears gigantic and tropical countries seem smaller than they really are."),
            ("Distortions with consequences",
             "These deformations aren't neutral. Enlarging Europe and the global North and shrinking Africa and equatorial countries has, according to some, influenced for centuries the perception of the continents' relative importance. A map is never just technical: it also conveys a viewpoint, often without our noticing."),
            ("Other projections, other flaws",
             "There are dozens of alternative projections. Some keep areas correct but distort shapes (continents look 'squashed'); others seek a balance among the various errors. None is perfect: the choice depends on the purpose. A map to navigate, one to study surfaces and one for school can all be different."),
            ("Even the center is a choice",
             "Why do we put Europe at the center and the North at the top? There's no physical law: in space there's no 'up' and 'down'. It's a historical convention. There are maps with the South at the top or centered on the Pacific, which disorient us precisely because they break a habit we thought natural and objective."),
            ("The takeaway",
             "No world map tells the complete truth: they all lie a bit, because they must. Knowing this makes you a more critical map reader: you ask yourself what was distorted and why. Behind something apparently neutral like a map hide technical, historical and cultural choices."),
        ]),
    "geo-rivers-civilization": E(
        "Why do great cities almost always arise near water?",
        ["rivers", "cities"],
        "London on the Thames, Cairo on the Nile, Paris on the Seine. Look at the world's metropolises: almost all have a river or sea beside them. It's no coincidence.",
        "Water has offered for millennia what a city needs: to drink, to irrigate, to transport goods and to defend. Rivers were the first highways.",
        [
            ("The lifeblood",
             "A city needs enormous amounts of water: to drink, cook, wash. Before modern aqueducts, the only way to guarantee it to thousands of people was to build near a reliable source. A river or lake was the obvious choice. Without water nearby, no settlement could grow beyond a certain size."),
            ("Farming to feed",
             "The plains crossed by rivers are fertile: floods deposit nutrient-rich sediments. The Nile, with its annual floods, made Egyptian civilization possible. A land able to produce food abundantly could support a numerous population, freeing some people from working the fields to devote themselves to other things."),
            ("The highways of antiquity",
             "Before paved roads and trains, moving heavy goods by land was very slow and costly. On water, instead, a boat could carry enormous loads with little effort. Rivers and seas were the great trade routes. A city on a navigable waterway naturally became a center of exchange and wealth."),
            ("Defense and power",
             "A river or the sea also offered protection: a natural obstacle against invaders, a ready-made moat. Many cities arose on river islands or on promontories defended by water. Controlling a ford or a port meant controlling trade and movement: an enormous strategic power in the hands of whoever held that point."),
            ("The flip side",
             "Living near water has a price, though: floods. The same floods that brought fertility could destroy homes and crops. Many civilizations developed hydraulic engineering, embankments and canals precisely to tame the rivers. Even today many metropolises fight against flood risk, worsened by climate change."),
            ("The takeaway",
             "Looking at a map of great cities, water tells of their origin: it was life, food, transport and defense at once. Even in the age of aqueducts and planes, that ancient bond remained imprinted in urban geography. Our metropolises often arise where, millennia ago, the most sensible choice flowed."),
        ]),
    "geo-plate-tectonics": E(
        "Do the continents really move?",
        ["continents", "plates"],
        "It sounds absurd, but Africa and South America were once attached. The continents travel, ever so slowly, beneath our feet at this very moment.",
        "Earth's surface is divided into plates that move a few centimeters a year: their slow journey creates mountains, earthquakes, volcanoes and new oceans.",
        [
            ("A brilliant intuition",
             "At the start of the twentieth century, scientist Alfred Wegener noticed that the coasts of Africa and South America fit together like puzzle pieces. He proposed that the continents were once united in a single supercontinent, called Pangaea, then fragmented. The idea was mocked for decades: it seemed impossible that such enormous masses could move."),
            ("The hidden proofs",
             "Wegener was right. Identical fossils of plants and animals are found on continents now separated by oceans: impossible, if they hadn't been united. Rock formations also match between very distant lands. These traces, scattered around the world, told a shared story of continents once embraced."),
            ("The engine beneath our feet",
             "The mechanism was understood later: Earth's crust is divided into large plates that float on a layer of hot, semi-fluid rock. The planet's internal heat generates slow convective motions that drag the plates. They move a few centimeters a year, roughly as fast as our nails grow, but over geological time they travel thousands of kilometers."),
            ("Where plates meet",
             "At the edges of the plates almost everything dramatic in geology happens. Where they collide, mountains rise like the Himalayas, still growing. Where one slides under another, volcanoes and violent earthquakes are born. Where they pull apart, magma rises and creates new crust, widening the oceans centimeter by centimeter."),
            ("The future of the map",
             "The movement continues. In tens of millions of years Africa could split along the Rift Valley, the Atlantic widen further, the Mediterranean close as Africa presses on Europe. Scientists hypothesize the continents will reunite in a new supercontinent, far off in time. The map we know is just one frame."),
            ("The takeaway",
             "The ground that seems to us the very image of stability is actually in perpetual, very slow motion. Mountains, oceans and earthquakes are the manifestations of this invisible journey. Continental drift reminds us that even the things we take for most unchanging, on a large enough scale, change constantly."),
        ]),
    "geo-why-travel": E(
        "Why does travel really change us?",
        ["travel", "mind"],
        "It's not just relaxation or photos to show off. Travel, when we do it well, leaves a deep mark on how we think and see the world. Here's why.",
        "Travel exposes us to novelty and different perspectives: it challenges our mental habits, increases empathy and creativity, and lets us see our life from outside.",
        [
            ("The brain loves novelty",
             "When we're in a new place, the brain is more attentive and present: everything is to be decoded, nothing is automatic. This intense attention makes travel memories often more vivid than routine. Stepping out of habitual patterns awakens a curiosity that tends to fall asleep in everyday life."),
            ("Breaking automatisms",
             "At home we live largely on autopilot: same routes, same gestures. Travel forces us to solve small new problems constantly: finding our way, communicating, adapting. This mental gymnastics makes us more flexible and trains us to handle the unexpected, a skill useful well beyond holidays."),
            ("Seeing other perspectives",
             "Meeting different cultures shows that our way of living isn't the only possible one nor 'the naturally right one'. Habits, foods, values we believed universal turn out to be choices among many. This broadens the mind and nourishes empathy: we understand that behind different behaviors there are reasons, stories and logics different from ours."),
            ("Looking at your own life from outside",
             "Physical distance creates mental distance. Away from daily problems, we often see them more clearly: what really matters, what we want to change. Many people make important decisions precisely while traveling, not by magic of the place, but because they finally have space to think without the usual noise."),
            ("Moving isn't enough",
             "Beware, though: travel doesn't automatically change anyone. Those who stay closed, avoid all contact and seek home comforts everywhere often return identical to how they left. Change comes from openness: talking with people, trying the unknown, accepting disorientation. It's the attitude, more than the destination, that makes the difference."),
            ("The takeaway",
             "Travel changes us when we truly let ourselves be crossed by what we meet. You don't need exotic destinations: exploring with fresh eyes what's near can have the same effect. The real souvenir of a good trip isn't in the suitcase, but in the slightly different way we, once back, look at the world and ourselves."),
        ]),
}
