"""PAUSE v5 — ampliamento catalogo (parte D): Curiosità, Economia & Denaro.
5 curiosità + 5 mini lezioni per categoria, scritte a mano in italiano."""
from story_builder import mk, mk_lesson as L

STORIES = [
    # ------------------------------ CURIOSITÀ ------------------------------
    mk("curiosita", "v5-sacchetto-patatine",
       "Perché il sacchetto delle patatine è mezzo vuoto?", ["sacchetto", "vuoto"],
       "Lo apri e trovi metà aria. Sembra una truffa, e in parte è marketing. Ma quell'aria non è aria, e senza di lei le patatine sarebbero immangiabili.",
       "Il sacchetto è riempito di azoto puro: senza ossigeno i grassi non irrancidiscono e senza umidità le patatine restano croccanti. Il cuscino di gas protegge anche dagli urti. Il volume vuoto medio è circa il 40%.",
       "",
       [
        ("Non è aria",
         "L'aria contiene il 21% di ossigeno, che reagisce con i grassi delle patatine e dopo poche settimane dà il sapore di rancido. L'azoto è inerte: non reagisce con nulla. Prima di sigillare il sacchetto, la macchina soffia via l'aria e la sostituisce con azoto puro. Lo stesso gas allunga la vita di insalate in busta, caffè e pane confezionato."),
        ("Un airbag per le patatine",
         "Le patatine sono fragili e il sacchetto viaggia in scatoloni, camion e scaffali. Il cuscino di gas assorbe gli urti come un airbag: un sacchetto sottovuoto arriverebbe pieno di briciole. I produttori hanno testato il volume minimo che protegge il contenuto ed è vicino a quello che vedi."),
        ("Quanto è pieno davvero",
         "Un'analisi su decine di marche ha trovato che in media il 43% del volume è gas, con punte oltre il 60%. La legge obbliga a indicare il peso netto, non il volume, quindi non è inganno: stai pagando i grammi scritti sull'etichetta. Ma un sacchetto grande vende di più, e le aziende lo sanno."),
        ("Perché il sacchetto è argentato",
         "L'interno metallizzato non è decorativo: blocca luce e ossigeno, che attraversano lentamente la plastica normale. La luce accelera l'irrancidimento dei grassi. Sacchetto opaco, azoto dentro e sigillo ermetico danno alle patatine una vita di scaffale di mesi. Apri il sacchetto, e il conto alla rovescia parte: dopo un giorno sono molli."),
       ]),
    mk("curiosita", "v5-miele-non-scade",
       "Il miele non scade mai (e quello dei faraoni era ancora buono)", ["miele", "scade"],
       "Vasi di miele trovati nelle tombe egizie, vecchi di 3.000 anni, erano ancora commestibili. Non esiste altro alimento che faccia lo stesso. Il merito è delle api, e di una chimica quasi perfetta.",
       "Il miele è troppo concentrato di zucchero per far vivere i batteri, troppo acido per la maggior parte dei microbi e contiene perossido di idrogeno prodotto da un enzima delle api. Sigillato, resta buono per sempre.",
       "",
       [
        ("Quasi niente acqua",
         "Il miele è zucchero all'80% e acqua al 17%. Lo zucchero attira l'acqua dalle cellule di qualunque batterio o lievito ci cada dentro, disidratandolo fino a ucciderlo. È lo stesso principio della marmellata e del sale che conserva il prosciutto, ma spinto al limite."),
        ("Acido e disinfettante",
         "Il miele ha pH tra 3,5 e 4,5, come un succo di frutta: troppo acido per la maggior parte dei microbi. Inoltre le api aggiungono un enzima, la glucosio ossidasi, che produce lentamente piccole quantità di perossido di idrogeno, l'acqua ossigenata. Per questo il miele si usava sulle ferite dagli egizi fino alla Prima guerra mondiale, e in alcuni ospedali si usa ancora."),
        ("Il lavoro delle api",
         "Il nettare è acqua al 70%. Le api lo passano di bocca in bocca aggiungendo enzimi, poi lo depositano nelle celle e sbattono le ali per farlo evaporare fino al 17-18%. Solo allora sigillano la cella con cera. Il miele è nettare disidratato e trasformato da migliaia di api che lavorano per giorni."),
        ("Le uniche condizioni",
         "Il barattolo deve restare chiuso: il miele assorbe umidità dall'aria e sopra il 20% d'acqua i lieviti ripartono e fermenta. Se cristallizza, diventa solido e opaco, non è andato a male: basta scaldarlo a bagnomaria. La data sull'etichetta è un obbligo di legge, non una scadenza reale."),
       ]),
    mk("curiosita", "v5-cavi-annodano",
       "Perché i cavi delle cuffie si annodano da soli in tasca?", ["cavi", "annodano"],
       "Li metti in tasca ordinati, li tiri fuori annodati. Non è sfortuna: due fisici hanno fatto l'esperimento 3.415 volte e hanno trovato la formula.",
       "Un cavo agitato in uno spazio chiuso forma nodi con probabilità che cresce con la lunghezza e la flessibilità: oltre i 46 centimetri, in pochi secondi di scossoni, si annoda in oltre metà dei casi. La causa è che ci sono molti più modi di essere annodato che di non esserlo.",
       "",
       [
        ("L'esperimento della scatola",
         "Nel 2007 due fisici dell'Università di San Diego misero cavi di varie lunghezze in una scatola e la fecero ruotare per dieci secondi, 3.415 volte. Sotto i 46 centimetri, nessun nodo. Tra 46 centimetri e 1,5 metri, la probabilità saliva rapidamente fino a superare il 50%. Cavi più lunghi non si annodavano di più perché lo spazio li costringeva a impacchettarsi."),
        ("Come si forma un nodo",
         "Nella scatola il cavo si arrotola in spire e un'estremità libera, agitata, scivola tra le spire. Ogni volta che l'estremità attraversa una spira, il cavo ha una probabilità di aver fatto un nodo. Bastano poche oscillazioni: i ricercatori hanno identificato 120 tipi di nodo diversi, alcuni con sette incroci."),
        ("La statistica è contro di te",
         "Un cavo ha una sola configurazione 'dritta' e un numero enorme di configurazioni annodate. Il movimento casuale le esplora tutte, e una volta entrato in un nodo il cavo non ne esce da solo: i nodi si formano facilmente e si sciolgono con difficoltà. È lo stesso motivo per cui la scrivania si disordina da sola e non si riordina mai."),
        ("Come evitarlo",
         "Tre fattori contano: lunghezza, flessibilità e tempo di agitazione. Cavi corti e rigidi non si annodano. Per gli altri: avvolgili in un anello e fissali con una fascetta, così l'estremità libera non può infilarsi nelle spire. Le cuffie senza fili hanno risolto il problema eliminando il cavo, ma la fisica dei nodi resta utile per il DNA, che nelle cellule si annoda allo stesso modo e ha enzimi apposta per sciogliersi."),
       ]),
    mk("curiosita", "v5-banane-radioattive",
       "Le banane sono radioattive (e tu anche)", ["banane", "radioattive"],
       "Una banana emette circa 15 disintegrazioni radioattive al secondo. Al punto che i fisici usano la 'dose equivalente a una banana' come unità di misura informale. Prima di preoccuparti: anche tu emetti radiazioni.",
       "Le banane contengono potassio, e una piccola frazione del potassio naturale è l'isotopo radioattivo potassio-40. La dose di una banana è un decimilionesimo di quella annuale che ricevi dall'ambiente. Il tuo corpo ne contiene l'equivalente di 280 banane.",
       "",
       [
        ("Il potassio-40",
         "Il potassio è essenziale alla vita, e in natura lo 0,012% è potassio-40, un isotopo radioattivo con un tempo di dimezzamento di 1,25 miliardi di anni. Ogni alimento ricco di potassio lo contiene: banane, patate, fagioli, noci, spinaci. Una banana media ha 450 milligrammi di potassio e circa 15 atomi che decadono ogni secondo."),
        ("La dose banana",
         "Mangiarne una equivale a una dose di 0,1 microsievert. La radiazione naturale di fondo, da rocce, cosmo e cibo, dà circa 2.400 microsievert l'anno. Una radiografia al torace circa 100. Un volo transatlantico 40, per i raggi cosmici in quota. Servirebbero 35 milioni di banane in una volta per avere una dose pericolosa."),
        ("Anche tu lo sei",
         "Un adulto contiene circa 140 grammi di potassio, e quindi circa 4.400 disintegrazioni al secondo di potassio-40, più un'altra fonte, il carbonio-14. Dormire accanto a una persona per un anno dà una dose simile a quella di qualche banana. E il potassio in eccesso viene espulso: mangiare banane non ti rende più radioattivo."),
        ("I camion di banane fermati alla dogana",
         "I rilevatori di radiazioni nei porti americani, installati per intercettare materiale nucleare, scattano regolarmente su carichi di banane, lettiera per gatti a base di argilla e piastrelle di granito. Tutti materiali naturali. La radioattività non è un'invenzione umana: è ovunque, da sempre, e il nostro corpo ci è nato dentro."),
       ]),
    mk("curiosita", "v5-qwerty",
       "Perché i tasti della tastiera sono in quest'ordine assurdo?", ["tastiera", "ordine"],
       "Q, W, E, R, T, Y. Nessuna logica alfabetica, le lettere più usate sparse ovunque. La disposizione ha 150 anni ed è nata per una macchina che non esiste più. Eppure non riusciamo a cambiarla.",
       "La disposizione QWERTY fu messa a punto nel 1873 per la macchina da scrivere Remington, probabilmente per evitare che i martelletti di lettere vicine si incastrassero e forse per aiutare i telegrafisti. È sopravvissuta per abitudine: cambiare costa più di quanto renda.",
       "",
       [
        ("I martelletti che si incastravano",
         "Nelle prime macchine da scrivere ogni tasto muoveva un martelletto che colpiva il foglio dal basso. Se due lettere vicine venivano battute in rapida successione, i martelletti si incastravano. Christopher Sholes provò decine di disposizioni e distribuì le coppie più frequenti in inglese, come T-H, lontane tra loro."),
        ("Forse per il telegrafo",
         "Una ricerca giapponese del 2011 propone un'altra origine: i primi utenti erano operatori del telegrafo che trascrivevano il codice Morse. Alcune lettere nel Morse americano erano ambigue fino all'arrivo del segnale successivo, e la disposizione le teneva vicine per correggere in fretta. La verità è probabilmente un misto di compromessi."),
        ("La riga che vende",
         "Sulla riga superiore si può scrivere la parola TYPEWRITER: secondo la leggenda i venditori la usavano per fare dimostrazioni veloci senza cercare i tasti. Vero o no, nel 1873 la Remington adottò la disposizione e con il suo successo commerciale divenne lo standard. Nel 1893 i principali produttori si accordarono per usarla tutti."),
        ("Perché non cambiamo",
         "Nel 1936 August Dvorak brevettò una tastiera con le vocali sotto la mano sinistra e le consonanti più frequenti sotto la destra: il 70% delle battute avviene sulla riga centrale, contro il 32% di QWERTY. Nei test era un po' più veloce. Ma milioni di persone già sapevano scrivere con QWERTY, e riaddestrarle costava di più. Il tuo telefono, che non ha martelletti, usa una disposizione pensata per evitarli."),
       ]),

    # ------------------------------ ECONOMIA ------------------------------
    mk("economia", "v5-diamanti-prezzo",
       "Perché i diamanti costano così tanto se non sono rari?", ["diamanti", "rari"],
       "Un diamante da un carato costa migliaia di euro. Eppure i diamanti sono tra le gemme più comuni, e rivenderlo ti darà una frazione del prezzo. Il valore è stato costruito, con precisione, da una campagna pubblicitaria.",
       "Per quasi un secolo un'unica società, la De Beers, ha controllato l'offerta mondiale di diamanti, accumulandoli per tenere alti i prezzi. Nel 1947 la sua agenzia inventò lo slogan 'un diamante è per sempre' e l'idea che l'anello di fidanzamento dovesse essere di diamante.",
       "",
       [
        ("La scoperta che ha creato il problema",
         "Fino al 1870 i diamanti venivano da pochi fiumi in India e Brasile: erano davvero rari. Poi in Sudafrica si scoprirono giacimenti enormi, tonnellate di diamanti. Il prezzo sarebbe crollato. I finanzieri delle miniere capirono che dovevano controllare quanti diamanti uscivano, e nel 1888 fondarono la De Beers."),
        ("Un rubinetto mondiale",
         "Per decenni la De Beers comprò o controllò quasi tutta la produzione mondiale, fino al 90%, e la vendette a un ritmo deciso da lei, accumulando scorte quando la domanda calava. Un diamante non è raro come uno smeraldo o un rubino di qualità; è raro sul mercato perché qualcuno lo tiene in cassaforte."),
        ("L'invenzione dell'anello",
         "Negli anni Trenta le vendite calavano. La De Beers ingaggiò un'agenzia di Filadelfia che prestò diamanti alle star di Hollywood, fece scrivere articoli sulle proposte di matrimonio con anelli di diamante e nel 1947 coniò 'A diamond is forever'. Un anello 'per sempre' non si rivende: e infatti ancora oggi il mercato dell'usato è quasi inesistente. In Giappone, dove l'anello di diamante non esisteva, nel 1981 lo indossava il 60% delle spose."),
        ("La crepa nel monopolio",
         "Dagli anni Novanta nuove miniere in Russia, Canada e Australia hanno rotto il controllo: la De Beers è scesa a un terzo del mercato. E dal 2015 i diamanti sintetici, identici a quelli naturali a livello atomico, costano fino all'80% in meno. Il prezzo del naturale regge grazie alla storia che gli è stata costruita intorno. Il valore, a volte, è una narrazione ben fatta."),
       ]),
    mk("economia", "v5-pietre-yap",
       "L'isola dove la moneta erano pietre da quattro tonnellate", ["pietre", "moneta"],
       "Su Yap, nel Pacifico, si pagava con dischi di calcare alti fino a quattro metri. Nessuno li spostava: cambiava solo chi ne era il proprietario. E una pietra caduta in fondo al mare valeva ancora.",
       "I rai di Yap erano dischi di pietra scavati su un'isola a 400 chilometri di distanza. Il loro valore dipendeva dalla storia e dalla fatica per portarli. Le transazioni erano pubbliche e ricordate da tutti: il denaro era il consenso, non l'oggetto. Un'anticipazione della blockchain.",
       "",
       [
        ("Pietre venute dal mare",
         "Yap non ha calcare. Gli abitanti navigavano fino a Palau, 400 chilometri di oceano su canoe, scavavano dischi con un foro al centro e li riportavano. Molti morivano nel viaggio. Il valore di una pietra non dipendeva solo dalle dimensioni ma dalla sua storia: quanti erano morti per portarla, chi l'aveva posseduta."),
        ("Nessuno le sposta",
         "Le pietre grandi restavano dove erano state posate, davanti a una casa o lungo un sentiero. Quando servivano per pagare una dote o comprare una canoa, il proprietario annunciava pubblicamente il passaggio. Tutti sapevano che quella pietra ora era di un altro, e tanto bastava. Il denaro era il registro condiviso nella memoria della comunità."),
        ("La pietra in fondo al mare",
         "Una famiglia possedeva una pietra enorme che, generazioni prima, era affondata durante il trasporto in una tempesta. I sopravvissuti avevano raccontato quanto era grande e bella. Tutti concordavano che esisteva e che apparteneva a quella famiglia, e la famiglia era ricca. Nessuno l'aveva mai vista. Non serviva."),
        ("Cosa insegna",
         "Un economista americano nel 1991 osservò che il sistema di Yap non era così diverso dall'oro conservato nei caveau, che nessuno vede e che cambia proprietario con una scrittura contabile. Il denaro non è mai l'oggetto: è l'accordo su chi possiede cosa. Quando nel 2009 nacque il Bitcoin, un registro pubblico condiviso in cui tutti sanno di chi è ogni moneta, gli economisti citarono Yap."),
       ]),
    mk("economia", "v5-miglia-aeree",
       "Le compagnie aeree guadagnano più vendendo miglia che biglietti", ["miglia", "biglietti"],
       "Il programma fedeltà sembrava un premio per i clienti. È diventato una banca che stampa la propria moneta, e in alcuni casi vale più della compagnia che lo ha inventato.",
       "Le compagnie vendono miliardi di miglia alle banche, che le regalano ai clienti delle carte di credito. Le miglia costano quasi nulla da produrre e molte non vengono mai usate. Nel 2020 il programma fedeltà di American Airlines fu valutato più dell'intera compagnia.",
       "",
       [
        ("Una moneta privata",
         "Il primo programma, quello di American Airlines nel 1981, premiava i clienti frequenti con voli gratis. Ma le compagnie capirono presto che potevano vendere le miglia a terzi: banche, hotel, catene di negozi, che le regalano ai propri clienti. Oggi oltre metà delle miglia in circolazione non è stata guadagnata volando ma con la carta di credito."),
        ("Costa niente, vale tanto",
         "Una compagnia vende una miglia alla banca per circa 1-2 centesimi. Il costo per lei è un posto vuoto su un volo che partirebbe comunque, e solo quando il cliente riscatta. Nel frattempo la compagnia ha incassato subito. È come stampare denaro con la certezza che una parte non verrà mai spesa."),
        ("Le miglia che scadono",
         "Una quota tra il 10 e il 30% delle miglia emesse non viene mai usata: scadono, i clienti dimenticano, i posti disponibili non ci sono mai. Per la compagnia sono ricavi puri. E lei controlla il valore: può alzare il costo in miglia di un volo da un giorno all'altro, una svalutazione che nessuna banca centrale potrebbe permettersi."),
        ("Più preziose degli aerei",
         "Nel 2020, con gli aerei a terra per la pandemia, United e American ottennero prestiti miliardari mettendo in garanzia non gli aerei ma i programmi fedeltà: MileagePlus fu valutato 22 miliardi di dollari, l'intera United in borsa ne valeva 10. Il business principale di una compagnia aerea, oggi, è vendere una moneta; volare è il modo per farla riscattare."),
       ]),
    mk("economia", "v5-latte-fondo",
       "Perché il latte è sempre in fondo al supermercato?", ["latte", "fondo"],
       "Entri per il latte, esci con dodici cose. Non è mancanza di volontà: il percorso è stato progettato per questo, dal parcheggio alla cassa, con studi su come si muovono i clienti.",
       "Il supermercato è disegnato per allungare il percorso e il tempo di permanenza: prodotti essenziali in fondo, frutta all'ingresso per mettere di buon umore, marche costose ad altezza occhi, dolci alla cassa. Ogni metro percorso in più aumenta la spesa.",
       "",
       [
        ("Il pretesto tecnico e quello vero",
         "La spiegazione ufficiale: il latte arriva dal retro, va tenuto al freddo e i frigoriferi stanno vicino al magazzino. Vero in parte. Ma i negozi che hanno provato a mettere il latte davanti hanno visto calare gli incassi. Il latte è l'acquisto più frequente e chi lo cerca deve attraversare tutto il negozio, passando davanti a centinaia di tentazioni."),
        ("Il percorso obbligato",
         "L'ingresso è quasi sempre a destra con un percorso in senso antiorario, perché la maggior parte delle persone tende a girare a destra. All'entrata ci sono frutta, verdura e fiori: colori e profumi che mettono di buon umore e danno un senso di freschezza al negozio intero. Il pane sfornato fa lo stesso lavoro con l'olfatto. Il carrello è grande perché un carrello mezzo vuoto sembra una spesa piccola."),
        ("Lo scaffale ha una geografia",
         "Ad altezza occhi, tra 120 e 160 centimetri, stanno le marche che pagano di più per la posizione o su cui il negozio guadagna di più. In basso, i prodotti economici: chi li vuole si abbassa. All'altezza degli occhi di un bambino, i cereali con i personaggi. I capi di corsia sono i posti più redditizi e ospitano le 'offerte', che spesso non lo sono."),
        ("La cassa e la musica",
         "In coda alla cassa ci sono dolci, gomme e riviste: acquisti d'impulso per chi ha già preso la decisione di spendere. La musica lenta rallenta il passo e aumenta la spesa fino al 38% secondo uno studio classico. Difese semplici: lista scritta, pancia piena, carrello piccolo, e la consapevolezza che ogni corsia in più è stata pensata per te."),
       ]),
    mk("economia", "v5-iperinflazione",
       "Quando i prezzi raddoppiavano ogni 15 ore: la peggiore inflazione della storia", ["raddoppiavano", "15 ore"],
       "Ungheria, 1946. Un operaio riceveva la paga e correva a spenderla prima di sera, perché la mattina dopo valeva la metà. Fu stampata una banconota da 100 milioni di miliardi.",
       "Nel 1946 l'Ungheria conobbe l'iperinflazione più violenta mai registrata: prezzi che raddoppiavano ogni 15 ore, 41 milioni di miliardi per cento al mese. La causa era la stampa di moneta per pagare le riparazioni di guerra. La cura fu una nuova valuta e la fine della stampa.",
       "",
       [
        ("Dalla Germania di Weimar a Budapest",
         "L'iperinflazione tedesca del 1923 è la più famosa: carriole di banconote per un pane. Ma quella ungherese del 1946 la superò di gran lunga. L'economia era distrutta dalla guerra, il governo doveva pagare riparazioni all'Unione Sovietica e le fabbriche non producevano. Lo Stato stampò moneta per coprire ogni spesa."),
        ("Il pengő che evapora",
         "Nell'estate 1945 un dollaro valeva 1.320 pengő. Un anno dopo ne valeva 460.000 miliardi di miliardi. Al picco, in luglio, i prezzi salivano del 150% al giorno. I lavoratori venivano pagati ogni giorno e correvano a comprare qualsiasi cosa. Fu emessa la banconota da 100 quintilioni, con venti zeri, la più alta mai stampata. Non bastò: le successive vennero preparate ma non emesse."),
        ("Come si ferma",
         "Il 1° agosto 1946 il governo introdusse il fiorino, con un cambio di 400.000 quadrilioni di pengő per fiorino, e smise di stampare per coprire il deficit, coperto da tasse e da riserve d'oro tornate dall'estero. L'inflazione si fermò in pochi giorni. La lezione è brutale: la moneta vale finché chi la stampa si trattiene, e crolla nel momento in cui smette."),
        ("Non è storia antica",
         "Lo Zimbabwe nel 2008 stampò la banconota da 100.000 miliardi di dollari locali, che comprava a malapena un biglietto dell'autobus, e abbandonò la sua valuta. Il Venezuela tra il 2016 e il 2019 ha visto prezzi moltiplicarsi per milioni. Il meccanismo è sempre lo stesso: spese che superano le entrate, coperte stampando. Ecco perché le banche centrali sono indipendenti dai governi."),
       ]),
]

LESSONS = [
    # ------------------------------ CURIOSITÀ ------------------------------
    L("curiosita", "v5-lez-regressione-media",
      "Perché la sfortuna 'si equilibra': la regressione verso la media", ["regressione"],
      "Il calciatore in copertina che poi delude, il rimedio che 'funziona' quando il dolore è al massimo, il figlio meno alto del padre altissimo. Tre fenomeni diversi, una sola legge statistica che quasi nessuno riconosce.",
      "Capire la regressione verso la media, riconoscerla nella vita quotidiana e non confonderla con cause inesistenti.",
      "Quando una misura è estrema, la successiva tende a essere più vicina alla media, perché parte dell'estremo era fortuna. Non c'è nessuna forza che riequilibra: è solo che la fortuna non si ripete. Chi non lo sa inventa cause: la maledizione della copertina, il rimedio miracoloso.",
      [
       ("Passo 1 — Il padre altissimo",
        "Galton nel 1886 misurò migliaia di padri e figli: i figli dei padri molto alti erano alti, ma in media meno dei padri; quelli dei molto bassi, meno bassi. Non perché l'umanità si uniformi: l'altezza estrema di un padre è in parte geni, che passa, e in parte fattori casuali, che non passano. Il figlio eredita la parte sistematica e ripesca la fortuna da zero."),
       ("Passo 2 — La maledizione della copertina",
        "Un atleta finisce in copertina dopo una stagione eccezionale. L'anno dopo fa peggio e si parla di maledizione. Ma una stagione eccezionale è talento più fortuna al massimo; la fortuna non si ripete, il talento sì. La copertina non causa il calo: seleziona proprio chi era all'estremo, e l'estremo torna indietro."),
       ("Passo 3 — Il rimedio che funziona sempre",
        "Vai dal medico, o provi un rimedio, quando stai peggio. Ma il peggio è, per definizione, un estremo: dopo tenderai a migliorare comunque. Qualunque cosa tu abbia preso in quel momento sembrerà aver funzionato. È il motivo per cui i farmaci si testano contro un placebo: per separare l'effetto reale dalla regressione che avviene da sola."),
       ("Passo 4 — Come usarla",
        "Prima di attribuire una causa a un cambiamento, chiediti: il punto di partenza era estremo? Se sì, una parte del ritorno verso il normale sarebbe avvenuta comunque. Vale per il rendimento di un dipendente dopo una sgridata, per un fondo di investimento dopo un anno record, per un ristorante dopo la recensione entusiasta. Chi lo sa evita di premiare la fortuna e punire la sfortuna."),
      ]),
    L("curiosita", "v5-lez-grafici-ingannevoli",
      "Come un grafico può mentire dicendo la verità: 4 trucchi da riconoscere", ["grafico"],
      "I numeri sono corretti, le fonti citate, e il messaggio è falso. I grafici ingannevoli non inventano dati: scelgono come mostrarli. Bastano quattro controlli per non caderci.",
      "Riconoscere le manipolazioni più comuni nei grafici di notizie e pubblicità e leggere i dati per quello che dicono.",
      "Controlla dove parte l'asse verticale (uno zero mancante gonfia le differenze), quale intervallo di tempo è mostrato, se le scale dei due grafici confrontati sono uguali e se un'area o un'immagine è stata usata al posto di una lunghezza.",
      [
       ("Passo 1 — L'asse che non parte da zero",
        "Due colonne, una a 50 e una a 52, sembrano quasi uguali. Ma se l'asse parte da 49, la seconda è tre volte più alta della prima. È il trucco più usato: un aumento del 4% che sembra un raddoppio. Cerca sempre il numero in basso all'asse verticale. Nei grafici a linee tagliare l'asse può essere legittimo, in quelli a barre quasi mai."),
       ("Passo 2 — La finestra temporale",
        "Un titolo che crolla del 30% in una settimana può essere un titolo salito del 300% in un anno. Chi sceglie il periodo sceglie la storia. 'Le vendite sono in calo' guardando gli ultimi due mesi; 'ai massimi storici' guardando dieci anni. Chiediti sempre: cosa c'era prima dell'inizio del grafico?"),
       ("Passo 3 — Due scale diverse",
        "Due linee sullo stesso grafico, una con la scala a sinistra e una a destra: chi le disegna può far coincidere qualunque andamento con qualunque altro stirando una scala. Molte 'correlazioni' spettacolari tra fenomeni scollegati nascono così. Se le scale sono diverse, il fatto che le linee si sovrappongano non significa niente."),
       ("Passo 4 — Aree e figure",
        "Un'infografica mostra due persone, una alta il doppio dell'altra, per dire che un valore è doppio. Ma la figura doppia in altezza è anche doppia in larghezza: l'occhio vede un'area quattro volte più grande. Lo stesso con torte in 3D che ingrandiscono la fetta davanti. Quando vedi immagini invece di barre, torna ai numeri."),
      ]),
    L("curiosita", "v5-lez-effetto-doppler",
      "Perché la sirena cambia tono quando passa: l'effetto Doppler", ["sirena", "Doppler"],
      "L'ambulanza si avvicina e il suono è acuto; passa, e diventa grave. La sirena non è cambiata. È lo stesso fenomeno che ci ha detto che l'universo si espande.",
      "Capire l'effetto Doppler nel suono e nella luce e le sue applicazioni, dagli autovelox all'astronomia.",
      "Se la sorgente si avvicina, le onde arrivano compresse, più frequenti: suono più acuto, luce più blu. Se si allontana, arrivano dilatate: suono più grave, luce più rossa. Misurando lo spostamento si calcola la velocità di qualunque cosa emetta o rifletta onde.",
      [
       ("Passo 1 — Onde compresse e stirate",
        "Una sirena emette onde sonore a intervalli regolari. Se si muove verso di te, ogni onda parte da un punto un po' più vicino della precedente: le onde si accumulano, la distanza tra loro diminuisce e ne ricevi più al secondo. Frequenza più alta, suono più acuto. Quando si allontana, il contrario. Il tono che sente l'autista non cambia mai."),
       ("Passo 2 — Misurare la velocità",
        "Lo spostamento di frequenza dipende dalla velocità: più veloce, più grande. L'autovelox invia onde radio, riceve quelle riflesse dall'auto e misura di quanto è cambiata la frequenza. I radar meteorologici fanno lo stesso con le gocce di pioggia per vedere i venti dentro un temporale. L'ecografia Doppler misura la velocità del sangue nelle arterie."),
       ("Passo 3 — Anche la luce",
        "La luce è un'onda e obbedisce alla stessa regola. Una sorgente che si allontana appare più rossa, una che si avvicina più blu. Le velocità quotidiane sono troppo piccole per vederlo, ma le stelle no: dalle righe del loro spettro si legge se si avvicinano o si allontanano e a quale velocità. È così che si scoprono pianeti intorno ad altre stelle: la stella oscilla appena, e il suo colore con lei."),
       ("Passo 4 — L'universo che si espande",
        "Nel 1929 Edwin Hubble misurò la luce di decine di galassie: quasi tutte spostate verso il rosso, e più erano lontane, più lo erano. Tutte si allontanano da noi, e da tutte le altre: lo spazio stesso si sta espandendo. Da quella osservazione nasce l'idea del Big Bang. La stessa fisica dell'ambulanza che passa sotto casa."),
      ]),
    L("curiosita", "v5-lez-hotel-hilbert",
      "L'albergo con infinite stanze: capire l'infinito con Hilbert", ["infinito", "Hilbert"],
      "Un albergo pieno, con infinite stanze tutte occupate. Arriva un nuovo ospite. Il direttore lo sistema senza cacciare nessuno. Poi ne arrivano infiniti, e li sistema tutti. Benvenuto nell'infinito.",
      "Capire attraverso il paradosso dell'albergo di Hilbert perché l'infinito non si comporta come i numeri normali e perché esistono infiniti più grandi di altri.",
      "Nell'albergo infinito si fa spazio spostando ogni ospite nella stanza successiva, o in quella con numero doppio. Infinito più uno è infinito, infinito più infinito è infinito. Ma Cantor dimostrò che i numeri reali sono un infinito più grande di quello dei numeri interi.",
      [
       ("Passo 1 — Un ospite in più",
        "Stanze numerate 1, 2, 3, ... all'infinito, tutte occupate. Arriva un cliente. Il direttore chiede a ogni ospite di spostarsi nella stanza successiva: chi è nella 1 va nella 2, chi è nella 2 nella 3, e così via. Nessuno resta fuori, perché non c'è un'ultima stanza. La stanza 1 è libera. Infinito più uno fa infinito."),
       ("Passo 2 — Infiniti ospiti in più",
        "Arriva un autobus con infiniti passeggeri. Il direttore sposta ogni ospite nella stanza con numero doppio: da 1 a 2, da 2 a 4, da 3 a 6. Ora tutte le stanze pari sono occupate e tutte le stanze impari, infinite, sono libere. I nuovi si sistemano lì. Infinito più infinito fa ancora infinito. È il motivo per cui i numeri pari sono 'tanti quanti' tutti i numeri, anche se sembrano la metà."),
       ("Passo 3 — L'idea di Cantor",
        "Due insiemi hanno la stessa grandezza se si possono accoppiare uno a uno senza avanzi. Interi, pari, frazioni: si possono tutti mettere in fila e accoppiare con 1, 2, 3, ... Sono infiniti 'numerabili'. Georg Cantor, alla fine dell'Ottocento, si chiese se valesse per tutti gli infiniti. La risposta gli costò l'ostilità dei colleghi."),
       ("Passo 4 — Un infinito più grande",
        "Prova a mettere in fila tutti i numeri tra 0 e 1, con infiniti decimali. Cantor mostrò che qualunque lista tu faccia, si può costruire un numero che non c'è: basta cambiare la prima cifra del primo, la seconda del secondo, e così via. Il nuovo numero differisce da ognuno della lista. I numeri reali non stanno nell'albergo: sono un infinito più grande. E ce ne sono infiniti, di infiniti, uno più grande dell'altro."),
      ]),
    L("curiosita", "v5-lez-numeri-primi",
      "I numeri primi: perché proteggono la tua carta di credito", ["numeri primi"],
      "2, 3, 5, 7, 11, 13. Numeri che si dividono solo per 1 e per sé stessi. Sembrano un gioco da matematici, e invece ogni acquisto online si regge su una loro proprietà.",
      "Capire cosa sono i numeri primi, perché sono i mattoni dell'aritmetica e come la difficoltà di scomporre numeri grandi protegge le comunicazioni.",
      "Ogni numero intero si scompone in modo unico in primi. Moltiplicare due primi enormi è facile; ritrovarli dal prodotto è praticamente impossibile con i computer attuali. Su questa asimmetria si basa la crittografia che cifra pagamenti e messaggi.",
      [
       ("Passo 1 — Gli atomi dei numeri",
        "Un numero primo ha solo due divisori: 1 e sé stesso. Tutti gli altri, i composti, si ottengono moltiplicando primi: 12 è 2 per 2 per 3, e non c'è altro modo. È il teorema fondamentale dell'aritmetica: i primi sono gli atomi con cui è costruito ogni numero, e la scomposizione è unica come una formula chimica."),
       ("Passo 2 — Infiniti e imprevedibili",
        "Euclide dimostrò 2.300 anni fa che i primi non finiscono mai: se prendi tutti quelli che conosci, li moltiplichi e aggiungi 1, ottieni un numero che nessuno di loro divide, quindi ce n'è almeno un altro. Ma non esiste una formula per trovarli: si diradano lentamente e compaiono in modo irregolare. Il più grande noto ha oltre 41 milioni di cifre."),
       ("Passo 3 — Facile in un senso, impossibile nell'altro",
        "Moltiplicare due primi di 300 cifre ciascuno richiede a un computer una frazione di secondo. Fare il contrario, dato il prodotto di 600 cifre, ritrovare i due primi, richiederebbe con i metodi noti più tempo dell'età dell'universo. Questa asimmetria è una porta che si chiude facilmente e non si riapre senza chiave."),
       ("Passo 4 — La chiave nella tua tasca",
        "Il sistema RSA, del 1977, funziona così: il prodotto dei due primi è la chiave pubblica, che chiunque può usare per cifrare un messaggio a te. I due primi, che solo tu conosci, sono la chiave privata per decifrarlo. Ogni volta che vedi il lucchetto nel browser, due numeri primi stanno lavorando. I computer quantistici potrebbero un giorno scomporre in fretta: per questo si stanno già progettando cifrari nuovi."),
      ]),

    # ------------------------------ ECONOMIA ------------------------------
    L("economia", "v5-lez-fondo-emergenza",
      "Il fondo di emergenza: costruirlo in 4 passi anche con poco", ["fondo di emergenza"],
      "La lavatrice si rompe, l'auto non parte, il contratto non viene rinnovato. Non è se succederà, è quando. Il fondo di emergenza è ciò che trasforma una crisi in un fastidio.",
      "Capire quanto serve nel fondo di emergenza, dove tenerlo e come costruirlo con versamenti automatici.",
      "Obiettivo: 3-6 mesi di spese essenziali, su un conto separato, liquido e non investito. Si comincia con un primo traguardo di 1.000 euro, si automatizza il versamento il giorno dello stipendio e si usa solo per vere emergenze, ricostituendolo dopo.",
      [
       ("Passo 1 — Quanto serve",
        "Calcola le spese essenziali di un mese: affitto o mutuo, bollette, cibo, trasporti, assicurazioni. Non le uscite totali, solo quelle che non puoi tagliare. Moltiplica per 3 se hai un lavoro stabile e nessuno a carico, per 6 se sei autonomo o hai famiglia. Quel numero è l'obiettivo finale. Sembra lontano: si arriva a tappe."),
       ("Passo 2 — Il primo traguardo: 1.000 euro",
        "Il primo obiettivo non è la cifra finale, ma 1.000 euro. Copre la maggior parte degli imprevisti comuni, dal dentista alla riparazione dell'auto, ed evita di finire su carte di credito o prestiti al 10-20% di interesse. Raggiungerlo dà la prova che il sistema funziona. Vendere ciò che non usi può portarci in un mese."),
       ("Passo 3 — Dove tenerlo e come alimentarlo",
        "Su un conto separato da quello quotidiano, meglio se in un'altra banca, così non lo vedi e non lo tocchi: un conto deposito libero, che rende qualcosa ma è disponibile in un giorno. Non in azioni o fondi: l'emergenza arriva quando i mercati scendono. Imposta un bonifico automatico il giorno dello stipendio, anche 50 euro: ciò che non vedi non lo spendi."),
       ("Passo 4 — Le regole d'uso",
        "Emergenza è ciò che è necessario, imprevisto e urgente insieme: le vacanze e il telefono nuovo non lo sono. Quando lo usi, non sentirti in colpa: è esattamente il suo scopo. Poi riparti con i versamenti finché non è ricostituito. Raggiunto l'obiettivo, i versamenti automatici possono spostarsi su investimenti a lungo termine: il fondo è la base su cui costruire tutto il resto."),
      ]),
    L("economia", "v5-lez-mutuo",
      "Come funziona un mutuo: tasso, rata e il trucco degli interessi", ["mutuo"],
      "Una casa da 200.000 euro con un mutuo trentennale può costarne 320.000. Dove finiscono gli altri 120.000, e perché nei primi anni sembra di non aver ripagato nulla?",
      "Capire la struttura di un mutuo, la differenza tra tasso fisso e variabile e come leggere il piano di ammortamento.",
      "La rata è costante ma nei primi anni è quasi tutta interessi, perché si calcolano sul debito residuo ancora alto. Il tasso fisso dà certezza, il variabile segue il mercato. Accorciare la durata o rimborsare in anticipo abbatte gli interessi totali in modo sproporzionato.",
      [
       ("Passo 1 — Cosa stai comprando",
        "La banca ti presta una somma (il capitale) e tu la restituisci a rate con un compenso (l'interesse), tenendo la casa in garanzia (l'ipoteca). Tre numeri decidono tutto: capitale, tasso annuo e durata. Con 200.000 euro al 3,5% per 30 anni la rata è circa 900 euro e il totale restituito 323.000: gli interessi sono più di metà del capitale."),
       ("Passo 2 — Perché all'inizio ripaghi poco",
        "Nel piano di ammortamento alla francese, quello standard in Italia, la rata è fissa ma la sua composizione cambia. Il primo mese l'interesse si calcola su 200.000 euro: 583 euro di interessi e solo 317 di capitale. Dopo 15 anni il debito è ancora circa 125.000. Negli ultimi anni la rata è quasi tutta capitale. Chi vende casa dopo cinque anni ha pagato soprattutto interessi."),
       ("Passo 3 — Fisso o variabile",
        "Il tasso fisso resta uguale per tutta la durata: sai esattamente quanto pagherai, e paghi qualcosa in più per questa certezza. Il variabile segue un indice di mercato più uno spread della banca: parte più basso ma può salire, anche molto, come tra il 2022 e il 2023. Regola pratica: se una rata cresciuta del 30% ti metterebbe in difficoltà, scegli il fisso."),
       ("Passo 4 — Le leve che contano",
        "Ogni anno di durata in meno abbatte gli interessi: lo stesso mutuo a 20 anni costa 78.000 euro di interessi invece di 123.000, con una rata di 1.160. Un rimborso anticipato anche piccolo nei primi anni toglie capitale su cui si sarebbero calcolati decenni di interessi. Confronta le offerte con il TAEG, che include spese e assicurazioni, non con il tasso nominale. E la surroga permette di cambiare banca gratis se trovi condizioni migliori."),
      ]),
    L("economia", "v5-lez-banca-centrale",
      "Cosa fa una banca centrale (e perché i tassi ti riguardano)", ["banca centrale", "tassi"],
      "Una riunione a Francoforte, una frase del presidente, e la rata del tuo mutuo cambia, il tuo conto rende di più, i prezzi frenano. Come fa un'istituzione a muovere tutto questo?",
      "Capire il ruolo della banca centrale, cosa sono i tassi di interesse ufficiali e come le sue decisioni arrivano nella vita di tutti i giorni.",
      "La banca centrale emette la moneta e fissa il tasso a cui presta alle banche. Alzarlo rende il credito più caro, frena spese e prezzi; abbassarlo li stimola. Il suo obiettivo principale è tenere l'inflazione intorno al 2%, ed è indipendente dai governi per non stampare moneta a comando.",
      [
       ("Passo 1 — La banca delle banche",
        "La banca centrale, la BCE per l'euro, la Federal Reserve per il dollaro, non ha sportelli per i cittadini. Presta denaro alle banche commerciali e custodisce le loro riserve. È l'unica che può creare moneta dal nulla. Il tasso a cui presta alle banche è il tasso ufficiale, e da lì si propaga a tutti gli altri."),
       ("Passo 2 — La leva dei tassi",
        "Se il tasso ufficiale sale, per le banche prendere denaro costa di più e lo prestano più caro: mutui e finanziamenti si alzano, le famiglie comprano meno, le imprese investono meno, la domanda cala e i prezzi smettono di correre. Se scende, il contrario: credito facile, più spesa, più crescita, ma anche rischio di inflazione. È un freno e un acceleratore per l'intera economia."),
       ("Passo 3 — L'obiettivo: 2%",
        "Quasi tutte le banche centrali puntano a un'inflazione intorno al 2%: abbastanza bassa da non erodere i risparmi, abbastanza alta da evitare la deflazione, in cui tutti rimandano gli acquisti aspettando prezzi più bassi. Nel 2022, con inflazione oltre il 10%, la BCE ha alzato i tassi da zero a 4% in un anno: la mossa più rapida della sua storia."),
       ("Passo 4 — Perché è indipendente",
        "Un governo tentato di stampare moneta per pagare le spese produce inflazione, come l'Ungheria del 1946. Per questo le banche centrali sono per legge indipendenti dalla politica, con mandati lunghi e obiettivi fissati. Quando senti che 'la BCE ha alzato i tassi di un quarto di punto', significa: il mutuo variabile costerà di più, il conto deposito renderà di più, e qualcuno sta cercando di frenare i prezzi che paghi al supermercato."),
      ]),
    L("economia", "v5-lez-costi-nascosti",
      "Costo affondato e costo opportunità: i due errori che ti fanno perdere soldi", ["costo affondato"],
      "Finisci il film brutto perché 'ho già pagato il biglietto'. Tieni un'azione in perdita per 'recuperare'. Compri il divano perché 'costa poco'. Tre decisioni, due errori invisibili.",
      "Riconoscere il costo affondato e il costo opportunità nelle decisioni quotidiane e decidere guardando avanti invece che indietro.",
      "Il costo affondato è denaro o tempo già speso che non torna: non deve influenzare le scelte future, eppure lo fa. Il costo opportunità è ciò a cui rinunci scegliendo un'opzione: il vero prezzo di qualunque cosa. Insieme spiegano gran parte delle cattive decisioni.",
      [
       ("Passo 1 — Il biglietto già pagato",
        "Il costo affondato è ciò che hai già speso e non puoi recuperare. Razionalmente non dovrebbe contare: il biglietto è pagato sia che tu resti sia che tu esca, quindi l'unica domanda è 'preferisco altre due ore qui o altrove?'. Ma la mente odia sentire di aver sprecato, e resta. Lo stesso vale per i corsi noiosi, i progetti falliti, le relazioni finite da tempo."),
       ("Passo 2 — Riconoscerlo",
        "La frase spia è 'ho già investito troppo per smettere'. Chi tiene un'azione crollata aspettando che torni al prezzo di acquisto ragiona sul passato; il prezzo di acquisto è irrilevante per il futuro del titolo. Il test: se oggi non avessi questa cosa, la comprerei o la comincerei da zero? Se la risposta è no, continuare è solo aggiungere costo al costo."),
       ("Passo 3 — Il costo opportunità",
        "Ogni euro e ogni ora spesi in una cosa sono tolti a un'altra. Il vero costo del divano da 800 euro non è 800 euro: è ciò che quegli 800 euro avrebbero fatto altrove, per esempio in un fondo pensione dove in trent'anni sarebbero diventati 3.000. Il costo di un'ora di serie TV è l'ora di sonno, o di sport, o di lavoro che non farai. Non esistono scelte gratuite."),
       ("Passo 4 — Decidere guardando avanti",
        "Prima di una scelta, due domande. Sul passato: cosa di ciò che ho speso tornerebbe se cambiassi strada? Se niente, ignoralo. Sul futuro: qual è la migliore alternativa a cui rinuncio? Se vale di più, cambia. Le aziende migliori chiudono progetti in perdita senza rimpianti e valutano ogni investimento contro l'alternativa: puoi farlo anche con il tuo tempo."),
      ]),
    L("economia", "v5-lez-diversificare",
      "Diversificare: perché non mettere tutte le uova in un paniere (e come farlo)", ["diversificare"],
      "I dipendenti di Enron avevano i risparmi pensionistici in azioni Enron. Quando l'azienda fallì persero lavoro e pensione lo stesso giorno. Non era sfortuna: era un paniere solo.",
      "Capire il principio della diversificazione, perché riduce il rischio senza ridurre il rendimento atteso e come applicarlo con strumenti semplici.",
      "Investimenti diversi non salgono e scendono insieme: mescolandoli il risultato è più stabile a parità di rendimento medio. Si diversifica per tipo di strumento, per area geografica, per settore e nel tempo. Un fondo indicizzato globale contiene migliaia di aziende in un solo acquisto.",
      [
       ("Passo 1 — Il principio",
        "Immagina due gelaterie: una vende gelato, l'altra ombrelli. Ogni estate una guadagna e l'altra no, ma in media entrambe rendono il 10%. Possiedi solo una: alcuni anni raddoppi, altri perdi tutto. Possiedile entrambe: ogni anno guadagni circa il 10%, senza sorprese. Il rendimento medio è identico; il rischio è sparito. Questa è l'unica cosa gratis in finanza."),
       ("Passo 2 — I quattro assi",
        "Per tipo: azioni, obbligazioni, liquidità, immobili reagiscono in modo diverso agli stessi eventi. Per geografia: un'economia in crisi non trascina tutte le altre. Per settore: tecnologia, energia, sanità, beni di consumo. Nel tempo: investire una somma un po' al mese invece che tutta insieme evita di entrare tutto al momento peggiore."),
       ("Passo 3 — L'errore più comune",
        "Investire nell'azienda per cui lavori, o solo in aziende italiane, o solo in ciò che conosci. Sembra prudenza ed è concentrazione: se il settore o il paese va male, perdi stipendio e risparmi insieme. L'Italia è meno dell'1% del mercato azionario mondiale: un portafoglio tutto italiano scommette tutto su un centesimo del pianeta."),
       ("Passo 4 — Come si fa in pratica",
        "Un fondo indicizzato globale, un ETF, compra in un solo strumento migliaia di aziende di tutto il mondo, a costi dello 0,2% l'anno. Aggiungi una quota di obbligazioni in base a quanto puoi tollerare le oscillazioni: più anni hai davanti, più azioni. Versa una cifra fissa ogni mese e non guardare troppo spesso. Diversificare non ti farà diventare ricco in fretta: ti impedirà di diventare povero in un giorno."),
      ]),
]
