"""PAUSE — 10 storie categoria ARTE & DESIGN (scritte a mano, IT)."""
from story_builder import mk

IMG = [
    "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1560174038-da43ac74f01b?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1583223904441-a5cdec5c1cef?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=1200&q=80&auto=format&fit=crop",
]

STORIES = [
    mk("arte", "arte-mona-lisa",
       "Perché la Gioconda è il quadro più famoso al mondo?",
       ["Gioconda", "famosa"],
       "Un piccolo ritratto dietro un vetro blindato, circondato ogni giorno da folle enormi. Ma cosa rende la Monna Lisa così speciale?",
       "La Gioconda è celebre per la tecnica rivoluzionaria di Leonardo, ma la sua fama planetaria nacque soprattutto da un furto clamoroso nel 1911.",
       IMG[0],
       [
        ("Un ritratto rivoluzionario",
         "Quando Leonardo la dipinse, intorno al 1503, i ritratti erano rigidi e di profilo. Lui scelse una posa di tre quarti, uno sguardo diretto verso chi guarda e un sorriso ambiguo. Usò la tecnica dello sfumato: contorni sfocati, passaggi morbidi tra luce e ombra, senza linee nette. Il risultato è un volto che sembra vivo, quasi in movimento."),
        ("Il mistero del sorriso",
         "Quel sorriso appare diverso a seconda di dove posi lo sguardo: sembra più marcato se guardi gli occhi, più tenue se fissi la bocca. È un effetto legato a come l'occhio umano percepisce i dettagli al centro e ai lati della vista. Leonardo, studioso di ottica e anatomia, sfruttò questo fenomeno per creare un'espressione che cambia mentre la osservi."),
        ("Il furto che la rese leggendaria",
         "Per secoli fu ammirata dagli esperti, ma non era un'icona di massa. Tutto cambiò nel 1911, quando un dipendente del Louvre la rubò nascondendola sotto il cappotto. Per due anni i giornali di tutto il mondo ne parlarono, la sua immagine fu ovunque. Quando tornò al museo, era ormai la donna più cercata del pianeta."),
        ("Il potere della riproduzione",
         "Nel Novecento l'immagine della Gioconda fu riprodotta ovunque: pubblicità, parodie, opere d'arte. Artisti come Duchamp e Warhol la reinterpretarono. Ogni copia e ogni scherzo aumentavano la sua notorietà, in un circolo che si autoalimenta: è famosa perché è famosa. La fama, a un certo punto, diventa una forza indipendente dall'opera stessa."),
        ("Il valore dell'originale",
         "Oggi esistono milioni di riproduzioni perfette, eppure le folle vogliono vedere \"quella\" tavola. È il fascino dell'autenticità: sapere di essere davanti all'oggetto toccato da Leonardo. L'aura dell'originale, diceva il filosofo Walter Benjamin, non si trasferisce nelle copie. È il motivo per cui viaggiamo per vedere di persona ciò che potremmo guardare in foto."),
        ("Cosa portarti a casa",
         "La Gioconda è capolavoro e fenomeno mediatico insieme. La sua grandezza artistica è reale, ma la fama planetaria nasce da una storia fatta di furti, riproduzioni e curiosità collettiva. Ci ricorda che il valore di un'opera non dipende solo dalla tela, ma anche dalle storie che le si costruiscono attorno."),
       ]),

    mk("arte", "arte-golden-ratio",
       "La sezione aurea: il numero della bellezza?",
       ["sezione", "aurea"],
       "Un numero, 1,618, che ricorre nei girasoli, nelle conchiglie e in innumerevoli opere d'arte. È la formula segreta della bellezza o solo un mito affascinante?",
       "La sezione aurea è una proporzione presente in natura e usata nell'arte: piacevole all'occhio, ma il suo ruolo come 'segreto della bellezza' è in parte leggenda.",
       IMG[1],
       [
        ("Cos'è la sezione aurea",
         "La sezione aurea è una proporzione particolare: dividi una linea in due parti tali che il rapporto tra il tutto e la parte grande sia uguale a quello tra la parte grande e quella piccola. Il risultato è un numero irrazionale, circa 1,618, indicato con la lettera greca phi. Ha proprietà matematiche affascinanti che intrigano gli studiosi da millenni."),
        ("La spirale in natura",
         "Legata alla sezione aurea c'è la successione di Fibonacci, dove ogni numero è la somma dei due precedenti. Questi numeri compaiono nella disposizione dei semi di girasole, nelle squame delle pigne, nelle spirali delle conchiglie. Non è misticismo: è il modo più efficiente per impacchettare elementi in crescita senza sprechi di spazio."),
        ("L'uso nell'arte",
         "Molti artisti e architetti hanno usato proporzioni vicine a phi per organizzare le loro opere, dal Partenone ad alcune composizioni rinascimentali. L'idea è che rettangoli e divisioni basati sulla sezione aurea risultino armoniosi all'occhio. Il rettangolo aureo, in particolare, è considerato equilibrato e piacevole, né troppo quadrato né troppo allungato."),
        ("Mito o realtà?",
         "Attenzione però: molti presunti usi della sezione aurea nell'arte sono esagerazioni o sovrainterpretazioni fatte a posteriori. Con abbastanza fantasia, si possono \"trovare\" rettangoli aurei quasi ovunque. Diversi capolavori attribuiti a phi in realtà seguono proporzioni diverse. Il fascino del numero ha alimentato tante leggende quanti fatti concreti."),
        ("Perché ci piace",
         "Esperimenti sulle preferenze estetiche danno risultati contrastanti: alcune persone prediligono proporzioni vicine all'aureo, altre no. La bellezza dipende molto da cultura, contesto e abitudine. Probabilmente la sezione aurea è una delle tante proporzioni gradevoli, non l'unica formula magica. Ma la sua ricorrenza in natura resta genuinamente sorprendente."),
        ("Cosa portarti a casa",
         "La sezione aurea è reale in matematica e in natura, meno certa come chiave universale della bellezza. Vale la pena conoscerla per l'eleganza dei suoi numeri, senza cadere nel mito che spieghi ogni capolavoro. A volte la vera meraviglia è proprio nel confine tra scienza rigorosa e leggenda affascinante."),
       ]),

    mk("arte", "arte-color-psychology",
       "Perché i colori ci fanno provare emozioni?",
       ["colori", "emozioni"],
       "Il rosso accende, il blu calma, il giallo mette allegria. I colori parlano una lingua che sentiamo prima ancora di capirla. Ma perché?",
       "I colori influenzano emozioni e comportamenti attraverso biologia e cultura: reazioni istintive si mescolano a significati appresi, diversi da società a società.",
       IMG[2],
       [
        ("Colore è luce, non materia",
         "Il colore non è una proprietà fissa degli oggetti: è il modo in cui il cervello interpreta le diverse lunghezze d'onda della luce riflessa. Una mela è \"rossa\" perché assorbe quasi tutte le onde tranne quelle rosse, che rimbalzano verso i tuoi occhi. Il colore, in un certo senso, esiste dentro di noi più che fuori."),
        ("Reazioni istintive",
         "Alcune risposte ai colori sembrano biologiche. Il rosso attira l'attenzione e può accelerare leggermente il battito: è il colore del sangue e del pericolo, utile da notare in fretta. I toni blu e verdi, associati a cielo e vegetazione, tendono a rilassare. Sono legami antichi, radicati nella nostra storia evolutiva."),
        ("Il peso della cultura",
         "Ma gran parte del significato dei colori è appreso e varia moltissimo. In Occidente il bianco è purezza e matrimonio; in molte culture orientali è il colore del lutto. Il rosso è fortuna in Cina e pericolo altrove. Non esiste un dizionario universale dei colori: ogni società scrive il proprio nel corso della sua storia."),
        ("Colori e marketing",
         "Le aziende scelgono i colori con estrema cura. Il rosso e il giallo stimolano appetito e urgenza, usati spesso nel fast food. Il blu comunica affidabilità, per questo domina banche e tecnologia. Non è una scienza esatta, ma decenni di test hanno mostrato che il colore giusto può cambiare come percepiamo un prodotto."),
        ("Colori e spazi",
         "Anche gli ambienti usano i colori per influenzarci. Pareti chiare fanno sembrare le stanze più grandi e luminose; toni caldi rendono un locale accogliente; il verde negli ospedali punta a rassicurare. La luce e il colore di uno spazio possono cambiare l'umore di chi lo abita, spesso senza che ce ne accorgiamo."),
        ("Cosa portarti a casa",
         "I colori ci parlano con una doppia voce: quella istintiva della biologia e quella appresa della cultura. Per questo la stessa tinta può calmare o allarmare a seconda di chi la guarda e dove. Notare come i colori ti fanno sentire è un piccolo esercizio di consapevolezza sul mondo che ti circonda."),
       ]),

    mk("arte", "arte-why-modern-art",
       "Perché l'arte moderna a volte sembra 'roba che potrei fare anch'io'?",
       ["arte", "moderna"],
       "Una tela con un punto, un orinatoio in un museo, una banana attaccata al muro. Provocazione, truffa o qualcosa di più profondo?",
       "L'arte moderna sposta il valore dal 'saper fare' all'idea: capirla richiede conoscere il contesto e le domande che pone, non solo la tecnica visibile.",
       IMG[3],
       [
        ("L'arte cambia domanda",
         "Per secoli l'arte ha cercato di rappresentare fedelmente la realtà: più era realistica, più era brava. Ma con l'invenzione della fotografia, questo compito passò alla macchina. Gli artisti si chiesero allora: se non serve più copiare il mondo, a cosa serve l'arte? La risposta ha rivoluzionato tutto ciò che veniva dopo."),
        ("Dal fare all'idea",
         "L'arte moderna e contemporanea spesso sposta il valore dalla tecnica all'idea. Non conta più solo quanto è difficile realizzare l'opera, ma quale pensiero, provocazione o domanda mette in moto. L'orinatoio esposto da Duchamp nel 1917 non era bello: era una sfida al concetto stesso di \"cosa può essere arte\"."),
        ("Il ruolo del contesto",
         "Un oggetto qualunque, messo in un museo e firmato da un artista, cambia significato. Il contesto trasforma la lettura: ci invita a guardarlo con occhi diversi, a chiederci perché sia lì. Molta arte contemporanea è proprio una riflessione su questo: chi decide cosa è arte, e in base a quali regole?"),
        ("Semplice non vuol dire facile",
         "\"Potevo farlo anch'io\" è la reazione più comune. Ma spesso il punto non è la difficoltà manuale: è essere stati i primi a pensarlo, in quel momento storico, con quel significato. Dopo che qualcuno ha aperto una strada sembra ovvia; prima non lo era affatto. L'originalità dell'intuizione è essa stessa un valore."),
        ("Il mercato e il valore",
         "C'è però anche un lato scomodo: il mercato dell'arte muove cifre enormi e a volte gonfia i prezzi per ragioni finanziarie e di prestigio, più che artistiche. Non tutto ciò che è costoso è profondo, e non tutto ciò che è provocatorio ha qualcosa da dire. Un pizzico di sano scetticismo è legittimo."),
        ("Cosa portarti a casa",
         "L'arte moderna può irritare, e va bene così: spesso vuole proprio farlo. Prima di liquidarla, però, vale la pena chiedersi quale domanda sta ponendo. A volte scoprirai un'idea potente; altre volte, solo furbizia. Imparare a distinguere è già un modo di guardare l'arte con occhi più maturi."),
       ]),

    mk("arte", "arte-perspective",
       "La prospettiva: come si dipinge la profondità sul piatto?",
       ["prospettiva", "profondità"],
       "Un quadro è una superficie piatta, eppure ci sembra di poterci entrare dentro. Come hanno imparato gli artisti a ingannare così bene i nostri occhi?",
       "La prospettiva è un insieme di regole geometriche, scoperte nel Rinascimento, che simulano la profondità su una superficie piana ingannando la percezione dell'occhio.",
       IMG[4],
       [
        ("Il problema del piano",
         "Un foglio o una tela hanno due dimensioni: larghezza e altezza. Il mondo reale ne ha tre, con la profondità. Per secoli i pittori faticarono a rendere questa terza dimensione: figure lontane e vicine sembravano tutte sullo stesso piano, come in molti dipinti medievali, belli ma \"schiacciati\". Serviva un metodo per organizzare lo spazio."),
        ("La scoperta del Rinascimento",
         "Nel Quattrocento, a Firenze, Brunelleschi e poi altri formalizzarono la prospettiva lineare. L'idea: le linee parallele che si allontanano sembrano convergere verso un punto all'orizzonte, il punto di fuga. Seguendo regole geometriche precise, si poteva costruire uno spazio credibile, dove gli oggetti rimpiccioliscono con la distanza in modo matematicamente esatto."),
        ("Come inganna l'occhio",
         "La prospettiva funziona perché imita ciò che fa davvero il nostro sistema visivo: gli oggetti lontani proiettano immagini più piccole sulla retina. Riproducendo questo effetto sulla tela, il cervello \"legge\" la profondità anche se sa che la superficie è piatta. È un'illusione consapevole a cui ci abbandoniamo volentieri."),
        ("Altri trucchi di profondità",
         "Oltre alle linee, gli artisti usano altri segnali: gli oggetti lontani sono più pallidi e sfumati (prospettiva aerea), i colori caldi sembrano avanzare e quelli freddi arretrare, la sovrapposizione indica cosa sta davanti. Combinando questi indizi, un bravo pittore può costruire spazi profondi e convincenti anche senza geometria rigorosa."),
        ("Rompere le regole",
         "Una volta padroneggiata, la prospettiva è stata anche volutamente infranta. Gli artisti moderni, da Cézanne a Picasso, hanno mostrato più punti di vista insieme o appiattito lo spazio di proposito, per esprimere qualcosa di nuovo. Conoscere le regole è servito proprio a superarle con consapevolezza, non per ignoranza."),
        ("Cosa portarti a casa",
         "La prospettiva è uno dei più eleganti incontri tra arte e matematica: regole geometriche al servizio dell'emozione. La prossima volta che un quadro ti sembra \"vero\", ricorda che stai guardando un'illusione costruita con cura. E che dietro quella magia c'è stata una vera e propria rivoluzione del pensiero."),
       ]),

    mk("arte", "arte-why-statues-white",
       "Le statue greche erano davvero bianche?",
       ["statue", "colori"],
       "Immaginiamo l'antichità classica come un mondo di candido marmo. E se ti dicessi che templi e statue erano in realtà dipinti con colori vivaci?",
       "Le statue greche e romane erano originariamente dipinte con colori sgargianti: il marmo bianco che ammiriamo oggi è il risultato del tempo, non l'aspetto originale.",
       IMG[0],
       [
        ("Il mito del bianco",
         "Musei, film e libri ci hanno abituato a immaginare l'antichità come un mondo di marmo immacolato. Statue bianche, templi candidi, un'estetica pura e sobria. Questa immagine ha profondamente influenzato l'idea occidentale di eleganza classica. Ma è un fraintendimento nato molto dopo, nel Rinascimento e soprattutto nel Settecento."),
        ("La verità dei pigmenti",
         "Analisi scientifiche moderne, con luce radente e raggi ultravioletti, hanno rivelato tracce di pigmenti su moltissime statue e templi antichi. Erano dipinti con rossi, blu, gialli e dorature accese. Gli occhi delle statue avevano colori, i vestiti motivi decorativi. L'antichità era un tripudio cromatico, non un elegante deserto di bianco."),
        ("Perché il colore è sparito",
         "Nel corso dei secoli i pigmenti si sono degradati per l'esposizione agli agenti atmosferici, alla luce e al terreno in cui molte opere sono rimaste sepolte. Quando furono riscoperte, il colore era quasi del tutto svanito. Restava solo il marmo, e si pensò erroneamente che fosse sempre stato così."),
        ("Un errore che è diventato gusto",
         "Studiosi settecenteschi, ammirando le statue ormai bianche, teorizzarono che il candore del marmo fosse l'ideale supremo della bellezza classica. Questa idea influenzò l'arte neoclassica e l'immaginario collettivo. A volte tracce di colore vennero persino rimosse perché considerate \"impurità\". Un fraintendimento fu così elevato a canone estetico."),
        ("Ricostruire i colori",
         "Oggi archeologi e restauratori realizzano ricostruzioni colorate delle statue antiche. All'inizio spiazzano: sembrano quasi kitsch ai nostri occhi abituati al bianco. Eppure sono più vicine all'originale di quanto lo siano le versioni immacolate. Ci costringono a rivedere un'immagine dell'antichità che credevamo certa."),
        ("Cosa portarti a casa",
         "Il candore delle statue classiche è un'illusione creata dal tempo e da un errore di interpretazione. La storia dell'arte non è fatta solo di scoperte, ma anche di fraintendimenti che diventano tradizione. Guardare le antiche statue a colori è un esercizio salutare: ci ricorda che il passato era più vivo e vario di come lo immaginiamo."),
       ]),

    mk("arte", "arte-design-everyday",
       "Perché alcuni oggetti sono facili da usare e altri no?",
       ["design", "oggetti"],
       "Una porta che spingi quando andava tirata. Un telecomando incomprensibile. Il buon design è invisibile; quello cattivo ci fa sentire stupidi ogni giorno.",
       "Il buon design comunica da solo come usare un oggetto: quando qualcosa è difficile da usare, quasi sempre la colpa è del progetto, non di chi lo usa.",
       IMG[1],
       [
        ("Il design è comunicazione",
         "Ogni oggetto ci \"dice\" come va usato, attraverso la sua forma. Una maniglia invita ad afferrare, una piastra piatta a spingere. Quando il messaggio è chiaro, non serve alcuna istruzione: capisci al volo. Il design non è solo estetica, è soprattutto comunicazione silenziosa tra l'oggetto e chi lo usa."),
        ("Le 'porte Norman'",
         "Il designer Don Norman ha dato il nome a un fenomeno diffuso: le porte che confondono. Quelle con una maniglia da tirare ma che vanno spinte, o senza indizi su quale lato aprire. Sono così comuni che il problema porta il suo nome. La lezione: se le persone sbagliano di continuo, il difetto è nel progetto."),
        ("Affordance e segnali",
         "Gli oggetti ben progettati sfruttano le \"affordance\": suggerimenti visivi su cosa puoi farci. Un pulsante sembra premibile, uno slider trascinabile. Aggiungere segnali chiari, come una piastra dove spingere o una freccia, guida senza bisogno di parole. Il bravo designer anticipa gli errori e li rende impossibili."),
        ("Il feedback conta",
         "Un buon oggetto risponde alle nostre azioni: un clic quando premi, una luce che si accende, una vibrazione. Questo feedback ci conferma che qualcosa è successo. La sua assenza genera incertezza: premo di nuovo? Ha funzionato? Molte frustrazioni quotidiane nascono da oggetti muti che non ci dicono cosa sta accadendo."),
        ("Semplicità è difficile",
         "Rendere qualcosa semplice da usare è molto più complesso che riempirlo di funzioni. Richiede togliere, non aggiungere; capire come pensano le persone reali, non gli ingegneri. I prodotti più amati spesso fanno poche cose ma benissimo, nascondendo dietro l'apparente facilità un enorme lavoro di progettazione."),
        ("Cosa portarti a casa",
         "La prossima volta che sbagli con una porta o un telecomando, non sentirti stupido: probabilmente è mal progettato. Il buon design lavora per te, in silenzio, rendendo naturale ciò che è complesso. È una forma di rispetto per chi userà l'oggetto, e si vede proprio quando non si nota."),
       ]),

    mk("arte", "arte-street-art",
       "Come i graffiti sono diventati arte da milioni?",
       ["street", "art"],
       "Da atto vandalico perseguito dalla legge a opere battute all'asta per cifre da capogiro. La street art ha ribaltato ogni regola del mondo dell'arte.",
       "La street art è passata da illegalità a fenomeno culturale globale: ha portato l'arte fuori dai musei, ma solleva domande su autenticità e mercato.",
       IMG[2],
       [
        ("Le radici ribelli",
         "La moderna street art nasce nelle città degli anni '70, tra i graffiti dei quartieri di New York. Era espressione di comunità spesso ai margini, un modo per lasciare un segno e dire \"io esisto\". Nata come atto illegale e anonimo, aveva un carattere ribelle e di protesta profondamente legato al territorio urbano."),
        ("Dal muro alla galleria",
         "Col tempo alcuni artisti di strada hanno raggiunto fama mondiale. Le loro opere, un tempo cancellate dalle autorità, hanno iniziato a essere fotografate, protette, persino staccate dai muri e vendute. Un'arte nata per essere gratuita e per tutti è entrata nel circuito del mercato, con un cortocircuito che fa ancora discutere."),
        ("Il caso dell'anonimato",
         "Alcuni tra i più celebri street artist mantengono l'anonimato. Questo mistero alimenta il mito e, paradossalmente, il valore commerciale delle opere. L'identità nascosta diventa parte del brand. È una delle tante contraddizioni: un movimento anti-sistema che finisce per usare le logiche del sistema che criticava."),
        ("Effimera per natura",
         "La street art è fatta per vivere all'aperto, esposta a pioggia, smog e cancellazioni. Questa fragilità è parte del suo senso: è arte del momento, del luogo. Congelarla in una galleria climatizzata ne tradisce un po' lo spirito. Alcuni artisti hanno persino autodistrutto le proprie opere per protestare contro la loro mercificazione."),
        ("Città come musei",
         "Oggi molte città commissionano murales per riqualificare quartieri e attrarre turismo. L'arte urbana è diventata strumento di rigenerazione e identità locale. C'è chi teme che questo la addomestichi, trasformando la ribellione in decorazione. Ma è innegabile che abbia portato l'arte nella vita quotidiana di milioni di persone."),
        ("Cosa portarti a casa",
         "La street art racconta come qualcosa considerato vandalismo possa diventare cultura celebrata, con tutte le contraddizioni del caso. Ci ricorda che i confini dell'arte sono mobili e continuamente ridiscussi. E che, a volte, i muri di una città dicono di noi più di tanti quadri appesi nei musei."),
       ]),

    mk("arte", "arte-music-emotion",
       "Perché la musica ci commuove così tanto?",
       ["musica", "emozione"],
       "Poche note e ci vengono i brividi, gli occhi lucidi, la pelle d'oca. Suoni organizzati nel tempo che toccano corde profonde dentro di noi. Ma come?",
       "La musica agisce su cervello ed emozioni tramite ritmo, aspettative e memoria: la nostra mente prevede i suoni e reagisce quando vengono confermati o sorpresi.",
       IMG[3],
       [
        ("Suono organizzato nel tempo",
         "La musica è, alla base, suono organizzato nel tempo: altezze, ritmi e timbri disposti secondo schemi. Non ha un significato letterale come le parole, eppure comunica emozioni potenti. Questa capacità di muoverci senza \"dire\" nulla di preciso è uno dei suoi misteri più affascinanti e universali, presente in ogni cultura umana conosciuta."),
        ("Il cervello prevede",
         "Ascoltando musica, il cervello anticipa continuamente cosa verrà dopo, basandosi su schemi appresi. Quando una melodia va dove ci aspettiamo, proviamo appagamento; quando ci sorprende con una nota inattesa, scatta una scarica emotiva. Il gioco tra aspettativa e sorpresa è alla radice di molti brividi musicali."),
        ("Ritmo e corpo",
         "Il ritmo ci coinvolge fisicamente: tendiamo a muoverci, battere il piede, sincronizzarci. Questo legame tra suono e movimento è antichissimo e ci unisce agli altri. Ballare o cantare insieme rilascia sostanze legate al piacere e al legame sociale. La musica è probabilmente nata anche come collante di gruppo, prima ancora che come intrattenimento."),
        ("Il potere della memoria",
         "Una canzone può riportarci di colpo a un momento preciso della vita: un amore, un viaggio, una perdita. La musica si lega fortemente ai ricordi e alle emozioni provate mentre l'ascoltavamo. Per questo alcune melodie ci commuovono non solo per come suonano, ma per tutto ciò che portano con sé nella nostra storia personale."),
        ("Cultura e apprendimento",
         "Non tutte le emozioni musicali sono universali: molto dipende da ciò a cui siamo abituati. Una scala che suona triste per noi può risultare neutra o allegra in un'altra tradizione. Impariamo fin da piccoli il \"linguaggio\" musicale della nostra cultura, e quello plasma le nostre reazioni emotive più di quanto crediamo."),
        ("Cosa portarti a casa",
         "La musica ci commuove perché intreccia biologia, aspettativa, corpo, memoria e cultura in un'unica esperienza. È insieme profondamente personale e universalmente umana. Non c'è nulla di irrazionale nei brividi che ci regala: sono la traccia udibile di come la mente e il cuore lavorano insieme."),
       ]),

    mk("arte", "arte-why-photos-good",
       "Cosa rende bella una fotografia?",
       ["fotografia", "composizione"],
       "Miliardi di foto scattate ogni giorno, ma solo alcune ci fermano davvero. Non è (solo) questione di attrezzatura: è questione di sguardo.",
       "Una bella foto nasce da composizione, luce e istante scelto: non conta la macchina costosa, ma l'occhio di chi decide cosa includere e quando scattare.",
       IMG[4],
       [
        ("Non è la macchina",
         "Si pensa spesso che servano attrezzature costose per belle foto. In realtà il fattore decisivo è chi guarda attraverso l'obiettivo. Un fotografo esperto con un telefono batte un principiante con una macchina professionale. La tecnologia aiuta, ma la differenza la fanno lo sguardo, la scelta e il tempismo di chi scatta."),
        ("La luce è tutto",
         "\"Fotografia\" significa letteralmente \"scrivere con la luce\". La qualità e la direzione della luce trasformano una scena: la luce morbida dell'alba o del tramonto (la \"golden hour\") è amata perché scolpisce i volti e crea atmosfera. La luce dura di mezzogiorno appiattisce e crea ombre nette. Imparare a vedere la luce è il primo passo."),
        ("La regola dei terzi",
         "Una linea guida classica della composizione: immagina la scena divisa da due righe orizzontali e due verticali, come una griglia. Posizionare il soggetto lungo queste linee o nei loro incroci crea immagini più dinamiche del semplice centro. Non è una legge, ma un punto di partenza che dà equilibrio senza rigidità."),
        ("Cosa lasciare fuori",
         "Fotografare è tanto includere quanto escludere. Spesso una foto migliora togliendo il superfluo: avvicinarsi, cambiare angolo, eliminare elementi di disturbo sullo sfondo. Il bordo dell'inquadratura è una scelta creativa potente. Decidere cosa lasciare fuori concentra l'attenzione su ciò che conta davvero."),
        ("L'istante decisivo",
         "Il fotografo Cartier-Bresson parlava di \"istante decisivo\": quel momento in cui gli elementi di una scena si allineano perfettamente. Un gesto, uno sguardo, una geometria che durano una frazione di secondo. Saper anticipare e cogliere quell'attimo distingue lo scatto memorabile da quello banale. È pazienza e intuito insieme."),
        ("Cosa portarti a casa",
         "Una bella foto è una decisione, non un caso: dove metterti, quando scattare, cosa includere. Sono scelte che chiunque può allenare, telefono in mano. La prossima volta non pensare all'attrezzatura: pensa alla luce, alla composizione e all'istante. Il resto è solo uno strumento al servizio del tuo sguardo."),
       ]),
]
