"""PAUSE — 10 storie categoria ECONOMIA & DENARO (scritte a mano, IT)."""
from story_builder import mk

IMG = [
    "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?w=1200&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1494212088344-91b18d9d4c11?w=1200&q=80&auto=format&fit=crop",
]

STORIES = [
    mk("economia", "eco-why-money-value",
       "Perché il denaro ha valore se è solo carta?",
       ["denaro", "valore"],
       "Una banconota è un pezzo di carta stampata. Eppure ci compri il pane, un viaggio, una casa. Da dove nasce davvero quel valore?",
       "Il denaro vale perché ci fidiamo tutti insieme che valga: è la fiducia condivisa, non l'oro, a reggere le monete moderne.",
       IMG[0],
       [
        ("Prima del denaro c'era il baratto",
         "Per millenni gli esseri umani si sono scambiati beni direttamente: un sacco di grano per una pecora, una giara d'olio per un attrezzo. Il problema è la \"doppia coincidenza dei bisogni\": devo trovare qualcuno che voglia esattamente ciò che ho e che abbia esattamente ciò che voglio. Nelle società complesse questo diventa impossibile. Serviva un intermediario universale che tutti accettassero."),
        ("La nascita di un intermediario",
         "Conchiglie, sale, bestiame, metalli preziosi: molte cose hanno fatto da denaro nella storia. Le monete di metallo si affermarono perché erano durevoli, divisibili e difficili da falsificare. L'oro e l'argento avevano un valore \"intrinseco\", ma anche un limite: erano pesanti e scarsi. La carta nacque come promessa: un biglietto che valeva l'oro depositato in una banca."),
        ("Il denaro oggi è pura fiducia",
         "Dal 1971 le principali valute non sono più legate all'oro: sono \"fiat\", cioè valgono perché lo Stato lo decreta e perché tutti le accettano. Una banconota da 50 euro non è coperta da metallo prezioso in un caveau. Vale perché sai che il tuo panettiere la prenderà, e lui sa che il suo fornitore la prenderà. È una catena di fiducia che si autoalimenta."),
        ("Perché la fiducia può crollare",
         "Quando la fiducia salta, il denaro perde valore in fretta. È successo in Germania nel 1923 e nello Zimbabwe negli anni 2000: i prezzi raddoppiavano in poche ore e servivano carriole di banconote per comprare il pane. Questa è l'iperinflazione. Dimostra che il valore del denaro non è nella carta, ma nella stabilità delle istituzioni che lo garantiscono."),
        ("Il denaro digitale",
         "Oggi la maggior parte del denaro non esiste nemmeno in forma fisica: è cifre su server delle banche. Quando ricevi lo stipendio, nessuno sposta banconote: cambiano solo dei numeri in un database. Le criptovalute hanno spinto l'idea oltre, provando a creare fiducia senza uno Stato, tramite la matematica e reti di computer. Ma il principio resta lo stesso: vale ciò in cui crediamo insieme."),
        ("Cosa portarti a casa",
         "Il denaro è una delle invenzioni sociali più potenti di sempre: un accordo collettivo che ci permette di collaborare tra sconosciuti. Capirlo cambia il modo in cui lo guardi: non è una cosa magica né un fine in sé, ma uno strumento di fiducia. E come ogni fiducia, va custodito, perché è più fragile di quanto sembri."),
       ]),

    mk("economia", "eco-compound-interest",
       "L'interesse composto: l'ottava meraviglia?",
       ["interesse", "composto"],
       "Si dice che Einstein lo chiamasse la forza più potente dell'universo. Piccole somme che, col tempo, diventano montagne di denaro.",
       "L'interesse composto fa crescere i risparmi in modo esponenziale: gli interessi generano altri interessi, e il tempo conta più della cifra iniziale.",
       IMG[1],
       [
        ("Interesse semplice vs composto",
         "Con l'interesse semplice guadagni ogni anno una percentuale solo sul capitale iniziale. Con l'interesse composto, invece, gli interessi si aggiungono al capitale e l'anno dopo generano a loro volta interessi. È la differenza tra una crescita lineare e una crescita che accelera su sé stessa. All'inizio la differenza è minima, ma con gli anni diventa enorme."),
        ("Il potere del tempo",
         "Immagina 1.000 euro al 7% annuo. Dopo 10 anni diventano circa 2.000, dopo 20 anni circa 4.000, dopo 30 anni quasi 8.000. Non hai aggiunto nulla: è il tempo che lavora. Questo è il motivo per cui iniziare a risparmiare a 25 anni invece che a 40 può valere più del doppio, a parità di somme versate."),
        ("La regola del 72",
         "C'è un trucco mentale per capire quanto tempo serve a raddoppiare un capitale: dividi 72 per il tasso di interesse. Al 6% ci vogliono circa 12 anni (72÷6), al 9% circa 8 anni. È un'approssimazione sorprendentemente precisa che ti fa intuire al volo la forza di un rendimento senza calcolatrice."),
        ("Funziona anche al contrario",
         "L'interesse composto è un amico quando investi, ma un nemico feroce quando hai debiti. Le carte di credito e i prestiti al consumo applicano lo stesso meccanismo: il debito non pagato genera interessi che si sommano al debito, che genera altri interessi. È così che piccole somme non saldate possono gonfiarsi fino a diventare ingestibili."),
        ("Perché è difficile percepirlo",
         "Il nostro cervello ragiona in modo lineare: fatichiamo a immaginare curve che esplodono verso l'alto. Per questo l'interesse composto sembra deludente nei primi anni e poi, all'improvviso, incredibile. Chi molla presto perde proprio la parte più ripida della curva, quella che arriva solo con la pazienza."),
        ("Cosa portarti a casa",
         "Non serve essere ricchi per sfruttarlo: serve tempo e costanza. Anche piccoli importi versati regolarmente, lasciati crescere per decenni, possono trasformarsi in una somma importante. Il vero segreto non è trovare il rendimento perfetto, ma iniziare presto e non interrompere il processo."),
       ]),

    mk("economia", "eco-inflation",
       "Cos'è l'inflazione e perché i prezzi salgono?",
       ["inflazione", "prezzi"],
       "Con 10 euro dei tuoi nonni si comprava molto più di oggi. Non è nostalgia: è inflazione, e cambia il valore stesso del denaro nel tempo.",
       "L'inflazione è l'aumento generale dei prezzi nel tempo: riduce il potere d'acquisto del denaro, spesso per squilibri tra domanda, offerta e quantità di moneta.",
       IMG[2],
       [
        ("Cosa significa davvero",
         "L'inflazione misura di quanto crescono, in media, i prezzi di beni e servizi in un anno. Se l'inflazione è al 3%, ciò che oggi costa 100 euro l'anno prossimo costerà circa 103. Non riguarda un singolo prodotto, ma il paniere complessivo della spesa tipica di una famiglia. Un'inflazione bassa e stabile è considerata normale e persino sana."),
        ("Perché i prezzi salgono",
         "Le cause principali sono due. La prima: la domanda cresce più dell'offerta, quindi i venditori possono alzare i prezzi. La seconda: aumentano i costi di produzione (energia, materie prime, salari) e le aziende li scaricano sul prezzo finale. C'è poi un terzo fattore: se in circolazione c'è troppa moneta rispetto ai beni disponibili, ogni euro vale meno."),
        ("Il nemico del risparmio fermo",
         "L'inflazione erode silenziosamente i soldi lasciati fermi. Se tieni 1.000 euro sotto il materasso e l'inflazione è al 4%, dopo un anno quei 1.000 euro comprano come 960. Non sono spariti, ma valgono meno. È il motivo per cui tenere tutto liquido, senza farlo fruttare, è una perdita nascosta ma reale."),
        ("Chi ci guadagna e chi ci perde",
         "L'inflazione penalizza chi ha risparmi liquidi e chi ha redditi fissi che non si adeguano. Favorisce invece chi ha debiti a tasso fisso: restituisce la stessa cifra nominale, ma che vale meno in termini reali. Per questo governi molto indebitati a volte non temono un po' di inflazione: alleggerisce il peso reale del loro debito."),
        ("Il ruolo delle banche centrali",
         "Le banche centrali, come la BCE, hanno il compito di tenere l'inflazione vicino a un obiettivo (di solito il 2%). Il loro strumento principale sono i tassi di interesse: alzandoli, rendono il denaro più caro, frenano la spesa e raffreddano i prezzi. Abbassandoli, stimolano l'economia. È un equilibrio delicato tra crescita e stabilità."),
        ("Cosa portarti a casa",
         "L'inflazione non è di per sé un male: il problema è quando è troppo alta o imprevedibile. Capirla ti aiuta a fare scelte migliori, dal chiedere adeguamenti di stipendio al non lasciare tutti i risparmi fermi. Il denaro non è statico: il suo valore cambia, e l'inflazione è la misura di quel cambiamento."),
       ]),

    mk("economia", "eco-supply-demand",
       "Domanda e offerta: la legge invisibile dei prezzi",
       ["domanda", "offerta"],
       "Perché l'acqua costa pochissimo e un diamante una fortuna, anche se dell'acqua non puoi fare a meno? La risposta è un equilibrio invisibile.",
       "Il prezzo nasce dall'incontro tra quanto un bene è desiderato (domanda) e quanto è disponibile (offerta): la scarsità, non l'utilità, decide spesso il valore.",
       IMG[3],
       [
        ("Il paradosso dell'acqua e del diamante",
         "L'acqua è essenziale alla vita, i diamanti no. Eppure i diamanti costano infinitamente di più. Questo paradosso confuse gli economisti per secoli. La soluzione sta nel concetto di scarsità: l'acqua è abbondante, quindi l'ultimo litro vale poco; i diamanti sono rari, quindi ogni pietra è preziosa. Non conta l'utilità totale, ma quella dell'ultima unità disponibile."),
        ("La curva della domanda",
         "In generale, più un bene costa, meno persone lo comprano; più costa poco, più persone lo vogliono. È la legge della domanda. Ma non vale allo stesso modo per tutto: per il pane o i farmaci essenziali la domanda cambia poco col prezzo, perché non puoi rinunciarvi. Per un gelato o una vacanza, invece, un piccolo rincaro può far scappare molti clienti."),
        ("La curva dell'offerta",
         "Dal lato dei venditori vale l'opposto: più alto è il prezzo, più conviene produrre e vendere. Se il prezzo del caffè sale, più agricoltori lo coltivano. Se crolla, molti smettono. L'offerta reagisce ai prezzi, ma spesso con lentezza: piantare un albero di caffè e aspettare che produca richiede anni."),
        ("Il punto di equilibrio",
         "Il prezzo di mercato si forma dove domanda e offerta si incontrano: la quantità che i compratori vogliono a quel prezzo coincide con quella che i venditori offrono. Se il prezzo è troppo alto, restano prodotti invenduti e scende; se è troppo basso, la merce finisce e sale. È un continuo aggiustamento, come una bilancia che cerca l'assetto."),
        ("Quando l'equilibrio si rompe",
         "Eventi improvvisi spostano le curve. Una gelata distrugge i raccolti: l'offerta crolla e i prezzi schizzano. Una moda fa esplodere la domanda di un prodotto: i prezzi salgono finché la produzione non recupera. Le speculazioni e i monopoli possono distorcere ulteriormente questo gioco, tenendo i prezzi artificialmente alti o bassi."),
        ("Cosa portarti a casa",
         "Dietro ogni cartellino del prezzo c'è una negoziazione silenziosa tra milioni di scelte individuali. Nessuno decide dall'alto quanto deve costare il pane: emerge dall'incontro di chi vende e chi compra. Capire domanda e offerta significa leggere il mondo economico come un enorme sistema di segnali."),
       ]),

    mk("economia", "eco-why-taxes",
       "Perché paghiamo le tasse (e dove finiscono)?",
       ["tasse", "Stato"],
       "Ogni anno una parte di ciò che guadagniamo va allo Stato. Un peso, certo. Ma senza tasse, gran parte del mondo che diamo per scontato sparirebbe.",
       "Le tasse finanziano beni e servizi collettivi che il mercato da solo non fornirebbe: strade, sanità, scuola, giustizia e sicurezza per tutti.",
       IMG[4],
       [
        ("Cosa sono le tasse",
         "Le tasse sono contributi obbligatori che cittadini e imprese versano allo Stato. Non sono un pagamento per un servizio specifico, ma un finanziamento collettivo. In cambio, lo Stato fornisce beni e servizi che riguardano tutti. È un patto sociale antico quanto le prime civiltà: già in Mesopotamia si registravano tributi su raccolti e bestiame."),
        ("I beni pubblici",
         "Alcune cose non possono essere vendute individualmente: l'illuminazione stradale, la difesa nazionale, la giustizia. Nessuna azienda le fornirebbe perché non potrebbe far pagare chi ne beneficia. Sono i \"beni pubblici\", e le tasse esistono soprattutto per finanziarli. Senza un contributo comune, resteremmo tutti senza, anche chi sarebbe disposto a pagare."),
        ("Dove finiscono i soldi",
         "Nei Paesi europei la maggior parte del gettito va a sanità, istruzione, pensioni e assistenza sociale. Il resto finanzia infrastrutture, sicurezza, giustizia e il funzionamento dello Stato. Una quota, spesso importante, serve a pagare gli interessi sul debito pubblico accumulato negli anni. Ogni bilancio statale è una fotografia delle priorità di una società."),
        ("Progressività: chi più ha, più paga",
         "In molti sistemi le imposte sul reddito sono progressive: l'aliquota cresce col reddito. L'idea è che chi guadagna di più possa contribuire in proporzione maggiore, riducendo le disuguaglianze. È un principio dibattuto: alcuni lo considerano giusto, altri temono che scoraggi il lavoro e gli investimenti se spinto troppo in alto."),
        ("Il problema dell'evasione",
         "Quando qualcuno non paga ciò che dovrebbe, il peso ricade sugli altri o i servizi peggiorano. L'evasione fiscale erode la fiducia nel sistema: se percepiamo che molti non pagano, siamo meno disposti a farlo noi. Per questo gli Stati investono molto in controlli e trasparenza, e sempre più in strumenti digitali per tracciare i pagamenti."),
        ("Cosa portarti a casa",
         "Le tasse non sono solo un prelievo: sono il prezzo della vita in comune. La domanda vera non è \"tasse sì o no\", ma quanto e come raccoglierle e spenderle. Dietro l'insofferenza per la dichiarazione dei redditi c'è, in fondo, la macchina che tiene in piedi strade, ospedali e scuole di tutti."),
       ]),

    mk("economia", "eco-stock-market",
       "Cos'è la borsa e perché le azioni salgono e scendono?",
       ["borsa", "azioni"],
       "Numeri che lampeggiano, grafici impazziti, fortune create e distrutte in un giorno. Ma cosa succede davvero quando compri un'azione?",
       "Comprare un'azione significa possedere una minuscola fetta di un'azienda: il prezzo sale e scende in base a quanto il mercato crede nel suo futuro.",
       IMG[0],
       [
        ("Un'azione è un pezzo di azienda",
         "Quando compri un'azione, diventi comproprietario di una società, per quanto in misura piccolissima. Se l'azienda va bene e cresce, la tua fetta vale di più; se va male, vale di meno. Le aziende vendono azioni per raccogliere denaro con cui espandersi, senza doverlo chiedere in prestito. In cambio, cedono una parte della proprietà e dei profitti futuri."),
        ("Perché esiste la borsa",
         "La borsa è un mercato dove queste fette di aziende si comprano e si vendono. Serve a due cose: permette alle imprese di raccogliere capitali e permette agli investitori di rivendere le proprie azioni quando vogliono. Senza un mercato del genere, chi compra una quota resterebbe bloccato: la liquidità, cioè poter vendere facilmente, è il vero motore della borsa."),
        ("Cosa muove i prezzi",
         "Il prezzo di un'azione riflette le aspettative sul futuro dell'azienda. Buone notizie, profitti in crescita, nuovi prodotti: il prezzo tende a salire. Cattive notizie o timori: scende. Spesso conta più l'aspettativa del dato reale: se un'azienda guadagna molto ma meno del previsto, il titolo può addirittura crollare. La borsa scommette sul domani, non sull'oggi."),
        ("Il ruolo delle emozioni",
         "I mercati non sono macchine perfettamente razionali: sono fatti di persone, con paura e avidità. Nei momenti di euforia i prezzi salgono oltre il ragionevole (bolle); nei momenti di panico crollano oltre il giustificabile. Grandi crolli storici, dal 1929 al 2008, sono stati amplificati proprio da reazioni emotive collettive."),
        ("Rischio e orizzonte temporale",
         "Nel breve periodo la borsa è imprevedibile e può perdere molto in poco tempo. Nel lungo periodo, storicamente, i mercati azionari dei Paesi sviluppati hanno reso più di quasi ogni altro investimento. La regola d'oro è non investire soldi che ti servono a breve e diversificare, cioè non puntare tutto su una sola azienda."),
        ("Cosa portarti a casa",
         "La borsa non è un casinò né una macchina per arricchirsi in fretta: è un modo per partecipare alla crescita delle aziende nel tempo. Chi la tratta come una scommessa rapida spesso perde; chi la usa con pazienza e disciplina, di solito, viene premiato dagli anni."),
       ]),

    mk("economia", "eco-gdp",
       "PIL: il numero che misura la ricchezza di un Paese",
       ["PIL", "ricchezza"],
       "Sentiamo dire che il PIL cresce o cala, e sembra decidere la salute di una nazione. Ma cosa misura davvero, e cosa dimentica?",
       "Il PIL è il valore di tutti i beni e servizi prodotti in un Paese in un anno: utile per misurare l'attività economica, ma cieco su benessere e disuguaglianze.",
       IMG[1],
       [
        ("Cosa significa PIL",
         "PIL sta per Prodotto Interno Lordo: è il valore totale di tutti i beni e servizi finali prodotti dentro i confini di un Paese in un anno. Se un panettiere vende pane per 100.000 euro e un'officina ripara auto per 200.000, entrambi contribuiscono al PIL. È il termometro più usato per misurare quanto \"gira\" un'economia."),
        ("Perché lo guardano tutti",
         "Un PIL in crescita di solito significa più produzione, più posti di lavoro e più redditi. Un PIL in calo per due trimestri di fila viene chiamato recessione, e spesso porta disoccupazione e tagli. Per questo governi, imprese e mercati seguono i dati del PIL con attenzione quasi ossessiva: orientano decisioni che riguardano milioni di persone."),
        ("Come si può far crescere",
         "Il PIL cresce se aumenta la produzione: più persone che lavorano, macchine più efficienti, nuove tecnologie, oppure più consumi e investimenti. La crescita non è infinita né automatica: dipende da innovazione, istruzione, infrastrutture e stabilità. I Paesi che investono in conoscenza e ricerca tendono a crescere in modo più solido nel lungo periodo."),
        ("Cosa il PIL non vede",
         "Il PIL misura la quantità, non la qualità della vita. Non registra il lavoro domestico non pagato, il volontariato o il tempo libero. Conta come positivo anche ciò che nasce da disastri: ricostruire dopo un'alluvione fa salire il PIL. E non dice nulla su come la ricchezza è distribuita: un Paese può crescere mentre le disuguaglianze aumentano."),
        ("Le alternative",
         "Proprio per questi limiti sono nati indicatori complementari, come l'Indice di Sviluppo Umano, che considera anche salute e istruzione, o misure di benessere e felicità. Alcuni Paesi hanno iniziato a usarli accanto al PIL. L'idea non è buttare via il PIL, ma affiancarlo con numeri che raccontino meglio la vita reale delle persone."),
        ("Cosa portarti a casa",
         "Il PIL è una bussola utile ma parziale: dice quanto un Paese produce, non quanto sta bene. Confonderlo con la felicità di una nazione è un errore comune. La ricchezza vera di una società si misura anche in salute, tempo, ambiente e giustizia: cose che nessun singolo numero può catturare del tutto."),
       ]),

    mk("economia", "eco-brands-value",
       "Perché un logo può valere miliardi?",
       ["marchio", "valore"],
       "Due magliette identiche, ma una ha un piccolo simbolo cucito sul petto e costa il triplo. Il valore di un marchio è una delle magie dell'economia.",
       "Un marchio forte vale perché crea fiducia, riconoscibilità e appartenenza: le persone pagano di più per ciò che il logo promette, non solo per il prodotto.",
       IMG[2],
       [
        ("Il marchio è una promessa",
         "Un marchio non è solo un logo: è l'insieme di aspettative che associamo a un nome. Quando vedi un simbolo noto, il tuo cervello richiama in un istante ricordi, qualità percepita, status. Questa scorciatoia mentale ha un valore economico enorme: riduce l'incertezza dell'acquisto. Compri con più sicurezza qualcosa che \"conosci\", anche se non l'hai mai provato."),
        ("Perché paghiamo di più",
         "Studi di neuromarketing mostrano che lo stesso prodotto piace di più se associato a un marchio amato. Non è ingenuità: il marchio vende anche identità e appartenenza. Indossare o usare un certo brand comunica agli altri (e a noi stessi) chi pensiamo di essere. Quel sovrapprezzo è, in parte, il costo di un messaggio sociale."),
        ("Come si costruisce",
         "Un marchio forte si costruisce con anni di coerenza: qualità mantenuta, comunicazione riconoscibile, esperienze positive ripetute. La fiducia è lenta da guadagnare e rapida da perdere. Un solo scandalo può cancellare decenni di reputazione. Per questo le aziende investono cifre enormi non solo in pubblicità, ma nella cura di ogni contatto col cliente."),
        ("Il valore nei bilanci",
         "I marchi più celebri valgono, da soli, centinaia di miliardi: spesso più delle fabbriche e dei macchinari dell'azienda. Questo valore \"immateriale\" viene stimato e messo a bilancio. Quando un'azienda ne compra un'altra, gran parte del prezzo può riguardare proprio il marchio, cioè la fiducia dei clienti, non i beni fisici."),
        ("Il rischio di essere troppo forti",
         "Un marchio potentissimo porta anche fragilità. Diventa un bersaglio: contraffazioni, critiche, boicottaggi. E rischia di \"invecchiare\" se non si rinnova: molti brand storici sono scomparsi per non aver saputo cambiare col pubblico. Il valore di un marchio non è mai acquisito per sempre: va difeso e reinventato di continuo."),
        ("Cosa portarti a casa",
         "Dietro un logo che vale miliardi non c'è magia, ma psicologia e fiducia accumulata. Riconoscerlo ti rende un consumatore più consapevole: capisci quando paghi il prodotto e quando paghi la promessa. A volte quella promessa vale davvero il prezzo; altre volte, è solo un simbolo cucito sul petto."),
       ]),

    mk("economia", "eco-scarcity-choices",
       "Perché non possiamo avere tutto: la scienza delle scelte",
       ["scarsità", "scelte"],
       "Tempo, denaro, energie: tutto è limitato. L'economia, prima ancora che di soldi, parla di come scegliamo quando non possiamo avere tutto.",
       "La scarsità obbliga a scegliere, e ogni scelta ha un costo nascosto: ciò a cui rinunci. È il concetto di costo opportunità, cuore del pensiero economico.",
       IMG[3],
       [
        ("La scarsità è ovunque",
         "L'economia nasce da un fatto semplice: i desideri sono infiniti, le risorse no. Non c'è abbastanza tempo, denaro o materie prime per soddisfare tutto ciò che vorremmo. Questo vale per una persona come per un intero Paese. La scarsità non è un problema temporaneo da risolvere: è la condizione di base con cui ogni scelta economica deve fare i conti."),
        ("Ogni scelta è una rinuncia",
         "Scegliere di fare una cosa significa rinunciare a un'altra. Se passi la serata a studiare, rinunci a vedere gli amici; se compri uno smartphone nuovo, quei soldi non finiscono in un viaggio. Gli economisti chiamano \"costo opportunità\" il valore della migliore alternativa a cui rinunci. È un costo invisibile ma reale, spesso più importante del prezzo pagato."),
        ("Ragionare al margine",
         "Le decisioni raramente sono \"tutto o niente\": di solito riguardano un po' di più o un po' di meno. Vale la pena studiare un'ora in più? Produrre mille pezzi in più? Il pensiero economico confronta il beneficio aggiuntivo con il costo aggiuntivo di ogni piccola unità. Questo \"ragionare al margine\" è uno degli strumenti più potenti per decidere bene."),
        ("Gli incentivi contano",
         "Le persone rispondono agli incentivi: cambiano comportamento se cambiano costi e benefici. Un aumento del prezzo della benzina spinge a usare meno l'auto; uno sconto fa comprare di più. Molti problemi si risolvono non con divieti, ma cambiando gli incentivi. E molte politiche falliscono perché ignorano come le persone reagiranno davvero."),
        ("I costi sommersi",
         "Un errore classico è lasciarsi condizionare da soldi o tempo già spesi e irrecuperabili: i \"costi sommersi\". Finire un film noioso perché hai pagato il biglietto, o continuare un progetto fallimentare perché ci hai già investito tanto. La logica economica dice di guardare avanti: ciò che è perso è perso, conta solo cosa conviene da adesso in poi."),
        ("Cosa portarti a casa",
         "L'economia, in fondo, è la scienza delle scelte in un mondo limitato. Pensare in termini di costo opportunità, margine e incentivi non serve solo agli economisti: aiuta a decidere meglio nella vita di tutti i giorni. Non puoi avere tutto, ma puoi scegliere con più consapevolezza a cosa dire di sì."),
       ]),

    mk("economia", "eco-why-things-cost",
       "Perché lo stesso prodotto costa prezzi diversi?",
       ["prezzo", "strategia"],
       "Un volo che cambia prezzo ogni ora, un caffè che costa il doppio in aeroporto. I prezzi non sono fissi: sono strategie studiate nei minimi dettagli.",
       "Le aziende variano i prezzi in base a domanda, luogo, momento e disponibilità a pagare del cliente: è la scienza del pricing, non un caso.",
       IMG[4],
       [
        ("Il prezzo non riflette solo il costo",
         "Verrebbe da pensare che un prezzo sia il costo di produzione più un margine. In realtà, molte aziende partono dalla domanda opposta: quanto è disposto a pagare il cliente? Il costo è il pavimento minimo, ma il prezzo finale dipende molto di più dal valore percepito e dal contesto in cui avviene l'acquisto."),
        ("Prezzi dinamici",
         "Voli, hotel e biglietti cambiano prezzo in continuazione grazie ad algoritmi che leggono la domanda in tempo reale. Se molti cercano quel volo, il prezzo sale; se restano posti vuoti a ridosso della partenza, può scendere. È lo stesso principio dei taxi che costano di più sotto la pioggia: prezzo alto quando la richiesta è alta."),
        ("Segmentare i clienti",
         "Le aziende sanno che persone diverse pagherebbero cifre diverse. Così creano versioni dello stesso prodotto per far pagare a ciascuno il massimo che è disposto a spendere: la classe economica e la business, l'abbonamento base e quello premium. Sconti per studenti e anziani servono proprio a intercettare chi altrimenti non comprerebbe."),
        ("Il potere del contesto",
         "Lo stesso caffè costa poco al bar di periferia e molto in un hotel di lusso. Non cambia il caffè: cambia il contesto e ciò che sei disposto a pagare in quel momento. In aeroporto o allo stadio i prezzi salgono perché non hai alternative comode. La scarsità di scelta è un ingrediente prezioso per chi fissa i prezzi."),
        ("I trucchi psicologici",
         "9,99 invece di 10 sembra molto meno, anche se è un centesimo di differenza: il nostro cervello legge la prima cifra. Un'opzione costosa messa accanto fa sembrare le altre convenienti. Offerte \"a tempo limitato\" spingono a decidere in fretta. Questi trucchi sfruttano scorciatoie mentali che usiamo tutti senza accorgercene."),
        ("Cosa portarti a casa",
         "Il prezzo che vedi è quasi sempre una scelta strategica, non una verità oggettiva. Saperlo ti rende un compratore più sveglio: confronti, aspetti il momento giusto, non ti fai ingannare dal 9,99. Dietro ogni cartellino c'è qualcuno che ha studiato a lungo come farti dire di sì."),
       ]),
]
