"""PAUSE — Mini lezioni scritte a mano (parte B): economia, arte, geografia,
cultura, corpo umano, curiosità. 2 lezioni per categoria.
Ogni lezione insegna UN concetto in 5 passi, con obiettivo dichiarato. IT + EN.
Stessa forma di seed_lessons_a: kind='lesson', objective, 5 capitoli + summary."""
from story_builder import mk_lesson as L

LESSONS_B = [
    # ------------------------------ ECONOMIA ------------------------------
    L("economia", "lez-interesse-composto",
      "L'interesse composto: perché il tempo conta più dei soldi", ["interesse composto"],
      "Einstein lo avrebbe chiamato l'ottava meraviglia del mondo. Non è magia: è matematica che lavora mentre dormi.",
      "Capire come l'interesse composto fa crescere una somma nel tempo e perché iniziare presto batte versare tanto.",
      "L'interesse composto è interesse sull'interesse: piccoli guadagni che generano altri guadagni. Il fattore decisivo non è quanto versi, ma per quanti anni lo lasci crescere.",
      [
          ("Passo 1 — Interesse semplice vs composto",
           "Con l'interesse semplice guadagni ogni anno sempre sulla stessa cifra iniziale. Con quello composto guadagni anche sugli interessi già maturati. Metti 100 euro al 10%: dopo un anno hai 110. L'anno dopo il 10% si calcola su 110, non su 100. La differenza sembra minima all'inizio, ma cresce sempre più in fretta."),
          ("Passo 2 — La palla di neve",
           "Immagina una palla di neve che rotola giù da una collina: più diventa grande, più neve raccoglie a ogni giro. I tuoi soldi fanno lo stesso. I primi anni sono lenti e deludenti, poi la curva si impenna. Chi molla presto vede solo la parte noiosa e si perde quella interessante."),
          ("Passo 3 — La regola del 72",
           "Un trucco per stimare a mente: dividi 72 per il tasso di rendimento annuo e ottieni gli anni per raddoppiare. Al 6% servono 12 anni, al 9% circa 8. Ti serve per capire al volo se un investimento raddoppia in un tempo ragionevole o no."),
          ("Passo 4 — Il tempo batte l'importo",
           "Chi versa 100 euro al mese da 25 anni finisce quasi sempre con più soldi di chi ne versa 200 ma parte a 40 anni. Il motivo è il tempo: gli anni in più danno agli interessi lo spazio per moltiplicarsi. Iniziare presto, anche con poco, è il vantaggio più grande che esista."),
          ("Passo 5 — Funziona anche contro di te",
           "La stessa forza lavora al contrario sui debiti. Il saldo non pagato di una carta di credito genera interessi che a loro volta generano interessi, e cresce in fretta proprio come un investimento. Prima capisci il meccanismo, prima puoi metterlo dalla tua parte invece che contro."),
      ],
      en={
          "title": "Compound interest: why time matters more than money", "highlight_words": ["compound interest"],
          "hook": "Einstein supposedly called it the eighth wonder of the world. It isn't magic: it's maths working while you sleep.",
          "objective": "Understand how compound interest grows a sum over time and why starting early beats saving a lot.",
          "summary": "Compound interest is interest on interest: small gains that generate more gains. What matters most is not how much you save, but how many years you let it grow.",
          "chapters": [
              ("Step 1 — Simple vs compound", "With simple interest you earn every year on the same starting amount. With compound interest you also earn on the interest already gained. Put 100 at 10%: after a year you have 110. Next year the 10% is on 110, not 100. The gap looks tiny at first, then grows faster and faster."),
              ("Step 2 — The snowball", "Picture a snowball rolling downhill: the bigger it gets, the more snow it grabs each turn. Your money does the same. The first years are slow and disappointing, then the curve shoots up. People who quit early only see the boring part and miss the interesting one."),
              ("Step 3 — The rule of 72", "A mental shortcut: divide 72 by the annual return to get the years needed to double. At 6% it takes 12 years, at 9% about 8. Use it to judge at a glance whether an investment doubles in a reasonable time or not."),
              ("Step 4 — Time beats amount", "Someone saving 100 a month for 25 years almost always ends up with more than someone saving 200 but starting at 40. The reason is time: the extra years give the interest room to multiply. Starting early, even with little, is the biggest advantage there is."),
              ("Step 5 — It works against you too", "The same force runs in reverse on debt. An unpaid credit-card balance earns interest that itself earns interest, growing fast just like an investment. The sooner you grasp the mechanism, the sooner you can put it on your side instead of against you."),
          ],
      }),

    L("economia", "lez-inflazione",
      "L'inflazione: perché 100 euro non valgono sempre uguale", ["inflazione"],
      "Il nonno ricorda il caffè a poche lire. Non era più ricco: erano i prezzi a essere diversi. Ecco perché.",
      "Capire cos'è l'inflazione, come si misura e cosa fa al valore reale dei tuoi soldi.",
      "L'inflazione è l'aumento medio dei prezzi nel tempo: con la stessa cifra compri meno. Un po' è normale; il problema è quando corre più veloce dei tuoi redditi.",
      [
          ("Passo 1 — Cosa significa",
           "Inflazione vuol dire che, in media, le cose costano di più di prima. Non un singolo prodotto, ma un intero paniere di beni e servizi. Se l'inflazione è al 3%, ciò che l'anno scorso costava 100 euro oggi ne costa 103. I tuoi soldi non sono cambiati, ma comprano un po' meno."),
          ("Passo 2 — Come si misura",
           "Gli istituti di statistica seguono i prezzi di un paniere fisso: pane, benzina, affitto, trasporti, elettronica. Confrontano il costo di oggi con quello di un anno fa e ne ricavano una percentuale. È una media: alcuni prezzi salgono molto, altri scendono, ma il numero riassume la tendenza generale."),
          ("Passo 3 — Da dove arriva",
           "I prezzi salgono quando c'è troppa domanda rispetto ai beni disponibili, oppure quando produrre costa di più (energia, materie prime, salari). Anche stampare troppa moneta può gonfiare i prezzi: più euro in giro inseguono la stessa quantità di cose."),
          ("Passo 4 — Perché ti riguarda",
           "Se i prezzi salgono del 3% ma il tuo stipendio resta uguale, ogni anno diventi un po' più povero senza accorgertene. I risparmi fermi sul conto perdono potere d'acquisto. Per questo un'inflazione bassa e stabile è considerata sana, mentre una alta erode silenziosamente i redditi."),
          ("Passo 5 — Come proteggerti",
           "Non esiste una difesa perfetta, ma qualche principio aiuta: evitare di tenere grandi somme ferme e improduttive, negoziare adeguamenti dello stipendio, e ricordare che i debiti a tasso fisso, con l'inflazione, diventano col tempo più leggeri da ripagare. Capire il meccanismo è già metà della difesa."),
      ],
      en={
          "title": "Inflation: why 100 euros isn't always worth the same", "highlight_words": ["Inflation"],
          "hook": "Grandpa remembers coffee for pennies. He wasn't richer: prices were simply different. Here's why.",
          "objective": "Understand what inflation is, how it is measured, and what it does to the real value of your money.",
          "summary": "Inflation is the average rise in prices over time: the same amount buys less. A little is normal; the problem is when it outruns your income.",
          "chapters": [
              ("Step 1 — What it means", "Inflation means that, on average, things cost more than before. Not a single product, but a whole basket of goods and services. If inflation is 3%, what cost 100 last year costs 103 today. Your money hasn't changed, but it buys a little less."),
              ("Step 2 — How it's measured", "Statistics agencies track the prices of a fixed basket: bread, fuel, rent, transport, electronics. They compare today's cost with a year ago and derive a percentage. It's an average: some prices rise a lot, others fall, but the number sums up the overall trend."),
              ("Step 3 — Where it comes from", "Prices rise when there's too much demand for the goods available, or when producing costs more (energy, raw materials, wages). Printing too much money can also inflate prices: more euros chasing the same amount of things."),
              ("Step 4 — Why it affects you", "If prices rise 3% but your salary stays the same, each year you quietly become a bit poorer. Savings sitting idle lose purchasing power. That's why low, stable inflation is seen as healthy, while high inflation silently erodes incomes."),
              ("Step 5 — How to protect yourself", "There's no perfect defence, but a few principles help: avoid keeping large sums idle and unproductive, negotiate salary adjustments, and remember that fixed-rate debt becomes lighter to repay over time with inflation. Understanding the mechanism is already half the defence."),
          ],
      }),

    # ------------------------------ ARTE ------------------------------
    L("arte", "lez-prospettiva",
      "La prospettiva: come dare profondità a un disegno", ["prospettiva"],
      "Un foglio è piatto, eppure un disegno può sembrare profondo chilometri. Il segreto lo scoprirono nel Rinascimento.",
      "Capire il principio del punto di fuga e usare la prospettiva lineare per rendere credibile lo spazio.",
      "La prospettiva lineare crea l'illusione della profondità facendo convergere le linee parallele verso uno o più punti di fuga sull'orizzonte.",
      [
          ("Passo 1 — L'illusione della profondità",
           "I nostri occhi giudicano la distanza da alcuni indizi: le cose lontane sembrano più piccole, più sbiadite e più in alto verso l'orizzonte. Un disegno che rispetta queste regole 'inganna' il cervello e appare tridimensionale, anche se il foglio resta perfettamente piatto."),
          ("Passo 2 — La linea dell'orizzonte",
           "Prima cosa: traccia una linea orizzontale. È l'orizzonte, e corrisponde all'altezza dei tuoi occhi. Tutto ciò che è sopra questa linea lo guardi dal basso, tutto ciò che è sotto lo guardi dall'alto. Spostarla in alto o in basso cambia completamente il punto di vista della scena."),
          ("Passo 3 — Il punto di fuga",
           "Sull'orizzonte scegli un punto: è il punto di fuga. Tutte le linee parallele che si allontanano da chi guarda (i bordi di una strada, di un tavolo, di un corridoio) sembrano convergere lì. È il trucco che i pittori del Quattrocento formalizzarono per rendere lo spazio matematicamente coerente."),
          ("Passo 4 — Uno o due punti",
           "Con un solo punto di fuga disegni scene frontali, come una strada che si allontana dritta. Con due punti, ai lati dell'orizzonte, ottieni oggetti visti d'angolo, come lo spigolo di un palazzo. Più punti usi, più il punto di vista diventa dinamico e realistico."),
          ("Passo 5 — Provalo con un cubo",
           "Disegna un quadrato sotto l'orizzonte, metti un punto di fuga sopra e collega ogni angolo del quadrato a quel punto con linee leggere. Taglia le linee alla stessa distanza per chiudere la faccia posteriore: hai un cubo che 'entra' nel foglio. Ripeti spostando il punto di fuga e vedrai il cubo ruotare."),
      ],
      en={
          "title": "Perspective: how to give a drawing depth", "highlight_words": ["Perspective"],
          "hook": "A sheet is flat, yet a drawing can look miles deep. The Renaissance figured out the secret.",
          "objective": "Understand the vanishing-point principle and use linear perspective to make space believable.",
          "summary": "Linear perspective creates the illusion of depth by making parallel lines converge toward one or more vanishing points on the horizon.",
          "chapters": [
              ("Step 1 — The illusion of depth", "Our eyes judge distance from a few cues: far things look smaller, paler and higher toward the horizon. A drawing that follows these rules 'tricks' the brain and appears three-dimensional, even though the sheet stays perfectly flat."),
              ("Step 2 — The horizon line", "First: draw a horizontal line. It's the horizon, and it matches the height of your eyes. Everything above it you look at from below, everything below it you look at from above. Moving it up or down completely changes the scene's point of view."),
              ("Step 3 — The vanishing point", "On the horizon pick a point: the vanishing point. All parallel lines receding away from the viewer (the edges of a road, a table, a corridor) seem to converge there. It's the trick that 15th-century painters formalised to make space mathematically consistent."),
              ("Step 4 — One or two points", "With a single vanishing point you draw frontal scenes, like a road running straight away. With two points, on either side of the horizon, you get objects seen at an angle, like the corner of a building. The more points you use, the more dynamic and realistic the viewpoint."),
              ("Step 5 — Try it with a cube", "Draw a square below the horizon, place a vanishing point above it and connect each corner of the square to that point with light lines. Cut the lines at the same distance to close the back face: you have a cube 'entering' the page. Repeat with the point moved and the cube seems to rotate."),
          ],
      }),

    L("arte", "lez-teoria-colore",
      "I colori: come nascono tutte le tinte da pochi", ["colori"],
      "Uno schermo fa milioni di colori con soli tre. Un pittore ne mescola infiniti da una manciata di tubetti. Come?",
      "Distinguere colori primari, secondari e complementari e usarli per creare armonia o contrasto.",
      "Da pochi colori primari nascono tutti gli altri per mescolanza. I complementari, opposti sulla ruota, creano il massimo contrasto; i vicini creano armonia.",
      [
          ("Passo 1 — I colori primari",
           "I primari sono i colori che non puoi ottenere mescolandone altri: nella pittura sono grosso modo rosso, giallo e blu. Da questi tre, combinandoli, nascono tutti gli altri. Sono i mattoni di partenza di ogni tavolozza."),
          ("Passo 2 — Secondari e terziari",
           "Mescola due primari e ottieni un secondario: giallo e blu danno il verde, rosso e giallo l'arancione, rosso e blu il viola. Mescola un primario con il secondario vicino e ottieni i terziari, come il giallo-verde. Così la ruota dei colori si riempie tinta dopo tinta."),
          ("Passo 3 — La ruota dei colori",
           "Disponi le tinte in cerchio nell'ordine dell'arcobaleno: hai la ruota dei colori. È lo strumento che rende visibili i rapporti tra i colori. Colori vicini sulla ruota si somigliano; colori opposti sono i più diversi possibile."),
          ("Passo 4 — Complementari e armonie",
           "I colori opposti sulla ruota si dicono complementari (blu e arancione, rosso e verde). Accostati, si esaltano a vicenda e creano contrasto vivace. Colori vicini invece danno armonie morbide e riposanti. Scegliere tra contrasto e armonia è metà del lavoro di ogni immagine."),
          ("Passo 5 — Caldo, freddo e profondità",
           "I colori caldi (rossi, arancioni, gialli) sembrano avanzare verso di te; i freddi (blu, verdi) sembrano allontanarsi. I pittori usano questo effetto per dare profondità: primo piano caldo, sfondo freddo. È lo stesso motivo per cui le montagne lontane ci appaiono azzurrine."),
      ],
      en={
          "title": "Colour: how every shade is born from a few", "highlight_words": ["Colour"],
          "hook": "A screen makes millions of colours from just three. A painter mixes endless shades from a handful of tubes. How?",
          "objective": "Tell primary, secondary and complementary colours apart and use them to create harmony or contrast.",
          "summary": "From a few primary colours all others are born by mixing. Complementaries, opposite on the wheel, create maximum contrast; neighbours create harmony.",
          "chapters": [
              ("Step 1 — The primary colours", "Primaries are the colours you can't get by mixing others: in painting they are roughly red, yellow and blue. From these three, combined, all the others are born. They are the starting bricks of every palette."),
              ("Step 2 — Secondary and tertiary", "Mix two primaries and get a secondary: yellow and blue make green, red and yellow orange, red and blue purple. Mix a primary with the neighbouring secondary and you get tertiaries, like yellow-green. That's how the colour wheel fills in, shade by shade."),
              ("Step 3 — The colour wheel", "Arrange the shades in a circle in rainbow order: you have the colour wheel. It's the tool that makes the relationships between colours visible. Colours close on the wheel look alike; opposite colours are as different as possible."),
              ("Step 4 — Complementaries and harmonies", "Opposite colours on the wheel are called complementary (blue and orange, red and green). Placed together, they heighten each other and create lively contrast. Neighbouring colours instead give soft, restful harmonies. Choosing between contrast and harmony is half the work of any image."),
              ("Step 5 — Warm, cool and depth", "Warm colours (reds, oranges, yellows) seem to advance toward you; cool ones (blues, greens) seem to recede. Painters use this to add depth: warm foreground, cool background. It's the same reason distant mountains look bluish."),
          ],
      }),

    # ------------------------------ GEOGRAFIA ------------------------------
    L("geografia", "lez-leggere-mappa",
      "Leggere una mappa: scala, simboli e orientamento", ["mappa"],
      "Prima del GPS bastavano un foglio e la capacità di leggerlo. È un superpotere che vale ancora la pena imparare.",
      "Saper interpretare scala, legenda e punti cardinali per orientarsi con qualsiasi mappa cartacea.",
      "Una mappa è la realtà ridotta e codificata: la scala dice quanto è ridotta, la legenda cosa significano i simboli, il nord dà la direzione.",
      [
          ("Passo 1 — Cos'è davvero una mappa",
           "Una mappa è un modello in miniatura del territorio, visto dall'alto. Non può mostrare tutto, quindi seleziona: strade, fiumi, rilievi, città. Capire una mappa significa sapere cosa è stato tenuto, cosa è stato tolto e come è stato rappresentato."),
          ("Passo 2 — La scala",
           "La scala dice quanto la realtà è stata rimpicciolita. 1:100.000 significa che 1 centimetro sulla carta vale 100.000 centimetri veri, cioè 1 chilometro. Scala piccola (1:1.000.000) mostra intere regioni con pochi dettagli; scala grande (1:25.000) mostra pochi chilometri ma con sentieri e case."),
          ("Passo 3 — La legenda",
           "Ogni mappa ha una legenda: la tabella che spiega i simboli. Una linea blu è un fiume, una tratteggiata un sentiero, un triangolo una vetta, i colori indicano l'altitudine o il tipo di terreno. Senza leggere la legenda, una mappa è un disegno muto."),
          ("Passo 4 — Orientarsi col nord",
           "Quasi tutte le mappe hanno il nord in alto. Se allinei il nord della mappa col nord reale (con una bussola o col sole) ciò che vedi davanti a te corrisponde a ciò che sta in alto sul foglio. Da lì est è a destra, ovest a sinistra, sud in basso."),
          ("Passo 5 — Dalla mappa al passo",
           "Per stimare una distanza a piedi, misura il tratto sulla carta e moltiplicalo per la scala. Ricorda che in salita si va più lenti: le curve di livello ravvicinate segnalano pendii ripidi. Leggere il terreno prima di camminarlo è ciò che distingue chi si orienta da chi si perde."),
      ],
      en={
          "title": "Reading a map: scale, symbols and orientation", "highlight_words": ["map"],
          "hook": "Before GPS, a sheet of paper and the skill to read it were enough. It's a superpower still worth learning.",
          "objective": "Interpret scale, legend and cardinal points to find your way with any paper map.",
          "summary": "A map is reality shrunk and encoded: the scale tells how much it's shrunk, the legend what the symbols mean, north gives direction.",
          "chapters": [
              ("Step 1 — What a map really is", "A map is a miniature model of the land, seen from above. It can't show everything, so it selects: roads, rivers, relief, towns. Understanding a map means knowing what was kept, what was removed and how it was represented."),
              ("Step 2 — The scale", "The scale says how much reality has been shrunk. 1:100,000 means 1 centimetre on paper equals 100,000 real centimetres, i.e. 1 kilometre. A small scale (1:1,000,000) shows whole regions with few details; a large scale (1:25,000) shows a few kilometres but with paths and houses."),
              ("Step 3 — The legend", "Every map has a legend: the key that explains the symbols. A blue line is a river, a dashed one a path, a triangle a peak, colours show altitude or terrain type. Without reading the legend, a map is a mute drawing."),
              ("Step 4 — Finding north", "Almost all maps have north at the top. If you align the map's north with real north (using a compass or the sun), what you see in front of you matches what's at the top of the sheet. From there east is right, west left, south down."),
              ("Step 5 — From map to stride", "To estimate a walking distance, measure the stretch on paper and multiply by the scale. Remember you go slower uphill: closely spaced contour lines signal steep slopes. Reading the terrain before walking it is what separates those who navigate from those who get lost."),
          ],
      }),

    L("geografia", "lez-fusi-orari",
      "I fusi orari: perché non è la stessa ora ovunque", ["fusi orari"],
      "Chiami un amico dall'altra parte del mondo e per lui è già domani. Non è fantascienza: è la Terra che gira.",
      "Capire perché esistono i fusi orari, come si contano e cos'è la linea del cambiamento di data.",
      "La Terra ruota e illumina una zona alla volta: per questo l'ora cambia con la longitudine. Il mondo è diviso in 24 fusi, uno per ogni ora del giorno.",
      [
          ("Passo 1 — La causa: la Terra gira",
           "In ogni istante metà della Terra è illuminata dal Sole e metà è al buio. Ruotando su se stessa in 24 ore, la Terra porta a turno ogni luogo verso la luce. Quando da noi è mezzogiorno, dall'altra parte del pianeta è mezzanotte: non è la stessa ora perché non è lo stesso momento del giorno."),
          ("Passo 2 — Dividere il globo in 24",
           "Un giro completo sono 360 gradi in 24 ore, quindi 15 gradi ogni ora. Il mondo è stato diviso in 24 spicchi verticali, i fusi orari, larghi circa 15 gradi ciascuno. Spostandoti di un fuso verso est aggiungi un'ora, verso ovest la togli."),
          ("Passo 3 — Il meridiano di partenza",
           "Serviva un punto zero da cui contare: fu scelto Greenwich, a Londra. L'ora lì è il riferimento mondiale (UTC). Tutti gli altri fusi si esprimono come 'più' o 'meno' rispetto a Greenwich: New York è a UTC-5, Tokyo a UTC+9."),
          ("Passo 4 — Confini che zigzagano",
           "Sulla carta i fusi non sono righe perfette: seguono i confini degli Stati, così che ogni Paese resti su un'ora sola. Alcuni Paesi enormi, come la Cina, usano un unico fuso pur essendo larghi migliaia di chilometri, per comodità amministrativa."),
          ("Passo 5 — La linea che cambia il giorno",
           "A metà del Pacifico corre la linea del cambiamento di data. Attraversandola verso ovest salti avanti di un giorno, verso est torni indietro. È il motivo per cui, girando il mondo, puoi 'guadagnare' o 'perdere' un giorno intero pur avendo vissuto le stesse ore."),
      ],
      en={
          "title": "Time zones: why it isn't the same hour everywhere", "highlight_words": ["Time zones"],
          "hook": "You call a friend on the other side of the world and for them it's already tomorrow. It's not sci-fi: it's the Earth turning.",
          "objective": "Understand why time zones exist, how they are counted, and what the date line is.",
          "summary": "The Earth rotates and lights one area at a time: that's why the hour changes with longitude. The world is split into 24 zones, one per hour of the day.",
          "chapters": [
              ("Step 1 — The cause: Earth spins", "At any instant half the Earth is lit by the Sun and half is dark. Spinning on itself in 24 hours, the Earth brings every place toward the light in turn. When it's noon for us, it's midnight on the far side: not the same hour because it's not the same moment of the day."),
              ("Step 2 — Splitting the globe into 24", "A full turn is 360 degrees in 24 hours, so 15 degrees per hour. The world was divided into 24 vertical slices, the time zones, each about 15 degrees wide. Move one zone east and you add an hour, west and you subtract one."),
              ("Step 3 — The starting meridian", "A zero point was needed to count from: Greenwich, in London, was chosen. The time there is the world reference (UTC). All other zones are expressed as 'plus' or 'minus' relative to Greenwich: New York is UTC-5, Tokyo UTC+9."),
              ("Step 4 — Borders that zigzag", "On the map the zones aren't perfect lines: they follow country borders, so each nation stays on a single time. Some huge countries, like China, use one zone despite being thousands of kilometres wide, for administrative convenience."),
              ("Step 5 — The line that changes the day", "Down the middle of the Pacific runs the date line. Crossing it westward you jump forward a day, eastward you go back. It's why, circling the world, you can 'gain' or 'lose' a whole day despite living the same hours."),
          ],
      }),

    # ------------------------------ CULTURA ------------------------------
    L("cultura", "lez-etimologia",
      "Da dove vengono le parole: capire l'etimologia", ["etimologia"],
      "Ogni parola che dici è un fossile vivente: dentro conserva secoli di storia. Basta saperla ascoltare.",
      "Capire cos'è l'etimologia e usare radici e prestiti per intuire il significato di parole nuove.",
      "L'etimologia studia l'origine delle parole. Riconoscere radici, prefissi e prestiti da altre lingue permette di capire e ricordare meglio il vocabolario.",
      [
          ("Passo 1 — Le parole hanno una storia",
           "Nessuna parola nasce dal nulla: deriva da parole più antiche, spesso di altre lingue. 'Telefono' unisce il greco tele (lontano) e phone (voce): voce da lontano. Conoscere questa storia trasforma un suono arbitrario in un piccolo racconto che si ricorda facilmente."),
          ("Passo 2 — Radici, prefissi, suffissi",
           "Molte parole sono costruite come mattoncini. La radice porta il significato centrale, il prefisso lo modifica davanti, il suffisso dietro. Da 'porto' (portare) nascono importare, esportare, trasportare: cambia il prefisso, cambia la direzione, ma il cuore resta lo stesso."),
          ("Passo 3 — Le lingue madri",
           "L'italiano viene soprattutto dal latino, con innesti di greco. L'inglese mescola radici germaniche e latine. Sapere queste 'famiglie' spiega perché parole di lingue diverse si somigliano: 'notte', 'night', 'nacht' e 'nuit' vengono tutte dalla stessa radice antica."),
          ("Passo 4 — I prestiti",
           "Le lingue si scambiano parole di continuo. L'italiano ha preso 'caffè' dall'arabo attraverso il turco, 'computer' dall'inglese, 'pizza' l'ha invece esportata nel mondo. Ogni prestito è la traccia di un incontro tra popoli, commerci o tecnologie."),
          ("Passo 5 — Usala per indovinare",
           "Davanti a una parola sconosciuta, spezzala. 'Idrofobia': idro (acqua) + fobia (paura) = paura dell'acqua. Non serve conoscere ogni termine: bastano poche radici ricorrenti per intuire migliaia di parole. È il modo più efficiente di ampliare il vocabolario."),
      ],
      en={
          "title": "Where words come from: understanding etymology", "highlight_words": ["etymology"],
          "hook": "Every word you say is a living fossil: inside it keeps centuries of history. You just have to listen.",
          "objective": "Understand what etymology is and use roots and loanwords to guess the meaning of new words.",
          "summary": "Etymology studies the origin of words. Recognising roots, prefixes and loans from other languages helps you understand and remember vocabulary better.",
          "chapters": [
              ("Step 1 — Words have a history", "No word comes from nothing: it derives from older words, often from other languages. 'Telephone' joins the Greek tele (far) and phone (voice): voice from afar. Knowing this story turns an arbitrary sound into a little tale that's easy to remember."),
              ("Step 2 — Roots, prefixes, suffixes", "Many words are built like bricks. The root carries the core meaning, the prefix modifies it in front, the suffix behind. From 'port' (carry) come import, export, transport: change the prefix, change the direction, but the heart stays the same."),
              ("Step 3 — The mother languages", "Italian comes mostly from Latin, with Greek grafts. English blends Germanic and Latin roots. Knowing these 'families' explains why words in different languages resemble each other: 'notte', 'night', 'nacht' and 'nuit' all come from the same ancient root."),
              ("Step 4 — Loanwords", "Languages swap words all the time. Italian took 'caffè' from Arabic via Turkish, 'computer' from English, and exported 'pizza' to the world. Each loan is the trace of an encounter between peoples, trades or technologies."),
              ("Step 5 — Use it to guess", "Faced with an unknown word, break it apart. 'Hydrophobia': hydro (water) + phobia (fear) = fear of water. You don't need to know every term: a few recurring roots let you guess thousands of words. It's the most efficient way to grow your vocabulary."),
          ],
      }),

    L("cultura", "lez-calendario",
      "Perché l'anno dura 365 giorni (e a volte 366)", ["anno"],
      "Chi ha deciso quanti giorni ha un anno? Non un re capriccioso, ma il cielo — e un errore da correggere ogni quattro anni.",
      "Capire come il moto della Terra definisce l'anno e perché servono gli anni bisestili.",
      "L'anno è il tempo che la Terra impiega a girare intorno al Sole: circa 365 giorni e un quarto. Quel quarto, accumulato, diventa il 29 febbraio ogni quattro anni.",
      [
          ("Passo 1 — Giorno e anno, due movimenti",
           "La Terra fa due cose insieme: gira su se stessa in 24 ore (il giorno) e gira intorno al Sole in circa 365 giorni (l'anno). Il calendario cerca di far combaciare questi due movimenti, che però non stanno in un rapporto esatto e tondo."),
          ("Passo 2 — Il quarto di giorno di troppo",
           "La Terra impiega circa 365 giorni e 6 ore a completare l'orbita. Se contassimo solo 365 giorni, ogni anno perderemmo 6 ore: dopo un secolo le stagioni sarebbero sfasate di settimane, con la neve a Ferragosto. Bisognava recuperare quel tempo perso."),
          ("Passo 3 — L'anno bisestile",
           "La soluzione: ogni quattro anni, quelle 6 ore accumulate quattro volte fanno un giorno intero. Lo aggiungiamo il 29 febbraio. Ecco l'anno bisestile, di 366 giorni. È un modo semplice per rimettere il calendario in pari col cielo."),
          ("Passo 4 — La correzione della correzione",
           "In realtà l'avanzo non è esattamente 6 ore, ma un po' meno. Aggiungere un giorno ogni quattro anni corregge troppo. Per questo i secoli (1700, 1800, 1900) non sono bisestili, tranne quelli divisibili per 400 (come il 2000). È il calendario gregoriano, in uso dal 1582."),
          ("Passo 5 — Perché ci riguarda ancora",
           "Grazie a questa regola le stagioni restano ancorate alle stesse date per migliaia di anni. Ogni volta che vedi un 29 febbraio, stai osservando una correzione astronomica antica di secoli che tiene il nostro tempo sincronizzato con il viaggio della Terra intorno al Sole."),
      ],
      en={
          "title": "Why a year is 365 days (and sometimes 366)", "highlight_words": ["year"],
          "hook": "Who decided how many days a year has? Not a whimsical king, but the sky — and an error to fix every four years.",
          "objective": "Understand how the Earth's motion defines the year and why leap years are needed.",
          "summary": "A year is the time the Earth takes to orbit the Sun: about 365 days and a quarter. That quarter, added up, becomes 29 February every four years.",
          "chapters": [
              ("Step 1 — Day and year, two motions", "The Earth does two things at once: it spins on itself in 24 hours (the day) and orbits the Sun in about 365 days (the year). The calendar tries to line up these two motions, which, however, don't sit in an exact, round ratio."),
              ("Step 2 — The extra quarter day", "The Earth takes about 365 days and 6 hours to complete its orbit. If we counted only 365 days, each year we'd lose 6 hours: after a century the seasons would be weeks out of step, with snow in August. That lost time had to be recovered."),
              ("Step 3 — The leap year", "The fix: every four years, those 6 hours saved four times make a whole day. We add it on 29 February. That's the leap year, of 366 days. It's a simple way to put the calendar back in step with the sky."),
              ("Step 4 — Correcting the correction", "In truth the surplus isn't exactly 6 hours, but a bit less. Adding a day every four years overcorrects. That's why century years (1700, 1800, 1900) aren't leap years, except those divisible by 400 (like 2000). This is the Gregorian calendar, in use since 1582."),
              ("Step 5 — Why it still matters", "Thanks to this rule the seasons stay anchored to the same dates for thousands of years. Every time you see a 29 February, you're witnessing a centuries-old astronomical correction that keeps our time in sync with the Earth's journey around the Sun."),
          ],
      }),

    # ------------------------------ CORPO UMANO ------------------------------
    L("corpo-umano", "lez-respirazione",
      "Come respiri davvero: il diaframma al lavoro", ["diaframma"],
      "Respiri 20.000 volte al giorno senza pensarci. Ma quasi nessuno sa chi fa davvero il lavoro: non i polmoni.",
      "Capire il meccanismo della respirazione e come il diaframma controlla l'aria che entra ed esce.",
      "Respirare non è 'aspirare' aria: è il diaframma che, muovendosi, cambia il volume del torace e fa entrare o uscire l'aria per differenza di pressione.",
      [
          ("Passo 1 — I polmoni non si gonfiano da soli",
           "Al contrario di quello che sembra, i polmoni sono passivi: non hanno muscoli propri per gonfiarsi. Sono come palloncini dentro una scatola, il torace. Chi cambia il volume della scatola sono i muscoli intorno, prima di tutto il diaframma."),
          ("Passo 2 — Il diaframma, il muscolo chiave",
           "Il diaframma è una cupola muscolare sotto i polmoni, che separa torace e pancia. Quando si contrae, si abbassa e appiattisce: il torace si allarga. Quando si rilassa, risale a cupola: il torace si stringe. È il motore silenzioso di ogni respiro."),
          ("Passo 3 — Inspirazione: fare spazio",
           "Quando il diaframma si abbassa, il volume del torace aumenta e la pressione al suo interno scende sotto quella esterna. L'aria, come sempre, va dove la pressione è minore: entra dai polmoni per pareggiare. Non 'tiri' l'aria, le fai spazio ed è lei a entrare."),
          ("Passo 4 — Espirazione: lasciar andare",
           "Per l'espirazione tranquilla non serve sforzo: il diaframma si rilassa, il torace torna piccolo, la pressione interna sale e l'aria esce da sola. Solo quando soffi con forza entrano in gioco i muscoli addominali, che spingono in su il diaframma."),
          ("Passo 5 — Respirare meglio",
           "Molti respirano corto, alzando solo le spalle. La respirazione 'di pancia' usa a pieno il diaframma: inspirando la pancia si gonfia, espirando si sgonfia. È più efficiente, ossigena meglio e calma il sistema nervoso: per questo è alla base di yoga, canto e tecniche anti-stress."),
      ],
      en={
          "title": "How you really breathe: the diaphragm at work", "highlight_words": ["diaphragm"],
          "hook": "You breathe 20,000 times a day without thinking. But almost no one knows who really does the work: not the lungs.",
          "objective": "Understand the mechanism of breathing and how the diaphragm controls the air going in and out.",
          "summary": "Breathing isn't 'sucking in' air: it's the diaphragm that, by moving, changes the chest's volume and draws air in or pushes it out through pressure differences.",
          "chapters": [
              ("Step 1 — Lungs don't inflate themselves", "Contrary to how it feels, the lungs are passive: they have no muscles of their own to inflate. They're like balloons inside a box, the chest. What changes the box's volume are the muscles around it, first of all the diaphragm."),
              ("Step 2 — The diaphragm, the key muscle", "The diaphragm is a muscular dome below the lungs, separating chest and belly. When it contracts, it lowers and flattens: the chest widens. When it relaxes, it rises back into a dome: the chest narrows. It's the silent engine of every breath."),
              ("Step 3 — Inhaling: making room", "When the diaphragm lowers, the chest's volume grows and the pressure inside drops below the outside. Air, as always, goes where pressure is lower: it enters the lungs to even out. You don't 'pull' air in, you make room and it comes in on its own."),
              ("Step 4 — Exhaling: letting go", "Quiet exhaling takes no effort: the diaphragm relaxes, the chest shrinks, inside pressure rises and air leaves by itself. Only when you blow out hard do the abdominal muscles kick in, pushing the diaphragm up."),
              ("Step 5 — Breathing better", "Many people breathe shallowly, just raising the shoulders. 'Belly' breathing uses the diaphragm fully: inhaling the belly swells, exhaling it falls. It's more efficient, oxygenates better and calms the nervous system: that's why it underpins yoga, singing and anti-stress techniques."),
          ],
      }),

    L("corpo-umano", "lez-febbre",
      "Perché viene la febbre (ed è dalla tua parte)", ["febbre"],
      "La febbre sembra un nemico da abbattere subito. In realtà è una strategia intelligente del tuo corpo.",
      "Capire perché il corpo alza la temperatura durante un'infezione e quando la febbre va rispettata o trattata.",
      "La febbre è un aumento controllato della temperatura corporea: rende l'ambiente ostile ai microbi e potenzia le difese. È un sintomo, non la malattia.",
      [
          ("Passo 1 — Il termostato del corpo",
           "Il corpo mantiene una temperatura di circa 37 gradi grazie a un 'termostato' nel cervello, l'ipotalamo. Di solito difende quel valore con precisione. Durante un'infezione, però, decide deliberatamente di alzarlo: non è un guasto, è una scelta."),
          ("Passo 2 — L'allarme dei globuli bianchi",
           "Quando virus o batteri entrano, le cellule immunitarie rilasciano sostanze che raggiungono l'ipotalamo e gli dicono di spostare il termostato più in alto. Il corpo allora si comporta come se avesse freddo: brividi e tremori servono a produrre calore e alzare la temperatura."),
          ("Passo 3 — Perché il calore aiuta",
           "Molti microbi si riproducono male a temperature più alte del normale. Il calore, inoltre, accelera le reazioni del sistema immunitario: i globuli bianchi si muovono e lavorano più in fretta. La febbre, insomma, rallenta il nemico e potenzia l'esercito."),
          ("Passo 4 — Quando rispettarla",
           "Una febbre moderata in un adulto sano di solito è utile e non va spenta a tutti i costi: abbassarla subito può, in alcuni casi, allungare la malattia. Riposo e liquidi sono spesso la cosa migliore. Contano più i sintomi generali che il numero sul termometro."),
          ("Passo 5 — Quando preoccuparsi",
           "La febbre diventa un segnale d'allarme se è molto alta, dura a lungo, o si accompagna a rigidità del collo, difficoltà a respirare, confusione o disidratazione, e sempre nei neonati. In questi casi non è più solo una strategia utile: serve un medico. Ascoltare il corpo significa anche saperne leggere i limiti."),
      ],
      en={
          "title": "Why you get a fever (and it's on your side)", "highlight_words": ["fever"],
          "hook": "A fever seems like an enemy to knock down at once. In fact it's a clever strategy of your body.",
          "objective": "Understand why the body raises its temperature during an infection and when a fever should be respected or treated.",
          "summary": "A fever is a controlled rise in body temperature: it makes the environment hostile to microbes and boosts the defences. It's a symptom, not the illness.",
          "chapters": [
              ("Step 1 — The body's thermostat", "The body keeps a temperature of about 37 degrees thanks to a 'thermostat' in the brain, the hypothalamus. Usually it defends that value precisely. During an infection, though, it deliberately decides to raise it: not a fault, a choice."),
              ("Step 2 — The white cells' alarm", "When viruses or bacteria get in, immune cells release substances that reach the hypothalamus and tell it to set the thermostat higher. The body then acts as if it were cold: shivers and trembling serve to produce heat and raise the temperature."),
              ("Step 3 — Why heat helps", "Many microbes reproduce poorly at higher-than-normal temperatures. Heat also speeds up the immune system's reactions: white cells move and work faster. In short, fever slows the enemy and strengthens the army."),
              ("Step 4 — When to respect it", "A moderate fever in a healthy adult is usually useful and shouldn't be suppressed at all costs: bringing it down at once can, in some cases, lengthen the illness. Rest and fluids are often best. General symptoms matter more than the number on the thermometer."),
              ("Step 5 — When to worry", "A fever becomes a warning sign if it's very high, lasts long, or comes with a stiff neck, trouble breathing, confusion or dehydration, and always in newborns. In these cases it's no longer just a useful strategy: a doctor is needed. Listening to the body also means reading its limits."),
          ],
      }),

    # ------------------------------ CURIOSITÀ ------------------------------
    L("curiosita", "lez-ghiaccio-galleggia",
      "Perché il ghiaccio galleggia sull'acqua", ["ghiaccio"],
      "Quasi tutte le sostanze, da solide, affondano nel proprio liquido. L'acqua fa il contrario — e la vita ringrazia.",
      "Capire perché l'acqua solida è meno densa di quella liquida e perché questo è vitale.",
      "Il ghiaccio galleggia perché, congelando, le molecole d'acqua si dispongono in una struttura più spaziosa: a parità di peso occupa più volume, quindi è meno denso dell'acqua liquida.",
      [
          ("Passo 1 — Galleggiare è questione di densità",
           "Un oggetto galleggia se è meno denso del liquido in cui sta, cioè se a parità di volume pesa meno. Il legno galleggia sull'acqua, una pietra affonda. La domanda quindi è: perché il ghiaccio, pur essendo acqua, è meno denso dell'acqua liquida?"),
          ("Passo 2 — La stranezza dell'acqua",
           "In quasi tutte le sostanze le molecole, raffreddandosi, si avvicinano e il solido è più denso del liquido: infatti affonda. L'acqua è una rara eccezione. Sotto i 4 gradi succede qualcosa di controintuitivo: le sue molecole cominciano ad allontanarsi invece di avvicinarsi."),
          ("Passo 3 — Il merito dei legami",
           "Le molecole d'acqua si attraggono con legami a idrogeno. Quando l'acqua congela, questi legami le costringono in una griglia esagonale ordinata e piena di spazi vuoti. È come impilare persone tenendole a braccia tese: occupano più posto che ammassate. Più volume, stesso peso: meno densità."),
          ("Passo 4 — La prova nel bicchiere",
           "Per questo un cubetto galleggia, con circa un decimo che sporge dall'acqua. Ed è anche il motivo per cui una bottiglia piena dimenticata nel congelatore si spacca: l'acqua, ghiacciando, si espande e spinge sulle pareti con forza sorprendente."),
          ("Passo 5 — Perché è vitale",
           "In inverno i laghi ghiacciano dalla superficie, non dal fondo. Lo strato di ghiaccio galleggiante fa da coperchio isolante e sotto l'acqua resta liquida: pesci e piante sopravvivono. Se il ghiaccio affondasse, i laghi gelerebbero da sotto e la vita acquatica sarebbe molto più fragile."),
      ],
      en={
          "title": "Why ice floats on water", "highlight_words": ["ice"],
          "hook": "Almost every substance, when solid, sinks in its own liquid. Water does the opposite — and life is grateful.",
          "objective": "Understand why solid water is less dense than liquid water and why this is vital.",
          "summary": "Ice floats because, on freezing, water molecules arrange into a more spacious structure: for the same weight it takes up more volume, so it's less dense than liquid water.",
          "chapters": [
              ("Step 1 — Floating is about density", "An object floats if it's less dense than the liquid it's in, i.e. if for the same volume it weighs less. Wood floats on water, a stone sinks. So the question is: why is ice, though it's water, less dense than liquid water?"),
              ("Step 2 — Water's oddity", "In almost every substance the molecules, on cooling, move closer and the solid is denser than the liquid: so it sinks. Water is a rare exception. Below 4 degrees something counter-intuitive happens: its molecules start moving apart instead of closer."),
              ("Step 3 — Thank the bonds", "Water molecules attract each other with hydrogen bonds. When water freezes, these bonds force them into an ordered hexagonal grid full of empty spaces. It's like stacking people holding their arms out: they take more room than packed tight. More volume, same weight: less density."),
              ("Step 4 — The proof in the glass", "That's why an ice cube floats, with about a tenth poking above the water. And it's also why a full bottle forgotten in the freezer cracks: water, on freezing, expands and pushes on the walls with surprising force."),
              ("Step 5 — Why it's vital", "In winter lakes freeze from the surface, not the bottom. The floating ice layer acts as an insulating lid and below it the water stays liquid: fish and plants survive. If ice sank, lakes would freeze from below and aquatic life would be far more fragile."),
          ],
      }),

    L("curiosita", "lez-eco",
      "Perché senti l'eco (e a volte no)", ["eco"],
      "Gridi in montagna e la voce ti torna indietro. In una stanza no. La differenza è tutta nel viaggio del suono.",
      "Capire come nasce l'eco dal rimbalzo del suono e perché serve una distanza minima per sentirla.",
      "L'eco è il suono che, dopo aver colpito una superficie lontana, torna indietro. La senti come separata solo se il ritardo supera circa un decimo di secondo.",
      [
          ("Passo 1 — Il suono è un'onda che viaggia",
           "Il suono è una vibrazione che si propaga nell'aria a circa 340 metri al secondo. Parte dalla tua bocca e si allontana in tutte le direzioni. Quando incontra un ostacolo, parte della sua energia rimbalza indietro, proprio come una palla contro un muro."),
          ("Passo 2 — Il rimbalzo",
           "Se davanti a te c'è una parete rocciosa, il suono la colpisce e torna verso di te. Questo suono di ritorno è l'eco. Più la superficie è dura e liscia, meglio riflette; superfici morbide come tende o alberi assorbono il suono e riflettono poco."),
          ("Passo 3 — La regola del decimo di secondo",
           "Il tuo orecchio distingue due suoni come separati solo se arrivano ad almeno un decimo di secondo di distanza. In quel tempo il suono percorre circa 34 metri. Per sentire l'eco come voce distinta, la parete deve quindi essere lontana almeno 17 metri: l'onda va e torna, quindi il doppio."),
          ("Passo 4 — Perché in stanza non c'è eco",
           "In una stanza le pareti sono a pochi metri: il suono torna quasi istantaneamente e si fonde con la tua voce. Non lo senti come eco separata, ma contribuisce al 'riverbero', quella coda sonora che rende una chiesa vuota così risonante e una stanza arredata più ovattata."),
          ("Passo 5 — Chi usa l'eco per vedere",
           "Pipistrelli e delfini sfruttano lo stesso principio: emettono suoni e misurano il tempo di ritorno dell'eco per ricostruire cosa hanno intorno, al buio o nell'acqua torbida. È l'ecolocalizzazione, lo stesso trucco dei sonar delle navi: trasformare un rimbalzo di suono in una mappa dello spazio."),
      ],
      en={
          "title": "Why you hear an echo (and sometimes don't)", "highlight_words": ["echo"],
          "hook": "You shout in the mountains and your voice comes back. In a room it doesn't. The difference is all in the sound's journey.",
          "objective": "Understand how an echo arises from sound bouncing and why a minimum distance is needed to hear it.",
          "summary": "An echo is sound that, after hitting a distant surface, comes back. You hear it as separate only if the delay is more than about a tenth of a second.",
          "chapters": [
              ("Step 1 — Sound is a travelling wave", "Sound is a vibration that spreads through air at about 340 metres per second. It leaves your mouth and moves away in all directions. When it meets an obstacle, part of its energy bounces back, just like a ball against a wall."),
              ("Step 2 — The bounce", "If there's a rocky wall in front of you, the sound hits it and returns toward you. This returning sound is the echo. The harder and smoother the surface, the better it reflects; soft surfaces like curtains or trees absorb sound and reflect little."),
              ("Step 3 — The tenth-of-a-second rule", "Your ear tells two sounds apart as separate only if they arrive at least a tenth of a second apart. In that time sound travels about 34 metres. To hear the echo as a distinct voice, the wall must be at least 17 metres away: the wave goes and returns, so double the distance."),
              ("Step 4 — Why there's no echo in a room", "In a room the walls are a few metres away: the sound returns almost instantly and blends with your voice. You don't hear it as a separate echo, but it feeds 'reverb', that sonic tail that makes an empty church so resonant and a furnished room more muffled."),
              ("Step 5 — Who uses echo to see", "Bats and dolphins exploit the same principle: they emit sounds and measure the echo's return time to reconstruct what's around them, in the dark or in murky water. It's echolocation, the same trick as ships' sonar: turning a bounce of sound into a map of space."),
          ],
      }),
]
