# Capitoli aggiuntivi — ANIMALI
EXTRA = {
    # ---- lezioni ----
    "v4-lez-osservare-uccelli": {"it": [
        ("Passo 5 — Il colore per ultimo", "Il colore è l'indizio che tutti guardano per primo ed è il meno affidabile: cambia con la luce, l'età, la stagione e il sesso. Un maschio di passera in primavera sembra un uccello diverso dalla femmina. Usalo solo per confermare: se sagoma, movimento, ambiente e voce dicono 'storno', un riflesso verde-viola sulle piume chiude il caso. Se invece parti dal colore, sbaglierai spesso."),
        ("Passo 6 — Tieni un taccuino", "Annota data, luogo, ora e tre parole per ogni osservazione: 'piccolo, coda che vibra, muretto'. Dopo un mese scoprirai schemi che non avevi notato: gli stessi merli allo stesso lampione, le rondini che arrivano a fine marzo, i gabbiani che a gennaio vengono in città. App come Merlin o eBird aiutano a confermare, ma il taccuino è ciò che ti trasforma da spettatore in osservatore."),
    ]},
    "v4-lez-incontro-fauna": {"it": [
        ("Passo 5 — Il lupo e l'orso", "Gli incontri con grandi carnivori in Italia sono rari e quasi mai pericolosi, ma la regola è la stessa: non correre, non voltare le spalle, parla con voce ferma e allontanati lentamente. Con l'orso non urlare e non fissarlo; se una madre ha i cuccioli, aumenta la distanza subito. Il cibo va tenuto chiuso in tenda e in auto: quasi tutti gli incidenti nascono da animali abituati a mangiare avanzi umani."),
        ("Passo 6 — Cosa fare dopo", "Se l'incontro finisce con un morso o una puntura, lava a lungo con acqua e sapone e chiama il 118 o il pronto soccorso: per i mammiferi serve valutare la profilassi antirabbica e antitetanica, per le vipere serve arrivare in ospedale calmi, senza lacci né incisioni. Segnala poi l'incontro ai carabinieri forestali o al parco: aiuta a monitorare gli animali e a proteggere chi passerà dopo di te."),
    ]},
    "v4-lez-catena-alimentare": {"it": [
        ("Passo 5 — Gli anelli invisibili", "La piramide reale è più ricca di quella disegnata sui libri: sotto tutto lavorano i decompositori, funghi e batteri che rimettono in circolo i nutrienti, e in mezzo si muovono gli onnivori, che saltano da un livello all'altro. Un orso mangia bacche, pesce e carogne: è produttore di guano per le piante e consumatore su tre piani. Le catene, in natura, sono reti."),
        ("Passo 6 — Cosa accade se togli un anello", "Nel parco di Yellowstone, dopo la reintroduzione dei lupi nel 1995, i cervi tornarono a muoversi e smisero di brucare i salici lungo i fiumi; le sponde si ricoprirono di alberi, tornarono castori e uccelli. È la cascata trofica: pochi predatori in cima regolano tutto il resto. Ricorda la regola del 10% e capirai perché eliminare i pochi grandi carnivori ha effetti enormi."),
    ]},
    "lez-classificare-animali": {
        "it": [("Passo 6 — I casi che confondono", "La classificazione serve proprio dove l'intuito sbaglia. La balena vive in mare ma respira aria e allatta: mammifero. Il pinguino non vola ma ha piume e depone uova: uccello. Lo squalo e il delfino si somigliano per forma, ma uno ha branchie e l'altro polmoni. Il ragno non è un insetto: otto zampe, niente antenne. Quando un animale ti mette in dubbio, ripercorri i livelli in ordine e la risposta arriva.")],
        "en": [("Step 6 — The confusing cases", "Classification is most useful exactly where intuition fails. The whale lives at sea but breathes air and nurses its young: mammal. The penguin cannot fly but has feathers and lays eggs: bird. Shark and dolphin look alike in shape, yet one has gills and the other lungs. The spider is not an insect: eight legs, no antennae. When an animal puzzles you, walk through the levels in order and the answer comes.")],
    },
    "lez-ecolocalizzazione": {
        "it": [("Passo 6 — I limiti e i trucchi", "L'ecolocalizzazione ha un punto debole: più il suono è alto, più si spegne in fretta nell'aria, quindi i pipistrelli vedono bene solo entro pochi metri. Alcune falene hanno imparato a sentirli e a lasciarsi cadere in picchiata, altre emettono click di disturbo. I pipistrelli rispondono cambiando frequenza, come una radio che cambia canale. È una corsa agli armamenti sonora che dura da 50 milioni di anni.")],
        "en": [("Step 6 — Limits and tricks", "Echolocation has a weak spot: the higher the sound, the faster it fades in air, so bats see well only within a few metres. Some moths have learned to hear them and drop into a dive; others emit jamming clicks. Bats respond by changing frequency, like a radio switching channels. It is a sonic arms race that has lasted 50 million years.")],
    },
    "v5-lez-ibernazione": {"it": [
        ("Passo 5 — Il risveglio", "Uscire dall'ibernazione costa più che entrarci. Il corpo si riscalda in poche ore bruciando il grasso bruno, un tessuto speciale che produce calore direttamente; il cuore passa da pochi battiti a centinaia al minuto. Molti animali si svegliano brevemente ogni una o due settimane anche in pieno inverno: sembra uno spreco, ma serve probabilmente a far ripartire il sistema immunitario e a dormire davvero, perché nel torpore il cervello non riposa."),
        ("Passo 6 — Cosa impara la medicina", "Gli scoiattoli artici sopravvivono con il cervello a temperature quasi sotto zero senza danni, e gli orsi restano fermi per mesi senza perdere massa muscolare né ossa. I ricercatori studiano questi trucchi per proteggere il cervello dopo un ictus, conservare organi da trapiantare più a lungo e, un giorno, mandare astronauti in viaggi lunghissimi in una sorta di letargo indotto."),
    ]},
    "v5-lez-comunicazione-animale": {"it": [
        ("Passo 5 — I segnali elettrici e a colori", "Alcune specie usano canali che noi non possiamo percepire. I pesci elettrici del Sud America si riconoscono e corteggiano con scariche a frequenza precisa; le seppie cambiano disegno sulla pelle in un decimo di secondo per minacciare o sedurre; molti uccelli hanno piume che riflettono l'ultravioletto, visibile solo ai loro simili. Ogni canale è adatto all'ambiente: dove l'acqua è torbida, la luce serve poco e l'elettricità molto."),
        ("Passo 6 — È linguaggio?", "Il canto di una balena o il fischio di un delfino trasmettono informazioni, ma non sono un linguaggio nel senso umano: mancano la grammatica e la capacità di combinare simboli per creare frasi nuove. Alcuni casi si avvicinano: i cercopitechi hanno allarmi diversi per aquila, leopardo e serpente, e i pappagalli usano etichette. La distanza con noi è grande, ma è una distanza di grado, non di natura."),
    ]},
    "v5-lez-insetti-utili": {"it": [
        ("Passo 5 — I decompositori", "Sotto la superficie lavorano gli insetti che nessuno ringrazia: le larve di alcuni coleotteri e ditteri, insieme a lombrichi e millepiedi, spezzano le foglie morte e trasformano il compost in terra. Un metro quadrato di suolo sano ne ospita migliaia. Senza di loro i nutrienti resterebbero bloccati nei residui e le piante crescerebbero a fatica. Lasciare un angolo di foglie secche è il modo più semplice per aiutarli."),
        ("Passo 6 — Riconoscere i falsi nemici", "Molti insetti finiscono schiacciati per errore. Il sirfide sembra una vespa ma non punge e le sue larve divorano afidi; la forbicina mangia larve dannose più che frutta; la vespa comune, tanto temuta, elimina bruchi e mosche. Prima di intervenire, osserva: se un insetto sta fermo su una colonia di afidi, è quasi sempre un alleato al lavoro."),
    ]},
    "v5-lez-mimetismo": {"it": [
        ("Passo 5 — Il mimetismo dei suoni e degli odori", "Nascondersi non riguarda solo la vista. Alcune falene emettono ultrasuoni che imitano quelli delle specie velenose per ingannare i pipistrelli; certe orchidee producono l'odore di una femmina di ape per farsi impollinare da maschi illusi; le larve di alcune farfalle blu copiano l'odore delle formiche e vengono nutrite nel formicaio come fossero regine. Ogni senso che un predatore usa può essere ingannato."),
        ("Passo 6 — Come si evolve un inganno", "Un mimetismo perfetto non nasce in un colpo. Basta una somiglianza vaga per ridurre di poco la probabilità di essere mangiati; in migliaia di generazioni la selezione affina i dettagli, perché ogni individuo un po' più convincente lascia più discendenti. Il risultato finale sembra progettato, ma è la somma di piccoli vantaggi. Lo si vede ancora oggi: dove i predatori cambiano, il travestimento si aggiorna in pochi decenni."),
    ]},
    "v5-lez-estinzione": {"it": [
        ("Passo 5 — La sesta estinzione", "Oggi il ritmo di estinzione è stimato tra cento e mille volte superiore a quello naturale, e stavolta la causa è una sola specie. Perdita di habitat, caccia, specie invasive, inquinamento e clima agiscono insieme: un animale indebolito da un fattore cede al successivo. Non è ancora una catastrofe come quelle del passato, ma la direzione è la stessa, e la velocità è ciò che preoccupa gli scienziati."),
        ("Passo 6 — Cosa puoi fare tu", "Le estinzioni si fermano a livello locale, e ogni scelta pesa. Consumare meno carne e pesce da fonti non sostenibili riduce la deforestazione e la pesca eccessiva; non comprare souvenir di corallo, avorio o legni tropicali toglie mercato al bracconaggio; lasciare piante spontanee in giardino nutre insetti e uccelli. E sostenere aree protette funziona: dove esistono, la maggior parte delle specie a rischio si stabilizza."),
    ]},
    # ---- curiosità ----
    "why-dogs-love-us": {
        "it": [("L'ormone dell'abbraccio", "Quando un cane e il suo padrone si guardano negli occhi, in entrambi sale l'ossitocina, lo stesso ormone che lega una madre al neonato. Lo hanno misurato ricercatori giapponesi nel 2015: più a lungo il cane guarda, più ossitocina produce l'umano, che a sua volta accarezza di più, e il ciclo si rinforza. Con i lupi cresciuti dall'uomo l'effetto non compare. È un circuito biologico costruito su misura per noi.")],
        "en": [("The cuddle hormone", "When a dog and its owner look into each other's eyes, oxytocin rises in both, the same hormone that bonds a mother to her newborn. Japanese researchers measured it in 2015: the longer the dog gazes, the more oxytocin the human produces, who in turn strokes more, and the loop reinforces itself. With human-raised wolves the effect does not appear. It is a biological circuit tailor-made for us.")],
    },
    "shark-facts": {
        "it": [("Un sesto senso", "Sul muso degli squali si aprono centinaia di piccoli pori pieni di gel, le ampolle di Lorenzini, che percepiscono i deboli campi elettrici prodotti dai muscoli e dal battito cardiaco delle prede. Uno squalo può trovare un pesce nascosto sotto la sabbia senza vederlo né sentirne l'odore. Questo senso, insieme all'olfatto straordinario, spiega perché sono cacciatori così precisi e perché, quasi sempre, capiscono subito che un umano non è cibo.")],
        "en": [("A sixth sense", "A shark's snout is dotted with hundreds of small gel-filled pores, the ampullae of Lorenzini, which sense the weak electric fields produced by the muscles and heartbeat of prey. A shark can find a fish hidden under sand without seeing or smelling it. This sense, together with extraordinary smell, explains why they are such precise hunters and why, almost always, they quickly realise a human is not food.")],
    },
    "elephants-memory": {
        "it": [("La memoria che salva la vita", "Nella savana la memoria è una questione di sopravvivenza. Le matriarche più anziane ricordano dove si trovavano pozze d'acqua durante siccità di decenni prima e guidano il branco per centinaia di chilometri verso di esse. Durante la grande siccità del 1993 in Tanzania, i gruppi guidati da femmine che avevano vissuto quella del 1958 persero molti meno cuccioli. Uccidere una matriarca significa cancellare la biblioteca del branco.")],
        "en": [("Memory that saves lives", "On the savanna memory is a matter of survival. The oldest matriarchs remember where waterholes were during droughts decades earlier and lead the herd hundreds of kilometres towards them. During the great Tanzanian drought of 1993, groups led by females who had lived through the 1958 drought lost far fewer calves. Killing a matriarch means erasing the herd's library.")],
    },
    "bird-migration": {
        "it": [("Il costo del viaggio", "Prima di partire molti uccelli raddoppiano il peso in poche settimane, accumulando grasso che sarà il loro unico carburante. La pittima minore vola dall'Alaska alla Nuova Zelanda, 11.000 chilometri senza mai fermarsi, per otto o nove giorni; durante il volo riduce persino le dimensioni di stomaco e intestino per risparmiare energia. All'arrivo pesa la metà. Nessuna macchina costruita dall'uomo ha un'efficienza simile.")],
        "en": [("The cost of the journey", "Before leaving, many birds double their weight in a few weeks, storing fat that will be their only fuel. The bar-tailed godwit flies from Alaska to New Zealand, 11,000 kilometres without ever stopping, for eight or nine days; during the flight it even shrinks its stomach and gut to save energy. On arrival it weighs half as much. No human-built machine has similar efficiency.")],
    },
    "penguins-cold": {
        "it": [("Il sangue che non si raffredda", "Il segreto più ingegnoso è nascosto nelle zampe e nelle ali. Arterie e vene corrono affiancate: il sangue caldo che scende cede il calore a quello freddo che risale, così il calore resta nel corpo e le estremità restano appena sopra lo zero, senza congelare ma senza sprecare energia. È lo scambiatore di calore controcorrente, lo stesso principio usato negli impianti industriali, inventato dall'evoluzione milioni di anni prima.")],
        "en": [("Blood that does not cool", "The cleverest secret hides in the feet and flippers. Arteries and veins run side by side: warm blood flowing down gives its heat to the cold blood flowing back up, so heat stays in the body while extremities remain just above zero, never freezing yet wasting no energy. It is the counter-current heat exchanger, the same principle used in industrial plants, invented by evolution millions of years earlier.")],
    },
    "v4-polpo-cervelli": {"it": [
        ("Un maestro del travestimento", "La pelle del polpo contiene milioni di cellule pigmentate, i cromatofori, controllate direttamente dai nervi: in meno di un secondo l'animale cambia colore, disegno e persino consistenza per imitare sabbia, corallo o alghe. Il polpo mimetico dell'Indonesia arriva a copiare la forma e i movimenti di pesci velenosi. E fa tutto questo pur essendo, secondo molti studi, daltonico: percepisce la luce con la pelle stessa."),
        ("Una vita breve e solitaria", "Tutta questa intelligenza dura pochissimo. La maggior parte dei polpi vive uno o due anni; la femmina depone le uova una sola volta, le cura per mesi senza mangiare e muore quando si schiudono. Non c'è trasmissione di conoscenze tra generazioni: ogni polpo impara tutto da solo. È forse il dato più sorprendente: un cervello così sofisticato, costruito e perso ogni volta da zero."),
    ]},
    "v4-migrazione-anguille": {"it": [
        ("Il mistero risolto solo nel 2022", "Per un secolo nessuno aveva mai seguito un'anguilla fino al Mar dei Sargassi. Nel 2022 un gruppo di ricercatori ha marcato con trasmettitori satellitari anguille partite dalle Azzorre e le ha seguite per oltre 2.000 chilometri fino all'area di riproduzione: la prova diretta che mancava da quando Johannes Schmidt aveva intuito la rotta nel 1920. Le anguille viaggiano in profondità di giorno e risalgono di notte, forse per orientarsi con il campo magnetico."),
        ("Una specie in pericolo", "Le anguille europee sono diminuite di oltre il 90% dagli anni Settanta. Dighe e turbine bloccano la risalita dei giovani, l'inquinamento e un parassita del vescica natatoria li indeboliscono, e la pesca illegale delle cieche, vendute a peso d'oro in Asia, è uno dei traffici di fauna più redditizi d'Europa. Una specie che ha attraversato l'Atlantico per milioni di anni rischia di sparire proprio ora che cominciamo a capirla."),
    ]},
    "v4-cane-naso": {"it": [
        ("Annusare in stereo", "Il cane usa le due narici in modo indipendente e riesce a capire da quale lato arriva un odore, come noi localizziamo un suono con due orecchie. Inoltre inspira ed espira per vie diverse: l'aria in uscita esce da fenditure laterali, così non disturba la nuova aria che entra. A ogni annusata, fino a cinque al secondo, una parte dell'aria viene deviata in una camera dedicata solo all'olfatto, dove le molecole restano a lungo."),
        ("Ricordi fatti di odori", "Per un cane il mondo è una mappa di odori sovrapposti nel tempo. Annusando un lampione legge chi è passato, quanto tempo fa, se era maschio o femmina, se era stressato. Riconosce il padrone a distanza dall'odore prima di vederlo, e negli esperimenti di risonanza il suo cervello si attiva nelle aree della ricompensa quando sente l'odore della persona di casa. Per lui il nostro odore è un volto."),
    ]},
    "v5-colibri": {"it": [
        ("Il torpore notturno", "Per superare la notte senza cibo il colibrì fa qualcosa che assomiglia a una piccola ibernazione: abbassa la temperatura corporea anche di 20 gradi e il cuore scende da 1.200 a 50 battiti al minuto. In questo stato consuma fino al 95% di energia in meno. All'alba il risveglio dura circa venti minuti, durante i quali il corpo trema per riscaldarsi. Alcune specie andine arrivano a portare la temperatura a soli 3 gradi."),
        ("Il volo che nessun altro sa fare", "Il colibrì è l'unico uccello capace di volare all'indietro e di restare fermo in aria a lungo. Il segreto è la spalla, che ruota quasi a 180 gradi e produce portanza sia nella battuta in avanti sia in quella indietro, come gli insetti. Le ali battono 50-80 volte al secondo, e nelle danze di corteggiamento alcune specie superano i 200. Il ronzio che dà loro il nome inglese, hummingbird, viene proprio da lì."),
    ]},
    "v5-gatto-piedi": {"it": [
        ("Il paracadute naturale", "Un gatto in caduta non si limita a girarsi. Raggiunta la posizione giusta, allarga le zampe e rilassa il corpo, aumentando la superficie e rallentando la caduta come un piccolo paracadute. La velocità massima che raggiunge, circa 100 chilometri l'ora, è la metà di quella di un umano, e il rapporto tra superficie e peso gioca a suo favore. All'impatto piega le zampe e inarca la schiena, distribuendo l'urto su muscoli e articolazioni."),
        ("Non sempre finisce bene", "Il riflesso non è una garanzia. I veterinari parlano di sindrome del gatto paracadutista: le cadute dal secondo o terzo piano sono spesso le più pericolose, perché il gatto non ha il tempo di completare la rotazione e di rilassarsi, e fratture di mandibola e zampe sono frequenti. In casa il rischio maggiore sono le finestre aperte e i balconi senza rete: il gatto non stima bene le altezze e insegue insetti e uccelli senza esitare."),
    ]},
    "v5-formiche-capo": {"it": [
        ("Il superorganismo", "Molti biologi guardano al formicaio come a un unico essere vivente. Ogni formica sarebbe una cellula: le operaie sono il corpo, la regina l'apparato riproduttivo, le soldato il sistema immunitario. Un formicaio respira, si nutre, si difende e si riproduce producendo nuove regine alate. Alcune colonie di formiche argentine formano supercolonie di miliardi di individui che si estendono per migliaia di chilometri lungo le coste."),
        ("Cosa impariamo dalle formiche", "Gli algoritmi ispirati alle formiche sono usati per instradare pacchetti su internet, ottimizzare i percorsi dei camion e gestire flotte di robot. L'idea è sempre la stessa: nessun controllo centrale, regole semplici, segnali locali che si rinforzano quando funzionano. Le formiche trovano il percorso più breve tra nido e cibo senza che nessuna di loro conosca la mappa, e il sistema si adatta da solo quando un ramo si spezza."),
    ]},
    "v5-camaleonte": {"it": [
        ("Gli occhi e la lingua", "Il camaleonte ha altri due record. Gli occhi si muovono in modo indipendente e coprono quasi 360 gradi: può osservare due prede contemporaneamente e, quando ne sceglie una, allinea gli occhi per una visione binoculare precisa. La lingua poi scatta a un'accelerazione che supera quella di un'auto da corsa, raggiunge la preda in meno di due centesimi di secondo e la trattiene con una punta appiccicosa e un vero effetto ventosa."),
        ("Un colore per ogni umore", "Nel camaleonte pantera del Madagascar i maschi in duello passano dal verde a un arancio acceso in pochi secondi, e chi cambia colore più in fretta di solito vince senza combattere. Le femmine gravide mostrano fasce scure per dire ai maschi di stare lontani. Il colore è dunque un linguaggio, e i ricercatori hanno imparato a leggerlo: nei camaleonti, un cambio di tinta è quasi sempre una frase rivolta a un altro camaleonte."),
    ]},
    "v5-delfini-nome": {"it": [
        ("Ricordare per decenni", "Un esperimento all'Università di Chicago ha mostrato che i delfini riconoscono il fischio-firma di compagni che non vedono da oltre vent'anni, rispondendo con vivacità mentre ignorano i fischi di sconosciuti. È la memoria sociale più lunga documentata in un animale dopo l'uomo, superiore persino a quella degli elefanti. Serve perché i delfini vivono in società fluide, dove i gruppi si sciolgono e si ricompongono di continuo."),
        ("La cultura dei delfini", "Il nome non è l'unica cosa che i delfini si tramandano. In Australia alcune femmine insegnano alle figlie a proteggersi il muso con una spugna mentre scavano sul fondo, una tecnica trasmessa da madre a figlia da generazioni. Altri gruppi cacciano spingendo i pesci sulla riva o collaborano con pescatori umani. Sono tradizioni locali, diverse da popolazione a popolazione: il segno di una cultura, per quanto lontana dalla nostra."),
    ]},
}
