# Capitoli aggiuntivi — ARTE & DESIGN
EXTRA = {
    "lez-prospettiva": {
        "it": [("Passo 6 — Gli errori da riconoscere", "Tre errori tradiscono un disegno in prospettiva. Le linee parallele che non convergono nello stesso punto: controlla con una riga che tutte puntino al punto di fuga. L'orizzonte che cambia altezza tra un oggetto e l'altro: deve essere uno solo per tutta la scena. E le persone tutte alte uguali indipendentemente dalla distanza: le teste di chi sta in piedi sullo stesso piano si allineano tutte sull'orizzonte, se l'osservatore è in piedi.")],
        "en": [("Step 6 — Mistakes to spot", "Three mistakes betray a perspective drawing. Parallel lines that do not converge to the same point: check with a ruler that all of them aim at the vanishing point. A horizon that changes height from one object to another: there must be only one for the whole scene. And people all the same height regardless of distance: the heads of anyone standing on the same ground line up on the horizon, if the viewer is standing too.")],
    },
    "lez-teoria-colore": {
        "it": [("Passo 6 — Il colore nella vita quotidiana", "Ora osserva il mondo con la ruota in mente. I loghi dei fast food usano rosso e giallo, caldi e stimolanti; le banche il blu, freddo e rassicurante. Una stanza dipinta di azzurro sembra più grande e fresca, una in terracotta più raccolta. Per un abbinamento sicuro nell'abbigliamento scegli due colori vicini sulla ruota più un neutro; per farti notare, due complementari. Il colore è una lingua e adesso ne conosci la grammatica.")],
        "en": [("Step 6 — Colour in everyday life", "Now look at the world with the wheel in mind. Fast-food logos use red and yellow, warm and stimulating; banks use blue, cool and reassuring. A room painted light blue feels larger and fresher, one in terracotta cosier. For a safe outfit pick two neighbouring colours on the wheel plus a neutral; to stand out, two complementaries. Colour is a language, and now you know its grammar.")],
    },
    "v5-lez-guardare-quadro": {"it": [
        ("Passo 5 — Il contesto", "Un quadro cambia significato se sai quando e per chi è stato dipinto. Una Madonna del Trecento era un oggetto di preghiera in una chiesa buia, illuminata da candele che facevano vibrare l'oro; un ritratto olandese del Seicento era un modo per mostrare la ricchezza di un mercante. Chiediti: dove stava questo quadro? Chi lo guardava? Cosa doveva provare? Spesso la risposta spiega dimensioni, colori e persino i dettagli strani."),
        ("Passo 6 — Torna una seconda volta", "Il segreto dei musei è tornare. Dopo aver visto altre sale, ripassa davanti al quadro che ti ha colpito e nota cosa vedi di nuovo: un personaggio sullo sfondo, una firma nascosta, un colore che prima non avevi notato. Gli studi mostrano che il piacere estetico cresce con la familiarità. Scegli tre opere per visita e dedica loro dieci minuti ciascuna: ricorderai più di chi ha attraversato cinquanta sale di corsa."),
    ]},
    "v5-lez-regola-terzi": {"it": [
        ("Passo 5 — Le linee guida", "La griglia dei terzi lavora insieme ad altre linee. Strade, fiumi, ringhiere e ombre che partono da un angolo e portano l'occhio verso il soggetto sono le linee guida: rendono la foto dinamica e conducono lo sguardo. Cerca di far coincidere il punto in cui convergono con uno degli incroci della griglia. Anche una cornice naturale, come una porta o dei rami, aiuta a isolare il soggetto."),
        ("Passo 6 — Esercizio pratico", "Attiva la griglia nella fotocamera del telefono e per una settimana scatta ogni foto due volte: una con il soggetto al centro e una con il soggetto su un incrocio dei terzi. La sera confrontale senza guardare quale è quale. Nella maggior parte dei casi preferirai la seconda; nei casi in cui preferisci la prima, chiediti perché: probabilmente c'era una simmetria forte. Così impari la regola e anche quando romperla."),
    ]},
    "v5-lez-scegliere-font": {"it": [
        ("Passo 5 — Leggibilità sullo schermo", "Un carattere che funziona su carta può fallire su un telefono. Sullo schermo preferisci font con occhielli aperti e lettere ben distinte, come Inter, Roboto o Source Sans; controlla che I maiuscola, l minuscola e 1 non si confondano. Il contrasto è cruciale: grigio chiaro su bianco è elegante ma illeggibile al sole. E lascia respirare il testo: righe di 50-75 caratteri sono le più comode da leggere."),
        ("Passo 6 — Mettilo alla prova", "Prima di decidere, stampa o mostra il testo a grandezza reale e guardalo da un metro di distanza: se il titolo non si legge, il font o la dimensione sono sbagliati. Poi chiedi a qualcuno di leggere un paragrafo ad alta voce e conta le esitazioni. Infine controlla il font in tutte le varianti che userai, corsivo e grassetto compresi: molti caratteri gratuiti ne sono privi e il sistema ne crea versioni brutte in automatico."),
    ]},
    "v5-lez-storia-arte-tappe": {"it": [
        ("Passo 5 — Il Novecento dopo la guerra", "Dopo il 1945 il centro dell'arte si sposta da Parigi a New York. Pollock lascia gocciolare il colore su tele enormi stese a terra: conta il gesto, non l'immagine. Negli anni Sessanta Warhol risponde con la Pop Art, serigrafie di lattine e dive prese dalla pubblicità: l'arte diventa un prodotto che parla di prodotti. Nello stesso periodo il Minimalismo riduce tutto a forme pure e ripetute."),
        ("Passo 6 — Oggi: l'idea prima dell'oggetto", "Dagli anni Settanta l'arte contemporanea sposta il peso dall'oggetto all'idea. Un'installazione, una performance o un video contano per il concetto che portano, e l'abilità manuale non è più il criterio principale. Per orientarti davanti a un'opera recente chiediti tre cose: cosa mi fa sentire, cosa vuole dire, cosa cambia se la guardo nel luogo in cui è esposta. Capire non significa per forza apprezzare, e viceversa."),
    ]},
    "v5-lez-leggere-edificio": {"it": [
        ("Passo 5 — Neoclassico e Liberty (1750-1914)", "Tra Barocco e Moderno passano due stili facili da riconoscere. Il Neoclassico torna alla misura antica: colonne, frontoni triangolari, facciate bianche e simmetriche, come i teatri e i musei dell'Ottocento. Il Liberty, o Art Nouveau, intorno al 1900 fa l'opposto: linee curve ispirate a fiori e piante, ferro battuto sinuoso, ceramiche colorate e vetrate. Se un palazzo ha balconi che sembrano rami, sei nel Liberty."),
        ("Passo 6 — Leggi la tua strada", "Adesso esci e prova. Cerca la data sull'edificio, spesso incisa sopra il portone, e verifica la tua ipotesi. Guarda le finestre: ad arco a sesto acuto, gotico; rettangolari con cornici regolari, rinascimentale o neoclassico; ovali o con decorazioni mosse, barocco; a nastro senza cornici, moderno. Osserva anche gli edifici ibridi, spesso ristrutturati in epoche diverse: leggere quelle stratificazioni è il vero piacere."),
    ]},
    "v5-blu-oltremare": {"it": [
        ("Il sostituto che cambiò la pittura", "Il blu artificiale di Guimet, vinto il premio del 1826, costava un decimo del pigmento naturale ed era quasi identico. In pochi decenni il blu, per secoli riservato alla Madonna e ai committenti ricchissimi, invase le tele: gli impressionisti lo usarono per le ombre, Van Gogh per i cieli notturni, Picasso per un intero periodo. Un colore che era stato un simbolo di potere divenne il colore della malinconia e del quotidiano."),
        ("Il blu che vale ancora oro", "L'oltremare naturale non è sparito. Restauratori e alcuni pittori lo comprano ancora oggi a centinaia di euro per pochi grammi, perché nessun sostituto ha la stessa profondità sotto la luce. Nel 2009 un gruppo di chimici dell'Oregon ha scoperto per caso un blu completamente nuovo, l'YInMn, il primo pigmento blu inorganico dopo due secoli. La caccia al blu perfetto, cominciata nelle miniere afghane, continua nei laboratori."),
    ]},
    "v5-ritratti-sorriso": {"it": [
        ("La questione dei denti", "Un motivo molto pratico: i denti del passato erano brutti. Carie, denti mancanti e anneriti erano la norma anche tra i nobili, e mostrarli in un ritratto destinato a durare secoli non era un'idea attraente. Solo dopo il Settecento, con la diffusione della dentistica e dello zucchero, il tema divenne visibile: quando Madame Vigée Le Brun si dipinse sorridendo a bocca aperta nel 1787, la critica parigina la giudicò uno scandalo."),
        ("Tenere la posa", "Anche la tecnica giocava un ruolo. Un ritratto richiedeva ore di posa distribuite su giorni: mantenere un sorriso sincero per così tanto tempo è impossibile e il risultato sarebbe stato una smorfia. I pittori più bravi preferivano un'espressione neutra e stabile, su cui l'osservatore potesse proiettare ciò che voleva. Il sorriso della Gioconda affascina proprio perché è appena accennato: un'eccezione studiata, non una regola."),
    ]},
    "v5-helvetica": {"it": [
        ("La versione digitale e il suo gemello", "Quando negli anni Ottanta i computer iniziarono a usare i font, Helvetica costava troppo in licenze, così Microsoft commissionò Arial, un carattere quasi identico nelle proporzioni ma disegnato per evitare problemi legali. Per questo su Windows la vedi ovunque e la scambi per Helvetica. I tipografi le distinguono da dettagli minimi: il taglio orizzontale della coda della R, l'inclinazione dei terminali della C e della S."),
        ("Perché funziona ancora", "Helvetica resiste perché è progettata per non farsi notare. Le lettere hanno spaziatura uniforme, forme chiuse e un contrasto minimo tra tratti: da lontano formano un blocco compatto e leggibile, il motivo per cui la metropolitana di New York la adottò nel 1989. Nel 2007 le è stato dedicato un intero film documentario. Poche invenzioni del design hanno attraversato settant'anni senza sembrare mai vecchie."),
    ]},
    "v5-david-proporzioni": {"it": [
        ("Un problema di ingegneria", "Il David pesa circa sei tonnellate e poggia su due caviglie sottili di marmo. Già nel Cinquecento, per trasportarlo dalla bottega alla piazza, ci vollero quaranta uomini e quattro giorni. Oggi le caviglie mostrano microfratture, aggravate da un lieve fuori piombo della statua. Gli ingegneri le monitorano con sensori e hanno simulato che un terremoto moderato potrebbe farla cadere: per questo il basamento antisismico è in discussione da anni."),
        ("Il significato politico", "Firenze non scelse il David solo per bellezza. Nel 1504 la repubblica era circondata da nemici più forti: Davide, il ragazzo che sconfigge il gigante con l'astuzia, era il simbolo perfetto. Fu collocato davanti a Palazzo Vecchio, sede del governo, con lo sguardo rivolto verso Roma. Per secoli i fiorentini l'hanno chiamato semplicemente il Gigante, e la copia che oggi sta in piazza continua a guardare nella stessa direzione."),
    ]},
    "v5-van-gogh-vendette": {"it": [
        ("L'artista più copiato", "Il colpo di scena arriva un secolo dopo. Nel 1990 il Ritratto del dottor Gachet fu battuto a 82,5 milioni di dollari, allora il quadro più costoso mai venduto. Oggi le sue opere valgono complessivamente miliardi, e il Museo Van Gogh di Amsterdam supera i due milioni di visitatori all'anno. L'uomo che sopravviveva con i soldi del fratello è diventato il pittore le cui riproduzioni si vendono più di ogni altro al mondo."),
        ("Le lettere che raccontano tutto", "Se conosciamo così bene la sua vita è grazie alle oltre 800 lettere che scrisse, per lo più a Theo. Vi descrive i quadri prima di dipingerli, i colori che vuole, i dubbi, la fame. Sono considerate uno dei più bei carteggi della letteratura europea e smontano il mito del pazzo che dipingeva d'istinto: Van Gogh studiava, leggeva, pianificava ogni tela con lucidità. La leggenda del genio incompreso è vera solo a metà."),
    ]},
}
