# Capitoli aggiuntivi — CULTURA
EXTRA = {
    "v4-lez-galateo-mondo": {"it": [
        ("Passo 5 — I regali", "Un regalo può offendere senza volerlo. In Cina non regalare orologi, che evocano la fine del tempo, né oggetti a gruppi di quattro, numero che suona come morte; in Giappone il regalo si rifiuta una o due volte per cortesia prima di accettarlo e non si apre davanti a chi lo dona. In molti paesi arabi i regali si porgono e si ricevono con la mano destra. In Russia i fiori si regalano in numero impari: quelli pari sono per i funerali."),
        ("Passo 6 — La regola universale", "Nessuno può conoscere tutte le usanze del mondo, e non serve. La regola che funziona ovunque è osservare e imitare: guarda cosa fanno i padroni di casa, aspetta che comincino loro, e se sbagli chiedi scusa con un sorriso. Gli ospiti stranieri sono quasi sempre perdonati per un errore di forma, quasi mai per l'arroganza di chi pensa che il proprio modo sia l'unico. L'umiltà è il galateo che tutte le culture condividono."),
    ]},
    "v4-lez-leggere-poesia": {"it": [
        ("Passo 5 — Cerca la svolta", "Quasi tutte le poesie hanno un punto in cui qualcosa cambia: il tono, l'immagine, il tempo verbale. Nel sonetto è spesso tra l'ottava e la sestina, nella poesia moderna può essere l'ultimo verso. Trova quel punto e chiediti cosa c'è prima e cosa dopo. Nell'Infinito di Leopardi la svolta è 'ma sedendo e mirando': prima c'è la siepe che blocca lo sguardo, dopo lo spazio sconfinato che la mente inventa."),
        ("Passo 6 — Rileggila tra una settimana", "Una poesia non si esaurisce in una lettura, e il suo significato cambia con te. Segna quelle che ti hanno colpito e rileggile dopo qualche giorno: noterai un'immagine che avevi saltato o capirai un verso che ti era sembrato oscuro. Impararne una a memoria, anche breve, la trasforma in qualcosa che ti porti dietro. Non serve capire tutto: alcune poesie si abitano, non si spiegano."),
    ]},
    "v4-lez-imparare-lingua": {"it": [
        ("Passo 5 — Accetta l'accento e gli errori", "Gli adulti imparano la grammatica più in fretta dei bambini, ma quasi mai perdono del tutto l'accento: la capacità di percepire e riprodurre nuovi suoni cala dopo la pubertà. Non è un fallimento, è un dato. Concentrati sull'essere compreso, non sull'essere perfetto. Gli errori sono informazione preziosa: chi ha paura di sbagliare parla meno e progredisce più lentamente di chi si butta e si corregge dopo."),
        ("Passo 6 — Un piano di 90 giorni", "Metti insieme i passi in un programma concreto. Ogni giorno: quindici minuti di flashcard con ripetizione spaziata, venti di ascolto o lettura comprensibile, come serie con sottotitoli nella lingua originale o podcast per studenti, e dieci di produzione, un messaggio vocale o un diario di tre frasi. Una volta a settimana, una conversazione di trenta minuti con un madrelingua o un tutor online. In tre mesi passerai da zero a una conversazione semplice ma vera."),
    ]},
    "lez-etimologia": {
        "it": [("Passo 6 — Le parole che cambiano significato", "Le parole non cambiano solo forma, cambiano senso. 'Formidabile' significava 'che fa paura' e oggi vuol dire 'eccezionale'; 'ganzo' era il fidanzato segreto e ora significa 'bello'; 'terribile' e 'tremendo' oscillano ancora tra spavento e ammirazione. Il processo continua: 'assolutamente' sta diventando un semplice sì. Quando incontri una parola in un testo antico, chiediti sempre cosa significava allora, non cosa significa oggi.")],
        "en": [("Step 6 — Words that change meaning", "Words do not just change shape, they change sense. 'Awful' once meant 'inspiring awe' and now means 'terrible'; 'nice' meant 'foolish'; 'silly' meant 'blessed'. The process goes on: 'literally' is becoming a mere intensifier. When you meet a word in an old text, always ask what it meant then, not what it means today.")],
    },
    "lez-calendario": {
        "it": [("Passo 6 — Gli altri calendari", "Il nostro non è l'unico modo di contare il tempo. Il calendario islamico è puramente lunare: dodici mesi di 29 o 30 giorni per un anno di 354, per questo il Ramadan cade ogni anno undici giorni prima. Quello ebraico e quello cinese sono lunisolari: seguono la Luna ma aggiungono un tredicesimo mese sette volte ogni diciannove anni per restare allineati alle stagioni. Il calendario etiope ha tredici mesi ed è indietro di sette anni rispetto al nostro. Ogni calendario è una scelta culturale su come abitare il cielo.")],
        "en": [("Step 6 — The other calendars", "Ours is not the only way to count time. The Islamic calendar is purely lunar: twelve months of 29 or 30 days for a 354-day year, which is why Ramadan falls eleven days earlier each year. The Hebrew and Chinese calendars are lunisolar: they follow the Moon but add a thirteenth month seven times every nineteen years to stay aligned with the seasons. The Ethiopian calendar has thirteen months and runs seven years behind ours. Every calendar is a cultural choice about how to inhabit the sky.")],
    },
    "v5-lez-cognomi": {"it": [
        ("Passo 5 — I cognomi più diffusi e perché", "Rossi, Russo, Ferrari, Esposito, Bianchi: i primi cinque cognomi italiani raccontano la geografia dei tipi. Rossi e Bianchi vengono da soprannomi legati a capelli e pelle; Ferrari dal mestiere del fabbro, il più comune nei villaggi; Esposito dai bambini abbandonati a Napoli; Russo è la forma meridionale di Rossi. Nel Nord prevalgono i cognomi in -i, plurale di famiglia; nel Sud le forme singolari, per una diversa tradizione notarile."),
        ("Passo 6 — Ricostruire l'albero genealogico", "Per risalire alle origini parti dai documenti di casa, poi chiedi all'anagrafe del comune di nascita dei nonni: gli atti di stato civile arrivano fino al 1866 circa. Prima di quella data la fonte sono i registri parrocchiali di battesimo, matrimonio e sepoltura, spesso digitalizzati sul portale Antenati degli Archivi di Stato. Con pazienza si arriva al Seicento e talvolta al Concilio di Trento, quando le parrocchie iniziarono a registrare tutto."),
    ]},
    "v5-lez-gesti-italiani": {"it": [
        ("Passo 5 — I gesti che cambiano regione", "Non tutta l'Italia gesticola allo stesso modo. Il gesto della mano a borsa è più frequente e più ampio al Sud; nel Veneto e in Lombardia i gesti sono più contenuti e vicini al corpo. Alcuni sono locali: a Napoli il pollice che sfiora le dita significa 'niente', e il gesto delle mani che si allontanano rapidamente indica 'me ne vado'. Un gesto fatto nel posto sbagliato può sembrare esagerato o non essere capito affatto."),
        ("Passo 6 — Gesti da evitare all'estero", "Alcuni gesti italiani innocui altrove sono insulti. Le corna, che da noi scacciano la sfortuna o indicano un tradimento, in Sud America e in parte degli Stati Uniti sono un'offesa grave. Il cerchio con pollice e indice, per noi 'perfetto', in Brasile e in Turchia è volgare. Il pollice alzato in Iran e in parte del Medio Oriente equivale al nostro dito medio. In viaggio, quando non sei sicuro, tieni le mani ferme e lascia parlare la voce."),
    ]},
    "v5-lez-miti-diluvio": {"it": [
        ("Passo 5 — Il diluvio del Mar Nero", "Un'ipotesi geologica del 1997 ha dato nuovo vigore all'idea del ricordo storico. Secondo i geologi Ryan e Pitman, circa 7.500 anni fa il Mediterraneo, salito con lo scioglimento dei ghiacci, avrebbe sfondato il Bosforo e riempito in pochi anni il bacino del Mar Nero, allora un lago più basso. Le popolazioni della costa sarebbero fuggite portando il ricordo con sé. L'ipotesi è discussa, ma spiega bene perché il diluvio abbondi proprio nel Vicino Oriente."),
        ("Passo 6 — Cosa ci dice sul presente", "I miti del diluvio non riguardano solo il passato. Raccontano che l'ordine umano è fragile, che la natura può cancellarlo e che la sopravvivenza dipende da chi ascolta gli avvertimenti e costruisce l'arca. Non è un caso che oggi si parli di diluvio per l'innalzamento dei mari e che i racconti di catastrofe tornino nei film. Leggere un mito significa riconoscere che la stessa domanda, come sopravviviamo, ce la poniamo da almeno cinquemila anni."),
    ]},
    "v5-lez-opera-lirica": {"it": [
        ("Passo 5 — Le voci", "Riconoscere le voci raddoppia il piacere. Il soprano è la voce femminile più alta e quasi sempre l'eroina; il mezzosoprano è più scura, spesso la rivale o la seduttrice, come Carmen; il tenore è l'innamorato, il baritono il padre o l'antagonista, il basso il re o il sacerdote. I compositori scrivevano i personaggi pensando a questi colori: quando senti una voce, sai già che ruolo ha nella storia."),
        ("Passo 6 — Dopo la prima volta", "Se la prima opera ti è piaciuta, allarga il repertorio per gradi: dopo Puccini e Verdi prova Mozart, con Le nozze di Figaro o Don Giovanni, poi Rossini per il comico e infine Wagner o Strauss quando avrai l'orecchio allenato. Molti teatri offrono biglietti a prezzi bassi per i giovani e prove generali aperte; le trasmissioni in diretta al cinema e le piattaforme streaming permettono di vedere le grandi produzioni da casa, con sottotitoli."),
    ]},
    "v5-lez-struttura-fiaba": {"it": [
        ("Passo 5 — Il numero tre e le ripetizioni", "Le fiabe amano il tre: tre fratelli, tre prove, tre desideri, tre porcellini. Le ripetizioni non sono pigrizia del narratore ma tecnica: aiutano a memorizzare storie che per secoli sono state tramandate a voce, creano attesa e permettono al terzo tentativo di sorprendere dopo due fallimenti. Anche le formule fisse, 'c'era una volta' e 'vissero felici e contenti', sono segnali che dicono all'ascoltatore quando entra e quando esce dal mondo del racconto."),
        ("Passo 6 — Le fiabe oggi", "La struttura non è mai scomparsa, si è solo travestita. Guerre stellari, Harry Potter e Il Re Leone seguono esattamente lo schema: una mancanza, la partenza, un mentore, le prove, il ritorno trasformato. Gli sceneggiatori lo studiano apertamente nel cosiddetto viaggio dell'eroe descritto da Joseph Campbell e Christopher Vogler. La prossima volta che guardi un film, prova a segnare le tappe: quasi sempre ci sono tutte."),
    ]},
    "why-many-languages": {
        "it": [("Le lingue inventate e quelle risorte", "Non tutte le lingue nascono per caso. L'esperanto, creato nel 1887 da un medico polacco per unire i popoli, ha oggi qualche centinaio di migliaia di parlanti e persino madrelingua. L'ebraico moderno è l'unico caso di lingua morta riportata alla vita quotidiana, alla fine dell'Ottocento, a partire dai testi sacri. E il gallese, il maori e il basco, quasi scomparsi, sono tornati a crescere grazie alle scuole. Le lingue muoiono, ma qualche volta rinascono.")],
        "en": [("Invented and revived languages", "Not all languages arise by chance. Esperanto, created in 1887 by a Polish doctor to unite peoples, today has a few hundred thousand speakers and even native ones. Modern Hebrew is the only case of a dead language brought back to everyday life, in the late nineteenth century, starting from sacred texts. And Welsh, Maori and Basque, nearly gone, have begun to grow again thanks to schools. Languages die, but sometimes they are reborn.")],
    },
    "origin-alphabet": {
        "it": [("Perché la A è fatta così", "Capovolgi una A maiuscola e vedrai una testa di bue con le corna: la lettera fenicia 'alef' significava proprio bue, e il suo disegno derivava dal geroglifico egizio. La B, 'bet', era la pianta di una casa; la M, 'mem', l'onda dell'acqua; la O, 'ayin', un occhio. Ogni volta che scrivi una parola stai usando pittogrammi di quattromila anni fa, semplificati e ruotati, ma ancora riconoscibili a chi sa guardare.")],
        "en": [("Why the A looks like that", "Turn a capital A upside down and you will see an ox head with horns: the Phoenician letter 'aleph' meant ox, and its shape came from an Egyptian hieroglyph. B, 'bet', was the floor plan of a house; M, 'mem', the wave of water; O, 'ayin', an eye. Every time you write a word you are using four-thousand-year-old pictograms, simplified and rotated, but still recognisable to anyone who knows how to look.")],
    },
    "chess-history": {
        "it": [("Il boom dei nostri giorni", "Gli scacchi non sono mai stati così popolari. La pandemia e una serie televisiva del 2020, La regina degli scacchi, hanno portato decine di milioni di nuovi giocatori sulle piattaforme online, dove ogni giorno si giocano oltre dieci milioni di partite. Tornei di scacchi veloci vengono seguiti in streaming come eventi sportivi, e i giovani campioni hanno milioni di follower. Un gioco di quindici secoli ha trovato la sua forma perfetta su uno schermo di sei pollici.")],
        "en": [("Today's boom", "Chess has never been so popular. The pandemic and a 2020 television series, The Queen's Gambit, brought tens of millions of new players to online platforms, where over ten million games are played every day. Fast chess tournaments are streamed like sporting events, and young champions have millions of followers. A fifteen-century-old game has found its perfect form on a six-inch screen.")],
    },
    "why-we-cry": {
        "it": [("Il pianto nelle culture", "Quanto e dove si piange dipende dalla società. Uno studio su 37 paesi ha trovato che si piange di più dove c'è più libertà di espressione e benessere, non dove c'è più sofferenza: in Cile e Svezia più che in Nigeria o Bulgaria. Nell'antica Grecia gli eroi piangevano apertamente, nel Giappone tradizionale il pianto pubblico è ancora scoraggiato, e in molte culture esistevano piangenti professioniste per i funerali. Le lacrime sono biologia, ma il permesso di versarle è cultura.")],
        "en": [("Crying across cultures", "How much and where people cry depends on society. A study across 37 countries found that people cry more where there is greater freedom of expression and prosperity, not where there is more suffering: in Chile and Sweden more than in Nigeria or Bulgaria. In ancient Greece heroes wept openly, in traditional Japan public crying is still discouraged, and in many cultures professional mourners existed for funerals. Tears are biology, but permission to shed them is culture.")],
    },
    "v4-okay-origine": {"it": [
        ("Il viaggio nel mondo", "Dagli Stati Uniti OK si è diffuso con i soldati americani nelle due guerre mondiali, con i film di Hollywood e con la radio. Oggi è compreso praticamente in ogni lingua e si scrive in decine di alfabeti diversi. È forse la parola più democratica mai esistita: non appartiene a nessuna élite, non ha una grammatica, funziona come aggettivo, avverbio, verbo e interiezione. Il suo successo sta nella sua leggerezza."),
        ("Il gesto e l'emoji", "OK ha anche una forma muta: il cerchio con pollice e indice. In alcuni paesi è offensivo, e negli ultimi anni è stato usato con doppio senso da gruppi estremisti, tanto da finire in alcune liste di simboli d'odio, pur restando innocuo per la stragrande maggioranza delle persone. Nel 2015 il gesto è diventato emoji, e OK è stato tra i primi bottoni delle interfacce dei computer: la scelta più semplice quando una macchina ci chiede di confermare."),
    ]},
    "v4-tredici-sfortuna": {"it": [
        ("La triscaidecafobia costa", "La paura del 13 ha un nome, triscaidecafobia, e un prezzo. Molti grattacieli americani saltano il tredicesimo piano, gli aerei di diverse compagnie non hanno la fila 13, alcuni ospedali evitano la stanza 13 e le città la via 13. Negli Stati Uniti si stima che venerdì 13 l'economia perda centinaia di milioni di dollari per viaggi rimandati e affari non conclusi. Una superstizione senza fondamento che sposta comunque denaro reale."),
        ("Chi ha scelto il 13 come fortunato", "Per altri il 13 è un numero buono. Nella tradizione ebraica è il numero degli attributi di Dio e l'età del Bar Mitzvah; per i Maya e gli Aztechi il 13 era sacro e scandiva il calendario. In Italia il 13 al totocalcio era il colpo perfetto, tanto che fare tredici è ancora sinonimo di grande fortuna. Lo stesso numero, in culture diverse, può portare rovina o ricchezza: la sfortuna non sta nel numero, ma nella storia che ci raccontiamo su di esso."),
    ]},
    "v4-caffe-espresso": {"it": [
        ("La scienza dell'estrazione", "Un espresso nasce da 7-9 grammi di caffè macinato fine, acqua a circa 92 gradi spinta a 9 bar di pressione per 25-30 secondi. Ognuno di questi numeri conta: macinatura più grossa e il caffè esce acquoso, più fine e diventa amaro e bruciato. La crema è un'emulsione di anidride carbonica, oli e proteine, e dura pochi minuti. Per questo il barista serve la tazzina subito e per questo l'espresso, a casa, è così difficile da replicare."),
        ("Il caffè nel mondo", "L'Italia ha esportato la parola e la macchina, ma ogni paese ha piegato l'espresso ai suoi gusti. A Vienna è annegato nella panna, a Lisbona diventa la bica servita con un bicchiere d'acqua, in Australia ha generato il flat white, negli Stati Uniti si allunga con acqua calda nell'americano, nato dai soldati che trovavano l'espresso troppo forte. Le grandi catene hanno globalizzato il rito, ma il caffè al banco in trenta secondi resta un'esperienza tutta italiana."),
    ]},
    "v5-applausi": {"it": [
        ("La fisica dell'applauso", "Un applauso è un fenomeno di sincronizzazione spontanea. Ricercatori ungheresi hanno registrato platee intere e scoperto che, dopo qualche secondo di caos, le mani di centinaia di persone si allineano sullo stesso ritmo senza che nessuno lo decida, per poi perdere di nuovo la sincronia quando il ritmo accelera. È lo stesso comportamento dei grilli che cantano insieme e dei metronomi su una base mobile: sistemi che si accordano da soli."),
        ("Quanto dura e chi lo decide", "La durata di un applauso dipende poco dalla qualità dello spettacolo e molto dalla folla. Uno studio svedese del 2013 ha mostrato che ogni spettatore smette quando sente gli altri smettere: l'applauso si spegne a ondate, come un contagio inverso. Le standing ovation partono da pochi individui in prima fila e si propagano perché restare seduti diventa imbarazzante. Per questo le claque funzionavano: bastavano venti persone per orientare un teatro intero."),
    ]},
    "v5-pizza-margherita": {"it": [
        ("La pizza va in America", "La pizza è diventata globale non da Napoli ma da New York. Gli emigrati napoletani aprirono la prima pizzeria americana, Lombardi's, nel 1905, e nei decenni seguenti la pizza si trasformò: forno a carbone, dimensioni enormi, fetta venduta per strada. Dopo la Seconda guerra mondiale i soldati tornati dall'Italia ne chiesero ancora, e le catene la portarono ovunque. Gli italiani riscoprirono la loro pizza anche attraverso il successo americano."),
        ("Patrimonio dell'umanità", "Nel 2017 l'UNESCO ha iscritto l'arte del pizzaiuolo napoletano nella lista del patrimonio culturale immateriale, dopo una petizione firmata da due milioni di persone. Non la pizza in sé, ma i gesti: l'impasto lavorato a mano, lo schiaffo che stende il disco, il forno a legna a 485 gradi per 60-90 secondi. Il disciplinare della pizza napoletana verace fissa persino il diametro massimo, 35 centimetri, e l'altezza del cornicione. La leggenda della regina è discutibile; la tecnica è reale e protetta."),
    ]},
    "v5-pollice-alzato": {"it": [
        ("Il pollice dei piloti e dei social", "La consacrazione moderna del pollice arriva dall'aviazione. I piloti americani della Seconda guerra mondiale lo usavano per dire al personale di terra che erano pronti al decollo, in un ambiente troppo rumoroso per le parole; da lì passò al cinema di guerra e al mondo intero. Nel 2009 Facebook lo scelse come icona del Mi piace, e oggi quel pollice viene premuto miliardi di volte al giorno: il gesto più diffuso della storia è anche il più recente."),
        ("La lezione dei gladiatori", "La storia del pollice insegna quanto siano fragili le nostre certezze sull'antichità. Molte immagini che abbiamo di Roma vengono da pittori dell'Ottocento e da film del Novecento, non dalle fonti: i gladiatori non combattevano quasi mai fino alla morte, perché costavano troppo, e la maggior parte degli scontri finiva con la resa. Quando vedi un dettaglio 'antico' molto chiaro e cinematografico, chiediti sempre chi lo ha raccontato per primo."),
    ]},
    "v5-natale-25": {"it": [
        ("Il Natale che non piaceva ai cristiani", "Per secoli molte comunità cristiane guardarono il Natale con sospetto. I puritani inglesi lo proibirono nel 1647 perché troppo pagano e chiassoso, e nel Massachusetts coloniale festeggiarlo costava una multa. Il Natale domestico e sentimentale che conosciamo nasce solo nell'Ottocento, con il Canto di Natale di Dickens, l'albero portato in Inghilterra dal principe Alberto e le cartoline illustrate. Il Babbo Natale rosso e panciuto è una creazione americana del 1930 circa."),
        ("Il 6 e il 7 gennaio", "Non tutti festeggiano il 25 dicembre. Le Chiese ortodosse di Russia, Serbia ed Etiopia seguono ancora il calendario giuliano e celebrano il Natale il 7 gennaio del nostro calendario; la Chiesa armena lo festeggia il 6 gennaio insieme all'Epifania, come si faceva nei primi secoli. In Italia il 6 gennaio porta la Befana, una figura che deriva da riti agrari di fine anno e che la Chiesa ha assorbito. Il Natale è una data mobile che ogni cultura ha ancorato a modo suo."),
    ]},
    "v5-salute-starnuto": {"it": [
        ("Cosa succede quando starnutisci", "Uno starnuto è un riflesso che coinvolge decine di muscoli. Le mucose irritate inviano un segnale al tronco encefalico, che coordina una profonda inspirazione, la chiusura della glottide e poi un'espulsione d'aria a oltre 150 chilometri l'ora, con migliaia di goccioline che possono viaggiare per diversi metri. Chiudiamo gli occhi automaticamente, ma non perché rischiano di uscire: è solo parte del riflesso. Trattenere uno starnuto tappando naso e bocca può danneggiare l'orecchio."),
        ("Perché il sole ci fa starnutire", "Circa una persona su quattro starnutisce quando passa dal buio a una luce intensa. Il fenomeno si chiama riflesso fotico dello starnuto ed è ereditario: probabilmente i segnali del nervo ottico, sovraccaricato dalla luce improvvisa, disturbano il vicino nervo trigemino, quello che governa il naso. Aristotele si chiedeva già perché il sole facesse starnutire. Anche in questo caso, tra i presenti, qualcuno dirà salute."),
    ]},
}
