# Capitoli aggiuntivi — CORPO UMANO
EXTRA = {
    "v4-lez-leggere-battito": {"it": [
        ("Passo 5 — Il battito e l'allenamento", "Il battito è anche la bussola per allenarsi bene. Sottrai la tua età a 220 per stimare la frequenza massima; il 60-70% di quel valore è la zona dove si costruisce la resistenza di base, l'80-90% quella degli sforzi intensi. Se al mattino il battito a riposo è cinque o più battiti sopra la tua media, il corpo ti sta dicendo che non ha recuperato: rimanda l'allenamento duro."),
        ("Passo 6 — Cosa lo altera", "Prima di preoccuparti per un numero strano, escludi le cause banali. Caffè, nicotina, alcol la sera prima, febbre, disidratazione, una notte corta e persino l'ansia della misurazione alzano il battito di 10-20 unità. Alcuni farmaci per la pressione lo abbassano. Se, escluso tutto, il battito resta sopra i 100 o sotto i 50 senza essere sportivo, o senti pause e salti frequenti, è il momento di parlarne con il medico."),
    ]},
    "v4-lez-sonno-cicli": {"it": [
        ("Passo 5 — Il sonnellino giusto", "Il sonnellino funziona se rispetta i cicli: 10-20 minuti restano nel sonno leggero e ti svegli fresco; 30-60 minuti ti fanno atterrare nel profondo e il risveglio è confuso per mezz'ora, la cosiddetta inerzia del sonno; 90 minuti completano un ciclo intero. Il momento migliore è il primo pomeriggio, quando la temperatura corporea cala naturalmente. Dopo le 16 rischi di rubare sonno alla notte."),
        ("Passo 6 — I nemici del ciclo", "Tre cose spezzano i cicli senza che te ne accorga. L'alcol ti fa addormentare prima ma sopprime il REM nella seconda metà della notte. La caffeina ha un'emivita di cinque o sei ore: un caffè alle 17 è ancora attivo a mezzanotte e riduce il sonno profondo. Gli orari irregolari nel fine settimana spostano l'orologio interno come un piccolo jet lag. Coricarsi e svegliarsi alla stessa ora è il rimedio più potente e più gratuito."),
    ]},
    "v4-lez-primo-soccorso": {"it": [
        ("Passo 5 — Lo svenimento e le convulsioni", "Se una persona sviene, stendila a terra e sollevale le gambe: il sangue torna al cervello e di solito si riprende in un minuto; se non accade, controlla il respiro e chiama aiuto. Durante una crisi convulsiva non bloccarla e non metterle nulla in bocca: allontana gli oggetti, proteggi la testa con qualcosa di morbido e cronometra. Quando finisce, mettila su un fianco e resta con lei finché non è lucida."),
        ("Passo 6 — Il kit e il corso", "Un kit di casa ha bisogno di poco: guanti, garze sterili, cerotti, una benda elastica, disinfettante, forbici, una coperta isotermica e la lista dei numeri utili. Controllalo ogni anno. Ma l'attrezzatura più importante sono le mani: un corso di primo soccorso di quattro ore, offerto da Croce Rossa e associazioni locali, ti fa esercitare le compressioni su un manichino e trasforma quello che hai letto in gesti automatici."),
    ]},
    "lez-respirazione": {
        "it": [("Passo 6 — Il respiro che calma", "Il diaframma è anche una leva sul sistema nervoso. Quando espiri lentamente, il nervo vago rallenta il cuore e abbassa la pressione: per questo un'espirazione più lunga dell'inspirazione calma in pochi minuti. Prova il 4-6: quattro secondi dentro dal naso, sei fuori dalla bocca, per cinque cicli. Funziona prima di un esame, in coda nel traffico o nel letto quando i pensieri corrono.")],
        "en": [("Step 6 — The breath that calms", "The diaphragm is also a lever on the nervous system. When you exhale slowly, the vagus nerve slows the heart and lowers blood pressure: that is why an exhale longer than the inhale calms you within minutes. Try 4-6: four seconds in through the nose, six out through the mouth, for five cycles. It works before an exam, in a traffic jam or in bed when thoughts race.")],
    },
    "lez-febbre": {
        "it": [("Passo 6 — I falsi miti", "Tre credenze non reggono. La febbre alta non fa danni cerebrali: sotto i 41 gradi non ci sono rischi per il cervello, e il corpo raramente supera quella soglia da solo. Coprirsi per sudare non fa scendere la temperatura: al contrario, la trattiene. E il valore in sé conta meno del quadro generale: un bambino a 39 che gioca è più tranquillizzante di uno a 38 che non risponde. Osserva la persona, non solo il termometro.")],
        "en": [("Step 6 — The myths", "Three beliefs do not hold. High fever does not cause brain damage: below 41 degrees there is no risk to the brain, and the body rarely exceeds that threshold on its own. Wrapping up to sweat does not lower the temperature: on the contrary, it traps heat. And the number itself matters less than the overall picture: a child at 39 who is playing is more reassuring than one at 38 who is unresponsive. Watch the person, not just the thermometer.")],
    },
    "v5-lez-idratazione": {"it": [
        ("Passo 5 — Quando serve di più", "Ci sono situazioni in cui la sete arriva in ritardo. Durante lo sport intenso puoi perdere un litro l'ora di sudore; con il caldo, la febbre, la diarrea o in aereo il fabbisogno sale; gli anziani sentono meno la sete e i bambini piccoli non sanno chiederla. In questi casi bevi a intervalli regolari anche senza voglia: un bicchiere ogni venti minuti durante l'attività fisica è una buona misura."),
        ("Passo 6 — Il cibo conta", "Circa il 20-30% dell'acqua che assumi arriva dal cibo. Cetriolo, anguria, pomodoro e lattuga sono acqua per oltre il 90%; anche pasta, riso e minestre ne contengono molta. Caffè e tè contano: l'effetto diuretico è minimo rispetto al liquido che apportano. Per questo chi mangia molta frutta e verdura può bere meno acqua pura senza problemi, mentre chi vive di snack secchi ha bisogno della bottiglia sempre a portata."),
    ]},
    "v5-lez-digestione": {"it": [
        ("Passo 5 — Il microbiota", "Nel colon vivono circa mille specie di batteri, per un peso complessivo di oltre un chilo. Digeriscono le fibre che noi non sappiamo scomporre, producono vitamine come la K e la B12, allenano il sistema immunitario e comunicano con il cervello attraverso il nervo vago. Una dieta varia e ricca di fibre li mantiene diversificati; antibiotici, zuccheri e cibi ultraprocessati ne riducono la varietà in pochi giorni."),
        ("Passo 6 — Cosa aiuta la digestione", "Alcune abitudini semplici fanno la differenza. Masticare a lungo riduce il lavoro dello stomaco e fa arrivare prima il segnale di sazietà. Una breve camminata dopo i pasti accelera lo svuotamento gastrico e abbassa il picco glicemico. Coricarsi almeno due ore dopo cena riduce il reflusso. Le fibre e l'acqua prevengono la stitichezza; i famosi digestivi alcolici invece rallentano tutto: l'alcol rilassa la valvola dello stomaco e irrita la mucosa."),
    ]},
    "v5-lez-muscoli": {"it": [
        ("Passo 5 — Il ruolo del sonno e dell'età", "La sintesi proteica corre soprattutto di notte, quando cala il cortisolo e sale l'ormone della crescita: dormire sei ore invece di otto riduce la crescita muscolare e aumenta la perdita di massa nelle diete. Con l'età il muscolo risponde meno agli stimoli, un fenomeno chiamato resistenza anabolica; per questo dopo i cinquant'anni servono più proteine e allenamenti di forza regolari. La sarcopenia, la perdita di muscolo, non è inevitabile."),
        ("Passo 6 — Un programma minimo", "Non servono ore in palestra. Due sedute a settimana da 40 minuti con sei esercizi fondamentali, come squat, stacchi, piegamenti, trazioni, spinte sopra la testa e rematore, ripetuti in tre serie da otto a dodici, bastano per crescere. La chiave è il sovraccarico progressivo: aggiungi peso o ripetizioni ogni settimana o due. Tieni un quaderno: quello che non misuri non migliora."),
    ]},
    "v5-lez-etichetta-nutrizionale": {"it": [
        ("Passo 5 — Le parole che ingannano", "Alcune diciture sono legali ma fuorvianti. Senza zuccheri aggiunti non significa senza zuccheri: un succo di frutta ne ha comunque dieci grammi per cento millilitri. Light indica solo il 30% in meno di un nutriente rispetto alla versione normale. Integrale è vero solo se la farina integrale è il primo ingrediente. E ricco di fibre vale da tre grammi per cento: poco. Le parole sul fronte vendono, i numeri sul retro informano."),
        ("Passo 6 — Il Nutri-Score e le porzioni", "Alcuni prodotti mostrano il Nutri-Score, una lettera da A a E che riassume la qualità nutrizionale per cento grammi. È utile per confrontare prodotti della stessa categoria, meno per categorie diverse: un olio d'oliva prende C o D ma resta salutare. Attento infine alle porzioni indicate: una confezione di biscotti dichiara valori per due biscotti, e nessuno si ferma a due. Fai i conti sulla quantità che mangi davvero."),
    ]},
    "v5-lez-postura": {"it": [
        ("Passo 5 — Il mito della postura perfetta", "Non esiste una posizione corretta da mantenere a lungo. Gli studi mostrano che le persone con la schiena dritta soffrono di mal di schiena quanto quelle che stanno curve: il problema non è la forma, ma il tempo trascorso senza cambiarla. La postura migliore è la prossima. Cambia posizione spesso, alterna sedia e piedi, appoggia la schiena e poi staccala. La colonna è fatta per muoversi, non per essere allineata come una colonna di marmo."),
        ("Passo 6 — Quando andare dal medico", "La maggior parte dei mal di schiena passa da sola in poche settimane e il riposo assoluto peggiora le cose. Rivolgiti al medico se il dolore scende lungo la gamba fino al piede con formicolio o perdita di forza, se compare dopo una caduta, se è accompagnato da febbre o perdita di peso, o se non migliora affatto in sei settimane. In tutti gli altri casi la cura più efficace, secondo le linee guida, è restare attivi."),
    ]},
    "immune-system": {
        "it": [("I vaccini e l'allenamento", "Un vaccino è una lezione senza pericolo: mostra al sistema immunitario un pezzo del nemico, o una versione innocua, e lascia che formi le sue cellule della memoria. Al primo incontro reale la risposta è pronta in ore anziché in giorni. È lo stesso meccanismo che ti protegge dopo aver avuto il morbillo, senza doverlo attraversare. La vaccinazione di massa ha eliminato il vaiolo e ridotto la polio del 99%.")],
        "en": [("Vaccines as training", "A vaccine is a lesson without danger: it shows the immune system a piece of the enemy, or a harmless version, and lets it form its memory cells. At the first real encounter the response is ready in hours instead of days. It is the same mechanism that protects you after having measles, without having to go through it. Mass vaccination eradicated smallpox and cut polio by 99%.")],
    },
    "how-skin-works": {
        "it": [("Il colore della pelle", "Tutte le tonalità umane dipendono da un solo pigmento, la melanina, prodotto da cellule chiamate melanociti. Ne abbiamo tutti circa lo stesso numero: cambia quanta melanina producono e come la distribuiscono. La pelle scura protegge dagli ultravioletti e dalla perdita di folati vicino all'equatore; quella chiara permette di produrre vitamina D dove il sole è debole. Il colore è un adattamento alla latitudine, non una differenza profonda.")],
        "en": [("The colour of skin", "All human shades depend on a single pigment, melanin, produced by cells called melanocytes. We all have roughly the same number of them: what changes is how much melanin they make and how they distribute it. Dark skin protects against ultraviolet light and folate loss near the equator; light skin allows vitamin D production where sunlight is weak. Colour is an adaptation to latitude, not a deep difference.")],
    },
    "how-taste-works": {
        "it": [("Il gusto si può allenare", "Le preferenze non sono fisse. Ripetere un cibo che non piace per otto o dieci volte, in piccole quantità, di solito lo rende accettabile: è la familiarità che abbassa la difesa. Chi riduce il sale per un mese percepisce poi come salati cibi che prima sembravano insipidi, perché i recettori si risensibilizzano. Lo stesso vale per lo zucchero. Il palato è un'abitudine, e le abitudini si cambiano.")],
        "en": [("Taste can be trained", "Preferences are not fixed. Repeating a disliked food eight to ten times, in small amounts, usually makes it acceptable: familiarity lowers the defence. People who cut salt for a month then perceive as salty foods that previously seemed bland, because receptors become sensitive again. The same goes for sugar. The palate is a habit, and habits can be changed.")],
    },
    "blood-basics": {
        "it": [("Donare sangue", "Un adulto può donare 450 millilitri ogni tre mesi senza conseguenze: il plasma viene rimpiazzato in un giorno, i globuli rossi in poche settimane. Una sacca viene separata in tre componenti e può aiutare fino a tre pazienti diversi: operati, malati oncologici, persone con talassemia. Il sangue non si può fabbricare né conservare a lungo, le piastrine durano cinque giorni. Per questo gli ospedali hanno bisogno di donatori ogni singolo giorno.")],
        "en": [("Donating blood", "An adult can donate 450 millilitres every three months with no consequences: plasma is replaced within a day, red cells within a few weeks. One bag is separated into three components and can help up to three different patients: surgery cases, cancer patients, people with thalassaemia. Blood cannot be manufactured or stored for long; platelets last five days. That is why hospitals need donors every single day.")],
    },
    "v4-pelle-oca": {"it": [
        ("Un nervo che collega paura e freddo", "Il segnale che alza i peli arriva dal sistema nervoso simpatico, lo stesso che accelera il cuore davanti a un pericolo e restringe i vasi quando fa freddo. Per questo la pelle d'oca compare in situazioni così diverse: una folata gelida, un rumore improvviso nel buio, un ricordo intenso. Il cervello usa un'unica leva per rispondere a ciò che percepisce come minaccia o forte emozione, e la pelle la esegue senza chiedere."),
        ("I follicoli che ricostruiscono la pelle", "Uno studio di Harvard del 2020 ha scoperto che quel piccolo muscolo non è inutile. Insieme al nervo che lo comanda forma una nicchia che protegge le cellule staminali del follicolo pilifero; quando il freddo dura a lungo, il nervo stimola le staminali a produrre nuovi peli. Nell'uomo l'effetto è modesto, ma la struttura è la stessa: la pelle d'oca è la punta visibile di un sistema che regola la crescita dei capelli."),
    ]},
    "v4-stomaco-acido": {"it": [
        ("Un batterio che vive nell'acido", "Per un secolo si è creduto che nulla potesse sopravvivere nello stomaco. Nel 1982 due medici australiani, Marshall e Warren, dimostrarono che l'Helicobacter pylori ci vive benissimo: si nasconde nel muco e produce ammoniaca per neutralizzare l'acido attorno a sé. È la causa principale di ulcere e gastriti, e Marshall lo provò bevendo una coltura del batterio e ammalandosi. I due vinsero il Nobel nel 2005."),
        ("Cosa succede agli antiacidi", "I farmaci che riducono l'acido, come gli inibitori di pompa protonica, sono tra i più venduti al mondo e alzano il pH dello stomaco fino a 4 o 5. Sono preziosi per chi ha ulcere o reflusso grave, ma un uso prolungato senza motivo ha un prezzo: assorbimento ridotto di vitamina B12, ferro e calcio, e una barriera più debole contro i batteri ingeriti con il cibo. L'acido è aggressivo perché deve esserlo."),
    ]},
    "v4-sbadiglio": {"it": [
        ("Sbadigliano quasi tutti i vertebrati", "Pesci, serpenti, uccelli e mammiferi sbadigliano tutti, e il feto umano lo fa già a undici settimane nell'utero. Un comportamento così antico e diffuso deve avere un valore: probabilmente quello di aumentare in un colpo solo l'afflusso di sangue al cervello e di stirare i muscoli della mandibola, preparando l'animale a un cambio di attività. Nei primati il capo branco sbadiglia spesso per mostrare i denti senza aggredire."),
        ("La durata dipende dal cervello", "Nel 2016 un gruppo di ricercatori ha confrontato la durata degli sbadigli di ventiquattro specie: i topi sbadigliano per meno di un secondo, gli umani per oltre sei. La durata cresce con il numero di neuroni della corteccia, non con la taglia del corpo. Il dato sostiene l'ipotesi del raffreddamento: un cervello più grande e attivo ha bisogno di uno sbadiglio più lungo per scambiare abbastanza calore."),
    ]},
    "v5-dita-acqua": {"it": [
        ("La prova sperimentale", "Nel 2013 ricercatori di Newcastle hanno chiesto a volontari di spostare biglie bagnate da un contenitore all'altro, prima con le dita normali e poi dopo trenta minuti in acqua tiepida. Con le dita arricciate il compito era più rapido, mentre con oggetti secchi non c'era alcuna differenza. È esattamente ciò che ci si aspetta da un adattamento alla presa in ambiente bagnato, come camminare su rocce scivolose o raccogliere cibo in un torrente."),
        ("Cosa dice la pelle sulla salute", "Il fenomeno è così regolare da essere usato come test. Se le dita non si arricciano in acqua tiepida, i nervi simpatici della mano potrebbero essere danneggiati: succede in alcune neuropatie, dopo lesioni nervose o in chi ha la lebbra. Alcuni studi propongono il test dell'arricciamento come metodo semplice per valutare la funzione nervosa nei diabetici. Una piccola stranezza quotidiana che si è rivelata una finestra sul sistema nervoso."),
    ]},
    "v5-capelli-bianchi": {"it": [
        ("Il colore può tornare", "Per decenni si è creduto che l'imbiancamento fosse irreversibile. Nel 2021 un gruppo della Columbia University ha analizzato singoli capelli e ha trovato tratti bianchi seguiti da tratti tornati colorati: coincidevano con periodi di forte stress e con la loro fine. Il recupero avviene solo nelle prime fasi, quando i melanociti sono inattivi ma non ancora scomparsi. Dopo i cinquant'anni la riserva è di solito esaurita e il processo non si inverte più."),
        ("Bianco, non grigio", "Un capello grigio in realtà non esiste. Ogni capello è o pigmentato o completamente bianco: la sensazione del grigio nasce dal miscuglio di capelli bianchi e scuri visto da lontano, esattamente come un'immagine in bianco e nero sembra avere sfumature. La tinta dei capelli chiari è dovuta a poca melanina; quelli bianchi ne sono privi e inglobano microscopiche bolle d'aria che riflettono la luce, rendendoli più lucidi e spesso più ruvidi."),
    ]},
    "v5-fegato-rigenera": {"it": [
        ("Il mito di Prometeo", "Gli antichi Greci sembravano saperlo. Nel mito, Prometeo è punito da Zeus con un'aquila che gli divora il fegato ogni giorno, e ogni notte il fegato ricresce. È l'unico organo che la mitologia descrive come rigenerante, e la scelta non è casuale: nei sacrifici animali i Greci lo esaminavano di continuo e forse ne avevano notato la straordinaria capacità di riparazione dopo ferite."),
        ("Come si difende dai veleni", "Il fegato rigenera perché è l'organo più esposto ai danni. Ogni sostanza assorbita dall'intestino, alcol e farmaci compresi, passa per il fegato prima di raggiungere il resto del corpo, e i suoi enzimi la trasformano in composti eliminabili. Il paracetamolo in dose eccessiva e l'alcol cronico lo colpiscono direttamente; un fegato sano ripara i danni per anni in silenzio, finché il tessuto cicatriziale non prende il posto delle cellule. A quel punto la rigenerazione si ferma."),
    ]},
    "v5-cuore-stanca": {"it": [
        ("Il pacemaker naturale", "Il ritmo nasce da un gruppo di cellule grandi quanto un chicco di riso, il nodo senoatriale, in alto nell'atrio destro. Queste cellule si scaricano spontaneamente circa settanta volte al minuto e l'impulso si propaga a tutto il muscolo lungo vie dedicate. Se il nodo si guasta, altre zone del cuore prendono il comando a un ritmo più lento: per questo esistono i pacemaker artificiali, che dal 1958 sostituiscono il generatore quando si ferma."),
        ("Il cuore fuori dal corpo", "Un cuore espiantato continua a battere per qualche minuto anche staccato dal corpo, perché il suo ritmo non dipende dal cervello. Nei trapianti viene fermato con una soluzione fredda ricca di potassio e riparte, dopo il collegamento ai vasi del ricevente, spesso da solo o con una piccola scossa. Alcuni sistemi moderni lo mantengono caldo e battente durante il trasporto, alimentandolo con sangue ossigenato: un cuore che viaggia vivo."),
    ]},
    "v5-giramento-testa": {"it": [
        ("Il mal di mare e il conflitto dei sensi", "La nausea da movimento nasce dallo stesso sistema. In nave l'orecchio interno sente il rollio, ma gli occhi che guardano la cabina dicono che tutto è fermo: il cervello riceve due versioni incompatibili della realtà e, secondo l'ipotesi più accettata, interpreta il conflitto come un possibile avvelenamento, attivando la nausea. Per questo guardare l'orizzonte aiuta: dà agli occhi un riferimento che concorda con l'orecchio."),
        ("Quando gira senza motivo", "Se la testa gira da ferma, spesso la causa è nell'orecchio. La vertigine posizionale, la più comune, nasce da piccoli cristalli di calcio che si staccano e finiscono in un canale sbagliato, dove muovono il liquido a ogni cambio di posizione della testa; si risolve con manovre precise eseguite da uno specialista, che riportano i cristalli al loro posto. Altre cause sono le infezioni del labirinto e la malattia di Ménière. Una vertigine improvvisa con altri sintomi neurologici richiede invece il pronto soccorso."),
    ]},
}
