# Capitoli aggiuntivi — CURIOSITÀ
EXTRA = {
    "v4-lez-stimare": {"it": [
        ("Passo 5 — Il metodo di Fermi", "Enrico Fermi era famoso per stimare qualsiasi cosa con carta e penna. Quanti accordatori di pianoforte ci sono a Milano? Un milione e quattrocentomila abitanti, una famiglia su venti con un pianoforte, accordatura una volta l'anno, un accordatore fa quattro lavori al giorno per duecento giorni: circa novanta accordatori. Il trucco è scomporre la domanda impossibile in cinque domande facili, sbagliare un po' su ognuna e lasciare che gli errori si compensino."),
        ("Passo 6 — Dove ti serve davvero", "La stima serve più spesso di quanto pensi: capire se un preventivo è ragionevole, se un dato letto sui giornali è plausibile, quanto tempo richiederà un progetto. Un titolo che parla di dieci milioni di partecipanti a una manifestazione crolla con due conti: quanti metri quadrati ha la piazza, quante persone stanno in un metro quadrato. Chi sa stimare non si fa impressionare dai numeri grandi e non sottovaluta quelli piccoli."),
    ]},
    "v4-lez-perche-cielo-notte": {"it": [
        ("Passo 5 — Il fondo cosmico", "Il cielo, in realtà, non è buio: lo è solo per i nostri occhi. La luce della prima epoca dell'universo, emessa 380.000 anni dopo il Big Bang, arriva da ogni direzione, ma l'espansione l'ha stirata fino alle microonde. È la radiazione cosmica di fondo, scoperta per caso nel 1964 da due ingegneri che cercavano la causa di un rumore nella loro antenna. Il cielo di Olbers è luminoso; brilla a una frequenza che non vediamo."),
        ("Passo 6 — Ripeti il ragionamento", "Riassumi in tre mosse. Se l'universo fosse infinito, eterno e statico, ogni linea di vista finirebbe su una stella e la notte sarebbe accecante. La notte è buia, quindi almeno una premessa è falsa. L'universo ha un'età finita, quindi vediamo solo le stelle la cui luce ha avuto il tempo di arrivare, e l'espansione indebolisce la luce più lontana. Un'osservazione banale, il cielo scuro, contiene la prova che il cosmo ha avuto un inizio."),
    ]},
    "v4-lez-coincidenze": {"it": [
        ("Passo 5 — Il caso sembra a grappoli", "L'intuito si aspetta che il caso sia uniforme, ma il caso vero fa grumi. Se lanci una moneta cento volte, sequenze di cinque teste di fila sono quasi certe; le bombe cadute su Londra nel 1944 sembravano concentrarsi su alcuni quartieri, ma l'analisi statistica mostrò una distribuzione perfettamente casuale. Quando vedi un grappolo, di malattie in un paese o di vittorie di un giocatore, la prima ipotesi da testare è la più noiosa: il caso."),
        ("Passo 6 — Usa la statistica come scudo", "Le coincidenze sono il carburante delle truffe e delle credenze. Un cartomante fa cinquanta previsioni vaghe e ne ricorderai le due giuste; una pubblicità mostra la persona guarita dal rimedio e non le mille che non lo sono. Prima di stupirti, chiediti: quanti tentativi ci sono stati? Quante altre cose avrebbero contato come 'coincidenza'? Con queste due domande la maggior parte dei prodigi torna a essere aritmetica."),
    ]},
    "lez-ghiaccio-galleggia": {
        "it": [("Passo 6 — Il ghiaccio che affonda", "Esiste un ghiaccio che va a fondo. A pressioni enormi, come quelle all'interno delle lune ghiacciate di Giove, l'acqua forma strutture cristalline diverse, numerate fino al ghiaccio XIX, alcune più dense del liquido. Anche il ghiaccio comune, se fatto con acqua pesante, in cui l'idrogeno è sostituito dal deuterio, affonda nell'acqua normale. Il galleggiamento a cui siamo abituati è una fortuna delle condizioni terrestri, non una legge universale.")],
        "en": [("Step 6 — Ice that sinks", "There is ice that sinks. At enormous pressures, like those inside Jupiter's icy moons, water forms different crystal structures, numbered up to ice XIX, some denser than the liquid. Even ordinary ice, if made with heavy water, in which hydrogen is replaced by deuterium, sinks in normal water. The floating we take for granted is a stroke of luck of Earthly conditions, not a universal law.")],
    },
    "lez-eco": {
        "it": [("Passo 6 — Progettare il suono", "Architetti e ingegneri usano la regola del decimo di secondo ogni giorno. In un teatro le pareti sono sagomate e i materiali scelti perché i riflessi arrivino entro quel limite e rinforzino la voce invece di sporcarla; in una cattedrale il riverbero lungo è voluto, perché dà solennità al canto. Negli uffici open space pannelli fonoassorbenti eliminano i riflessi che rendono le voci confuse. Quando entri in una stanza e senti che 'suona bene', qualcuno ha fatto quei calcoli.")],
        "en": [("Step 6 — Designing sound", "Architects and engineers use the tenth-of-a-second rule every day. In a theatre the walls are shaped and materials chosen so that reflections arrive within that limit and reinforce the voice instead of muddying it; in a cathedral long reverberation is intended, because it gives solemnity to singing. In open-plan offices absorbing panels remove the reflections that make voices confusing. When you walk into a room and feel it 'sounds good', someone did those calculations.")],
    },
    "v5-lez-regressione-media": {"it": [
        ("Passo 5 — Dove la incontri ogni giorno", "La regressione spiega mille cose apparentemente misteriose. Il giocatore che dopo una stagione da record delude l'anno dopo. Il ristorante che ti aveva entusiasmato la prima volta e la seconda ti sembra normale. Il figlio di due genitori altissimi che è alto, ma meno di loro. La medicina alternativa che 'funziona' perché la prendi quando stai peggio, cioè poco prima di migliorare comunque. In tutti questi casi non c'è una causa: c'è il ritorno verso la media."),
        ("Passo 6 — Il test delle due misure", "Per non farti ingannare, applica una regola: non giudicare mai un intervento da un singolo prima-e-dopo scelto nel momento estremo. Se un'azienda introduce un corso dopo il trimestre peggiore e i risultati salgono, chiediti cosa sarebbe successo senza il corso. La risposta onesta richiede un gruppo di confronto o molte misure ripetute. È il motivo per cui la medicina usa i gruppi di controllo: senza, ogni cura sembrerebbe miracolosa."),
    ]},
    "v5-lez-grafici-ingannevoli": {"it": [
        ("Passo 5 — I dati che mancano", "Un grafico può mentire anche per ciò che non mostra. Un aumento di vendite spettacolare in un paese diventa banale se manca il confronto con i paesi vicini, cresciuti allo stesso modo; una curva di casi 'in aumento' perde significato senza il numero di test effettuati. Chiediti sempre: rispetto a cosa? Su quale totale? Cosa succedeva nello stesso periodo altrove? Il contesto è il dato più importante e il più facile da omettere."),
        ("Passo 6 — Il controllo in dieci secondi", "Prima di condividere o credere a un grafico, fai quattro controlli rapidi. Leggi i valori sugli assi e cerca lo zero. Controlla l'intervallo di tempo e chiediti perché inizia proprio lì. Cerca la fonte dei dati in piccolo, sotto il grafico. E prova a immaginare come sarebbe lo stesso dato disegnato dal punto di vista opposto. Se dopo questi controlli il grafico regge, è probabilmente onesto."),
    ]},
    "v5-lez-effetto-doppler": {"it": [
        ("Passo 5 — L'ecografia e le stelle doppie", "L'effetto Doppler è uno strumento medico quotidiano. L'ecodoppler invia ultrasuoni nei vasi sanguigni: i globuli rossi in movimento riflettono il suono con una frequenza spostata, e da quello spostamento il medico calcola la velocità del sangue e individua restringimenti. Gli astronomi usano lo stesso principio per scoprire pianeti attorno ad altre stelle: il pianeta fa oscillare leggermente la stella, e la sua luce diventa a turno un po' più blu e un po' più rossa."),
        ("Passo 6 — Prova a osservarlo", "Ora cerca l'effetto nella vita reale. Fermati vicino a una strada e ascolta un'auto che passa: il tono cala nel momento esatto in cui ti supera. Nota che la sirena di un'ambulanza ferma non cambia mai tono, anche se si avvicina un'altra auto: conta il movimento tra sorgente e ascoltatore. Se hai un'app che misura la frequenza del suono, registra il passaggio di un treno e vedrai il salto nel grafico. La fisica dell'universo in espansione è nella stessa curva."),
    ]},
    "v5-lez-hotel-hilbert": {"it": [
        ("Passo 5 — Perché non c'è contraddizione", "L'albergo di Hilbert sembra un paradosso, ma è solo l'intuito che protesta. Le nostre regole, come 'una parte è più piccola del tutto', sono state imparate contando oggetti finiti e non valgono per gli insiemi infiniti. In matematica un insieme è infinito proprio quando può essere messo in corrispondenza con una sua parte. Non è un trucco: è la definizione. L'infinito non è un numero molto grande, è un modo diverso di essere grande."),
        ("Passo 6 — L'infinito nella vita reale", "Che ce ne facciamo di infiniti diversi? Molto. Il calcolo infinitesimale, che permette di progettare ponti e prevedere le orbite, si basa su somme di infiniti termini che hanno un risultato finito. L'informatica usa gli infiniti di Cantor per dimostrare che esistono problemi che nessun computer potrà mai risolvere, perché i programmi possibili sono numerabili e i problemi no. L'albergo di Hilbert è il modo più semplice di entrare in un edificio dove lavorano ingegneri e programmatori."),
    ]},
    "v5-lez-numeri-primi": {"it": [
        ("Passo 5 — La caccia ai primi giganti", "Il più grande numero primo conosciuto ha oltre 41 milioni di cifre ed è stato trovato nel 2024 da un progetto di calcolo distribuito a cui chiunque può partecipare con il proprio computer. Appartiene ai primi di Mersenne, della forma 2 elevato a p meno 1, per i quali esiste un test speciale. Stamparlo richiederebbe migliaia di pagine. A cosa serve? A niente e a tutto: mette alla prova hardware e algoritmi, e ogni tanto una scoperta pura trova un uso decenni dopo."),
        ("Passo 6 — Il futuro: i computer quantistici", "La sicurezza basata sui primi ha una data di scadenza. Un computer quantistico abbastanza grande, con l'algoritmo di Shor, potrebbe fattorizzare in ore ciò che oggi richiede miliardi di anni. Le macchine attuali sono lontane da quella soglia, ma governi e aziende stanno già passando alla crittografia post-quantistica, basata su problemi matematici diversi, per proteggere dati che devono restare segreti a lungo. I primi hanno protetto il mondo per cinquant'anni; il testimone sta per passare."),
    ]},
    "why-lefties": {
        "it": [("Il mondo costruito per destri", "Essere mancini significa vivere in un ambiente progettato per gli altri. Forbici, apriscatole, banchi di scuola con il ripiano a destra, la penna che sbava scrivendo da sinistra, il cambio dell'auto, il mouse. Fino a metà Novecento i bambini mancini venivano corretti a forza, con conseguenze su lettura e linguaggio. Oggi l'atteggiamento è cambiato, e i mancini hanno persino una giornata mondiale, il 13 agosto. Ma provate a cercare una chitarra per mancini in un negozio qualsiasi.")],
        "en": [("A world built for right-handers", "Being left-handed means living in an environment designed for others. Scissors, can openers, school desks with the surface on the right, the pen that smudges when writing from the left, the car's gearstick, the mouse. Until the mid-twentieth century left-handed children were forcibly corrected, with consequences for reading and language. Attitudes have changed, and lefties even have a world day, 13 August. But try finding a left-handed guitar in an average shop.")],
    },
    "colors-cant-see": {
        "it": [("Le persone che vedono un colore in più", "Una piccola parte delle donne possiede quattro tipi di coni invece di tre, una condizione chiamata tetracromia. Nel 2010 una ricercatrice inglese ha identificato una donna capace di distinguere sfumature che per tutti gli altri erano identiche: dove noi vediamo un milione di colori, lei ne vedrebbe forse cento milioni. Il gene extra sta sul cromosoma X, il motivo per cui è quasi esclusivamente femminile. Il suo mondo è pieno di colori che non possiamo nemmeno immaginare.")],
        "en": [("People who see one colour more", "A small share of women have four types of cones instead of three, a condition called tetrachromacy. In 2010 a British researcher identified a woman able to tell apart shades that looked identical to everyone else: where we see a million colours, she may see a hundred million. The extra gene sits on the X chromosome, which is why it is almost exclusively female. Her world is full of colours we cannot even imagine.")],
    },
    "time-zones": {
        "it": [("Il tempo dei computer", "Sotto la superficie, il mondo digitale non usa fusi orari: ogni server conta i secondi trascorsi dal primo gennaio 1970 in tempo universale, e converte nell'ora locale solo quando deve mostrarla a un umano. È il modo per evitare il caos di 38 fusi e di regole sull'ora legale che cambiano ogni anno; un database pubblico, aggiornato da volontari, tiene traccia di ogni modifica decisa dai governi. Quando un paese cambia fuso con poco preavviso, milioni di telefoni vanno aggiornati di corsa.")],
        "en": [("Computer time", "Under the surface, the digital world does not use time zones: every server counts the seconds elapsed since 1 January 1970 in universal time, converting to local time only when it must show it to a human. It is the way to avoid the chaos of 38 zones and daylight-saving rules that change every year; a public database, maintained by volunteers, tracks every change decided by governments. When a country changes its zone at short notice, millions of phones must be updated in a hurry.")],
    },
    "why-mirror-flip": {
        "it": [("Perché non ti riconosci nelle foto", "Lo specchio ti ha abituato a un volto invertito. Il tuo viso non è simmetrico, e per tutta la vita hai visto il ciuffo, la piega del sorriso e l'occhio leggermente più basso da un lato preciso. Una fotografia mostra il lato che vedono gli altri, e per questo ti sembra sbagliata, mentre agli amici piace di più: loro sono abituati a quella versione. È l'effetto della mera esposizione: preferiamo ciò che vediamo più spesso, anche quando è il nostro volto al contrario.")],
        "en": [("Why you dislike your photos", "The mirror has trained you to an inverted face. Your face is not symmetrical, and all your life you have seen the fringe, the crease of the smile and the slightly lower eye on one specific side. A photograph shows the side others see, which is why it looks wrong to you while friends like it better: they are used to that version. It is the mere-exposure effect: we prefer what we see most often, even when it is our own face reversed.")],
    },
    "v4-carta-sette-volte": {"it": [
        ("I record ufficiali", "Dopo Britney Gallivan, la sfida è diventata uno sport. Nel 2012 gli studenti di una scuola del Massachusetts hanno piegato tredici volte un rotolo di carta igienica lungo sedici chilometri nel corridoio del MIT; il tentativo è stato ripetuto in altre università, e il Guinness registra ancora tredici come il massimo. Ogni piega aggiuntiva richiede un foglio quattro volte più lungo: per la quattordicesima servirebbero circa 65 chilometri di carta."),
        ("Cosa insegna sulla crescita esponenziale", "Il foglio è la migliore lezione sull'esponenziale, il tipo di crescita che l'intuito umano sottovaluta sempre. Vale per gli interessi composti, che raddoppiano il capitale a intervalli regolari; per le epidemie, dove pochi contagi diventano migliaia in settimane; per i chip dei computer, che hanno raddoppiato la potenza ogni due anni per mezzo secolo. Ogni volta che qualcosa raddoppia a ritmo costante, la tua mente vede una linea e la realtà disegna un muro."),
    ]},
    "v4-pop-corn": {"it": [
        ("Un cibo di diecimila anni", "Il pop-corn è uno dei cibi più antichi delle Americhe: in una grotta del New Mexico sono stati trovati chicchi scoppiati di oltre cinquemila anni, e in Perù resti ancora più antichi. Gli Aztechi lo usavano come ornamento nelle cerimonie e lo chiamavano momochitl. Gli europei lo scoprirono con la conquista, ma divenne uno spettacolo di massa solo nel 1885, quando Charles Cretors inventò la macchina a vapore per farlo per strada."),
        ("Perché sta al cinema", "Nei primi cinema il pop-corn era proibito: i proprietari volevano un pubblico elegante e silenzioso come a teatro, e i venditori ambulanti stazionavano fuori. La Grande Depressione cambiò tutto: era il piacere più economico che si potesse comprare, e i cinema che lo vendettero sopravvissero mentre gli altri chiudevano. Durante la guerra lo zucchero fu razionato e il pop-corn, salato, prese il posto delle caramelle. Oggi vale per le sale più del biglietto stesso."),
    ]},
    "v4-strisce-zebra": {"it": [
        ("Perché non funziona il raffreddamento", "L'idea che le strisce raffreddino il corpo, creando piccoli vortici d'aria tra zone nere calde e bianche fresche, è stata messa alla prova nel 2018 con bidoni d'acqua rivestiti di pelli diverse lasciati al sole: la temperatura interna dei bidoni a strisce era identica a quella dei bidoni grigi. Le zebre però hanno un altro trucco: possono sollevare il pelo nero e tenere piatto quello bianco, forse per regolare lo scambio di calore."),
        ("Le strisce sono uniche", "Come un'impronta digitale, il disegno di ogni zebra è irripetibile e i biologi lo usano per riconoscere gli individui senza catturarli, con software che leggono le strisce nelle foto come fossero codici a barre. Le tre specie hanno stili diversi: la zebra di Grévy ha strisce sottili e fitte, quella di montagna un ventre bianco, quella di pianura strisce larghe e ombreggiate. E il colore di fondo è il nero: le strisce chiare sono zone in cui il pigmento viene inibito."),
    ]},
    "v5-sacchetto-patatine": {"it": [
        ("Il rumore è parte del gusto", "Il sacchetto crepitante non è un difetto: è marketing. Uno studio dell'Università di Oxford ha dimostrato che le stesse patatine sembrano più fresche e croccanti se il rumore del morso viene amplificato in cuffia, e alcune aziende hanno riprogettato il materiale del sacchetto per renderlo più rumoroso. Nel 2010 un marchio americano ha dovuto fare marcia indietro dopo aver introdotto un sacchetto compostabile che raggiungeva i 95 decibel: i clienti lo trovavano insopportabile."),
        ("Quanto costa davvero il 'vuoto'", "L'aria nel sacchetto ha anche un prezzo ambientale. Tre quarti di quel volume viaggiano sui camion e occupano gli scaffali senza contenere nulla, e il sacchetto multistrato con alluminio è quasi impossibile da riciclare. Le normative europee sul packaging puntano a ridurre lo spazio vuoto negli imballaggi, e alcune aziende sperimentano confezioni più compatte in tubo rigido. Il sacchetto gonfio protegge la patatina, ma è uno dei simboli dello spreco che stiamo imparando a vedere."),
    ]},
    "v5-miele-non-scade": {"it": [
        ("Il miele come medicina", "Per la sua chimica il miele è stato per millenni il farmaco più diffuso al mondo. Gli Egizi lo usavano per medicare le ferite, e la medicina moderna lo ha riscoperto: il miele di manuka è approvato come medicazione per ustioni e piaghe, perché l'ambiente acido e l'acqua ossigenata che rilascia lentamente uccidono batteri resistenti agli antibiotici. Un cucchiaino di miele prima di dormire riduce la tosse notturna nei bambini sopra l'anno meglio di molti sciroppi."),
        ("L'unico pericolo", "Il miele ha un solo avvertimento serio. Può contenere spore di Clostridium botulinum, che nell'ambiente acido e privo d'acqua restano dormienti e per un adulto sono innocue; nell'intestino di un neonato sotto i dodici mesi, non ancora protetto da una flora batterica matura, possono invece germinare e causare il botulismo infantile. Per questo il miele non si dà mai ai lattanti. Per tutti gli altri, un barattolo dimenticato per anni resta perfettamente commestibile."),
    ]},
    "v5-cavi-annodano": {"it": [
        ("La matematica dei nodi", "I nodi sono un ramo serio della matematica. La teoria dei nodi classifica i modi in cui una corda chiusa può intrecciarsi: il nodo più semplice, il trifoglio, poi quello a otto, e via via oltre un milione di nodi distinti con sedici incroci. Nell'esperimento della scatola i ricercatori hanno riconosciuto oltre 120 tipi diversi di nodi formati spontaneamente. Le stesse idee servono ai biologi per capire come il DNA, lungo due metri in ogni cellula, si annodi e si sciolga senza rompersi."),
        ("Il problema che gli auricolari hanno risolto", "Il successo degli auricolari senza fili è dovuto anche a questo: hanno eliminato uno dei fastidi quotidiani più universali. Prima le aziende avevano provato tutto: cavi piatti, rivestimenti in tessuto, cavi più rigidi, clip magnetiche. Ogni soluzione riduceva l'annodamento ma non lo eliminava, perché la fisica era contro di loro. Alla fine il modo più semplice per non annodare un cavo è stato toglierlo."),
    ]},
    "v5-banane-radioattive": {"it": [
        ("Da dove viene la radioattività di ogni giorno", "La banana è solo una voce in un bilancio molto più grande. Una persona riceve in media 2-3 millisievert l'anno di radiazioni naturali: dal radon che sale dal suolo, dai raggi cosmici, dalle rocce, dal cibo. Un volo transoceanico ne aggiunge quanto quattrocento banane, una radiografia del torace quanto mille, una TAC quanto decine di migliaia. Vivere a Roma, con il suo tufo vulcanico, espone più che vivere a Milano. Il fondo naturale è la scala su cui ogni rischio va misurato."),
        ("Il potassio che ci serve", "Il potassio-40 non si può evitare, perché il potassio è indispensabile: regola il battito del cuore, la contrazione dei muscoli e l'equilibrio dei liquidi. Un adulto ne contiene circa 140 grammi, e il corpo ne mantiene la quantità costante: mangiare più banane non ti rende più radioattivo, perché elimini il potassio in eccesso. Fagioli, patate, spinaci e persino il caffè ne contengono più della banana. La curiosità radioattiva è in realtà una lezione su quanto il corpo sia bravo a fare i conti."),
    ]},
    "v5-qwerty": {"it": [
        ("La tastiera del telefono", "Sullo smartphone la QWERTY non ha più nessuna ragione meccanica di esistere, ma è sopravvissuta anche lì. Alcuni layout alternativi sono stati proposti, ottimizzati per i pollici e per la scrittura predittiva, e in laboratorio risultano più veloci. Nessuno li usa: il costo di reimparare supera il vantaggio. Le tastiere dei telefoni sono così diventate la prova più chiara che la QWERTY vince non perché è migliore, ma perché è già nelle nostre dita."),
        ("Le tastiere del mondo", "Fuori dall'inglese la QWERTY si adatta. I francesi usano l'AZERTY, i tedeschi la QWERTZ con la Z al posto della Y, perché in tedesco la Z è molto più frequente. La tastiera italiana ha le lettere accentate al posto di alcuni simboli. E poi ci sono i sistemi radicalmente diversi: i cinesi digitano la pronuncia in lettere latine e scelgono il carattere da un menu, i giapponesi alternano tre alfabeti. Ogni tastiera è un compromesso tra una lingua e un'invenzione dell'Ottocento."),
    ]},
}
