# Capitoli aggiuntivi — ECONOMIA & DENARO
EXTRA = {
    "v4-lez-budget-50-30-20": {"it": [
        ("Passo 5 — Adatta le percentuali", "Il 50/30/20 è un punto di partenza, non una legge. Se vivi in una città dove l'affitto assorbe da solo il 40% del netto, le necessità supereranno il 50% e dovrai comprimere i desideri, non il futuro. Chi ha debiti a tasso alto dovrebbe spostare gran parte del 30% sul rimborso, perché estinguere un prestito al 10% rende come un investimento al 10%. L'importante è che le tre voci esistano sempre e che il 20% non venga mai eroso per primo."),
        ("Passo 6 — Gli errori più comuni", "Tre errori mandano a monte il budget. Classificare come necessità ciò che è desiderio: l'abbonamento alla palestra o il telefono nuovo stanno nel 30%. Ignorare le spese annuali come assicurazioni, bollo e regali di Natale, che vanno divise per dodici e messe da parte ogni mese. E abbandonare tutto al primo mese sbagliato: un budget funziona come una dieta, conta la media su un anno, non la perfezione di ogni singolo mese."),
    ]},
    "v4-lez-leggere-busta-paga": {"it": [
        ("Passo 5 — TFR e tredicesima", "Due voci restano invisibili per gran parte dell'anno. Il TFR, trattamento di fine rapporto, è circa il 7% dello stipendio lordo che il datore accantona ogni mese e ti paga alla fine del rapporto, oppure versa nel fondo pensione se lo hai scelto. La tredicesima, e in alcuni contratti la quattordicesima, sono stipendi aggiuntivi maturati mese per mese e pagati a dicembre e a giugno. Se guardi solo il netto mensile, sottovaluti quanto guadagni davvero."),
        ("Passo 6 — Confrontare due offerte di lavoro", "Quando confronti due stipendi, confronta il lordo annuo comprensivo di tutte le mensilità, poi aggiungi il valore di buoni pasto, auto aziendale, assicurazione sanitaria e contributi extra al fondo pensione, che possono valere migliaia di euro l'anno e sono tassati poco o nulla. Un lordo di 30.000 euro su 14 mensilità con buoni pasto può battere uno di 32.000 su 13 senza benefit. Il numero da confrontare è il costo totale per l'azienda, non la cifra del colloquio."),
    ]},
    "v4-lez-domanda-offerta": {"it": [
        ("Passo 5 — Quando il prezzo non può muoversi", "A volte il prezzo viene bloccato per legge e il meccanismo si inceppa. Un tetto agli affitti sotto il prezzo di equilibrio fa sparire le case dal mercato, perché i proprietari preferiscono non affittare, e nascono le liste d'attesa e il mercato nero. Un prezzo minimo sopra l'equilibrio, come il sostegno agricolo, produce eccedenze invendute. Non significa che gli interventi siano sempre sbagliati, ma che hanno effetti collaterali prevedibili."),
        ("Passo 6 — Leggi i prezzi intorno a te", "Ora osserva i prezzi come segnali. Le fragole costano il triplo a dicembre perché l'offerta è minima; un biglietto aereo sale la settimana di Natale perché la domanda esplode; i prezzi degli hotel crollano il lunedì. Un affitto che sale in un quartiere dice che la domanda supera l'offerta, e spesso anticipa nuovi negozi e nuove costruzioni. Chi legge i prezzi come informazioni capisce l'economia meglio di chi legge solo le notizie."),
    ]},
    "lez-interesse-composto": {
        "it": [("Passo 6 — Metti in pratica", "Trasforma l'idea in un'azione di dieci minuti. Apri una simulazione online di interesse composto e inserisci 100 euro al mese al 5% per trent'anni: vedrai oltre 80.000 euro, di cui solo 36.000 versati da te. Poi ripeti con 200 euro per quindici anni: il risultato è più basso nonostante la stessa cifra versata. Infine imposta un bonifico automatico verso un piano di accumulo il giorno dopo lo stipendio. La palla di neve inizia a rotolare solo se la spingi una volta.")],
        "en": [("Step 6 — Put it into practice", "Turn the idea into a ten-minute action. Open an online compound-interest simulator and enter 100 euros a month at 5% for thirty years: you will see over 80,000 euros, of which only 36,000 came from you. Then repeat with 200 euros for fifteen years: the result is lower despite the same amount paid in. Finally set up an automatic transfer to a savings plan the day after payday. The snowball starts rolling only if you push it once.")],
    },
    "lez-inflazione": {
        "it": [("Passo 6 — Deflazione e iperinflazione", "L'inflazione ha due estremi, entrambi pericolosi. La deflazione, il calo generale dei prezzi, sembra una buona notizia ma paralizza l'economia: se tutto costerà meno domani, nessuno compra oggi, le aziende vendono meno, licenziano, e i debiti diventano più pesanti; il Giappone ci ha convissuto per vent'anni. L'iperinflazione, oltre il 50% al mese, distrugge la moneta in pochi mesi. Per questo le banche centrali puntano a un'inflazione bassa ma positiva, intorno al 2%: abbastanza per non bloccare gli acquisti, poco abbastanza per non erodere i risparmi.")],
        "en": [("Step 6 — Deflation and hyperinflation", "Inflation has two extremes, both dangerous. Deflation, a general fall in prices, sounds like good news but paralyses the economy: if everything will cost less tomorrow, nobody buys today, companies sell less, lay people off, and debts grow heavier; Japan lived with it for twenty years. Hyperinflation, above 50% a month, destroys a currency within months. That is why central banks aim for low but positive inflation, around 2%: enough not to freeze spending, small enough not to erode savings.")],
    },
    "v5-lez-fondo-emergenza": {"it": [
        ("Passo 5 — Cosa non è un'emergenza", "Il fondo funziona solo se lo difendi. Un'emergenza è una spesa imprevista, necessaria e urgente: l'auto che non parte e ti serve per lavorare, il dentista, la lavatrice rotta. Non lo sono il volo in offerta, il regalo di compleanno dimenticato, le tasse che sapevi di dover pagare. Per queste spese prevedibili apri un secondo salvadanaio separato. Se ogni volta che tocchi il fondo scrivi il motivo su un foglio, scoprirai in fretta quali erano vere emergenze."),
        ("Passo 6 — Ricostruirlo dopo averlo usato", "Usare il fondo non è un fallimento: è esattamente il suo scopo. Dopo un prelievo, torna al bonifico automatico e, se puoi, aumentalo per qualche mese finché non sei tornato all'obiettivo. Rivedi la cifra ogni anno: se il tuo affitto o la tua famiglia sono cresciuti, il fondo deve crescere con loro. Chi ha un fondo di emergenza dorme meglio, negozia con più calma e non finisce in un prestito al consumo al 12% per una gomma bucata."),
    ]},
    "v5-lez-mutuo": {"it": [
        ("Passo 5 — Surroga e estinzione anticipata", "Un mutuo non è una condanna trentennale. Con la surroga puoi trasferirlo gratis a un'altra banca che offre un tasso migliore, come si fa con l'operatore telefonico: se i tassi scendono di un punto, su 150.000 euro risparmi decine di migliaia di euro. Puoi anche estinguerlo in anticipo, in tutto o in parte, senza penali: versare 5.000 euro nei primi anni riduce soprattutto gli interessi futuri, proprio perché all'inizio la rata è quasi tutta interessi."),
        ("Passo 6 — I costi oltre la rata", "La rata è solo una parte del conto. Aggiungi le spese di istruttoria e perizia, l'imposta sostitutiva, il notaio per l'atto di mutuo oltre a quello di compravendita, l'assicurazione incendio obbligatoria e quella sulla vita, spesso proposta dalla banca ma acquistabile altrove a metà prezzo. Il numero che li riassume tutti è il TAEG, non il tasso pubblicizzato: due mutui con lo stesso TAN possono avere TAEG diversi di mezzo punto, e quel mezzo punto vale migliaia di euro."),
    ]},
    "v5-lez-banca-centrale": {"it": [
        ("Passo 5 — Cosa è successo nel 2022", "Il meccanismo si è visto in diretta. Dopo la pandemia e la guerra in Ucraina l'inflazione nell'area euro ha toccato il 10% alla fine del 2022. La BCE ha risposto alzando i tassi da zero al 4% in poco più di un anno: i mutui variabili sono aumentati di centinaia di euro al mese, i prestiti alle imprese sono rallentati, la domanda si è raffreddata e l'inflazione è scesa verso il 2% nel 2024. Un caso da manuale, pagato però da chi aveva debiti a tasso variabile."),
        ("Passo 6 — Come leggere le notizie sui tassi", "Quando senti che la banca centrale alza o taglia i tassi, traduci così. Tassi in aumento: mutui e prestiti più cari, conti deposito più generosi, borsa spesso in calo, valuta più forte, buon momento per risparmiare e cattivo per indebitarsi. Tassi in calo: l'opposto. Le decisioni si prendono circa otto volte l'anno e i mercati provano a indovinarle in anticipo, quindi spesso l'effetto arriva prima dell'annuncio. Non serve prevedere, basta capire in che direzione soffia il vento."),
    ]},
    "v5-lez-costi-nascosti": {"it": [
        ("Passo 5 — Il costo dell'inazione", "Il costo opportunità più sottovalutato è quello del non decidere. Soldi lasciati per anni su un conto corrente a zero perdono ogni anno il valore dell'inflazione, cioè migliaia di euro nel tempo, senza che nessun estratto conto lo mostri. Restare in un lavoro che non piace per non buttare via gli anni di esperienza è costo affondato e costo opportunità insieme. Ogni volta che rimandi una scelta, stai scegliendo comunque: stai scegliendo lo stato attuale."),
        ("Passo 6 — Una domanda per ogni decisione", "Costruisci un'abitudine con due domande. Prima: se non avessi già speso nulla, farei questa scelta oggi? Se la risposta è no, il passato non deve trattenerti. Seconda: qual è la migliore alternativa a cui sto rinunciando? Se non sai rispondere, non hai ancora deciso davvero. Scrivere le due risposte prima di scelte importanti, un acquisto grande, un corso, un cambio di lavoro, richiede tre minuti e ti salva dagli errori più costosi."),
    ]},
    "v5-lez-diversificare": {"it": [
        ("Passo 5 — Diversificare nel tempo", "Esiste anche una diversificazione temporale. Investire tutto in un giorno espone al rischio di entrare al picco; investire una cifra fissa ogni mese, con un piano di accumulo, compra più quote quando i prezzi sono bassi e meno quando sono alti, e riduce l'ansia del momento giusto, che nessuno indovina. E l'orizzonte conta: i soldi che ti serviranno entro tre anni non vanno in borsa, quelli per la pensione possono sopportare oscillazioni ampie."),
        ("Passo 6 — Ribilanciare una volta l'anno", "Con il tempo il paniere si sbilancia: se le azioni salgono molto, finiscono per pesare il 80% invece del 60% previsto, e sei più esposto di quanto volevi. Una volta l'anno riporta le percentuali all'obiettivo vendendo un po' di ciò che è cresciuto e comprando ciò che è sceso: è l'unico modo meccanico per comprare basso e vendere alto senza fare previsioni. Segna la data in calendario e non guardare il portafoglio nel frattempo."),
    ]},
    "v4-tulipani-bolla": {"it": [
        ("Quanto fu grave davvero", "Storici recenti hanno ridimensionato la leggenda. Le compravendite più folli coinvolgevano poche decine di mercanti e artigiani ricchi nelle taverne di Haarlem e Amsterdam, molti contratti non furono mai onorati e il governo li annullò, e l'economia olandese, allora la più forte del mondo, non subì alcun crollo. Le storie di rovine e suicidi vengono in gran parte da opuscoli moralisti scritti dopo, per condannare l'avidità. La bolla fu reale; la catastrofe fu in buona parte letteratura."),
        ("Le bolle dopo i tulipani", "Lo schema è tornato ogni volta con un oggetto diverso. Le azioni della Compagnia del Mississippi nel 1720, le ferrovie inglesi nel 1840, la borsa americana nel 1929, le società internet nel 2000, le case negli Stati Uniti nel 2007, le criptovalute negli anni recenti. Cambiano gli strumenti e le tecnologie, non le persone: ogni generazione si convince che 'questa volta è diverso'. Il tulipano è ancora il modo migliore per ricordarsi che non lo è mai."),
    ]},
    "v4-prezzi-99": {"it": [
        ("Il prezzo tondo del lusso", "Il segno opposto esiste ed è altrettanto studiato. I marchi di lusso e i ristoranti di alto livello usano cifre tonde, 300 euro e non 299, perché il prezzo netto comunica qualità e sicurezza e non chiede al cliente di fare calcoli. Anche i menu eliminano il simbolo dell'euro e i decimali per ridurre la sensazione di spesa. Il ,99 dice 'affare'; il numero tondo dice 'non ti preoccupare del prezzo'. Ogni cifra è una frase rivolta a un cliente diverso."),
        ("Come difenderti", "Il trucco funziona finché non lo guardi in faccia. Una difesa semplice è arrotondare sempre per eccesso mentalmente: 9,99 sono 10, 199 sono 200. Un'altra è confrontare il prezzo al chilo o al litro, stampato in piccolo sull'etichetta dello scaffale, che ignora ogni artificio. Infine, chiediti quale prezzo ti avrebbe fatto esitare: se 200 euro ti sembrano troppi e 199 no, quell'euro sta pensando al posto tuo."),
    ]},
    "v4-banconote-valore": {"it": [
        ("Come nasce una banconota", "Una banconota in euro è un oggetto di alta tecnologia. La carta è di puro cotone, che resiste a migliaia di piegature; contiene filigrana, filo di sicurezza, un ologramma con ritratto, numeri che cambiano colore inclinandola, inchiostri visibili solo agli ultravioletti e microscritture leggibili solo con la lente. Ogni banconota costa alla BCE pochi centesimi ed è progettata per vivere qualche anno prima di essere distrutta e sostituita. È carta, ma carta quasi impossibile da copiare."),
        ("Il denaro che non si vede", "La maggior parte del denaro oggi non è nemmeno carta. In Europa banconote e monete sono meno del 10% della quantità di moneta: il resto sono numeri nei computer delle banche, creati quando una banca concede un prestito e cancellati quando viene ripagato. Un pagamento con carta sposta cifre da un registro a un altro senza che nulla di fisico si muova. La fiducia che sostiene la banconota è la stessa che sostiene quelle cifre: niente di più, niente di meno."),
    ]},
    "v5-diamanti-prezzo": {"it": [
        ("I diamanti sintetici", "Il colpo più duro al monopolio arriva dai laboratori. Dal 2018 i diamanti coltivati in pochi giorni con carbonio e alta pressione sono chimicamente identici a quelli estratti e costano una frazione del prezzo; nel 2024 rappresentano quasi la metà delle pietre vendute negli anelli di fidanzamento americani. Le grandi case cercano di difendere la naturalezza, ma il mercato dei diamanti naturali ha perso valore ogni anno. Una pietra creata in laboratorio non è meno diamante: è solo meno scarsa."),
        ("Il valore della storia", "Perché un diamante, dunque, costa quanto costa? Perché il prezzo non misura la rarità del carbonio ma il valore di una storia condivisa: il fidanzamento, la promessa, la pubblicità del 1947 con lo slogan 'un diamante è per sempre', votato miglior slogan del secolo. Il diamante insegna che il valore di molte cose che compriamo è culturale prima che materiale. Non è un inganno se lo sai: è una scelta."),
    ]},
    "v5-pietre-yap": {"it": [
        ("Il registro invisibile", "Il sistema di Yap funzionava perché tutti gli abitanti ricordavano chi possedeva ogni pietra. Le transazioni erano pubbliche, avvenivano davanti a testimoni e diventavano parte della memoria comune del villaggio. Se qualcuno avesse provato a rivendicare una pietra non sua, l'intera comunità lo avrebbe smentito. Era un libro mastro distribuito, mantenuto nella testa delle persone: ogni scambio valido perché tutti concordavano."),
        ("Yap e le criptovalute", "Gli economisti moderni citano spesso Yap quando spiegano il bitcoin. Anche lì il denaro non si sposta: cambia solo il nome scritto accanto a una cifra in un registro condiviso, la blockchain, che migliaia di computer conservano in copia e su cui devono accordarsi. La pietra in fondo al mare diventa un portafoglio digitale di cui il proprietario ha perso la chiave: tutti sanno che esiste, nessuno può usarlo. Un'isola del Pacifico aveva inventato, con la pietra, l'idea del registro senza banca."),
    ]},
    "v5-miglia-aeree": {"it": [
        ("Il primo programma", "Tutto è iniziato nel 1981 con American Airlines: l'idea era premiare i passeggeri frequenti con voli gratis, sfruttando i posti che sarebbero rimasti comunque vuoti. In pochi mesi tutte le compagnie fecero lo stesso, e nel giro di dieci anni i programmi si aprirono a banche, hotel e autonoleggi. Il passo decisivo fu vendere le miglia alle banche per le carte di credito: da quel momento le miglia non erano più un premio, ma un prodotto."),
        ("Come usarle bene", "Per il passeggero le miglia sono una moneta che vale solo se spesa con criterio. Convertirle in merce o buoni regalo rende pochissimo; usarle per voli intercontinentali in classe business, dove il prezzo in denaro è altissimo, può valere dieci volte di più. Regola pratica: accumula su un solo programma, controlla le scadenze, e non spendere più di quanto avresti speso comunque per guadagnarle. Ricorda che la compagnia può cambiare le regole dall'oggi al domani: le miglia sono un debito che lei stessa può svalutare."),
    ]},
    "v5-latte-fondo": {"it": [
        ("Il livello degli occhi e quello dei bambini", "Anche l'altezza dello scaffale è una scelta calcolata. All'altezza degli occhi stanno i prodotti con il margine più alto o le marche che pagano per quella posizione; in basso i prodotti economici e le marche del supermercato; all'altezza degli occhi di un bambino, cioè in basso, i cereali con i personaggi dei cartoni e i dolciumi. Guardare in alto e in basso, invece che dritto davanti a sé, è il modo più semplice per risparmiare."),
        ("Il supermercato online", "La logica non è sparita con la spesa da casa: si è spostata nell'algoritmo. Le app propongono i prodotti in ordine di margine, suggeriscono 'i clienti hanno comprato anche' e ricordano di aggiungere ciò che è finito. In compenso spariscono gli acquisti d'impulso alla cassa e gli odori del pane: gli studi mostrano che chi fa la spesa online compra meno dolci e snack. Il latte online è in prima pagina; a comprarlo, però, ci arrivi con un percorso disegnato lo stesso."),
    ]},
    "v5-iperinflazione": {"it": [
        ("La vita quotidiana nel caos", "Nella Germania del 1923 gli operai venivano pagati due volte al giorno e correvano a spendere prima che i prezzi cambiassero; le banconote da mille miliardi di marchi valevano meno della carta su cui erano stampate, e la gente le usava per accendere la stufa o tappezzare le pareti. Un pane costava 200 miliardi di marchi. Chi aveva risparmi in banca li vide azzerarsi; chi aveva debiti li estinse con un pugno di carta. Il trauma segnò la Germania per un secolo."),
        ("I paesi che ci vivono oggi", "L'iperinflazione non è un fenomeno del passato. Il Venezuela ha superato il milione per cento nel 2018, lo Zimbabwe ha stampato una banconota da cento trilioni nel 2008 prima di abbandonare la propria moneta, l'Argentina ha convissuto per anni con prezzi che raddoppiavano in dodici mesi. Le cause sono sempre le stesse: spese pubbliche finanziate stampando denaro, perdita di fiducia, fuga verso il dollaro. E la cura è sempre dolorosa: fermare la stampa, tagliare, ricominciare con una moneta nuova."),
    ]},
}
