# Capitoli aggiuntivi — GEOGRAFIA & VIAGGI
EXTRA = {
    "lez-leggere-mappa": {
        "it": [("Passo 6 — Quando il GPS non basta", "Le mappe digitali sono comode, ma hanno limiti che la carta non ha. Il telefono si scarica, il segnale manca in montagna e nelle gole, e il GPS sbaglia di decine di metri in città tra i palazzi. Soprattutto, lo schermo mostra un francobollo di territorio e fa perdere il senso dell'insieme. Il metodo migliore è misto: la carta per capire il quadro e pianificare, il telefono per confermare la posizione. Chi sa leggere una mappa usa il GPS meglio di chi non sa farlo.")],
        "en": [("Step 6 — When GPS is not enough", "Digital maps are convenient, but they have limits paper does not. The phone runs out of battery, the signal fails in mountains and gorges, and GPS is off by tens of metres in cities between buildings. Above all, the screen shows a postage stamp of territory and makes you lose the sense of the whole. The best method is mixed: paper to understand the picture and plan, the phone to confirm your position. Those who can read a map use GPS better than those who cannot.")],
    },
    "lez-fusi-orari": {
        "it": [("Passo 6 — L'ora legale", "Al puzzle dei fusi si aggiunge l'ora legale: circa settanta paesi spostano le lancette avanti di un'ora in primavera per sfruttare la luce della sera, e le riportano indietro in autunno. L'Europa lo fa nell'ultima domenica di marzo e di ottobre, gli Stati Uniti in date diverse, e l'emisfero sud nelle stagioni opposte: per qualche settimana la differenza tra Roma e New York cambia. Molti paesi l'hanno abolita e l'Unione Europea discute da anni se farlo, perché i benefici energetici sono ormai minimi.")],
        "en": [("Step 6 — Daylight saving time", "Daylight saving adds to the time-zone puzzle: about seventy countries move their clocks forward one hour in spring to use evening light, and back in autumn. Europe does it on the last Sunday of March and October, the United States on different dates, and the southern hemisphere in the opposite seasons: for a few weeks the difference between Rome and New York changes. Many countries have abolished it and the European Union has debated doing so for years, since the energy benefits are now minimal.")],
    },
    "v5-lez-coordinate": {"it": [
        ("Passo 5 — Come fa il telefono a saperle", "Il telefono calcola le coordinate ascoltando almeno quattro satelliti GPS, ciascuno dei quali trasmette l'ora esatta e la propria posizione. Dal ritardo con cui arrivano i segnali ricava le distanze e quindi il punto in cui si trova, con una precisione di pochi metri. Nelle città usa anche le reti Wi-Fi e le celle telefoniche per correggere. I sistemi europei Galileo e russi GLONASS funzionano allo stesso modo e i telefoni moderni li combinano tutti."),
        ("Passo 6 — Comunicare una posizione", "Se devi indicare un punto a un soccorritore o a un amico, le coordinate decimali sono la forma più sicura: 45.4642, 9.1900 è il Duomo di Milano e funziona in qualsiasi app. Nelle app di mappe puoi tenere premuto un punto per leggerle e copiarle. Esistono anche sistemi alternativi come what3words, che assegna tre parole a ogni quadrato di tre metri del pianeta, usato dai servizi di emergenza britannici. Ma i gradi restano la lingua universale."),
    ]},
    "v5-lez-montagne": {"it": [
        ("Passo 5 — Perché non crescono all'infinito", "Se le Alpi si alzano di un millimetro l'anno da milioni di anni, perché non sono alte cinquanta chilometri? Perché l'erosione le consuma quasi alla stessa velocità: pioggia, gelo, ghiacciai e frane portano via ogni anno tanto materiale quanto ne viene sollevato. Inoltre la crosta terrestre galleggia sul mantello e una montagna troppo pesante affonda. Il limite teorico sulla Terra è intorno ai dieci chilometri; l'Everest, con 8.849 metri, è vicino al massimo possibile."),
        ("Passo 6 — Le montagne degli altri pianeti", "Il confronto con altri mondi conferma la regola. Su Marte, con una gravità un terzo della nostra e senza placche in movimento, il vulcano Olympus Mons ha potuto crescere per miliardi di anni sullo stesso punto fino a 22 chilometri, due volte e mezzo l'Everest. Su Venere le montagne sono modeste perché la crosta è calda e cede. Guardando l'altezza dei rilievi, i geologi capiscono come funziona l'interno di un pianeta senza scavare."),
    ]},
    "v5-lez-correnti-clima": {"it": [
        ("Passo 5 — Il caso dell'Italia", "L'Italia stessa è un laboratorio di questi fattori. Milano e Genova sono alla stessa latitudine, ma Genova ha inverni di quattro gradi più miti grazie al mare che la protegge dal freddo e alle Alpi che fermano i venti da nord. Trieste soffre la bora, un vento gelido che scende dall'altopiano carsico. La Sicilia riceve lo scirocco carico di sabbia dal Sahara. In poche centinaia di chilometri l'Italia raccoglie climi che altrove si trovano a migliaia di chilometri di distanza."),
        ("Passo 6 — Cosa cambia con il clima che cambia", "Il riscaldamento globale sta modificando questi equilibri. La corrente del Golfo mostra segni di rallentamento a causa dell'acqua dolce dei ghiacci della Groenlandia, e un suo indebolimento raffredderebbe paradossalmente l'Europa nordoccidentale. Il Mediterraneo si scalda più in fretta della media e alimenta tempeste più intense. Capire perché Roma e New York hanno inverni diversi serve anche a prevedere come cambieranno nei prossimi decenni."),
    ]},
    "v5-lez-jet-lag": {"it": [
        ("Passo 5 — Melatonina e caffeina", "Due sostanze possono aiutare, se usate con precisione. La melatonina, in dose bassa da 0,5 a 3 milligrammi, presa all'ora in cui vorresti dormire nel nuovo fuso, anticipa l'orologio quando vai verso est; è disponibile senza ricetta ma va concordata con il medico se prendi altri farmaci. La caffeina è utile al mattino nel nuovo fuso per restare svegli, dannosa dopo le 14 locali. L'alcol invece peggiora tutto: frammenta il sonno e disidrata."),
        ("Passo 6 — Il jet lag sociale", "Il jet lag colpisce anche chi non vola. Chi va a letto alle 2 nel fine settimana e alle 23 nei giorni lavorativi sposta ogni settimana il proprio orologio come se volasse da Roma a Mosca e ritorno: è il jet lag sociale, associato a stanchezza cronica, umore basso e aumento di peso. Gli stessi rimedi valgono anche qui: orari costanti, luce al mattino, buio alla sera. Il corpo non distingue un fuso orario da un sabato notte."),
    ]},
    "v5-lez-leggere-valle": {"it": [
        ("Passo 5 — Le firme dell'uomo", "Anche noi lasciamo firme nel paesaggio, e sono facili da confondere con quelle naturali. I terrazzamenti sui versanti sono agricoltura di secoli; un fiume che scorre dritto tra argini regolari è stato canalizzato; un lago con una diga di cemento a un'estremità è artificiale; i cumuli di sassi in mezzo ai campi sono spietramenti. In Italia quasi nessun paesaggio è del tutto naturale: leggere una valle significa leggere anche la sua storia umana."),
        ("Passo 6 — Esercizio sul campo", "La prossima volta che sei in montagna, prova questo esercizio in dieci minuti. Guarda il profilo della valle dalla strada: a U o a V? Cerca massi isolati di roccia diversa da quella circostante e pareti lisce con striature: ghiaccio. Cerca strette gole, meandri e ghiaie sul fondo: acqua. Osserva dove sta il paese: sui conoidi laterali, al sicuro dalle piene. Poi racconta la storia in tre frasi: cosa c'era, cosa l'ha scolpito, cosa succede adesso."),
    ]},
    "v5-point-nemo": {"it": [
        ("La vita al punto Nemo", "Point Nemo è uno dei luoghi meno vivi dell'oceano. Si trova al centro del vortice del Pacifico meridionale, una zona dove le correnti girano in tondo e impediscono l'arrivo dei nutrienti dalle coste; senza nutrienti non c'è plancton, e senza plancton non ci sono pesci. L'acqua è tra le più trasparenti del pianeta. Gli unici abitanti sono batteri e piccoli organismi attorno alle sorgenti idrotermali del fondale, a quattro chilometri di profondità."),
        ("Chi ci è arrivato", "Nel 2018 gli skipper della Volvo Ocean Race hanno attraversato Point Nemo durante la regata attorno al mondo, e nel 2024 una spedizione scientifica lo ha raggiunto per la prima volta di proposito, con lo scopo di studiare il fondale e la plastica che si accumula nel vortice. I navigatori raccontano un'esperienza inquietante: giorni senza vedere una nave, un uccello o un aereo, con la certezza che in caso di emergenza il soccorso più vicino sarebbe a una settimana di distanza."),
    ]},
    "v5-samoa-giorno": {"it": [
        ("Il paradosso delle Samoa Americane", "A settanta chilometri dalle Samoa indipendenti ci sono le Samoa Americane, che nel 2011 non seguirono il cambio. Da allora le due isole, così vicine da vedersi nelle giornate limpide, hanno un giorno di differenza: quando nelle Samoa è lunedì mattina, nelle Samoa Americane è ancora domenica mattina. Sono l'ultimo posto al mondo dove finisce ogni giorno del calendario, e i tour operator vendono la possibilità di festeggiare due volte il Capodanno con un volo di trenta minuti."),
        ("Il fuso come scelta economica", "Il fuso orario è uno strumento politico più che geografico. La Spagna vive un'ora avanti rispetto al suo sole dal 1940, quando Franco si allineò alla Germania nazista, e per questo gli spagnoli cenano alle dieci. La Cina, larga cinquemila chilometri, impone un solo fuso per unità nazionale, e nello Xinjiang il sole sorge alle dieci. La Corea del Nord nel 2015 creò un fuso tutto suo, spostato di trenta minuti, per poi abolirlo tre anni dopo come gesto di distensione verso il Sud."),
    ]},
    "v5-citta-piu-fredda": {"it": [
        ("Cosa succede al corpo a -50", "A quelle temperature l'aria fa male a respirare: si inspira attraverso una sciarpa per non gelare i polmoni, e il vapore del respiro si trasforma in cristalli con un lieve fruscio che i locali chiamano il sussurro delle stelle. Le ciglia si coprono di ghiaccio, gli occhiali di metallo non si possono indossare, la pelle esposta congela in pochi minuti. Eppure gli abitanti raccontano che il freddo secco e senza vento di Jakutsk si sopporta meglio di uno zero umido europeo."),
        ("L'economia del ghiaccio", "Il freddo estremo è anche una risorsa. Il suolo permanentemente gelato conserva i corpi di mammut con pelo e carne, che si affacciano dalle sponde dei fiumi e alimentano un commercio di zanne d'avorio legale, l'unico al mondo. I mercati vendono pesce e carne all'aperto senza frigoriferi, impilati come legna. Ma il permafrost si sta scaldando: gli edifici si inclinano, le strade si deformano e il metano intrappolato da millenni inizia a uscire, accelerando il cambiamento che lo libera."),
    ]},
    "v5-sahara-verde": {"it": [
        ("Il Sahara che nutre l'Amazzonia", "Il deserto di oggi è legato alla foresta più grande del mondo. Ogni anno i venti sollevano dal Sahara oltre cento milioni di tonnellate di polvere e le trasportano attraverso l'Atlantico; circa venti milioni si depositano sull'Amazzonia, portando fosforo, un nutriente che il suolo tropicale perde di continuo con le piogge. La polvere viene in gran parte da un'unica depressione in Ciad, il letto di un antico lago del Sahara verde. Il fondo di un lago scomparso fertilizza la giungla."),
        ("Le persone del Sahara verde", "Il periodo umido non fu solo un fatto climatico: fu un mondo abitato. Pastori con mandrie di bovini vivevano dove oggi ci sono solo dune; nel sito di Gobero, in Niger, sono state trovate centinaia di tombe di due popolazioni diverse vissute a distanza di millenni. Quando le piogge cessarono, tra 6.000 e 4.000 anni fa, le comunità si spostarono verso il Nilo e contribuirono probabilmente alla nascita della civiltà egizia. Il deserto ha spinto gli uomini a costruire uno dei primi Stati della storia."),
    ]},
    "v5-mediterraneo-secco": {"it": [
        ("La vita nel deserto di sale", "Durante la crisi di salinità il fondo del Mediterraneo divenne un ambiente da altro pianeta: laghi ipersalini, saline sterminate, temperature estive da forno per via della depressione di migliaia di metri sotto il livello del mare. Le isole di oggi erano montagne su una pianura di sale. Alcuni animali attraversarono a piedi i ponti di terra: elefanti nani e ippopotami raggiunsero così Cipro, Creta e la Sicilia, dove i loro resti fossili hanno ispirato forse il mito dei Ciclopi."),
        ("Potrebbe succedere ancora", "Il Mediterraneo dipende da Gibilterra come una vasca dal rubinetto: evapora più acqua di quanta ne ricevano i fiumi, e ogni anno l'Atlantico ne versa la differenza attraverso uno stretto largo appena quattordici chilometri. L'Africa continua a spingere verso l'Europa di pochi millimetri l'anno, e i geologi ritengono che tra alcuni milioni di anni lo stretto si chiuderà di nuovo. Il mare che ha fatto nascere Fenici, Greci e Romani è, su scala geologica, un lago temporaneo."),
    ]},
}
