# Capitoli aggiuntivi — NATURA
EXTRA = {
    "v4-lez-fotosintesi": {"it": [
        ("Passo 5 — Di notte e in inverno", "La fotosintesi si ferma senza luce, ma la pianta non muore. Di notte respira come noi: consuma una parte dello zucchero prodotto di giorno e rilascia anidride carbonica. Nei giorni corti d'inverno il bilancio è quasi in pari, e per questo molti alberi lasciano cadere le foglie: mantenerle costerebbe più di quanto producono. I sempreverdi tengono aghi cerosi che resistono al gelo e fotosintetizzano a rilento nelle giornate miti."),
        ("Passo 6 — Copiare la foglia", "Gli scienziati provano da decenni a imitare la foglia. La fotosintesi artificiale usa catalizzatori e luce per spezzare l'acqua e produrre idrogeno o combustibili dal CO2, con un'efficienza che in laboratorio supera già quella delle piante, ferma intorno all'1-2%. Il problema è il costo e la durata dei materiali. Se funzionasse su larga scala, avremmo carburante pulito prodotto direttamente dal sole e dall'aria, esattamente come fa un filo d'erba da mezzo miliardo di anni."),
    ]},
    "v4-lez-orientarsi-natura": {"it": [
        ("Passo 5 — L'orologio come bussola", "Se hai un orologio analogico, hai una bussola approssimativa. Nell'emisfero nord punta la lancetta delle ore verso il Sole: il sud si trova a metà strada tra quella lancetta e le ore 12. Con l'ora legale usa le 13 al posto delle 12. Il metodo funziona anche con un orologio digitale, basta immaginare il quadrante. L'errore può arrivare a 20-30 gradi, ma per scegliere la direzione generale di una valle è più che sufficiente."),
        ("Passo 6 — Il vento e la neve", "Il paesaggio conserva la memoria dei venti dominanti. Sulle creste alpine la neve si accumula sul lato sottovento e forma cornici; gli alberi isolati crescono piegati e con i rami solo da un lato, opposto alla direzione da cui soffia il vento prevalente, che in gran parte d'Italia arriva da ovest o nord-ovest. Le dune di sabbia hanno il pendio dolce verso il vento e quello ripido dall'altra parte. Nessuno di questi indizi da solo è certo: tre indizi concordi lo sono quasi."),
    ]},
    "v4-lez-leggere-fiume": {"it": [
        ("Passo 5 — Il colore e la temperatura", "Il colore dell'acqua racconta da dove viene. Verde-azzurro lattiginoso significa acqua di fusione glaciale ricca di sedimenti finissimi, gelida anche in agosto; marrone significa piena recente o terreno argilloso a monte; limpida e scura, acqua di sorgente o di lago. Un fiume che diventa torbido improvvisamente mentre il cielo è sereno dice che a monte sta piovendo o che una diga ha aperto le paratoie: è il momento di uscire dall'acqua."),
        ("Passo 6 — Attraversare in sicurezza", "Se devi attraversare un torrente, scegli il punto più largo e non il più stretto: dove l'alveo si restringe l'acqua accelera e si approfondisce. Cerca il tratto increspato e basso, mai il liscio profondo. Slaccia lo zaino, tieni un bastone a monte come terzo appoggio, avanza di lato e non guardare l'acqua che scorre ma la sponda. Con acqua sopra il ginocchio e corrente sostenuta non attraversare: la spinta cresce con il quadrato della velocità."),
    ]},
    "lez-ciclo-acqua": {
        "it": [("Fase 6 — Il ciclo che cambia", "Il ciclo dell'acqua sta accelerando. Un'atmosfera più calda trattiene circa il 7% di vapore in più per ogni grado, quindi evapora di più e, quando piove, piove più forte: alluvioni più intense nelle zone umide, siccità più lunghe in quelle aride, perché la stessa quantità d'acqua si concentra in meno eventi. In Italia i ghiacciai alpini, serbatoio estivo del Po, hanno perso metà del volume dal 1900. Capire il ciclo serve a capire perché le notizie sul meteo sembrano sempre più estreme.")],
        "en": [("Phase 6 — A changing cycle", "The water cycle is speeding up. A warmer atmosphere holds about 7% more vapour per degree, so more water evaporates and, when it rains, it rains harder: more intense floods in wet regions, longer droughts in arid ones, because the same amount of water is concentrated in fewer events. In Italy Alpine glaciers, the summer reservoir of the Po, have lost half their volume since 1900. Understanding the cycle helps explain why weather news seems ever more extreme.")],
    },
    "lez-leggere-nuvole": {
        "it": [("Passo 6 — Le nuvole speciali", "Alcune nuvole valgono la pena di essere riconosciute per il loro spettacolo. Le lenticolari, a forma di disco, si formano sopra le montagne e restano ferme mentre il vento le attraversa: spesso vengono scambiate per dischi volanti. Le mammatus, sacche pendenti sotto un temporale, indicano turbolenza estrema. Le scie degli aerei che persistono e si allargano segnalano aria umida in quota e spesso precedono un peggioramento. Le nubi nottilucenti, altissime e argentate, si vedono solo d'estate dopo il tramonto verso nord.")],
        "en": [("Step 6 — Special clouds", "Some clouds are worth recognising for their show. Lenticular clouds, disc-shaped, form over mountains and stay still while the wind flows through them: they are often mistaken for flying saucers. Mammatus, pouches hanging under a thunderstorm, indicate extreme turbulence. Aircraft contrails that persist and spread signal humid air aloft and often precede worsening weather. Noctilucent clouds, very high and silvery, are visible only in summer after sunset towards the north.")],
    },
    "v5-lez-riconoscere-alberi": {"it": [
        ("Passo 5 — Corteccia, frutti e gemme", "Quando le foglie mancano, in inverno, il tronco parla. La betulla ha corteccia bianca che si sfoglia; il platano chiazze verdi e gialle; il ciliegio strisce orizzontali; il pino a maturità placche rossastre. I frutti caduti sono indizi certi: ghiande per la quercia, castagne con riccio, samare a elica per l'acero, pigne. Le gemme invernali del faggio sono lunghe e appuntite, quelle dell'ippocastano grandi e appiccicose. Un albero si riconosce in ogni stagione."),
        ("Passo 6 — I cinque alberi da sapere", "Comincia da cinque specie che incontri ovunque in Italia. La quercia, con la foglia lobata e la ghianda. Il faggio, con la foglia ovale a margine ondulato e la corteccia liscia grigia. Il pino, con gli aghi a coppie e la corteccia a placche. Il platano dei viali cittadini, con la foglia a cinque punte e la corteccia a chiazze. L'ulivo, con la foglia stretta argentata sotto. Riconoscerli ti farà notare che una città o un bosco sono fatti di individui, non di verde."),
    ]},
    "v5-lez-terremoti": {"it": [
        ("Passo 5 — Perché non si possono prevedere", "Nessuno sa prevedere un terremoto con giorno e luogo, e chi lo promette mente. La roccia si spezza quando lo sforzo accumulato supera la resistenza, ma non c'è modo di misurare né l'uno né l'altra in profondità. Quel che la scienza fa è la previsione probabilistica: sa quali zone d'Italia hanno più probabilità di forti scosse nei prossimi decenni, e su questo si basano le mappe di pericolosità e le norme di costruzione. L'unica difesa vera è costruire bene prima."),
        ("Passo 6 — Rendere sicura la casa", "Il terremoto non uccide: uccidono gli edifici. Verifica se la tua casa è stata costruita o adeguata secondo le norme antisismiche; in Italia molte case sono precedenti al 1974, quando entrarono in vigore le prime regole moderne. In casa fissa al muro librerie e mobili alti, tieni una torcia e le scarpe vicino al letto, individua i punti sicuri e il luogo di ritrovo fuori. Il bonus per gli interventi antisismici rende gli adeguamenti meno costosi di quanto si pensi."),
    ]},
    "v5-lez-suolo": {"it": [
        ("Passo 5 — Il suolo e il clima", "Il suolo è il secondo serbatoio di carbonio del pianeta dopo gli oceani: contiene più carbonio dell'atmosfera e di tutta la vegetazione messe insieme, sotto forma di humus e radici. Quando viene arato in profondità o cementificato, quel carbonio si ossida e finisce nell'aria. Pratiche come la semina senza aratura, le colture di copertura e il compost lo riportano sottoterra. Un campo ben gestito è una macchina che toglie CO2 dall'atmosfera."),
        ("Passo 6 — Un test in giardino", "Vuoi sapere se il tuo suolo è vivo? Fai il test del bicchiere: metti una manciata di terra in un barattolo con acqua, agita e lascia riposare un giorno. In fondo si depositerà la sabbia, poi il limo, sopra l'argilla, e la materia organica galleggerà: le proporzioni ti dicono la tessitura. Poi il test più semplice di tutti: scava una vanga di terra e conta i lombrichi. Più di cinque per vangata significa un suolo in buona salute."),
    ]},
    "v5-lez-ecosistema": {"it": [
        ("Passo 5 — Le specie chiave", "Non tutte le specie pesano allo stesso modo. Alcune, chiamate specie chiave, tengono in piedi l'intero sistema pur essendo poco numerose. Le lontre marine mangiano i ricci che altrimenti divorerebbero le foreste di alghe kelp; i castori costruiscono dighe che creano stagni per centinaia di altre specie; i fichi tropicali fruttificano tutto l'anno e sfamano gli animali quando non c'è altro. Toglierne una equivale a togliere la chiave di volta di un arco."),
        ("Passo 6 — L'ecosistema di un balcone", "Anche un vaso sul balcone è un piccolo ecosistema. Le piante producono, gli afidi consumano, le coccinelle li predano, i lombrichi e i funghi nel terriccio decompongono le foglie morte. Se elimini gli afidi con un insetticida, le coccinelle spariscono e alla prossima invasione non avrai difese; se lasci fare, in due settimane il sistema si riequilibra. Osservare un vaso per una stagione insegna i quattro ruoli meglio di qualsiasi libro."),
    ]},
    "v5-lez-compost": {"it": [
        ("Passo 5 — Risolvere i problemi", "Il compost parla, basta ascoltarlo. Odore di uova marce o di ammoniaca significa troppo umido e troppo verde: aggiungi cartone e foglie secche e rimescola. Se non succede nulla per settimane è troppo secco o povero di azoto: inumidisci e aggiungi scarti di cucina. I moscerini della frutta compaiono se gli scarti sono scoperti: coprili sempre con uno strato di marrone. Topi e ratti arrivano solo con carne, pesce e formaggi, che nel compost domestico non vanno mai."),
        ("Passo 6 — Il compost in appartamento", "Senza giardino ci sono due strade. La compostiera elettrica, che essicca e tritura gli scarti in poche ore producendo un ammendante secco. Oppure il vermicompost: una cassetta a strati con lombrichi rossi californiani che, sul balcone o sotto il lavello, trasformano gli scarti di cucina in humus finissimo e in un liquido fertilizzante. Non puzza, occupa quanto una cassetta della frutta e riduce di un terzo il sacco dell'umido."),
    ]},
    "volcanoes-basics": {
        "it": [("I vulcani italiani", "L'Italia è l'unico paese dell'Europa continentale con vulcani attivi. L'Etna è il più alto d'Europa e uno dei più attivi al mondo, con eruzioni quasi ogni anno; lo Stromboli erutta piccole esplosioni ogni venti minuti da almeno duemila anni, e per questo i marinai lo chiamavano il faro del Mediterraneo. Il Vesuvio dorme dal 1944 con tre milioni di persone attorno, e i Campi Flegrei, un supervulcano sotto Pozzuoli, sollevano il suolo di centimetri l'anno sotto lo sguardo attento dell'INGV.")],
        "en": [("Italy's volcanoes", "Italy is the only country in mainland Europe with active volcanoes. Etna is Europe's highest and one of the most active in the world, erupting almost every year; Stromboli has produced small explosions every twenty minutes for at least two thousand years, which is why sailors called it the lighthouse of the Mediterranean. Vesuvius has slept since 1944 with three million people around it, and the Campi Flegrei, a supervolcano under Pozzuoli, raise the ground by centimetres a year under the close watch of the INGV.")],
    },
    "why-seasons": {
        "it": [("Le stagioni degli altri pianeti", "Ogni pianeta ha le stagioni che la sua inclinazione gli concede. Marte, inclinato quasi come la Terra, ha stagioni simili ma lunghe il doppio, con calotte polari che crescono e si sciolgono. Urano è coricato di 98 gradi: ogni polo resta 42 anni alla luce e 42 al buio. Giove, quasi verticale, non ha stagioni. Venere, capovolta di 177 gradi, ne ha pochissime. La nostra inclinazione di 23,4 gradi è un caso fortunato che dà stagioni marcate ma vivibili.")],
        "en": [("Seasons on other planets", "Each planet has the seasons its tilt allows. Mars, tilted almost like Earth, has similar seasons but twice as long, with polar caps that grow and melt. Uranus lies on its side at 98 degrees: each pole spends 42 years in light and 42 in darkness. Jupiter, almost upright, has no seasons. Venus, flipped at 177 degrees, has very few. Our 23.4-degree tilt is a lucky accident that gives marked but liveable seasons.")],
    },
    "how-trees-live": {
        "it": [("L'albero più vecchio del mondo", "In Svezia un abete rosso chiamato Old Tjikko ha radici di 9.550 anni: il tronco che vediamo ha poche centinaia di anni, ma l'apparato radicale continua a produrre nuovi fusti da quando finì l'ultima glaciazione. In California i pini dai coni setolosi superano i 4.800 anni con un solo tronco contorto. E in Utah un bosco di pioppi tremuli, Pando, è un unico individuo di 47.000 fusti collegati dalle radici, forse vecchio di decine di migliaia di anni. Un albero può essere più antico di ogni civiltà.")],
        "en": [("The oldest tree in the world", "In Sweden a Norway spruce called Old Tjikko has roots 9,550 years old: the trunk we see is a few hundred years old, but the root system has kept producing new stems since the last ice age ended. In California bristlecone pines exceed 4,800 years with a single twisted trunk. And in Utah a grove of quaking aspens, Pando, is a single individual of 47,000 stems connected by roots, perhaps tens of thousands of years old. A tree can be older than any civilisation.")],
    },
    "why-oceans-salty": {
        "it": [("Il sale come risorsa", "Da quel sale l'uomo ha costruito economie. Le saline, dove l'acqua marina evapora in vasche poco profonde, funzionano da millenni in Sicilia, in Sardegna e a Cervia; nell'antica Roma il sale era così prezioso da dare il nome al salario dei soldati e alla via Salaria. Oggi la dissalazione fa il percorso inverso: oltre ventimila impianti nel mondo tolgono il sale al mare per produrre acqua potabile, soprattutto nel Golfo Persico, a un costo energetico che le nuove membrane stanno riducendo.")],
        "en": [("Salt as a resource", "From that salt humans built economies. Salt pans, where seawater evaporates in shallow basins, have operated for millennia in Sicily, Sardinia and Cervia; in ancient Rome salt was so precious it gave its name to the soldiers' salary and to the Via Salaria. Today desalination goes the other way: over twenty thousand plants worldwide remove salt from the sea to produce drinking water, especially in the Persian Gulf, at an energy cost that new membranes are reducing.")],
    },
    "how-glaciers-move": {
        "it": [("Archivi di ghiaccio", "Ogni strato di neve compressa intrappola bolle d'aria dell'epoca in cui è caduto. Carotando i ghiacciai dell'Antartide, i ricercatori hanno estratto aria di 800.000 anni fa e ricostruito temperatura e CO2 di otto ere glaciali. Anche i ghiacciai alpini conservano storie: polveri del Sahara, piombo delle miniere romane, il fallout dei test nucleari degli anni Sessanta, il corpo di Ötzi, l'uomo di 5.300 anni riemerso nel 1991. Quando un ghiacciaio si scioglie, si perde una biblioteca.")],
        "en": [("Archives of ice", "Every layer of compressed snow traps air bubbles from the time it fell. By coring Antarctic glaciers, researchers have extracted air from 800,000 years ago and reconstructed temperature and CO2 across eight ice ages. Alpine glaciers keep stories too: Saharan dust, lead from Roman mines, fallout from 1960s nuclear tests, the body of Ötzi, the 5,300-year-old man who reappeared in 1991. When a glacier melts, a library is lost.")],
    },
    "v4-foglie-autunno": {"it": [
        ("Perché l'albero le lascia cadere", "La caduta è un'operazione pianificata, non una morte per freddo. Prima di lasciare andare la foglia, l'albero ne recupera azoto, fosforo e zuccheri e li immagazzina nei rami e nelle radici per la primavera successiva; poi costruisce alla base del picciolo uno strato di cellule che sigilla la ferita e si sfalda, e la foglia si stacca al primo vento. È lo stesso meccanismo con cui un frutto maturo cade. Il tappeto di foglie nutrirà poi il suolo del bosco."),
        ("L'autunno che si sposta", "Il cambiamento climatico sta modificando il calendario del foliage. Autunni più caldi ritardano i colori di alcuni giorni per decennio, e le siccità estive fanno cadere le foglie ancora verdi senza spettacolo. Gli scienziati usano i dati delle foglie, raccolti anche da cittadini volontari, per misurare il ritmo delle stagioni. In Nord America e in Giappone il foliage vale miliardi di turismo, e le previsioni dei colori sono seguite come quelle del meteo."),
    ]},
    "v4-fulmini": {"it": [
        ("Fulmini strani", "Non tutti i fulmini vanno dalla nube al suolo. La maggior parte scarica dentro la nube stessa o tra due nubi. Sopra i grandi temporali, a decine di chilometri di altezza, compaiono per pochi millesimi di secondo gli sprite, scariche rosse a forma di medusa scoperte solo nel 1989. I fulmini vulcanici nascono dalle ceneri che si caricano sfregandosi. E i fulmini globulari, sfere luminose che galleggiano per secondi, sono stati filmati ma non ancora spiegati del tutto."),
        ("Come proteggersi", "Durante un temporale il posto più sicuro è un edificio chiuso o un'auto con il tetto in metallo, che funziona come una gabbia di Faraday: la corrente scorre sulla carrozzeria e non dentro. Fuori, evita alberi isolati, creste e specchi d'acqua, e non sdraiarti a terra: accovacciati con i piedi uniti. La regola 30-30: se tra lampo e tuono passano meno di 30 secondi, il fulmine è a meno di dieci chilometri e devi ripararti; aspetta 30 minuti dall'ultimo tuono prima di uscire."),
    ]},
    "v4-funghi-rete": {"it": [
        ("Le madri della foresta", "Gli alberi più grandi e vecchi, che l'ecologa Suzanne Simard chiama alberi madre, sono i nodi principali della rete: sono collegati a centinaia di alberi vicini e passano zuccheri ai giovani cresciuti nella loro ombra, che da soli non ricevono abbastanza luce. Quando un albero madre viene tagliato, la sopravvivenza delle piantine attorno cala drasticamente. Gli esperimenti con carbonio marcato hanno mostrato che gli alberi riconoscono persino i propri semenzali e li favoriscono."),
        ("Anche i funghi hanno un prezzo", "La rete non è un'utopia di generosità. I funghi trattano: alcune specie forniscono più fosforo agli alberi che li ripagano con più zucchero e riducono le forniture a chi dà poco, un vero mercato sotterraneo. Alcune piante, come certe orchidee senza clorofilla, rubano dalla rete senza dare nulla. E i funghi possono trasmettere anche malattie. Il bosco è una società complessa, con alleanze, scambi e qualche parassita, molto più simile alla nostra di quanto sembri."),
    ]},
    "v5-seme-germoglia": {"it": [
        ("I semi che aspettano secoli", "Alcuni semi possono aspettare tempi lunghissimi. Nel 2005 in Israele è germogliata una palma da dattero da un seme di duemila anni trovato a Masada; nel 2012 ricercatori russi hanno fatto fiorire una pianta artica da tessuti congelati nel permafrost siberiano per 32.000 anni. Il segreto è la disidratazione estrema, che ferma quasi ogni reazione chimica, e a volte il freddo. Nella banca dei semi delle Svalbard, scavata nel ghiaccio, oltre un milione di campioni aspettano un futuro incerto."),
        ("Ingannare il seme in cucina e in giardino", "I giardinieri sfruttano questi segnali ogni giorno. Mettere i semi di melo o di lavanda in frigorifero per qualche settimana nella sabbia umida imita l'inverno e li sblocca: si chiama vernalizzazione. Scarnificare con carta vetrata i semi dal guscio duro, come quelli di ipomea, fa entrare l'acqua. Un ammollo di una notte accelera fagioli e piselli. E i germogli che mangiamo in insalata sono semi convinti che sia primavera, raccolti tre giorni dopo il risveglio."),
    ]},
    "v5-neve-bianca": {"it": [
        ("Le nevi colorate", "La neve non è sempre bianca. In montagna, a fine primavera, compaiono chiazze rosa o rosse chiamate neve di sangue o neve d'anguria: sono alghe microscopiche con pigmenti rossi che le proteggono dai raggi ultravioletti. La neve verde cresce in Antartide dove i pinguini la concimano. La neve nera o grigia delle città è fuliggine e pneumatici. E la neve arancione caduta sull'Europa orientale nel 2018 era sabbia del Sahara sollevata da una tempesta e mescolata alle nubi."),
        ("Il bianco che raffredda il pianeta", "Il colore della neve ha un peso sul clima. Una superficie innevata riflette fino al 90% della luce solare, il mare scuro ne assorbe oltre il 90%. Quando i ghiacci artici si sciolgono, l'acqua scoperta assorbe più calore, scioglie altro ghiaccio e il ciclo si rinforza: si chiama retroazione dell'albedo ed è uno dei motivi per cui l'Artico si scalda quattro volte più veloce del resto del pianeta. Il bianco della neve non è solo bello: è un condizionatore globale."),
    ]},
    "v5-geyser": {"it": [
        ("Old Faithful e la puntualità imperfetta", "Il geyser più famoso, Old Faithful a Yellowstone, erutta ogni 60-110 minuti da quando è stato scoperto nel 1870 e i ranger prevedono l'orario con un margine di dieci minuti osservando la durata dell'eruzione precedente: una lunga svuota di più il serbatoio e allunga l'attesa. I geyser però cambiano: terremoti lontani, cambi nel sistema idrico e persino oggetti lanciati dai turisti hanno spento geyser che eruttavano da secoli. Sono orologi geologici delicatissimi."),
        ("Energia dal sottosuolo", "Gli stessi sistemi che alimentano i geyser producono elettricità. L'Islanda ricava dalla geotermia gran parte del riscaldamento e un quarto dell'elettricità; in Italia la centrale di Larderello, in Toscana, è la più antica del mondo, attiva dal 1904, e i soffioni boraciferi che la alimentano erano descritti già da Dante. Il vapore che spinge fuori una colonna d'acqua a Yellowstone e quello che fa girare una turbina in Toscana è lo stesso: la Terra che si raffredda dall'interno."),
    ]},
    "v5-fiori-notte": {"it": [
        ("L'orologio floreale di Linneo", "Nel 1751 il botanico Carl Linneo propose un orologio fatto di fiori: piantando in cerchio specie che si aprono a ore diverse, si sarebbe potuta leggere l'ora guardando quali corolle erano aperte. Il tarassaco alle cinque, la calendula alle nove, la bella di notte alle sedici, la belladonna alle diciotto. L'idea era poetica ma imprecisa, perché il tempo di apertura dipende anche da latitudine e stagione; è però la prova che la puntualità delle piante si conosce da secoli."),
        ("Le piante che dormono", "Anche le foglie si muovono di notte. Il trifoglio, il fagiolo e molte leguminose piegano le foglie verso il basso al tramonto e le rialzano all'alba; Darwin scrisse un intero libro su questi movimenti e li chiamò sonno delle piante. Servono forse a ridurre la perdita di calore o l'accumulo di rugiada. Nel 2016 i ricercatori hanno scoperto con i laser che perfino le betulle abbassano i rami di dieci centimetri durante la notte: gli alberi, in un certo senso, dormono."),
    ]},
    "v5-odore-pioggia": {"it": [
        ("L'ozono prima del temporale", "L'odore che precede una tempesta è diverso da quello che segue una pioggia leggera. I fulmini spezzano le molecole di ossigeno nell'aria e formano ozono, che ha un odore pungente, quasi metallico, e che i venti discendenti del temporale portano al suolo prima delle gocce. Per questo si può davvero sentire l'odore di un temporale in arrivo. La geosmina e gli oli delle piante arrivano dopo, quando le prime gocce toccano il terreno."),
        ("La geosmina in cucina", "La stessa molecola della pioggia finisce nel piatto. La geosmina dà alla barbabietola il suo sapore terroso, ed è il motivo per cui alcuni la amano e altri la detestano; contamina il vino quando l'uva è stata colpita da muffe, e dà a certi pesci d'acqua dolce, come carpe e pesci gatto, il tipico gusto di fango. Le cantine e gli allevamenti la combattono come un difetto. Il nostro naso, che la rileva a concentrazioni di poche parti per trilione, non la dimentica mai."),
    ]},
}
