# Capitoli aggiuntivi — PSICOLOGIA
EXTRA = {
    "v4-lez-abitudini": {"it": [
        ("Passo 5 — Cambia l'ambiente, non la volontà", "L'abitudine più facile è quella che l'ambiente rende inevitabile. Vuoi leggere di più? Metti il libro sul cuscino e il telefono a caricare in un'altra stanza. Vuoi mangiare meglio? La frutta sul tavolo, i biscotti nell'armadio in alto. Gli studi sulle mense mostrano che spostare un cibo di trenta centimetri cambia i consumi del 20%. Ogni sera prepara la scena del giorno dopo: la tuta accanto al letto vale più di qualsiasi motivazione."),
        ("Passo 6 — Quanto ci vuole davvero", "Il mito dei 21 giorni è falso. Uno studio dell'University College London ha misurato che un'abitudine diventa automatica in media dopo 66 giorni, con enormi differenze: 18 giorni per bere un bicchiere d'acqua a colazione, oltre 250 per fare cinquanta addominali. Bevi la notizia come una liberazione: se dopo un mese ti costa ancora fatica, non stai sbagliando, sei nella media. La curva sale piano e poi, un giorno, non ci pensi più."),
    ]},
    "v4-lez-ascolto-attivo": {"it": [
        ("Passo 5 — Il corpo ascolta", "Il messaggio più forte arriva dal corpo. Rivolgi il busto verso chi parla, tieni il telefono fuori dalla vista, non a faccia in giù sul tavolo, e regola lo sguardo: contatto visivo, ma senza fissare. Annuisci quando hai capito, non per fretta. I silenzi di due o tre secondi dopo che l'altro ha finito sono il momento in cui spesso arriva la cosa più importante, che non avrebbe detto se avessi riempito subito il vuoto."),
        ("Passo 6 — Nei conflitti e al lavoro", "L'ascolto attivo è più prezioso proprio quando è più difficile: in una discussione. Prima di ribattere, riformula la posizione dell'altro finché lui non dice 'esatto': solo allora ha senso esporre la tua. I negoziatori dell'FBI chiamano questa tecnica etichettatura e specchio, e funziona con un adolescente come con un cliente arrabbiato. Al lavoro, chiudere una riunione riassumendo cosa hai capito e chiedendo conferma evita la metà degli errori dei giorni seguenti."),
    ]},
    "v4-lez-gestire-ansia": {"it": [
        ("Passo 5 — Il movimento scarica l'allarme", "L'ansia prepara il corpo a correre o combattere: se non fai nessuna delle due cose, l'adrenalina resta in circolo. Cinque minuti di movimento intenso, salire le scale, camminare veloce, scuotere braccia e gambe, la consumano e dicono al cervello che il pericolo è passato. È il motivo per cui l'attività fisica regolare riduce l'ansia quanto molti farmaci nei casi lievi. Nel momento acuto, il corpo si calma prima della mente: usalo."),
        ("Passo 6 — Quando chiedere aiuto", "Le tecniche funzionano per i momenti d'ansia; non sostituiscono la cura quando l'ansia diventa una condizione. Se gli episodi sono frequenti, ti fanno evitare situazioni, disturbano il sonno per settimane o si accompagnano a attacchi di panico, parlane con il medico o con uno psicologo. La terapia cognitivo-comportamentale ha tassi di efficacia molto alti sui disturbi d'ansia, spesso in dieci-venti incontri. Chiedere aiuto non è il fallimento delle tecniche: è la tecnica successiva."),
    ]},
    "lez-memoria-tecniche": {
        "it": [("Passo 6 — Il palazzo della memoria", "I campioni di memoria non hanno cervelli speciali: usano un metodo antico di 2.500 anni. Scegli un percorso che conosci a memoria, casa tua o la strada per il lavoro, e colloca in ogni punto un'immagine assurda e vivida che rappresenta la cosa da ricordare: la lista della spesa diventa un pollo che suona il campanello, il latte che allaga l'ingresso. Per richiamare, ripercorri il tragitto. Il cervello ricorda luoghi e immagini molto meglio di parole: il palazzo della memoria traduce le seconde nei primi.")],
        "en": [("Step 6 — The memory palace", "Memory champions do not have special brains: they use a 2,500-year-old method. Pick a route you know by heart, your home or the way to work, and place at each point an absurd, vivid image representing the thing to remember: the shopping list becomes a chicken ringing the doorbell, milk flooding the hallway. To recall, walk the route again. The brain remembers places and images far better than words: the memory palace translates the latter into the former.")],
    },
    "lez-bias-conferma": {
        "it": [("Passo 6 — Il bias e gli algoritmi", "Oggi il bias di conferma ha un alleato potente: le piattaforme. I social mostrano contenuti simili a quelli con cui hai già interagito, perché ti trattengono di più, e costruiscono attorno a te una bolla in cui tutti sembrano pensare come te. Il motore di ricerca suggerisce le domande che confermano ciò che cerchi. Per difenderti segui deliberatamente fonti serie di opinione opposta, cerca la tesi contraria con le sue parole e non con le tue, e diffida della sensazione che 'tutti la pensano così'.")],
        "en": [("Step 6 — Bias and algorithms", "Today confirmation bias has a powerful ally: platforms. Social networks show you content similar to what you already engaged with, because it keeps you longer, building a bubble around you where everyone seems to think like you. The search engine suggests the questions that confirm what you are looking for. To defend yourself, deliberately follow serious sources of the opposite view, search for the opposing thesis in its own words rather than yours, and distrust the feeling that 'everyone thinks so'.")],
    },
    "v5-lez-distorsioni": {"it": [
        ("Passo 5 — La tecnica delle tre colonne", "Il rimedio più efficace è scriverle. Dividi un foglio in tre colonne: la situazione, il pensiero automatico, la distorsione che riconosci. Poi aggiungi una quarta colonna con un pensiero più realistico: non positivo per forza, realistico. 'Ho sbagliato la presentazione, sono un incapace' diventa 'Ho sbagliato una slide su venti e nessuno ha commentato'. È l'esercizio base della terapia cognitiva e, fatto per due settimane, cambia il modo di pensare in automatico."),
        ("Passo 6 — Il pensiero non è un fatto", "La lezione finale è una sola: un pensiero è un evento mentale, non una descrizione della realtà. Quando ti accorgi di dire 'sempre', 'mai', 'sicuramente' o 'tutti', fermati: sono le parole delle distorsioni. Chiediti che prove hai, cosa diresti a un amico nella stessa situazione, come vedrai la cosa tra un mese. Non si tratta di pensare positivo, ma di pensare preciso: la realtà è quasi sempre meno drammatica dei pensieri che la commentano."),
    ]},
    "v5-lez-feedback": {"it": [
        ("Passo 5 — Il momento e il luogo", "Il feedback migliore arriva presto e in privato. Aspettare la valutazione annuale per segnalare un problema di marzo è inutile: la persona non ricorda nemmeno l'episodio. Parla entro uno o due giorni, ma non a caldo, e mai davanti ad altri: la critica pubblica attiva la difesa, non l'ascolto. Chiedi prima il permesso, 'posso darti un feedback su ieri?', e concordate un momento: dieci minuti dedicati valgono più di un commento buttato nel corridoio."),
        ("Passo 6 — Ricevere un feedback", "Il metodo funziona anche al contrario. Quando ricevi una critica, la prima reazione del cervello è difendersi; contali fino a tre e fai una domanda invece di rispondere: 'Puoi farmi un esempio?'. Ringrazia, anche se non sei d'accordo, e prenditi un giorno prima di decidere cosa fare. Chiedi feedback regolarmente a chi lavora con te: chi lo chiede riceve informazioni più oneste e viene percepito come più competente, non meno."),
    ]},
    "v5-lez-motivazione": {"it": [
        ("Passo 5 — La motivazione nei figli e nella scuola", "L'effetto dei premi si vede chiaramente con i bambini. Pagare i figli per i buoni voti aumenta i voti finché dura il pagamento, poi crolla lo studio; lodare l'impegno, 'hai lavorato sodo', mantiene la motivazione, mentre lodare il talento, 'sei intelligente', la rende fragile perché il bambino evita le sfide che potrebbero smentirlo. Le classi in cui gli studenti scelgono parte dei compiti mostrano più curiosità e voti migliori nel lungo periodo."),
        ("Passo 6 — Un esperimento personale", "Prova su te stesso per una settimana. Scegli un'attività che fai per dovere e chiediti quale dei tre bisogni manca: puoi scegliere come farla? Vedi progressi? La fai con qualcuno? Poi cambia una sola cosa: decidi tu l'orario, misura un miglioramento, coinvolgi una persona. Osserva cosa succede alla voglia di farla. Quasi sempre non è l'attività a essere noiosa, ma il modo in cui è organizzata."),
    ]},
    "v5-lez-decisioni": {"it": [
        ("Passo 5 — Decisioni reversibili e irreversibili", "Non tutte le decisioni meritano lo stesso tempo. Se una scelta si può annullare in pochi giorni con un costo basso, decidi in fretta e correggi dopo: la maggior parte delle decisioni quotidiane è così, e rimuginarci sopra costa più dell'errore. Riserva gli strumenti pesanti alle decisioni difficili da invertire: una casa, un matrimonio, lasciare un lavoro sicuro. Chiediti sempre prima: posso tornare indietro? La risposta ti dice quanto pensare."),
        ("Passo 6 — Dopo la decisione", "Una decisione presa bene può avere un esito cattivo, e viceversa: il caso esiste. Giudica il processo, non solo il risultato. Scrivi in poche righe perché hai scelto e cosa ti aspetti, e rileggilo dopo sei mesi: scoprirai quali dei tuoi ragionamenti reggono e quali no, e la prossima volta deciderai meglio. E smetti di guardare le alternative scartate: il rimpianto è il costo affondato delle decisioni, e non restituisce nulla."),
    ]},
    "v5-lez-stress": {"it": [
        ("Passo 5 — I segnali di stress cronico", "Lo stress cronico si maschera bene. Non arriva come una crisi ma come piccole cose: il sonno che si accorcia, i raffreddori frequenti, la mandibola serrata al risveglio, l'irritabilità per sciocchezze, la difficoltà a concentrarsi su un libro, il bisogno di zuccheri o di alcol la sera. Se riconosci tre o quattro di questi segnali da più di un mese, il tuo allarme è acceso da troppo tempo e ha bisogno di essere spento, non gestito."),
        ("Passo 6 — Ridurre lo stress alla fonte", "Le tecniche di recupero servono, ma la soluzione duratura è togliere carburante all'allarme. Fai un elenco delle fonti di stress delle ultime due settimane e dividile in tre gruppi: quelle che puoi eliminare, quelle che puoi ridurre, quelle che devi accettare. Sul primo gruppo agisci subito, anche con una sola cosa. Sul secondo negozia: orari, aspettative, deleghe. Sul terzo lavora con il cambio di etichetta e il recupero. Lo stress che non puoi cambiare pesa meno quando hai eliminato quello che potevi."),
    ]},
    "why-we-dream": {
        "it": [("Gli incubi e i sogni lucidi", "Gli incubi sono comuni e di solito innocui: nei bambini raggiungono il picco tra i 5 e i 10 anni, negli adulti si intensificano con stress e alcuni farmaci. Diventano un problema quando si ripetono ogni notte, come nel disturbo post-traumatico, e in quel caso esiste una terapia specifica in cui si riscrive da svegli il finale del sogno. All'estremo opposto ci sono i sogni lucidi, in cui il sognatore sa di sognare e può influenzare la trama: circa la metà delle persone ne ha fatto almeno uno, e la capacità si può allenare.")],
        "en": [("Nightmares and lucid dreams", "Nightmares are common and usually harmless: in children they peak between ages 5 and 10, in adults they intensify with stress and some medications. They become a problem when they recur every night, as in post-traumatic disorder, and in that case a specific therapy exists in which the dream's ending is rewritten while awake. At the opposite extreme are lucid dreams, in which the dreamer knows they are dreaming and can influence the plot: about half of people have had at least one, and the skill can be trained.")],
    },
    "procrastination": {
        "it": [("La regola dei due minuti", "Un trucco semplice funziona perché aggira il cervello anziché combatterlo. Prometti a te stesso di lavorare al compito per soli due minuti: aprire il documento, scrivere una riga, mettere le scarpe da corsa. La resistenza riguarda l'inizio, non l'attività; una volta partiti, la maggior parte delle persone continua. Un altro strumento è il pre-impegno: dire a qualcuno una scadenza, o usare app che bloccano i social in certe ore. Non serve più forza di volontà, servono meno decisioni.")],
        "en": [("The two-minute rule", "A simple trick works because it bypasses the brain instead of fighting it. Promise yourself to work on the task for just two minutes: open the document, write one line, put on your running shoes. The resistance is about starting, not about the activity; once started, most people keep going. Another tool is pre-commitment: telling someone a deadline, or using apps that block social media at certain hours. You do not need more willpower, you need fewer decisions.")],
    },
    "fear-basics": {
        "it": [("Perché cerchiamo la paura", "Se la paura è spiacevole, perché paghiamo per un film horror o una montagna russa? Perché la paura in un contesto sicuro è eccitante: il corpo rilascia adrenalina e dopamina, e quando il cervello capisce che il pericolo non è reale, quella carica si trasforma in euforia e in sollievo. È una palestra: sperimentare la paura sapendo di controllarla aumenta la fiducia nel poterla gestire davvero. Gli studi mostrano che chi ama l'horror ha affrontato la pandemia con meno ansia degli altri.")],
        "en": [("Why we seek fear", "If fear is unpleasant, why do we pay for a horror film or a roller coaster? Because fear in a safe context is exciting: the body releases adrenaline and dopamine, and when the brain realises the danger is not real, that charge turns into euphoria and relief. It is a gym: experiencing fear while knowing you control it increases confidence in truly handling it. Studies show that horror fans faced the pandemic with less anxiety than others.")],
    },
    "memory-basics": {
        "it": [("I falsi ricordi", "La memoria non solo dimentica: inventa. Negli esperimenti di Elizabeth Loftus, bastava suggerire con una domanda un dettaglio inesistente per far 'ricordare' ai testimoni un fienile che non c'era; con un po' di insistenza, un quarto dei volontari costruiva il ricordo completo di essersi perso in un centro commerciale da bambino, un episodio mai accaduto. Per questo le testimonianze oculari sono la prima causa di condanne ingiuste poi smentite dal DNA. Un ricordo vivido e sicuro non è per forza un ricordo vero.")],
        "en": [("False memories", "Memory does not only forget: it invents. In Elizabeth Loftus's experiments, merely suggesting a non-existent detail in a question made witnesses 'remember' a barn that was not there; with a little insistence, a quarter of volunteers built a full memory of being lost in a shopping mall as a child, an event that never happened. That is why eyewitness testimony is the leading cause of wrongful convictions later overturned by DNA. A vivid, confident memory is not necessarily a true one.")],
    },
    "empathy-basics": {
        "it": [("L'empatia si allena", "L'empatia non è fissa. Leggere romanzi, che ci fanno vivere nella mente di personaggi diversi da noi, migliora la capacità di riconoscere emozioni negli altri; lo stesso fanno il teatro e il volontariato con persone lontane dal proprio ambiente. Nelle scuole i programmi di educazione emotiva riducono il bullismo. E funziona anche una domanda semplice, fatta ogni giorno: cosa sta provando questa persona in questo momento e perché? Il muscolo cresce con l'uso, come tutti gli altri.")],
        "en": [("Empathy can be trained", "Empathy is not fixed. Reading novels, which let us live inside the minds of characters unlike us, improves the ability to recognise emotions in others; theatre and volunteering with people far from one's own environment do the same. In schools, emotional education programmes reduce bullying. And a simple daily question works too: what is this person feeling right now, and why? The muscle grows with use, like every other.")],
    },
    "v4-effetto-zeigarnik": {"it": [
        ("Perché le serie finiscono sul più bello", "Le industrie dell'intrattenimento vivono di Zeigarnik. Il cliffhanger alla fine di un episodio lascia una tensione aperta che ti spinge a guardare il successivo; le notifiche con puntini di sospensione, 'qualcuno ha commentato la tua foto', ti costringono ad aprire l'app per chiudere il cerchio; i giochi mostrano barre di progresso al 90%. Ogni volta che senti il bisogno irresistibile di finire qualcosa che non hai scelto di iniziare, qualcuno ha sfruttato l'effetto contro di te."),
        ("Chiudere i cerchi per dormire", "L'effetto spiega anche perché la mente corre a letto: ogni compito lasciato a metà torna a chiedere attenzione quando le distrazioni si spengono. Uno studio del 2018 ha mostrato che chi scrive prima di dormire una lista dettagliata delle cose da fare il giorno dopo si addormenta in media nove minuti prima di chi scrive le cose già fatte. Non è ottimismo: è il cervello che, vedendo un piano, considera il cerchio abbastanza chiuso per lasciarti andare."),
    ]},
    "v4-paradosso-scelta": {"it": [
        ("Il dibattito tra gli scienziati", "L'esperimento delle marmellate è famoso, ma non tutti gli studi successivi lo hanno confermato. Una revisione del 2010 su cinquanta esperimenti ha trovato che, in media, l'effetto del sovraccarico è vicino a zero: dipende dalle condizioni. Le troppe opzioni paralizzano quando sono difficili da confrontare, quando non hai preferenze chiare e quando la decisione è poco importante. Se sai bene cosa vuoi, più scelta è meglio. La lezione onesta è che la quantità di opzioni conta meno della loro leggibilità."),
        ("Come i negozi hanno risposto", "Le aziende hanno imparato la lezione a modo loro. Le catene di supermercati che hanno ridotto l'assortimento, come Aldi e Lidl, con circa duemila prodotti contro i quarantamila di un ipermercato, hanno visto crescere vendite e fedeltà. Apple vende pochi modelli per categoria; i menu con poche voci vendono di più; le piattaforme di streaming mostrano un'unica proposta grande in cima alla pagina. Quando l'offerta si restringe, di solito non è per risparmiare: è per farti decidere."),
    ]},
    "v4-effetto-spettatore": {"it": [
        ("La storia vera di Kitty Genovese", "Il caso da cui tutto è nato è più complesso della leggenda. L'articolo del New York Times del 1964 parlava di 38 testimoni che avevano guardato senza fare nulla; ricerche successive hanno mostrato che pochi videro davvero l'aggressione, che almeno due chiamarono la polizia e che una vicina uscì e tenne Kitty tra le braccia fino all'arrivo dei soccorsi. La leggenda ha generato ricerche preziose e il numero unico di emergenza 911, ma la storia reale racconta anche di persone che intervennero."),
        ("Le buone notizie dalle telecamere", "Studi recenti hanno guardato i dati reali invece che il laboratorio. Nel 2019 ricercatori hanno analizzato oltre duecento video di sorveglianza di aggressioni in strada a Amsterdam, Lancaster e Città del Capo: in nove casi su dieci almeno uno spettatore intervenne, e più persone c'erano, più probabile era che qualcuno aiutasse. L'effetto spettatore esiste, ma la maggior parte delle persone, davanti a un pericolo reale, fa qualcosa. Sapere cosa fare rende quel qualcosa più efficace."),
    ]},
    "v5-brividi-musica": {"it": [
        ("La musica come medicina", "L'effetto della musica sul cervello viene usato in clinica. Nei pazienti con Parkinson un ritmo regolare aiuta a camminare quando le gambe si bloccano; nei malati di Alzheimer le canzoni della giovinezza riaccendono ricordi e linguaggio quando tutto il resto è perduto, perché la memoria musicale è tra le ultime a spegnersi; negli ospedali riduce ansia e dolore prima degli interventi, con meno bisogno di sedativi. I brividi sono la punta di un sistema che collega suono, emozione e corpo."),
        ("Costruire la scaletta perfetta", "Puoi cercare i brividi di proposito. Funzionano meglio i brani che conosci abbastanza da anticipare ma non così tanto da esserne annoiato, quindi le canzoni amate ma non ascoltate da tempo. Aiutano il volume alto, le cuffie e l'attenzione piena, senza fare altro. Ricercatori hanno raccolto migliaia di segnalazioni di momenti da brivido: molti coincidono con l'ingresso di una voce, un cambio di tonalità o un crescendo dopo un silenzio. Ascoltare con questa consapevolezza rende l'effetto più frequente, non meno."),
    ]},
    "v5-ricordi-flash": {"it": [
        ("La memoria collettiva", "I ricordi flash hanno anche una dimensione sociale: sono i ricordi che una generazione condivide e racconta, e per questo si deformano ancora di più. Ogni volta che ne parliamo con altri incorporiamo dettagli sentiti da loro o visti in televisione dopo. Chi era a New York l'11 settembre e chi lo ha visto dalla TV finiscono per avere ricordi simili, perché entrambi hanno assorbito le stesse immagini ripetute. Il ricordo diventa un racconto condiviso più che un'esperienza personale."),
        ("Cosa fare con questa scoperta", "Sapere che i ricordi vividi sono inaffidabili non li rende inutili: cambia il modo di usarli. Non discutere con un familiare su chi ha ragione riguardo a un evento di vent'anni fa, perché probabilmente sbagliate entrambi. Se un ricordo è importante, scrivilo subito: il diario del giorno dopo batte qualsiasi memoria del decennio dopo. E nei tribunali questa ricerca ha cambiato le regole: la sicurezza di un testimone non è più considerata una prova della sua accuratezza."),
    ]},
    "v5-perche-ridiamo": {"it": [
        ("Ridere fa bene, sul serio", "Una risata vera coinvolge quindici muscoli del viso, il diaframma e gli addominali, aumenta il battito e poi lo abbassa sotto il livello di partenza, con un effetto rilassante che dura fino a 45 minuti. Rilascia endorfine e alza la soglia del dolore: nei laboratori, chi ha appena riso in gruppo sopporta più a lungo il freddo di un manicotto ghiacciato. Non allunga la vita in modo dimostrato, ma riduce lo stress e rafforza i legami, che sì, la allungano."),
        ("La risata contagiosa e quella finta", "Il cervello distingue la risata spontanea da quella sociale in pochi decimi di secondo e le elabora in aree diverse: la prima attiva le regioni emotive, la seconda quelle che cercano di capire le intenzioni degli altri. Le risate registrate nelle sitcom, introdotte negli anni Cinquanta, funzionano perché il contagio della risata è quasi automatico: sentire ridere fa ridere. Nel 1962 in Tanzania un'epidemia di risate incontrollabili si diffuse tra centinaia di studentesse e durò mesi."),
    ]},
    "v5-ancoraggio": {"it": [
        ("Gli esperti non sono immuni", "Si potrebbe pensare che la competenza protegga dall'ancoraggio. Non è così. In un esperimento, giudici tedeschi con quindici anni di esperienza hanno emesso pene più severe dopo aver lanciato un dado truccato con numeri alti; agenti immobiliari hanno valutato la stessa casa con differenze di decine di migliaia di euro a seconda del prezzo di partenza mostrato loro, pur negando di averlo considerato. L'ancoraggio agisce sotto la consapevolezza, e l'esperienza dà solo la falsa sicurezza di esserne esenti."),
        ("Usarlo a tuo favore", "L'ancoraggio funziona in entrambe le direzioni, quindi puoi anche impugnarlo. In una trattativa, fai tu la prima offerta e falla ambiziosa ma giustificabile: chi parla per primo sposta l'intero negoziato verso il proprio numero. Quando vendi, indica un prezzo preciso, 1.250 e non 1.200, perché i numeri precisi ancorano più forte e sembrano frutto di un calcolo. E quando chiedi un aumento, nomina una cifra prima che lo faccia il tuo capo. La prima cifra è la più importante della conversazione."),
    ]},
    "v5-noia": {"it": [
        ("La noia dei bambini", "Molti genitori corrono a riempire ogni minuto vuoto dei figli, ma gli psicologi dello sviluppo dicono l'opposto: la noia è dove nascono l'immaginazione e l'autonomia. Un bambino che non sa cosa fare, se non gli si porge uno schermo, dopo dieci minuti di lamentele inventa un gioco, costruisce, disegna, esplora. Imparare a tollerare il vuoto è una competenza che serve per tutta la vita, e chi non la sviluppa cerca stimoli sempre più forti da adulto."),
        ("Come annoiarsi bene", "Prova a programmare la noia. Una passeggiata senza cuffie, una coda in posta senza telefono, dieci minuti sul divano a guardare il soffitto. All'inizio è sgradevole, proprio come dice l'esperimento delle scosse, ma dopo pochi minuti la mente comincia a vagare, a collegare cose, a ricordare ciò che aveva rimosso: è lo stato in cui arrivano le idee migliori. La doccia è famosa per le intuizioni non perché l'acqua ispiri, ma perché è uno degli ultimi luoghi in cui ci annoiamo."),
    ]},
}
