# Capitoli aggiuntivi — STORIA (scritti a mano, stesso tono degli altri)
EXTRA = {
    "egyptian-pyramids": {
        "it": [("Cosa non sappiamo ancora", "Le domande aperte sono più affascinanti delle risposte. Nel 2017 i fisici hanno rilevato, misurando le particelle cosmiche che attraversano la pietra, un grande vuoto lungo trenta metri sopra la Grande Galleria: nessuno sa a cosa servisse. Non abbiamo trovato la mummia di Cheope, né un solo testo egizio che spieghi come fu organizzato il cantiere. Sappiamo però che i blocchi esterni erano ricoperti di calcare bianco lucidato, e che la piramide, appena finita, brillava al sole come uno specchio visibile a decine di chilometri.")],
        "en": [("What we still don't know", "The open questions are more fascinating than the answers. In 2017 physicists detected, by measuring cosmic particles passing through the stone, a large void thirty metres long above the Grand Gallery: nobody knows what it was for. We have not found Khufu's mummy, nor a single Egyptian text explaining how the building site was organised. We do know that the outer blocks were covered in polished white limestone and that the pyramid, when new, gleamed in the sun like a mirror visible from dozens of kilometres away.")],
    },
    "printing-press": {
        "it": [("Il paradosso di Gutenberg", "L'uomo che cambiò il mondo non ci guadagnò nulla. Gutenberg si era indebitato con il finanziere Johann Fust per costruire l'officina; nel 1455, proprio mentre le prime Bibbie uscivano dalla pressa, Fust lo citò in giudizio, vinse e si prese l'attrezzatura e i libri. Gutenberg morì nel 1468, quasi dimenticato, con una piccola pensione dell'arcivescovo di Magonza. Delle circa 180 Bibbie stampate ne sopravvivono 49: oggi un solo volume vale decine di milioni di euro, più di quanto Gutenberg abbia visto in tutta la vita.")],
        "en": [("Gutenberg's paradox", "The man who changed the world made nothing from it. Gutenberg had borrowed from the financier Johann Fust to build his workshop; in 1455, just as the first Bibles were coming off the press, Fust sued him, won, and took the equipment and the books. Gutenberg died in 1468, almost forgotten, on a small pension from the archbishop of Mainz. Of the roughly 180 Bibles printed, 49 survive: today a single volume is worth tens of millions of euros, more than Gutenberg saw in his entire life.")],
    },
    "french-revolution": {
        "it": [("Cosa ci ha lasciato", "Molto di ciò che consideriamo normale nasce in quegli anni. Il sistema metrico decimale, con metro e chilogrammo, fu creato per sostituire le centinaia di misure locali. La leva militare di massa, il matrimonio civile, lo stato laico e l'idea che la sovranità appartenga alla nazione e non a un re sono figli della Rivoluzione. Anche la parola 'destra' e 'sinistra' in politica viene dai posti a sedere nell'Assemblea del 1789: i sostenitori del re a destra del presidente, i rivoluzionari a sinistra.")],
        "en": [("What it left us", "Much of what we consider normal was born in those years. The decimal metric system, with metre and kilogram, was created to replace hundreds of local measures. Mass conscription, civil marriage, the secular state and the idea that sovereignty belongs to the nation and not to a king are children of the Revolution. Even the words 'right' and 'left' in politics come from the seating in the 1789 Assembly: the king's supporters to the right of the president, the revolutionaries to the left.")],
    },
    "world-war-1": {
        "it": [("La guerra che cambiò il secolo", "Le conseguenze durarono molto più di quattro anni. Caddero quattro imperi: tedesco, austro-ungarico, russo e ottomano, e sulle loro macerie nacquero decine di nuovi stati, con confini tracciati in fretta che ancora oggi generano conflitti in Medio Oriente e nei Balcani. La Russia in guerra scivolò nella rivoluzione bolscevica. Le donne, entrate in fabbrica per sostituire gli uomini al fronte, ottennero il voto in molti paesi. E l'umiliazione tedesca a Versailles preparò il terreno a Hitler: molti storici parlano di un'unica guerra dei trent'anni, dal 1914 al 1945.")],
        "en": [("The war that shaped the century", "The consequences lasted far longer than four years. Four empires fell: German, Austro-Hungarian, Russian and Ottoman, and on their ruins dozens of new states were born, with hastily drawn borders that still generate conflicts in the Middle East and the Balkans. Russia at war slid into the Bolshevik revolution. Women, who had entered the factories to replace men at the front, won the vote in many countries. And Germany's humiliation at Versailles prepared the ground for Hitler: many historians speak of a single thirty years' war, from 1914 to 1945.")],
    },
    "vikings-truth": {
        "it": [("Perché finirono", "L'età vichinga si chiuse nel 1066, quando Harald Hardrada, re di Norvegia, fu sconfitto in Inghilterra a Stamford Bridge. Ma la vera fine fu più dolce: i vichinghi si convertirono al cristianesimo, si stabilirono nelle terre che avevano razziato e vi si mescolarono. I normanni che conquistarono l'Inghilterra e la Sicilia erano loro discendenti francesizzati. In Inghilterra restano centinaia di parole scandinave nell'uso quotidiano, da 'sky' a 'window', e i giorni della settimana portano ancora i nomi dei loro dei: Thursday è il giorno di Thor.")],
        "en": [("Why they ended", "The Viking age closed in 1066, when Harald Hardrada, king of Norway, was defeated in England at Stamford Bridge. But the real ending was gentler: the Vikings converted to Christianity, settled in the lands they had raided and blended in. The Normans who conquered England and Sicily were their Frenchified descendants. Hundreds of Scandinavian words remain in everyday English, from 'sky' to 'window', and the days of the week still carry the names of their gods: Thursday is Thor's day.")],
    },
    "v4-biblioteca-alessandria": {"it": [
        ("Cosa si è perso davvero", "Alessandria non era l'unica biblioteca: Pergamo, Roma, Costantinopoli ne avevano di enormi. Il sapere antico non si perse in un luogo, ma in un processo. I rotoli di papiro duravano un paio di secoli e andavano ricopiati; ogni generazione sceglieva cosa ricopiare e cosa lasciare marcire. Dei circa 120 drammi di Sofocle ne abbiamo sette. Non perché bruciati, ma perché a un certo punto nessuno li richiese più. Ciò che sopravvive è ciò che qualcuno ha continuato a leggere."),
        ("La biblioteca rinata", "Nel 2002 l'Egitto ha inaugurato la Bibliotheca Alexandrina, un edificio a forma di disco solare inclinato verso il mare, a pochi passi dal luogo dove sorgeva l'antica. Ospita otto milioni di volumi e un archivio di internet. È anche un promemoria: il sapere oggi non è più su papiri che marciscono, ma su server che qualcuno deve pagare e mantenere. La lezione di Alessandria vale ancora: i libri non muoiono di fuoco, muoiono di abbandono."),
    ]},
    "v4-cleopatra-piramidi": {"it": [
        ("Quanto era antico l'antico", "Per capire la distanza, prova così: fra noi e Cleopatra passano circa 2.050 anni; fra Cleopatra e la Grande Piramide ne passano 2.500. Quando lei saliva al trono, la civiltà che aveva costruito le piramidi era più lontana nel tempo di quanto lo siano per noi i Romani. Gli egizi stessi, all'epoca, restauravano monumenti già antichi: il faraone Khaemweset, figlio di Ramesse II, intorno al 1250 a.C. fece incidere sulle piramidi i nomi dei costruttori perché si stavano dimenticando. Era un archeologo, 3.200 anni fa."),
        ("Il volto che non conosciamo", "Cleopatra è una delle donne più rappresentate della storia, eppure non sappiamo che aspetto avesse. Le uniche immagini certe sono sulle monete che fece battere: un profilo dal naso pronunciato e dal mento deciso, lontano dalle attrici di Hollywood. Gli storici antichi che la descrissero erano romani e ostili, e insistevano sul fascino della voce e dell'intelligenza più che sulla bellezza. Parlava, dicono, nove lingue, ed è stata la prima della sua dinastia in trecento anni a imparare l'egiziano."),
    ]},
    "v4-guerra-piu-breve": {"it": [
        ("Il conto del bombardamento", "Finita la battaglia, i britannici presentarono a Zanzibar la fattura delle munizioni sparate e pretesero che il nuovo sultano la pagasse. Il bilancio umano fu tutt'altro che comico: circa cinquecento morti tra i difensori e gli abitanti del palazzo, un solo ferito grave tra i britannici. La 'guerra più breve' fu in realtà un bombardamento su un edificio di legno pieno di persone, e servì a mostrare a tutta l'Africa orientale chi decidesse le successioni."),
        ("Come si misura una guerra", "I 38 minuti sono un record, ma solo se accettiamo di chiamare guerra quell'episodio. La storia è piena di guerre dichiarate e mai combattute, come quella tra Paesi Bassi e Isole Scilly, formalmente durata 335 anni senza un colpo, o di conflitti mai dichiarati e sanguinosissimi. La lezione per chi legge i record: dietro ogni primato c'è una definizione, e la definizione la sceglie chi racconta. Chiediti sempre cosa è stato contato, e cosa no."),
    ]},
    "v4-lez-leggere-mappa-storica": {"it": [
        ("Passo 5 — Le proiezioni mentono tutte", "Nessuna mappa piatta è fedele: la Terra è una sfera e appiattirla costringe a deformare. La proiezione di Mercatore, la più diffusa, ingrandisce enormemente ciò che sta vicino ai poli: la Groenlandia sembra grande come l'Africa, che in realtà è quattordici volte più estesa. Fu disegnata nel 1569 per i naviganti, che avevano bisogno di angoli esatti, non di aree. Quando confronti la grandezza di due paesi su una mappa, ricordati che stai guardando una scelta matematica, non il mondo."),
        ("Passo 6 — Mettiti alla prova", "Prendi una mappa storica qualunque, anche da un libro di scuola, e rispondi per iscritto a cinque domande: quando è stata disegnata e da chi; cosa sta al centro; cosa rappresentano i colori e chi ha scelto i confini; quali popoli o territori mancano; a cosa doveva servire. Poi cerca una mappa della stessa regione fatta da un'altra parte, per esempio una carta ottomana dei Balcani accanto a una austriaca. La differenza tra le due è la storia che nessuna delle due racconta da sola."),
    ]},
    "v4-lez-fonti-primarie": {"it": [
        ("Passo 5 — Anche le primarie mentono", "Una fonte primaria è vicina ai fatti, non per questo è vera. Le lettere si scrivono sapendo chi le leggerà, i diari si scrivono spesso per i posteri, le fotografie si scelgono e si tagliano. Le relazioni dei funzionari coloniali descrivono popoli 'felici e docili' perché chi le leggeva voleva sentire questo. La domanda giusta non è 'è primaria?' ma 'cosa poteva sapere questa persona, e cosa aveva interesse a dire?'. Anche un documento falso è una fonte preziosa: racconta cosa qualcuno voleva far credere."),
        ("Passo 6 — Usalo oggi", "Applica il metodo a una notizia di questa settimana. Trova la fonte primaria: il comunicato, il video originale, il documento citato. Poi confronta come due giornali di orientamento diverso la hanno riassunta: dove tagliano, quali aggettivi aggiungono. Infine chiediti chi guadagna se ci credi. In dieci minuti avrai fatto ciò che uno storico fa con documenti di cinquecento anni. La differenza è che le fonti di oggi sono a un clic di distanza, e quasi nessuno le apre."),
    ]},
    "v4-lez-perche-cadono-imperi": {"it": [
        ("Passo 5 — Il caso che non torna: Roma d'Oriente", "Ogni modello ha eccezioni istruttive. L'Impero romano d'Oriente, Bisanzio, sopravvisse mille anni alla caduta di Roma pur subendo tutti e quattro gli schemi: perse territori, svalutò la moneta, ebbe guerre civili e pestilenze. Resistette perché seppe restringersi in tempo, rinunciando alle province lontane per difendere il cuore, e perché aveva una capitale imprendibile e una burocrazia che continuava a funzionare anche con imperatori pessimi. La lezione: gli imperi che durano non sono quelli che non cadono, ma quelli che sanno ritirarsi."),
        ("Passo 6 — Guardare il presente con lo schema", "Ora usa i quattro schemi come una lente, non come una profezia. Quando leggi di una grande potenza di oggi, chiediti: sta difendendo più di quanto riesca a pagare? La moneta e il debito reggono? Le élite e i cittadini credono ancora nel progetto? Quale shock esterno la metterebbe in crisi? Nessuna risposta è definitiva, e la storia non si ripete uguale. Ma chi ha in mente Roma e Bisanzio legge le notizie con una profondità che la cronaca da sola non dà."),
    ]},
    "v5-dieci-giorni-persi": {"it": [
        ("La rivolta dei giorni rubati", "Non tutti la presero bene. Quando l'Inghilterra saltò gli undici giorni nel 1752, circolarono storie di folle che gridavano 'ridateci i nostri undici giorni'. Gli storici oggi credono che le rivolte siano in gran parte una leggenda nata da una stampa satirica, ma le preoccupazioni erano reali: affitti, salari e interessi andavano ricalcolati, e i compleanni spostati. Alcuni, come il fondatore della Pennsylvania William Penn, scrissero di sentirsi 'più vecchi di undici giorni senza averli vissuti'."),
        ("Il calendario è ancora un po' sbagliato", "Neppure Gregorio fu perfetto. Il calendario gregoriano accumula un giorno di errore ogni circa 3.300 anni: intorno all'anno 4900 qualcuno dovrà saltare un giorno. La Chiesa ortodossa usa ancora il calendario giuliano per le feste, ed è per questo che il Natale ortodosso cade il 7 gennaio. E resta un residuo dello scarto anche nel nome delle rivoluzioni: la Rivoluzione d'ottobre russa del 1917 avvenne, per il nostro calendario, a novembre."),
    ]},
    "v5-napoleone-basso": {"it": [
        ("Il soprannome che confonde", "I soldati lo chiamavano 'le petit caporal', il piccolo caporale, e il nomignolo sembra confermare la leggenda. Ma 'petit' era un vezzeggiativo affettuoso, guadagnato dopo la battaglia di Lodi nel 1796 quando i veterani lo 'promossero' scherzosamente al grado più basso per la sua abitudine di stare in mezzo a loro. Contribuiva anche l'entourage: Napoleone era spesso circondato dalle guardie imperiali, scelte apposta tra gli uomini più alti dell'esercito. Accanto a giganti di un metro e novanta, chiunque sembra piccolo."),
        ("Le altre leggende su di lui", "Napoleone è una fabbrica di miti. Non è vero che i suoi soldati abbiano sparato al naso della Sfinge: era già danneggiata secoli prima, come mostrano disegni del 1737. Non dormiva tre ore per notte come dicono: faceva molti sonnellini. È vero invece che i francesi guidano a destra per una sua imposizione nei paesi conquistati, mentre l'Inghilterra, mai occupata, rimase a sinistra. E il codice civile che promulgò nel 1804 è ancora, con modifiche, la base del diritto in gran parte d'Europa."),
    ]},
    "v5-anno-senza-estate": {"it": [
        ("La bicicletta e il colore dei tramonti", "Le conseguenze arrivarono dove nessuno le aspettava. In Germania la carestia uccise così tanti cavalli, o li rese così costosi da mantenere, che il barone Karl von Drais cercò un mezzo per muoversi senza animali: nel 1817 presentò la Laufmaschine, l'antenata della bicicletta. In Inghilterra il pittore William Turner dipinse cieli infuocati, arancio e viola, che i critici giudicarono esagerati: erano reali, colorati dagli aerosol vulcanici che filtravano la luce del tramonto."),
        ("Potrebbe succedere di nuovo", "Il Tambora non è un caso unico. Nel 1991 il Pinatubo, nelle Filippine, abbassò la temperatura globale di mezzo grado per due anni con un'eruzione dieci volte più piccola. I vulcanologi stimano che un'eruzione da 'anno senza estate' avvenga in media una volta ogni due o tre secoli; oggi colpirebbe un pianeta di otto miliardi di persone con scorte di cibo per pochi mesi. Per questo alcuni scienziati studiano proprio questo meccanismo, l'aerosol in stratosfera, come possibile, e controverso, strumento per raffreddare artificialmente il clima."),
    ]},
    "v5-quarantena-venezia": {"it": [
        ("Il primo passaporto sanitario", "Venezia inventò anche la burocrazia della salute. Le navi in arrivo dovevano esibire una 'fede di sanità', un documento rilasciato dal porto di partenza che attestava l'assenza di peste in città: se mancava o era sospetto, la nave finiva in quarantena. I Provveditori alla Sanità tenevano registri dei morti per causa, tra i primi in Europa, e potevano ordinare la chiusura di case e botteghe. Ispettori pagati controllavano i lazzaretti. Tutto questo tre secoli prima che qualcuno vedesse un batterio al microscopio."),
        ("Quello che avevano capito senza saperlo", "Nessuno nel Trecento conosceva Yersinia pestis, il batterio trasmesso dalle pulci dei ratti. Ma l'osservazione era corretta: la malattia arrivava con le navi e con le merci, in particolare con la lana e i tessuti, che i veneziani facevano arieggiare e fumigare per giorni. Le pulci, senza saperlo, morivano nell'attesa. La quarantena funzionava per la ragione sbagliata, ma funzionava. È un buon promemoria: in medicina, le misure basate sull'osservazione attenta possono precedere la teoria di secoli."),
    ]},
    "v5-primo-sciopero": {"it": [
        ("Come vivevano gli scioperanti", "Deir el-Medina è uno dei siti meglio documentati dell'antichità, perché i suoi abitanti sapevano scrivere e lo facevano su tutto: cocci, schegge di pietra, papiri. Conosciamo i nomi degli operai, le liti tra vicini, le assenze dal lavoro giustificate con 'ha bevuto con il capo' o 'ha imbalsamato la madre', e persino un caso di corruzione di un caposquadra. Erano artigiani rispettati, con un orario di otto ore, riposo ogni dieci giorni e razioni di grano, birra, pesce e verdure: la classe media del mondo antico."),
        ("Una protesta moderna", "Ciò che colpisce nel papiro è quanto la scena sembri di oggi. Gli operai non si ribellano al faraone: chiedono ciò che spetta loro, si siedono in un luogo pubblico e sacro dove non possono essere ignorati, negoziano con i funzionari e sospendono la protesta quando arrivano le razioni, per riprenderla al ritardo successivo. Uno di loro pronuncia una frase che potrebbe stare su uno striscione: 'Abbiamo fame'. Tremila anni dopo, il meccanismo dello sciopero non è cambiato di una virgola."),
    ]},
    "v5-lez-datare-reperti": {"it": [
        ("Passo 5 — Oltre i 50.000 anni", "Per i tempi profondi il carbonio-14 non basta: è quasi tutto decaduto. Si passa ad altri orologi radioattivi, più lenti: il potassio-argon data le rocce vulcaniche che racchiudono i fossili, fino a miliardi di anni; la termoluminescenza misura da quanto tempo un frammento di ceramica o una pietra sono stati scaldati l'ultima volta; la luminescenza otticamente stimolata dice quando un granello di sabbia ha visto la luce per l'ultima volta prima di essere sepolto. Ogni materiale ha il suo cronometro."),
        ("Passo 6 — Prova a datare tu", "Immagina di trovare, scavando in giardino, un coccio con un frammento di scritta, sotto uno strato che contiene una moneta del 1850. Cosa puoi dire con certezza? Che il coccio è più vecchio del 1850, perché sta sotto. Cosa non puoi dire? Quanto più vecchio: potrebbe essere del 1840 o del 1200. Servirebbe uno stile della ceramica noto, o un pezzo di carbone accanto da analizzare. Ragionare così, distinguendo il certo dal probabile, è tutto il mestiere dell'archeologo."),
    ]},
    "v5-lez-rivoluzione-agricola": {"it": [
        ("Passo 5 — La trappola che non si può disfare", "Una volta imboccata, la strada dell'agricoltura non ha ritorno. Un villaggio di contadini genera più figli di un gruppo di cacciatori, e quei figli hanno bisogno di più campi; i campi richiedono più lavoro, il lavoro più figli. In poche generazioni la popolazione è troppo numerosa per tornare a vivere di caccia. Gli storici la chiamano la trappola dell'agricoltura: ciascuna scelta era ragionevole, la somma ha legato la specie alla zappa. Vale ancora oggi per molte tecnologie: comode a una a una, irrinunciabili tutte insieme."),
        ("Passo 6 — Cosa resta nel tuo piatto", "Guarda la tua cena con occhi da archeologo. Il pane viene dal grano addomesticato nella Mezzaluna fertile 11.000 anni fa; il riso dalla Cina, il mais e i fagioli dal Messico, le patate dalle Ande, il pollo dall'Asia sudorientale. Delle circa 300.000 piante commestibili, coltiviamo su larga scala una ventina, e tre, grano, riso e mais, forniscono metà delle calorie dell'umanità. Le decisioni dei primi agricoltori sono ancora nel tuo piatto, ogni sera."),
    ]},
    "v5-lez-nascita-citta": {"it": [
        ("Passo 5 — Perché alcune città muoiono", "Le stesse condizioni che fanno nascere una città possono farla sparire. Quando il fiume cambia corso o si insabbia, come a Efeso, il porto diventa una pianura e la città si svuota. Quando una via commerciale si sposta, come per le carovaniere della seta dopo l'apertura delle rotte oceaniche, le oasi-città dell'Asia centrale si spengono. E quando la funzione che attirava le persone scompare, una miniera esaurita, una capitale spostata, restano le città fantasma. Detroit ha perso due terzi degli abitanti in sessant'anni quando l'industria dell'auto si è dispersa."),
        ("Passo 6 — Le città del futuro", "Oggi nascono ancora città, ma per una condizione nuova: la decisione politica. Brasilia, Canberra, Astana e la nuova capitale amministrativa egiziana sono state disegnate a tavolino, lontano dai fiumi e dagli incroci naturali, per spostare il potere o decongestionare una metropoli. Alcune funzionano, altre restano vuote la sera. Il test è sempre lo stesso di Uruk: una città vive se le persone hanno una ragione per restarci quando l'ufficio chiude. Le condizioni sono cambiate, la regola no."),
    ]},
    "v5-lez-medioevo": {"it": [
        ("Passo 5 — Il Medioevo che vedi ogni giorno", "Prova a togliere il Medioevo dalla tua giornata. Niente occhiali, inventati a Pisa o Venezia verso il 1290. Niente bottoni con asole, niente carriola, niente mulino a vento, niente orologio meccanico, che nel Trecento cominciò a dividere la giornata in ore uguali. Niente università né lauree, niente ospedali come istituzioni, niente numeri arabi con lo zero, che i mercanti italiani adottarono per far di conto. E niente notazione musicale, senza la quale ogni canzone che conosci sarebbe stata dimenticata."),
        ("Passo 6 — Come parlarne bene", "Tre abitudini per non ripetere il luogo comune. Prima: specifica quale Medioevo, perché tra il 500 e il 1500 cambia tutto; il Duecento delle cattedrali non è il Seicento dopo la peste. Seconda: chiediti chi racconta, perché la fonte 'i medievali credevano che' è quasi sempre di un umanista o di un illuminista che vendeva la propria epoca. Terza: cerca il dato concreto. La prossima volta che senti 'siamo tornati al Medioevo' per qualcosa di brutto, hai il diritto di chiedere: a quale, esattamente?"),
    ]},
    "v5-lez-moneta-antica": {"it": [
        ("Passo 5 — Il falso antico e quello moderno", "Anche i falsari fanno storia. Nel mondo romano i 'suberati' erano monete di rame rivestite d'argento, e le autorità punivano i falsari con la morte; eppure i ritrovamenti mostrano che circolavano in massa, prova di quanto la gente si fidasse dell'aspetto più che del peso. Oggi il rischio è il falso moderno venduto come antico: controlla il peso con una bilancia di precisione, il suono che fa cadendo su un piano di legno, argento e bronzo antichi 'cantano' diversamente dalle leghe moderne, e diffida delle monete troppo perfette con la patina uniforme."),
        ("Passo 6 — Cosa fare se ne trovi una", "In Italia, e in gran parte d'Europa, una moneta antica trovata nel terreno appartiene allo Stato: non è un souvenir, è un documento. Fotografala sul posto, segna il punto, e consegnala alla Soprintendenza o ai Carabinieri per la tutela del patrimonio; il ritrovamento può dare diritto a un premio. Non pulirla mai con acidi o spazzole: la patina è parte della storia e la pulizia aggressiva cancella la legenda. E se vuoi collezionare, compra solo da venditori che forniscano la provenienza documentata."),
    ]},
    "lez-linea-del-tempo": {
        "it": [("Passo 6 — I calendari degli altri", "Il nostro conteggio non è l'unico. Il calendario ebraico è al 5780 e rotti, contando dalla creazione del mondo secondo la tradizione; quello islamico parte dal 622 d.C., l'anno dell'egira di Maometto, ed è lunare, quindi guadagna un anno ogni 33 dei nostri; il calendario cinese numera gli anni per cicli di sessanta. Perfino il nostro 'a.C.' è un'invenzione tardiva: fu proposta da un monaco nel 525 e diventò comune solo mille anni dopo. Quando leggi una data antica chiediti sempre chi contava e da dove: la linea del tempo ha tanti punti zero quante culture.")],
        "en": [("Step 6 — Other people's calendars", "Our count is not the only one. The Hebrew calendar is in the 5780s, counting from the creation of the world according to tradition; the Islamic one starts in 622 AD, the year of Muhammad's hijra, and is lunar, so it gains a year every 33 of ours; the Chinese calendar numbers years in cycles of sixty. Even our 'BC' is a late invention: it was proposed by a monk in 525 and became common only a thousand years later. When you read an ancient date, always ask who was counting and from where: the timeline has as many zero points as there are cultures.")],
    },
    "lez-valutare-fonte": {
        "it": [("Passo 6 — L'immagine come fonte", "Le foto e i video meritano un capitolo a parte, perché sembrano prove e sono racconti. Una foto ha un autore che ha scelto inquadratura, momento e cosa lasciare fuori; oggi può essere generata da zero. Tre controlli veloci: la ricerca inversa dell'immagine mostra se e quando è già circolata; i dettagli, ombre, cartelli, targhe, meteo, devono essere coerenti con il luogo e la data dichiarati; le mani, i testi e i riflessi sono i punti dove l'intelligenza artificiale sbaglia ancora. Un'immagine che arriva senza fonte è un'affermazione, non una prova.")],
        "en": [("Step 6 — Images as sources", "Photos and videos deserve a chapter of their own, because they look like evidence and are actually stories. A photograph has an author who chose the framing, the moment and what to leave out; today it can be generated from nothing. Three quick checks: a reverse image search shows whether and when it has already circulated; details, shadows, signs, number plates, weather, must match the claimed place and date; hands, text and reflections are where artificial intelligence still slips. An image that arrives without a source is a claim, not proof.")],
    },
}
