# Capitoli aggiuntivi — SPORT & MOVIMENTO (IT + EN)
EXTRA = {
    "sport-second-wind": {
        "it": [
            ("Il ruolo del respiro", "Nei primi minuti il respiro è corto e affannato perché il centro respiratorio nel tronco encefalico riceve segnali contrastanti: i muscoli chiedono ossigeno, ma cuore e polmoni non hanno ancora aumentato la portata. Dopo cinque o dieci minuti la ventilazione si stabilizza e la respirazione diventa più profonda e regolare. È in quel momento che la fatica sembra dissolversi: il corpo smette di correre dietro al debito di ossigeno e inizia a lavorare in equilibrio."),
            ("Cosa dicono gli studi", "I fisiologi hanno misurato il fenomeno in laboratorio: il consumo di ossigeno sale rapidamente all'inizio dello sforzo e raggiunge un plateau, mentre il lattato nel sangue prima aumenta e poi si stabilizza. Il secondo fiato coincide con questa fase di stato stazionario. Non tutti lo percepiscono allo stesso modo: chi è più allenato arriva prima all'equilibrio e quasi non nota il passaggio, mentre chi corre poco lo vive come una piccola rinascita."),
            ("Come favorirlo", "Il modo più semplice per incontrare il secondo fiato è partire piano. Un riscaldamento di dieci minuti a ritmo blando permette a cuore, vasi e mitocondri di alzare gradualmente il regime, evitando il debito iniziale che rende i primi chilometri sgradevoli. Anche respirare con un ritmo costante, per esempio tre passi in inspirazione e due in espirazione, aiuta. E soprattutto non fermarsi ai primi minuti di fatica: spesso il momento in cui tutto si fa più facile è a un passo."),
        ],
        "en": [
            ("The role of breathing", "In the first minutes breathing is short and laboured because the respiratory centre in the brainstem gets conflicting signals: muscles demand oxygen, but heart and lungs have not yet increased their output. After five to ten minutes ventilation settles and breathing becomes deeper and steadier. That is when fatigue seems to melt away: the body stops chasing its oxygen debt and starts working in balance."),
            ("What studies say", "Physiologists have measured the phenomenon in the lab: oxygen uptake rises quickly at the start of exercise and reaches a plateau, while blood lactate first increases and then stabilises. The second wind coincides with this steady state. Not everyone feels it the same way: well-trained people reach equilibrium sooner and barely notice the shift, while occasional runners experience it as a small rebirth."),
            ("How to invite it", "The easiest way to meet your second wind is to start slowly. A ten-minute warm-up at an easy pace lets heart, vessels and mitochondria raise their output gradually, avoiding the initial debt that makes the first kilometres unpleasant. Breathing to a steady rhythm, say three steps in and two steps out, also helps. Above all, do not stop at the first minutes of fatigue: the moment when everything gets easier is often one step away."),
        ],
    },
    "sport-doms": {
        "it": [
            ("Perché arriva in ritardo", "Il dolore muscolare compare 24-72 ore dopo perché non nasce dallo sforzo in sé ma dall'infiammazione che segue le micro-lesioni. Le cellule immunitarie raggiungono le fibre danneggiate, rilasciano sostanze che sensibilizzano i nervi e richiamano liquidi, causando un lieve gonfiore. Questo processo ha bisogno di tempo: per questo il giorno dopo si sta ancora bene e quello successivo si fa fatica a scendere le scale."),
            ("Le contrazioni eccentriche", "Non tutti i movimenti fanno male allo stesso modo. I dolori peggiori arrivano dopo le contrazioni eccentriche, quelle in cui il muscolo si allunga mentre resiste a un carico: scendere le scale, la fase di discesa di uno squat, correre in discesa. In quella fase poche fibre reggono molta tensione e si danneggiano di più. È il motivo per cui una lunga camminata in discesa lascia più indolenziti di una salita altrettanto faticosa."),
            ("Cosa aiuta davvero", "Molti rimedi tradizionali funzionano poco: lo stretching statico prima o dopo non previene il dolore e il ghiaccio riduce solo la sensazione per qualche minuto. Le evidenze migliori riguardano il movimento leggero, che aumenta il flusso di sangue, il massaggio, il sonno e una buona quota di proteine. La notizia migliore è che il muscolo si adatta: ripetendo lo stesso esercizio entro una o due settimane, il dolore sarà molto minore."),
        ],
        "en": [
            ("Why it arrives late", "Muscle soreness appears 24-72 hours later because it does not come from the effort itself but from the inflammation that follows micro-tears. Immune cells reach the damaged fibres, release substances that sensitise nerves and draw in fluid, causing slight swelling. This process takes time: that is why you feel fine the next day and struggle to walk downstairs the day after."),
            ("Eccentric contractions", "Not all movements hurt the same way. The worst soreness follows eccentric contractions, when the muscle lengthens while resisting a load: walking downstairs, the lowering phase of a squat, downhill running. In that phase few fibres bear a lot of tension and get damaged more. That is why a long downhill walk leaves you stiffer than an equally tiring climb."),
            ("What really helps", "Many traditional remedies do little: static stretching before or after does not prevent soreness, and ice only numbs the feeling for a few minutes. The best evidence supports light movement, which increases blood flow, massage, sleep and a good protein intake. The best news is that muscle adapts: repeat the same exercise within a week or two and the soreness will be far milder."),
        ],
    },
    "sport-marathon-wall": {
        "it": [
            ("Il cervello nel muro", "Il muro non è solo una questione di gambe. Il cervello consuma quasi esclusivamente glucosio e, quando la glicemia cala, riduce per precauzione il segnale inviato ai muscoli: è il cosiddetto governatore centrale. Il risultato è una sensazione di pesantezza e confusione che sembra arrivare dal nulla. Per questo molti maratoneti ricordano il muro come un momento mentale prima ancora che fisico."),
            ("Allenare il metabolismo dei grassi", "Il corpo ha due serbatoi: circa 2.000 calorie di glicogeno e decine di migliaia in forma di grasso. Il problema è che il grasso brucia lentamente. Le corse lunghe a ritmo lento insegnano ai muscoli a usarlo di più, risparmiando glicogeno; alcuni atleti eseguono sedute a digiuno proprio per questo. Chi si allena bene sposta il muro oltre il traguardo perché consuma gli zuccheri con parsimonia."),
            ("La strategia del giorno della gara", "Tre regole evitano il muro a quasi tutti. Partire al ritmo previsto e non più veloce, perché ogni secondo guadagnato nei primi chilometri costa glicogeno prezioso. Assumere carboidrati durante la gara, 30-60 grammi l'ora tra gel e bevande, cominciando presto e non quando si è già in crisi. E arrivare al via con le riserve piene grazie a due o tre giorni di pasti ricchi di carboidrati."),
        ],
        "en": [
            ("The brain inside the wall", "The wall is not only about legs. The brain runs almost exclusively on glucose and, when blood sugar drops, it precautionarily reduces the signal sent to the muscles: the so-called central governor. The result is a heaviness and confusion that seems to come from nowhere. That is why many marathoners remember the wall as a mental moment even before a physical one."),
            ("Training fat metabolism", "The body has two tanks: about 2,000 calories of glycogen and tens of thousands stored as fat. The problem is that fat burns slowly. Long slow runs teach muscles to use more of it, sparing glycogen; some athletes even train fasted for this reason. Well-trained runners push the wall beyond the finish line because they spend their sugars frugally."),
            ("Race-day strategy", "Three rules keep almost everyone away from the wall. Start at the planned pace and not faster, because every second gained early costs precious glycogen. Take carbohydrates during the race, 30-60 grams per hour from gels and drinks, starting early rather than when the crisis has begun. And reach the start line with full stores thanks to two or three days of carbohydrate-rich meals."),
        ],
    },
    "sport-cold-water": {
        "it": [
            ("Cosa dice la ricerca recente", "Studi condotti su atleti di forza hanno mostrato che l'immersione in acqua fredda subito dopo l'allenamento riduce l'attivazione delle vie che costruiscono nuovo muscolo. L'infiammazione, spesso vista come nemica, è in realtà il segnale che avvia la riparazione e l'adattamento. Spegnerla con il ghiaccio ogni volta significa allenarsi tanto e adattarsi meno."),
            ("Freddo e mente", "C'è però un beneficio meno discusso: la sensazione. Chi fa un bagno freddo riferisce meno dolore percepito, più energia e un umore migliore nelle ore successive, in parte per il rilascio di noradrenalina e in parte per l'effetto placebo, che nello sport non è affatto trascurabile. Sentirsi recuperati permette di affrontare la sessione seguente con più fiducia."),
            ("La regola pratica", "Il consiglio dei fisiologi oggi è semplice. Se l'obiettivo è crescere in forza o massa, evita il ghiaccio nelle ore dopo la seduta e lascia lavorare l'infiammazione. Se invece devi gareggiare di nuovo entro poche ore o pochi giorni, per esempio in un torneo, l'acqua fredda a 10-15 gradi per dieci minuti aiuta a sentirsi pronti. Il ghiaccio è uno strumento, non un rito."),
        ],
        "en": [
            ("What recent research says", "Studies on strength athletes have shown that cold-water immersion right after training reduces the activation of the pathways that build new muscle. Inflammation, often seen as an enemy, is actually the signal that starts repair and adaptation. Switching it off with ice every time means training a lot and adapting less."),
            ("Cold and the mind", "There is a less discussed benefit, though: how you feel. People who take cold baths report less perceived pain, more energy and a better mood in the following hours, partly due to noradrenaline release and partly to a placebo effect, which in sport is far from negligible. Feeling recovered lets you face the next session with more confidence."),
            ("The practical rule", "Physiologists' advice today is simple. If your goal is strength or muscle growth, avoid ice in the hours after a session and let inflammation do its job. If instead you must compete again within hours or days, say in a tournament, cold water at 10-15 degrees for ten minutes helps you feel ready. Ice is a tool, not a ritual."),
        ],
    },
    "sport-heart-athlete": {
        "it": [
            ("Il cuore che cresce", "Anni di allenamento aerobico modificano la struttura del cuore: le pareti del ventricolo sinistro si ispessiscono leggermente e la cavità si allarga. È il cosiddetto cuore d'atleta, un adattamento fisiologico e reversibile che permette di pompare fino a 35-40 litri di sangue al minuto durante lo sforzo massimo, contro i circa 20 di una persona sedentaria."),
            ("Il sistema nervoso", "La frequenza bassa a riposo non dipende solo dalle dimensioni del cuore. L'allenamento aumenta il tono del nervo vago, la componente parasimpatica che frena il battito, e riduce l'influenza del sistema simpatico che lo accelera. Per questo gli atleti si rilassano più in fretta dopo uno sforzo e recuperano il battito normale in pochi minuti: è uno degli indici di forma più usati dagli allenatori."),
            ("Quando preoccuparsi", "Un battito lento in un atleta è normale, ma non tutte le bradicardie sono innocue. Se la frequenza bassa si accompagna a vertigini, svenimenti o affanno insolito, va indagata con un elettrocardiogramma. I cardiologi dello sport distinguono il cuore d'atleta dalle cardiomiopatie proprio con questi esami. La regola d'oro: chi si allena seriamente fa un controllo cardiologico periodico."),
        ],
        "en": [
            ("A heart that grows", "Years of aerobic training reshape the heart: the walls of the left ventricle thicken slightly and the chamber enlarges. This is the so-called athlete's heart, a physiological and reversible adaptation that allows pumping up to 35-40 litres of blood per minute during maximal effort, against about 20 for a sedentary person."),
            ("The nervous system", "A low resting rate does not depend on heart size alone. Training increases vagal tone, the parasympathetic component that slows the beat, and reduces the influence of the sympathetic system that speeds it up. That is why athletes settle faster after exertion and return to a normal pulse within minutes: it is one of the fitness markers coaches use most."),
            ("When to worry", "A slow pulse in an athlete is normal, but not every bradycardia is harmless. If the low rate comes with dizziness, fainting or unusual breathlessness, it should be checked with an electrocardiogram. Sports cardiologists tell athlete's heart apart from cardiomyopathies precisely with these tests. Golden rule: anyone who trains seriously gets a periodic heart check-up."),
        ],
    },
    "sport-flow-state": {
        "it": [
            ("Cosa succede nel cervello", "Le neuroimmagini mostrano che durante il flow la corteccia prefrontale, sede dell'autocritica e del monitoraggio di sé, riduce la sua attività: è la cosiddetta ipofrontalità transitoria. Contemporaneamente aumentano dopamina e noradrenalina, che affinano attenzione e riflessi. Il risultato è una mente che smette di commentare e lascia il comando alle abilità automatizzate in anni di pratica."),
            ("Il tempo che cambia", "Uno dei segni più riconoscibili della zona è la distorsione del tempo. Molti atleti raccontano che la palla sembra rallentare o che un'ora di allenamento passa in un attimo. Accade perché l'attenzione, tutta concentrata sul compito, non tiene più il conto dei secondi. È la stessa esperienza dei musicisti durante un concerto riuscito o dei programmatori assorti in un problema."),
            ("Allenare la zona", "Il flow non si comanda, ma si prepara. Servono obiettivi chiari per ogni sessione, un feedback immediato su come sta andando, l'eliminazione delle distrazioni e un compito appena oltre le proprie capacità attuali. Molti campioni usano una routine pre-gara fissa, quasi un rituale, per segnalare al cervello che è il momento di entrare in quello stato. Con il tempo la porta si apre sempre più facilmente."),
        ],
        "en": [
            ("What happens in the brain", "Neuroimaging shows that during flow the prefrontal cortex, home of self-criticism and self-monitoring, reduces its activity: the so-called transient hypofrontality. At the same time dopamine and noradrenaline increase, sharpening attention and reflexes. The result is a mind that stops commenting and hands control to skills automated through years of practice."),
            ("Time that changes", "One of the most recognisable signs of the zone is time distortion. Many athletes describe the ball seeming to slow down or an hour of training passing in an instant. It happens because attention, fully absorbed by the task, no longer keeps count of the seconds. It is the same experience musicians have during a great concert or programmers lost in a problem."),
            ("Training the zone", "Flow cannot be commanded, but it can be prepared. You need clear goals for each session, immediate feedback on how it is going, no distractions and a task just beyond your current ability. Many champions use a fixed pre-competition routine, almost a ritual, to tell the brain it is time to enter that state. Over time the door opens more and more easily."),
        ],
    },
    "sport-lesson-warmup": {
        "it": [
            ("Passo 4 — Attiva il sistema nervoso", "Negli ultimi minuti del riscaldamento inserisci due o tre gesti brevi ed esplosivi: qualche balzo, tre o quattro scatti di dieci metri, un paio di lanci. Non servono a stancare, ma a svegliare la connessione tra cervello e muscoli, così che le prime azioni della seduta siano già rapide e coordinate. È il segreto degli sprinter, che prima della gara eseguono partenze a intensità crescente."),
            ("Passo 5 — Dosalo in base al contesto", "Un riscaldamento non è uguale per tutti i giorni. Al freddo servono cinque minuti in più e un abbigliamento a strati da togliere gradualmente; al mattino il corpo è più rigido e chiede più mobilità; prima di una gara conviene finire a intensità alta ma entro dieci minuti dal via, per non perdere l'effetto. Un buon indicatore è la sudorazione leggera: quando compare, il motore è pronto."),
            ("Passo 6 — Gli errori da evitare", "Tre errori rovinano un riscaldamento. Lo stretching statico prolungato prima dello sforzo, che riduce temporaneamente la forza esplosiva: riservalo al dopo. Il riscaldamento troppo lungo o intenso, che consuma energie preziose. E il salto diretto all'esercizio principale, la causa più frequente di stiramenti nei dilettanti. Dieci-quindici minuti ben strutturati sono l'investimento più redditizio dell'intera seduta."),
        ],
        "en": [
            ("Step 4 — Wake up the nervous system", "In the last minutes of the warm-up add two or three short, explosive drills: a few jumps, three or four ten-metre sprints, a couple of throws. They are not meant to tire you but to wake the connection between brain and muscles, so the first actions of the session are already quick and coordinated. It is the sprinters' secret: before a race they perform starts of increasing intensity."),
            ("Step 5 — Adapt it to the context", "A warm-up is not the same every day. In the cold you need five extra minutes and layered clothing to remove gradually; in the morning the body is stiffer and needs more mobility; before a race it is best to finish at high intensity but within ten minutes of the start, so the effect is not lost. A good indicator is light sweating: when it appears, the engine is ready."),
            ("Step 6 — Mistakes to avoid", "Three mistakes ruin a warm-up. Long static stretching before exertion, which temporarily reduces explosive strength: save it for afterwards. A warm-up that is too long or intense, which burns precious energy. And jumping straight into the main exercise, the most frequent cause of strains among amateurs. Ten to fifteen well-structured minutes are the most profitable investment of the whole session."),
        ],
    },
    "sport-lesson-breathing": {
        "it": [
            ("Passo 4 — Naso o bocca?", "A ritmi lenti respirare dal naso filtra e riscalda l'aria e aiuta a tenere un'andatura davvero facile: se non riesci a farlo, stai andando troppo forte. Quando l'intensità sale, la bocca è inevitabile perché lascia passare molta più aria. Molti corridori usano una via mista, naso e bocca insieme, che è la soluzione più naturale. Non esiste una regola rigida: conta che l'aria arrivi senza sforzo."),
            ("Passo 5 — Gestisci il fiatone in salita", "In salita il fiato si accorcia perché il cuore lavora di più. Invece di accelerare il respiro, accorcia il passo e mantieni il ritmo respiratorio, oppure passa a due passi per inspirazione e due per espirazione. Se il fiatone diventa affanno, rallenta fino a poter dire una frase intera: è il test più semplice per sapere se sei nella zona aerobica."),
            ("Passo 6 — Allena il respiro a casa", "Cinque minuti al giorno bastano per rendere il diaframma più forte. Sdraiato, mano sulla pancia, inspira per quattro secondi gonfiando l'addome ed espira per sei. Poi prova lo stesso esercizio in piedi e camminando. In due o tre settimane il respiro addominale diventerà automatico anche durante la corsa, e il punto al fianco, spesso causato da un diaframma affaticato, comparirà molto più raramente."),
        ],
        "en": [
            ("Step 4 — Nose or mouth?", "At easy paces breathing through the nose filters and warms the air and helps you keep a truly easy pace: if you cannot manage it, you are going too fast. When intensity rises the mouth is unavoidable, as it lets through much more air. Many runners use a mixed route, nose and mouth together, which is the most natural solution. There is no rigid rule: what matters is that air comes in without strain."),
            ("Step 5 — Manage breathlessness uphill", "Uphill your breath shortens because the heart works harder. Instead of speeding up your breathing, shorten your stride and keep the breathing rhythm, or switch to two steps in and two steps out. If breathlessness turns into gasping, slow down until you can say a full sentence: it is the simplest test to know you are in the aerobic zone."),
            ("Step 6 — Train your breath at home", "Five minutes a day are enough to strengthen the diaphragm. Lying down, hand on your belly, breathe in for four seconds inflating the abdomen and out for six. Then try the same exercise standing and walking. In two or three weeks belly breathing will become automatic while running too, and the side stitch, often caused by a tired diaphragm, will appear far less often."),
        ],
    },
    "gen-lesson-ideal-running-cadence-how-to-find-your-rhythm-without-wastin": {
        "it": [
            ("6. Mantienila nel tempo", "Una cadenza migliore si perde in fretta se non la si rinforza. Una volta a settimana corri dieci minuti seguendo un metronomo o una playlist con i battiti giusti, e ogni tanto controlla il dato sull'orologio nelle ultime fasi di una corsa lunga, quando la stanchezza tende a farti allungare il passo. Se il numero cala di oltre cinque punti, accorcia la falcata e rilassa le braccia: la cadenza tornerà da sola."),
        ],
        "en": [
            ("6. Keep it over time", "A better cadence fades quickly if it is not reinforced. Once a week run ten minutes following a metronome or a playlist with the right beats, and now and then check the number on your watch in the late stages of a long run, when fatigue tends to lengthen your stride. If the number drops by more than five points, shorten your stride and relax your arms: the cadence will come back on its own."),
        ],
    },
}
