# Capitoli aggiuntivi — SPAZIO
EXTRA = {
    "v4-lez-fasi-luna": {"it": [
        ("Passo 5 — La luce cinerea", "Nei giorni attorno alla Luna nuova, guardando la falce sottile, si intravede debolmente anche la parte in ombra: è la luce cinerea, la luce del Sole riflessa dalla Terra verso la Luna e poi rimandata a noi. Leonardo da Vinci fu il primo a spiegarla correttamente, cinquecento anni fa. Osservandola stai vedendo la Terra fare da luna alla Luna. È più intensa in primavera, quando l'emisfero nord è coperto da più nubi e ghiacci che riflettono meglio."),
        ("Passo 6 — Le fasi e la vita quotidiana", "Le fasi lunari hanno effetti reali e altri leggendari. Le maree sono più forti con Luna piena e nuova, quando Sole e Luna tirano allineati, e più deboli ai quarti. La Luna piena disturba davvero il sonno di qualche minuto, secondo alcuni studi, per la luce in più. Non ha invece effetti misurabili su nascite, umore o crimini, nonostante il mito del lunatico. Le semine secondo la Luna sono una tradizione senza conferme: le piante seguono la luce del Sole e la temperatura."),
    ]},
    "v4-lez-anno-luce": {"it": [
        ("Passo 5 — Come misuriamo le distanze", "Come sappiamo quanto è lontana una stella? Per quelle vicine si usa la parallasse: la stella si sposta leggermente sullo sfondo quando la Terra passa da un lato all'altro della sua orbita, e dall'angolo si ricava la distanza, come quando chiudi un occhio alla volta e il pollice sembra spostarsi. Per le distanze maggiori si usano le candele standard, oggetti di luminosità nota come alcune stelle variabili e le supernove: più appaiono deboli, più sono lontane."),
        ("Passo 6 — I limiti dell'universo osservabile", "L'anno luce ci dice anche dove finisce ciò che possiamo vedere. L'universo ha 13,8 miliardi di anni, quindi nessuna luce ha potuto viaggiare più a lungo di così; ma poiché lo spazio si è espanso durante il viaggio, gli oggetti più lontani che vediamo si trovano oggi a circa 46 miliardi di anni luce. Oltre quel confine può esserci moltissimo altro, ma la sua luce non ci ha ancora raggiunto e, se l'espansione accelera, forse non lo farà mai."),
    ]},
    "v4-lez-riconoscere-pianeti": {"it": [
        ("Passo 5 — I pianeti uno per uno", "Ogni pianeta ha una firma. Venere è la cosa più luminosa del cielo dopo la Luna, bianco abbagliante, sempre vicino all'orizzonte poco dopo il tramonto o prima dell'alba, mai a mezzanotte. Giove è il secondo per luminosità, bianco-giallo, e può stare alto nel cielo per tutta la notte. Marte è arancione-rosso e cambia molto luminosità nel corso degli anni. Saturno è giallo pallido e più debole. Mercurio è raro: basso, vicino al Sole, visibile poche settimane all'anno."),
        ("Passo 6 — Con un binocolo", "Un semplice binocolo trasforma i punti in mondi. Puntando Giove vedrai fino a quattro puntini in fila ai suoi lati: le lune scoperte da Galileo nel 1610, che cambiano posizione da una sera all'altra. Venere mostra fasi come la Luna, e la sua falce è visibile con un binocolo stabile. Saturno appare allungato, e con un piccolo telescopio si separano gli anelli. Marte resta un dischetto arancione. Quattro secoli dopo Galileo, puoi rifare la sua scoperta da un balcone."),
    ]},
    "lez-orientarsi-stelle": {
        "it": [("Passo 6 — Orientarsi con la Luna e i pianeti", "Le stelle non sono l'unico aiuto. La Luna, come il Sole, sorge a est e tramonta a ovest; nel primo quarto, la sera, la parte illuminata guarda verso ovest, dove il Sole è appena tramontato; nell'ultimo quarto, al mattino, guarda verso est. Congiungendo le due punte della falce e prolungando la linea fino all'orizzonte trovi approssimativamente il sud. Anche i pianeti stanno sempre lungo la strada del Sole, quindi indicano la fascia sud del cielo per chi vive nell'emisfero nord.")],
        "en": [("Step 6 — Using the Moon and planets", "Stars are not the only help. The Moon, like the Sun, rises in the east and sets in the west; at first quarter, in the evening, its lit side faces west, where the Sun has just set; at last quarter, in the morning, it faces east. Joining the two tips of the crescent and extending the line to the horizon gives you roughly south. Planets too always lie along the Sun's path, so they mark the southern band of the sky for anyone in the northern hemisphere.")],
    },
    "lez-orbite-gravita": {
        "it": [("Passo 6 — Lasciare l'orbita", "Per abbandonare del tutto la Terra non basta orbitare: serve la velocità di fuga, 11,2 chilometri al secondo, oltre 40.000 chilometri l'ora. A quella velocità la palla di cannone di Newton non torna più indietro, perché la gravità la rallenta ma non abbastanza da fermarla. Le sonde interplanetarie usano poi gli altri pianeti come fionde: passando vicino a Giove rubano un po' della sua energia orbitale e accelerano gratis. Le Voyager, lanciate nel 1977, hanno così superato la velocità di fuga dal Sole e viaggiano ora nello spazio interstellare.")],
        "en": [("Step 6 — Leaving orbit", "To leave Earth entirely, orbiting is not enough: you need escape velocity, 11.2 kilometres per second, over 40,000 kilometres per hour. At that speed Newton's cannonball never comes back, because gravity slows it but not enough to stop it. Interplanetary probes then use other planets as slingshots: passing close to Jupiter they steal a little of its orbital energy and accelerate for free. The Voyagers, launched in 1977, thereby exceeded the Sun's escape velocity and now travel through interstellar space.")],
    },
    "v5-lez-eclissi": {"it": [
        ("Passo 5 — Come osservarle in sicurezza", "Un'eclissi lunare si guarda a occhio nudo senza alcun rischio, in qualsiasi fase. Quella solare no: anche con il 99% del disco coperto, la luce residua brucia la retina senza dolore, perché la retina non ha recettori del dolore. Servono occhiali con filtro certificato ISO 12312-2, non occhiali da sole, CD o vetri affumicati. Solo nei pochi minuti della totalità si può guardare a occhio nudo. Un metodo sicuro per tutti: proiettare l'immagine del Sole attraverso un forellino su un foglio."),
        ("Passo 6 — Le prossime eclissi", "Le eclissi si possono prevedere con secoli di anticipo e si ripetono in cicli di 18 anni e 11 giorni, il saros noto già ai Babilonesi. L'Italia vedrà un'eclissi solare parziale il 12 agosto 2026, con il Sole coperto per oltre il 90% nel nord-ovest, e una totale il 2 agosto 2027 visibile da Lampedusa, mentre in Spagna e Nord Africa la totalità durerà oltre sei minuti. Le eclissi lunari totali sono più frequenti: la prossima ben visibile dall'Italia è il 31 dicembre 2028."),
    ]},
    "v5-lez-sistema-solare-scala": {"it": [
        ("Passo 5 — Quanto sono grandi i pianeti", "Riduciamo anche le taglie. Se il Sole è un pallone da 30 centimetri, la Terra è un granello di 3 millimetri, Marte 1,5, Giove una biglia di 3 centimetri, Saturno poco meno. Dentro il Sole entrano 1,3 milioni di Terre; dentro Giove più di mille. Tutti i pianeti messi in fila starebbero nello spazio tra la Terra e la Luna. E il Sole è una stella di taglia media: Betelgeuse, nella spalla di Orione, arriverebbe fino all'orbita di Giove."),
        ("Passo 6 — Il viaggio più lungo", "Il vuoto si misura anche in tempo. La luce del Sole raggiunge la Terra in 8 minuti, Giove in 43, Nettuno in 4 ore. Una sonda che viaggia a 60.000 chilometri l'ora, come New Horizons, ha impiegato nove anni per raggiungere Plutone e le Voyager hanno impiegato 35 anni per uscire dalla bolla del vento solare. Per arrivare alla stella più vicina, Proxima Centauri, con la stessa velocità ci vorrebbero 75.000 anni. Il Sistema Solare è quasi tutto spazio vuoto, e attorno c'è uno spazio ancora più vuoto."),
    ]},
    "v5-lez-telescopio": {"it": [
        ("Passo 5 — Oltre la luce visibile", "La luce che vediamo è una fetta sottile di ciò che l'universo emette. I radiotelescopi captano onde radio da nubi di gas fredde e dai buchi neri, e l'immagine del buco nero in M87 del 2019 è stata ottenuta collegando antenne su tutta la Terra. Il James Webb lavora nell'infrarosso, che attraversa la polvere e mostra le prime galassie. I telescopi a raggi X, in orbita perché l'atmosfera li blocca, vedono gas a milioni di gradi. Ogni finestra rivela un universo diverso."),
        ("Passo 6 — Comprare il primo telescopio", "Se vuoi cominciare, ignora gli ingrandimenti scritti sulla scatola e guarda l'apertura: un riflettore da 130-150 millimetri di diametro su montatura stabile mostra i crateri lunari, gli anelli di Saturno, le lune di Giove e le nebulose più brillanti, e costa quanto uno smartphone economico. Un buon binocolo 10x50 è però il primo acquisto giusto: leggero, immediato, ideale per la Via Lattea e gli ammassi. Il miglior telescopio è quello che usi davvero, e il cielo migliore è quello lontano dalle luci."),
    ]},
    "v5-lez-costellazioni": {"it": [
        ("Passo 5 — Le costellazioni sono un'illusione", "Le stelle di una costellazione non hanno nulla in comune tra loro: sono a distanze enormemente diverse e sembrano vicine solo perché le vediamo sulla stessa linea di vista. Nel Grande Carro le stelle stanno tra 80 e 120 anni luce, e tra 50.000 anni il disegno sarà irriconoscibile perché ognuna si muove in una direzione diversa. Le costellazioni sono mappe mentali, utili come i quartieri di una città; e culture diverse hanno tracciato disegni diversi sulle stesse stelle."),
        ("Passo 6 — Le 88 ufficiali e lo zodiaco", "Nel 1922 l'Unione Astronomica Internazionale ha fissato 88 costellazioni con confini precisi che coprono tutto il cielo, così ogni stella appartiene a una sola. Molte di quelle dell'emisfero sud furono inventate dai navigatori del Seicento e hanno nomi di strumenti: il Microscopio, il Telescopio, l'Orologio. Le dodici dello zodiaco sono quelle attraversate dal Sole, ma per la precessione dell'asse terrestre il Sole oggi sta in ciascuna circa un mese dopo rispetto ai segni astrologici, e attraversa anche una tredicesima, l'Ofiuco."),
    ]},
    "v5-lez-assenza-peso": {"it": [
        ("Passo 5 — Cosa fa al corpo", "Fluttuare ha un prezzo. Senza peso da sostenere, ossa e muscoli si indeboliscono: gli astronauti perdono fino all'1-2% di massa ossea al mese e devono allenarsi due ore al giorno. I fluidi salgono verso la testa, gonfiando il viso e comprimendo il nervo ottico; il cuore si riduce leggermente perché fatica meno. Al ritorno molti non riescono a stare in piedi per qualche ora. Un viaggio verso Marte di sei mesi è, per il corpo, la sfida principale."),
        ("Passo 6 — Gravità artificiale", "La soluzione dei film è far ruotare l'astronave: la forza centrifuga spinge verso il pavimento e simula il peso. Funziona, ma serve un raggio grande, decine di metri, altrimenti la differenza tra testa e piedi dà nausea. Nessuna stazione l'ha ancora realizzata per costi e complessità. La NASA ha testato per ora sedute su centrifughe brevi. Per il momento la gravità artificiale resta l'unica tecnologia spaziale che vediamo al cinema da cinquant'anni e non ancora in orbita."),
    ]},
    "moon-tides": {
        "it": [("Le maree più grandi del mondo", "Nella Baia di Fundy, in Canada, il dislivello tra alta e bassa marea raggiunge i 16 metri, l'altezza di un palazzo di cinque piani, perché la forma della baia entra in risonanza con il ritmo delle maree. Al Mont-Saint-Michel il mare si ritira per chilometri e torna, dicevano gli antichi, alla velocità di un cavallo al galoppo. Nel Mediterraneo le maree sono modeste, pochi decimetri, perché il bacino è quasi chiuso; ma a Venezia bastano per l'acqua alta.")],
        "en": [("The biggest tides in the world", "In Canada's Bay of Fundy the difference between high and low tide reaches 16 metres, the height of a five-storey building, because the bay's shape resonates with the rhythm of the tides. At Mont-Saint-Michel the sea withdraws for kilometres and returns, the ancients said, at the speed of a galloping horse. In the Mediterranean tides are modest, a few tens of centimetres, because the basin is almost closed; yet in Venice they are enough for the acqua alta.")],
    },
    "how-stars-die": {
        "it": [("Il destino del Sole", "Il nostro Sole seguirà la via delle stelle piccole. Tra circa cinque miliardi di anni, esaurito l'idrogeno nel nucleo, si gonfierà in una gigante rossa cento volte più grande, inghiottendo Mercurio e Venere e rendendo la Terra una roccia arroventata. Poi espellerà gli strati esterni in una nebulosa colorata e resterà un nucleo bianco grande quanto la Terra, che si raffredderà per miliardi di anni. Molto prima, tra un miliardo di anni, la sua luminosità crescente avrà già fatto evaporare gli oceani.")],
        "en": [("The fate of the Sun", "Our Sun will follow the path of small stars. In about five billion years, with the hydrogen in its core exhausted, it will swell into a red giant a hundred times larger, swallowing Mercury and Venus and turning Earth into a scorched rock. Then it will shed its outer layers into a colourful nebula and leave a white core the size of Earth, cooling for billions of years. Long before that, in a billion years, its growing brightness will already have boiled away the oceans.")],
    },
    "why-sun-shines": {
        "it": [("Il Sole visto da vicino", "Dal 2018 la sonda Parker Solar Probe sfiora il Sole più di qualsiasi oggetto costruito dall'uomo, passando a sei milioni di chilometri dalla superficie attraverso la corona, la parte esterna dell'atmosfera solare, protetta da uno scudo di carbonio che regge 1.400 gradi. Ha risolto un mistero antico: perché la corona è a un milione di gradi mentre la superficie è a 5.500. La risposta sta nei campi magnetici che si attorcigliano e rilasciano energia come elastici. Il Sole è un laboratorio di fisica che possiamo finalmente toccare.")],
        "en": [("The Sun up close", "Since 2018 the Parker Solar Probe has skimmed the Sun closer than any human-made object, passing six million kilometres from the surface through the corona, the outer part of the solar atmosphere, protected by a carbon shield that withstands 1,400 degrees. It has helped solve an ancient mystery: why the corona is at a million degrees while the surface is at 5,500. The answer lies in magnetic fields that twist and release energy like rubber bands. The Sun is a physics lab we can finally touch.")],
    },
    "how-many-galaxies": {
        "it": [("Lo scontro con Andromeda", "La galassia più vicina alla nostra, Andromeda, si avvicina a 110 chilometri al secondo. Tra circa quattro miliardi di anni le due galassie si fonderanno in una sola, soprannominata Lattomeda. Non sarà uno scontro violento per le stelle, tanto distanti tra loro che quasi nessuna collisione avverrà, ma il cielo notturno cambierà completamente e i due buchi neri centrali finiranno per fondersi. Il Sole, se ancora esiste, verrà probabilmente spinto in un'orbita più esterna.")],
        "en": [("The collision with Andromeda", "The nearest large galaxy, Andromeda, is approaching at 110 kilometres per second. In about four billion years the two galaxies will merge into one, nicknamed Milkomeda. It will not be a violent crash for the stars, which are so far apart that almost no collisions will occur, but the night sky will change completely and the two central black holes will eventually merge. The Sun, if it still exists, will probably be flung into a more distant orbit.")],
    },
    "how-iss-works": {
        "it": [("Come vederla dal balcone", "La Stazione Spaziale è visibile a occhio nudo ed è uno degli oggetti più luminosi del cielo. Passa sopra l'Italia diverse volte a settimana, poco dopo il tramonto o prima dell'alba, quando il cielo è scuro ma la stazione, 400 chilometri più in alto, è ancora illuminata dal Sole. Appare come una stella bianchissima che si muove senza lampeggiare, attraversando il cielo in circa cinque minuti da ovest verso est. Siti e app gratuite come Spot the Station indicano l'orario esatto per la tua città.")],
        "en": [("How to see it from your balcony", "The Space Station is visible to the naked eye and is one of the brightest objects in the sky. It passes over Europe several times a week, shortly after sunset or before dawn, when the sky is dark but the station, 400 kilometres higher, is still lit by the Sun. It appears as a very bright white star moving without blinking, crossing the sky in about five minutes from west to east. Free sites and apps such as Spot the Station give the exact time for your city.")],
    },
    "big-bang-basics": {
        "it": [("Cosa c'era prima?", "La domanda più naturale è anche la più difficile. Nella relatività generale, il tempo stesso nasce con il Big Bang, quindi chiedere cosa c'era prima è come chiedere cosa c'è a nord del Polo Nord. Ma la teoria smette di funzionare nel primo istante, dove servirebbe una fisica quantistica della gravità che non abbiamo. Alcune ipotesi parlano di un universo che rimbalza, altre di un multiverso in cui il nostro è una bolla tra tante. Per ora sono idee, non risultati: la frontiera è esattamente lì.")],
        "en": [("What came before?", "The most natural question is also the hardest. In general relativity, time itself begins with the Big Bang, so asking what came before is like asking what lies north of the North Pole. But the theory breaks down in the first instant, where we would need a quantum physics of gravity we do not have. Some hypotheses speak of a bouncing universe, others of a multiverse in which ours is one bubble among many. For now these are ideas, not results: the frontier is exactly there.")],
    },
    "why-comets-tails": {
        "it": [("Atterrare su una cometa", "Nel 2014 la sonda europea Rosetta ha raggiunto la cometa 67P dopo dieci anni di viaggio e ha fatto scendere il lander Philae sulla sua superficie: il primo atterraggio su una cometa. Le immagini hanno mostrato un corpo a forma di papera lungo quattro chilometri, nero come il carbone, con scogliere, pozzi e getti di gas. Rosetta ha trovato molecole organiche e ossigeno, e ha misurato acqua diversa da quella terrestre, mettendo in dubbio l'idea che i nostri oceani vengano dalle comete.")],
        "en": [("Landing on a comet", "In 2014 the European probe Rosetta reached comet 67P after a ten-year journey and dropped the Philae lander onto its surface: the first landing on a comet. Images showed a duck-shaped body four kilometres long, black as coal, with cliffs, pits and gas jets. Rosetta found organic molecules and oxygen, and measured water different from Earth's, casting doubt on the idea that our oceans came from comets.")],
    },
    "exoplanets-basics": {
        "it": [("I mondi più strani", "La galassia ha immaginazione più di noi. Esistono pianeti che orbitano attorno a due stelle, come Tatooine; giganti gassosi così vicini alla loro stella da compiere un giro in poche ore, con temperature da 2.000 gradi e piogge di ferro fuso; pianeti fatti forse di diamante; mondi erranti espulsi dal loro sistema che vagano soli nel buio. Il sistema TRAPPIST-1 ha sette pianeti di taglia terrestre attorno a una stella nana, tre nella zona abitabile, a 40 anni luce da noi: uno dei luoghi più promettenti per cercare la vita.")],
        "en": [("The strangest worlds", "The galaxy has more imagination than we do. There are planets orbiting two stars, like Tatooine; gas giants so close to their star they complete an orbit in hours, with temperatures of 2,000 degrees and rains of molten iron; planets possibly made of diamond; rogue worlds expelled from their systems, wandering alone in the dark. The TRAPPIST-1 system has seven Earth-sized planets around a dwarf star, three in the habitable zone, 40 light-years away: one of the most promising places to look for life.")],
    },
    "v4-luna-stessa-faccia": {"it": [
        ("Il primo sguardo sull'altro lato", "Nessun essere umano vide il lato nascosto della Luna fino al 7 ottobre 1959, quando la sonda sovietica Luna 3 lo fotografò e trasmise a Terra immagini sgranate ma rivoluzionarie. I sovietici battezzarono i nuovi crateri e mari con nomi russi, come il Mare di Mosca. Nel 1968 gli astronauti dell'Apollo 8 furono i primi a vederlo con i propri occhi, e nel 2019 la sonda cinese Chang'e 4 è stata la prima a posarsi su quel lato, comunicando tramite un satellite di rimbalzo perché la Luna blocca il segnale diretto."),
        ("Anche la Terra rallenta", "La stessa forza che ha bloccato la Luna sta lavorando sulla Terra. L'attrito delle maree rallenta la rotazione del nostro pianeta di circa due millesimi di secondo per secolo: il giorno di un dinosauro durava 23 ore, quello dei primi organismi meno di 20. L'energia persa dalla Terra passa alla Luna, che si allontana di 3,8 centimetri l'anno, un dato misurato con i laser riflessi dagli specchi lasciati dagli astronauti dell'Apollo. In un futuro remoto la Terra mostrerà alla Luna sempre la stessa faccia."),
    ]},
    "v4-giorno-venere": {"it": [
        ("L'inferno gemello della Terra", "Venere ha quasi le stesse dimensioni e la stessa massa della Terra, e per questo veniva chiamata il pianeta gemello. Ma la sua atmosfera di anidride carbonica, 90 volte più densa della nostra, intrappola il calore in un effetto serra fuori controllo: 465 gradi in superficie, giorno e notte, ai poli come all'equatore, e nuvole di acido solforico. Le sonde sovietiche Venera che vi atterrarono negli anni Settanta e Ottanta resistettero al massimo due ore prima di essere schiacciate e fuse."),
        ("Le prossime missioni", "Dopo trent'anni di poco interesse Venere è tornata al centro dell'attenzione. Nel 2020 un gruppo di ricercatori ha annunciato tracce di fosfina nelle nuvole, un gas che sulla Terra è prodotto dalla vita, e il dibattito che ne è seguito ha spinto la NASA a approvare due missioni, DAVINCI e VERITAS, e l'ESA la sonda EnVision, in partenza nei primi anni Trenta. L'obiettivo è capire se Venere abbia avuto oceani e perché sia diventata ciò che è: la risposta riguarda anche il futuro della Terra."),
    ]},
    "v4-fascia-asteroidi": {"it": [
        ("Gli asteroidi che ci hanno visitato", "La fascia non è del tutto tranquilla: le collisioni tra asteroidi e l'influenza di Giove ne spingono ogni tanto alcuni verso il Sistema Solare interno. Uno di questi, largo dieci chilometri, colpì la Terra 66 milioni di anni fa e pose fine all'era dei dinosauri. Nel 2013 un frammento di venti metri esplose sopra Chelyabinsk, in Russia, ferendo 1.500 persone con i vetri rotti. Per questo la NASA e l'ESA catalogano gli asteroidi vicini alla Terra: ne conoscono oltre 35.000, e nessuno di grandi dimensioni è in rotta di collisione nei prossimi cento anni."),
        ("Spostare un asteroide", "Nel settembre 2022 l'umanità ha modificato per la prima volta l'orbita di un corpo celeste. La sonda DART della NASA si è schiantata a 22.000 chilometri l'ora contro Dimorphos, un asteroide di 160 metri che orbita attorno a uno più grande, accorciandone il periodo di 32 minuti, molto più del previsto. La missione europea Hera arriverà nel 2026 a misurare il cratere. Se un giorno scoprissimo un asteroide pericoloso con anni di anticipo, sappiamo ora che una spinta basterebbe."),
    ]},
    "v5-saturno-galleggia": {"it": [
        ("Gli anelli sono giovani e temporanei", "Gli anelli di Saturno sono fatti di miliardi di frammenti di ghiaccio quasi puro, da granelli a case, disposti in un disco largo 280.000 chilometri ma spesso in media solo dieci metri. Le misure della sonda Cassini indicano che sono giovani, forse 100 milioni di anni, nati dalla distruzione di una luna o di una cometa, e che stanno piovendo sul pianeta: tra 100 e 300 milioni di anni saranno spariti. Viviamo nell'epoca giusta per vederli, e nel 2025 il loro piano è passato di taglio rispetto alla Terra, rendendoli quasi invisibili per qualche mese."),
        ("Le lune che promettono vita", "Saturno ha oltre 140 lune conosciute e due sono tra i luoghi più interessanti del Sistema Solare. Encelado spruzza dal polo sud geyser d'acqua salata che Cassini ha attraversato, trovando idrogeno e molecole organiche: sotto la crosta c'è un oceano con sorgenti idrotermali. Titano, più grande di Mercurio, ha un'atmosfera densa e laghi di metano liquido, l'unico posto oltre la Terra con liquidi in superficie. La missione Dragonfly della NASA vi farà volare un drone dal 2034."),
    ]},
    "v5-astronauti-alti": {"it": [
        ("Il record e il ritorno", "Il cambiamento più studiato è avvenuto sui gemelli Kelly: Scott ha passato 340 giorni in orbita mentre Mark, suo gemello identico, restava a Terra. Al ritorno Scott era più alto di cinque centimetri, e in pochi giorni è tornato normale, ma l'espressione di migliaia di geni era cambiata, i telomeri si erano allungati per poi accorciarsi bruscamente, e il sistema immunitario aveva reagito come a uno stress prolungato. La maggior parte delle differenze è sparita entro sei mesi."),
        ("Preparare il corpo per Marte", "Ciò che accade alla colonna vertebrale è uno degli ostacoli per i viaggi lunghi. Gli astronauti che tornano da sei mesi hanno un rischio di ernia del disco quattro volte più alto nell'anno successivo. Per un viaggio verso Marte di due o tre anni si studiano tute compressive che simulano il peso, esercizi mirati per i muscoli profondi della schiena e, per il futuro, sezioni rotanti che producano gravità artificiale. Il corpo che si allunga nello spazio è un promemoria: siamo costruiti per la Terra."),
    ]},
    "v5-corpo-senza-tuta": {"it": [
        ("È già successo, a qualcuno", "Non è solo teoria. Nel 1966 un tecnico della NASA, Jim LeBlanc, stava testando una tuta in una camera a vuoto quando un tubo si staccò: perse conoscenza in quattordici secondi e ricorda solo la saliva che gli bolliva sulla lingua. Fu salvato in meno di trenta secondi e si riprese completamente. Nel 1971 i tre cosmonauti della Soyuz 11 morirono invece quando una valvola si aprì durante il rientro: l'unica tragedia umana avvenuta nello spazio vero, che portò a rendere obbligatorie le tute durante decollo e rientro."),
        ("Come funziona una tuta spaziale", "La tuta è una piccola astronave personale. Mantiene una pressione di circa un terzo di quella terrestre con ossigeno puro, il che costringe gli astronauti a respirare ossigeno per ore prima di uscire per eliminare l'azoto dal sangue. Quattordici strati proteggono da micrometeoriti, radiazioni e sbalzi tra 120 gradi al sole e meno 150 all'ombra; un sottotuta percorso da tubicini d'acqua raffredda il corpo. Pesa 130 chili, costa decine di milioni e i guanti restano la parte più difficile da progettare."),
    ]},
    "v5-pioggia-diamanti": {"it": [
        ("Perché Nettuno è così blu", "Il metano che si spezza in profondità è anche il responsabile del colore. Alto nell'atmosfera, assorbe la luce rossa e riflette quella blu, dando a Nettuno il suo azzurro intenso. Urano, con più foschia, appare verde-acqua. Le due atmosfere producono anche i venti più veloci del Sistema Solare: su Nettuno raggiungono i 2.000 chilometri l'ora, senza che si sappia bene da dove venga l'energia, dato che il Sole vi arriva 900 volte più debole che sulla Terra."),
        ("Le uniche visite", "Tutto ciò che sappiamo da vicino di questi due mondi viene da un solo passaggio ciascuno: la Voyager 2 nel 1986 per Urano e nel 1989 per Nettuno, pochi giorni di dati in tutto. Sono i pianeti meno esplorati del Sistema Solare, eppure quelli di tipo più comune nella galassia. Le agenzie spaziali discutono da anni una missione orbitale attorno a Urano, indicata come priorità per il prossimo decennio: con le finestre di lancio giuste, arriverebbe attorno al 2045."),
    ]},
    "v5-tempesta-giove": {"it": [
        ("Il tempo su Giove", "La Grande Macchia Rossa non è sola. Giove è coperto da fasce di nubi che scorrono in direzioni opposte a centinaia di chilometri l'ora, con fulmini mille volte più potenti dei nostri e, ai poli, cicloni grandi quanto la Terra disposti in schemi geometrici scoperti dalla sonda Juno nel 2017. Sotto le nubi di ammoniaca il pianeta non ha superficie: l'idrogeno diventa sempre più denso fino a trasformarsi in metallo liquido, generando il campo magnetico più forte tra i pianeti."),
        ("La macchia vista dai telescopi", "Le prime osservazioni di una macchia su Giove risalgono a Cassini nel 1665, ma non è certo che fosse la stessa: le registrazioni continue partono dal 1831. Da allora si è ridotta da 40.000 a 16.000 chilometri e ha cambiato tinta dal rosso mattone al salmone. Nel 2019 sembrava sfaldarsi, con lembi di nube strappati via, ma si è ricompattata. Oggi chiunque con un telescopio da 15 centimetri può vederla nelle notti buone: una tempesta iniziata forse prima della nascita di Galileo."),
    ]},
}
