# Capitoli aggiuntivi — SCIENZA
EXTRA = {
    "v4-lez-densita": {"it": [
        ("Passo 5 — Il principio di Archimede", "Dietro la regola c'è una legge precisa, scoperta ad Archimede, secondo la leggenda, in una vasca da bagno: un corpo immerso riceve una spinta verso l'alto pari al peso del fluido che sposta. Se pesa meno di quell'acqua, galleggia; se pesa di più, affonda. Per questo una nave affonda finché non ha spostato tanta acqua quanto il suo peso, e una nave carica sta più bassa. Il fluido non deve essere acqua: una mongolfiera galleggia nell'aria per lo stesso motivo."),
        ("Passo 6 — Densità nella vita di tutti i giorni", "La densità spiega decine di cose quotidiane. L'olio galleggia sul brodo perché è meno denso dell'acqua, e per lo stesso motivo la vinaigrette si separa. Il ghiaccio galleggia nel bicchiere. Nel Mar Morto, dove il sale rende l'acqua più densa, il corpo umano galleggia senza sforzo. I palloncini a elio salgono, quelli gonfiati con la bocca cadono. E la lava fa risalire i metalli più leggeri e sprofondare quelli pesanti: è così che il ferro è finito al centro della Terra."),
    ]},
    "v4-lez-atomo": {"it": [
        ("Passo 5 — Perché gli atomi si legano", "Gli atomi cercano di completare il guscio più esterno di elettroni, e per farlo si scambiano o si condividono elettroni: è questo il legame chimico. Il sodio ha un elettrone di troppo e il cloro ne vuole uno: il sodio lo cede e nasce il sale da cucina. Due atomi di idrogeno e uno di ossigeno condividono elettroni e formano l'acqua. Tutta la chimica, dalla digestione alle batterie, è il racconto di elettroni che cambiano posto."),
        ("Passo 6 — Vedere gli atomi", "Per un secolo l'atomo è stato un'ipotesi utile: nessuno lo aveva visto. Nel 1981 il microscopio a effetto tunnel ha permesso di osservare singoli atomi come piccole gobbe su una superficie e persino di spostarli uno a uno: nel 1989 ricercatori IBM scrissero il logo dell'azienda con 35 atomi di xeno. Oggi i microscopi elettronici mostrano la disposizione degli atomi in un cristallo con chiarezza. La palla invisibile dei greci è diventata qualcosa che si può fotografare."),
    ]},
    "v4-lez-leggere-etichetta": {"it": [
        ("Passo 5 — Il mito del naturale", "Naturale non significa sicuro e chimico non significa pericoloso: tutto è chimico, compresa l'acqua. La cicuta e l'amanita sono perfettamente naturali; l'acido citrico del limone e quello prodotto in fabbrica sono la stessa identica molecola. Molte etichette sfruttano la parola naturale per vendere di più, senza che cambi nulla nella composizione. Giudica un prodotto per quello che contiene e per la dose, mai per l'origine dichiarata degli ingredienti."),
        ("Passo 6 — Mai mescolare", "Un'ultima regola può evitarti un incidente domestico. Non mescolare mai la candeggina, ipoclorito di sodio, con l'ammoniaca o con gli anticalcare acidi: le reazioni producono gas tossici, clorammine e cloro, responsabili ogni anno di intossicazioni in casa. Usa un prodotto alla volta, sciacqua tra l'uno e l'altro, tieni le finestre aperte. Le etichette lo scrivono, ma in piccolo: ora sai perché quella riga è la più importante di tutte."),
    ]},
    "lez-metodo-scientifico": {
        "it": [("Passo 6 — Il consenso e il dubbio", "Un singolo esperimento non basta mai: la scienza si fida di un risultato solo quando altri laboratori lo hanno replicato e la comunità lo ha esaminato. Per questo una notizia su 'uno studio dimostra che' vale poco finché non è confermata. Al tempo stesso il consenso non è dogma: può cambiare davanti a prove nuove, come è accaduto con la deriva dei continenti o con i batteri dello stomaco. La scienza non è un insieme di verità, è un metodo per sbagliare sempre meno.")],
        "en": [("Step 6 — Consensus and doubt", "A single experiment is never enough: science trusts a result only when other labs have replicated it and the community has examined it. That is why a headline about 'a study shows that' means little until confirmed. At the same time, consensus is not dogma: it can change in the face of new evidence, as happened with continental drift or with stomach bacteria. Science is not a set of truths; it is a method for being wrong less and less.")],
    },
    "lez-energia-conservazione": {
        "it": [("Passo 6 — Perché allora l'energia finisce?", "Se l'energia si conserva, perché parliamo di crisi energetica? Perché non tutta l'energia è ugualmente utile. Quando bruci benzina, l'energia chimica diventa movimento e calore; il calore si disperde nell'aria e non puoi più raccoglierlo per far ripartire l'auto. La quantità totale non cambia, ma la qualità sì: l'energia degrada verso forme sempre meno utilizzabili. È il secondo principio della termodinamica, ed è il motivo per cui il moto perpetuo è impossibile e per cui servono sempre nuove fonti.")],
        "en": [("Step 6 — So why does energy run out?", "If energy is conserved, why do we talk about an energy crisis? Because not all energy is equally useful. When you burn petrol, chemical energy becomes motion and heat; the heat spreads into the air and you can no longer collect it to restart the car. The total amount does not change, but the quality does: energy degrades towards ever less usable forms. This is the second law of thermodynamics, and it is why perpetual motion is impossible and why new sources are always needed.")],
    },
    "v5-lez-stati-materia": {"it": [
        ("Passo 5 — Il quarto stato: il plasma", "Se continui a scaldare un gas, gli elettroni vengono strappati agli atomi e nasce il plasma, un gas di particelle cariche che conduce elettricità e risponde ai campi magnetici. È lo stato più comune dell'universo: le stelle sono plasma, così come i fulmini, le aurore e il gas dentro le lampade al neon e gli schermi al plasma. Nei reattori a fusione si cerca di contenere un plasma a cento milioni di gradi con campi magnetici, perché nessun materiale reggerebbe."),
        ("Passo 6 — Gli stati esotici", "All'estremo opposto, vicino allo zero assoluto, la materia fa cose strane. L'elio liquido diventa superfluido e risale le pareti del contenitore senza attrito; alcuni metalli diventano superconduttori e trasportano corrente senza perdite, il principio delle risonanze magnetiche negli ospedali. Nel 1995 sono stati creati i condensati di Bose-Einstein, in cui migliaia di atomi si comportano come un unico atomo gigante. Solido, liquido e gas sono solo i tre stati che incontriamo a temperatura di cucina."),
    ]},
    "v5-lez-reazione-chimica": {"it": [
        ("Passo 5 — Le reazioni nel tuo corpo", "Ogni secondo nel tuo corpo avvengono milioni di reazioni chimiche, e mostrano gli stessi segnali. Digerire è spezzare molecole grandi in piccole con l'aiuto di enzimi; respirare è bruciare glucosio con l'ossigeno, producendo anidride carbonica, acqua e calore, il motivo per cui hai 37 gradi. La ruggine e la respirazione sono la stessa reazione, l'ossidazione, a velocità diverse. Persino un pensiero è una cascata di reazioni tra neurotrasmettitori."),
        ("Passo 6 — Accelerare e rallentare", "Puoi controllare la velocità di una reazione con tre leve. La temperatura: il frigorifero rallenta le reazioni che fanno marcire il cibo, il forno accelera quelle che lo cuociono. La superficie: lo zucchero in polvere si scioglie prima della zolletta, la legna sminuzzata brucia prima del ceppo. I catalizzatori: sostanze che accelerano senza consumarsi, come gli enzimi nel corpo o il platino nella marmitta catalitica che trasforma i gas di scarico. La chimica è anche una questione di ritmo."),
    ]},
    "v5-lez-pressione": {"it": [
        ("Passo 5 — La pressione in alta quota", "Salendo in montagna l'aria sopra di te diminuisce e con lei la pressione. A 3.000 metri è circa il 70% di quella al mare: l'acqua bolle a 90 gradi e la pasta cuoce peggio, i sacchetti di patatine si gonfiano, le orecchie fanno male in ascensore e in aereo. Il corpo riceve meno ossigeno per ogni respiro, ed è per questo che si ha il fiato corto e che gli atleti si allenano in altura per produrre più globuli rossi."),
        ("Passo 6 — Sott'acqua e nello spazio", "Nell'acqua la pressione cresce di un'atmosfera ogni dieci metri di profondità. A trenta metri un subacqueo respira aria a quattro atmosfere e l'azoto si scioglie nel sangue: se risale troppo in fretta, forma bolle come una bottiglia di spumante stappata, la malattia da decompressione. Nello spazio accade l'opposto: pressione zero. Le tute spaziali sono palloni pressurizzati, e senza di esse l'acqua dei tessuti inizierebbe a evaporare. Viviamo in una fascia sottile di pressione, e ce ne accorgiamo appena la lasciamo."),
    ]},
    "v5-lez-calore-temperatura": {"it": [
        ("Passo 5 — Tre modi di viaggiare", "Il calore si sposta in tre modi. Per conduzione, attraverso il contatto: il manico della pentola si scalda. Per convezione, con il movimento di un fluido: l'aria calda del termosifone sale e circola nella stanza, e la stessa cosa accade nel mantello terrestre e nell'atmosfera. Per irraggiamento, senza bisogno di materia: il Sole ti scalda attraverso il vuoto, e il fuoco ti scalda il viso anche senza toccarlo. Il thermos combatte tutti e tre con il vuoto, il tappo e l'argento."),
        ("Passo 6 — Il freddo non esiste", "Ecco la conseguenza più sorprendente: il freddo non è una cosa, è l'assenza di calore. Quando tocchi il ghiaccio, non entra freddo nella tua mano: è il calore della mano che passa al ghiaccio. Il frigorifero non produce freddo, sposta calore dall'interno all'esterno, ed è per questo che la sua parte posteriore è tiepida. Il limite inferiore è lo zero assoluto, meno 273,15 gradi, dove le molecole hanno la minima energia possibile: non esiste nulla di più freddo, mentre verso l'alto la temperatura non ha limite."),
    ]},
    "v5-lez-acidi-basi": {"it": [
        ("Passo 5 — Il pH del corpo", "Il tuo corpo tiene il pH sotto stretto controllo. Il sangue è a 7,4 e una deviazione di pochi decimi è pericolosa: polmoni e reni lavorano di continuo per correggerla, eliminando anidride carbonica e acidi. Lo stomaco è a 1,5, la pelle a circa 5,5, leggermente acida, e per questo i saponi troppo alcalini la seccano. Le famose diete alcaline non cambiano il pH del sangue di un decimale: il corpo lo fa da solo, con qualunque cosa tu mangi."),
        ("Passo 6 — Esperimenti da fare a casa", "Il cavolo rosso è un indicatore naturale. Fai bollire qualche foglia, filtra il liquido viola e versane un po' in bicchieri diversi: con il limone diventa rosso, con il bicarbonato azzurro, con il sapone per i piatti verde. Hai costruito una scala del pH in cucina. Poi versa aceto sul bicarbonato e osserva la schiuma di anidride carbonica: è la stessa reazione che fa gonfiare le torte con il lievito chimico. La chimica degli acidi e delle basi è già tutta nella tua dispensa."),
    ]},
    "gravity-newton-einstein": {
        "it": [("Le onde gravitazionali", "Nel 2015, cent'anni dopo la previsione di Einstein, i rilevatori LIGO hanno sentito per la prima volta le onde gravitazionali: increspature dello spazio-tempo prodotte dalla fusione di due buchi neri a oltre un miliardo di anni luce. Il segnale ha allungato e accorciato bracci lunghi quattro chilometri di una frazione del diametro di un protone. Da allora se ne sono registrate centinaia, e l'astronomia ha un senso nuovo: oltre a vedere l'universo, possiamo ascoltarlo.")],
        "en": [("Gravitational waves", "In 2015, a hundred years after Einstein's prediction, the LIGO detectors heard gravitational waves for the first time: ripples in space-time produced by the merger of two black holes over a billion light-years away. The signal stretched and shortened four-kilometre arms by a fraction of a proton's diameter. Hundreds have been recorded since, and astronomy has a new sense: besides seeing the universe, we can now listen to it.")],
    },
    "how-dna-works": {
        "it": [("Il DNA come archivio e come prova", "Il DNA ha usi che vanno oltre la biologia. Nei tribunali una traccia di saliva o un capello identificano una persona con probabilità di errore di una su miliardi, e hanno scagionato centinaia di condannati innocenti. I test genealogici ricostruiscono migrazioni di migliaia di anni fa da un campione di saliva. E gli informatici lo usano come memoria: un grammo di DNA può contenere in teoria 200 milioni di gigabyte, e nel 2017 un film intero è stato scritto e riletto in molecole di DNA sintetico.")],
        "en": [("DNA as archive and evidence", "DNA has uses far beyond biology. In courts a trace of saliva or a hair identifies a person with an error probability of one in billions, and has exonerated hundreds of wrongly convicted people. Genealogy tests reconstruct migrations from thousands of years ago from a saliva sample. And computer scientists use it as storage: one gram of DNA can theoretically hold 200 million gigabytes, and in 2017 an entire film was written into and read back from synthetic DNA molecules.")],
    },
    "quantum-basics": {
        "it": [("Il gatto di Schrödinger", "L'esperimento mentale più famoso della fisica nacque per mostrare quanto la teoria fosse assurda. Schrödinger immaginò un gatto chiuso in una scatola con un atomo radioattivo che, decadendo, libera un veleno: finché nessuno apre la scatola, l'atomo è in sovrapposizione di decaduto e non decaduto, e il gatto dovrebbe essere vivo e morto insieme. Oggi sappiamo che gli oggetti grandi perdono la sovrapposizione quasi istantaneamente interagendo con l'ambiente, un fenomeno chiamato decoerenza, ed è proprio il nemico principale dei computer quantistici.")],
        "en": [("Schrödinger's cat", "The most famous thought experiment in physics was born to show how absurd the theory seemed. Schrödinger imagined a cat shut in a box with a radioactive atom which, by decaying, releases a poison: until someone opens the box, the atom is in a superposition of decayed and not decayed, and the cat should be alive and dead at once. Today we know that large objects lose superposition almost instantly by interacting with their environment, a phenomenon called decoherence, and it is precisely the main enemy of quantum computers.")],
    },
    "why-evolution": {
        "it": [("L'evoluzione in diretta", "L'evoluzione non è solo passato remoto: si osserva. I batteri diventano resistenti agli antibiotici in pochi anni, e in laboratorio si vedono nascere le mutazioni una generazione dopo l'altra. Le falene di Manchester si scurirono con la fuliggine industriale e tornarono chiare quando l'aria fu pulita. I fringuelli delle Galápagos cambiano la forma del becco dopo una siccità. E gli elefanti del Mozambico, dopo decenni di bracconaggio, nascono sempre più spesso senza zanne. Il meccanismo di Darwin lavora anche adesso.")],
        "en": [("Evolution live", "Evolution is not just the distant past: it can be observed. Bacteria become resistant to antibiotics within a few years, and in the lab mutations are seen appearing generation after generation. Manchester's moths darkened with industrial soot and turned pale again when the air was cleaned. Galápagos finches change beak shape after a drought. And Mozambique's elephants, after decades of poaching, are increasingly born without tusks. Darwin's mechanism is at work right now.")],
    },
    "why-water-strange": {
        "it": [("L'acqua oltre la Terra", "L'acqua è ovunque nell'universo, ma quasi mai liquida. Il ghiaccio ricopre le lune di Giove e Saturno, e sotto la crosta di Europa ed Encelado si nascondono oceani salati più grandi di tutti i nostri messi insieme, tenuti liquidi dal calore delle maree. Marte ne aveva fiumi e laghi tre miliardi di anni fa. Il vapore è stato trovato nell'atmosfera di pianeti di altre stelle. Cercare la vita significa cercare l'acqua liquida: è l'unico solvente in cui la chimica della vita, per quel che sappiamo, funziona.")],
        "en": [("Water beyond Earth", "Water is everywhere in the universe, but almost never liquid. Ice covers the moons of Jupiter and Saturn, and beneath the crusts of Europa and Enceladus hide salty oceans larger than all of ours combined, kept liquid by tidal heat. Mars had rivers and lakes three billion years ago. Vapour has been found in the atmospheres of planets around other stars. Searching for life means searching for liquid water: it is the only solvent in which the chemistry of life, as far as we know, works.")],
    },
    "photosynthesis-basics": {
        "it": [("La fotosintesi che nutre il mondo", "Tutto ciò che mangi è fotosintesi in seconda o terza mano: il pane viene dal grano, la carne da animali che hanno mangiato erba, il pesce da catene alimentari che partono dal fitoplancton. Anche il petrolio e il carbone sono foreste e alghe di milioni di anni fa. La quantità di energia solare fissata dalle piante ogni anno è circa dieci volte il consumo energetico dell'umanità. Quando guardi un campo di grano, stai guardando una centrale solare che funziona da tre miliardi di anni.")],
        "en": [("The photosynthesis that feeds the world", "Everything you eat is second- or third-hand photosynthesis: bread comes from wheat, meat from animals that ate grass, fish from food chains that start with phytoplankton. Even oil and coal are forests and algae from millions of years ago. The amount of solar energy fixed by plants each year is about ten times humanity's energy consumption. When you look at a wheat field, you are looking at a solar power plant that has been running for three billion years.")],
    },
    "why-magnets": {
        "it": [("I magneti che muovono il mondo", "Ogni motore elettrico, dal frullatore alla Tesla, funziona facendo girare un magnete dentro un campo magnetico prodotto dalla corrente; ogni generatore fa l'inverso, muovendo magneti per produrre corrente. I treni a levitazione magnetica galleggiano su campi che respingono; le risonanze magnetiche negli ospedali usano magneti superconduttori centomila volte più forti del campo terrestre per far vibrare gli atomi d'idrogeno del corpo. I magneti più potenti, al neodimio, sono nelle cuffie che hai in tasca.")],
        "en": [("Magnets that move the world", "Every electric motor, from a blender to a Tesla, works by spinning a magnet inside a magnetic field produced by current; every generator does the reverse, moving magnets to produce current. Maglev trains float on repelling fields; hospital MRI scanners use superconducting magnets a hundred thousand times stronger than Earth's field to make the body's hydrogen atoms vibrate. The most powerful magnets, made of neodymium, are in the earphones in your pocket.")],
    },
    "why-rain-falls": {
        "it": [("La pioggia artificiale", "Dagli anni Quaranta l'uomo prova a far piovere. L'inseminazione delle nubi consiste nel spargere dagli aerei particelle di ioduro d'argento che fanno da nuclei attorno a cui le gocce si formano prima. La Cina l'ha usata per garantire il cielo sereno alle Olimpiadi di Pechino nel 2008, gli Emirati Arabi la praticano centinaia di volte l'anno. Funziona? Gli studi mostrano aumenti modesti, del 10-15%, e solo quando le nubi sono già pronte a piovere: si può anticipare la pioggia, non crearla dal nulla.")],
        "en": [("Artificial rain", "Since the 1940s humans have tried to make it rain. Cloud seeding involves spreading silver iodide particles from aircraft to act as nuclei around which droplets form sooner. China used it to guarantee clear skies at the 2008 Beijing Olympics; the United Arab Emirates practise it hundreds of times a year. Does it work? Studies show modest increases, 10-15%, and only when clouds are already ready to rain: rain can be brought forward, not created from nothing.")],
    },
    "chemistry-basics": {
        "it": [("Da dove vengono gli atomi", "Gli atomi del tuo corpo hanno una storia lunga quanto l'universo. L'idrogeno si è formato nei primi minuti dopo il Big Bang. Il carbonio, l'ossigeno e l'azoto sono stati costruiti dentro le stelle per fusione nucleare e liberati quando quelle stelle sono esplose. Il ferro del tuo sangue viene da supernove, l'oro dei gioielli dalla collisione di stelle di neutroni. Come disse Carl Sagan, siamo fatti di polvere di stelle: non è una metafora, è chimica.")],
        "en": [("Where atoms come from", "The atoms in your body have a history as long as the universe. Hydrogen formed in the first minutes after the Big Bang. Carbon, oxygen and nitrogen were built inside stars by nuclear fusion and released when those stars exploded. The iron in your blood comes from supernovae, the gold in jewellery from colliding neutron stars. As Carl Sagan said, we are made of star stuff: not a metaphor, but chemistry.")],
    },
    "v4-ghiaccio-galleggia": {"it": [
        ("Il ghiaccio che rompe le rocce", "La stessa espansione che fa galleggiare il ghiaccio distrugge le montagne. L'acqua entra nelle fessure delle rocce, di notte gela e aumenta di volume del 9%, esercitando una pressione enorme che allarga la crepa; il giorno dopo si scioglie, entra più in profondità, e il ciclo ricomincia. È il crioclastismo, e in alta montagna è la principale forma di erosione: le pietraie ai piedi delle pareti sono il risultato di milioni di notti di gelo. Lo stesso processo spacca le tubature e i vasi d'inverno."),
        ("Il pattinaggio e le impronte sul ghiaccio", "Il ghiaccio è scivoloso per un motivo collegato. Sulla superficie esiste sempre uno strato sottilissimo di molecole d'acqua quasi liquide, perché le molecole del bordo non hanno vicini con cui legarsi da tutte le parti; la lama del pattino, con la pressione e l'attrito, lo rende più spesso e scivola su di esso. Sotto i 30 gradi sotto zero quello strato quasi sparisce e il ghiaccio diventa ruvido come cemento: nelle basi antartiche i pattinatori non pattinano."),
    ]},
    "v4-sale-neve": {"it": [
        ("Cosa usano dove fa più freddo", "Dove le temperature scendono regolarmente sotto i dieci gradi sotto zero il sale da cucina non basta. Si usa il cloruro di calcio, efficace fino a 30 gradi sotto zero e che sviluppa calore sciogliendosi, o il cloruro di magnesio. Nelle piste degli aeroporti si spruzzano invece glicoli e acetati, meno corrosivi per gli aerei. Alcune città sperimentano il succo di barbabietola mescolato alla salamoia, che aderisce meglio all'asfalto e riduce la quantità di sale necessaria."),
        ("Il gelato e il sale", "Lo stesso principio fa il gelato. Prima dei frigoriferi, il gelato si preparava mettendo la crema in un recipiente immerso in un secchio di ghiaccio e sale: la miscela scende fino a 20 gradi sotto zero, molto più del ghiaccio da solo, e congela la crema mentre la si mescola. È la ragione per cui la crema può gelare mentre il ghiaccio attorno si scioglie. Il trucco era noto già alla corte dei Medici nel Cinquecento, ed è ancora usato nelle gelatiere a manovella."),
    ]},
    "v4-microonde": {"it": [
        ("Nato per caso, dal radar", "Il microonde nacque nel 1945 da un incidente. Percy Spencer, ingegnere della Raytheon, lavorava sui magnetron per i radar militari quando notò che una barretta di cioccolato in tasca si era sciolta; provò con i chicchi di mais, che scoppiarono, e con un uovo, che esplose in faccia a un collega. Il primo forno commerciale del 1947 era alto quasi due metri, pesava 340 chili e costava quanto un'auto. Il modello domestico arrivò vent'anni dopo."),
        ("Cosa non metterci dentro", "Alcune regole hanno una spiegazione fisica precisa. Il metallo riflette le microonde e le punte concentrano le cariche, producendo scintille: niente forchette né bordi dorati. L'uovo intero e i cibi con la buccia esplodono perché il vapore non può uscire: bucali prima. Un bicchiere d'acqua può surriscaldarsi oltre i 100 gradi senza bollire e poi eruttare quando lo tocchi: metti dentro un cucchiaino di legno. E l'uva tagliata a metà produce plasma: spettacolare, ma da non fare."),
    ]},
    "v5-arcobaleno-arco": {"it": [
        ("L'arcobaleno doppio e quello lunare", "Sopra l'arco principale compare a volte un secondo arco più debole, con i colori invertiti: è la luce che ha rimbalzato due volte dentro le gocce, e tra i due archi il cielo appare più scuro, la banda di Alessandro, descritta già nel II secolo. Con la luna piena e una pioggia notturna nasce l'arcobaleno lunare, così debole che l'occhio lo vede grigio ma la fotocamera lo mostra colorato. Le cascate e gli spruzzi del mare producono arcobaleni a qualsiasi ora, purché il sole sia dietro di te."),
        ("Quanti colori sono?", "I sette colori di Newton sono una convenzione. Lo spettro è continuo, senza confini tra un colore e l'altro: Newton scelse sette per analogia con le note musicali, e aggiunse l'indaco per arrivare a quel numero. Molte lingue e culture ne contano cinque o sei, e nell'antica Grecia il blu non aveva quasi nome. Il tuo occhio distingue nell'arcobaleno forse un centinaio di sfumature; i colori che nomini dipendono dalla lingua che parli, non dalla fisica della luce."),
    ]},
    "v5-metallo-freddo": {"it": [
        ("Il paradosso della sauna", "In una sauna a 90 gradi l'aria non ti brucia, ma la panca di metallo sì e per questo le panche sono di legno: la stessa conducibilità che fa sembrare il metallo freddo d'inverno lo fa sembrare rovente d'estate. È il motivo per cui puoi infilare per un istante la mano in un forno a 200 gradi senza danni ma non puoi toccare la teglia, e per cui una maniglia d'auto al sole scotta mentre la carrozzeria di plastica è solo tiepida. Il metallo non è più caldo: passa calore più in fretta."),
        ("I materiali che ingannano di più", "Alcuni materiali ingannano il tatto in modo estremo. L'aerogel, un solido fatto al 99% di aria, si può tenere in mano mentre una fiamma lo scalda dall'altro lato. Il grafene conduce il calore dieci volte meglio del rame. Il diamante, contro l'intuito, è uno dei migliori conduttori termici che esistano, ed è per questo che al tatto sembra gelido: i gioiellieri lo usavano per distinguerlo dal vetro prima degli strumenti moderni. Un diamante falso si scalda in mano; uno vero resta freddo."),
    ]},
    "v5-candela": {"it": [
        ("La candela nello spazio", "Sulla Stazione Spaziale una candela brucia in modo completamente diverso. Senza gravità l'aria calda non sale, quindi non c'è convezione: la fiamma è una sfera azzurra, piccola e debole, che non tremola e consuma l'ossigeno attorno a sé solo per diffusione. Brucia più a lungo e più fredda, e produce quasi nessuna fuliggine. Gli esperimenti sulla combustione in microgravità servono a progettare motori più puliti e a capire come spegnere un incendio a bordo."),
        ("Faraday e la storia chimica di una candela", "Nel 1848 Michael Faraday tenne a Londra una serie di lezioni per ragazzi intitolata La storia chimica di una candela, ancora oggi considerata una delle migliori introduzioni alla scienza mai scritte. Mostrò che il vapore d'acqua si condensa su un cucchiaio freddo sopra la fiamma, che l'anidride carbonica spegne un fiammifero, che una candela e una persona respirano lo stesso ossigeno. Con un oggetto da pochi centesimi spiegò combustione, stati della materia e chimica dell'aria: la stessa candela che hai sul tavolo."),
    ]},
    "v5-suono-acqua": {"it": [
        ("Nei solidi ancora più veloce", "Se il suono corre nell'acqua a 1.500 metri al secondo, nei solidi va ancora più forte: circa 5.000 nel legno e nell'acciaio, oltre 12.000 nel diamante. Per questo i nativi americani appoggiavano l'orecchio alle rotaie per sentire il treno in arrivo molto prima del rumore nell'aria, e per questo i medici usano lo stetoscopio e i geologi ascoltano le onde sismiche: la loro velocità nelle diverse rocce racconta cosa c'è sotto i nostri piedi fino al nucleo."),
        ("Il canale che porta i suoni intorno al mondo", "A circa mille metri di profondità esiste uno strato in cui il suono viaggia più lentamente che sopra e sotto, e le onde vi restano intrappolate come la luce in una fibra ottica: è il canale SOFAR. Le balene lo usano per farsi sentire attraverso interi oceani, e durante la Guerra fredda le marine ci piazzarono microfoni per seguire i sottomarini. Nel 1960 un'esplosione al largo dell'Australia fu registrata alle Bermuda, dall'altra parte del pianeta, dopo tre ore e mezzo di viaggio."),
    ]},
    "v5-bolle-sapone": {"it": [
        ("Gli stessi colori in una macchia d'olio", "Il fenomeno si chiama interferenza a film sottile e lo vedi ovunque ci sia uno strato sottilissimo. La macchia d'olio sull'asfalto bagnato, l'iridescenza di una conchiglia di madreperla, le ali di una libellula, i riflessi colorati di un CD, la pellicola di ossido su un pezzo di acciaio scaldato. In nessuno di questi casi c'è un pigmento: i colori nascono dalla geometria e scompaiono se cambi angolo. Le piume del pavone e le ali delle farfalle morpho usano una versione più elaborata dello stesso trucco."),
        ("Perché le bolle sono sferiche", "La bolla è rotonda per un motivo di risparmio. La pellicola di sapone è tesa e cerca di ridurre la propria superficie al minimo; la sfera è la forma che racchiude un dato volume d'aria con la superficie più piccola possibile. Per questo anche una bolla soffiata da un anello quadrato diventa tonda in un istante. Quando due bolle si toccano formano una parete piatta comune, e tre bolle si incontrano sempre con angoli di 120 gradi: le stesse geometrie delle celle degli alveari."),
    ]},
}
