# Capitoli aggiuntivi — TECNOLOGIA (scritti a mano, stesso tono degli altri)
EXTRA = {
    "how-gps-works": {
        "it": [("Perché in città sbaglia", "Il GPS funziona alla perfezione in campo aperto, ma tra i palazzi il segnale rimbalza sulle facciate di vetro e cemento prima di arrivare al telefono: il ricevitore misura un percorso più lungo di quello reale e ti piazza sul marciapiede sbagliato. Per questo le mappe combinano il GPS con altri indizi: le antenne Wi-Fi conosciute nei dintorni, le celle telefoniche, l'accelerometro e la bussola. In una galleria, dove il cielo sparisce del tutto, il telefono tira a indovinare in base alla velocità e alla direzione dell'ultimo punto noto.")],
        "en": [("Why it fails in cities", "GPS works perfectly in open country, but between buildings the signal bounces off glass and concrete façades before reaching your phone: the receiver measures a path longer than the real one and drops you on the wrong pavement. That is why maps combine GPS with other clues: known Wi-Fi networks nearby, phone masts, the accelerometer and the compass. In a tunnel, where the sky disappears entirely, the phone makes an educated guess from the speed and direction of the last known fix.")],
    },
    "how-batteries-work": {
        "it": [("Perché invecchia", "Ogni ciclo di carica e scarica lascia una traccia. Gli ioni di litio, andando avanti e indietro tra gli elettrodi, depositano una pellicola microscopica che con il tempo si ispessisce e ruba spazio alla reazione utile; qualche ione resta intrappolato e non torna più in gioco. Dopo circa 500 cicli completi una batteria di telefono conserva l'80% della capacità originale. Il calore accelera tutto: una batteria lasciata al sole a 40 gradi invecchia il doppio di una a temperatura ambiente. Non è un difetto di fabbrica: è chimica.")],
        "en": [("Why it ages", "Every charge and discharge cycle leaves a trace. Lithium ions, shuttling back and forth between the electrodes, deposit a microscopic film that thickens over time and steals room from the useful reaction; some ions get trapped and never rejoin the game. After about 500 full cycles a phone battery keeps 80% of its original capacity. Heat speeds everything up: a battery left in the sun at 40 °C ages twice as fast as one at room temperature. It is not a manufacturing flaw: it is chemistry.")],
    },
    "how-internet-works": {
        "it": [("Chi lo possiede", "Nessuno, e insieme moltissimi. I cavi appartengono a consorzi di operatori e, sempre più spesso, a Google, Meta, Amazon e Microsoft, che ne posano di propri. I grandi snodi dove le reti si scambiano il traffico sono edifici anonimi alla periferia delle città. Le regole comuni, i protocolli, sono scritte da gruppi di ingegneri volontari e chiunque può leggerle. È questa assenza di un padrone che rende internet così resistente: se un cavo si rompe, e succede circa cento volte all'anno per ancore e terremoti, i pacchetti prendono un'altra strada in pochi millisecondi.")],
        "en": [("Who owns it", "Nobody, and at the same time a great many. The cables belong to consortia of carriers and, increasingly, to Google, Meta, Amazon and Microsoft, which lay their own. The big exchange points where networks swap traffic are anonymous buildings on city outskirts. The shared rules, the protocols, are written by groups of volunteer engineers and anyone can read them. This lack of an owner is what makes the internet so resilient: when a cable breaks, and it happens about a hundred times a year because of anchors and earthquakes, packets take another route within milliseconds.")],
    },
    "how-encryption-works": {
        "it": [("Il lucchetto che vedi ogni giorno", "La stessa idea protegge ogni sito con il lucchetto accanto all'indirizzo. Quando apri la pagina della banca, il tuo browser e il server si scambiano chiavi pubbliche e in pochi millisecondi costruiscono una chiave segreta condivisa che nessuno lungo il percorso può ricostruire. Da quel momento tutto ciò che digiti viaggia cifrato. È il motivo per cui i browser avvertono quando un sito è ancora in chiaro: chiunque sulla stessa rete Wi-Fi, in un bar o in aeroporto, potrebbe leggere quello che scrivi come su una cartolina.")],
        "en": [("The padlock you see every day", "The same idea protects every website with the padlock next to its address. When you open your bank's page, your browser and the server exchange public keys and within milliseconds build a shared secret key that nobody along the route can reconstruct. From then on everything you type travels encrypted. That is why browsers warn you when a site is still unencrypted: anyone on the same Wi-Fi network, in a café or at an airport, could read what you write as if it were a postcard.")],
    },
    "how-ai-learns": {
        "it": [("Perché a volte inventa", "Un modello linguistico non consulta un archivio di fatti: genera la parola successiva più probabile date le precedenti. Se gli chiedi una citazione o una data rara, produce qualcosa che suona giusto perché ha la forma giusta, anche se non esiste. Sono le cosiddette allucinazioni. Non è un bug che si corregge con una riga di codice, ma una conseguenza del metodo: il modello è stato premiato per essere convincente, non per essere vero. Per questo le versioni più recenti vengono collegate a motori di ricerca e chiedono di verificare le fonti.")],
        "en": [("Why it sometimes makes things up", "A language model does not consult a store of facts: it generates the most probable next word given the previous ones. Ask it for a quote or an obscure date and it produces something that sounds right because it has the right shape, even if it does not exist. These are the so-called hallucinations. It is not a bug fixed with a line of code but a consequence of the method: the model was rewarded for being convincing, not for being true. That is why newer versions are connected to search engines and ask you to check the sources.")],
    },
    "why-smartphones-fast": {
        "it": [("Il collo di bottiglia non è più il chip", "Oggi la velocità di un telefono dipende sempre meno dal processore e sempre più da tutto ciò che gli sta intorno: la memoria che deve rifornirlo di dati abbastanza in fretta, il software che deve sfruttarne i core in parallelo, la batteria e il calore che lo costringono a rallentare dopo pochi minuti di sforzo. Un chip può eseguire un calcolo in un miliardesimo di secondo e poi aspettare cento volte tanto che arrivi il dato successivo. Per questo i produttori parlano meno di gigahertz e più di efficienza: fare la stessa cosa consumando un decimo.")],
        "en": [("The bottleneck is no longer the chip", "Today a phone's speed depends less and less on the processor and more and more on everything around it: the memory that must feed it data fast enough, the software that must use its cores in parallel, the battery and the heat that force it to slow down after a few minutes of effort. A chip can perform a calculation in a billionth of a second and then wait a hundred times longer for the next piece of data to arrive. That is why manufacturers talk less about gigahertz and more about efficiency: doing the same thing using a tenth of the power.")],
    },
    "what-is-blockchain": {
        "it": [("Oltre le criptovalute", "Il registro immodificabile serve anche dove non girano soldi. Alcune catene alimentari lo usano per tracciare un lotto di caffè dalla piantagione allo scaffale, così una contaminazione si isola in secondi invece che in giorni. Gli atti notarili e i diplomi universitari possono essere registrati per renderli verificabili da chiunque, senza telefonare all'università. Il principio è sempre lo stesso: quando molte parti non si fidano l'una dell'altra ma devono condividere una storia comune, una blockchain può sostituire l'arbitro. Quando invece un arbitro affidabile c'è già, un database normale è più semplice e più veloce.")],
        "en": [("Beyond cryptocurrencies", "The tamper-proof ledger is also useful where no money changes hands. Some food supply chains use it to track a batch of coffee from plantation to shelf, so a contamination is isolated in seconds rather than days. Notarial deeds and university degrees can be recorded to make them verifiable by anyone, without phoning the university. The principle is always the same: when many parties do not trust each other but must share a common history, a blockchain can replace the referee. When a trustworthy referee already exists, an ordinary database is simpler and faster.")],
    },
    "how-3d-printing": {
        "it": [("Il ponte, la casa, la Luna", "Le stampanti più grandi non stanno su un tavolo: sono bracci robotici che depositano cemento. Ad Amsterdam un ponte pedonale in acciaio è stato stampato interamente da robot; in Messico e in Texas quartieri di case sono stati costruiti in pochi giorni con muri estrusi strato dopo strato, che poi ricevono tetto e finestre tradizionali. La NASA sperimenta stampanti che userebbero la polvere lunare come materiale per costruire ripari senza portare mattoni dalla Terra. L'idea è sempre la stessa del piccolo oggetto in plastica: aggiungere, non togliere.")],
        "en": [("The bridge, the house, the Moon", "The largest printers do not sit on a desk: they are robotic arms that lay down concrete. In Amsterdam a steel footbridge was printed entirely by robots; in Mexico and Texas whole neighbourhoods of houses were built in days with walls extruded layer by layer, then finished with conventional roofs and windows. NASA is testing printers that would use lunar dust as raw material to build shelters without shipping bricks from Earth. The idea is the same as the little plastic object: add, don't subtract.")],
    },
    "v4-touchscreen": {"it": [
        ("Dieci dita insieme", "Il vero salto arrivò quando gli schermi impararono a seguire più dita contemporaneamente. La griglia non misura un solo punto: legge ogni incrocio tra righe e colonne, centinaia di volte al secondo, e costruisce una mappa di dove la carica è disturbata. Così distingue due dita che si allontanano per ingrandire una foto da una sola che scorre. Il pizzico per lo zoom, presentato nel 2007, sembrò magia proprio perché i vecchi schermi resistivi potevano registrare un solo tocco alla volta."),
        ("Gocce d'acqua e tocchi fantasma", "Se hai mai visto il telefono impazzire sotto la pioggia, ora sai perché: anche l'acqua conduce, e ogni goccia è un piccolo dito che ruba carica. I controller moderni cercano di riconoscere la forma e la stabilità di una goccia per ignorarla, ma non sempre ci riescono. Lo stesso vale per il palmo che sfiora lo schermo mentre scrivi: il software prova a capire quale contatto sia intenzionale in base a dimensione, pressione stimata e movimento. Il touchscreen non sente il dito: interpreta indizi elettrici, e come ogni interprete a volte sbaglia."),
    ]},
    "v4-gps": {"it": [
        ("Due effetti in direzioni opposte", "La storia completa ha un colpo di scena. La velocità dei satelliti rallenta i loro orologi di circa 7 microsecondi al giorno, ma la gravità più debole a 20.000 chilometri li fa correre più veloci di 45 microsecondi. Il risultato netto è quell'anticipo di 38 microsecondi. Gli ingegneri, prima del lancio, regolano di proposito gli orologi a bordo su una frequenza leggermente sbagliata, così che una volta in orbita risultino esatti. Einstein non è un dettaglio da manuale: è una vite da girare nel laboratorio."),
        ("La prova che convinse tutti", "Quando il primo satellite sperimentale fu lanciato nel 1977, alcuni tecnici erano ancora scettici sulla relatività e chiesero di installare un interruttore per attivare o spegnere la correzione. Il satellite volò per venti giorni con la correzione spenta: l'orologio accumulò esattamente lo scarto previsto da Einstein. Da allora l'interruttore è rimasto acceso. Ogni volta che il navigatore ti dice in quale corsia stai, sta anche confermando una teoria del 1915."),
    ]},
    "v4-cavi-sottomarini": {"it": [
        ("Squali, ancore e terremoti", "Per anni si è raccontato che gli squali mordessero i cavi attratti dal campo elettrico: qualche morso c'è stato, ma è un'inezia. Oltre due terzi dei guasti sono causati da ancore e reti a strascico che trascinano il cavo sui fondali poco profondi; il resto da frane sottomarine e terremoti, come quello che nel 2006 tagliò nove cavi al largo di Taiwan. Per questo i cavi vicino alla costa sono corazzati e interrati, e i percorsi evitano le zone di pesca intensa."),
        ("Chi li ripara", "Quando un cavo si rompe, una nave specializzata parte da uno dei porti di stazionamento sparsi nel mondo. Localizza il guasto misurando quanto tempo impiega un impulso di luce a tornare indietro, poi cala un rampino che aggancia il cavo a chilometri di profondità e lo porta in superficie. A bordo i tecnici saldano le fibre, sottili come capelli, sotto un microscopio, con la nave che ondeggia. Una riparazione dura da pochi giorni a settimane. Nel frattempo il traffico viaggia sugli altri cavi e tu non te ne accorgi."),
    ]},
    "v4-lez-riconoscere-phishing": {"it": [
        ("Passo 5 — Anche su WhatsApp e al telefono", "Le stesse regole valgono fuori dall'email. Il messaggio 'Ciao mamma, ho cambiato numero, mi presti dei soldi?' e la chiamata dal 'servizio antifrode della banca' che ti chiede di trasferire i soldi su un conto sicuro sono phishing con un altro vestito. Il trucco è sempre lo stesso: urgenza, un canale che non puoi verificare, una richiesta di dati o denaro. Chiudi la conversazione e richiama tu il numero ufficiale stampato sulla carta o sul sito: chi è onesto non si offende."),
        ("Passo 6 — Cosa fare se hai cliccato", "Capita anche agli esperti. Se hai inserito una password, cambiala subito da un dispositivo pulito e attiva la verifica in due passaggi. Se hai inserito dati della carta, chiama la banca e falla bloccare: i primi minuti contano. Segnala il messaggio come phishing nel tuo programma di posta, così aiuta gli altri. E non vergognarti: le truffe funzionano perché sono progettate da professionisti. Il vero errore è restare in silenzio."),
    ]},
    "v4-lez-cloud": {"it": [
        ("Passo 5 — Il costo nascosto: energia", "Un data center consuma quanto una piccola città, soprattutto per raffreddare i server che lavorano giorno e notte. Le grandi aziende li costruiscono in Scandinavia o in Irlanda per sfruttare il freddo e l'energia rinnovabile, e sperimentano perfino server sommersi in mare. Le tue foto nel cloud, quindi, hanno un peso fisico: pochi grammi di CO₂ ciascuna, che moltiplicati per miliardi di utenti diventano significativi. Cancellare i doppioni non è solo ordine: è un piccolo gesto ecologico."),
        ("Passo 6 — Usarlo bene", "Tre abitudini rendono il cloud un alleato. Prima: attiva la sincronizzazione automatica, così il backup avviene senza pensarci. Seconda: controlla una volta all'anno quali app hanno accesso al tuo account e revoca quelle che non usi più. Terza: ricorda che 'sincronizzato' non significa 'al sicuro'. Se cancelli una foto sul telefono, sparisce anche nel cloud, di solito dopo trenta giorni nel cestino. Per un vero archivio serve una copia in più, su un disco che sta a casa tua."),
    ]},
    "v4-lez-batteria": {"it": [
        ("Passo 5 — La ricarica rapida fa male?", "Meno di quanto si pensi. I caricatori veloci lavorano insieme al telefono: spingono forte solo nella prima metà, quando la batteria accetta energia senza scaldarsi troppo, poi rallentano. Il danno vero lo fa la combinazione di ricarica veloce e caldo: caricare in auto sotto il parabrezza d'estate o giocando con lo schermo al massimo. Se il telefono è tiepido, va bene; se scotta, staccalo. E usa caricatori certificati: quelli scadenti non dialogano con il telefono e possono superare i limiti di sicurezza."),
        ("Passo 6 — La checklist finale", "Riassumendo in un gesto quotidiano: metti in carica quando sei intorno al 20-30%, stacca quando puoi verso l'80-90% oppure attiva la ricarica ottimizzata che lo fa da sola di notte. Tieni il telefono lontano da fonti di calore mentre carica. Non lasciarlo scarico nel cassetto per mesi: sotto una certa soglia la batteria può non riaccendersi più; se devi riporlo, lascialo a metà carica. Con queste abitudini la batteria può durare quattro o cinque anni invece di due."),
    ]},
    "v5-qr-rovinato": {"it": [
        ("Quanto può mancare", "Chi crea un codice QR sceglie il livello di protezione: L recupera fino al 7% dei dati, M il 15%, Q il 25%, H il 30%. Più protezione significa più quadratini per la stessa informazione, quindi un codice più denso. I menu dei ristoranti e i biglietti usano spesso il livello M; i codici stampati su imballaggi esposti alle intemperie salgono a H. Un QR di livello H può perdere quasi un terzo della superficie e restare perfettamente leggibile."),
        ("Nato in una fabbrica di ricambi", "Il codice QR fu inventato nel 1994 da Masahiro Hara, ingegnere della Denso Wave, fornitore Toyota, per tracciare i pezzi nelle catene di montaggio: i codici a barre tradizionali contenevano troppo poche informazioni e andavano letti da un'angolazione precisa. Il motivo dei tre quadrati è ispirato al gioco del Go. L'azienda decise di non far pagare la licenza del brevetto, e questa scelta, più della tecnica, ha fatto sì che oggi il QR sia ovunque, dal pagamento al bar al biglietto del treno."),
    ]},
    "v5-streaming-sgrana": {"it": [
        ("Cosa puoi fare tu", "Se il problema è frequente, il colpevole di solito è in casa. Il Wi-Fi a 2,4 gigahertz attraversa meglio i muri ma è affollato e lento: se il router lo permette, usa la rete a 5 gigahertz stando nella stessa stanza, o un cavo per la TV. Chiudi i download in corso su altri dispositivi e scollega quelli che non usi. E controlla le impostazioni dell'app: alcune fissano la qualità su 'automatica', altre permettono di forzare la risoluzione alta, accettando qualche pausa in più."),
        ("Perché il 4K non pesa quanto pensi", "Un film in 4K su una piattaforma di streaming occupa meno banda di quanto il numero di pixel farebbe pensare: circa 15-25 megabit al secondo, un decimo di un disco Blu-ray. Il merito è dei nuovi formati di compressione, che descrivono un'immagine ad alta risoluzione quasi come un pittore descrive una scena: forme, gradienti e movimenti, non pixel uno per uno. Ogni generazione di codec dimezza il peso a parità di qualità, ma richiede chip più potenti per decodificarlo: per questo una TV vecchia a volte non riproduce i formati più recenti."),
    ]},
    "v5-contactless": {"it": [
        ("Il telefono fa lo stesso, ma meglio", "Quando paghi con lo smartphone, il chip della carta è virtuale: il telefono genera un numero di carta sostitutivo, diverso da quello stampato sulla tua, e lo usa per la transazione. Se un negozio venisse violato, i ladri troverebbero solo quel numero fittizio, inutile altrove. In più il pagamento richiede impronta o volto, quindi un telefono rubato non paga da solo. È il motivo per cui i pagamenti con il telefono, che sembrano più fragili, sono in realtà più sicuri della carta fisica."),
        ("La paura del portafoglio scansionato", "Le custodie schermate anti-RFID vendono bene, ma il rischio che proteggono è quasi teorico. Per leggere una carta servono pochi centimetri, un lettore registrato presso una banca e ogni transazione lascia una traccia che porta al truffatore. E quello che si otterrebbe è un codice monouso, valido per un solo pagamento a piccolo importo. Nella pratica i furti avvengono altrove: nei siti compromessi e nel phishing. Il contactless in sé è uno dei pezzi più sicuri dell'intero sistema."),
    ]},
    "v5-cuffie-rumore": {"it": [
        ("Perché senti pressione nelle orecchie", "Molti, appena attivano la cancellazione, avvertono una sensazione simile a quella dell'aereo in discesa. Non c'è alcuna variazione di pressione: il cervello, abituato a un rumore di fondo costante, interpreta il silenzio improvviso alle basse frequenze come un'anomalia e lo traduce in una sensazione fisica. Di solito passa in pochi minuti d'uso. Le cuffie migliori attenuano il fenomeno lasciando passare una minima quantità di suono naturale."),
        ("Il rumore che fa bene sentire", "La cancellazione attiva ha un rovescio: in strada isola dai clacson, dalle biciclette e dalle voci che dovrebbero avvisarti. Per questo le cuffie moderne includono una modalità 'trasparenza' che fa il contrario: cattura i suoni esterni e li riproduce nell'orecchio, come se non le portassi. Alcune passano automaticamente da una modalità all'altra quando rilevano che stai parlando. Il silenzio artificiale è una conquista, ma va acceso e spento con giudizio."),
    ]},
    "v5-foto-notturne": {"it": [
        ("Il cavalletto lo fai tu", "L'allineamento è la parte più difficile. In due o tre secondi la mano si muove di qualche millimetro e ogni scatto della raffica è leggermente spostato. Il telefono usa il giroscopio per stimare il movimento e poi confronta le immagini pixel per pixel, sovrapponendo i punti in comune e scartando le zone dove qualcosa si è mosso, come una persona che passa. È lo stesso principio con cui gli astronomi sommano centinaia di foto di una galassia debolissima: molta luce accumulata, poco rumore."),
        ("Quando la foto è troppo bella", "La modalità notte a volte mente. Un cielo che a occhio nudo era nero diventa blu profondo con le stelle, un vicolo buio sembra illuminato. È il risultato di scelte del software: alza le ombre, scalda i colori, aggiunge dettagli che l'algoritmo ritiene plausibili. Alcuni telefoni sostituiscono perfino la Luna con un'immagine più nitida imparata durante l'addestramento. La foto è tecnicamente reale, ma non è quello che hai visto. Per fedeltà, cerca l'opzione che disattiva l'elaborazione o scatta in formato RAW."),
    ]},
    "v5-lez-bluetooth-wifi": {"it": [
        ("Passo 5 — Perché a volte si disturbano", "Bluetooth, Wi-Fi e forno a microonde condividono la stessa banda a 2,4 gigahertz, ed è per questo che le cuffie a volte gracchiano vicino al router o mentre scaldi il pranzo. Il Bluetooth si difende saltando frequenza 1.600 volte al secondo, così un disturbo colpisce solo un frammento di dati; il Wi-Fi cambia canale o passa ai 5 gigahertz. Se la connessione balla, allontana il router dal microonde e dagli altri router dei vicini, o cambia canale dalle impostazioni."),
        ("Passo 6 — Quale usare per cosa", "Una regola pratica. Cuffie, smartwatch, tastiere, sensori: Bluetooth, perché consuma pochissimo e la quantità di dati è piccola. Video, backup, aggiornamenti pesanti: Wi-Fi, o anche un cavo. In movimento, o quando il Wi-Fi pubblico non ti convince: rete cellulare, che è cifrata dall'operatore ed è più sicura di una rete aperta in un bar. E quando il telefono ha poca batteria, spegni ciò che non usi: ogni radio accesa è una piccola bocca che beve."),
    ]},
    "v5-lez-due-fattori": {"it": [
        ("Passo 5 — Le passkey, il passo successivo", "Il futuro elimina la password del tutto. Una passkey è una coppia di chiavi crittografiche: quella privata resta nel tuo telefono, protetta da impronta o volto, quella pubblica va al sito. Per entrare, il sito ti manda una sfida e il telefono la firma. Niente da ricordare, niente da digitare, e soprattutto niente da rubare con il phishing, perché la passkey funziona solo sul sito per cui è stata creata. Google, Apple, Microsoft e molte banche la offrono già: quando la vedi proposta, accettala."),
        ("Passo 6 — Cambiare telefono senza panico", "Il momento critico è il nuovo telefono. Prima di resettare il vecchio, apri l'app di autenticazione e usa la funzione di trasferimento o esportazione; molte app oggi salvano i codici nel cloud, cifrati, e li ripristinano con il tuo account. Verifica che ogni servizio funzioni sul nuovo dispositivo prima di cancellare il vecchio. Se hai una chiavetta fisica, comprane sempre due e registrale entrambe: una in tasca, una in un cassetto sicuro. La sicurezza che ti chiude fuori non è sicurezza."),
    ]},
    "v5-lez-app-server": {"it": [
        ("Passo 5 — Perché a volte è istantaneo", "Non tutto viaggia fino al server. Le app tengono una copia locale dei dati più recenti, la cache, così quando riapri la chat vedi subito i vecchi messaggi mentre in background arrivano i nuovi. Alcune azioni vengono mostrate come già riuscite prima che il server confermi: il 'mi piace' si colora all'istante e, se la rete fallisce, torna grigio. Si chiama aggiornamento ottimistico: una piccola bugia a fin di bene che rende l'app fluida anche con la connessione che va e viene."),
        ("Passo 6 — Cosa sa il server di te", "Ogni richiesta porta con sé chi sei: un gettone di accesso ottenuto al login, l'ora, il tipo di dispositivo, spesso la posizione approssimativa. Il server registra tutto in file di log per sicurezza e statistica. Per questo le impostazioni privacy contano: non riguardano solo ciò che vedi, ma ciò che inviato in automatico a ogni tocco. Un buon esercizio: apri le impostazioni di un'app che usi ogni giorno e leggi quali permessi ha davvero. Spesso il microfono e la posizione non le servono affatto."),
    ]},
    "v5-lez-motore-ricerca": {"it": [
        ("Passo 5 — Cercare meglio", "Poche mosse cambiano i risultati. Le virgolette cercano la frase esatta: \"effetto serra spiegato\" trova solo pagine con quelle parole in quell'ordine. Il segno meno esclude: giaguaro -auto toglie la casa automobilistica. site:nome.it limita a un sito. Un'altra abitudine utile: leggi l'indirizzo sotto il titolo prima di cliccare, e scorri oltre i primi tre risultati, che sono i più ottimizzati per comparire, non necessariamente i migliori."),
        ("Passo 6 — Le risposte generate dall'AI", "I motori ora aggiungono in alto un riassunto scritto da un'intelligenza artificiale che legge le prime pagine e le sintetizza. Comodo, ma con due rischi: il riassunto può mescolare fonti affidabili e non, e può inventare dettagli che suonano plausibili. Usalo come mappa, non come risposta finale: apri almeno una delle fonti citate, soprattutto per salute, denaro e notizie. Il motore di ricerca resta uno strumento per trovare chi sa, non chi sa."),
    ]},
    "v5-lez-backup": {"it": [
        ("Passo 5 — Il ransomware e la copia scollegata", "Esiste un attacco che rende inutili i backup collegati: il ransomware cifra tutti i file che raggiunge, compresi quelli sul disco esterno attaccato al computer e sulle cartelle sincronizzate col cloud. Per questo almeno una copia deve essere scollegata: un disco che colleghi una volta al mese, aggiorni e riponi. Molti servizi cloud offrono la cronologia delle versioni, che permette di tornare ai file prima della cifratura: controlla che sia attiva."),
        ("Passo 6 — Un'ora, una volta", "Fai il piano oggi, in un'ora. Attiva il backup automatico del telefono e la sincronizzazione delle foto. Compra un disco esterno e imposta il backup del computer con lo strumento incluso nel sistema. Scrivi su un foglio dove stanno le tre copie e quando le controlli: ogni tre mesi apri un file a caso dal backup e verifica che si legga. Segna la data in calendario. È l'ora meglio spesa dell'anno: quando il telefono cadrà, e cadrà, sarà solo un fastidio."),
    ]},
    "lez-password-sicura": {
        "it": [("Passo 6 — Il gestore di password, senza paura", "Ricordare venti frasi diverse è impossibile: per questo esistono i gestori di password. Ne ricordi una sola, molto lunga, e il programma genera e conserva tutte le altre, cifrate, compilandole al posto tuo su siti e app. Il timore che 'se bucano il gestore perdo tutto' è comprensibile, ma i gestori seri non conoscono la tua chiave principale e i dati restano illeggibili anche in caso di furto. Il rischio reale, oggi, è il contrario: riutilizzare la stessa password ovunque. Scegli un gestore, importa le password che hai e sostituisci per prime quelle di email e banca.")],
        "en": [("Step 6 — The password manager, without fear", "Remembering twenty different phrases is impossible: that is what password managers are for. You remember just one, very long, and the program generates and stores all the others, encrypted, filling them in for you on sites and apps. The worry that 'if the manager is hacked I lose everything' is understandable, but serious managers never know your master key and the data stays unreadable even if stolen. The real risk today is the opposite: reusing the same password everywhere. Pick a manager, import the passwords you have and replace those for email and banking first.")],
    },
    "lez-algoritmo": {
        "it": [("Passo 6 — Gli algoritmi che ti scelgono", "Ora che sai cos'è un algoritmo, riconoscerai quelli che ti circondano. Il feed dei social è un algoritmo che ordina i post in base a quanto ti hanno trattenuto quelli simili; il navigatore ne esegue uno che confronta migliaia di percorsi in un secondo; il prezzo di un volo cambia per un algoritmo che stima quanto sei disposto a pagare. Nessuno di questi è magico e nessuno è neutrale: ognuno ottimizza un obiettivo deciso da qualcuno. La domanda utile davanti a un risultato automatico è sempre la stessa: quale problema stava risolvendo, e per chi?")],
        "en": [("Step 6 — The algorithms that choose you", "Now that you know what an algorithm is, you will recognise the ones around you. A social feed is an algorithm that ranks posts by how long similar ones kept you watching; your sat-nav runs one that compares thousands of routes in a second; a flight's price changes because an algorithm estimates how much you are willing to pay. None of these is magic and none is neutral: each optimises a goal chosen by someone. The useful question in front of any automated result is always the same: which problem was it solving, and for whom?")],
    },
}
