// PAUSE — Story audio player: shared styles.

import { makeStyles, spacing, radius, typography } from "@/src/theme";

export const useStyles = makeStyles((colors) => ({
  wrap: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.glassBgStrong,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    alignSelf: "stretch",
    gap: spacing.md,
    boxShadow: `0px 8px 22px ${colors.glassShadow}` as any,
  },
  wrapCompact: { marginTop: 0, paddingHorizontal: spacing.sm + 2, paddingVertical: spacing.xs + 2, gap: spacing.sm },
  wrapDense: { flex: 1, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.pill, backgroundColor: colors.glassBg },
  sheetBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)" },
  sheet: {
    backgroundColor: colors.surface, borderTopLeftRadius: radius.lg + 8, borderTopRightRadius: radius.lg + 8,
    paddingHorizontal: spacing.lg, paddingTop: spacing.sm, maxHeight: "85%",
    borderTopWidth: 1, borderColor: colors.border,
  },
  sheetHandle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: colors.borderStrong, marginBottom: spacing.md },
  sheetHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.xs },
  sheetTitleRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  sheetTitle: { color: colors.onSurface, fontFamily: typography.bodyBold, fontSize: 14, letterSpacing: 1 },
  sheetClose: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceSecondary },
  trigger: {
    flexDirection: "row", alignItems: "center", gap: 6, height: 34, paddingHorizontal: spacing.md,
    borderRadius: radius.pill, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.cyan + "66",
    boxShadow: `0px 3px 10px ${colors.cyanGlowSoft}` as any,
  },
  triggerActive: { backgroundColor: colors.cyan + "22", borderColor: colors.cyan },
  triggerText: { color: colors.onGradient, fontFamily: typography.bodyBold, fontSize: 12 },
  playBtnCompact: { width: 38, height: 38, borderRadius: 19 },
  playBtnDense: { width: 34, height: 34, borderRadius: 17 },
  compactHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  fill: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0 },
  mainRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm + 2 },
  playBtn: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  center: { flex: 1, gap: 4 },
  eyebrow: { color: colors.brand, fontFamily: typography.bodyBold, fontSize: 9, letterSpacing: 1.4 },
  subtitle: { color: colors.onSurface, fontFamily: typography.bodyMedium, fontSize: 12 },
  progressTrack: { height: 3, borderRadius: 2, overflow: "hidden", backgroundColor: colors.track, marginTop: 2 },
  progressFill: { height: 3, borderRadius: 2 },
  timesRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 2 },
  time: { color: colors.muted, fontFamily: typography.body, fontSize: 10 },
  expandBtn: {
    width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center",
    backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder,
  },
  expandBtnActive: { borderColor: colors.cyan + "66", backgroundColor: colors.cyanGlowSoft },
  expandedWrap: { gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: spacing.md },
  transportRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm },
  transportBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 3,
    minWidth: 68, height: 38, paddingHorizontal: spacing.md,
    borderRadius: radius.pill, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder,
  },
  transportLabel: { color: colors.onSurface, fontFamily: typography.bodyBold, fontSize: 12 },
  speedBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4,
    minWidth: 74, height: 38, paddingHorizontal: spacing.md, borderRadius: radius.pill,
    borderWidth: 1, borderColor: colors.cyan + "66", backgroundColor: colors.cyanGlowSoft,
    boxShadow: `0px 4px 12px ${colors.cyanGlowSoft}` as any,
  },
  speedBtnActive: { backgroundColor: colors.cyan + "33" },
  speedBtnLabel: { color: colors.cyan, fontFamily: typography.bodyBold, fontSize: 13 },
  toolsRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
  toolChip: {
    flexDirection: "row", alignItems: "center", gap: 5, height: 30, paddingHorizontal: 12,
    borderRadius: radius.pill, borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.glassBg,
  },
  toolChipActive: { borderColor: colors.cyan + "66", backgroundColor: colors.cyanGlowSoft },
  toolChipLabel: { color: colors.onSurfaceSecondary, fontFamily: typography.bodyBold, fontSize: 11, maxWidth: 120 },
  premiumPill: { marginLeft: "auto", flexDirection: "row", alignItems: "center", gap: 3, paddingHorizontal: 7, height: 22, borderRadius: radius.pill, backgroundColor: colors.cyanGlowSoft },
  premiumPillText: { color: colors.cyan, fontFamily: typography.bodyBold, fontSize: 9, letterSpacing: 0.5 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 2 },
  optChip: {
    flexGrow: 1, flexBasis: "22%", height: 34, borderRadius: radius.pill, flexDirection: "row", gap: 4,
    alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.glassBg,
  },
  optChipActive: { backgroundColor: colors.cyan + "26", borderColor: colors.cyan },
  optChipLabel: { color: colors.onSurfaceSecondary, fontFamily: typography.bodyBold, fontSize: 12 },
  optChipLabelActive: { color: colors.cyan },
  voiceList: { gap: 6, marginTop: 2 },
  voiceRow: {
    flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingHorizontal: 10, height: 40,
    borderRadius: radius.md, borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.glassBg,
  },
  voiceRowActive: { borderColor: colors.cyan + "66", backgroundColor: colors.cyanGlowSoft },
  voiceMain: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.sm, height: "100%" },
  voiceLabel: { color: colors.onSurface, fontFamily: typography.bodyMedium, fontSize: 13 },
  sampleBtn: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, height: 28, borderRadius: radius.pill, backgroundColor: colors.surfaceTertiary },
  sampleLabel: { color: colors.onSurfaceSecondary, fontFamily: typography.bodyBold, fontSize: 10 },
  hint: { color: colors.muted, fontFamily: typography.body, fontSize: 11, marginTop: 2 },
  pressed: { opacity: 0.75 },
  listenBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    height: 46, borderRadius: radius.pill, paddingHorizontal: spacing.lg,
    borderWidth: 1, borderColor: colors.cyan + "66", backgroundColor: colors.cyanGlowSoft,
    boxShadow: `0px 0px 16px ${colors.cyanGlow}` as any,
  },
  listenBtnLabel: { color: colors.cyan, fontFamily: typography.bodyBold, fontSize: 14 },
  listenBtnCompact: { height: 54, borderRadius: radius.lg, paddingHorizontal: spacing.lg, backgroundColor: colors.glassBg },
}));
